### ISSUE TITLE
fix for a signed/unsigned mismatch in c++ code

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#1242]
Version: 1.2-current
CUPS.org User: stohr

in pdftops code there was a c++ object that had private members
which were counting pages, but those were unneccessarily defined
as signed numbers. in a few comparisons the "sizeof" operator was
used which is an unsigned type. to eliminate the compilation warning
the private member and a few other local objects were converted to
unsigned types. this should not affect other code.

-Alex.

**Comment by Kodwings22** [comment]
I keep reading a lot of posts when I first get into trouble. This is how I once reached this website (https://kodlogs.net/341/c-signed-unsigned-mismatch) and got the desired solution. You can read this post as well as visit here. I think it will be very useful for you
