### ISSUE TITLE
Wrong paper size for C and POSIX locales

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#1688]
Version: 1.2.0
CUPS.org User: twaugh.redhat

ipp.c:4060:

```
if (!DefaultLanguage ||
    !strcasecmp(DefaultLanguage, "C") ||
    !strcasecmp(DefaultLanguage, "POSIX") ||
    !strcasecmp(DefaultLanguage, "en") ||
    !strncasecmp(DefaultLanguage, "en_US", 5) ||
    !strncasecmp(DefaultLanguage, "en_CA", 5) ||
    !strncasecmp(DefaultLanguage, "fr_CA", 5))
{
 /*
  * These are the only locales that will default to "letter" size...
  */
```

Hey, 'C' and 'POSIX' both use A4:

$ LC_ALL=C locale -k LC_PAPER
height=297
width=210
paper-codeset="ANSI_X3.4-1968"
$ rpm -q glibc
glibc-2.4-4

**Comment by rrthomas** [comment]
The "POSIX" locale is not US-specific. As far as I can see, POSIX itself [does not define](https://pubs.opengroup.org/onlinepubs/9699919799/) `LC_PAPER`. FWIW, `A4` seems a logical "simplest" choice to me. Note that sorting is by byte order in the POSIX locale, which does not match US lexical conventions (for example, sorting upper-case before lower-case).
