### ISSUE TITLE
lpoptions unable to set a basic printer setting

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#1970]
Version: 1.2.2
CUPS.org User: relovett

I'm trying set the default behavior of a spool to be duplex. If I run

  # lpoptions -d pr1 -l

I see, among other things,

  Duplex/2-Sided Printing: *None DuplexNoTumble DuplexTumble

I tried:

  # lpoptions -o Duplex/2-Sided\ Printing=DuplexNoTumble

but that puts

  Default pr1 Duplex/2-Sided=true Printing=DuplexNoTumble

into /etc/cups/lpoptions. I also tried quoting in several ways without success. I then decided to put

  Default pr1 Duplex/2-Sided Printing=DuplexNoTumble

into lpoptions but that had no effect on the actual behavior of the printer. I then tried

  Default pr1 sides=two-sided

but that had no effect either. Using the web interface in the past, I recall you could set this behavior. The web interface would set this by modifying the PPD directly rather than creating/modifying an lpoptions file. The current web interface is giving me trouble (I'll save that for another bug) so I wanted to try the command line. Is this possible at all?

The OS is Ubuntu 6.06.01 running cupsys 1.2.2. I'm using the standard configuration plus LogLevel set to debug.

**Comment by lindes** [comment]
As a data point, I was hitting this too, and my solution was to edit the `/etc/cups/ppd/<my-printer>.ppd` file, making the following change:

```
199c199
< *DefaultDuplex: None
---
> *DefaultDuplex: DuplexNoTumble
```
I don't know if I'll ever be able to print non-duplex or short-edge binding, but at least my 90+% use case is satisfied.  Frustrating that lpoptions wasn't able to do this, though, and even more frustrating that options selected in the print UI from evince (Document Viewer) weren't honored.
