### ISSUE TITLE
Can we print out to IPv6 printer with CUPS1.2.7 ?

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#2234]
Version: 1.2.7
CUPS.org User: haginaka

We'd like to print out from Redhat to the printer(has IPv6 link local
address) on IPv6 network.

Our environment:
*network: 
    shared with both IPv4 and IPv6
*How to get address:
    DHCP
*Which distribution
    Redhat Linux Enterprise WS4(have been changed to IPv6)
*CUPS version into Redhat
    1.2.7
*browser to check CUPS status
    Konqueror

We had confirmed followings for check that our network is OK.
- Linux PC had both IPv4 address and IPv6 address(Link Local address)
  by "ipconfig" command into Terminal.
- This PC doesn't has a global address of IPv6.
- We tried to "ping6" command to itself. we could get reply.
- We tried to the printer(has IPv6 address), we could get reply.
- We tried this line 
  # lsmod | grep ipv6
  we had reply "ipv6  177748  -1". So, maybe IPv6 module is running on
  PC.

---- our try and issue ----
- When we add printer on http://localhost:631 and print out,
  We can't print out and display "Unable to connect to 
  printer; will retry in 30 seconds..." on localhost web page.
- We had been debug backend's code.
  It seems that this line into lpd.c occur error.
  "connect(fd, &(addr->addr.addr), httpAddrLength(&(addr->addr)))"
- We had tried to add printer with this line.
  # lpd://[fe80::xxxx:xxxx:xxxx:xxxx]/q

---- Question ----
1. How should we add printer with LPD and IPv6 address ?
We had tried this line
# lpd://[fe80::xxxx:xxxx:xxxx:xxxx]/q
1. We got CUPSver1.2.7 source code from cups.org site. and compiled,
   install. (./configure ->>  make ->> make install)
   Can we print out with IPv6 without special setting of build before
   compile ?
2. If our build process is correct, How to be available IPv6 into CUPS ?
3. Should we change cupsd.conf file for printing out to IPv6 printer ?

**Comment by talhamughal10** [comment]
Hi can i am working on printing document using printer with socket communication in java android studio. i have printer which has link local address and i am stuck to give it a print command using in link local address. when i use its ipv4 address it prints. how to use ipv6 address to print using socket communication.
