### ISSUE TITLE
Ability to rename a printer queue via web or cli

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#2337]
Version: -feature
CUPS.org User: angelb.bugarin

At the moment there's no simple way to rename a printer queue. If all I
want is to change the name of a printer queue and leave the rest of the
attributes unchanged, currently, I have to delete the queue and readd
it with the new name.

A user should have some way to rename a printer queue either from the web interface or from the command line.

Please remove my request if a simillar one already exist.

Thanks,
Angel

**Comment by sjvudp** [comment]
Actually I don't understand: Today you can rotate videos in real-time, detect faces and fingerprints transform color-spaces, but you cannot rename a printer queue? As it is obviously messy to do by hand, that is a strong indicator that there should be a better way.

**Comment by michaelrsweet** [comment]
@sjvudp The issue is that there isn't an IPP operation to do it (yet), largely because it involves a bunch of security and accounting problems that are not easy to solve.
