### ISSUE TITLE
Support for SELinux context based job banners

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#2476]
Version: -feature
CUPS.org User: mra

Utilizing the Classification setting, banner options were added mls, te,
and selinux.  This patch includes blank banner sheets for these banner types, but they are place holders so that the stored job context can be used to generate the appropriate label.

Choosing selinux would result in the entire SELinux context to be used
as the label: staff_u:sysadm_r:sysadm_lpr_t:SystemLow-SystemHigh

Using te would have a label of: sysadm_lpr_t

And mls would just be: SystemLow-SystemHigh

Also included in this patch is support for a boolean PerPageLabels which
defaults to yes.  When set to no the labels are left off the actual job
output, and only forced on the banner pages.

One concern that our evaluator had was that a significantly complex
SELinux context could extend beyond the width of the page.  For our
evaluation another patch for WriteLabelProlog() in filter/common.c
broke up long labels over multiple lines.  Since the 1.2 release used
in RHEL5 that filter code has changed, but it could be ported if there
is interest.

**Comment by ileyd** [comment]
@michaelrsweet would you be able to edit your comments to encapsulate the patch file in a code block?  I'm interested in those patches. but it's parsed by markdown at the moment and I'm not sure how to recover the original text.

**Comment by michaelrsweet** [comment]
Should be fixed now...

> On Jul 24, 2016, at 2:41 AM, ileyd <notifications@github.com> wrote:
> 
> @michaelrsweet would you be able to edit your comments to encapsulate the patch file in a code block? I'm interested in those patches. but it's parsed by markdown at the moment and I'm not sure how to recover the original text.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

________________________
Michael Sweet
