### ISSUE TITLE
Status of remote IPP jobs cannot be discovered

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#2732]
Version: -feature
CUPS.org User: twaugh.redhat

Currently it is impossible to know whether a job sent to a remote IPP queue is actually still in progress, or if it failed.

The solution is for the IPP backend to act as a proxy for remote IPP jobs.  It needs to maintain a small database of local job IDs to remote job URIs, and to add the following actions:
1. While watching the remote job, if the remote job stops, fetch the remote job-state-reasons and set them locally using an 'ATTR:' stderr output line, and then exit with CUPS_BACKEND_STOP.
2. When the backend is started, if the job ID is already in the database, try to restart the remote job (and re-submit the job if that fails) and then continue to watch the remote job as normal.

This way, it will actually be possible to monitor the state of a remote job.

(See http://cyberelk.net/tim/2008/02/29/print-job-failure-alerts/ for one example of why this is needed: but otherwise just look at http://localhost:631/jobs/ when a remote job has failed.)

**Comment by Sabapathy777** [comment]
Hi Michael,
            I am trying to get bulk "history of previous jobs" in ipp using java ,is there any possibility to get the "previous print history" using ipp?
if yes means how many printed events can i fetch?
How can we save the job logs using cups? is there any implementations? how cups takes the completed status from printer? could you please explain?
Thanks in advance...
