### ISSUE TITLE
Standby/failover printer inside a CLASS

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#2878]
Version: -feature
CUPS.org User: bsavioli

Hello there.

I have searched a lot and haven't found a way of doing this.

This is the scenario:

1 Printer Server
2 Printers
1 Class containing the 2 printers.

With the normal settings, when you send a job using the CLASS, cups will kind of "round robin" or send the job to the first available printer.

Because of the way we work, the order that the document comes out of the printer, it is very important that all jobs use the same printer, unless the first printer is down for some reason.

I reckon adding a possibility to add a priority configuration, or a way to choose the preferable printer or a way of assigning one or more printers in the class with the status of "STAND BY" and only become online when there is a problem with the other printer in the class.

Apologies if this is already possible or if there is a request for this, but I couldn't find a way of doing it.

I believe this would be a useful option for many people.

Thanks

Bruno

**Comment by rodolphedj** [comment]
this feature has been added to CUPS Redhat release.
why it was not forwarded to the CUPS core dev ?


**How can I configure CUPS in RHEL to fail-over from one printer to another**
https://access.redhat.com/solutions/1491303

CUPS have a "failover" backend that will allow fail-over to a backend without sending print jobs to multiple printers in a "round-robin" fashion

lpadmin -p ${master-queue} -v failover:/// -E -o failover-default=ipp://localhost:631/printers/print-queue-1,ipp://localhost:631/printers/print-queue-2

**Comment by michaelrsweet** [comment]
@rodolphedj This backend has not been contributed to the CUPS project, nor would we use this approach since there are performance and privacy issues.
