### ISSUE TITLE
cups-lpd can't suppress form feeds

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#3290]
Version: 1.4-current
CUPS.org User: mabafu

I'm using Ubuntu 9.04 to receive print jobs from a mainframe.

The mainframe sends a LPD job via port 515.

Unfortunatelly the mainframe or cups-lpd adds a form feed after every job, then printing a blank page, and incresaing printing costs.

I did set up the /etc/xinetd.d/cups file according to the cups-lpd man page. I've also tried inserting some fixes into "server-args", like: -o job-sheets=none,none, but it didn't works.

It seems that the "sf" (suppress form feed) option in the "printcap" file of older LPD/LPRng servers could deal with that issue, althought the /var/run/cups/printcap is always overwritten by cups.

Any help would be most welcome.

Tks in advance,

Marcelo

**Comment by knuta** [comment]
For those of you arriving here from Google in a search for a way to stop an extra blank page from appearing in your prints, look into the `SendFF` option, which causes a form feed to be added and is on by default in at least the `texttotext` filter.

You can try disabling it with this command to see if it solves your problem:

```
sudo lpoptions -p MyPrinterQueue -o SendFF=false
```

The resulting setting will wind up in `/etc/cups/lpoptions` or a similar location.
