### ISSUE TITLE
fit-to-page doesn't work with pdf files

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#3376]
Version: 1.4.1
CUPS.org User: cyberpatrol

The option fit-to-page doesn't work with pdf files. If I print pdf files which are bigger than the printable area of my printer (HP DeskJet 960C) they are printed in the original size and the bottom of the page is cut.

This bug was already existing with the option fitplot at least in version 1.3.11.

In earlier versions fitplot worked perfectly with pdf files.

**Comment by ccding** [comment]
have the same issue after almost 10 years

**Comment by mabra** [comment]
Now 14Y later and no changes!
