### ISSUE TITLE
CUPS backend "socket" doesn't return marker(toner) levels for HP 1505n, Pro P1102, xerox 6110n, Samsung CLP-300n and others 

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#3610]
Version: 1.5-feature
CUPS.org User: rickr.mn.rr

CUPS backend "socket" doesn't return marker(toner) levels for HP 1505n, Pro P1102, xerox 6110n, Samsung CLP-300n and others.

The problem is SNMP prtGeneralCurrentLocalization and prtLocalizationCharacterSet do not exist at all.

prtMarkerLifeCount should be a counter but it actually an integer.

Patchincluded.

After Patch:$ ./testsupplies 192.168.1.15
DEBUG2: hrDeviceDesc="HP LaserJet Professional P1102w"
DEBUG: prtGeneralCurrentLocalization type is 5, expected 2!
DEBUG2: prtGeneralCurrentLocalization=0
DEBUG: prtLocalizationCharacterSet type is 5, expected 2!
DEBUG2: prtLocalizationCharacterSet=0
DEBUG2: prtMarkerSuppliesColorantIndex.1.1 = 1
DEBUG2: prtMarkerSuppliesType.1.1 = 3
DEBUG2: prtMarkerSuppliesDescription.1.1 = "Black Cartridge"
DEBUG2: prtMarkerSuppliesMaxCapacity.1.1 = 100
DEBUG2: prtMarkerSuppliesLevel.1.1 = 70
DEBUG2: prtMarkerColorantValue.1.1 = "black"
ATTR: marker-colors=#000000
ATTR: marker-names="Black Cartridge"
ATTR: marker-types=toner
ATTR: marker-levels=70
STATE: -media-low-report
STATE: -media-empty-warning
STATE: -toner-low-report
STATE: -toner-empty-warning
STATE: -door-open-report
STATE: -media-jam-warning
STATE: -input-tray-missing-warning
STATE: -output-tray-missing-warning
STATE: -marker-supply-missing-warning
STATE: -output-area-almost-full-report
STATE: -output-area-full-warning
backendSNMPSupplies: backendSNMPSupplies: PASS (page_count=68, printer_state=3)
DEBUG2: prtMarkerSuppliesLevel.1.1 = 70
ATTR: marker-levels=70
backendSNMPSupplies: backendSNMPSupplies: PASS (page_count=68, printer_state=3)
DEBUG2: prtMarkerSuppliesLevel.1.1 = 70
ATTR: marker-levels=70
^C

$ ./testsupplies 192.168.1.11
DEBUG2: hrDeviceDesc="Xerox Phaser 6110; OS <P6110N_V1.74.01.91 09-29-2006>,
Net <V4.01.05(P6110) 08-22-2006>, Eng <1.01.35>, GDI <5.24 06-28-2006>"
DEBUG2: prtGeneralCurrentLocalization=1
DEBUG2: prtLocalizationCharacterSet=0
DEBUG2: prtMarkerSuppliesColorantIndex.1.1 = 1
DEBUG2: prtMarkerSuppliesColorantIndex.1.2 = 2
DEBUG2: prtMarkerSuppliesColorantIndex.1.3 = 3
DEBUG2: prtMarkerSuppliesColorantIndex.1.4 = 4
DEBUG2: prtMarkerSuppliesColorantIndex.1.5 = 5
DEBUG2: prtMarkerSuppliesColorantIndex.1.6 = 6
DEBUG2: prtMarkerSuppliesType.1.1 = 3
DEBUG2: prtMarkerSuppliesType.1.2 = 3
DEBUG2: prtMarkerSuppliesType.1.3 = 3
DEBUG2: prtMarkerSuppliesType.1.4 = 3
DEBUG2: prtMarkerSuppliesType.1.5 = 9
DEBUG2: prtMarkerSuppliesType.1.6 = 4
DEBUG2: prtMarkerSuppliesDescription.1.1 = "Cyan Toner Cartridge 106R01206"
DEBUG2: prtMarkerSuppliesDescription.1.2 = "Magenta Toner Cartridge 106R01205"
DEBUG2: prtMarkerSuppliesDescription.1.3 = "Yellow Toner Cartridge 106R01204"
DEBUG2: prtMarkerSuppliesDescription.1.4 = "Black Toner Cartridge 106R01203"
DEBUG2: prtMarkerSuppliesDescription.1.5 = "Imaging Unit 108R00721"
DEBUG2: prtMarkerSuppliesDescription.1.6 = "Waste Container 108R00722"
DEBUG2: prtMarkerSuppliesMaxCapacity.1.1 = 1000
DEBUG2: prtMarkerSuppliesMaxCapacity.1.2 = 1000
DEBUG2: prtMarkerSuppliesMaxCapacity.1.3 = 1000
DEBUG2: prtMarkerSuppliesMaxCapacity.1.4 = 2000
DEBUG2: prtMarkerSuppliesMaxCapacity.1.5 = 50000
DEBUG2: prtMarkerSuppliesMaxCapacity.1.6 = 5000
DEBUG2: prtMarkerSuppliesLevel.1.1 = 810
DEBUG2: prtMarkerSuppliesLevel.1.2 = 810
DEBUG2: prtMarkerSuppliesLevel.1.3 = 810
DEBUG2: prtMarkerSuppliesLevel.1.4 = 1640
DEBUG2: prtMarkerSuppliesLevel.1.5 = 49220
DEBUG2: prtMarkerSuppliesLevel.1.6 = -3
DEBUG2: prtMarkerColorantValue.1.1 = "Cyan"
DEBUG2: prtMarkerColorantValue.1.2 = "Magenta"
DEBUG2: prtMarkerColorantValue.1.3 = "Yellow"
DEBUG2: prtMarkerColorantValue.1.4 = "Black"
ATTR: marker-colors=none,none,none,none,none,none
ATTR: marker-names="Cyan Toner Cartridge 106R01206","Magenta Toner Cartridge
106R01205","Yellow Toner Cartridge 106R01204","Black Toner Cartridge
106R01203","Imaging Unit 108R00721","Waste Container 108R00722"
ATTR: marker-types=toner,toner,toner,toner,opc,wasteToner
ATTR: marker-levels=81,81,81,82,98,0
STATE: -media-low-report
STATE: -media-empty-warning
STATE: -toner-low-report
STATE: -toner-empty-warning
STATE: -door-open-report
STATE: -media-jam-warning
STATE: -input-tray-missing-warning
STATE: -output-tray-missing-warning
STATE: -marker-supply-missing-warning
STATE: -output-area-almost-full-report
STATE: -output-area-full-warning
backendSNMPSupplies: backendSNMPSupplies: PASS (page_count=351,
printer_state=3)
^C

**Comment by bittner** [comment]
Erm, sorry, I know this is maybe a weird question, but ...

What is "marker supply" (as in `marker-supply-missing-warning`)? In a multi-function color laser printer, what is it? What does a user need to do or replace?

It's not a marker pen, is it? And it's not one of the CMYK toner cartridges, right? What is it? The fuser, or the imaging unit? The transfer roller or the tray pickup roller it's probably not. -- For non-native speakers an explanation for this seems almost impossible to find. :worried: I'm serious.

**Comment by michaelrsweet** [comment]
Marker supply is toner, ink, and waste tanks - basically anything that is used to put dots on paper.
