### ISSUE TITLE
Support for Zebra Technologies Kiosk Printers in CUPS

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#3767]
Version: -feature
CUPS.org User: mwilner

Request to add support for the following Zebra Technology Kiosk Printers:
TTP20x0 
TTP2130 
TTP7030 
TTP8200
KR403

The latest version to be included is attached to this request. Enclosed is a summary of the changes.

**Comment by olekanderp** [comment]
How setup driver ttp8200 on linux?

**Comment by olekanderp** [comment]
When i compiling i got

/usr/bin/ld: /tmp/ccAKeKze.o: in function `initialize_settings':
rastertozebrakiosk.c:(.text+0x4b8): undefined reference to `get_option_choice_index'
/usr/bin/ld: rastertozebrakiosk.c:(.text+0x4d0): undefined reference to `get_option_choice_index'
/usr/bin/ld: rastertozebrakiosk.c:(.text+0x4e8): undefined reference to `get_option_choice_index'
/usr/bin/ld: rastertozebrakiosk.c:(.text+0x500): undefined reference to `get_option_choice_index'
/usr/bin/ld: rastertozebrakiosk.c:(.text+0x524): undefined reference to `get_option_choice_index'
/usr/bin/ld: /tmp/ccAKeKze.o:rastertozebrakiosk.c:(.text+0x53c): more undefined references to `get_option_choice_index' follow
/usr/bin/ld: /tmp/ccAKeKze.o: in function `job_setup':
rastertozebrakiosk.c:(.text+0xb3c): undefined reference to `output_command'
/usr/bin/ld: rastertozebrakiosk.c:(.text+0xb58): undefined reference to `output_command'
/usr/bin/ld: rastertozebrakiosk.c:(.text+0xb74): undefined reference to `output_command'
/usr/bin/ld: rastertozebrakiosk.c:(.text+0xb98): undefined reference to `output_command'
/usr/bin/ld: rastertozebrakiosk.c:(.text+0xbb8): undefined reference to `output_command'
/usr/bin/ld: /tmp/ccAKeKze.o:rastertozebrakiosk.c:(.text+0xbd4): more undefined references to `output_command' follow
/usr/bin/ld: /tmp/ccAKeKze.o: in function `job_setup':
rastertozebrakiosk.c:(.text+0xbf8): undefined reference to `set_bm_params'
/usr/bin/ld: rastertozebrakiosk.c:(.text+0xc00): undefined reference to `set_loop_length'
/usr/bin/ld: rastertozebrakiosk.c:(.text+0xc2c): undefined reference to `set_sys_params'
/usr/bin/ld: rastertozebrakiosk.c:(.text+0xc34): undefined reference to `set_partial_cut'
/usr/bin/ld: /tmp/ccAKeKze.o: in function `page_setup':
rastertozebrakiosk.c:(.text+0xdbc): undefined reference to `do_reverse'
/usr/bin/ld: /tmp/ccAKeKze.o: in function `end_page':
rastertozebrakiosk.c:(.text+0xe08): undefined reference to `do_advance'
/usr/bin/ld: rastertozebrakiosk.c:(.text+0xe34): undefined reference to `output_command'
/usr/bin/ld: /tmp/ccAKeKze.o: in function `end_job':
rastertozebrakiosk.c:(.text+0xeb8): undefined reference to `output_command'
/usr/bin/ld: rastertozebrakiosk.c:(.text+0xed4): undefined reference to `output_command'
/usr/bin/ld: rastertozebrakiosk.c:(.text+0xee0): undefined reference to `do_eject'
collect2: error: ld returned 1 exit status
