### ISSUE TITLE
access to cups impossible with SSH tunnels

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#3912]
Version: 1.4.3
CUPS.org User: Uqbar

For technical reason I need to print from local CUPS to a remote CUPS printer.
The access is done through an SSH tunnel.
The remote CUPS says:
Request from "localhost" using invalid Host: field "172.16.1.1"

where 172.16.1.1 is a local dummy interface used by SSH to forward traffic to the remote CUPS.
For the sake of completeness, the tunnel is opened from the remote CUPS machine to the local one with a commmand like this:

ssh -C -N -T -R 172.16.1.1:631:127.0.0.1:631 -L 8080:127.0.0.1:631 root@localmachine

I think this very bug is related to this:
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=530027

**Comment by jimduchek** [comment]
Adding this here as this is a major Google result for this issue.  The solution is to add a 2nd loopback address (127.0.0.2 works, but the loopback network is netmask 8 so you have some fun with it), then connect to CUPS using that instead.  It is _insane_ that CUPS _hardcodes_ the 127.0.0.1/loopback matchup, with no configuration setting to fix this.
