### ISSUE TITLE
Please follow the XDG Base Directory spec for user configuration files

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#3937]
Version: -feature
CUPS.org User: wolfy

Could CUPS please follow the XDG Base Directory Specification for the configuration/data directory (~/.cups) on linux./freebsd?
more infos here:
- http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
- http://www.freedesktop.org/wiki/Software/pyxdg
- https://wiki.ubuntu.com/LittleDetails#Use%20XDG%20folders

**Comment by ifohancroft** [comment]
I would like to request for the proposal to be revisited.

**Comment by michaelrsweet** [comment]
No.
