### ISSUE TITLE
Support intermediate certificate authority file

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4039]
Version: -feature
CUPS.org User: relovett

From http://www.cups.org/newsgroups.php?s8+gcups.general+v26+T0+Qcertificate

We were issued a certificate from an InCommon-Comodo service. It is a valid SSL certificate but we need to be able to tell CUPS to look at the intermediate certificates. This is along the lines of apache's SSLCertificateChainFile option.

**Comment by peturbg** [comment]
michaelrsweet you are not going implement to secure the cups server. michaelrsweet why then there is not manuals that explain how peoples can install and configure cups so michaelrsweet for that cups use insecure ciphers. michaelrsweet you can works for apple but apple and nobody have rights to break the law. michaelrsweet if you make cups then tell apple to use your insecure ciphers and be less modificated, and when you write servertokes none they will not be disabled they will show again. michaelrsweet when you start develope your first programs what you said to yourself make the latest and secure. michaelrsweet install cups on your server and use your insecure ciphers and less modified cups configurations. yes we love apache, becouse they are transparency and you can modified all what you want, but again it just confirm the peoples that apple is totaly shit. i will not buy apple anymore and if they try it for free i will not accept from apple, the first company that is robbery, data leaks, fbia, cia, nsa, governments do i need to continue. In the moment im human and im concern becouse i have human rights and this human rights and inviolated by nobody, the law had been created in the past and nobody have the rights to give away humanlife. now my client is open to  robbery, data leaks, fbia, cia, nsa, governments.

**Comment by michaelrsweet** [comment]
@peturbg I'm not sure why you posted this comment to this issue, or why you are so upset with me/Apple? Issue #5037 (concerning insecure ciphers and TLS/1.0, which seems to be the only relevant recent issue) was reported 27 days ago, fixed 25 days ago, and released in CUPS 2.2.4 only 21 days ago. The defaults on all shipping platforms prefer newer TLS versions and cipher suites over older versions and cipher suites, with CUPS controls to explicitly disable TLS/1.0, CBC-based cipher suites, etc.
