### ISSUE TITLE
Broken colour printing on Xerox Workcentre 6015

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4186]
Version: 1.5.3
CUPS.org User: gellert.gyuris

Xerox Workcentre 6015 has an official Xerox driver: http://www.support.xerox.com/support/workcentre-6015/downloads/enus.html?operatingSystem=linux

The colour printing is broken with this driver. See the 1st attachment. The black-white printing works well.

It seams to me it is a CUPS bug, while the driver works well on
- Ubuntu 10.04 (i386) - CUPS 1.4.3
- Ubuntu 11.04 (i386) - CUPS 1.4.6
- Ubuntu 11.10 (i386) - CUPS 1.5.0
  but the colour bug is present on
- Ubuntu 12.04 (i386) - CUPS 1.5.3
- Ubuntu 12.10b1 (i386) - CUPS 1.6.1

Same bug described here: 
- https://bugs.launchpad.net/ubuntu/+source/cups/+bug/984424 
- http://ubuntuforums.org/showthread.php?p=12190974#post12190974
- http://ubuntu.hu/node/30585#comment-351157

**Comment by assolutooccidentale** [comment]
Any news?
i'd like to be able to print images from linux as well....

**Comment by michaelrsweet** [comment]
This isn't a CUPS bug, it is an issue in the cups-filters package provided with the various Linux distros...

**Comment by assolutooccidentale** [comment]
how long do you guess we need to wait in order to have the filters packages fixed?

**Comment by jhonny-oliveira** [comment]
Same problem here! Any progress on this? The printer had a Penguin stamp on it when I bought it, it should work!
