### ISSUE TITLE
Possible problems found by static analysis of code of cups-1.6.1

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4242]
Version: 1.6-current
CUPS.org User: jpopelka

Hello,

we analyzed the cups-1.6.1 code with Coverity - tool for
static analysis.

I'm attaching a tarball of patches.
Each patch contains a relevant snippet from analysis log.
I hope the log line numbers are ok, I changed them to sync with svn repo head.

**Comment by lemonwuhao** [comment]
Hi, Michael
Do you have str4242 patch file. I find that page http://www.cups.org/strfiles/4242/str4242.patch  has been moved.
I need to update these issues. My version is 1.6.1

**Comment by michaelrsweet** [comment]
Copy the patch from the bug comment above. Github offered no way for us to mass-upload the patch files from the old servers...
