### ISSUE TITLE
Support XDG Basedir specification

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4243]
Version: -feature
CUPS.org User: eheintzmann

Please, support FreeDesktop.org XDG Basedir specification

http://ploum.net/post/207-modify-your-application-to-use-xdg-folders
https://live.gnome.org/GnomeGoals/XDGConfigFolders
http://standards.freedesktop.org/basedir-spec/latest/

**Comment by jcrben** [comment]
Allowing the user to set an environment variable would provide complete backwards compatibility.

**Comment by michaelrsweet** [comment]
@jcrben There are security and usability issues with using environment variables for this sort of thing, and it still doesn’t solve the migration or platform issues. So this is still a no...

**Comment by jcrben** [comment]
OK, altho I've got dozens of similar types of environment variables relocating config files already.

It might sound nuts, but clutter like this has pushed me to evaluate returning to Linux.

**Comment by rouing** [comment]
I realize this is old and is labeled "Wont Fix" but is there a chance of re-eval? Many other programs have moved to the Freedesktop spec.

**Comment by sparr** [comment]
This does seem like the sort of decision that deserves revisiting 5+ years later.
