### ISSUE TITLE
Xerox workcentre 6015b wrong colors (it's duplicate but please read)

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4268]
Version: 1.6-current
CUPS.org User: sss123next

i have read few bugs on launchpad and ubuntu bugracker about this issue, i have talked to xerox support which said to use old red hat or old ubunut, i tested myself all available versions of cups (1.4.8, 1.5.2, 1.6.1), i using gentoo system on amd64 machine, and for me it's persistent problem on all cups versions, can you just point me to right direction to solve problem, i have not found what exactly cause this problem, so i do not know what to do to workaround this

**Comment by sven337** [comment]
Using the Xerox Phaser 6020 official driver instead appears to "work" : colors look OK. However, text bleeds a little with that driver, so it still isn't perfect. :(
