### ISSUE TITLE
Add Printer Options to lpr / lp man pages

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4329]
Version: 2.0-feature
CUPS.org User: odyx

Hi Michael,

Christopher Swingley reported the following bug against cups 1.1.23:
http://bugs.debian.org/304504

> It would be convenient to have the printer options (all those things 
> available with -o option) listed in the manual page.  I've attached a 
> patch against lpr.1 that could be applied.  The same code could probably 
> be inserted into the lp manual page.

I have attached his patch here.

Thanks for considering!

**Comment by alxwk** [comment]
I don't understand why for **adding** options the existing lines (like those describing `lpi` or `cpi`) were needed to be deleted, while they are still exist and work. I wasted half a day trying to figure them out, digging up manual pages from a decade ago.
