### ISSUE TITLE
lpr -l (raw printing) broken

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4430]
Version: 1.7.1
CUPS.org User: omvsj

I filed this bug in Mint (https://bugs.launchpad.net/bugs/1327676) but I think is Cups-specific.

I tested in Linux Mint 17 amd64 fresh installed and up-to-date in 3 desktops and 1 laptop.

I tried printing with "lpr -l" and "lpr -o raw" with local (usb-attached) and net printers and got nothing printed. After some research and trying different configs I tried printing to cups-pdf printer.

$ lpr -l somefile.txt

or

$ lpr -o raw somefile.txt

Produces an EMPTY file, with size 2.2 kB: /home/user/PDF/PDF.Pdf

$ lpr somefile.txt

Procduces file with text: /home/user/PDF/somefile.pdf

"lpr -l" and "lpr -o raw" should print files "as is", keeping filename.

**Comment by michaelweghorn** [comment]
This bug is closed now in GitHub. Has it been fixed or was that just an error of the migration to GitHub and the bug still needs to be addressed? As far as I remember, it was not closed before the migration took place.

**Comment by michaelrsweet** [comment]
The bug got closed ("unresolved") back in June of 2014. OdyX's proposed change might make sense, but watch Issue #4782 since that is where we will try to address things...
