### ISSUE TITLE
web user interface -- potentially vulnerable to Clickjacking

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4492]
Version: 2.0.0
CUPS.org User: polymorphm

good day!

this problem:

web user interface -- potentially vulnerable to Clickjacking ( http://i1.minus.com/ibce5VW8VV5oX0.png )

(I used CUPS version 1.7.5)

it will be very very nice, if in HTTP-Headers (on all web-pages of web-ui http://127.0.0.1:631/ ) will be added next two lines:

X-Frame-Options: DENY
Content-Security-Policy: frame-options 'deny'

thanks in advance!

P.S.: sorry for my bad english

**Comment by ecropolis** [comment]
Is there a config setting available if you do want to load in an iframe (of same origin)?

**Comment by michaelrsweet** [comment]
@ecropolis Sorry, no.
