### ISSUE TITLE
HP LJ p1102 doesn't print: media-needed-error always.

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4501]
Version: 1.7.2
CUPS.org User: binow

I tried to print from command line and from c++ cups wrapper and getting same error each time (but there is paper in printer). Printing from other programs (like browser) is ok. 
OS â Mac Os X 10.9.5

**Comment by thiagotalma** [comment]
I remain with this problem.
Has anyone also had it and managed to solve it?

**Comment by Tonguc-Endem** [comment]
I also have this problem.  I can print without any issues from MacOS printer dialog.  But if I go into the CUPS web management and print a test page, it always says "Manual Feed: Load paper in the manual feed tray and press the Go button."  so I just open and close the cartrige door/cover and then it prints.  I need CUPS to be working normally to be able to make the printer an AirPrint printer with a dns-sd -R script.
