### ISSUE TITLE
Implement multi-threaded cupsd

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4511]
Version: -feature
CUPS.org User: alexk

I have a 24 CPU Linux server that serves ~700 printers and ~10000 CUPS clients. cupsd process is occupying 100% of a single CPU, and not making any use of other cores. It is good for filters that can run faster, but bad for regular requests (lots of clients do Get-Printers all the time, get slow response). 

Would be nice if cupsd could use threads more effectively.

This is with CUPS 1.7.5. 

$ pidstat -t -p 15708 1
Linux 3.13.0-37-generic (printserver1)  10/28/2014  _x86_64_    (24 CPU)

03:25:18 PM      TGID       TID    %usr %system  %guest    %CPU   CPU  Command
03:25:19 PM     15708         -   89.00   10.00    0.00   99.00    16  cupsd
03:25:19 PM         -     15708   89.00   10.00    0.00   99.00    16  |__cupsd

**Comment by paolobenve** [comment]
I'd be happy to see this issue solved. Cups printing in libreoffice is always very very very slow for me.

**Comment by michaelrsweet** [comment]
@paolobenve Slow LibreOffice printing isn't caused by a lack of threading support in cupsd - on modern hardware it can easily handle 20k Get-Printer-Attributes requests per second. But regardless any changes in this respect will happen in the [OpenPrinting CUPS](https://github.com/openprinting/cups) project and not here...
