### ISSUE TITLE
cups.css file is detected on Linux as x-csource, not text/css

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4593]
Version: 2.0.2
CUPS.org User: alexk

When i compile and install CUPS 2.0.2 on Ubuntu 12.04, its web interface is broken because cups.css doesn't load. 

Browser says: The stylesheet https://printserver/cups.css was not loaded because its MIME type, "application/x-csource", is not "text/css".

$ file -l /usr/share/cups/doc-root/cups.css 
<snip>
Text patterns:
Strength = 250 : Tenex C shell script text executable [text/x-shellscript]
Strength = 250 : new awk script text executable [text/x-nawk]
Strength = 250 : GNU awk script text executable [text/x-gawk]
Strength = 250 : Bourne-Again shell script text executable [text/x-shellscript]

CUPS reports the same mime type in error log:
D [23/Feb/2015:18:31:07 +0000] [Client 48] filename="/usr/share/cups/doc-root/cups.css", type=application/x-csource
D [23/Feb/2015:18:31:07 +0000] [Client 48] cupsdSendHeader: code=200, type="application/x-csource", auth_type=0

Removing /\* Layout CSS */ comment from the top of the cups.css file workarounds the problem.

**Comment by jraschke** [comment]
Hi

JFYI :
I got this css-error after debian dist upgrade  jessie --> stretch.
Reason:   very old mime.types in /etc/cups as Mike guessed above

Gruss,
Juergen

**Comment by Jaleks** [comment]
Still present for me in Debian 9 and CUPS version 2.2.1-8+deb9u3. Manually removing `mime.types` and `mime.convs` files from `/etc/cups` (like suggested in [Debian Bug report logs - #792731](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=792731#29)) let the CUPS admin web interface use the CSS like expected (after a `cupsd` restart) again.

**Comment by Sprinterfreak** [comment]
# Remove files
rm /usr/share/cups/mime/mime.convs /usr/share/cups/mime/mime.types
rm /etc/cups/mime.convs /etc/cups/mime.types
# Copy system-wide mime.types to cups. Otherwise all ist text/plain and page won't display either.
cp /etc/mime.types /etc/cups.mime.types
systemctl restart cups
