### ISSUE TITLE
Mac cgpdftops creates bad PostScript output for Cyrillic PDF document

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4607]
Version: 1.7.2
CUPS.org User: alexk

Discovered on Mavericks (10.9, CUPS 1.7.2). 

When attached PDF with Cyrillic fonts is printed on a Mac, Cyrillic characters are not rendered correctly. 

The first called filter, cgpdftops, creates a PS file that cannot be parsed by Adobe Distiller, GhostScript, or printer PS engine. 

Here is the output of Distiller:

Start Time: Tuesday, March 17, 2015 at 11:50:12
Source: cgp2.ps
Destination: cgp2.pdf
Adobe PDF Settings: C:\ProgramData\Adobe\Adobe PDF\Settings\High Quality Print.joboptions
%%[ Error: invalidfont; OffendingCommand: xshow; ErrorInfo: MetricsCount --nostringval-- ]%%

Stack:
-dict-
-file-

%%[ Flushing: rest of job (to end-of-file) will be ignored ]%%
%%[ Warning: PostScript error. No PDF file produced. ] %%
Distill Time: 00 Hour(s) : 00 Minute(s) : 00.109 Second(s)
***\* End of Job ****

Here is the output of GS:

gs /tmp/cgp2.ps 
GPL Ghostscript 9.05 (2012-02-08)
Copyright (C) 2010 Artifex Software, Inc.  All rights reserved.
This software comes with NO WARRANTY: see the file PUBLIC for details.
GPL Ghostscript 9.05: Error: Font Renderer Plugin ( FreeType ) return code = -10
GPL Ghostscript 9.05: Error: Font Renderer Plugin ( FreeType ) return code = -10
Can't render Font INRIXH+AA0102+Arial with FAPI, will do with native GS renderer.
Can't render Font F1.1 ( aliased from INRIXH+AA0102+Arial ) with FAPI, will do with native GS renderer.
Error: /rangecheck in --xshow--
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1910   1   3   %oparray_pop   1909   1   3   %oparray_pop   1893   1   3   %oparray_pop   1787   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--
Dictionary stack:
   --dict:1160/1684(ro)(G)--   --dict:0/20(G)--   --dict:78/200(L)--   --dict:90/141(L)--
Current allocation mode is local
Last OS error: No such file or directory
Current file position is 201751
GPL Ghostscript 9.05: Unrecoverable error, exit code 1

Poppler's pdftops and pdftocairo filters on Linux can process the original PDF just fine. GS on Linux can convert this PDF to PS just fine, too. Only cgpdftops on Mac is affected. 

Original file contract-p2.pdf is attached.
Resulting cgp2.ps file is also attached.

**Comment by william8000** [comment]
If cgpdftops is based on poppler pdftops, this might fix the "/rangecheck in --xshow--" error
https://bugs.freedesktop.org/show_bug.cgi?id=63963

**Comment by michaelrsweet** [comment]
cgpdftops is based on CoreGraphics (thus the "cg" prefix). We do not use poppler or Xpdf.
