### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4671]
Version: 2.1b1
CUPS.org User: elfring

I guess that a different program design will be needed for your function "sigterm_handler".
- Variables like "abort_job" and "job_canceled" should use the data type "sig_atomic_t", shouldn't they?
- The functions "exit" and "fprintf" do not belong to the list of async-signal-safe functions.
  https://www.securecoding.cert.org/confluence/display/seccode/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers

**Comment by elfring** [comment]
Will the mentioned implementation details get another look?

**Comment by michaelrsweet** [comment]
[master 9880f81] Don't call exit() from signal handler (Issue #4671)

**Comment by elfring** [comment]
Thanks for [another small source code improvement](https://github.com/apple/cups/commit/9880f818cf9facbb0c62651472c48f7e6f08a0ea "Don't call exit() from signal handler").
