### ISSUE TITLE
Investigate further error handling and annotation improvements

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4672]
Version: -feature
CUPS.org User: elfring

I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.
http://cwe.mitre.org/data/definitions/252.html

Would you like to add more error handling for return values from functions like the following?
- ippNewRequest â cupsGetDevices, httpAssembleURI
- sigaction â main

**Comment by elfring** [comment]
* Where did you store the files which were attached in the previous bug report since August 2015?
* How will corresponding software evolution be continued?

**Comment by michaelrsweet** [comment]
In answer to your first question, since Github does not have a way to import attachments into their issue tracking system yet, anything that was not identified as a simple unified diff were lost in the transition over to Github.

I don't understand your second question - all we have done is move CUPS over to Github, but the same people are working on it and the same development process is in use.  The only change that Github brings is the concept of a "pull request" which is (for some) an easier way for contributors to provide patches to the project, but those are incorporated using the same development process on our end (i.e. same as if you sent us a unified diff).

**Comment by elfring** [comment]
>…, since Github does not have a way to import attachments into their issue tracking system yet,

Were the corresponding interfaces improved a bit for [the management of attachments](https://github.com/blog/2061-attach-files-to-comments "Attach files to comments") in the meantime?


>anything that was not identified as a simple unified diff were lost in the transition over to Github.

I attach the archive (from 2015-08-11) again:
[source_code_analysis1.zip](https://github.com/apple/cups/files/348242/source_code_analysis1.zip)

Do you get further ideas from such files which I generated with the help of the asterisk functionality from [the Coccinelle software](http://coccinelle.lip6.fr/ "Source code transformation engine")?

**Comment by michaelrsweet** [comment]
After review we have decided not to address this issue.

**Comment by elfring** [comment]
I would appreciate a bit more constructive feedback.
How long are you going to [keep exception handling incomplete](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") in your software?
