### ISSUE TITLE
Remove unnecessary NULL pointer checks

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4673]
Version: -feature
CUPS.org User: elfring

Some extra null pointer checks are not needed at specific source code places here.
http://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first

Would you like to apply the following semantic patch to find more update candidates?
http://coccinelle.lip6.fr/

@Remove_unnecessary_pointer_checks@
expression x;
@@
-if (x)
    free(x);

**Comment by elfring** [comment]
Will the shown implementation details get another look?

**Comment by michaelrsweet** [comment]
This is very low priority work that will require a significant amount of regression testing to ensure that we don't break platforms that currently work. The issue is open but will not happen for 2.2.

**Comment by elfring** [comment]
How are the chances that you can rerun corresponding Coccinelle scripts also in your own development environment when the interest might increase for improvements also around software efficiency?

**Comment by michaelrsweet** [comment]
After review we have decided not to address this issue.

**Comment by elfring** [comment]
I am surprised that you would not like to integrate this update suggestion.
Do you really prefer to preserve unnecessary NULL pointer checks in the affected source code forever?
