### ISSUE TITLE
URL for remote printing networks

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4688]
Version: 2.0-current
CUPS.org User: genemosher

When I need to manage a remote printing network I first open a terminal and type
ssh -L 6310:localhost:631 root@remoteip

Then I type localhost:6310 into my browser's URL and go to work on the remote printing network as if I were there.

The bug in this scenario is that if I modify a printer on the remote network, upon completion of the operation, the url forgets that I'm on a remote network and instead of keeping me on 6310, it returns me to 631, and I have to put the 0 back in the url address to return to the remote network.

It is wonderful and amazing to be able to set up and manage remote CUPS networks, except for this inconvenient bug.

**Comment by h-k-h** [comment]
I am encountering this problem too.
However I came across some information that may invalidate the argument for closing this bug:
In https://en.wikipedia.org/wiki/URL_redirection I find the following information
HTTP/1.1 allows for either a relative URI reference or an absolute URI reference.[8]
Ref [8] is https://tools.ietf.org/html/rfc7231#page-68 
Roy T. Fielding; Julian F. Reschke, eds. (June 2014). "Location". Hypertext Transfer Protocol (HTTP/1.1): Semantics and Content. IETF. p. 68. sec. 7.1.2. RFC 7231.

**Comment by michaelrsweet** [comment]
@h-k-h I don't think you understand.

This isn't about Location: redirects, it is about hyperlinks generated by the CUPS web interface for remote printer URLs. We cannot provide a usable URL when tunneling over SSH because cupsd has no idea what address or port number(s) are being used in the mapping.

**Comment by h-k-h** [comment]
May be I do not understand. However I did some reading in RFC 2396 to improve.
I guess the entire application - usually addressed using http://localhost:631 - has no need to ever change the authority component of the URL . Only the path component and query component of the URI/URL i.e. relativeURI = abs path | rel path should be used throughout the application. If it was like this we wouldn't have this discussion. For most parts of the application this seems to be true - it works fine. Only in a special case we have a problem...
Please show the source code snippet where the "absolute Redirection" is required or what ever you think could help me understand ...
Regards
