### ISSUE TITLE
French language not supported

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4731]
Version: 2.0-feature
CUPS.org User: patdealt

French interface is missing in cups-2.

seen in Mageia version 5 with packages :
cups-2.0.4-1.1.mga5
cups-common-2.0.4-1.1.mga5

French interface was available in cups version 1.

Affects several Linux-OS such as Fedora.

**Comment by LAfricain** [comment]
Please can you give the solution? Why this post is closed cups is still in English today on Ubuntu 16.04.
I would be very interesting to know the solution and to help if need.

**Comment by LAfricain** [comment]
Hello
@papoteur-mga, what are you waiting. I think it is possible to translate help.
