### ISSUE TITLE
CUPS driver for Zebra LP 2824 Plus on Mac OS X 10.11 doesn't print as previewed

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4751]
Version: -feature
CUPS.org User: blasto333

CUPS driver for Zebra LP 2824 Plus on Mac OS X 10.11 doesn't print as previewed. In Chrome the label shows up correctly in print preview as taking up one label. When printed it prints the wrong direction (rotated 90 degrees) and over 2 labels.

**Comment by frazhome** [comment]
hello blasto333,

maybe you have problems with autorotation of the label.

try to disable it with
lpoptions -p <queuename>  -o pdfAutoRotate=false

@michaelrsweet is it possible to show this propertie at the webinterface?

it is not easy to check this settings after month :-(

**Comment by VeronicaZCS** [comment]
Hi
I Have the same problem with my Mac OS X 10.11 and my SATO CG412TT label printer. 
I tried "lpoptions -p -o pdfAutoRotate=false", but it doens't work.  What can I do? Thanks

**Comment by michaelrsweet** [comment]
pdfAutoRotate is specific to Linux, and is not a standard IPP attribute (which is what the web interface shows).

This sounds like it is a Chrome printing bug and not something we can fix in the driver.
