### ISSUE TITLE
Change Default ErrorPolicy to abort-job

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4757]
Version: -feature
CUPS.org User: solutions

The default error policy, unless modified by the user in cupsd.conf, is stop-printer.

In the default configuration, this means that if there is an error, the local cups printer will automatically be stopped. Resuming the printer requires manual intervention; even if the printer subsequently reports that it is working, users are unable to print unless the resume the printer.

This is a little bit counter intuitive; if a user job automatically causes a printer error and stoppage - the generally needs to be resolved by an administrator - why doesn't cups automatically resume when the printer reports good health?

Alternatively, why doesn't it simply abort the job?

The only use case we might see this being of benefit would be in a large networked printer environment. But in this case, there would be a very limited amount of machines that need to be configured (especially as the client machines would likely only see a "single" virtual printer).

This is especially frustrating for two reasons:

1) Cups doesn't recognize a difference between a filter error (or something caused by a malformed pdf) vs an out-of-paper or any other kind of error, instead choosing to stop the printer whenever something might possibly go wrong. Why not abort the job instead? (Holding the job might causes people to print the same thing multiple times, but is an equally valid option).

2) For individual or small network users using a remote printer, this can cause the local cups printer to stop, even though it may work for everyone else. This is, again, a frustrating default to keep.

Judging from the number of web results, this seems to be a common problem.

Rather than configuring every single computers cupsd.conf file with a new ErrorPolicy directive, can we instead change the internal default to "abort-job" in order to provide a more useful out-of-box experience for more users?

**Comment by OdyX** [comment]
In Debian, we have now changed the default ErrorPolicy to be `retry-job` with the following patch:
```
Description: Set default job error policy to "retry-job", since it is less
 confusing and a better default on most machines.
 .
 Amend documentation accordingly.
Author: Martin Pitt <martin.pitt@ubuntu.com>
Author: Didier Raboud <odyx@debian.org>
Origin: vendor
Last-Update: 2016-07-03

--- a/scheduler/conf.c
+++ b/scheduler/conf.c
@@ -785,7 +785,7 @@
   cupsdSetString(&LPDConfigFile, CUPS_DEFAULT_LPD_CONFIG_FILE);
   cupsdSetString(&SMBConfigFile, CUPS_DEFAULT_SMB_CONFIG_FILE);
 
-  cupsdSetString(&ErrorPolicy, "stop-printer");
+  cupsdSetString(&ErrorPolicy, "retry-job");
 
   JobHistory          = DEFAULT_HISTORY;
   JobFiles            = DEFAULT_FILES;
@@ -1307,8 +1307,8 @@
       strcmp(ErrorPolicy, "retry-job") &&
       strcmp(ErrorPolicy, "stop-printer"))
   {
-    cupsdLogMessage(CUPSD_LOG_ALERT, "Invalid ErrorPolicy \"%s\", resetting to \"stop-printer\".", ErrorPolicy);
-    cupsdSetString(&ErrorPolicy, "stop-printer");
+    cupsdLogMessage(CUPSD_LOG_ALERT, "Invalid ErrorPolicy \"%s\", resetting to \"retry-job\".", ErrorPolicy);
+    cupsdSetString(&ErrorPolicy, "retry-job");
   }
 
  /*
--- a/doc/help/man-cupsd.conf.html
+++ b/doc/help/man-cupsd.conf.html
@@ -99,11 +99,11 @@
 <dt><a name="ErrorPolicy"></a><b>ErrorPolicy abort-job</b>
 <dd style="margin-left: 5.0em">Specifies that a failed print job should be aborted (discarded) unless otherwise specified for the printer.
 <dt><b>ErrorPolicy retry-job</b>
-<dd style="margin-left: 5.0em">Specifies that a failed print job should be retried at a later time unless otherwise specified for the printer.
+<dd style="margin-left: 5.0em">Specifies that a failed print job should be retried at a later time unless otherwise specified for the printer. The 'retry-job' error policy is the default.
 <dt><b>ErrorPolicy retry-this-job</b>
 <dd style="margin-left: 5.0em">Specifies that a failed print job should be retried immediately unless otherwise specified for the printer.
 <dt><b>ErrorPolicy stop-printer</b>
-<dd style="margin-left: 5.0em">Specifies that a failed print job should stop the printer unless otherwise specified for the printer. The 'stop-printer' error policy is the default.
+<dd style="margin-left: 5.0em">Specifies that a failed print job should stop the printer unless otherwise specified for the printer.
 <dt><a name="FilterLimit"></a><b>FilterLimit </b><i>limit</i>
 <dd style="margin-left: 5.0em">Specifies the maximum cost of filters that are run concurrently, which can be used to minimize disk, memory, and CPU resource problems.
 A limit of 0 disables filter limiting.
--- a/man/cupsd.conf.man.in
+++ b/man/cupsd.conf.man.in
@@ -148,13 +148,13 @@
 Specifies that a failed print job should be aborted (discarded) unless otherwise specified for the printer.
 .TP 5
 \fBErrorPolicy retry-job\fR
-Specifies that a failed print job should be retried at a later time unless otherwise specified for the printer.
+Specifies that a failed print job should be retried at a later time unless otherwise specified for the printer. The 'retry-job' error policy is the default.
 .TP 5
 \fBErrorPolicy retry-this-job\fR
 Specifies that a failed print job should be retried immediately unless otherwise specified for the printer.
 .TP 5
 \fBErrorPolicy stop-printer\fR
-Specifies that a failed print job should stop the printer unless otherwise specified for the printer. The 'stop-printer' error policy is the default.
+Specifies that a failed print job should stop the printer unless otherwise specified for the printer.
 .\"#FilterLimit
 .TP 5
 \fBFilterLimit \fIlimit\fR

```

**Comment by michaelrsweet** [comment]
I don't see us changing the default we ship to either abort-job or retry-job. We provide a choice for a reason, and after careful consideration we won't be making either change to the main CUPS sources.

The problem with abort-job is that it gives up too quickly, which is not the best solution for users.

The problem with retry-job is that it can make the (unfortunately common) wrong driver failure even worse (more spewed pages), and will hide a DoS of a printer when the issue is that the PDL is crashing the printer's interpreter and causing the printer to reboot.

"hold-job" might be an interesting compromise - then the job isn't immediately tossed nor retried, and subsequent jobs can continue without stopping the queue.

But for now we want to stick with "stop-printer" as the default, out of the box policy. This yields a user notification on most platforms so that the user can act accordingly.

**Comment by imsedgar** [comment]
Michael, you write that with "stop-printer" as the default, this yields a user notification on most platforms so that the user can act accordingly. This may be appropriate for a single user system when the printer is only for personal use. But in a networked, administrated environment (for example university environment), even if users are notificated, they usually have no rights to re-enable the stopped printer queue. They can do nothing but wait for an administrator that can re-enable the printer queue. Users can clear paper jam or some other reason that may cause stop the printer - but the printer queue remains disabled, the printer queue doesn't re-check periodically if the printer is ready again. 

This is a big fail of cups!

Everything which could be done automatically should be done this way. If the printer queue was enabled by an administrator at some time, it should stay in this state. Why do you think it is worth that an administrator should be enter an admin command (and the users have to wait for this), as cups can detect the printer ready state itself?

**Comment by michaelrsweet** [comment]
Edgar,

Most systems running CUPS are desktops, with users in control of the print queues. Recognizing that some people do still run print servers (by far the minority), we provide a configuration option (both a global default and the per-printer setting) to choose an alternate policy.

That said, all of these error policies only kick in if the backend exits with status 1 (error happened, use default policy), which (for the standard CUPS backends) only happens in exceptional situations that cannot be automatically retried because it requires administrative attention. (It is possible that some third-party backends do not follow the CUPS guidelines, thus the error policy setting...)

**Comment by james-portman** [comment]
I just wanted to say, this is still really annoying.
Making someone have to resume a printer because one job failed is an extremely annoying default

**Comment by OdyX** [comment]
@james-portman See https://github.com/OpenPrinting/cups/commit/956623c7efe5dbbf7a95fed1089fc15a96c6d76f from [OpenPrinting/cups](https://github.com/OpenPrinting/cups/) (available in 2.3.3op1).

**Comment by dmitrydonskih** [comment]
I agree with @james-portman , I also find this annoying.
Why not add a configuration directive **DefaultErrorPolicy** and use its value as default for new printers?

**Comment by michaelrsweet** [comment]
@dmitrydonskih OpenPrinting CUPS supports the "ErrorPolicy" directive in cupsd.conf to specify the default error policy for new printers.
