### ISSUE TITLE
allow setting of default user name from per instance options

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4764]
Version: 2.1.2
CUPS.org User: vdanjean

Hi,

  When submitting a work to remote printer, if I'm not misleading, the user is the '-U' option of 'lp', the value of "User" setting in client.conf (cf #3114), the value of the CUPS_USER environment variable.

  All these settings are global for a user session at least (can be even global for all users on a computer if the "User" setting is used in /etc/cups/client.conf)

  With cups/ipp more and more widespread, it is common to have a laptop that must integrate into different enterprise networks (not at the same time), in which the remote user to use is different. For example, for myself, I've the 'vdanjean' local login, I must use the 'danjean' remote user in one of my two workplace and 'danjeanv' remote user in the other one...
  As I do not reboot not even logout/loging when I move between theses locations, I cannot use the environment variable. So I must change the cups/client.conf file each time (or manually use the 'lp' command with the '-U' option). 

  It would be very interesting if the default remote user can be configured per local user and per printer (or even per instance as some systems use the username to select a remote queue...)
  At least, 'lp' should be able to use a user specified by destination/instance in lpoptions.
  It would be better if most (all ?) cups config dialog in applications also allow to choose the remote user to use.

  Regards,
   Vincent

**Comment by mystifico** [comment]
@michaelrsweet : Do you still have this solution. We have an issue with out University print system which requires that the username sent by cups to a remote printer is a specific name but not all users have the correct name set as system username. I believe that your fix here takes care of it but cannot find the file.

**Comment by michaelrsweet** [comment]
@mystifico There was no solution to this issue aside from using IPP or SMB with authentication to get the proper user name. The original reporter had come up with a backend script to wrap all print requests and convert the local user name to the corresponding server user name, but that isn't something that CUPS supports natively nor is it authenticated for purposes of identification.
