### ISSUE TITLE
CUPS Webinterface Kerberos

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4776]
Version: 1.7.5
CUPS.org User: kutfejbela

I set DefaultAuthType to Negotiate.
When I connect to the Web Interface and try to add, modify, delete a printer I got error message: "Unauthorized. Enter your username and password or the root username and password to access this page. If you are using Kerberos authentication, make sure you have a valid Kerberos ticket."
When I connect with system-config-printer everything OK, I can manage printers and classes.
With Basic AuthType my user can admin printers and classes.
I set up an apache server on the same host and kerberos authentication is works.

**Comment by michaelrsweet** [comment]
Well, "host" is all that works for Windows... In any case, you can use the GSSServiceName configuration directive in client.conf and cupsd.conf to force a particular value.

**Comment by kato223** [comment]
Too bad this got closed.  It is a simple answer.  

In your address bar, type in:

http://localhost:631/admin/login

Then it will ask for your username and password and allow for full printer administration for that session of CUPS.
