### ISSUE TITLE
Intermec PC43t prints only the first job, usb-no-reattach-default=true solves the issue

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4780]
Version: 1.7.2
CUPS.org User: sysmatck

I had a bad time until I get this printer working. In the beggining I could not set it up because bad commands makes the printer freeze. After strugling for about a week I found the ideal combination of driver and configurations, but the printer was printing only the first job sent, after this it won't accept anymore.

I installed the Intermec CUPS drivers (version 1.2-56) available at: http://apps.intermec.com/EFulfillment/SoftwareListForm.aspx?SoftwareID=3149

Searching for syslog I found that the printer was disconnecting after a job sent. "DebuggingPrintingProblems" Ubuntu Wiki Page helped me to solve the issue. After installing the printer, I ran (lpstat -p -d) to find the printer name, then (lpadmin -p Intermec-PC43t-203-FP -o usb-no-reattach-default=true) to fix the disconnecting behaiver.

On research I found that is possible to fix the issue also editing the file (/usr/share/cups/usb/org.cups.usb-quirks) but I will wait untill a fix is released, probably using this configuration file.

I'm now using Direct Protocol with specific PC43t drivers (not generic Intermec drivers) and everything is working properly. I also reported this problem to Launchpad (https://bugs.launchpad.net/ubuntu/+source/cups/+bug/1553494).

$ lsusb
Bus 008 Device 003: ID 067e:0042 Intermec Technologies Corp.

**Comment by tillkamppeter** [comment]
The current GIT state of CUPS has already a quirk rule to add no-reattach to all Intermec printers, so the bug is already fixed in current CUPS.
