### ISSUE TITLE
Xerox WorkCentre 3220 needs usb-no-reattach-default=true

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#4789]
See

https://bugs.launchpad.net/ubuntu/+source/cups/+bug/1406203

The Xerox WorkCentre 3220 needs a USB quirk rule to set no-reattach.

lsusb gives:

Bus 001 Device 002: ID 0924:4294 Xerox

The following needs to get added to the backend/org.cups.usb-quirks file:

# Xerox WorkCentre 3220 https://bugs.launchpad.net/bugs/1406203
0x0924 0x4294 no-reattach

See also the patch attached to the Ubuntu bug report which does exactly this.

**Comment by michaelrsweet** [comment]
Fixed.

[master 5925ce3] Add USB quirk rule for Xerox WorkCentre 3220 (Issue #4789)
[branch-2.1 0417631] Mirror fix from master.
