### ISSUE TITLE
remove adding document-name from cups-lpd

### ISSUE THREAD

**Issue by frazhome** [apple/cups#4790]
since cups 1.6 this attribute throws warnings at error_log.

remove the code 
  if (docname[0])
    ippAddString(request, IPP_TAG_OPERATION, IPP_TAG_NAME, "document-name",
                 NULL, docname);

at cups-lpd.c line 364 .

**Comment by michaelrsweet** [comment]
What warning are you seeing? Because document-name is a valid attribute and I do not see any code that would specifically warn about its use...

**Comment by frazhome** [comment]
each printjob received via lpd create such a message:
W [21/Mar/2016:09:27:01 +0100] Unexpected 'document-name' operation attribute in a Create-Job request.

http://marc.info/?l=cups&m=134556471411674&w=2

this message is created at  cups/scheduler/ipp.c 
'create_job()' - Print a file to a printer or class.
Line 5124 - 5200

**Comment by michaelrsweet** [comment]
Fixed.

[master 961a8a3] The cups-lpd mini-daemon incorrectly included the document-name attribute when creating a job.  It should only be included when sending a job (Issue #4790)

[branch-2.1 4cc64a8] Mirror fix from master.
