### ISSUE TITLE
Assertion `*_head == _item` failed in avahi_entry_group_free

### ISSUE THREAD

**Issue by OdyX** [apple/cups#4793]
Hi Mike,

this cupsd SIGABRT has been reported in multiple different forums:

- https://bugs.launchpad.net/ubuntu/+source/cups/+bug/1495276
- https://bugs.launchpad.net/ubuntu/+source/cups/+bug/1442169
- https://github.com/apple/cups/issues/4719
- https://bugs.debian.org/818694

Sam Morris provided a full backtrace in the Debian bug above. I don't experience this bug, and can't reproduce it either, unfortunately. Do you need any more logs for this?

Cheers, OdyX

**Comment by michaelrsweet** [comment]
As noted in Issue #4719, unless you can contribute a fix we can do nothing here. This looked like a race condition in Avahi itself but I a) cannot reproduce myself and b) do not have the time to spend on tracking this down further myself.
