### ISSUE TITLE
lp man page should fully document -o options

### ISSUE THREAD

**Issue by archenemies** [apple/cups#4794]
I know of several options which are useful, and parsed by `lp`, however they are not listed in the manual page `lp(1)`:

    -o page-ranges=N..M
    -o page-set={odd,even}
    -o outputorder=reverse

**Comment by michaelrsweet** [comment]
These are already documented in the online help, but will consider adding more to the man pages...

**Comment by archenemies** [comment]
Thank you, that would be great. The man page could also mention that the options it lists are not comprehensive, and link to the online help. But I feel it would be better to actually add the documentation to the man page. Consulting the man page is a good deal faster and easier, at least for me.

**Comment by michaelrsweet** [comment]
[master 40df01c] Add common options to lp/lpr man pages (Issue #4794)
