### ISSUE TITLE
when cancelling a job in web interface, please take me back to the jobs listing

### ISSUE THREAD

**Issue by archenemies** [apple/cups#4795]
Cancelling many jobs via the web interface is tedious because every time I cancel one, the Cups browser takes me to a new page. The new page only contains a message saying that the job was cancelled. I would prefer for the Cups browser to just reload the jobs listing, perhaps with this 'job cancelled' message going on top of the listing, so that I can cancel multiple jobs without having to hit "back" each time. Thanks.

**Comment by archenemies** [comment]
Also, I notice there are other places where the web interface has similar issues, for instance when I select "Administration > Set Default Options", then click the button "Set Default Options", a new page loads saying

    Printer [printer name] default options have been set successfully.

After a few seconds, this page redirects to the printers page. Such UI design is disorienting and unconventional. I think users would prefer and expect that clicking the "Set Default Options" button should keep them on the same page. It's easy enough to indicate that the options have been set successfully via a header on this page. This would be especially preferable since the options come in three groups, "General", "Banners", and "Policies"; a user who modifies an option under "General" would probably want to click on the other two groups to see what else might need to be changed. Instead he is taken somewhere else, and has to hit the "Back" button.

**Comment by michaelrsweet** [comment]
Will bring this up with our HI folks but don't expect any quick changes (if we make any - the web interface is not a high priority and isn't intended as the primary UI...)

**Comment by jgrumboe** [comment]
just curiosity: what is the intended primary UI?

**Comment by michaelrsweet** [comment]
@jgrumboe The OS-supplied UI is primary, the web UI is a "backup" for remote admin (and one that we'd very much like to get rid of)...

After review, we've decided that we are not going to address this specific issue...

**Comment by jgrumboe** [comment]
@michaelrsweet thx for your answer.
Sad to hear that you wanna get rid of the web-ui. I do understand that for client/desktop usage of CUPS it is not important and that a OS-supplied UI is available.
But what about central CUPS printservers, where the support-team has no linux/cmdline knowledge (or either access) and a web UI is "mission-critical"?

**Comment by michaelrsweet** [comment]
@jgrumboe We are constrained by the HTTP server capabilities of cupsd and the security issues that come with using a single server to manage both web and IPP traffic. For now we've adopted a "disabled by default" policy, but longer term we want a different solution for headless servers.

Personally I'd prefer to see a CUPS web interface running from Apache (or some other dedicated web server) that can also serve as a front-end for other management interfaces (Mailman, etc.) typically provided with servers.

**Comment by jgrumboe** [comment]
@michaelrsweet OK, the plan sounds good and i do understand your concerns with managing web and IPP traffic.
Do you know any web-interface replacement running on Apache/... (outside of cupsd)?

**Comment by michaelrsweet** [comment]
I know of some NAS solutions that have some basic CUPS support in them, but otherwise no.

(FWIW, the CUPS web interface isn't going away soon, but we also are not investing a lot of development effort into it - bug fixes and simple changes only)
