### ISSUE TITLE
[cups] Brazilian Portuguese (pt_BR) translation for 2.1.2 

### ISSUE THREAD

**Issue by josephgbr** [apple/cups#4796]
As requested in #4768, here is the tarball containing the translation files. Let me know if any other problem come up.
[pt_BR.tar.gz](https://github.com/apple/cups/files/192014/pt_BR.tar.gz)

**Comment by michaelrsweet** [comment]
Thanks!

**Comment by michaelrsweet** [comment]
[master abc9d50] Add Brazilian Portuguese localization (Issue #4796)
