### ISSUE TITLE
Ubuntu 14.4 and MFC 240c will not work

### ISSUE THREAD

**Issue by oo7vin** [apple/cups#4797]
I have done this many times, but now I have 64 bit and a more updated ubuntu. Can not get it to work.
I get my drivers from here.
 [](http://support.brother.com/g/b/downloadlist.aspx?c=us&lang=en&prod=mfc240c_all&os=128)
Any help? I have looked all over got none even went to Chaletos forum no response as of yet.

**Comment by michaelrsweet** [comment]
We don't develop or support these drivers, so there isn't much we can do to help you...
