### ISSUE TITLE
l10n: extra trailing space in cups.strings

### ISSUE THREAD

**Issue by MingcongBai** [apple/cups#4800]
The line pointed out below shows an extra trailing space on the string "Envelope #10".

https://github.com/apple/cups/blob/5eb74392544acafddc9faeb7b1e8d1fe5e2715f1/locale/cups.strings#L804

And this is exposed to the gettext catalogs.

**Comment by MingcongBai** [comment]
Similar issue found here https://github.com/apple/cups/blob/5eb74392544acafddc9faeb7b1e8d1fe5e2715f1/locale/cups.strings#L834.

**Comment by michaelrsweet** [comment]
[master a395099] Fix localization of some media sizes (Issue #4800)
