### ISSUE TITLE
CUPS 2.1.3 with zebra TTP2030 

### ISSUE THREAD

**Issue by cretico** [apple/cups#4801]
After downloading cups 2.1.3 and compiling on MAC OS 10.11.4, go to browser with url: localhost:631/ to configure the zebra printer. 
Step1: discover the local USB printer------no issue.
Step 2: upload the ppd file ttp20x0.ppd---shows error message: OpenGroup without a CloseGroup first.
             not sure what it refer to, because I had never modified the ppd file.
Step3: try to upload the KR203.ppd file for this ttp2030 printer, the printer show status:
"File "/usr/libexec/cups/filter/rastertozebrakiosk" not available: No such file or directory" 
             not sure what it refer to, MAC OS come with driver 2.1, why does it require extra file?

**Comment by cretico** [comment]
http://www.cups.org/strfiles.php/3767/zebraCupsDrivers_v2.zip

I did google search and found the above link, i know it posted about 5 years ago, not surprised that it's gone, anyone know where to get it in year 2016?

**Comment by michaelrsweet** [comment]
This isn't a driver we provide or support. OS X *does* come with drivers for ZPL and EPL label printers, but not ones that use those PPDs.

**Comment by cretico** [comment]
I clearly understand "OS X does come with drivers for ZPL and EPL label printers, but not ones that use those PPDs.", but did you every try to print on TTP2030 printer with those drivers?
