### ISSUE TITLE
CUPS doesn't return toner level for printer Brother-MFC-7860DN when it's empty during printing

### ISSUE THREAD

**Issue by yyikaka** [apple/cups#4802]
when a print job was sent to a network printer with an empty toner, the "marker-level" turned out not to be 0, and attribute "printer-state-rason" of subscription was "none"...
os: ubuntu
cups version:1.7.2

**Comment by michaelrsweet** [comment]
What is the device URI for the printer? (lpstat -v will show you)

What driver are you using?

**Comment by yyikaka** [comment]
The device-uri is "dnssd://Brother%20MFC-7860DN._pdl-datastream._tcp.local/".
I use a PPD file for driver for the printer.
 



1316208403@qq.com
 
From: Michael R Sweet
Date: 2016-04-09 02:06
To: apple/cups
CC: yyikaka
Subject: Re: [apple/cups] CUPS doesn't return toner level for printer Brother-MFC-7860DN when it's empty during printing (#4802)
What is the device URI for the printer? (lpstat -v will show you)
What driver are you using?

**Comment by michaelrsweet** [comment]
OK, for this type of connection we depend on either the driver reporting supply levels or the printer supporting SNMP. It sounds like neither of these things are the case...
