### ISSUE TITLE
plain text diffs of old patches have become unaccessible

### ISSUE THREAD

**Issue by jsmeix** [apple/cups#4804]
Since CUPS was moved to GitHub
the plain text diffs of old patches are no longer accessible.

For an example see the old CUPS STR 3010
https://www.cups.org/str.php?L3010
that redirects to the GitHub issue https://github.com/apple/cups/issues/3010

In the GitHub issue https://github.com/apple/cups/issues/3010 the "str3010.patch" is shown
as garbled text (probably messed up by markdown)
and the plain text diff is not directly accessible
from the GitHub issue https://github.com/apple/cups/issues/3010

On www.cups.org the plain text diffs of old patches
are still available under URLs of the form
<pre>
https://www.cups.org/strfiles.php/MMMM/strNNNN.patch
</pre>
where NNNN is the CUPS STR number
but the problem is the other number MMMM
that has no predicatble relation to NNNN
(i.e. one cannot know what MMMM is)
which makes the plain text diffs of old patches
unaccessible.

For me personally this is a major issue because
we (i.e. SUSE) provide maintenance even for
old CUPS versions (e.g. CUPS 1.3.9 that
we have in SUSE Linux Enterprise 11)
and in case of issues it helps very much when
the plain text diffs of old patches is easily available.

**Comment by michaelrsweet** [comment]
I can edit the older bug reports to reformat the embedded patch files. Unfortunately, Github does not provide an API for attaching files when importing bugs/issues, so I had to do the best I could when migrating the CUPS bug database over...

If there are specific bugs you need the patches for, please let me know and I will do what I can...

**Comment by jsmeix** [comment]
I think a general reformatting of existing GitHub issue texts
is not really needed (but it would be nice to have if that is
easily possible because it would make embedded diffs and
other embedded code in existing GitHub issues better readable).

Specifically currently I liked to get the plain text diff
of the "str3010.patch" in https://github.com/apple/cups/issues/3010

@michaelrsweet 
many thanks for making the embedded diff in https://github.com/apple/cups/issues/3010#issuecomment-197671298 readable!

I wished there was a predictable URL on www.cups.org
to get patches for known old CUPS STR numbers
or perhaps even a search form where one could
enter a STR number to get its matching patches.

For example something like
<pre>
https://www.cups.org/strfiles/strNNNN.patch
</pre>
or perhaps better when there are more patches
for one STR there could be a directory like
<pre>
https://www.cups.org/strfiles/NNNN/
</pre>
where all files for that STR number are accessible.

**Comment by michaelrsweet** [comment]
Unfortunately, there are a lot of bugs with multiple patches, either different versions or parts, so making this work in a way that isn't more confusing.
