### ISSUE TITLE
I noticed that if print a few files with same prefix "lpr *file" with "prettyprint" that the name of the first file is the page header for all of the files

### ISSUE THREAD

**Issue by zemlik** [apple/cups#4805]

**Comment by michaelrsweet** [comment]
First, the text filters are part of the cups-filters project...

Second, the original filename information is not available to filters. The "lp" and "lpr" commands set the default default job name to the base name of the first file on the command-line, and that is what the text filter is using to display the filename on each page of the output.

The workaround is to submit each file separately.
