### ISSUE TITLE
index.html.in

### ISSUE THREAD

**Issue by SilvanScherrer** [apple/cups#4809]
The german index.html.in doesn't contain @CUPS_VERSION@ for the version string. It still says CUPS 2.0.2.

**Comment by michaelrsweet** [comment]
For what version? I don't see that in the master or 2.1 branches in Git...

**Comment by SilvanScherrer** [comment]
https://github.com/apple/cups/blob/master/doc/de/index.html.in
line 26

**Comment by michaelrsweet** [comment]
OK, got it and a fix for the master branch is now merged.
