### ISSUE TITLE
restricting access to printer by user hides printer from list

### ISSUE THREAD

**Issue by dab18** [apple/cups#4810]
step to reproduce (tested on CUPS 2.1.3):
1. go to http://localhost:631/printers/myprinter (login as SystemGroup/"lpadmin" member)
2. select "Administration" - "Set Allowed Users"
3. fill "Users:" field with some usernames: say "zzz" (don't include youself or "lpadmin" group)
4. select "Allow these users to print" and press "Set Allowed Users"
check /etc/cups/printers.conf:
...
AllowUser zzz
...
run "lpstat -a" - does not show "myprinter".
go to  http://localhost:631/printers/ - does not show "myprinter".
but "myprinter" directly accessible through http://localhost:631/printers/myprinter

**Comment by michaelrsweet** [comment]
Behaves correctly, requesting-user-name-allowed/denied trump policies, you need to explicitly include the system group(s) or user(s) in the user list.
