### ISSUE TITLE
ippAddString for compression results in BAD_REQUEST

### ISSUE THREAD

**Issue by enoha** [apple/cups#4812]
I'm very new to using CUPS so the answer may be very straightforward, I'm trying to enable compression for a printer that supports gzip, I call
ippAddString(request, IPP_TAG_OPERATION, IPP_TAG_KEYWORD,
                 "compression", NULL, "gzip");
the print call results in a BAD_REQUEST, actually if I make the same with "none" I get the same issue. I'm using version 1.7.5

**Comment by michaelrsweet** [comment]
Are you talking to the printer or to CUPS?

**Comment by enoha** [comment]
To CUPS, I get  a `IPP_BAD_REQUEST` as a result of calling cupsDoRequest, it otherwise goes fine if I don't add compression to the request

**Comment by michaelrsweet** [comment]
OK, to get CUPS to use compression to the printer you need to specify it in the device URI for CUPS 1.7 and earlier, it happens automatically in later releases.

Doing it in the request to CUPS will only tell it to expect compression in your request to CUPS, not in the requests made to the printer.

**Comment by michaelrsweet** [comment]
http://www.cups.org/documentation.php/network.html
