### ISSUE TITLE
LogLevel Info is broken

### ISSUE THREAD

**Issue by frazhome** [apple/cups#4815]
LogLevel Info seems to be broken.

When Loglevel Info is configured at cupsd.conf, no Job information are logged

when Debug is configured the following Info-Messages are logged:
I [24/Apr/2016:19:57:19 +0200] [Job 39] Adding start banner page "none".
I [24/Apr/2016:19:57:19 +0200] [Job 39] Queued on "lpd" by "support".
I [24/Apr/2016:19:57:19 +0200] [Job 39] File of type text/plain queued by "support".
I [24/Apr/2016:19:57:19 +0200] [Job 39] Adding end banner page "none".
I [24/Apr/2016:19:57:19 +0200] [Job 39] Started filter /usr/lib/cups/filter/texttopdf (PID 22935)
I [24/Apr/2016:19:57:19 +0200] [Job 39] Started filter /usr/lib/cups/filter/pdftopdf (PID 22936)
I [24/Apr/2016:19:57:19 +0200] [Job 39] Started filter /usr/lib/cups/filter/gstopxl (PID 22937)
I [24/Apr/2016:19:57:19 +0200] [Job 39] Started backend /usr/lib/cups/backend/lpd (PID 22938)
I [24/Apr/2016:19:57:19 +0200] [Job 39] Starting GPL Ghostscript 9.18...
I [24/Apr/2016:19:57:19 +0200] [Job 39] Copying print data.
I [24/Apr/2016:19:57:23 +0200] [Job 39] Connecting to printer.
I [24/Apr/2016:19:57:23 +0200] [Job 39] Connected to printer.
I [24/Apr/2016:19:57:23 +0200] [Job 39] Control file sent successfully.
I [24/Apr/2016:19:57:23 +0200] [Job 39] Spooling job, 0% complete.
I [24/Apr/2016:19:57:23 +0200] [Job 39] Data file sent successfully.
I [24/Apr/2016:19:57:23 +0200] [Job 39] Job completed.
I [24/Apr/2016:19:57:23 +0200] Expiring subscriptions...

maybe cupsdLogMessage at scheduler/log.c is broken.

I tested this on ubuntu 16.04 and sles12sp1 (cups1.7.5)

with this failure it is hard to track down spooling problem.

regards
Franz

**Comment by frazhome** [comment]
does this in log.c starting at 770 
/*
  * See if we want to log this message...
  */

  if ((TestConfigFile || !ErrorLog) && level <= CUPSD_LOG_WARN)

mean only messages with a level WARN or DEBUG is logged?

or should it be like:

  if ((TestConfigFile || !ErrorLog) && level <= loglevel


sorry I am not a real programmer ...

regards
Franz

**Comment by michaelrsweet** [comment]
No, that's the backup logging for errors (so you'll see something on the console).

**Comment by frazhome** [comment]
but could you confirm the issue?

**Comment by michaelrsweet** [comment]
As I have been on travel and in meetings (or preparation for meetings), I have not had an opportunity to confirm the issue yet. Please be patient.

**Comment by michaelrsweet** [comment]
Can you attach your cupsd.conf file (the one that does not show info messages) to this issue?

**Comment by frazhome** [comment]
Hello Michael,

here the config.

the cupsd-op-policies.conf is a include of cupsd.conf.

regards
Franz
Am 01.05.2016 um 18:01 schrieb Michael R Sweet <notifications@github.com>:

**Comment by michaelrsweet** [comment]
OK, this appears to be an intentional change that was made back in CUPS 1.4 for the automatic debug logging. Investigating the implications of passing INFO messages through to the log when the filter doesn't fail - we don't want progress messages ("Printing page 4, 37% complete", etc.) getting logged, for example...

**Comment by frazhome** [comment]
why do you call it RFE?

In my opinion there is something broke.
This is not a request for a feature?

**Comment by michaelrsweet** [comment]
Because this is behaving as designed/intended and you want a different behavior, this is a RFE.

(the reason is that we don't want to pollute the error_log file with a lot of INFO messages - lots of "everything is OK" messages are not particularly useful...)

**Comment by frazhome** [comment]
maybe you are right, but take a look at a errror_log with LogLevel Info :+1: 
I [05/May/2016:20:13:46 +0200] Saving subscriptions.conf...
D [05/May/2016:20:13:47 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Dirty files"
D [05/May/2016:20:13:47 +0200] Creating keep-alive file "/var/cache/cups/org.cups.cupsd".
I [05/May/2016:20:13:47 +0200] Saving job.cache...
D [05/May/2016:20:13:47 +0200] cupsdStopSelect()
I [05/May/2016:20:15:26 +0200] Listening to 0.0.0.0:631 (IPv4)
I [05/May/2016:20:15:26 +0200] Listening to [v1.::]:631 (IPv6)
I [05/May/2016:20:15:26 +0200] Listening to /var/run/cups/cups.sock (Domain)
I [05/May/2016:20:15:26 +0200] Remote access is enabled.
I [05/May/2016:20:15:26 +0200] Loaded configuration file "/etc/cups/cupsd.conf"
I [05/May/2016:20:15:26 +0200] Using default TempDir of /var/spool/cups/tmp...
I [05/May/2016:20:15:26 +0200] Configured for up to 100 clients.
I [05/May/2016:20:15:26 +0200] Allowing up to 100 client connections per host.
I [05/May/2016:20:15:26 +0200] Using policy "default" as the default.
I [05/May/2016:20:15:26 +0200] Full reload is required.
I [05/May/2016:20:15:27 +0200] Loaded MIME database from "/usr/share/cups/mime" and "/etc/cups": 49 types, 83 filters...
I [05/May/2016:20:15:27 +0200] Generating printcap /var/run/cups/printcap...
I [05/May/2016:20:15:27 +0200] Loading job cache file "/var/cache/cups/job.cache"...
I [05/May/2016:20:15:27 +0200] Full reload complete.
I [05/May/2016:20:15:27 +0200] Cleaning out old files in "/var/spool/cups/tmp".
I [05/May/2016:20:15:27 +0200] Cleaning out old files in "/var/cache/cups".
I [05/May/2016:20:15:27 +0200] Registering ICC color profiles for "blacky".
I [05/May/2016:20:15:27 +0200] Registering ICC color profiles for "lpd".
I [05/May/2016:20:15:27 +0200] Listening to 0.0.0.0:631 on fd 10...
I [05/May/2016:20:15:27 +0200] Listening to [v1.::]:631 on fd 11...
I [05/May/2016:20:15:27 +0200] Listening to /var/run/cups/cups.sock on fd 3...
I [05/May/2016:20:15:27 +0200] Resuming new connection processing...
I [05/May/2016:20:15:28 +0200] Expiring subscriptions...
I [05/May/2016:20:15:33 +0200] Expiring subscriptions...
I [05/May/2016:20:15:34 +0200] Expiring subscriptions...
I [05/May/2016:20:15:58 +0200] Saving printers.conf...
I [05/May/2016:20:15:58 +0200] Saving job.cache...
I [05/May/2016:20:15:58 +0200] Saving subscriptions.conf...
I [05/May/2016:20:15:58 +0200] Expiring subscriptions...
I [05/May/2016:20:16:53 +0200] Expiring subscriptions...
I [05/May/2016:20:16:54 +0200] Expiring subscriptions...
I [05/May/2016:20:16:55 +0200] Expiring subscriptions...

In this log there was printed one printjob to the printer lpd.


With this log you could not analyze  anything. And when you switch the LogLevel to Debug you got Info-Messages about printjobs.

So, when it is intentional, than all printer status messages should have the marker 'D' not 'I' -> Bug
or, the maker 'I' is ok, than the behaviour not is broken.

But maybe, there should be a LogLevel Info2 for more Info-Message.

In my environment Debug is not possilbe because it create >1G on one day.

**Comment by michaelrsweet** [comment]
Now imagine getting thousands of "Printing page 1, N%" messages added to the log...

**Comment by michaelrsweet** [comment]
[master 75c86da] The scheduler now logs informational messages for jobs at LogLevel "info" (Issue #4815)

**Comment by frazhome** [comment]
Today I made my first tests. It worked! thanks a lot.
Franz
