### ISSUE TITLE
Stopped - Printer disappeared or cups-browsed shutdown

### ISSUE THREAD

**Issue by jcobban** [apple/cups#4816]
I cannot find any explanation of this printer status on the CUPS client or any advice of how to resolve it.  I have examined every bit of information on both the client and the server and see nothing obviously wrong.  According to the logs on the CUPS server the CUPS client has not even communicated with the server even though they are 30cm apart and attached to the same LAN hub!  All I want to know is what I have to do to get the client to send the two weeks of accumulated print jobs across to the server.  This is very frustrating and at the least indicates a gap in the documentation.

**Comment by michaelrsweet** [comment]
As cups-browsed is not part of CUPS, there isn't much we can do to help you there.

The /var/log/cups/error_log file on the client will contain information about the jobs that are queued and as they are processed/forwarded. Run "cupsctl --debug-logging" to enable debug logging on the client and/or server.
