### ISSUE TITLE
USB printer not detected within CUPS

### ISSUE THREAD

**Issue by github-k8n** [apple/cups#4817]
USB Printer Samsung SL-M2026
with CUPS 2.1.3
on Gentoo Linux (amd64, no multilib)

At first, everything looks fine:

kernel usb_printer support is disabled (to not interfere with libusb)
```
# zcat /proc/config.gz |grep USB_PRINTER
# CONFIG_USB_PRINTER is not set

```
```
lsusb:
Bus 001 Device 003: ID 04e8:3321 Samsung Electronics Co., Ltd 

```
```
# ls -la /dev/bus/usb/001/003 
crw-rw-r-- 1 root lp 189, 2 27. Apr 22:08 /dev/bus/usb/001/003
```

running the backend as root seems to detect the printer
```
# /usr/libexec/cups/backend/usb 
DEBUG: Loading USB quirks from "/usr/share/cups/usb".
DEBUG: Loaded 77 quirks.
DEBUG: list_devices
DEBUG: libusb_get_device_list=12
DEBUG2: Printer found with device ID: MFG:Samsung;CMD:SPL,URF,FWV,PIC,EXT;MDL:M2020 Series;CLS:PRINTER;CID:SA_SPLV3_BW;MODE:SPL3,R000105;STATUS:BUSY; Device URI: usb://Samsung/M2020%20Series?serial=08HVB8GGCF013HK
direct usb://Samsung/M2020%20Series?serial=08HVB8GGCF013HK "Samsung M2020 Series" "Samsung M2020 Series" "MFG:Samsung;CMD:SPL,URF,FWV,PIC,EXT;MDL:M2020 Series;CLS:PRINTER;CID:SA_SPLV3_BW;MODE:SPL3,R000105;STATUS:BUSY;" ""
```

However, no printer is detected in the Interface and also not with lpinfo:
```
# lpinfo -v
network beh
network ipp
network lpd
network socket
network ipps
network https
network http
```

and running the backend as user lp does not show any printer:
```
# sudo -u lp /usr/libexec/cups/backend/usb 
DEBUG: Loading USB quirks from "/usr/share/cups/usb".
DEBUG: Loaded 77 quirks.
DEBUG: list_devices
DEBUG: libusb_get_device_list=0

```

So my question would be:
Is there any other location that the usb backend needs the correct rights to?
even changing /dev/bus/usb/001/003 to 777 does not help here.
Is the "usb" backend supposed to be run as root or as user lp?

How can I make cups detect and use the printer?

**Comment by michaelrsweet** [comment]
The USB backend should run as the "lp" user, and your Linux distribution should be setting things up to properly set the permissions on the USB device files and directories. It sounds like the latter is not the case - please contact Gentoo to find out if something has changed to prevent USB permissions from being set properly...

**Comment by github-k8n** [comment]
Yes, sorry, the culprit was a grsec-enabled kernel with the option CONFIG_GRKERNSEC_SYSFS_RESTRICT

(just posting this here in case someone else fails into the same trap..)
