### ISSUE TITLE
Label printers print unscanable barcodes due to bad PWG

### ISSUE THREAD

**Issue by kylemacfarlane** [apple/cups#4820]
When I print shipping labels via CUPS the quality of barcodes are greatly reduced and unscanable by most devices. This is not a problem from Windows.

Both CUPS and Windows convert PDFs to an image and then embed that image as a GRF in ZPL. So I made a GRF => PNG converter to check the quality and it's obvious that the GRF from CUPS is wrong. Not low quality but drawn incorrectly.

Then I hooked gs to check what options are being used to generate the PWG so I could generate my own PWG and view it in an app called Rasterview. Doing this confirms that the problem exists in the PWG as well.

Running the same gs command but outputting a PNG shows the same problem. In fact all raster devices show the problem when run with the options CUPS uses to convert PDFs. Ghostscript's options aren't well documented and I am yet to find something that fixes the problem.

![barcode-comparison](https://cloud.githubusercontent.com/assets/99594/15101583/08a20e18-158c-11e6-8cc6-0fe32dd3c836.png)

**Comment by michaelrsweet** [comment]
This isn't a cups problem but a Ghostscript problem...

**Comment by kylemacfarlane** [comment]
I spoke to the Ghostscript guys and they said it's not their problem because they match Adobe.

The problem is that thermal printers are low res (203dpi) and so CUPS asks pdftoraster for a low res mono image. Due to the low resolution gs has to make some assumptions and rounding errors. The end result will print OK on a high res laser but will not on a low res thermal printer where the nature of thermal paper causes bleeding that makes the rounding errors even worse.

So what CUPS probably should do is ask for a high res or greyscale image from pdftoraster and then have rastertolabel convert it to a low res mono GRF appropriate for label printers. Rastertolabel is the only part of the chain that knows it's going to a special type of printer so that should be where the special conditions are handled.

If CUPS won't fix it then I think it will be pretty easy to write my own filters to do PDF => PNG => GRF but how could I hijack the PDF mimetypes only for our label printers without affecting our laser printers?

**Comment by jsmeix** [comment]
@kylemacfarlane 
only FYI in general regarding
"own filters ... only for our label printers"
you may have a look in particular at the sections
"Print Queue Specific Custom Filters" and
"Print Job Data Specific Custom Filters" in
https://en.opensuse.org/SDB:Using_Your_Own_Filters_to_Print_with_CUPS

**Comment by michaelrsweet** [comment]
Kyle,

Without a copy of the source PDF it is impossible to comment further on how to improve things, but if the PDF contains a bitmap/image representation of the bar code that is not 203 PPI/DPI then Ghostscript will need to subsample the image leading to the kind of output issues you are seeing. And in that case  increasing the intermediate resolution will probably not fix this issue and might in fact make it worse.

**Comment by jsmeix** [comment]
Only for completeness:
The matching Ghostscript issue report is
http://bugs.ghostscript.com/show_bug.cgi?id=696758

**Comment by kylemacfarlane** [comment]
Looking at the GRFs generated by Windows vs CUPS the text is mostly the same but the barcodes are pretty different. From CUPS the minimum black bar is 2px and the minimum white is 1px but from Windows it's swapped with the white bars getting preference. This is because on a thermal printer a 1px white gap mostly disappears as the black bars on either side of it kiss like a shadow blister.

Since we have control over our labels I simply changed how our barcodes are drawn and increased the size of the white bars. Only real downside is that you have to remember to generate different PDFs for thermal printers and laser printers.

I'm not sure how to fix it for labels we don't control. Either CUPS needs to implement special downscaling which targets thermal printers or something to run over the GRF and look for barcode patterns and clean them up.

Something also of note in the Windows GRF is that the boldest text has hollow spots. This doesn't appear on the print out and I don't know if it's a bug or purposeful post processing to eliminate over heating.

If you Google for say "mac blurry barcode" you can see that the problem is pretty widespread. Someone has even made a $200 driver that claims to alleviate the problem.

The attached GRFs => PNGs are slightly edited to erase my signature.

https://dl.dropboxusercontent.com/u/17827955/cups/source.pdf
https://dl.dropboxusercontent.com/u/17827955/cups/linux.grf.png
https://dl.dropboxusercontent.com/u/17827955/cups/windows.grf.png

**Comment by kylemacfarlane** [comment]
@jsmeix What is the the purpose of the vendor mimetypes, i.e. application/pdf vs application/vnd.cups-pdf?

Why do the values for requested-orientation go from 2-6 whereas orientation in Ghostscript/Postscript is 0-3? Despite the different values are they otherwise the same thing and thus can be mapped as follows?

    0 => 3
    1 => 5
    2 => 6
    3 => 4

I ended up with a bunch of scripts to convert between PDF/PNG/GRF/ZPL and so put them together into https://github.com/kylemacfarlane/zplgrf I also put `pdftozpl` in there which can be used as a `*cupsFilter2` but still needs some work to deal with multi page PDFs, images that go over multiple pages, operating the cutter/peeler, etc. However I don't think I will use it as a filter but rather do PDF => ZPL on our servers and send the ZPL round the network as it's much quicker than sending round a PDF.

One of the reasons it's quicker is that I figured out how to use compressed images in ZB64 format which is about 1/3 of the size of the run length compressed ZPL rastertolabel generates. Zebra say that ZB64 uses LZ77 and a proprietary CRC but actually it's just regular DEFLATE with a CCITT CRC.

**Comment by michaelrsweet** [comment]
The orientation-requested values go from 3-7, as defined for IPP. Ghostscript uses 0-3 as defined for PostScript.

**Comment by kylemacfarlane** [comment]
Thanks. I see that I should probably just ignore requested-orientation for most formats.

I wonder if the overlap at 3 is the reason why Google Cloud Print has so many issues related to printing landscape PDFs.

**Comment by jsmeix** [comment]
@kylemacfarlane
regarding application/pdf vs application/vnd.cups-pdf

Inspect the various /usr/share/cups/mime/*.convs
and /etc/cups/*.convs MIME conversions files
how one particular MIME type is converted
into another particular MIME type.

On my openSUSE Leap 42.1 system with CUPS 1.7.5 and
cups-filters I have in /usr/share/cups/mime/cupsfilters.convs
(which is from cups-filters)
<pre>
application/pdf  application/vnd.cups-pdf  66  pdftopdf
</pre>
i.e. the pdftopdf filter /usr/lib/cups/filter/pdftopdf
(also from cups-filters) converts application/pdf
into application/vnd.cups-pdf

Regarding what the purpose of the pdftopdf filter is
see the documentation of cups-filters.
On my openSUSE Leap 42.1 system the main
documentation of cups-filters is installed as
/usr/share/doc/packages/cups-filters/README
The cups-filters upstream page is
http://www.linuxfoundation.org/collaborate/workgroups/openprinting/cups-filters

In /usr/share/cups/mime/cupsfilters.convs there are various
other MIME conversion rules that result application/vnd.cups-pdf
and there are rules that further convert application/vnd.cups-pdf
into some other MIME types so that in the end data of a MIME
type that the final printer device understands is generated
which is finally sent to the printer device to make a printout.

**Comment by chunlinyao** [comment]
@kylemacfarlane ghostscript support center-of-pixel rule, and any-part-of-pixel rule. we can adjust it by `gs -c '0 .setfilladjust'`, it will generate more accurate barcode. we should report to the upstream cups-filters to add an option for `setfilladjust` support.

**Comment by kylemacfarlane** [comment]
@chunlinyao I don't have any printers next to me to test but looking at generated PNGs that certainly looks like a possible fix (but just because it looks good doesn't mean it will scan).

I believe it's also possible to insert raw PostScript in PDFs which might be a fix if you generate your own labels but not if you have to print somebody else's.

Do you want to comment on http://bugs.ghostscript.com/show_bug.cgi?id=696758 with your suggestion? They will take it more seriously if multiple people have the same problem.

**Comment by chunlinyao** [comment]
It is related to cups-filters project, so I created a feature request at https://bugs.linuxfoundation.org/show_bug.cgi?id=1373

**Comment by frazhome** [comment]
since 21th September the feature is implemented and available with cups-filters 1.11.4.

Now only the CenterOfPixel option is missing at the ZPL-driver in sample.drv

**Comment by frazhome** [comment]
I added the following lines to ppdc/sample.drv

1167,1169d1166
<       Option "CenterOfPixel/Lowres optimizing" PickOne AnySetup 20.0
< 	*Choice "Standard/Standard" ""
< 	Choice "true/True" "true"

is this enough?

**Comment by michaelrsweet** [comment]
This isn't a driver option, it is a RIP option for a filter that is not shipped with CUPS, so we won't include this in the CUPS label printer drivers, sorry.

**Comment by frazhome** [comment]
So back to my latest question.

Are this three lines enough to enable the Center-of-Pixel feature in the ZPL driver from the CUPS-Project?

I understand your opinion about the RIP option, but how we should solve our problems this labelprinters.

Aren't the filterchange for rastertolabel using the ghostscript?

**Comment by michaelrsweet** [comment]
@frazhome No idea whether that is enough, we don't maintain or support cups-filters.

The drivers included with CUPS use whatever RIP is available on the system - Ghostscript/poppler on Linux and cgpdftoraster on macOS.

**Comment by frazhome** [comment]
I added the following lines to sample.drv to enable this feature.

diff -u /usr/share/cups/drv/sample.drv ~/src/cups/ppdc/sample.drv 
--- /usr/share/cups/drv/sample.drv	2016-10-04 21:24:54.000000000 +0200
+++ /home/support/src/cups/ppdc/sample.drv	2016-09-30 23:44:05.628629364 +0200
@@ -1164,6 +1164,9 @@
 	*Choice "Saved/Printer Default" ""
 	Choice "Always/Always" ""
 	Choice "Never/Never" ""
+      Option "CenterOfPixel/Center-of-Pixel" PickOne AnySetup 20.0
+	*Choice "Standard/Postscript Standard" ""
+	Choice "true/True" "true"
   }
 }

**Comment by frazhome** [comment]
Sorry for the doublepost :-(

But, what is the right way to make this opition available to configure?

**Comment by michaelrsweet** [comment]
This would need to be a patch that the Linux distros apply the CUPS sources.

**Comment by frazhome** [comment]
shoud this patch change the sample.drv

this mean a fork of sample.drv?! Does anybody like this?

**Comment by kylemacfarlane** [comment]
@frazhome If you are trying to enable this for a printer then you want to edit that printer's .ppd file. Sample.drv doesn't affect anything.

Run the command `lpstat -l -p | grep ppd`. Those are the files you want to edit. Add the six lines shown in the README at http://bzr.linuxfoundation.org/loggerhead/openprinting/cups-filters/revision/7538

You will have to restart cups after editing the files.

**Comment by frazhome** [comment]
the modification is not the problem. I am doing something like this since years ..

And modification of the sample.drv is working. Moderns cups, I think since 2.x, creates the ppd on the fly in the memory from the drv-file in the cups-drv path. 
You can check this via lpinfo -m 
Older Versions needs a ppdc sample.drv with creates the ppd files.

**Comment by kylemacfarlane** [comment]
I'm no expert on CUPS but I would assume the PPDs generated by sample.drv are supposed to be bare bones starting points.

Zebra, Citizen, etc have PPDs available to download that support more features.
