### ISSUE TITLE
Two Printers with no Serial number cause cups backend failure.

### ISSUE THREAD

**Issue by jmanleyUSA** [apple/cups#4821]
I have two label printers: Citizen CLP-7201e.
I use the PPD from the manufacture.
As long as I only have one plugged in and setup at a time CUPS works fine.
The Printers do not show a Serial Number in lsusb -v
So they both end up having the same exact Device URI.
This is what I think is causing issues printing in CUPS.
Let me know if you need output from anything else.
So in cups on the back end when they are plugged in I get:

```
root@Z:/usr/lib/cups/backend# ./usb
DEBUG: Loading USB quirks from "/usr/share/cups/usb".
DEBUG: Loaded 131 quirks.
DEBUG: list_devices
DEBUG: libusb_get_device_list=12
DEBUG2: Printer found with device ID: MANUFACTURER:CITIZEN;COMMAND SET:NATIVE ON, NATIVE OFF;MODEL:CLP-7201e;ACTIVE COMMAND:NATIVE OFF; Device URI: usb://CITIZEN/CLP-7201e
direct usb://CITIZEN/CLP-7201e "CITIZEN CLP-7201e" "CITIZEN CLP-7201e" "MANUFACTURER:CITIZEN;COMMAND SET:NATIVE ON, NATIVE OFF;MODEL:CLP-7201e;ACTIVE COMMAND:NATIVE OFF;" ""
DEBUG2: Printer found with device ID: MANUFACTURER:CITIZEN;COMMAND SET:NATIVE ON, NATIVE OFF;MODEL:CLP-7201e;ACTIVE COMMAND:NATIVE OFF; Device URI: usb://CITIZEN/CLP-7201e
direct usb://CITIZEN/CLP-7201e "CITIZEN CLP-7201e" "CITIZEN CLP-7201e" "MANUFACTURER:CITIZEN;COMMAND SET:NATIVE ON, NATIVE OFF;MODEL:CLP-7201e;ACTIVE COMMAND:NATIVE OFF;" ""
```

**Comment by jsmeix** [comment]
You cannot use two printer devices with same DeviceURI.

You need to get different DeviceURIs for different printers.

I assume you must make your own backends
to achieve that for your particular printer models, cf.
https://en.opensuse.org/SDB:Using_Your_Own_Backends_to_Print_with_CUPS

**Comment by michaelrsweet** [comment]
The issue here is that the printer is not supporting the (recommended) serial number, so there is no reliable way to target multiple printers.

What we do on OS X is to remember the port the printer is connected to and use that when there isn't a serial number, which we could potentially do on Linux as well.  But the kicker is that if you ever re-connect the printers to different ports then those queues will stop working...

**Comment by michaelrsweet** [comment]
Unfortunately, we do not have the resources to address this issue...
