### ISSUE TITLE
"filter failed" error message could be more useful

### ISSUE THREAD

**Issue by archenemies** [apple/cups#4823]
I've been using CUPS for over ten years.

I noticed that I sometimes get a "filter failed" error message in the Web GUI, under the "jobs" listing.

First of all I have a question, last time I reported an issue here I was informed (by Michael Sweet) that the web interface was not meant to be the primary interface to CUPS, so I'm wondering how to get access to the jobs listing (complete with "filter failed" error message) via command line tools...

Secondly I would like to request a more detailed error message. For instance, what was the filter command that failed? Without that information, it's hard to know where to start debugging the problem. I don't even know which package the filter is part of. I did a recent upgrade, and I noticed that sometimes HP filters break when I upgrade. However, it would be preferable if the CUPS interface saved me from having to do this kind of guesswork when something breaks. There's a reason that Unix devotes a whole filehandle to the task of passing error messages back to the user: often a small component of a large system will want to tell us in some detail about why it failed. If this information is turned into a generic "something failed" message then troubleshooting becomes much harder.

Even just printing the path to the filter, together with its input, would be helpful. Then at least I could try running it on the command line.

Thank you!

**Comment by michaelrsweet** [comment]
The error_log file contains detailed information, and in fact the default status message says:

" Job stopped due to filter errors; please consult the error_log file for details.

Unfortunately, the code that reports the terminating state of the job does not have the name of the process that failed, which gets logged separately...

**Comment by archenemies** [comment]
Thank you. I understand that it may be difficult to fix. Modifying some internal APIs to pass the desired information would be great.

I don't recall being asked by the web interface to consult error_log. Linking to this file from the web interface might be helpful. Since some of the lines seem to be prefixed by job numbers, it might even be possible to highlight the relevant lines. That would be a more creative workaround. Thanks.

**Comment by michaelrsweet** [comment]
Sorry, after review we've decided this bug is unlikely to be addressed/fixed beyond what CUPS already supports (view error_log in web interface, etc.)

**Comment by zilti** [comment]
"The error_log file contains detailed information" - actually, it doesn't. I just have the case where I simply get "filter failed" on my local CUPS when trying to print to a remote CUPS, and the error_log has nothing.
