### ISSUE TITLE
Would DEVICE_URI be a useful addition to cupsfilter

### ISSUE THREAD

**Issue by debiantriage** [apple/cups#4826]
The detail is at

[https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=825219](url)

but basically using HP's hpps filter does not give an output file when using the -e and -m options with cupsfilter.

Regards,

Brian.

**Comment by michaelrsweet** [comment]
Filters MUST be able to function without access to the output device. Please report this to the HP folks...

**Comment by debiantriage** [comment]
[https://bugs.launchpad.net/ubuntu/+source/hplip/+bug/1589897](url)
