### ISSUE TITLE
Cups asks for password twice in GTK print dialog

### ISSUE THREAD

**Issue by hut** [apple/cups#4828]
When I print something with evince or other GTK programs over a remote cups server, it asks for the password twice.

The first time the server is adressed via the host name. After successfully typing the password, the list of printers appears in the printing dialog and it asks for the password again, adressing the server via its IP.

This doesn't happen if I set the IP in `ServerName` in the `~/.cups/client.conf`, only if I set the host name there.

Is there maybe some configuration option that forbids access when adressing the server via its hostname?

cups version: 1.6.3 @ Cent OS 7.2.1511
evince version 3.20.0
GTK version: 3.20.6-1

**Comment by michaelrsweet** [comment]
This isn't a CUPS issue, but a GNOME issue...

**Comment by hut** [comment]
nope, happens with QT programs as well.

This is the password dialog on the console when I print with Kwrite:
![screenshot2](https://cloud.githubusercontent.com/assets/90548/15710010/36ac9e8e-2808-11e6-94cd-6449fd45bb62.png)

(Sorry for the german language, it says "Password for" .... "on" ....)

**Comment by michaelrsweet** [comment]
Then Qt is making the same mistake as GTK+/GNOME.

The application (or toolkit in this case) is responsible for caching credentials beyond the HTTP connection. They aren't doing that...
