### ISSUE TITLE
Head Cleaning Issue (stopped  "Invalid printer command "Clean".")

### ISSUE THREAD

**Issue by KitchM** [apple/cups#4830]
I am using Xubuntu 14.04 with Firefox 45.0.1, and I have CUPS 1.7.2 installed along with HPLIP Software Version 3.14.3 and Device Manager Version 15.0 (Qt4); aka HPLIP Status Service.  I am using an HP Photosmart C3140 All-in-One.  It is considered one of the C3100 Series devices.

CUPS shows the following:
▼ Queue Name ▼	Description	Location	Make and Model	Status
HP_Photosmart_C3100_series	HP Photosmart C3100 series		HP Photosmart c3100 Series hpijs, 3.14.3	Idle
PDF	PDF		Generic CUPS-PDF Printer	Idle
Photosmart_C3100	Photosmart_C3100		HP Photosmart c3100 Series, hpcups 3.14.3	Idle

HPLIP cannot do a proper cleaning as each step is exactly as the first.  CUPS fails the same task with; stopped  "Invalid printer command "Clean"." when using the HP_Photosmart_C3100_series.  There is no clean option with the Photosmart_C3100 printer choice.

What should I do to get a proper cleaning function for the ink cartridges?

Thanks.

**Comment by michaelrsweet** [comment]
Please contact the HP folks for help with this driver; basically CUPS relies on the printer driver to do printer maintenance stuff.
