### ISSUE TITLE
Unable to build .deb

### ISSUE THREAD

**Issue by mfly** [apple/cups#4831]
packaging/cups.list.in is not up-to-date which results in ```$ make deb ``` failing.
Build log: https://gist.github.com/mfly/fc6f1487afefbf77a833326ecb6f0c34.

It looks like this issue: https://github.com/apple/cups/issues/4518 was solved only partially and banner files still exist in cups.list.in. There is a similar problem with files in doc/help/.

**Comment by michaelrsweet** [comment]
Closing this one, tracking with PR #4832.
