### ISSUE TITLE
Cups 2.1.3 Admin Login Fails when root password same as a user password

### ISSUE THREAD

**Issue by carlocapocasa** [apple/cups#4840]
To reproduce:

1. Set root password of a linux test system to foobar22
1. Set password of current user to foobar22
1  Go to localhost:631 in Cups 2.1.3
1. Click "Administration"
1. Click "Add Printer"
1. Enter root as username, foobar22 as password

Expected behavior: Login occurs
Actual behavior: The baseauth password form is displayed again, as is default browser behavior for an incorrect password

I was unable to come up with a specific scenario, but there is a theoretical security issue with this, because information about user passwords is leaked to the root user (and potentially any user with cups admin access)

**Comment by michaelrsweet** [comment]
What Linux distribution?

Are you compiling CUPS from source or using a package from the distribution?

**Comment by carlocapocasa** [comment]
Thank you for your reply Michael.

I am using a [binary package from Arch linux](https://www.archlinux.org/packages/extra/x86_64/cups/).

**Comment by michaelrsweet** [comment]
OK, I can't reproduce this at all... :/

Can you enable debug logging ("cupsctl --debug-logging" from the command-line as root), try the web interface again, and then attach a copy of your /var/log/cups/error_log file?

**Comment by carlocapocasa** [comment]
Thanks for checking. I'll get back to you.

**Comment by carlocapocasa** [comment]
Sorry for the delay, here it is.

https://gist.githubusercontent.com/carlocapocasa/e419d51a4a049f3b96abdf3082479e4a/raw/eb37a310d5de0ba019f3e850a11036ee4471c00f/gistfile1.txt
