### ISSUE TITLE
delete printer not working

### ISSUE THREAD

**Issue by rick212** [apple/cups#4842]
I can't delete printer Brother DCP7055.  After providing computer ID and password (Fedora23) the site displays <forbidden>. 
![delete_printer_-_cups_2 1 3_-_2016-06-15_23 04 01](https://cloud.githubusercontent.com/assets/19961938/16099036/073add4a-334e-11e6-91a1-2d08e781ae87.png)

**Comment by michaelrsweet** [comment]
You need to use the root username and password on Fedora.

**Comment by rick212** [comment]
I used it, it says <forbidden>

**Comment by michaelrsweet** [comment]
Please enable debug logging (cupsctl --debug-logging), try it again, and attach your /var/log/cups/error_log file here.

**Comment by rick212** [comment]
cupsctl on terminal and from root renders:


[Rick@tirex yum.repos.d]$ cupsctl --debug-logging
cupsctl: Forbidden

On Thu, Jun 16, 2016 at 9:12 PM, Michael R Sweet <notifications@github.com>
wrote:

> Please enable debug logging (cupsctl --debug-logging), try it again, and
> attach your /var/log/cups/error_log file here.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/apple/cups/issues/4842#issuecomment-226599681>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ATCYUntmdxMNyFu2or4oK8n6G72XHmVbks5qMa4RgaJpZM4I22Dt>
> .
>

Page 1 (<troubleshoot.SchedulerNotRunning.SchedulerNotRunning object at 0x7fbb75d6d828>):
{'cups_connection_failure': False}
Page 2 (<troubleshoot.ChoosePrinter.ChoosePrinter object at 0x7fbb75d87ef0>):
{'cups_dest': <cups.Dest DCP7055 (default)>,
 'cups_instance': None,
 'cups_queue': 'DCP7055',
 'cups_queue_listed': True}
Page 3 (<troubleshoot.CheckPrinterSanity.CheckPrinterSanity object at 0x7fbb75d87c88>):
{'cups_device_uri_scheme': 'usb',
 'cups_printer_dict': {'device-uri': 'usb://Brother/DCP-7055?serial=E69740G1N747677',
                       'printer-info': 'Brother DCP-7055',
                       'printer-is-shared': False,
                       'printer-location': '04f9:0248',
                       'printer-make-and-model': 'Brother DCP7055 for CUPS',
                       'printer-state': 3,
                       'printer-state-message': '',
                       'printer-state-reasons': ['none'],
                       'printer-type': 10620932,
                       'printer-uri-supported': 'ipp://localhost/printers/DCP7055'},
 'cups_printer_remote': False,
 'is_cups_class': False,
 'local_cups_queue_attributes': {'charset-configured': 'utf-8',
                                 'charset-supported': ['us-ascii', 'utf-8'],
                                 'color-supported': False,
                                 'compression-supported': ['none', 'gzip'],
                                 'copies-default': 1,
                                 'copies-supported': (1, 9999),
                                 'cups-version': '2.1.3',
                                 'device-uri': 'usb://Brother/DCP-7055?serial=E69740G1N747677',
                                 'document-format-default': 'application/octet-stream',
                                 'document-format-supported': ['application/octet-stream',
                                                               'application/pdf',
                                                               'application/postscript',
                                                               'application/vnd.adobe-reader-postscript',
                                                               'application/vnd.cups-command',
                                                               'application/vnd.cups-pdf',
                                                               'application/vnd.cups-pdf-banner',
                                                               'application/vnd.cups-postscript',
                                                               'application/vnd.cups-raster',
                                                               'application/vnd.cups-raw',
                                                               'application/x-cshell',
                                                               'application/x-csource',
                                                               'application/x-perl',
                                                               'application/x-shell',
                                                               'image/gif',
                                                               'image/jpeg',
                                                               'image/png',
                                                               'image/pwg-raster',
                                                               'image/tiff',
                                                               'image/x-bitmap',
                                                               'image/x-photocd',
                                                               'image/x-portable-anymap',
                                                               'image/x-portable-bitmap',
                                                               'image/x-portable-graymap',
                                                               'image/x-portable-pixmap',
                                                               'image/x-sgi-rgb',
                                                               'image/x-sun-raster',
                                                               'image/x-xbitmap',
                                                               'image/x-xpixmap',
                                                               'image/x-xwindowdump',
                                                               'text/css',
                                                               'text/html',
                                                               'text/plain'],
                                 'finishings-default': 3,
                                 'finishings-supported': [3],
                                 'generated-natural-language-supported': ['en-gb'],
                                 'ipp-features-supported': ['subscription-object'],
                                 'ipp-versions-supported': ['1.0',
                                                            '1.1',
                                                            '2.0',
                                                            '2.1'],
                                 'ippget-event-life': 15,
                                 'job-cancel-after-default': 10800,
                                 'job-cancel-after-supported': (0,
                                                                2147483647),
                                 'job-creation-attributes-supported': ['copies',
                                                                       'finishings',
                                                                       'ipp-attribute-fidelity',
                                                                       'job-hold-until',
                                                                       'job-name',
                                                                       'job-priority',
                                                                       'job-sheets',
                                                                       'media',
                                                                       'media-col',
                                                                       'multiple-document-handling',
                                                                       'number-up',
                                                                       'output-bin',
                                                                       'orientation-requested',
                                                                       'page-ranges',
                                                                       'print-color-mode',
                                                                       'print-quality',
                                                                       'printer-resolution',
                                                                       'sides'],
                                 'job-hold-until-default': 'no-hold',
                                 'job-hold-until-supported': ['no-hold',
                                                              'indefinite',
                                                              'day-time',
                                                              'evening',
                                                              'night',
                                                              'second-shift',
                                                              'third-shift',
                                                              'weekend'],
                                 'job-ids-supported': True,
                                 'job-k-limit': 0,
                                 'job-k-octets-supported': (0, 47929224),
                                 'job-page-limit': 0,
                                 'job-priority-default': 50,
                                 'job-priority-supported': [100],
                                 'job-quota-period': 0,
                                 'job-settable-attributes-supported': ['copies',
                                                                       'finishings',
                                                                       'job-hold-until',
                                                                       'job-name',
                                                                       'job-priority',
                                                                       'media',
                                                                       'media-col',
                                                                       'multiple-document-handling',
                                                                       'number-up',
                                                                       'output-bin',
                                                                       'orientation-requested',
                                                                       'page-ranges',
                                                                       'print-color-mode',
                                                                       'print-quality',
                                                                       'printer-resolution',
                                                                       'sides'],
                                 'job-sheets-default': ('none', 'none'),
                                 'job-sheets-supported': ['none',
                                                          'classified',
                                                          'confidential',
                                                          'form',
                                                          'secret',
                                                          'standard',
                                                          'topsecret',
                                                          'unclassified'],
                                 'jpeg-k-octets-supported': (0, 47929224),
                                 'jpeg-x-dimension-supported': (0, 65535),
                                 'jpeg-y-dimension-supported': (1, 65535),
                                 'marker-change-time': 0,
                                 'media-bottom-margin-supported': [423],
                                 'media-col-supported': ['media-bottom-margin',
                                                         'media-left-margin',
                                                         'media-right-margin',
                                                         'media-size',
                                                         'media-source',
                                                         'media-top-margin',
                                                         'media-type'],
                                 'media-default': 'iso_a4_210x297mm',
                                 'media-left-margin-supported': [635],
                                 'media-right-margin-supported': [635,
                                                                  600,
                                                                  1270],
                                 'media-source-supported': ['manual',
                                                            'tray-1'],
                                 'media-supported': ['na_letter_8.5x11in',
                                                     'na_legal_8.5x14in',
                                                     'na_executive_7.25x10.5in',
                                                     'iso_a4_210x297mm',
                                                     'iso_a5_148x210mm',
                                                     'iso_a6_105x148mm',
                                                     'na_number-10_4.125x9.5in',
                                                     'na_monarch_3.875x7.5in',
                                                     'iso_dl_110x220mm',
                                                     'iso_c5_162x229mm',
                                                     'om_env-isob-5_176.04x250.12mm',
                                                     'om_env-isob-6_124.88x176.04mm'],
                                 'media-top-margin-supported': [423],
                                 'multiple-document-handling-supported': ['separate-documents-uncollated-copies',
                                                                          'separate-documents-collated-copies'],
                                 'multiple-document-jobs-supported': True,
                                 'multiple-operation-time-out': 300,
                                 'multiple-operation-time-out-action': 'process-job',
                                 'natural-language-configured': 'en-gb',
                                 'notify-attributes-supported': ['printer-state-change-time',
                                                                 'notify-lease-expiration-time',
                                                                 'notify-subscriber-user-name'],
                                 'notify-events-default': ['job-completed'],
                                 'notify-events-supported': ['job-completed',
                                                             'job-config-changed',
                                                             'job-created',
                                                             'job-progress',
                                                             'job-state-changed',
                                                             'job-stopped',
                                                             'printer-added',
                                                             'printer-changed',
                                                             'printer-config-changed',
                                                             'printer-deleted',
                                                             'printer-finishings-changed',
                                                             'printer-media-changed',
                                                             'printer-modified',
                                                             'printer-restarted',
                                                             'printer-shutdown',
                                                             'printer-state-changed',
                                                             'printer-stopped',
                                                             'server-audit',
                                                             'server-restarted',
                                                             'server-started',
                                                             'server-stopped'],
                                 'notify-lease-duration-default': 86400,
                                 'notify-lease-duration-supported': (0,
                                                                     2147483647),
                                 'notify-max-events-supported': [100],
                                 'notify-pull-method-supported': ['ippget'],
                                 'notify-schemes-supported': ['dbus',
                                                              'mailto',
                                                              'rss'],
                                 'number-up-default': 1,
                                 'number-up-supported': [1, 2, 4, 6, 9, 16],
                                 'operations-supported': [2,
                                                          4,
                                                          5,
                                                          6,
                                                          8,
                                                          9,
                                                          10,
                                                          11,
                                                          12,
                                                          13,
                                                          16,
                                                          17,
                                                          18,
                                                          19,
                                                          20,
                                                          21,
                                                          22,
                                                          23,
                                                          24,
                                                          25,
                                                          26,
                                                          27,
                                                          28,
                                                          34,
                                                          35,
                                                          37,
                                                          38,
                                                          56,
                                                          57,
                                                          59,
                                                          16385,
                                                          16386,
                                                          16387,
                                                          16388,
                                                          16389,
                                                          16390,
                                                          16391,
                                                          16392,
                                                          16393,
                                                          16394,
                                                          16395,
                                                          16396,
                                                          16397,
                                                          16398,
                                                          16399,
                                                          16423,
                                                          14],
                                 'orientation-requested-default': None,
                                 'orientation-requested-supported': [3,
                                                                     4,
                                                                     5,
                                                                     6],
                                 'output-bin-default': 'face-down',
                                 'output-bin-supported': ['face-down'],
                                 'page-ranges-supported': True,
                                 'pages-per-minute': 18,
                                 'pdf-k-octets-supported': (0, 47929224),
                                 'pdf-versions-supported': ['adobe-1.2',
                                                            'adobe-1.3',
                                                            'adobe-1.4',
                                                            'adobe-1.5',
                                                            'adobe-1.6',
                                                            'adobe-1.7',
                                                            'iso-19005-1_2005',
                                                            'iso-32000-1_2008',
                                                            'pwg-5102.3'],
                                 'pdl-override-supported': ['attempted'],
                                 'port-monitor': 'none',
                                 'port-monitor-supported': ['none'],
                                 'print-color-mode-default': 'monochrome',
                                 'print-color-mode-supported': ['monochrome'],
                                 'print-quality-default': 4,
                                 'print-quality-supported': [4],
                                 'printer-commands': ['AutoConfigure',
                                                      'Clean',
                                                      'PrintSelfTestPage'],
                                 'printer-config-change-date-time': '(IPP_TAG_DATE)',
                                 'printer-config-change-time': 1466006406,
                                 'printer-current-time': '(IPP_TAG_DATE)',
                                 'printer-dns-sd-name': None,
                                 'printer-error-policy': 'stop-printer',
                                 'printer-error-policy-supported': ['abort-job',
                                                                    'retry-current-job',
                                                                    'retry-job',
                                                                    'stop-printer'],
                                 'printer-geo-location': '(unknown IPP '
                                                         'value tag 0x12)',
                                 'printer-get-attributes-supported': ['document-format'],
                                 'printer-icons': 'http://localhost/icons/DCP7055.png',
                                 'printer-info': 'Brother DCP-7055',
                                 'printer-is-accepting-jobs': True,
                                 'printer-is-shared': False,
                                 'printer-location': '04f9:0248',
                                 'printer-make-and-model': 'Brother DCP7055 '
                                                           'for CUPS',
                                 'printer-more-info': 'http://localhost/printers/DCP7055',
                                 'printer-name': 'DCP7055',
                                 'printer-op-policy': 'default',
                                 'printer-op-policy-supported': ['authenticated',
                                                                 'default'],
                                 'printer-organization': '',
                                 'printer-organizational-unit': '',
                                 'printer-resolution-default': (600, 600, 3),
                                 'printer-resolution-supported': [(600,
                                                                   600,
                                                                   3),
                                                                  (2400,
                                                                   600,
                                                                   3)],
                                 'printer-settable-attributes-supported': ['printer-geo-location',
                                                                           'printer-info',
                                                                           'printer-location',
                                                                           'printer-organization',
                                                                           'printer-organizational-unit'],
                                 'printer-state': 3,
                                 'printer-state-change-date-time': '(IPP_TAG_DATE)',
                                 'printer-state-change-time': 1466086442,
                                 'printer-state-message': '',
                                 'printer-state-reasons': ['none'],
                                 'printer-type': 10620932,
                                 'printer-up-time': 1466108502,
                                 'printer-uri-supported': ['ipp://localhost/printers/DCP7055'],
                                 'printer-uuid': 'urn:uuid:02e85c40-8807-379c-4183-a81da4dc58a2',
                                 'queued-job-count': 0,
                                 'server-is-sharing-printers': False,
                                 'sides-default': 'one-sided',
                                 'sides-supported': ['one-sided'],
                                 'uri-authentication-supported': ['requesting-user-name'],
                                 'uri-security-supported': ['none'],
                                 'which-jobs-supported': ['completed',
                                                          'not-completed',
                                                          'aborted',
                                                          'all',
                                                          'canceled',
                                                          'pending',
                                                          'pending-held',
                                                          'processing',
                                                          'processing-stopped']}}
Page 4 (<troubleshoot.CheckPPDSanity.CheckPPDSanity object at 0x7fbb75d87908>):
{'cups_printer_ppd_defaults': {'General': {'BrMediaType': 'PLAIN',
                                           'InputSlot': 'TRAY1',
                                           'PageRegion': 'A4',
                                           'PageSize': 'A4',
                                           'Resolution': '600dpi',
                                           'Sleep': 'PrinterDefault',
                                           'TonerSaveMode': 'OFF'}},
 'cups_printer_ppd_valid': True,
 'missing_pkgs_and_exes': ([], [])}
Page 5 (<troubleshoot.LocalOrRemote.LocalOrRemote object at 0x7fbb75d745c0>):
{'printer_is_remote': False}
Page 6 (<troubleshoot.VerifyPackages.VerifyPackages object at 0x7fbb75d8fa58>):
{'packages_verification': {'cups': ['..?......    '
                                    '/etc/cups/cups-files.conf.default',
                                    '..?......    '
                                    '/etc/cups/cupsd.conf.default',
                                    '..?......    '
                                    '/etc/cups/snmp.conf.default',
                                    '..?......    '
                                    '/usr/lib/cups/backend/dnssd',
                                    '..?......    /usr/lib/cups/backend/ipp',
                                    '..?......    /usr/lib/cups/backend/lpd',
                                    'missing     /var/spool/cups/tmp '
                                    '(Permission denied)'],
                           'foomatic': [],
                           'gutenprint': [],
                           'hpijs': ['package hpijs is not installed'],
                           'hplip': ['package hplip is not installed'],
                           'system-config-printer': []}}
Page 7 (<troubleshoot.PrintTestPage.PrintTestPage object at 0x7fbb75d8f6a0>):
{'test_page_job_status': [], 'test_page_successful': False}
Page 8 (<troubleshoot.Locale.Locale object at 0x7fbb758336a0>):
{'printer_page_size': 'A4',
 'system_locale_lang': 'en_GB',
 'user_locale_ctype': 'en_GB',
 'user_locale_messages': 'en_GB'}

**Comment by michaelrsweet** [comment]
OK, sounds like something is broken with the configuration or the packaging. Please report this to the Fedora folks and see if they have any guidance...
