### ISSUE TITLE
Release tarballs are not GPG-signed anymore

### ISSUE THREAD

**Issue by OdyX** [apple/cups#4843]
Hi Mike,

As I was about to start packaging the 2.1.4 new release for Debian, I noticed that the tarballs are not accompanied with GPG signatures anymore. Since 1.7.0, I could always authenticate the new upstream tarballs against the 0xDBA3A7AB08D76223 GPG key, and now I couldn't find any signatures for 2.1.4 or 2.2b1. Would it be imaginable to reintroduce these signatures alongside the releases (current and future)?

Thanks in advance, cheers,

OdyX

**Comment by michaelrsweet** [comment]
Didier,

I'll see what I can do - Github doesn't make it easy to associate GPG signatures with uploads, so they'll just show up as extra download files...

**Comment by michaelrsweet** [comment]
OK, I think I have all of the signatures up now...
