### ISSUE TITLE
CUPS consume CPU and stop to respond

### ISSUE THREAD

**Issue by ELHG** [apple/cups#4848]
We have cups 1.4.2-72 version on RHEL 6.7 production servers
It arrives often that cups consume a high cpu and then it stop to respond, then we should restart cupsd to becoming responding again
We don't know what is the cause of this issue
I notice that even when we create many printers one after the other, the CPU usage increases by cuspd and then cups stucks

we need to know why cupsd react this way and how to fix it

Thank you in advance for your help

**Comment by michaelrsweet** [comment]
CUPS 1.4.2 is obsolete.

Please contact Red Hat for assistance with their version of CUPS.
