### ISSUE TITLE
Add support for printer-input-tray attribute

### ISSUE THREAD

**Issue by mfly** [apple/cups#4849]
As described in PWG's [IPP: Job and Printer Extensions – Set 3](http://ftp.pwg.org/pub/pwg/candidates/cs-ippjobprinterext3v10-20120727-5100.13.pdf).
For IPP-enabled printers supporting this attribute, information can be obtained directly via IPP. For other networked printers, values can be mapped from SNMP as described in the linked document.

**Comment by michaelrsweet** [comment]
We will consider this, however as with all of the other printer state/supply attributes in CUPS, they only get updated when a job is active, and then only when a standard interface or a compatible driver is used.

**Comment by michaelrsweet** [comment]
After much deliberation, support for this attribute will require enhancing the printer driver interface, which is deprecated. Future versions of CUPS will expose this as part of a general relaying of all printer attributes.
