### ISSUE TITLE
Printer State Message not cleared upon successful print job completion.

### ISSUE THREAD

**Issue by bmason-redhat** [apple/cups#4851]
Based on this message (http://cups.org/pipermail/cups-devel/2016-July/016834.html), the IPP `printer-state-message` (`printer->state_message`) should be cleared after the job completes without error.  However, if I submit a job that completes successfully to a socket printer, the printer state message remains "Waiting for printer to finish":

    $ lpstat -p Officejet-6700
    printer Officejet-6700 is idle.  enabled since Tue 05 Jul 2016 08:24:21 AM PDT
        Waiting for printer to finish.

This is with CUPS 2.1.3 in Fedora 23, but I've looked through the cups-master branch and can't seem to find any code that would clear `job->printer->state_message` when a job completes successfully.  I would expect to maybe find something in `finalize_job()` since the printer reasons are cleared in there, but I don't see anything in that code to clear the state message.

Does "without error" mean `job->status_level <= CUPSD_LOG_ERROR` when the job completes?  Or does it mean `job->status == 0`? (Or something else?)

Thanks.

**Comment by bmason-redhat** [comment]
Would this work as a patch?
```
diff --git a/scheduler/job.c b/scheduler/job.c
index e6434d9..daaef0f 100644
--- a/scheduler/job.c
+++ b/scheduler/job.c
@@ -3532,6 +3532,15 @@ finalize_job(cupsd_job_t *job,           /* I - Job */
                        printer_state == IPP_PRINTER_STOPPED);
   update_job_attrs(job, 0);
 
+  /*
+   * Clear the printer status message if the job completed successfully.
+   */
+
+  if ( job_state = IPP_JOB_COMPLETED )
+  {
+    job->printer->state_message[0] = '\0';
+  }
+
   if (job->history)
   {
     if (job->status &&
```

**Comment by michaelrsweet** [comment]
No, we want to preserve any error message that was reported, and only clear the printer-state-message string if the job completes without errors.

**Comment by michaelrsweet** [comment]
[master 837dc15] Clear informational messages out of printer-state-message when a job completes (Issue #4851)
