### ISSUE TITLE
Printer Not Working

### ISSUE THREAD

**Issue by mattbatki** [apple/cups#4852]
I have a brother HL-2220 attached to my raspberry pi. There is no specific driver for this printer. I have tried the two drivers closet to where the printers actual driver would be. I have another xerox that is working properly so this must be a driver issue of some sorts. Also I have tried a test print using a windows computer. It worked completely fine.  Any help would be greatly appreciated. Much thanks!!

**Comment by michaelrsweet** [comment]
We don't actually ship a driver for this printer in CUPS...  The Brother web site lists the language support as "GDI" which basically means you need a specific driver from Brother for it, but I don't think Brother supports ARM CPUs... :(

Sorry, not much we can do to help you here...

**Comment by mattbatki** [comment]
Thank you for the help. Was never aware brother didn't support ARM on their
HL-2220.
