### ISSUE TITLE
Feature Request: IPDS Support

### ISSUE THREAD

**Issue by LaxSlash** [apple/cups#4853]
It would be nice if CUPS would support IPDS Emulation/IPDS Server Emulation, and accept jobs from an AS/400, IBM Mainframe, or other sources in the form of an IPDS or AFP print job, as well as be an interface for communication between the normal printer and the print job source.

**Comment by michaelrsweet** [comment]
Unfortunately, IPDS is not easily supported nor emulated. There are a few companies that specialize in this sort of thing but generally only for embedding in commercial products and not open source projects.

Adding IPDS support would be a project all on its own and is far outside the scope of what we are trying to do for CUPS...
