### ISSUE TITLE
Rewriting status code in add_printer() function

### ISSUE THREAD

**Issue by dimV36** [apple/cups#4854]
I use CUPS 2.1.3.

When we send CUPS-Add-Modify-Printer request to CUPS, CUPS call function add_printer(). During the function add_printer() calling, CUPS call set_printer_defaults() function.

Setting of some defaults attributes (like printer's policy name) is implied in function set_printer_defaults(), which can send error (via send_ipp_status()), if something bad and returns.
But at the end of function add_printer() I see, that

 con->response->request.status.status_code = IPP_OK;

So, status code (that could be not IPP_OK) is rewriting by this row. So on, we have error message like client-not-possible-error and Cups-Add-Modify-Printer returns IPP_OK in log. 

My proposals:

1. Move the row    
       con->response->request.status.status_code = IPP_OK; 

  from end of add_printer() function to start. 
2. Check status code after calling set_printer_defaults() and if status is not IPP_OK return from add_printer() function.

**Comment by michaelrsweet** [comment]
[master f0b589f] The CUPS-Add-Modify-Class and CUPS-Add-Modify-Printer operations did not always return an error for failed adds (Issue #4854)
