### ISSUE TITLE
How to get the ipp-device uri from a unknown printing device

### ISSUE THREAD

**Issue by frazhome** [apple/cups#4855]
A lot of printers support printing via ipp, but the printer vendors seldom document the device-uri for printing.

is there a list available about device-uri's versus devices?
could I use the ipptool to get out the uri from the device?

I hope anybody could help.

**Comment by IslandCow** [comment]
Frequently, printers are advertised using Bonjour which is documented here https://developer.apple.com/bonjour/printing-specification/bonjourprinting-1.2.pdf.  The queue name is listed under "rp" and the ip address should be discoverable using mDNS.  You can use avahi-browse to resolve mDNS advertisements on your network.

**Comment by frazhome** [comment]
You are right Bonjour could be helpfull, I am working in a managed environment.
Bonjour is only woring inside of a broadcast domain.
Bonjour is anounciing the device-uri and most of this devices are using app-socket connection.

I am looking for something to get the ipp device-uri or a list of this

**Comment by michaelrsweet** [comment]
You might be able to use ipptool to get the proper printer URI, but then you need to know a working URI for the printer to return the information...

Most new printers use /ipp/print as the resource path. Older printers use:

- Epson: /Epson_IPP_Printer
- Brother, Canon, Samsung, some others: /ipp/printer
- HP: /printers/Laserjet, /ipp/port1
- Fuji-Xerox: /ipp/ap
- Others: /printer
