### ISSUE TITLE
Minor documentation issue and encryption support question

### ISSUE THREAD

**Issue by enoha** [apple/cups#4856]
In the 2.1.4 release install.txt file, it says: "Besides these tools you'll want ZLIB library for compression support, the CDSA, GNU TLS, or OpenSSL libraries for encryption support" .. My understanding is starting CUPS 2.0, support for OpenSSL has been dropped, is that correct? We are currently using a pre 2.0 version and are having a problem switching to 2.0+ due to this since we build CUPS for Android and GNU TLS is not available.

**Comment by michaelrsweet** [comment]
[master bfbcda7] Don't mention OpenSSL, clarify macOS instructions.

**Comment by michaelrsweet** [comment]
This will be fixed in the 2.2 release.
