### ISSUE TITLE
CUPS "Class" neither load balances nor fails over as I would expect

### ISSUE THREAD

**Issue by garycarroll** [apple/cups#4859]
From an Apple publication:
“Print jobs are sent to the next available printer in the class, so you can have as many jobs printing simultaneously as you have printers assigned to the class. If a printer is unavailable for any reason, the other printers in the class continue to print waiting jobs. Printer class queues are configured in Printer Setup Utility and, like any other queue, are managed using Server Admin.”
This seems to indicate jobs for an unavailable printer will go to the first available printer. 
But what I seem to see in my limited testing is “round – robin” load balancing: each new job is sent to the printer in the class that has gone the longest without being sent a new job, irrespective of whether the first printer is available. Also, without regard to the number of pages actually sent – if four jobs are sent to a two-printer class, with the first job being 1000 pages long, the 1000 page job would go to printer one, job two to printer two, job three to printer one, and job four to printer two. Obviously, this is not what would have been preferred… when job three comes in printer one is busy, but printer two is available.
More seriously, jobs continue to be sent to a printer that is “down” and not printing at all.
How does one get failover behavior, with or without the round-robin?

**Comment by michaelrsweet** [comment]
First, classes are round-robin only. There is no way to select another scheduling algorithm.

Second, failover depends on the backend supporting the CLASS environment variable. All of the standard CUPS backends do this. None (or few) of the third-party backends do it - "lpstat -v" will show the device URIs, where the scheme name is the backend. What backends are you using?

**Comment by garycarroll** [comment]
Garys-Mac-Pro:~ garycarroll$ lpstat -v
device for RICOH_Aficio_SP_C240SF: usb://RICOH/Aficio%20SP%20C240SF?serial=RH408F75 <usb://RICOH/Aficio%20SP%20C240SF?serial=RH408F75>

But, others will certainly be used other times, mostly I would be concerned with network PostScript or PCL printers. 
Round Robin is acceptable. 
The goal is that if a device becomes busy by printing a large job (tied up for a long time) it will come out of the rotation until it’s free, and jobs will be apportioned to devices that are idle.

Thanks for your response!
