### ISSUE TITLE
"algorithm" field is not supported in the WWW-Authenticate header of a 401 response

### ISSUE THREAD

**Issue by NE21** [apple/cups#4862]
When the printer responds with a 401 and states in the response header that it supports sha256 and md5, the response sent back does not contain the algorithm to be used and hence the printer uses md5. Is there a way to configure the use of sha256 when the printer supports it? We're using `cupsDoIORequest` to make the request with CUPS version 1.6.3. Thank you

**Comment by michaelrsweet** [comment]
The algorithm field is brand new in the latest HTTP Digest update and is not supported by any version of CUPS right now (and very little client software at all).

I'll use this bug to track adding support in a future release (but not 2.2...)

**Comment by michaelrsweet** [comment]
We will also use this bug to track supporting multiple WWW-Authenticate header values so that we can choose among the supported ways to authenticate.

**Comment by michaelrsweet** [comment]
Quite the substantial set of changes, but I think we've ended up in a happy place...

[master 2b4f6f21a] Support the latest HTTP Digest authentication specification (Issue #4862)
