### ISSUE TITLE
Private libraries libcups{cgi,mime,ppdc} should be installed in a private directory

### ISSUE THREAD

**Issue by OdyX** [apple/cups#4863]
Since d825017aa0d372b0c72e777b7fd7b4e61a2f544e, `libcupscgi.so.1`, `libcupsmime.so.1` and `libcupsppdc.so.1` don't have their staticly compiled counterparts (.a) or their headers (.h) shipped anymore, as they're claimed to be private API.

They should therefore not be shipped in the public `${libdir}`, but in a cups-specific subdirectory (such as ` ${libdir}/cups`)

**Comment by michaelrsweet** [comment]
This isn't something we can do without causing MASSIVE dynamic linker pain on multiple OS's. Sorry, but no thanks.
