### ISSUE TITLE
switch of localization.

### ISSUE THREAD

**Issue by frazhome** [apple/cups#4864]
How could I disable the localization of the web interface.

I modified /extend the templates of the web interface, but I am not able to do the translations to the different languages.

So I want to run the web-interface only in english.
Which parameter has to be set, to achieve this.

**Comment by michaelrsweet** [comment]
The web interface gets the language from the web browser. Changing the default language in the web interface depends on the browser and OS, but once you tell the browser to use English you'll get the English web interface, etc.

**Comment by frazhome** [comment]
I know this behaviour. 

but this is not helpfull. I changed my own browser, but there are a lot of people around where I could not change the defautl language (spain/czech/chinese/portugies).

Is there now additional way to change everything to english?

**Comment by michaelrsweet** [comment]
Not at this time, no.

About all you could do is delete all of the language subdirectories from /usr/share/cups/templates so that only the English (fallback) files are used.
