### ISSUE TITLE
`cupsctl --no-remote-any` is defunct

### ISSUE THREAD

**Issue by leoarnold** [apple/cups#4866]
On several CUPS versions up to and including 2.1.3, I noticed that

```
cupsctl --remote-any
```

will act as expected, but

```
cupsctl --no-remote-any
```

fails to reverse the effect. The server stays reachable.

**On CUPS 1.7.5:** Initial `cupsd.conf`

```
Listen localhost:631

[...]

# Restrict access to the server...
<Location />
  Order allow,deny
</Location>
```

After enabling

```
# Allow remote access
Port 631

[...]

<Location />
  # Allow remote access...
  Order allow,deny
  Allow all
</Location>
```

After trying to disable

```
Port 631

[...]

<Location />
  Order allow,deny
  Allow all
</Location>
```

only the comments vanish.

**Comment by michaelrsweet** [comment]
Investigating, but this code hasn't changed in a long time... :/

**Comment by michaelrsweet** [comment]
Possibly identified the problem, doing some regression testing...

**Comment by michaelrsweet** [comment]
[master 6720d4f] The --no-remote-any option of cupsctl had no effect (Issue #4866)
