### ISSUE TITLE
Add printer-id attribute support

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#4868]
Add support for the "printer-id (integer(1:65535))" Printer Status attribute.

Todo:
- Add printer_id to cupsd_printer_t
- Support for filtering in CUPS-Get-Printers?
- Add NextPrinterId to printers.conf
- Assign next printer-id value in LoadAllPrinters/Classes/add_printer/add_class

**Comment by xuwenlong02** [comment]
some printer does'nt have a printer-id,how to add it ?

**Comment by michaelrsweet** [comment]
@xuwenlong02 There is currently no way to provide a printer-id from CUPS. That is the purpose of this bug...

**Comment by michaelrsweet** [comment]
[master 409f54979] Add support for "printer-id" attribute (Issue #4868)
