### ISSUE TITLE
Epson XP-860

### ISSUE THREAD

**Issue by BelgraveUser** [apple/cups#4871]
Hi I have set up Cups to recognise my printer. Everything looks fine until I come to print say a test page. Printer goes into action and starts to print a blank page then another and another add infinitum.
Looks like I am nearly there but not.
Anyone give me a clue where to go?

**Comment by michaelrsweet** [comment]
You'll need a printer driver for this printer; Gutenprint is probably your best option at this point, unless you are on a Mac in which case the AirPrint path should work out of the box.

You might also be able to get help from the CUPS user list...

**Comment by BelgraveUser** [comment]
Thanks for that,

 

My system already recognises the printer and uses the Gutenprint driver. Everything looks fine but although the printer works when prompted there is no text printed and it continues to print blank pages until I cancel.

 

 

David Bate

1 Belgrave Place

Birkdale

Southport

Merseyside

PR8 2EF

01704 564 132

07836 328 614
