### ISSUE TITLE
Single Pages are printed on the wrong side of letter paper

### ISSUE THREAD

**Issue by nsanli** [apple/cups#4875]
If we print a single page on letter paper, it cames out on the wrong side of the letter paper (the blank side).

The Difference:
In Documents which are made with Latex-dvips there is "%%Pages: 1" in the Header of the PostScript File.
In Documents which are made with enscript there is " %%Pages: (atend)" in the Header of the PostScript File.

You need to use the "atend" and then "*cupsEvenDuplex: True". After this procedure, everything works fine.

We open a similar Issue 7 years ago. See 
https://www.cups.org/pipermail/cups-devel/2009-February/009231.html

We have workaround this Problem with this selfmade wrapper:
https://hg.intevation.de/adminton/file/default/shebang/pstops-wrapper

This is just a workaround for us, can you please fix this issue?

Friendly regards,

Nadie Sanli

**Comment by michaelrsweet** [comment]
This isn't a CUPS issue, it is a driver issue.
