### ISSUE TITLE
CUPS does not check policy in Print-Job and Create-Job

### ISSUE THREAD

**Issue by dimV36** [apple/cups#4880]
In code of functions print_job() and create_job() (scheduler/ipp.c) call like cupsdCheckPolicy() of validate_user() is missing, but in Policy directive in cupsd.conf those IPP commands are exists.
So, any policy rules will be ignored for those commands.

I use cups 2.2.0 from official release.

**Comment by michaelrsweet** [comment]
The policy is checked in the add_job() function which is called by both create_job() and print_job().
