### ISSUE TITLE
Warnings during CUPS building from source code

### ISSUE THREAD

**Issue by dimV36** [apple/cups#4881]
During compilation I have some warnings (possibly some warning are not dangerous):

1. backend/ieee1284.c: function BackendGetDeviceID():
    /home/developer/git/cups-2.2.0/backend/ieee1284.c:91: warning: conversion to 'unsigned int' from 'int' may change the sign of the result [-Wsign-conversion]

2. scheduler/auth.c: function cupsdCheckGroup():
    auth.c:1186: warning: conversion to '__gid_t' from 'int' may change the sign of the result [-Wsign-conversion]
   auth.c:1186: warning: pointer targets in passing argument 3 of 'getgrouplist' differ in signedness [-Wpointer-sign]

I use CUPS 2.2.0 from official release and gcc 4.7

**Comment by michaelrsweet** [comment]
[master f093225] Address some build warnings on Linux (Issue #4881)
