### ISSUE TITLE
Possible bug with CUPS?

### ISSUE THREAD

**Issue by bweishoff** [apple/cups#4883]
So we're seeing a number of PDF's that we're able to print using Windows.  These very same PDF files refuse to print via CUPS.   I've looked in the cups error logs, and I'm seeing a message "pdftopdf stopped with status 5."   The overall configuration appears to be sound as it prints other PDF files just fine.  The problem is the PDF files are all generated in the same way.   I cranked up the logging to DEBUG per the instructions, but it's really not yielding any more clues -- at least clues that I'm able to recognize as such.

Anyone have some pointers?

Thanks,

**Comment by michaelrsweet** [comment]
This is a cups-filters issue and not something we can fix in CUPS...
