### ISSUE TITLE
Data is not written to a file: device if all filters are NULL ("-")

### ISSUE THREAD

**Issue by mityada** [apple/cups#4889]
If a job doesn't have any not-NULL filters and device has file: URI, no processes are created, so no data is transferred. Job successfully completes without anything being printed.

I guess cupsdContinueJob() should either copy the data directly or create a process which will do that.

I faced this issue when printing from Windows via Samba. Windows driver sends data in printer's native format, so CUPS doesn't have to do any transformations. As a workaround, I added a dummy filter to printer's PPD file.

**Comment by michaelrsweet** [comment]
The file pseudo-device is a) not enabled by default and b) DOES NOT WORK WITHOUT A FILTER.

This is expected and as designed. We do not want to support direct, raw printing to a file.
