### ISSUE TITLE
Tristate radiobutton for select debug|warning|info at the admin webinterfac

### ISSUE THREAD

**Issue by frazhome** [apple/cups#4890]
Since fixing the issue #4815  LogLevel Info is broken.

It possible to get some more interesting informatin in the cups error log.

please extend the checkbox "debug" at the admin-page of the webinterface to a radio button 
- Debug
- Warning
- Info

this would be very helpfull.

**Comment by michaelrsweet** [comment]
Not likely to change anytime soon, but will keep this around as a feature request.

**Comment by michaelrsweet** [comment]
Sorry, after doing a review of open feature requests, we don't believe this will be implemented.
