### ISSUE TITLE
protect template files from updateing

### ISSUE THREAD

**Issue by frazhome** [apple/cups#4891]
I created some extended template files for the webinterface.

how could I protect them from updateing when a update of the package is done?

is there a special subdirectory or anything else to do something lile this?

regards
Franz

**Comment by michaelrsweet** [comment]
This isn't something we support in the CUPS source distribution, and AFAIK none of the Linux distributors do either. On macOS you can't (by default) change the contents  of the /usr/share/cups/templates directory, either...

Generally speaking, it is up to you to re-install your updated template files after updating CUPS (and dealing with any upstream changes...)
