### ISSUE TITLE
using libcups but with an error: bad file descriptor

### ISSUE THREAD

**Issue by yorkie** [apple/cups#4892]
The following is what I'm trying:

```c
cups_dest_t *dests;
int num_dests = cupsGetDests(&dests);
if (num_dests == 0)
    puts(cupsLastErrorString());
```

Then the terminal prints "Bad file descriptor". One more detail about how I use this library:

1. I'm using libcups, so that I have cross-compiled libcups with the above source code successfully in compile time.
2. I don't start any CUPS exec at that runtime machine

So actually my question might be **if possible to have CUPS to be working only with libcups.so**?
Thanks!

**Comment by michaelrsweet** [comment]
This is because cupsGetDests tries, by default, to connect to the local cupsd. If you have no local cupsd, then you'll never see any destinations.

The cupsSetServer function can be used to point to a different server, or you can use the cupsEnumDests API instead to get a list of destinations that is available on the network.

**Comment by yorkie** [comment]
@michaelrsweet could libcups.so work without any cupsd?

**Comment by yorkie** [comment]
By the way, after running cupsd on that machine, but got an error when running `lpstat -a`:

```shell
$ lpstat: No destinations added
```

But I did use the same source to compile to my other macOS and ubuntu machines, both they are working without any configurations :(

**Comment by yorkie** [comment]
> libcups.so in general works without any cupsd

Really, that's cool, may I ask you to detail what's the cupsd's work? and one more question: if there is possible to connect to a network-attached printer and create a job without cupsd? @michaelrsweet May I ask you to make an example to create a printing job with a specific address only with libcups.so?

Thanks so much :)

**Comment by michaelrsweet** [comment]
For a description of how CUPS works in general, see:

    https://www.cups.org/doc/spec-design.html

As for sending a print job to an address, that's not how CUPS or IPP works. If you have a printer's "ipp" or "ipps" URI, you can use the cupsGetDestWithURI API:

    https://www.cups.org/doc/api-cups.html#cupsGetDestWithURI

and then use the cupsDest APIs to create a job and send a document to it. Alternately you can just send IPP requests - that API is documented here:

    https://www.cups.org/doc/api-httpipp.html

**Comment by yorkie** [comment]
Thanks for the detailed answers. And I have some questions still:

> and then use the cupsDest APIs to create a job and send a document to it.

I have successfully got the correct `cups_dest_t` instance, but when trying to use `cupsCreateJob` to create job, this function returns -1 and got an error: "bad file descriptor", so I guess sending a job requires cupsd?

Actually what I'm doing with CUPS is to print something without __cupsd__.

> Alternately you can just send IPP requests - that API is documented here

I guess the IPP API is only the part of making an IPP request, it's a low-level one, and that doesn't handle with filter and raster API.

@michaelrsweet Let me describe more about what I'm doing with CUPS, I'm trying to integrate with an embedded operating system which runs on an x86 arch, so the following is what I have done:

- cross-compiling CUPS to that machine

Because the type of device is resource-limited, thus I don't want running extra service, namely cupsd on runtime, so this is why I hope our programs can directly work with only libcups, and our program will need the following functionality:

- discovery of network-attached printers
- convert PDF to an raster image, maybe libcupsimage?
- send IPP requests to specific printer

Thanks!

**Comment by michaelrsweet** [comment]
Perhaps look at the ippsample project here:

    https://github.com/istopwg/ippsample

which is CUPS-based but provides a much lighter weight solution (ippserver and ipptransform) that is better suited for things like Raspberry Pi's and other assorted embedded SoC solutions. You can just use ipptransform from an application to convert PDF to raster if you want to avoid any kind of a spooler...

**Comment by yorkie** [comment]
That's very cool, thanks for your quick reply :)
