### ISSUE TITLE
Zebra zpl not printing on Z6Mplus printer

### ISSUE THREAD

**Issue by kkoksvik** [apple/cups#4898]
While trying to set up a Z6Mplus printer to use the CUPS zebra zpl driver I find that printing only produces a blank label.

The issue turns out to be (at least with the Z6Mplus printer) that the downloaded graphic is deleted from R(RAM) memory before the label is printed.

I have tracked this issue to filter/rastertolabel.c line 608
`puts("^IDR:CUPS.GRF^FS");`
This line is supposed to delete the downloaded image for this print job to clean up so not to leave anything on the printer after the job has finished.. The problem is that the ^IDR command deletes the image from ram before "^XZ" command is encountered and triggers the print.

I have tested moving the ^IDR:CUPS.GRF^FS command to a seperate section after the ^XZ command:
`
^XA
^IDR:CUPS.GRF^FS
^XZ`
This seams to work properly and cleans up ram after the print.

**Comment by kkoksvik** [comment]
Update:
Doing some more research I have found that the issue is only pressent when my printer is set to zpl mode. When set to zpl2 it prints. 

However there seams to be some issues with orientation depending on:
Label size, custom 
Depending on witch program is being printed from:
lpr prints correct
Libreoffice writer prints 90 deg counterclockwise
Gimp prints 90 deg clockwise

OS Arch
CUPS version 2.2.1

**Comment by michaelrsweet** [comment]
Strange this has never been an issue before - the driver is essentially unchanged for the past 10 years or so... :/

**Comment by michaelrsweet** [comment]
OK, I'm going to leave the driver as-is for now.

**Comment by kkoksvik** [comment]
I do not know what exactly the difference is between zpl and zpl2. The way the driver is named in cups is a bit miss-leading i guess. It should probably be named zpl2 instead of zpl.

Well even though it has been like this for 10 years, the driver does not behave normal when it comes to with, hight, landscape or portrait. 
As far as I can see the printer-driver does not use the orientation settings, so my guts tells me that when the printing application sets the orientation setting the driver do not act upon it?

I would very much like to investigate further, and I would very much appreciate some tips in debugging these issues.

Is there a way of logging all commands from the printing application (what cups receives from application)? Then I could compare between writer,gimp and lpr?

**Comment by michaelrsweet** [comment]
Reopening for potential driver fix pending testing results. The orientation issue is specific to those applications (nothing I can do to "fix" those) but the blank label issue isn't expected (and might be related to the limited memory on the old Z6Mplus you are using...)

**Comment by michaelrsweet** [comment]
OK, I got my hands on a current GX420d.

While I'm not seeing the blank label issue, moving the IDR command after the XZ command doesn't seem to cause any problems either so I'm making that change.

I also tested with some different label/receipt paper sizes and noticed that media < 4" in width was not being centered properly. Will be fixing that issue as well...

Finally, looks like the output is coming out rotated (top of label image isn't on the leading edge) - investigating that one.. :/

**Comment by michaelrsweet** [comment]
[master 29500e1] Fix some issues with the Zebra ZPL printer driver (Issue #4898)

**Comment by kkoksvik** [comment]
Thanks a lot for looking in to this :-), I will try your changes as soon as I am able to install it.

I probably was unclear in my explanation on the blank label issue, I only got that when my printers internal configuration was set to zpl. This problem disappeared when I set it to zpl2. So the naming on the driver should probably be zpl2 instead of zpl.

![screenshot_20161107_162652](https://cloud.githubusercontent.com/assets/1898400/20063349/186559da-a507-11e6-9219-5b1511cb46a5.png)

**Comment by michaelrsweet** [comment]
Thing is, we aren't using any ZPL2 commands, and it should Just Work™ for any ZPL printer... I'll do some more playing to see if I can duplicate the issue.

**Comment by michaelrsweet** [comment]
Hmm, just tried it on my GX420d and I still get the correct label printed in ZPL mode.

What size labels are you trying to print?

**Comment by kkoksvik** [comment]
My labels in the machine is 158mm wide and 209mm high.

I tried many custom sizes within this envelope, but was always confused if the sizes took.

**Comment by michaelrsweet** [comment]
OK, I think I found the reason for the failure in an older edition of the ZPL programming manual:

- With ZPL II, all data fields are formatted as they are received. In standard ZPL, the data
fields are not processed until after the ^XZ (End Format) command is received.

So before the change you suggested, deleting the graphic before the ^XZ caused the blank label. With the change (which is how I was testing with my printer) it works in both ZPL and ZPL2 modes...

So I think you should be good with the updated driver.

**Comment by crishoj** [comment]
Using the ZPL driver, I am unable to get CUPS to print on 80x50mm labels when the label is fed along the long edge. The output always ends up being printed across the label, regardless of the setting for `requested-orientation`, media size, scaling and auto-rotation:

![image](https://user-images.githubusercontent.com/20393/38212673-e413b26c-36be-11e8-859e-d7386e13f8a1.jpeg)

The issue affects both CUPS versions 2.2.7 on Ubuntu and 2.2.5 on High Sierra.

What makes this so odd is that
1. it Just Works™  with CUPS version 1.7.5, and
2. it also works if I artificially expand the PDF document to double height (by adding whitespace below and rotation 180°). I seems that when the document is taller than it is wide, the rotation suddenly behaves as expected.

The printer in question is a Citizen CL-S631 (in Zebra mode):

![untitled](https://user-images.githubusercontent.com/20393/38212927-d1dd426a-36bf-11e8-99ef-b57df9a9f853.png)

Any suggestions on how to debug this would be much appreciated.

**Comment by michaelrsweet** [comment]
@crishoj Please open a new issue; this issue is CLOSED and you are reporting an unrelated issue to an old bug!

**Comment by kylemacfarlane** [comment]
I have a project where I copied the basic ZPL out of rastertolabel and someone has pointed out that ^IDR outside of ^XA/^XZ doesn't seem to always delete the image which I can confirm.

CUPS therefore has the same bug which may have security implications (imagine POS systems) as a copy of the image is being left on the printer.

Wrapping with ^XA/^XZ seems more bulletproof but it seems weird considering that ~DGR works fine outside of a label.

**Comment by michaelrsweet** [comment]
@kylemacfarlane Swapped the ^XZ and ^IDR commands and everything seems to work on my Zebra printer.

[master 5098fdde6] Swap ^IDR and ^XZ commands to make sure that page image is deleted on the label printer. (Why is this even a thing?)

**Comment by michaelrsweet** [comment]
[branch-2.2 fd8245cd0] Mirror ZPL fix from master.

**Comment by kylemacfarlane** [comment]
@michaelrsweet Won't swapping the commands bring back the the problem the OP of this issue had or did that turn out to be something else?

**Comment by michaelrsweet** [comment]
@kylemacfarlane Yes, that's right. Updated changes (tested my on GX420d) pushed with the IDR command in its own ^XA/^XZ section.

[master 03cc81b70] Put IDR command in its own XA/XZ section.

[branch-2.2 c5b991fda] Put IDR command in its own XA/XZ section.

**Comment by kylemacfarlane** [comment]
@michaelrsweet Thanks for fixing it quickly.

BTW the reason deleting is required is because you're supposed to only load fonts, logos, etc to the printer and then print multiple labels reusing the same assets. But nobody is going to fully implement ZPL when sending a 1 bit bitmap to the printer works well enough.

I think even Zebra themselves have accepted this as their newer printers can print PNGs and their very new ones can even do PDFs directly.
