### ISSUE TITLE
still problems with cups-lpd mini-daemon and non unicode characters 

### ISSUE THREAD

**Issue by BIT-SERV-OS** [apple/cups#4899]
Dear all, 

i just rpmbuild 2.2.1 on CENTOS 7.2.1511 and hoped  to avoid utf-8 problems as i found  

'smart_strlcpy()' - Copy a string and convert from ISO-8859-1 to UTF-8 as needed.
in the  source of cups-lpd.

But this implementation does not appear to work for me. I still get errors like this one:

Create-Job client-error-attributes-or-values-not-supported: Bad job-name value: \"job-name\": Bad name value \"CAT<C1>LOGO MAY 2016 [Modo de Compatibilidade].pdf\" - bad UTF-8 sequence (RFC 2911 section 4.1.2).

When some prints from a windows server are spooled to cups-lpr that contains special characters.

May it be that the match does not find all foreign chars or replaces them wrong?

Kind Regards
Olaf

**Comment by JTeichmann** [comment]
I found the problem in the function 'smart_strlcpy()' in the 'scheduler/cups-lpd.c'.
UTF-8 has to look binary like this four possibilities:
0xxxxxxx
110xxxxx 10xxxxxx
1110xxxx 10xxxxxx 10xxxxxx
11110xxx 10xxxxxx 10xxxxxx 10xxxxxx

If it's possibility 2 to 4 only byte one is checked. Byte two, three and four not. For these bytes there has to be proofed something like this:
if ((*srcptr & 0xc0) == 0x80)		/*is second byte starting with 10 (utf-8 has two)*/
    *dstptr++ = *srcptr++;
else
    *dstptr++ = (*srcptr++ >> 2) | 0x80;

I will try it tomorrow and test if the function then works correctly.

**Comment by michaelrsweet** [comment]
[master 5babee8] The cups-lpd program did not catch all legacy usage of ISO-8859-1 (Issue #4899)

Try the changes in TOT and let me know if you still have problems...

**Comment by JTeichmann** [comment]
Hi Michael,

works as designed! Many thanks from Olaf and me for your quick response and support.
Great work.

Cheers
Janek
