### ISSUE TITLE
Kyocera Ecosys P6026cdn needs usb-no-reattach-default=true

### ISSUE THREAD

**Issue by michaelweghorn** [apple/cups#4900]
When printing two documents very quickly after one another on the Kyocera Ecosys P6026cdn connected by USB, the output of the second printout is incorrect.
This was initially detected on an Ubuntu 14.04 based machine. I was able to reliably reproduce the issue by printing the printer test page on Debian unstable; the "cups" package has version 2.2.1-1 there.

The sheet generated for the second print job contains the following content:

~~~
Script interpreter crashes on early name binding,
                                                          % so eliminate all "bind"s by
~~~

It can be fixed by adding the following lines to the USB quirks file (`/usr/share/cups/usb/org.cups.usb-quirks` in Debian):

~~~
# Kyocera Ecosys P6026cdn
0x0482 0x063f no-reattach
~~~

Could you possibly add this to upstream CUPS?

Please let me know in case you need any additional information.

**Comment by michaelrsweet** [comment]
Should hopefully have this added for the next 2.2.x update.

**Comment by michaelweghorn** [comment]
Thank you, that sounds great!

**Comment by michaelrsweet** [comment]
[master dffb0ea] Add a USB quirk rule for the Kyocera Ecosys P6026cdn (Issue #4900)
