### ISSUE TITLE
When CUPS 2.2.1 re-reads past job attributes, it's completely unresponsive

### ISSUE THREAD

**Issue by akorobkin** [apple/cups#4902]
Reproducible on Ubuntu with CUPS 2.2.1. How to reproduce:
1. Make sure CUPS have already printed about 100 jobs (/var/spool/cups should have a ~100 c00XX files). 
2. Run lpstat -a in a loop: "watch lpstat -a" or "while true; do lpstat -a; sleep 2s; done"

Once a minute lpstat will stop for ~20 seconds to return any results. It will either be stuck, or will return "lpstat: Bad file descriptor" message. If you try WebUI, it will also be stuck. ipptool also can't talk to it during this period.

With debug log enabled, you will see that it happens when CUPS starts enumerating past jobs:

```
D [13/Oct/2016:11:14:39 -0700] [Job 70] Loading attributes...
D [13/Oct/2016:11:16:10 -0700] [Job 79] Loading attributes...
D [13/Oct/2016:11:16:10 -0700] [Job 78] Loading attributes...
D [13/Oct/2016:11:16:10 -0700] [Job 77] Loading attributes...
D [13/Oct/2016:11:16:11 -0700] [Job 76] Loading attributes...
D [13/Oct/2016:11:16:11 -0700] [Job 75] Loading attributes...
D [13/Oct/2016:11:16:12 -0700] [Job 74] Loading attributes...
D [13/Oct/2016:11:16:12 -0700] [Job 73] Loading attributes...
D [13/Oct/2016:11:16:12 -0700] [Job 72] Loading attributes...
D [13/Oct/2016:11:16:13 -0700] [Job 71] Loading attributes...
D [13/Oct/2016:11:16:14 -0700] [Job 70] Loading attributes...
```

With 3-4 jobs per second it takes it ~30 sec to enumerate past jobs, during which it completely stops serving any clients. I don't see this with CUPS 2.1.4.

**Comment by michaelrsweet** [comment]
There is some caching of job attributes, but cupsd will unload job history when it has not been accessed in a certain amount of time. When it needs to re-load the job history this will block other clients' access to cupsd, although it definitely should not be this slow.

How large are the "c" files on your system, and what hardware and OS is this on?

**Comment by akorobkin** [comment]
The files are between 1K and 2K in size. CUPS is running on a virtual machine, 2 CPU, 1Gb RAM, Ubuntu 14.04 x64. I didn't see this with CUPS 2.1.3 that was running here previously. 

```
-rw-------  1 root lp   1703 Sep 29 13:20 c00089
-rw-------  1 root lp   1720 Sep 29 13:20 c00090
-rw-------  1 root lp   1703 Sep 29 13:20 c00091
-rw-------  1 root lp   1078 Oct 12 09:55 c00092
-rw-------  1 root lp   1094 Oct 12 09:56 c00093
```

**Comment by michaelrsweet** [comment]
Can you attach your cupsd.conf file?

**Comment by akorobkin** [comment]
[cupsd.conf.txt](https://github.com/apple/cups/files/530300/cupsd.conf.txt)

**Comment by akorobkin** [comment]
I rebuilt CUPS testing the patch for bug #4901 and I can't reproduce this one anymore.

**Comment by michaelrsweet** [comment]
OK, we can re-open if you run into this again...
