### ISSUE TITLE
Build error on Android Standalone Toolchains without poll.

### ISSUE THREAD

**Issue by hudongcheng** [apple/cups#4905]
Hello!
I try to build libcups ([ippsample](https://github.com/istopwg/ippsample) which use the same source core) on my android board,  but the compiler complain:
```
Making all in cups...
Compiling http-addrlist.c...
http-addrlist.c:315:24: error: use of undeclared identifier 'input'
        if (FD_ISSET(fds[i], &input) && !FD_ISSET(fds[i], &error))
                              ^
http-addrlist.c:315:53: error: use of undeclared identifier 'error'
        if (FD_ISSET(fds[i], &input) && !FD_ISSET(fds[i], &error))
                                                           ^
http-addrlist.c:330:29: error: use of undeclared identifier 'error'
        else if (FD_ISSET(fds[i], &error))
                                   ^
3 errors generated.
make[1]: *** [http-addrlist.o] Error 1
make: *** [all] Error 1
```
Is that `input` should be `input_set`, and `error` should be `error_set`?
Can someone help?

**Comment by michaelrsweet** [comment]
Seriously, Android doesn't have poll?!?

**Comment by hudongcheng** [comment]
I am not sure if toolchain problem. Maybe I should try to port libcups source file to a JNI project, and compile with Android Studio.

I followed instruction of https://developer.android.com/ndk/guides/standalone_toolchain.html to install the toolchains. 
```
$ NDK/build/tools/make_standalone_toolchain.py \
    --arch arm --api 21 --install-dir /opt/my-android-toolchain
$ PATH=/opt/my-android-toolchain/bin:$PATH
```
Configure the source, the output said on poll, and can't find poll.h in `/opt/my-android-toolchain/sysroot`:
```
$ ./configure --host=arm-linux-androideabi --prefix=/opt/my-android-toolchain
```

**Comment by hudongcheng** [comment]
I make a mistake. I confirmed that `poll.h` can be found in `/opt/my-android-toolchain/sysroot/usr/include`. So it seems configure did not work properly.

**Comment by michaelrsweet** [comment]
Well, we can track that down as well (probably an issue with cross-compilation) but in the meantime we still want builds for platforms without poll() to work...

**Comment by michaelrsweet** [comment]
[master c750571] Fix builds on systems without a working poll() implementation (Issue #4905)
