### ISSUE TITLE
CUPS printers question

### ISSUE THREAD

**Issue by dimv36** [apple/cups#4906]
Hello,

Printers can have 2 type: shared and local. If we set CUPS to work on TCP (e.g. set ServerName in client.conf), then CUPS will give only shared printers on CUPS-Get-Printers request.

Next, in those configuration I can try to create printer with name, that already exists in CUPS (local printer, that is not shown by CUPS-Get-Printers request), CUPS execute add_printer() function. 

CUPS checks, that printer exists and updates configuration of local printer. Is it correct?

**Comment by michaelrsweet** [comment]
That is an unfortunate side-effect of how printer sharing works, and as long as you have remote administration enabled this is something you can do (configure a printer but not have access to it remotely until you mark it as shared...)
