### ISSUE TITLE
Cups not working inside docker with privileged flag

### ISSUE THREAD

**Issue by xvs32x** [apple/cups#4911]
I have error on start cups service in ubuntu 16.04 and fedora 24 inside docker container with --privileged flag:
`/usr/sbin/cupsd: error while loading shared libraries: libcupsmime.so.1: cannot open shared object file: Permission denied`
Cups versions: 2.*

**Comment by michaelrsweet** [comment]
We do not provide any explicit support for CUPS inside docker containers, nor do we provide pre-compiled containers for use.

Did you build the container yourself or download it from a third-party?

What are the permissions of the named shared library and its parent directories?

**Comment by xvs32x** [comment]
I have tried several third-party apps (for example: https://hub.docker.com/r/gfjardim/cups/), and bult own containers based on official ubuntu and fedora repos. All containers work perfect without --priveleged flag, but in my case i neded usb.
Is not god, but for experiment i have added full permissions (777) for all paths inside container, but is not work

**Comment by michaelrsweet** [comment]
Sorry, not sure we can be any help here, doesn't seem to be a CUPS issue but a container issue... :/
