### ISSUE TITLE
cannot create class with two printers

### ISSUE THREAD

**Issue by zdohnal** [apple/cups#4913]
Hi, 

we encountered this problem on version 2.2.0 . 

Steps to Reproduce:
1.have a 2 printers, created via s-c-printer > find > browse local printer server

# lpstat -v printer1
device for printer1: ipp://s01.brq.redhat.com:631/printers/brno1-5th-cafe-en
# lpstat -v printer-root
device for printer-root: ipp://s01.brq.redhat.com:631/printers/brno2-1st-rec

2. create class with 1 printer: (via s-c-printer):

[root@localhost ~]# lpstat -c class
members of class class:
	printer1

3.  try to add second printer into class:
[root@localhost ~]# lpadmin -p printer-root -c class
lpadmin: The printer or class was not found.
[root@localhost ~]# echo $?
1

# error, s-c-printer has similar error

4. try again, and see what happens:

[root@localhost ~]# lpadmin -p printer-root -c class
[root@localhost ~]# lpstat -c class
members of class class:
	printer-root

Actual results:
it somehow switches one printer for another

Expected results:
class should be with two printers

Additional info:
Its only for this ipp printer searched via s-c-p. If you try to add printer created via socket it works.

Content of error_log (logs are from cups-1.4.3, but this bug exists even on 2.2.0):

STEP 3:

D [25/Oct/2016:04:24:31 -0400] cupsdAcceptClient: skipping getpeercon()
D [25/Oct/2016:04:24:31 -0400] cupsdAcceptClient: 13 from localhost (Domain)
D [25/Oct/2016:04:24:31 -0400] Report: clients=1
D [25/Oct/2016:04:24:31 -0400] Report: jobs=1
D [25/Oct/2016:04:24:31 -0400] Report: jobs-active=0
D [25/Oct/2016:04:24:31 -0400] Report: printers=5
D [25/Oct/2016:04:24:31 -0400] Report: printers-implicit=0
D [25/Oct/2016:04:24:31 -0400] Report: stringpool-string-count=487
D [25/Oct/2016:04:24:31 -0400] Report: stringpool-alloc-bytes=6216
D [25/Oct/2016:04:24:31 -0400] Report: stringpool-total-bytes=10712
D [25/Oct/2016:04:24:31 -0400] cupsdReadClient: 13 POST / HTTP/1.1
D [25/Oct/2016:04:24:31 -0400] cupsdSetBusyState: Active clients
D [25/Oct/2016:04:24:31 -0400] cupsdAuthorize: No authentication data provided.
D [25/Oct/2016:04:24:31 -0400] cupsdReadClient: 13 1.1 Get-Printer-Attributes 1
D [25/Oct/2016:04:24:31 -0400] Get-Printer-Attributes ipp://localhost/classes/class
D [25/Oct/2016:04:24:31 -0400] Returning IPP successful-ok for Get-Printer-Attributes (ipp://localhost/classes/class) from localhost
D [25/Oct/2016:04:24:31 -0400] cupsdSetBusyState: Not busy
D [25/Oct/2016:04:24:31 -0400] cupsdReadClient: 13 POST /admin/ HTTP/1.1
D [25/Oct/2016:04:24:31 -0400] cupsdSetBusyState: Active clients
D [25/Oct/2016:04:24:31 -0400] cupsdAuthorize: No authentication data provided.
D [25/Oct/2016:04:24:31 -0400] cupsdReadClient: 13 1.1 CUPS-Add-Modify-Class 1
D [25/Oct/2016:04:24:31 -0400] CUPS-Add-Modify-Class ipp://localhost/classes/class
D [25/Oct/2016:04:24:31 -0400] cupsdIsAuthorized: username=""
D [25/Oct/2016:04:24:31 -0400] Returning HTTP Unauthorized for CUPS-Add-Modify-Class (ipp://localhost/classes/class) from localhost
D [25/Oct/2016:04:24:31 -0400] cupsdSendHeader: 13 WWW-Authenticate: Basic realm="CUPS", trc="y"
D [25/Oct/2016:04:24:31 -0400] cupsdReadClient: 13 WAITING Closing on EOF
D [25/Oct/2016:04:24:31 -0400] cupsdCloseClient: 13
D [25/Oct/2016:04:24:31 -0400] cupsdSetBusyState: Not busy
D [25/Oct/2016:04:24:31 -0400] cupsdAcceptClient: skipping getpeercon()
D [25/Oct/2016:04:24:31 -0400] cupsdAcceptClient: 13 from localhost (Domain)
D [25/Oct/2016:04:24:31 -0400] cupsdReadClient: 13 WAITING Closing on EOF
D [25/Oct/2016:04:24:31 -0400] cupsdCloseClient: 13
D [25/Oct/2016:04:24:31 -0400] cupsdAcceptClient: skipping getpeercon()
D [25/Oct/2016:04:24:31 -0400] cupsdAcceptClient: 13 from localhost (Domain)
D [25/Oct/2016:04:24:31 -0400] cupsdReadClient: 13 POST /admin/ HTTP/1.1
D [25/Oct/2016:04:24:31 -0400] cupsdSetBusyState: Active clients
D [25/Oct/2016:04:24:31 -0400] cupsdAuthorize: Authorized as root using PeerCred
D [25/Oct/2016:04:24:31 -0400] cupsdReadClient: 13 1.1 CUPS-Add-Modify-Class 1
D [25/Oct/2016:04:24:31 -0400] CUPS-Add-Modify-Class ipp://localhost/classes/class
D [25/Oct/2016:04:24:31 -0400] cupsdIsAuthorized: username="root"
D [25/Oct/2016:04:24:31 -0400] CUPS-Add-Modify-Class client-error-not-found: The printer or class was not found.
D [25/Oct/2016:04:24:31 -0400] Returning IPP client-error-not-found for CUPS-Add-Modify-Class (ipp://localhost/classes/class) from localhost
D [25/Oct/2016:04:24:31 -0400] cupsdSetBusyState: Not busy
D [25/Oct/2016:04:24:31 -0400] cupsdReadClient: 13 WAITING Closing on EOF
D [25/Oct/2016:04:24:31 -0400] cupsdCloseClient: 13

STEP 4:

D [25/Oct/2016:04:24:36 -0400] cupsdAcceptClient: skipping getpeercon()
D [25/Oct/2016:04:24:36 -0400] cupsdAcceptClient: 13 from localhost (Domain)
D [25/Oct/2016:04:24:36 -0400] cupsdReadClient: 13 POST / HTTP/1.1
D [25/Oct/2016:04:24:36 -0400] cupsdSetBusyState: Active clients
D [25/Oct/2016:04:24:36 -0400] cupsdAuthorize: No authentication data provided.
D [25/Oct/2016:04:24:36 -0400] cupsdReadClient: 13 1.1 Get-Printer-Attributes 1
D [25/Oct/2016:04:24:36 -0400] Get-Printer-Attributes ipp://localhost/classes/class
D [25/Oct/2016:04:24:36 -0400] Returning IPP successful-ok for Get-Printer-Attributes (ipp://localhost/classes/class) from localhost
D [25/Oct/2016:04:24:36 -0400] cupsdSetBusyState: Not busy
D [25/Oct/2016:04:24:36 -0400] cupsdReadClient: 13 POST /admin/ HTTP/1.1
D [25/Oct/2016:04:24:36 -0400] cupsdSetBusyState: Active clients
D [25/Oct/2016:04:24:36 -0400] cupsdAuthorize: No authentication data provided.
D [25/Oct/2016:04:24:36 -0400] cupsdReadClient: 13 1.1 CUPS-Add-Modify-Class 1
D [25/Oct/2016:04:24:36 -0400] CUPS-Add-Modify-Class ipp://localhost/classes/class
D [25/Oct/2016:04:24:36 -0400] cupsdIsAuthorized: username=""
D [25/Oct/2016:04:24:36 -0400] Returning HTTP Unauthorized for CUPS-Add-Modify-Class (ipp://localhost/classes/class) from localhost
D [25/Oct/2016:04:24:36 -0400] cupsdSendHeader: 13 WWW-Authenticate: Basic realm="CUPS", trc="y"
D [25/Oct/2016:04:24:36 -0400] cupsdReadClient: 13 WAITING Closing on EOF
D [25/Oct/2016:04:24:36 -0400] cupsdCloseClient: 13
D [25/Oct/2016:04:24:36 -0400] cupsdSetBusyState: Not busy
D [25/Oct/2016:04:24:36 -0400] cupsdAcceptClient: skipping getpeercon()
D [25/Oct/2016:04:24:36 -0400] cupsdAcceptClient: 13 from localhost (Domain)
D [25/Oct/2016:04:24:36 -0400] cupsdReadClient: 13 WAITING Closing on EOF
D [25/Oct/2016:04:24:36 -0400] cupsdCloseClient: 13
D [25/Oct/2016:04:24:36 -0400] cupsdAcceptClient: skipping getpeercon()
D [25/Oct/2016:04:24:36 -0400] cupsdAcceptClient: 13 from localhost (Domain)
D [25/Oct/2016:04:24:36 -0400] cupsdReadClient: 13 POST /admin/ HTTP/1.1
D [25/Oct/2016:04:24:36 -0400] cupsdSetBusyState: Active clients
D [25/Oct/2016:04:24:36 -0400] cupsdAuthorize: Authorized as root using PeerCred
D [25/Oct/2016:04:24:36 -0400] cupsdReadClient: 13 1.1 CUPS-Add-Modify-Class 1
D [25/Oct/2016:04:24:36 -0400] CUPS-Add-Modify-Class ipp://localhost/classes/class
D [25/Oct/2016:04:24:36 -0400] cupsdIsAuthorized: username="root"
D [25/Oct/2016:04:24:36 -0400] cupsdRegisterPrinter(p=0x7feb71c0ec70(class))
D [25/Oct/2016:04:24:36 -0400] cupsdMarkDirty(-C----)
D [25/Oct/2016:04:24:36 -0400] cupsdSetBusyState: Active clients and dirty files
D [25/Oct/2016:04:24:36 -0400] cupsdMarkDirty(---p--)
D [25/Oct/2016:04:24:36 -0400] Discarding unused printer-modified event...
I [25/Oct/2016:04:24:36 -0400] Class "class" modified by "root".
D [25/Oct/2016:04:24:36 -0400] Returning IPP successful-ok for CUPS-Add-Modify-Class (ipp://localhost/classes/class) from localhost
D [25/Oct/2016:04:24:36 -0400] cupsdSetBusyState: Dirty files
D [25/Oct/2016:04:24:36 -0400] cupsdReadClient: 13 WAITING Closing on EOF
D [25/Oct/2016:04:24:36 -0400] cupsdCloseClient: 13
D [25/Oct/2016:04:24:36 -0400] cupsdAcceptClient: skipping getpeercon()
D [25/Oct/2016:04:24:36 -0400] cupsdAcceptClient: 13 from localhost (Domain)
D [25/Oct/2016:04:24:36 -0400] cupsdReadClient: 13 POST / HTTP/1.1
D [25/Oct/2016:04:24:36 -0400] cupsdSetBusyState: Active clients and dirty files
D [25/Oct/2016:04:24:36 -0400] cupsdAuthorize: No authentication data provided.
D [25/Oct/2016:04:24:36 -0400] cupsdReadClient: 13 1.1 Get-Jobs 1
D [25/Oct/2016:04:24:36 -0400] Get-Jobs ipp://localhost/printers/
D [25/Oct/2016:04:24:36 -0400] Returning IPP successful-ok for Get-Jobs (ipp://localhost/printers/) from localhost
D [25/Oct/2016:04:24:36 -0400] cupsdSetBusyState: Dirty files
D [25/Oct/2016:04:24:36 -0400] cupsdReadClient: 13 WAITING Closing on EOF
D [25/Oct/2016:04:24:36 -0400] cupsdCloseClient: 13
D [25/Oct/2016:04:24:36 -0400] cupsdAcceptClient: skipping getpeercon()
D [25/Oct/2016:04:24:36 -0400] cupsdAcceptClient: 13 from localhost (Domain)
D [25/Oct/2016:04:24:36 -0400] cupsdReadClient: 13 POST / HTTP/1.1
D [25/Oct/2016:04:24:36 -0400] cupsdSetBusyState: Active clients and dirty files
D [25/Oct/2016:04:24:36 -0400] cupsdAuthorize: No authentication data provided.
D [25/Oct/2016:04:24:36 -0400] cupsdReadClient: 13 1.1 Get-Notifications 1
D [25/Oct/2016:04:24:36 -0400] Get-Notifications /
D [25/Oct/2016:04:24:36 -0400] cupsdIsAuthorized: requesting-user-name="petr"
D [25/Oct/2016:04:24:36 -0400] Returning IPP successful-ok for Get-Notifications (/) from localhost
D [25/Oct/2016:04:24:36 -0400] cupsdSetBusyState: Dirty files
D [25/Oct/2016:04:24:36 -0400] cupsdReadClient: 13 WAITING Closing on EOF
D [25/Oct/2016:04:24:36 -0400] cupsdCloseClient: 13
I [25/Oct/2016:04:25:08 -0400] Saving classes.conf...
I [25/Oct/2016:04:25:08 -0400] Generating printcap /etc/printcap...
D [25/Oct/2016:04:25:08 -0400] cupsdSetBusyState: Not busy

**Comment by zdohnal** [comment]
I am not sure if it is cups problem, cups-browsed or some issue with our internal net, did someone managed to reproduce it?

**Comment by michaelrsweet** [comment]
I can't reproduce.
