### ISSUE TITLE
Canon i-sensys LBP5050 is not printing in Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by Umeaboy** [apple/cups#4914]
The driver is correctly installed and checking in System settings -> Printers I found the Canon i-sensys LBP5050 printer, but if I try to print a test page nothing happens.

The problem isn't recognising it, the problem is sending prints to it.

What are the things to check?

4.4.0-45-generic is the kernel I'm using.

lsusb says:

Bus 001 Device 003: ID 04a9:26ba Canon, Inc.

and I don't have any other Canon device connected to this computer.

lshw doesn't show it.

dmesg have this information this if I search for Canon:

[    2.113768] usb 1-1.3: New USB device found, idVendor=04a9, idProduct=26ba
[    2.113774] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.113777] usb 1-1.3: Product: Canon CAPT USB Device
[    2.113779] usb 1-1.3: Manufacturer: Canon
[    2.113781] usb 1-1.3: SerialNumber: 0000A1B4TInJ
[    2.183513] usb 1-1.4: new low-speed USB device number 4 using ehci-pci
[    2.279252] usb 1-1.4: New USB device found, idVendor=17ef, idProduct=600e
[    2.279257] usb 1-1.4: New USB device strings: Mfr=0, Product=2, SerialNumber=0

**Comment by Umeaboy** [comment]
CUPS tries to send to the program that Canon uses and that makes the driver program crash. Could be that it is built against an older library, but I'm not sure.

**Comment by Umeaboy** [comment]
Asking Canon to update the driver for Linux doesn't seem to help much according to my research,

**Comment by michaelrsweet** [comment]
This is a Canon driver issue, unfortunately. Not sure there is an open source driver that will work... :/
