### ISSUE TITLE
Reprinting jobs not possible

### ISSUE THREAD

**Issue by BlueMax** [apple/cups#4915]
Hallo,
i'm trying to preserve print jobs so i can reprint them via webinterface. The problem is there is no button for that action in the job history. Also, in /var/spool/cron all files are only around 1k filesize and seem to hold only metadata. I've not changed anything in default cupsd.conf. Only put my user into admin group in 'cups-files.conf'. I've also tried adding the entries below into cupsd.conf. They get reflected properly in the webinterface but still no controls to reprint jobs. The jobs itself are listed but 'controls' column is empty.
>PreserveJobFiles 31d
>MaxJobsPerUser 50
>MaxJobsPerPrinter 50

I also cannot save configuration (cupsd.conf) via webinterface. The service crashes and doesn't revive by itself so i have to manually restart it. Not sure if that's related or if its a distribution dependent problem. I'm using the official Arch package and standard system environment. The last 'debug' level log entries of CUPS (error_log) are:
>D [07/Nov/2016:21:27:18 +0100] PID 3087 (/usr/lib/cups/cgi-bin/admin.cgi) exited with no errors.
>D [07/Nov/2016:21:27:18 +0100] [Client 27] con->http=0x560cc8d84240
>D [07/Nov/2016:21:27:18 +0100] [Client 27] cupsdWriteClient error=0, used=0, state=HTTP_STATE_POST_SEND, data_encoding=HTTP_ENCODING_CHUNKED, data_remaining=0, response=(nil)(), pipe_pid=3087, file=16
>D [07/Nov/2016:21:27:18 +0100] [Client 27] Waiting for CGI data.
>D [07/Nov/2016:21:27:18 +0100] [Client 27] Sending 0-length chunk.
>D [07/Nov/2016:21:27:18 +0100] [Client 27] Flushing write buffer.
>D [07/Nov/2016:21:27:18 +0100] [Client 27] New state is HTTP_STATE_WAITING
>D [07/Nov/2016:21:27:18 +0100] [Client 27] Waiting for request.
>D [07/Nov/2016:21:27:18 +0100] [Client 27] Closing because Keep-Alive is disabled.
>D [07/Nov/2016:21:27:18 +0100] [Client 27] Closing connection.
>D [07/Nov/2016:21:27:18 +0100] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
>E [07/Nov/2016:21:27:18 +0100] Scheduler shutting down due to program error.
>D [07/Nov/2016:21:27:18 +0100] Discarding unused server-stopped event...
>D [07/Nov/2016:21:27:18 +0100] Creating keep-alive file "/var/cache/cups/org.cups.cupsd".
>I [07/Nov/2016:21:27:18 +0100] Saving job.cache...
>D [07/Nov/2016:21:27:18 +0100] cupsdStopSelect()

I'm not sure if i'm missing something here or if its a bug. Printing does work properly though. Any ideas why i cannot reprint jobs?

Linux 4.8.6-1-ARCH x86_64
XFCE
Firefox
cups 2.2.1
Brother HL-2030 (HL-1250 PPD)

**Comment by michaelrsweet** [comment]
Please attach your cupsd.conf file.

**Comment by BlueMax** [comment]
Its this one. Should be default.
http://pastebin.com/rxyk9Egy

**Comment by michaelrsweet** [comment]
What happens if you run "cupsctl PreserveJobFiles=31d" as root? This looks very much like a Linux distribution issue...

**Comment by BlueMax** [comment]
Then the CUPS service dies/crashes. Looks like a bug in Arch (or my system) indeed. I will contact the Arch maintainer. Thank you.

**Comment by BlueMax** [comment]
Looks like any cupsctl command (like cupsctl debuglevel=warn) brings the service down. I've noticed that v2.1.4 works properly and beginning with v2.2.0 its broken. I don't have the specific v2.1.4 Arch patches yet so i cannot continue there at the moment.
Next step would be to test another Linux distribution. By any chance, do you have a Linux system in range (or know about a system) where it works properly (cupsctl doesn't crash)? Otherwise i will setup one tomorrow.

**Comment by BlueMax** [comment]
This is the Arch bug report. They say it's a regression in v2.2.0 upstream.
https://bugs.archlinux.org/task/51774

**Comment by michaelrsweet** [comment]
Then this is probably the same issue as Issue #4870 - can you try with a current release of CUPS?

**Comment by BlueMax** [comment]
Yes, but no change between 'origin/master' and '2.2.1'. Still crashing.

**Comment by michaelrsweet** [comment]
We made some systemd-related changes for Issue #4935 that prevented some of the restart logic from working. Can you re-test with origin/master and report back?

Thanks!

**Comment by BlueMax** [comment]
The service still crashes when i save the configuration in webinterface.

**Comment by michaelrsweet** [comment]
If it is crashing, I need to see a backtrace of the crash. The logs don't show a crash but a normal shutdown/restart sequence.

(you probably need to reboot to get systemd to recognize the changed config files, or at least that is my experience...)

**Comment by BlueMax** [comment]
You're right. It looks like a graceful exit indeed. I cannot squeeze anything out of GDB but 'process exited with error code 01'.
In case its intended behavior that CUPS simply exits on configuration change the culprit should be the systemd unit that doesn't handle any service restarts indeed. I've put a 'restart=always' in the unit file and it works properly now. Unless you say that's not intended and CUPS should restart all by itself i will pass this to the Arch maintainer.

Unfortunately, this bug is not related to the original problem. I still have no controls for preserved documents.
 
[![pic](http://abload.de/thumb/cups23fj5u.png)](http://abload.de/img/cups23fj5u.png) [![pic](http://abload.de/thumb/cups1bgkl7.png)](http://abload.de/img/cups1bgkl7.png)

**Comment by kylemacfarlane** [comment]
I have the same problem. Did a clean install of 2.2.1 from Raspbian stretch and can no longer reprint any jobs.

**Comment by kylemacfarlane** [comment]
Possibly worth pointing out that it's also no longer possible to sort the job list by ID etc. You can cancel or move running jobs but otherwise the jobs page seems to be totally read only even for the admin.

**Comment by Baddawg0509** [comment]
I am having the same issue after upgrading from 1.7.2 to 2.1.3. All reprint options are now gone from the web interface and it appears to be deleting the completed job files. Is there any resolution to this issue?

**Comment by michaelrsweet** [comment]
This is because of the new JobPrivateAccess/Values stuff, which provide fine-grained control over what job information is exposed. Since the job listing on the web interface is not authenticated by default, you don't see the controls for reprinting.

**Comment by michaelrsweet** [comment]
(going to put together a test configuration that we can document for folks to enable authentication on the web interface but not for normal printing, or for disabling the privacy controls so that anyone can reprint a job)

**Comment by kylemacfarlane** [comment]
@michaelrsweet I already have RestartJob allowed for all but it's not working in 2.x like it did in 1.x. Additionally I can't even reprint when logged in as @SYSTEM.

Plus as others have said the jobs are being deleted form the spool.

**Comment by kylemacfarlane** [comment]
@michaelrsweet Also I already have `JobPrivateValues none` because I like to be able to see the user and filenames without logging in.

**Comment by kylemacfarlane** [comment]
@michaelrsweet And some other problems with the jobs page in 2.x that I've noticed:

- "Show all jobs" is sorted ascending but "Show completed jobs" is sorted desc. I can't remember what order active jobs is. It's not a big deal but it is annoying because I can never remember what order each page is supposed to be in.
- The total jobs seems to be off by one, e.g. if `MaxJobs` is set to 500 the jobs page will say "Showing 100 of 499" instead of "of 500".
- The pagination doesn't update with the page, e.g. pages 1, 2, 3, 4 will all say "Showing 100 of 499" instead of "1-100", "101-200", etc so you have to look at the URL to find out what page you're actually on.

**Comment by michaelrsweet** [comment]
@kylemacfarlane The other web interface bugs should be filed as separate issues. This issue just involves the "reprint job" functionality.

Disabling private values should be enough, but there might still be a bug there.

**Comment by kylemacfarlane** [comment]
@michaelrsweet Should I open them as one issue or separate issues? By themselves they're all very minor but add up to make the jobs page kind of frustrating to use.

Also I edited `jobs.tmpl` to echo the values and the reason the reprint button isn't show is because `job_preserved` is always 0 even though the web interface shows:

- Preserve job history = ticked
- Maximum jobs = 500
- Retain Metadata = Yes
- Retain Documents = 1d

**Comment by michaelrsweet** [comment]
@kylemacfarlane One bug for the count and pagination is fine. The order is determined by IPP, and prior releases had this wrong...

For active jobs the order is determined by creation time and priority - typically the order the jobs will be printed (although held jobs end up at the top of the list until released...)

For completed jobs the order is determined by when they completed or were canceled/aborted, newest (most recently completed/canceled/aborted) first.

(perhaps I can add text to the top of the jobs list to this effect...)

**Comment by michaelrsweet** [comment]
OK, looking at this again with the test server; active jobs that are canceled retain their document files, but pending jobs that are canceled lose them. Something appears to be wrong with the logic there, and perhaps that is the reason for the issue the original reporter is seeing?

**Comment by michaelrsweet** [comment]
OK, found the problem.

[master 875ef65a9] The "reprint job" option was not available for some canceled jobs (Issue #4915)
