### ISSUE TITLE
If setting up legacy IPP printer with "lpadmin -m everywhere" an invalid PPD file gets generated

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#4916]
I have some older IPP printers which are no IPP Everywhere printers and if I try to create queues for them with IPP-autogenerated PPDs via the "-m everywhere" option for the "lpadmin" command I get invalid PPD files which fail cupstestppd due to missing "PageSize"/"PageRegion"/"PaperDimension"/"ImageableArea" entries. Also there are no *cupsFilter(2) entries for a useful (PDF, PostScript, PWG Raster) page description language or no entries at all.

So there should be two checks:

1. Presence of "PageSize"/"PageRegion"/"PaperDimension"/"ImageableArea", the only required option in a PPD file
2. Presence of a *cupsFilter(2) line for PWG Raster, PDF, PostScript

Otherwise we would get a print queue which does not work.

**Comment by michaelrsweet** [comment]
First, is this with the latest (git master) code or with the last release?

Second, can you run:

    ipptool -tv ipp://... get-printer-attributes.test

for these printers (substituting the correct device URI of course) and attach the output?

I'm all for updating the private API to error out when we can't generate a proper PPD, but I also want to make this work as reliably as possible.

**Comment by tillkamppeter** [comment]
I have tested on Ubuntu Yakkety (16.10), which has CUPS 2.2.0.

I have used the following two printers: HP Color LaserJet CM3530 MFP and HP OfficeJet Pro 8500 A910. The former is a color laser multi-function printer with PDF and PostScript, but only IPP 1.1. The latter is a color inkjet multi-function printer which can also print photos directly from a camera or SD card.

I have run "ippfind" to get the URIs of these two printers and created print queues with the following command:

lpadmin -p ippevtest -E -v <URI> -m everywhere

for each printer. Both PPDs fail cupstestppd like this:

sudo cupstestppd /etc/cups/ppd/ippevtest.ppd 
[sudo] password for till: 
/etc/cups/ppd/ippevtest.ppd: FAIL
      **FAIL**  REQUIRED DefaultImageableArea
                REF: Page 102, section 5.15.
      **FAIL**  REQUIRED DefaultPaperDimension
                REF: Page 103, section 5.15.
      **FAIL**  REQUIRED PageSize
                REF: Pages 99-100, section 5.14.
      **FAIL**  REQUIRED PageRegion
                REF: Page 100, section 5.14.
      **FAIL**  REQUIRED PageSize
                REF: Page 41, section 5.
                REF: Page 99, section 5.14.
      **FAIL**  Missing REQUIRED PageSize option.
                REF: Page 99, section 5.14.
      **FAIL**  Missing REQUIRED PageRegion option.
                REF: Page 100, section 5.14.
till@till-x1carbon:~/printing/cups/cups$

Meaning that in both cases the PPDs missing entries for the page sizes.

In addition, the PPD for the CM3530 has no *cupsFilter(2) line at all and the inkjet has lines for URF and JPEG, both not useful for printing jobs with CUPS.

**Comment by tillkamppeter** [comment]
Output of the command
ipptool -tv ipp://... get-printer-attributes.test
for both printers attached:

[HP-Color-LaserJet-CM3530-MFP-ipp-attr.txt](https://github.com/apple/cups/files/577080/HP-Color-LaserJet-CM3530-MFP-ipp-attr.txt)
[HP-Officejet-Pro-8500-A910-ipp-attr.txt](https://github.com/apple/cups/files/577081/HP-Officejet-Pro-8500-A910-ipp-attr.txt)

**Comment by michaelrsweet** [comment]
OK, so the CM3530 does not actually support any of the standard PDLs, but we could (conceptually) generate a PPD that uses the sample PCL driver (thinking about that one...)

The OfficeJet should be fixed by the changes for Issue #4909 - please re-test with the current Git code and let me know if that doesn't resolve things for you...

**Comment by michaelrsweet** [comment]
OK, after some further thought I'm not going to support PCL with this function - that's what the sample PCL driver is for. This bug will track returning NULL and deleting any temporary PPD we create if the printer doesn't support enough IPP to work.

**Comment by michaelrsweet** [comment]
[master d4259b4] More IPP Everywhere fixes/improvements (Issue #4916)

**Comment by jhcloos** [comment]
I’m curious:

You write:

MS> the CM3530 does not actually support any of the standard PDLs

but the HP-Color-LaserJet-CM3530-MFP-ipp-attr.txt file Till posted says:

        printer-info (textWithoutLanguage) = MFG:Hewlett-Packard;CMD:PJL,BIDI-ECP,PJL,PCLXL,PCL,PDF,POSTSCRIPT;MDL:HP Color LaserJet CM3530 MFP;CLS:PRINTER;DES:Hewlett-Pack

so it claims that it supports PDF.

**Comment by michaelrsweet** [comment]
But document-format-supported does not list PDF as a supported document format over IPP... :/

**Comment by tillkamppeter** [comment]
Seems to be a firmware bug in the CM3530, probably because in the time when it was introduced one still did not see the necessity that printers should correctly report their capabilities in some standard format.

**Comment by jhcloos** [comment]
>>>>> "MS" == Michael R Sweet <notifications@github.com> writes:

MS> But document-format-supported does not list PDF as a supported
document format over IPP... :/

Ah.  I missed that.

-JimC
-- 
James Cloos <cloos@jhcloos.com>         OpenPGP: 0x997A9F17ED7DAEA6
