### ISSUE TITLE
cupsd: symbol lookup error: cupsd: undefined symbol: httpAddrFamily

### ISSUE THREAD

**Issue by senunpm** [apple/cups#4918]
Debian 8.1
Was running cups 1.7.5.
Installed 2.2.1
After this cups does not start.
\cupsd -t
cupsd: symbol lookup error: cupsd: undefined symbol: httpAddrFamily

After a few installations, ones from scratch other upgrading from 1.7.5 found that the issue is somewhat related with ghostscript.

If CUPS is installed scratch:
after installed from apt-get install ghostscript, cupsd fails to start "cupsd: symbol lookup error: cupsd: undefined symbol: httpAddrFamily". 
If I remove ghostscript, apt-get remove --purge ghostscript, cups starts again.

Help needed?

**Comment by michaelrsweet** [comment]
You need to make sure you have also upgraded the CUPS libraries (libcups) since the 1.7.x libraries do not provide everything the 2.2.1 build needs.

**Comment by senunpm** [comment]
Thanks.
Where can I get the correct version?
Just check and they are 1.7.x

M.

**Comment by evgenmedia** [comment]
Hello, @michaelrsweet !

I have the same issue ;(
After Ghostscript installing, get error:
"cupsd: symbol lookup error: cupsd: undefined symbol: httpAddrFamily"

When downgrade to cups 1.6.3 everything is fine, but this version maybe have a log of bugs. 

How i can update libcups for CentOS 7?

**Comment by michaelrsweet** [comment]
@evgenmedia You'll need to ask the CentOS folks for help there - the version of CUPS bundled with Linux distros is often strongly tied to a bunch of other packages bundled with the distro... :/
