### ISSUE TITLE
Apple raster support in libcupsimage: Page header is 32 bytes long, not 64 bytes

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#4920]
Following your hint in issue #4916, that the OfficeJet (which is an AirPrint printer and not an IPP Everywhere printer) should work your most recent fixes in the GIT repo, I had a deeper look into the repo and saw that you have added Apple raster support. Now I have tried it and the Apple raster generated by CUPS only printed the first page of each document, both on the mentioned OfficeJet, the Officejet Pro 8500 A910 via IPP, and on the DeskJet Ink Advantage 2540 via USB (regular CUPS "usb" backend, not IPP-over-USB).

So I had a look into your code and that Apple raster has 64-byte headers, where only the bytes 0, 1, and 12-23 were actually used for metadata. Then I compared with an old filter which is able to read Apple raster but based on reverse engineering and there the page header size is 32 bytes. So I tried changing your code to make the header size 32 bytes (and this drops only zeros, nothing of the metadata) and both printers started printing the Apple raster files correctly, all pages. A number of pages in the file header seems not to be required (was always zero in my sample files which I generated with the cupsfilter command).

Patch attached.

Please check through the rest of CUPS whether it needs further changes concerning the 32 byte long Apple raster headers.

[urf-has-32-byte-headers.patch.txt](https://github.com/apple/cups/files/598243/urf-has-32-byte-headers.patch.txt)

**Comment by michaelrsweet** [comment]
Note that this code is still BETA and subject to change. And the IANA registered name is "Apple raster"... :)

**Comment by michaelrsweet** [comment]
[master 98f204f] Fix size of header (Issue #4920)
