### ISSUE TITLE
IPP Everywhere PPD generator: Enumeration of media not consistent when generating options PageSize, PageRegion, ImageableArea, and PaperDimension

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#4921]
PPD files have the required options/entries PageSize, PageRegion, ImageableArea, and PaperDimension to describe the paper sizes supported by a printer and their unprintable margins. Each of them treats the same set of paper sizes so when generating them in the PPD generator the list of paper sizes needs to be generated the same way for each of them.

In the IPP Everywhere PPD generator of CUPS (function _ppdCreateFromIPP() in file cups/ppd-cache.c) PageSize uses another method to obtain the list of supported media than PageRegion and ImageableArea/Paperdimension. It seems that you have added support for both the "media-size-supported" and "media-supported" attributes and have taken into account the different internal structures of them, but made this change only for PageSize, not for PageRegion and ImageableArea/Paperdimension, leading to broken PPDs for some printers, as my HP OfficeJet Pro 8500.

I have passed your changes over to PageRegion and ImageableArea/Paperdimension now and this way the printer works perfectly now.

Patch attached.

[ppd-generator-fix-pagesize-pageregion.patch.txt](https://github.com/apple/cups/files/598401/ppd-generator-fix-pagesize-pageregion.patch.txt)

**Comment by michaelrsweet** [comment]
[master 3be8e02] Fix some more IPP Everywhere PPD generator problems (Issue #4921)
