### ISSUE TITLE
IPP Everywhere PPD generator: Use urf-supported IPP attribute for more options

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#4922]
The PPD generator uses the urf-supported IPP attribute currently for ColorModel, Duplex, and Resolution, but it contains: Copies (CP, max copies? hardware copies?), MediaType (MT), OutputBin (OB), Finishers (OFU), PrintQuality (PQ), Resolution (RS), ColorModel (SRGB24, ...), BitsPerPixel? (W8), DuplexMode (DM), InputSlot (IS).

Example urf-supported attribute of my HP OfficeJet Pro 8500:
CP1,MT1-2-8-9-10-11,OB9,OFU0,PQ3-4-5,RS300-600,SRGB24,W8,DM3,IS1-2

**Comment by michaelrsweet** [comment]
Some of the values are unused because there are IPP attributes providing the same information (but better).
