### ISSUE TITLE
HP NFC/Wireless 1200w – Mobile Print Accessory: Small glitches in generated PPD file

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#4923]
The Mobile Print Accessory is an add-on module for legacy HP laser printers which is connected to the USB of the printer and adds AirPrint support, accepting the Apple Raster format. So I tried it on my HP Color LaserJet CM3530 MFP running the command (URI found with "ippfind"):

lpadmin -p hp1200wtest -E -v ipp://NPIE8F64A.local:631/ipp/print -m everywhere

and the resulting PPD file passes "cupstestppd" without warnings. Printing works perfectly with current GIT CUPS using the Apple Raster format.

There are only some small glitches in the PPD file which do not break actual printing:

Manufacturer and model information comes out this way:

*Manufacturer: "CLJ3530:HP"
*ModelName: "1200w Mobile Print Accy"
*Product: "(1200w Mobile Print Accy)"
*NickName: "1200w Mobile Print Accy"
*ShortNickName: "1200w Mobile Print Accy"

The manufacturer looks strange. Should be "HP" (both printer and adapter are from HP).

The *Product entry does not match the product TXT record entry of the Bonjour record of the adapter ("(CLJ3530:HP 1200w Mobile Print Accy)"), it would match if the *Manufacturer entry is added.

Looking into the code there is no mechanism to assure that the *ShortNickName is not longer than 31 characters.

The filter lines are the following:

*cupsFilter2: "image/urf image/urf 10 -"
*cupsFilter2: "application/PCLm application/PCLm 10 -"
*cupsFilter2: "image/jpeg image/jpeg 10 -"

There are correctly added lines for Apple Raster and JPEG, but the PCLm line looks wrong for me, as CUPS does not support PCLm (or does it now?). Note that PCLm is a proprietary format used by HP and others which has nothing to do with PCL 5c/e or PCL-XL. So it is not relevant for printing with CUPS and cups-filters.

Output of

ipptool -tv ipp://NPIE8F64A.local:631/ipp/print get-printer-attributes.test

attached.

[HP-1200w-CM3530-ipp-attr.txt](https://github.com/apple/cups/files/601779/HP-1200w-CM3530-ipp-attr.txt)

**Comment by michaelrsweet** [comment]
We should probably filter out application/PCLm since it isn't supported on macOS or Linux.

As for the product/nickname strings, I specifically want to avoid doing extra processing on them - that's something we could end up adding a tremendous amount of code to clean up every buggy implementation for very little gain. Both CUPS and Windows have no problem with long "ShortNickName" values (cupstestppd is pendantic about it, but that's about it) so I don't see the point in making sure the ShortNickName value is limited to 31 characters...

**Comment by tillkamppeter** [comment]
The problem of PCLm appearing is caused that to sort out which cupsFilter2 lines the PPDs should get you name the formats you do not want, and this allows any new proprietary format which gets a nice name to get in. Better name the formats you want to have, as there you know what CUPS, Mac OS X, and cups-filters are capable to generate.

**Comment by michaelrsweet** [comment]
[master 07428f6] Only list supported PDLs (Issue #4923)

**Comment by tillkamppeter** [comment]
Now Apple Raster is missing. Is that correct? Only PDF, PWG Raster, and JPEG?

**Comment by michaelrsweet** [comment]
No, you should still see Apple raster in the list of filters.

**Comment by tillkamppeter** [comment]
I have checked again and Apple Raster is there. You're right.
