### ISSUE TITLE
Pages count unknown

### ISSUE THREAD

**Issue by marcieee** [apple/cups#4924]
Hello, I'm trying using CUPS on my mac to keep an history of my prints, but for each completed job in the page count column is shown "Unknown". Anyway to fix it so i can have a report of many pages I have actually printed? I've been googling around to find this issue, i found few very old posts  with no solution. Thank you so much.

**Comment by michaelrsweet** [comment]
What OS?

What driver are you using?

**Comment by marcieee** [comment]
Thank you so much, I'm glad that you answered!
Mac Os El Capitan 10.11.16. Driver, not sure, can you help me where to look?
My printer is Samsung C48x Series.

**Comment by michaelrsweet** [comment]
OK, you can see the driver being used in the Print & Scan system preference pane. Select the printer there to see the driver listed on the right.

If you are using the Samsung driver, please contact Samsung for support - their driver is responsible for providing the necessary accounting information.

If you are using the AirPrint driver ("-AirPrint" on the end of the driver name) then this should be working. If not, please file a bug with Apple against macOS: https://bugreport.apple.com

**Comment by marcieee** [comment]
Thank you so much Michael. The Diver used is Samsung C48X Series-AirPrint. So i'm going to report this at the link you gave me! :)

**Comment by limbusone** [comment]
I have the same issue, CUPS 2.1.3-4, printer: Lexmark CX 510de, PPD: http://www.openprinting.org/printer/Lexmark/Lexmark-CX510de

**Comment by michaelrsweet** [comment]
OK, after investigating things it turns out this is a web interface bug.

**Comment by michaelrsweet** [comment]
[master 1cd3106] Fix reporting of printed pages in the web interface (Issue #4924)
