### ISSUE TITLE
Cups and remote printer attached to nas

### ISSUE THREAD

**Issue by ferrvittorio** [apple/cups#4926]
Hi,
a laser printer attached to my NAS does not print some PDF and does not print at all pictures
Print is issued from desktop, file reaches the printer, which rejects and starts blinking error.

PC:
Linux arch-h11 4.8.8-2-ARCH #1 SMP PREEMPT Thu Nov 17 14:51:03 CET 2016 x86_64 GNU/Linux
NAS:
QNAP TS-212

Pc and Nas are on the same network.
Printer is locally configured as ipp: ; and on Nas is shown as smb: share.
Printer name/model is Brother_HL-L2300D
Driver with the corresponding name was found and installed through aur

I can only produce cups logs from local pc, NAS uses kind of native method of sharing and dont know where to put hands

How can we troubleshoot

Thanks

**Comment by ferrvittorio** [comment]
I add a log file
It shows cups behaviour for two jobs, the first successful print, the second fails

[cups_error_log.txt](https://github.com/apple/cups/files/608355/cups_error_log.txt)

**Comment by michaelrsweet** [comment]
Well, it looks like the printer is hung after the first job so the subsequent job is stalled. Probably needs some sort of a USB quirk rule on the NAS to fix things there - try running the following on the NAS:

    lsusb

to determine the vendor and model IDs and then add the following to the /usr/share/cups/usb/org.cups.usb-quirks file:

```
0x04f9 0xNNNN no-reattach
```

(0x04f9 is the Brother vendor ID, the model ID in the lsusb output will show you the model ID as 4 hex digits)
