### ISSUE TITLE
Web Interface/dnssd backend: IPP should get preferred when adding printer, for driverless printing

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#4927]
I am looking into making driverless printing (preferably IPP Everywhere but also Apple Raster legacy) universally available, as most users will not discover the "lpadmin ... -m everywhere ..." method and I am not sure whether it is the right way to let cups-browsed auto-setup driverless print queues on desktops and servers.

So I have tested the way of whether a printer setup tool could somehow generate the PPD (with command line tool in cups-filters or library function in libcupsfilters) or even CUPS (with command line tool from cups-filters in /usr/lib/cups/drivers/), or simply a Generic PPD from a CUPS sample driver or cups-filters. I have tried this and it actually works!) and then one uses the usual steps of the printer setup tool to set up the printer (especially printers which one gets to work under Linux with ONLY one of IPP Everywhere or Apple Raster).

So I have taken the web interface (http://localhost:631/) and tried to add my HP OfficeJet Pro 8500 A910 (this printer is an Apple Raster printer which works perfectly auto-setup by cups-browsed or set up with "lpadmin -p ... -E -v ipp://... -m everywhere"). The printer is on the network and I have chosen all instances of it under the discovered printers and none of these instances is connecting the printer via IPP, only via socket or via LPD. So I went on with the dnssd URI connecting to socket. I chose the generated Apple Raster PPD for this printer and completed the setup.

When trying to print I got only garbage as probably due to the socket connection the needed IPP attributes did not get transmitted.

So the important thing for the driverless printing age is that one can easily connect to printers via IPP. Either the dnssd backend or the web interface need to take care that an IPP-based entry is in the list of discovered printers and preferably at the top of the list.

**Comment by michaelrsweet** [comment]
The cupsDest* APIs, and in particular the cupsEnumDests API, already prefer IPP and are what you should be using. The legacy printer driver interface (and the corresponding web interface) has to honor the priority reported by the printer, otherwise you *will* have trouble with the printer interpreting  traditional PDLs like PCL... :/

**Comment by tillkamppeter** [comment]
What is the right way then to set up an IPP Everywhere printer with the CUPS web interface?

**Comment by michaelrsweet** [comment]
If IPP isn't the primary protocol, go to the printer's web interface and change the priority to IPP.

**Comment by tillkamppeter** [comment]
Unfortunately, my OfficeJet only offers LPD and 9100 printing to choose as priority protocol Firmware bug, or they expect desktop/server is only classic with driver and therefore no IPP and IPP is phone-only).

Auto-setup with cups-browsed (cups-filters 1.12.0 which I have released some hours ago) works perfectly, but cups-browsed only searches for IPP connections and ignores the others.

Also manual setup with lpadmin and the URI found with ippfind works (but ippfind also only finds the IPP connections, like cups-browsed). Perhaps I need to write a discovery-only backend (like snmp) which outputs the IPP URIs.

**Comment by tillkamppeter** [comment]
Solved the problem with cups-filters' own discovery-only backend. The utility "driverless", introduced in cups-filters 1.12.0 now does not only auto-generate PPDs but also list the suitable printers with their IPP URIs, allowing for correct driverless setup.
