### ISSUE TITLE
Error on sending an print job.

### ISSUE THREAD

**Issue by alphat5** [apple/cups#4928]
Hy, I recently installed CUPS on my Raspberry Pi 2. The printer wich is linked to the py is an Samsung-SCX-3205. It works perfectly, i can print an test page to the printer trough the cups admin panel. 

But I have an problem when I whant to print from my windows 10. I correctly added the printer with IPP. But I got an error in CUPS logs.

```
192.168.0.46 - pi [27/Nov/2016:17:10:59 +0000] "POST /admin HTTP/1.1" 200 138 - -

localhost - - [27/Nov/2016:17:10:59 +0000] "PUT /admin/conf/cupsd.conf HTTP/1.1" 401 0 - -

localhost - pi [27/Nov/2016:17:10:59 +0000] "PUT /admin/conf/cupsd.conf HTTP/1.1" 201 3116 - -

192.168.0.46 - pi [27/Nov/2016:17:10:59 +0000] "POST /admin HTTP/1.1" 200 2211 - -

192.168.0.46 - pi [27/Nov/2016:17:11:27 +0000] "POST /admin HTTP/1.1" 200 285 - -

localhost - - [27/Nov/2016:17:11:28 +0000] "PUT /admin/conf/cupsd.conf HTTP/1.1" 401 0 - -

localhost - pi [27/Nov/2016:17:11:28 +0000] "PUT /admin/conf/cupsd.conf HTTP/1.1" 201 3132 - -

192.168.0.46 - pi [27/Nov/2016:17:11:27 +0000] "POST /admin HTTP/1.1" 200 2395 - -

192.168.0.46 - - [27/Nov/2016:17:12:20 +0000] "POST /printers/Samsung_SCX-3200 HTTP/1.1" 200 84833 Print-Job client-error-not-authorized

192.168.0.46 - - [27/Nov/2016:17:13:52 +0000] "POST /printers/Samsung_SCX-3200 HTTP/1.1" 200 84833 Print-Job client-error-not-authorized

192.168.0.46 - pi [27/Nov/2016:17:14:10 +0000] "GET /admin/log/access_log? HTTP/1.1" 200 33147 - -
```

**Comment by michaelrsweet** [comment]
We'll need to see a debug error_log showing the Windows client sending the print job. To enable debug logging, run:

    cupsctl --debug-logging

**Comment by alphat5** [comment]
Ok, I will do it, I will drop it here :)?

Envoy? de mon iPhone

Le 28 nov. 2016 ? 03:47, Michael R Sweet <notifications@github.com<mailto:notifications@github.com>> a ?crit :


We'll need to see a debug error_log showing the Windows client sending the print job. To enable debug logging, run:

cupsctl --debug-logging


-

**Comment by alphat5** [comment]
Hi, here is the error log file: http://pastebin.com/xx7zcwYz
And here is my cupsd.conf:  http://pastebin.com/HaaALXCT

**Comment by michaelrsweet** [comment]
OK, sorry for the long wait, it looks like the Windows client isn't including the print file; might be an issue with the Windows print driver being used...
