### ISSUE TITLE
lp authentication and cups server

### ISSUE THREAD

**Issue by tomjanowski** [apple/cups#4929]
I am struggling with making a secure CUPS server for a research group. Besides problems mentioned by me in other issue that involves cupsd entering infinite loop if authorization is required at the topmost level (Location /) I now discovered a new problem with local printing using "lp" command. I attempt to print using a slightly customized "authenticated" policy. lp communicates with the server via UNIX socket using PeerCred. First request to create a job is denied since initially lp tries to communicate without authentication. After getting "HTTP/1.1 401 Unauthorized" response it creates a job successfully using PeerCred. Then it sends the data file, again without authorization. Although the server responds the same way (HTTP/1.1 401) after a whole document was transferred, lp does not seem to care and exits happily as if the job were properly transmitted. The server deletes unauthenticated transfer, while lpstat reports an existing job with empty file, that is aborted after a while due to timeout.

**Comment by tomjanowski** [comment]
I see that this issue is quite closely related to issue #4901 . I t makes me wonder whether I am doing something wrong or PAM authentication over encrypted channel is simply work in progress.

I have tested two setups:
1. I define `<Location />` as available to anyone. In this case when lp client communicates with cupsd and does not provide authorization data it gets two responses: the first one is `HTTP/1.1 100 Continue` and the second, that immediately follows, is `HTTP/1.1 401 Unauthorized`. Remote Windows clients can print and cupsd does not enter infinite loop, but local lp print fails. I think lp is just fooled by the server that first responds that is expects more data and a moment later it says it was kidding and authorization was needed.
2. I define the following:
`<Location />`
`   AuthType default`
`   Require valid-user`
`</Location>`

In this case server immediately responds `HTTP/1.1 401 Unauthorized` if clients does not send credentials, lp commands prints fine but remote Windows clients make the cupsd to enter an infinite loop and consume 100% CPU. I think the daemon eventually fails in this case.

**Comment by michaelrsweet** [comment]
The initial "100" response is required since (at that point) the server doesn't know whether authentication will be required for the given request. I'm guessing this *is* related to Issue #4901 but we need to track down the reason.

**Comment by michaelrsweet** [comment]
@tomjanowski Does this problem reproduce for you when the patch for Issue #4901 is applied?

**Comment by michaelrsweet** [comment]
No response in a month, closing...
