### ISSUE TITLE
/lib/systemd/system/cups.path and keepalive file /var/cache/cups/org.cups.cupsd do not make sense with systemd

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#4930]
During the investigation of whet causes this Ubuntu bug (most probably a systemd bug)

https://bugs.launchpad.net/ubuntu/+source/init-system-helpers/+bug/1642966

we have found out that cupsd creates the empty file /var/cache/cups/org.cups.cupsd and otherwise removes it. It does this during startup and shutdown. AFAIK it is a keepalive file, probably only needed for Apple's launchd.

There is also a systemd unit file /lib/systemd/system/cups.path which starts CUPS when the /var/cache/cups/org.cups.cupsd file is newly created (not when it is already there). As there is nothing which creates this file outside CUPS, and systemd does not use keepalive files at all, and there are various more standard and more obvious methods on how to start CUPS. I do not see any sense in the /lib/systemd/system/cups.path file and on systemd systems I also do not see any sense in the /var/cache/cups/org.cups.cupsd file.

So my suggestions is:

1. Do not create and take down /var/cache/cups/org.cups.cupsd in a systemd environment

2. Remove /lib/systemd/system/cups.path or modify it that it starts CUPS on boot when there are pending jobs in /var/spool/cups/

If there is any intention behind /lib/systemd/system/cups.path and /var/cache/cups/org.cups.cupsd in systemd environments, please tell.

**Comment by martinpitt** [comment]
What is supposed to remove that stamp file actually? I haven't had used cups in many years, and my stamp file is from early 2015. Same in a clean VM install, it just never gets removed, thus cups will always start on boot anyway.

I strongly recommend to put such stamp files into `/run/` so that they don't survive a reboot.

**Comment by tillkamppeter** [comment]
pitti, as far as I understand the source code of CUPS (scheduler/main.c) once at startup and once at shutdown/restart CUPS checks whether one of the following conditions is true
- Web interface active
- At least one shared printer
- Active jobs
and in this case it creates the file, otherwise it deletes it.

**Comment by michaelrsweet** [comment]
All,

The keepalive file is there to make sure that cupsd is restarted when the system boots up, otherwise printer sharing, processing of previously-queued jobs, and the web interface won't work. Putting the file in /run would defeat the purpose - cupsd would never be started until somebody tried to print or a system process queried it.

So if you want CUPS to be using systemd at all, it needs this functionality to work for resuming job processing, sharing printers, and/or supporting the web interface.

**Comment by tillkamppeter** [comment]
Problem is here that systemd only starts CUPS when the keepalive file is newly created, not when it is already there (from the previous cupsd session, before the reboot), so it seems that the bug is in systemd then. Am I right?

**Comment by michaelrsweet** [comment]
Yes, this looks like a bug in systemd.

**Comment by martinpitt** [comment]
I guess we have two different bugs then -- cups never removing the keepalive file, and something entirely new ("systemd only starts CUPS when the keepalive file is newly created") which wasn't discussed/reported/described anywhere yet.

**Comment by michaelrsweet** [comment]
@martinpitt cupsd *does* remove the keepalive file, but only on exit when it knows it should not be restarted.

**Comment by martinpitt** [comment]
Well, if we find that this `.path` unit is actually necessary under Linux, and you don't want to use this issue, I'll file a separate issue about this then. This is perfectly reproducible in a fresh VM after installing cups -- the stamp file gets created and never ever removed. If that's the intent, then the `.path` file is unnecessary and `cups.service` can just always be started at boot -- but I thought the web interface and local print requests would be covered by the `*.socket` unit. Starting on boot for pending print jobs should be done with a `*.path` unit for `DirectoryNotEmpty=/var/spool/cups` (or something similar).

**Comment by michaelrsweet** [comment]
@martinpitt cupsd creates this file if the current settings a) enable the web interface, b) enable printer sharing, or c) there are pending print jobs. If none of those conditions exist, the file is removed.

The code in question lives in scheduler/main.c (see the "service_checkout()" function), and is called from main(). Currently it looks like service_checkout is called after the configuration file is loaded and again on exit, although normally that should only need to happen on exit - those changes happened as part of the patches that were supplied to us in Issue #3917.

Again, the reason for this file to exist is to inform the service daemon (systemd in this case) that cupsd needs to be run immediately and not "on demand".

**Comment by martinpitt** [comment]
Ah, thanks @michaelrsweet  -- so I suppose the reason is that we do enable the web interface in our packages, as I didn't do b) or c). The web interface should actually be triggered by a socket unit too (`ListenStream=631`, you can specify as many `ListenStream`s as you want).

**Comment by tillkamppeter** [comment]
pitti, the intention is the following:

If CUPS is exiting and one of the following is true, CUPS needs to get restarted after the next boot:

- Web interface active
- At least one shared printer
- Active jobs

CUPS marks this by creating the empty keepalive file at a place where it survives the boot. If none of the criteria is true it removes the keepalive file (try by editing cupsd.conf). It does this in the following situations:

- At startup (probably right after reading cupsd.conf), to assure the correct behavior on reboot after an unclean termination (crash, kill -9, ...).
- At restart (kill -HUP, cupsctl operation, configuration change via web interface), to update with a configuration change.
- At regular shutdown

The intention is that on boot with the keepalive file present, CUPS should be started as it has either to stay running permanently (printer sharing, web interface) or has to finish pending jobs. CUPS does not need to be started on boot otherwise.

This means that whenever there is this keepalive file the *.path has to start CUPS it CUPS is not already running, indpendent whether it is already there or newly created. If it is not there, *.path does not need to do anything. The current behavior is a bug in systemd.

Another bug in systemd is the shutdown problem of the original Ubuntu bug report.

Mike, can you assure that if there are no shared printers and the web interface is off, that as soon as a job appears that the keepalive file is created and as soon as CUPS runs out of jobs that the file is removed? This way on an unclean shutdown at any time and with corrected systemd CUPS would be immediately restarted if the system is still running or started on boot if the system had to be rebooted and so we get assured that the jobs get finished.

**Comment by michaelrsweet** [comment]
@tillkamppeter we don't micro-manage the keep-alive file. If cupsd is started unnecessarily then it will just idle-exit, removing the file. If cupsd isn't started (and needed to), it will need a process to connect to it to start it back up. But a crash is typically very rare these days...

@martinpitt you don't want to add a listener on port 631 through systemd since (unless the bug has been fixed) it doesn't create a pair of listeners for both IPv4 ad IPv6 (totally useless for a CUPS server), and doing so unnecessarily exposes the system to browser-based attacks on localhost.
