### ISSUE TITLE
PPD Generator for IPP Everywhere/driverless: Hierarchy of PDLs

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#4932]
Attached is the PPD file generated with "lpadmin ... -meverywhere" of the Lexmark CS720de color laser printer.

The printer understands PDF, PWG Raster, Apple Raster, and JPEG. Therefore the PPD gets the following filter lines:

*cupsFilter2: "image/urf image/urf 10 -"
*cupsFilter2: "image/pwg-raster image/pwg-raster 10 -"
*cupsFilter2: "application/vnd.cups-pdf application/pdf 10 -"
*cupsFilter2: "image/jpeg image/jpeg 10 -"

They all have the cost value of 10, so no preference. In reality PDF gets preferred as there no filter after pdftopdf is needed, all the others need at least something like pdftoraster in addition. But to make sure that always the most reliable PDL is used, I suggest to control this with the cost values, like for example:

*cupsFilter2: "image/urf image/urf 200 -"
*cupsFilter2: "image/pwg-raster image/pwg-raster 100 -"
*cupsFilter2: "application/vnd.cups-pdf application/pdf 0 -"
*cupsFilter2: "image/jpeg image/jpeg 300 -"

My suggestion for a hierarchy is:

PDF -> PWG Raster -> Apple Raster ->JPEG

PDF is the most versatile and the standard in CUPS printing workflows, and PWG Raster is a completely open and therefore known format, whereas Apple Raster is only partially known but sufficien for printing general documents on most printers and JPEG only supports one-page documents.

Currently I especially do not see anything prioritizing PWG Raster against Apple Raster.

In the PPD generator in cups-filters I have already applied a hierarchy for the supported PDLs.

**Comment by tillkamppeter** [comment]
Said PPD file:
[Lexmark-CS720de-cups-driverless.ppd.txt](https://github.com/apple/cups/files/642763/Lexmark-CS720de-cups-driverless.ppd.txt)

**Comment by michaelrsweet** [comment]
OK, so generally speaking we should prefer PDF over PWG Raster or Apple Raster, however a JPEG file can be printed directly so that cost needs to remain low.

I will look at doing a cost of 10 for PDF (usually needs a little local massaging), 0 for JPEG (pass-through), and 100 for PWG Raster and Apple Raster (full RIP).

**Comment by tillkamppeter** [comment]
And if a printer support both PWG Raster and Apple Raster but no PDF it should prefer PWG Raster because it is the more sophisticated and more standard format, even if both raster formats take exactly the same amount of CPU cycles for rendering the same job.

**Comment by michaelrsweet** [comment]
@tillkamppeter PWG Raster is larger (output size) and requires (slightly) more CPU than Apple Raster on macOS, so we'll leave the cost the same in the PPD. The cost(s) for the RIP filter(s) on the system will then determine which PDL is preferred.

**Comment by michaelrsweet** [comment]
[master 1add233] Tweak the PDL priority (Issue #4932)
