### ISSUE TITLE
PPD Generator for IPP Everywhere/driverless: Suppress duplicate choices in options

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#4933]
Probably due to bugs in the firmware it can happen that IPP printers report the same choice for an option more than once, as for example the Lexmark CS720de (PPD auto-generated via "lpadmin ... -meverywhere" attached) reports the page size "Legal" two times (with the same actual size).

The PPDs generated by CUPS contain the duplicate choices then (in this case two times "Legal" under PageSize, PageRegion, ImageableArea, and PaperDimension) and "cupstestppd" complains.

Could you make such duplicates getting suppressed?

PPD file of the Lexmark CS720de:
[Lexmark-CS720de-cups-driverless.ppd.txt](https://github.com/apple/cups/files/643021/Lexmark-CS720de-cups-driverless.ppd.txt)

**Comment by debiantriage** [comment]
[HP-ENVY-4500.ppd.txt](https://github.com/apple/cups/files/644036/HP-ENVY-4500.ppd.txt)

The PPD produced with everywhere for an HP ENVY 4500 Series printer. cupstestppd gives a FAIL for multiple occurences of PageRegion  and PageSize and a warning for size "om_small-photo".

Cheers,

Brian.

**Comment by michaelrsweet** [comment]
As for the cupstestppd issues, I'm not concerned about warnings, but we should definitely suppress duplicates. I will probably add code to log comments in the PPD about what we're seeing as well...

**Comment by michaelrsweet** [comment]
[master 7fad1ee] Suppress duplicate media sizes (Issue #4933)
