### ISSUE TITLE
Apple Raster: Asymmetric resolution printed incorrectly

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#4934]
I have done some IPP-over-USB tests with the HP DeskJet Ink Advantage 2540 for finding out about driverless printing via USB.

I run

ippusbxd -v 0x03F0 -m 0xC211 -s BR54BFB02C05XK -p 60000 -d 2>&1 | tee log2.txt

in one terminal (ippusbxd from "git clone git@github.com:tillkamppeter/ippusbxd.git") and get the printer on the IPP URI 

ipp://localhost:60000/ipp/print

I have successfully created a queue for it with

lpadmin -p ippusbxdtest -E -v ipp://localhost:60000/ipp/print -meverywhere

and the generated PPD (attached) passes cupstestppd. It accepts Apple Raster and JPEG as CUPS/cups-filters-compatible input formats, no PWG Raster.

Available user-settable options are:

till@till-x1carbon:~$ lpoptions -p ippusbxdtest -l
PageSize/Media Size: Letter 8x10 *A4 Executive Legal A6 EnvC5 ISOB5
MediaType/Media Type: PhotographicGlossy *Stationery Transparency
ColorModel/Color Mode: *RGB
cupsPrintQuality/Print Quality: Draft *Normal High
till@till-x1carbon:~$

and I can print correctly on this printer. I tried a text file and a PDF.

I am also able to print with cupsPrintQuality=Hogh.

I get the page content compressed to the first half of the page if I print with cupsPrintQuality=Draft, and when I look into the PPD, the Normal and High qualities generate 300x300-dpi and 600x600-dpi bitmaps whereas Draft generates 300x150 dpi. It seems that something is wrong with printing Apple Raster in asymmetric resolutions.

Can you have a look into this?

I did not test this yet via WiFi, but probably there the same problem occurs.

PPD file:

[HP-DeskJet_2540-everywhere.ppd.txt](https://github.com/apple/cups/files/644634/HP-DeskJet_2540-everywhere.ppd.txt)

Output of

ipptool -tv ipp://localhost:60000/ipp/print get-printer-attributes.test > HP-DeskJet_2540-ipp-attr.txt

[HP-DeskJet_2540-ipp-attr.txt](https://github.com/apple/cups/files/644635/HP-DeskJet_2540-ipp-attr.txt)

**Comment by tillkamppeter** [comment]
Same problem happens when doing the above steps via WiFi instead of IPP-over-USB.

**Comment by michaelrsweet** [comment]
[master 073e58a] Fix asymmetric resolution bug, address unit test issues.

**Comment by tillkamppeter** [comment]
I have applied your fix and now the image is actually printed undistorted, but it stops after half of the page. The other half stays blank.

**Comment by michaelrsweet** [comment]
[master 10887d2] One more fix for asymmetric resolutions (Issue #4934)

Forgot to update the bitmap height that is in the Apple raster header... :/

**Comment by tillkamppeter** [comment]
Tested again and now it works correctly. Thank you very much.
