### ISSUE TITLE
systemd support: cups.path needs a "PartOf=cups.service" in the [Unit] section to assure clean shutdown of CUPS

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#4935]
The problem of the Ubuntu bug report

https://bugs.launchpad.net/ubuntu/+source/init-system-helpers/+bug/1642966

is not due of CUPS' keepalive file (Issue #4930) but needs a change in the cups.path unit file. The line "PartOf=cups.service" needs to be added to the [Unit] section, telling that cups.path belongs to CUPS (main unit cups.service) and so cups.path gets started/stopped/restarted whenever cups.service gets started/stopped/restarted.

This means that if cups,service gets stopped, cups.path gets stopped and so CUPS stays stopped and does not get re-triggered immediately by cups.path. On next boot everything gets started and so cups.path starts CUPS on the presence of the keepalive file.

So the cups.path file has to look like this:
```
[Unit]
Description=CUPS Scheduler
PartOf=cups.service

[Path]
PathExists=/var/cache/cups/org.cups.cupsd

[Install]
WantedBy=multi-user.target
```

**Comment by michaelrsweet** [comment]
Scheduled for the next 2.2.x release.

**Comment by michaelrsweet** [comment]
and that would be "PartOf=org.cups.cupsd.service" since we use org.cups.cupsd in the official CUPS sources. And I think we need this in the org.cups.cupsd.socket file as well...

[master 7852449] Update systemd config files (Issue #4935)

**Comment by michaelrsweet** [comment]
(the pushed change also adds this to the org.cups.cups-lpd.socket file for the org.cups.cups-lpd.service)
