### ISSUE TITLE
Some documents print, some don't. All marked "completed" (IPP client/server)

### ISSUE THREAD

**Issue by pjotrek-b** [apple/cups#4937]
The problem is that the printer works fine *most of the time* - but some documents won't print.

CUPS webinterface says the jobs are completed, and the logs say everything's fine.

Print server is a Raspberry Pi (Raspbian Debian 8 Jessie, CUPS version **1.7.5-11+deb8u1**) with a HP LaserJet P1102w (USB). Driver used is "printer-driver-foo2zjs" (Debian package). HPLIP didn't work at all.

I was able to reproduce the behavior from different clients (Xubuntu 12.04, 14.04, 16.04).
The documents affected were all PDFs.

I suspected different PDF generators to be the issue, but I have a case where all PDFs were created using LibreOffice (same document template) - and some print and some don't.

When connecting the printer directly (on Xubuntu 12.04, CUPS 1.5.3-0ubuntu8.7), all affected documents print fine.

Here's an excerpt of a failing job in "/var/log/cups/access_log" (error_log has no entry):
> 10.0.0.xx - - [19/Dec/2016:19:10:51 +0100] "POST /printers/HP_LaserJet_Professional_P_1102w HTTP/1.1" 200 538 Validate-Job successful-ok
> 10.0.0.xx - - [19/Dec/2016:19:10:51 +0100] "POST /printers/HP_LaserJet_Professional_P_1102w HTTP/1.1" 200 538 Create-Job successful-ok
> 10.0.0.xx - - [19/Dec/2016:19:10:51 +0100] "POST /printers/HP_LaserJet_Professional_P_1102w HTTP/1.1" 200 74242 Send-Document successful-ok

**Comment by michaelrsweet** [comment]
This is probably an issue with this particular printer and the driver being used, *not* an issue in CUPS.
