### ISSUE TITLE
CUPS 2.2.1 rpmbuild fails

### ISSUE THREAD

**Issue by pconklin** [apple/cups#4940]
CentOS 7.3.1611 x86_64

Fails with both --without libusb1 or normal (symptoms same as bug 4436)

Checking for unpackaged file(s): /usr/lib/rpm/check-files /root/rpmbuild/BUILDROOT/cups-2.2.1-0.x86_64
error: Installed (but unpackaged) file(s) found:
   /usr/share/doc/cups/pt_BR/index.html
   /usr/share/locale/pt_BR/cups_pt_BR.po

RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/share/doc/cups/pt_BR/index.html
   /usr/share/locale/pt_BR/cups_pt_BR.po

Started with Minimal install of CentOS 7.3, then did the following
yum update -y
yum install rpm-build
yum install gnutls
yum install gnutls-devel
yum install -y pam-devel
yum install -y dbus-devel
yum install -y avahi-devel
yum install -y libusb-devel
yum install -y systemd-devel
yum install -y gcc
yum install -y gcc-c++
yum install -y libusb
yum install -y libusb-devel
yum install libusbx
yum install libusbx-devel

**Comment by michaelrsweet** [comment]
[master 3980a9c] Update packaging files (Issue #4940)
