### ISSUE TITLE
build cups ppdc still asking -lstdc++ when we have CXXLIBS=-lc++ -lc++abi on linux

### ISSUE THREAD

**Issue by kangjoni76** [apple/cups#4943]
Cups version latest git, using Linux clang 3.9.1 libc++ on centos , this happen strangely when projectroot/Makedefs none had declared -lstdc++ explicitly, any ideas?
thanks

**Comment by michaelrsweet** [comment]
No clue, we don't pull in libstdc++ ourselves, must be clang doing that...
