### ISSUE TITLE
I want the patch for "Issue #4242" v1.6.1  

### ISSUE THREAD

**Issue by hanjianlong1988** [apple/cups#4944]
Our old product use the CUPS verions 1.6.1(v).But I can not find the path in our web site now.It seems that the patchs have been removed.
 Can you help me to find the patch,thank you very much !

**Comment by michaelrsweet** [comment]
OK, the patch in Issue #4242 should be copy-able now.

And yes all of the old bug database patch files were removed when CUPS was moved to Github... Sadly there was no way to migrate the attachments over in a way that preserved the links...
