### ISSUE TITLE
Zebra Driver

### ISSUE THREAD

**Issue by angelopbernardes** [apple/cups#4945]
Hi, I'm experiencing a issue with a printed area size when I change from 203DPI tom 300DPI a Zebra ZT 230 printer.
I used the embedded driver to install this printer over ethernet connection.
My tag has 10X12 cm (Width x Height), and it has two barcodes, one Code 3 of 9 and other Code 128. When I'm using 203 DPI configured the barcode 3 of 9 was printed without resolution enough to be read using any data colector, so I changed the configuration to 300 DPI to fix that resolution issue, for my surprise when I made this change the tag was printed bigger then the paper, is almost 1/2 of my tag has fit into the media paper, as the following images show.
Doesn't matter change the paper sizer, set any margins the result always is the same.

When Configured with 203 DPI with lack of resolution.
![image](https://cloud.githubusercontent.com/assets/680911/21764538/d1b1d6c4-d64a-11e6-87e3-49b3626a30b4.png)

When configured with 300DPI with any paper size defined

![image](https://cloud.githubusercontent.com/assets/680911/21764570/f5a9316c-d64a-11e6-9bdd-85f485d9d880.png)

I hope if that weren't an issue that you could tell what I have done wrong to have this result, because I've always used CUPS with lots of printers of Intermec(Honeywell) and Argox, both companies have delivered theirs own Linux Drivers, and for the first time I'm installing a Zebra printer on Linux, and the Zebra company has produced a tutorial, [tutorial link](https://km.zebra.com/kb/index?page=content&id=SO7680), using cups telling that the embedded driver should be enough to print Zebra tags on Linux.

Thanks

**Comment by michaelrsweet** [comment]
Please verify that your ZT230 has the 300 dpi printing option, and that it is enabled.

There have also been some recent changes in the Linux "cups-filters" package to correct an issue with Ghostscript rendering of bar codes.

**Comment by angelopbernardes** [comment]
Hi Michael, thank you for answer so fast, I've checked and the printer in question has the 300DPI mode enabled and when I use the Windows Driver (Made by Zebra) the tag is printed ok.
I updated all cups packages that you told and nothing changed.
Do you have any other suggestion?

**Comment by frazhome** [comment]
did you replaced the 203dpi printhead with the 300dpi printhead, when you changed the resolution?
It is not enough to change the driver settings.

Maybe you run into the issue:
https://github.com/apple/cups/issues/4820

regards
Franz
