### ISSUE TITLE
cups-2.2.2: cupsd won't start when gssapi has been disabled during compilation

### ISSUE THREAD

**Issue by Polynomial-C** [apple/cups#4947]
In [Gentoo bug #606472](https://bugs.gentoo.org/606472) we got a report that cupsd from cups-2.2.2 fails to start with its default cupsd.conf file if cups has been compiled without gssapi support.
We've fixed this by conditionally removing the kerberos policy part from cupsd.conf (see gentoo/gentoo@7ee57377c41da4814963ba9a162d03bc466448d8) but perhaps this can be fixed in a more convenient way.

**Comment by michaelrsweet** [comment]
Hmm, OK, we'll look into a better long-term solution.

**Comment by michaelrsweet** [comment]
Fixed in TOT.
