### ISSUE TITLE
CUPS iOS

### ISSUE THREAD

**Issue by jlwatkins** [apple/cups#4948]
I see here that it states there is a library for iOS. Can this be used for client side printing and getting a list of printers in a modern Swift 3 project? Are there any examples of a working xcode project that can be used in an iOS application?

I am referring the readme stated here:
https://github.com/apple/cups/tree/master/xcode

`the CUPS library for iOS`

**Comment by michaelrsweet** [comment]
The target is mainly there for printer manufacturers that want to do their printer utilities over IPP.

There is no explicit Swift support for CUPS (and honestly I have no idea how Swift bridges things to C APIs), while there *is* explicit Swift support for AirPrint through the UIKit framework (which is what Apple supports for printing on iOS).
