### ISSUE TITLE
"lpadmin -m everywhere": Odd error messages when no PPD can get generated

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#4954]
If one uses "lpadmin" with the "-m everywhere" option to create a CUPS queue with auto-generated PPD based on polling printer capabilities via IPP (on IPP Everywhere or AirPrint printers) and the IPP printer does not support driverless printing, CUPS is not able to create a PPD file.

The problem here is an odd error message:

```
till@till-x1carbon:~/printing/cups/bzr/y$ lpadmin -p ippcupstest -E -v ipp://till-x1carbon.local:631/printers/printer -m everywhere
lpadmin: Unable to create PPD file: No such file or directory
till@till-x1carbon:~/printing/cups/bzr/y$
```

In another attempt with another printer I get

```
till@till-x1carbon:~/printing/cups/bzr/y$ lpadmin -p ippcupstest -E -v ipp://NPI90E6C1.local:631/NPI90E6C1 -m everywhere
lpadmin: Unable to create PPD file: Success
till@till-x1carbon:~/printing/cups/bzr/y$
```

The first printer is a CUPS queue where the PPD generation fails due to Issue #4950 and the second is an IPP printer which is not an IPP Everywhere or AirPrint printer (HP Color LaserJet CM3530 MFP via built-in Ethernet connector).

IPP records of the printers attached.
ipptool -tv ipp://till-x1carbon.local:631/printers/printer get-printer-attributes.test > cups-queue-hp-clj-cm3530.txt

[cups-queue-hp-clj-cm3530.txt](https://github.com/apple/cups/files/743431/cups-queue-hp-clj-cm3530.txt)

ipptool -tv ipp://NPI90E6C1.local:631/NPI90E6C1 get-printer-attributes.test > printer-NPI90E6C1.txt

[printer-NPI90E6C1.txt](https://github.com/apple/cups/files/743433/printer-NPI90E6C1.txt)

There should be a decent error message, like

Unable to create PPD file: Printer does not supply sufficient information (probably not IPP Everywhere or AirPrint)

**Comment by michaelrsweet** [comment]
Added error messages.
