### ISSUE TITLE
CUPS get stuck for long periods of time handling groups with many users

### ISSUE THREAD

**Issue by akorobkin** [apple/cups#4956]
My /etc/groups.cache file is 32Mb in size, containing tens of thousands of users in 14 thousand groups. Whenever CUPS 2.2.2 stumbles upon AllowUser @groupname in the printers.conf file, cupsdCheckGroup() dives into these groups and becomes unresponsive for seconds. With many printers it easily turns into minutes on a busy server.

This seems to happen when 
a) job attributes are loaded:
```
d [02/Feb/2017:12:27:32 -0800] cupsdLoadJob: JobHistoryUpdate=1486066324
d [02/Feb/2017:12:27:32 -0800] cupsdCheckGroup(username="anonymous", user=(nil), groupname="OWNER")
```

b) printers are listed, and some of them are private (AllowUser):
```
D [02/Feb/2017:12:28:45 -0800] CUPS-Get-Printers
d [02/Feb/2017:12:28:45 -0800] get_printers(0x7fce197452c0[12], 0)
<...>
d [02/Feb/2017:12:28:46 -0800] cupsdCheckGroup(username="akorobkin", user=0x7fcdf43f9240, groupname="printergurus")
```

It didn't happen in CUPS 2.1.x, so I traced it down to getgrouplist() in https://github.com/apple/cups/commit/6eb98aee93be531b09425ea4bce86cfe05e8b4ef#diff-574168d22229d2c090c033dfa9fb6c22R1186

Somehow this function is very slow with large groups to check, and throwing away whole block of "#ifdef HAVE_GETGROUPLIST" solved my problem: authentication works OK, but there is no more stuck moments anymore. 

To verify my findings, I compared strace output from before and after the removal. 
With getgrouplist() whole file /etc/groups.cache is read line by line, until it finds all the groups. 
Without the function I see it seeking straight to the relevant lines and reading them. 

Is it OK to remove getgrouplist()? Does any other part of the code depend on it?

**Comment by michaelrsweet** [comment]
getgrouplist is an optimization (or at least it is supposed to be) that also handles groups that span different auth servers (/etc/groups, LDAP, etc.)

Sounds like getgrouplist on your system is poorly optimized - what OS/Linux distribution are you using?

**Comment by akorobkin** [comment]
I'm on Ubuntu 14.04 x64. I can try to report it to launchpad bug tracker, but I'd need to tell what I'm comparing it to, and it's unclear to me from the code what function was there before 2.2. 

man getgrouplist() has a nice example C program for me to try, and I can time it to tell the difference. 
http://man7.org/linux/man-pages/man3/getgrouplist.3.html

**Comment by michaelrsweet** [comment]
OK, so the fallback code in cupsd is to use the gr_mem array in the group structure, so you'd be comparing the speed of:

    group = getgrnam("group");
    user    = getpwnam("user");

    /* use getgrouplist("user", user->pw_gid, ...) and compare the integer groups against group->gr_gid */

to:

    group = getgrnam("group");
    user    = getpwnam("user");

    /* loop through group->gr_mem comparing against the username */

**Comment by akorobkin** [comment]
Thank you. Do I understand it correctly that the function cupsdCheckGroup() wants to check if the user is a member of one particular group passed via arguments? 

Looks like Getgrouplist() gets all groups the user belong to, while group->gr_mem method would read only the members of one group. In my situation gr_mem method is vastly more efficient than getgrouplist because it doesn't need to read all members of all groups to figure out the list of groups.

**Comment by michaelrsweet** [comment]
Yes, you understand correctly.

The reason for using getgrouplist() is that it handles groups that span local and network domains (i.e. both a local and network "staff" group), while getgrnam only returns one matching group (typically the local group, although which group "wins" is undefined...)

Conceptually we could add a configuration directive for this ("AllowDuplicateGroups <boolean>" or something like that) so that we can use the more efficient lookup by default.

**Comment by akorobkin** [comment]
A vaguely related question: this code is part of get_printers() routine in ipp.c, line 7536:
```
      if (cupsArrayCount(printer->users) && username &&
	  !user_allowed(printer, username))
        continue;
```
I think it is responsible for printers being hidden from the list retrieved via lpstat or Get-Printers or web UI when user is not allowed to print to it. It's inconvenient in my environment because print admins can't see printers that they are not allowed to use, but allowed to change. 

If I remove these lines, do you think it will break anything in CUPS?

**Comment by michaelrsweet** [comment]
It won't technically break anything, but it *will* probably increase user support calls (why can I see the printer but not print to it?)

**Comment by akorobkin** [comment]
To anyone who encounters the same issue: installing nscd drastically improves performance of getgrouplist(). 

Thanks Mike! This issue can be resolved. As for support calls, in my environment it's OK: people see the same printers via Samba or Cloud Print, it's more confusing to them when they do not see a printer. Also private printers are explicitly labelled/named as private.

**Comment by michaelrsweet** [comment]
OK, perhaps if I do a CUPS performance tuning guide I'll remember to add a note about large groups and nscd.
