### ISSUE TITLE
CUPS prints error messages when more than 1 page

### ISSUE THREAD

**Issue by i-Moi** [apple/cups#4957]
Hi everybody from Paris,

I have CUPS 1.7.5 installed on my RPi B+, with a 8Gb SD Cad on it, running Jessie Raspbian (january 2017), connected through USB to a Laser Postscript Lexmark printer (352dn), and through wifi to my network, using the AirPrint (Avahi) feature on my Mac.

When I print small text or pdf docs, printing only 1 page at a time, everything is fine. I generally have to resize printing to 90% of the actual size. If I do otherwise, I get a blank page with hermetical code in it, like :

`7oM*o%:D37/I$S.]\mgscphMRIG413
                                                             (Z=Q;")5F8)`Qr"=NfCOoQ)ibuD`CCLE1_#S2=*J!5rCj3Lr`

So I tend to think that it's either a SD card size issue, or a memory issue (the latter being IMHO the most plausible explanation).

The problem is that when I print directly from my Mac, without RPi and CUPS, no problem : therefore the printer itself does have enough memory to print a poor 2 pages PDF bill...

I tried 3 different PPD files already : the official Lexmark for Linux 4, the one I got already installed on the Mac, and the Gutenprint one... The generic Postscript one works faster, but otherwise, nothing changes.

Does anyone has had the same problem, or have an idea ?
Thanks a lot everybody

i-Moi

**Comment by michaelrsweet** [comment]
Not sure what is going wrong here; you might try using the network interface on the printer to eliminate the USB port as the problem...
