### ISSUE TITLE
New install, v1.7.2? 2 different error messages, 3 different printers?

### ISSUE THREAD

**Issue by davidmoss1** [apple/cups#4959]
using MagPi June 2015, p46, as a guide, installed CUPS, went to 127.0.0.1:631 added my 1 printer connected by usb cable, and it wont print from ubuntu 14.04, kernal 108 running on a hp-mini talking to a hp-deskjet 3510.  manage printers shows 3 different machines, with 2 different error messages?

Search in Printers:

Showing 3 of 3 printers.
▼ Queue Name ▼	Description	Location	Make and Model	Status
Deskjet-3510-series	HP Deskjet 3510 series	hpmini	HP Deskjet 3510 Series hpijs, 3.14.3	Idle - "Directory "/usr/lib/cups/filter" has insecure permissions (040777/uid=0/gid=0)."
HP-Deskjet-3510	HP Deskjet 3510	10.0.0.10	HP Deskjet 3510 Series, hpcups 3.14.3	Idle - "File "/usr/lib/cups/filter/hpcups" not available: No such file or directory"
HP_Deskjet_3510_series	HP Deskjet 3510 series	Graham	HP Deskjet 3510 Series hpijs, 3.14.3	Idle - "Directory "/usr/lib/cups/filter" has insecure permissions (040777/uid=0/gid=0)."

What am I missing in the installation?  Thank You

**Comment by michaelrsweet** [comment]
Well, for one thing the permissions of the CUPS filter directory are bad:

   chmod 755 /usr/lib/cups/filter

You are also missing the hpcups filter (not sure what the package is called for the HP drivers, sorry.)
