### ISSUE TITLE
Map PPD keyword "RIFoldType" to equivalent IPP attribute(s)

### ISSUE THREAD

**Issue by michaelweghorn** [apple/cups#4962]
As recently discussed in the thread "PPD API: Status, future and alternatives to handle printer-specific options" on the CUPS mailing list [1], [2], CUPS currently does not match the (vendor-specific) PPD keyword "RIFoldType" to any IPP attributes.

This means that folding is not supported when using the Job Ticket API, but only when using the deprecated PPD API to retrieve printer options for respective printers.

As suggested on the CUPS mailing list [3], I am asking to add support for this (non-standard) keyword so that it is mapped to the respective IPP attribute(s).

A sample PPD for a RICOH MP C5504 and the output of the `ipptool get-attributes` command for the respective printer queue set up with the PPD are attached to issue #4960.

[1] http://lists.cups.org/pipermail/cups/2017-January/thread.html
[2] http://lists.cups.org/pipermail/cups/2017-February/thread.html
[3] http://lists.cups.org/pipermail/cups/2017-February/028204.html

**Comment by michaelrsweet** [comment]
So as noted in Issue #4960 we have a mechanism for PPDs to tell CUPS how to map their vendor-specific finishing options to IPP finishing templates. I will add these Ricoh-specific fold options (as well as the Adobe standard fold options) to the finishing options _ppdCacheCreateWithPPD looks for when cupsIPPFinishings is not defined.

**Comment by michaelrsweet** [comment]
Changes in TOT.
