### ISSUE TITLE
Cupsfilter PDF generation options not documented

### ISSUE THREAD

**Issue by tobyjsullivan** [apple/cups#4965]
I am using cupsfilter (on Mac OS) to generate a PDF from a PostScript file however the output always has the default paper size. I need to be able to specify the paper size of the PDF output.

Looking at the [cups documentation](https://www.cups.org/doc/options.html#OPTIONS), I found a "media" option but this doesn't appear to have any effect with the cupsfilter default PDF generation. None of the listed options appear to work. Is there any documentation for options accepted by the filter `pstopdffilter`?

The command I have attempted is:

```
cupsfilter -o "media=Custom.36x72in" -o fit-to-page=true ~/sandbox/in-file.eps > ~/sandbox/out-file.pdf
```

**Comment by michaelrsweet** [comment]
Toby, please file a bug with Apple on this. The filter in question (PS normalizer) typically only converts the PS to PDF as-is, and doesn't offer the usual set of options since it only exists on macOS.

**Comment by michaelrsweet** [comment]
(https://bugreport.apple.com)
