### ISSUE TITLE
CUPS webinterface cannot handle crazy queue names

### ISSUE THREAD

**Issue by leoarnold** [apple/cups#4966]
In CUPS, the following are valid queue names:

- `'` (single-quote literal)
- `"` (double-quote literal)
- `\` (backslash)

Trying to modify or delete such a printer *through the webinterface* won't work (tested with several versions of CUPS).

(Just an observation. I personally do not use those characters in queue names.)

**Comment by michaelrsweet** [comment]
Yes, this looks like an issue with the validation of resource paths in scheduler/client.c.

**Comment by leoarnold** [comment]
Question marks also seem to pose a problem

**Comment by michaelrsweet** [comment]
[master f1547f121] No longer support backslash, question mark, or quotes in printer names (Issue #4966)
