### ISSUE TITLE
CUPS-Create-Local-Printer: dash becomes underscore in print queue name

### ISSUE THREAD

**Issue by stephanwib** [apple/cups#4967]
I was experimenting with the CUPS-Create-Local-Printer IPP call in order to create IPP Everywhere print queues on CUPS servers. I used ipptool with the cups-create-local-printer.test file. If the print queue name provided contains a dash, the dash is changed to an underscore for the resulting print queue on the server.

Please see below for an exemplary Wireshark trace:

POST / HTTP/1.1
Content-Length: 188
Content-Type: application/ipp
Host: lin1:631
User-Agent: CUPS/2.2.2 (NetBSD 7.0; amd64) IPP/2.0
Accept-Encoding: deflate, gzip, identity
Expect: 100-continue

..@(.....G..attributes-charset..utf-8H..attributes-natural-language..enE..printer-uri..ipp://lin1:631/B..requesting-user-name..root.B..printer-name..hp-eE.
device-uri..ipp://10.70.235.32/.HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Connection: Keep-Alive
Content-Language: en
Content-Length: 251
Content-Type: application/ipp
Date: Thu, 16 Feb 2017 10:54:12 GMT
Keep-Alive: timeout=10
Accept-Encoding: identity
Server: CUPS/2.2 IPP/2.1
X-Frame-Options: DENY
Content-Security-Policy: frame-ancestors 'none'

.........G..attributes-charset..utf-8H..attributes-natural-language..enA..status-message..Local printer created.."..printer-is-accepting-jobs...#.
printer-state......D..printer-state-reasons..noneE..printer-uri-supported..ipp://lin1:631/printers/hp_e.

**Comment by michaelrsweet** [comment]
This is as designed.
