### ISSUE TITLE
How to archive tray selection information?

### ISSUE THREAD

**Issue by guettli** [apple/cups#4968]
This is a follow up to #4964

Cups support tray selection. Nice.

But how to archive tray selection data with printed data?

Our customer wants to archive the printed documents **and** the tray selection.

**Comment by michaelrsweet** [comment]
The job ticket information is part of the job history but is not embedded (by CUPS at least) in the spooled documents. If you want a permanent archival of whole print jobs you are probably better off using a third party solution with CUPS so that you don't have performance issues down the road.

**Comment by guettli** [comment]
Do you know which third party solutions provide an archive which stores the tray selection information?

**Comment by michaelrsweet** [comment]
Most of them are infinitely configurable/scriptable for this; I think Pykota will do it, but best to search for a solution with your favorite search engine...
