### ISSUE TITLE
Getting Error while compiling cups for MIPS

### ISSUE THREAD

**Issue by jammy12** [apple/cups#4970]
Hi,

I am trying to compile cups-2.2.2 for MIPS by using below command.

./configure --host=mips --target=mips --disable-gnutls --disable-gssapi --disable-dbus --without-python --disable-shared --without-java --without-php --without-perl --with-optim=-fPIC --libdir=/usr/lib --without-systemd

And then,

make

I am getting below error.

../cups/libcups.a(http-addr.o): In function `httpGetHostByName':
http-addr.c:(.text+0x140c): warning: gethostbyname is obsolescent, use getnameinfo() instead.
Making all in ppdc...
Compiling ppdc-array.cxx...
Compiling ppdc-attr.cxx...
Compiling ppdc-catalog.cxx...
ppdc-catalog.cxx: In constructor ‘ppdcCatalog::ppdcCatalog(const char*, const char*)’:
ppdc-catalog.cxx:138:42: error: ‘strlcpy’ was not declared in this scope
       strlcpy(baseloc, l, sizeof(baseloc));
                                          ^
ppdc-catalog.cxx: In member function ‘int ppdcCatalog::load_messages(const char*)’:
ppdc-catalog.cxx:455:29: error: ‘strlcpy’ was not declared in this scope
  strlcpy(id, ptr, sizeof(id));
                             ^
ppdc-catalog.cxx:473:31: error: ‘strlcpy’ was not declared in this scope
  strlcpy(str, ptr, sizeof(str));
                               ^
ppdc-catalog.cxx:478:31: error: ‘strlcat’ was not declared in this scope
  strlcat(str, ptr, sizeof(str));
                               ^
ppdc-catalog.cxx:480:29: error: ‘strlcat’ was not declared in this scope
  strlcat(id, ptr, sizeof(id));
                             ^
make[1]: *** [ppdc-catalog.o] Error 1
make: *** [all] Error 1

I  know it is simple linking issue, could you help me to resolve this error.

**Comment by michaelrsweet** [comment]
Can you attach a config.log file?

**Comment by jammy12** [comment]
Now i solved the 'strlcat' and 'strlcpy' error by adding the definitions of strlcpy and strlcat in cups/strings.c file. But after that, i am getting below error.

a - ppdc-array.o
a - ppdc-attr.o
a - ppdc-catalog.o
a - ppdc-choice.o
a - ppdc-constraint.o
a - ppdc-driver.o
a - ppdc-file.o
a - ppdc-filter.o
a - ppdc-font.o
a - ppdc-group.o
a - ppdc-import.o
a - ppdc-mediasize.o
a - ppdc-message.o
a - ppdc-option.o
a - ppdc-profile.o
a - ppdc-shared.o
a - ppdc-source.o
a - ppdc-string.o
a - ppdc-variable.o
Compiling ppdc.cxx...
Linking ppdc...
/usr/bin/ld: ../cups/libcups.a(array.o): Relocations in generic ELF (EM: 8)
/usr/bin/ld: ../cups/libcups.a(array.o): Relocations in generic ELF (EM: 8)
../cups/libcups.a: could not read symbols: File in wrong format
collect2: error: ld returned 1 exit status
make[1]: *** [ppdc] Error 1


I am attaching the config.log file

[config.docx](https://github.com/apple/cups/files/802724/config.docx)

**Comment by michaelrsweet** [comment]
Any chance you can attach the original, plain text config.log file and not the file imported into Word?

The latest errors make me suspect you have an incompatible version of the C++ compiler installed on your system, or just a general compiler tool bug.

**Comment by michaelrsweet** [comment]
Closing for now; will re-open if I get more info to act on...
