### ISSUE TITLE
`cups_option_t` should have `const char*` members

### ISSUE THREAD

**Issue by marc-kdab** [apple/cups#4971]

**Comment by marc-kdab** [comment]
Most of the time, the option names are known, and having `char*` members prevents from filling an `cups_option_t[]` as

    cups_option_t options[] = {
        { "sides", "one-sided", },
        // ...
    };

in C++, since in C++, a string literal is of type `const char[]` and cannot implicitly convert to a char* without a `const_cast`.

Looking at `cups.h`, it seems many APIs have this problem.

**Comment by michaelrsweet** [comment]
The APIs that manipulate cups_option_t arrays work with allocated strings (and arrays). While you can technically (right now) pass a static array of cups_option_t's to the cupsPrint* and cupsCreate* APIs when queuing a print job, you cannot pass them to any of the cups*Option APIs and the intent is not to support such usage.

(That the cups_option_t array is exposed is an artifact of the time CUPS was originally written; today such an API would use an opaque type to enforce safe usage...)
