### ISSUE TITLE
cupsFinishingTemplate handling issues

### ISSUE THREAD

**Issue by stephanwib** [apple/cups#4976]
As discussed on the CUPS mailing list:

Given the following IPP Everywhere generated PPD:

*OpenUI *cupsFinishingTemplate/Finishing: PickMany
*OrderDependency: 10 AnySetup *cupsFinishingTemplate
*DefaultcupsFinishingTemplate: none
*cupsFinishingTemplate none/No Finishing: ""
*cupsIPPFinishings 3/none: "*cupsFinishingTemplate none"
*cupsFinishingTemplate staple/Staple: ""
*cupsIPPFinishings 4/staple: "*cupsFinishingTemplate staple"
*cupsFinishingTemplate staple-top-left/Single Staple (Portrait): ""
*cupsIPPFinishings 20/staple-top-left: "*cupsFinishingTemplate staple-top-left"
*cupsFinishingTemplate staple-top-right/Single Staple (Landscape): ""
*cupsIPPFinishings 22/staple-top-right: "*cupsFinishingTemplate
staple-top-right"
*CloseUI: *cupsFinishingTemplate

When a print job is submitted with the setting
"cupsFinishingTemplate=staple", the option vector for the filters and
backend looks like this:

D [09/Mar/2017:07:43:29 +0000] [Job 795] argv[5]="ColorModel=Gray
cupsFinishingTemplate=staple Duplex=None finishings=3 InputSlot=Auto
MediaType=Stationery number-up=1 OutputBin=Tray1 PageSize=A4
job-uuid=urn:uuid:2030f953-2c5f-305e-50b7-8907717ad0c2
job-originating-host-name=localhost date-time-at-creation=
date-time-at-processing= time-at-creation=1489045409
time-at-processing=1489045409
document-name-supplied=Administrator-6bb3985e
cupsFinishingTemplate=none"

The option cupsFinishingTemplate appears twice, one is set to "staple"
and one to "none". The standard "finishings" option is set to 3
(none). As a result, the job is set up with finishings set to none:

D [09/Mar/2017:07:43:30 +0000] [Job 795] ---- job-attributes-tag ----
D [09/Mar/2017:07:43:30 +0000] [Job 795] media-col collection
{media-size={x-dimension=21000 y-dimension=29700}
media-type=stationery media-top-margin=423 media-left-margin=423
media-right-margin=423 media-bottom-margin=423 media-source=auto}
D [09/Mar/2017:07:43:30 +0000] [Job 795] output-bin keyword tray-1
D [09/Mar/2017:07:43:30 +0000] [Job 795] print-color-mode keyword
auto-monochrome
D [09/Mar/2017:07:43:30 +0000] [Job 795] print-quality enum normal
D [09/Mar/2017:07:43:30 +0000] [Job 795] sides keyword one-sided
D [09/Mar/2017:07:43:30 +0000] [Job 795] multiple-document-handling
keyword separate-documents-collated-copies
D [09/Mar/2017:07:43:30 +0000] [Job 795] finishings enum none

However, when the option "finishings=4" is provided insted, the option
vector looks like this:

D [09/Mar/2017:08:13:52 +0000] [Job 798] argv[5]="finishings=4
number-up=1 job-uuid=urn:uuid:4b3dcdf5-eade-3f4c-408a-2a683c1bbf72
job-originating-host-name=localhost date-time-at-creation=
date-time-at-processing= time-at-creation=1489047232
time-at-processing=1489047232
document-name-supplied=Administrator-6bb3985e
cupsFinishingTemplate=staple"

The option "cupsFinishingTemplate=staple" is applied automatically
with the right value and the job attribute is also correct:

D [09/Mar/2017:08:13:53 +0000] [Job 798] finishings enum staple

To conclude, the finishing options are only selectable throgh
"finishings", but not through the PPD option "cupsFinishingTemplate".

**Comment by michaelrsweet** [comment]
OK, this is because cupsFinishingTemplate is a "PickMany" option...  Need to think a bit about what the right solution is here...

**Comment by michaelrsweet** [comment]
[master a740a84] The IPP Everywhere finishings support did not work correctly with common UI or command-line options (Issue #4976)
