### ISSUE TITLE
runloop.c: 2 * bad condition ?

### ISSUE THREAD

**Issue by dcb314** [apple/cups#4979]
runloop.c:80:27: warning: logical 'or' of collectively exhaustive tests is always true [-Wlogical-op]
runloop.c:308:22: warning: logical 'or' of collectively exhaustive tests is always true [-Wlogical-op]

      if (errno != EAGAIN || errno != EINTR)

**Comment by michaelrsweet** [comment]
[master 0b1399a] Fix an issue with the error handling for the network backends (Issue #4979)
