### ISSUE TITLE
ppd-cache.c: 2 * bad condition ?

### ISSUE THREAD

**Issue by dcb314** [apple/cups#4980]
ppd-cache.c: In function '_ppdCacheWriteFile':
ppd-cache.c:2880:28: warning: logical 'or' of equal expressions [-Wlogical-op]
   if (pc->cups_accuracy[0] || pc->cups_accuracy[0] || pc->cups_accuracy[2])
                            ^~
ppd-cache.c:2883:26: warning: logical 'or' of equal expressions [-Wlogical-op]
   if (pc->cups_volume[0] || pc->cups_volume[0] || pc->cups_volume[2])
                          ^~

**Comment by michaelrsweet** [comment]
[master 87f3405] Clean out old code (Issue #4980)
