### ISSUE TITLE
cups-pdf mixes portret and landscape

### ISSUE THREAD

**Issue by freekdk** [apple/cups#4981]
I am using cups-pdf.3.0.0 and I try to print from LibreOffice 5.3.0.3 a 24 page A5 document as brochure. I would expect 12 pages with page 1 and 24 on one A4, page 2 and 23 on one page A4, etc. I do get such a PDF file. However part of the A4 pages are in portret and the rest in landscape orientation. These pages are intermixed. Printing this file in one does not give a good result. The printer needs a setting in portret or landscape orientation.

**Comment by freekdk** [comment]
![spectacle vr4241](https://cloud.githubusercontent.com/assets/3691996/23914345/ff36f642-08e5-11e7-9ba5-b84da1989a2f.png)
The picture shows the sidebar of okular with part of the pages in the PDF and shows the mix of portret and landscape.

**Comment by michaelrsweet** [comment]
This isn't CUPS, but a combination of cups-pdf and LibreOffice...

**Comment by jsmeix** [comment]
@freekdk only FYI
regarding LibreOffice and "landscape"
you may have a look at
https://en.opensuse.org/SDB:Landscape_Printing

**Comment by jpka-** [comment]
It is not Libreoffice. It is Cups-PDF. (The software nowadays tend to be smarter than humans; this always fail). The working solution i found and post here: 
https://bugs.launchpad.net/ubuntu/+source/cups-pdf/+bug/798036
And it is still not fixed now. My current cups-pdf-3.0.1-x86_64-1_slonly still have this bug. The bug and fix is same on Ubuntu and Slackware.

**Comment by michaelrsweet** [comment]
and CUPS-PDF is not part of CUPS...

**Comment by debiantriage** [comment]
On Thu 06 Sep 2018 at 18:08:47 +0000, jpka- wrote:

> It is not Libreoffice. It is Cups-PDF. (The software nowadays tend to
> be smarter than humans; this always fail). The working solution i
> found and post here:
> https://bugs.launchpad.net/ubuntu/+source/cups-pdf/+bug/798036 And it
> is still not fixed now. My current cups-pdf-3.0.1-x86_64-1_slonly
> still have this bug. The bug and fix is same on Ubuntu and Slackware.

No, it is not cups-pdf. All that does is convert a file to PDF. Having
said that, CUPS is not involved either.

You appear to have been searching for a solution since 2011 but have not
found the Debian wiki printing portal yet.

-- 
Brian.
