### ISSUE TITLE
mantohtml.c:1156: bad test ?

### ISSUE THREAD

**Issue by dcb314** [apple/cups#4982]
mantohtml.c:1156]: (warning) Logical conjunction always evaluates to false: EXPR == '\"' && EXPR == '\''.
mantohtml.c:1156]: (warning) Logical conjunction always evaluates to false: EXPR == '\'' && EXPR == '-'.

Source code is

        if (*s != '\\' && *s == '\"' && *s == '\'' && *s == '-')
          fprintf(stderr, "mantohtml: Unrecognized escape \"\\%c\" ignored.\n", *s);

        html_putc(*s++, fp);

Note also that the error message is wrong - there is no ignoring. 
It does the same html_putc with all characters.

**Comment by michaelrsweet** [comment]
The message is there to say that nothing special will be done with the escape sequence - nroff supports a lot of different kinds of \ escape sequences, and the message is a warning for sequences mantohtml does not support.

**Comment by michaelrsweet** [comment]
[master 845913b] Fix mantohtml compiler warning (Issue #4982)
