### ISSUE TITLE
how to create a raster by PPD file

### ISSUE THREAD

**Issue by 502904420** [apple/cups#4983]
I have a new printer, there is no raster for it . I want to write a raster likes rastertoepson in CUPS by PPD file, but i don't how !

**Comment by michaelrsweet** [comment]
Without further information it is hard to provide specific guidance.

You might want to check on the [OpenPrinting](https://wiki.linuxfoundation.org/openprinting/start) web site to see if a driver already exists.

Most network printers will work out-of-the-box via IPP.

Worst case you can read the [Developing Raster Printer Drivers](https://www.cups.org/doc/raster-driver.html) documentation on the CUPS web site for details of how to write a driver for CUPS.
