### ISSUE TITLE
Rename the "-m everywhere" option into "-m driverless"

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#4985]
Using "-m everywhere" with the lpadmin command does not only allow setting up IPP Everywhere printers but also Apple AirPrint printers, so it sets up driverless printing in general. Therefore it makes more sense to call it "-m driverless". We can let lpadmin accept both doing the same thing for backward compatibility.

**Comment by michaelrsweet** [comment]
First, we do not officially support AirPrint using the IPP Everywhere PPD generator, it MAY work but is definitely beta functionality and has not been fully tested nor optimized.

Second, I see no point in making a gratuitous and incompatible name change for a function that is only provided for setting up legacy print queues. The supported, modern printing APIs handle automatic queue creation, if only applications and toolkits will start using them 7 years after they were first introduced...
