### ISSUE TITLE
"FAIL: 62 job control files were not purged" when building CUPS 2.2.3

### ISSUE THREAD

**Issue by akorobkin** [apple/cups#4987]
I can't seem to build CUPS 2.2.3 on Ubuntu, it stops at "FAIL: 62 job control files were not purged" error during run-stp-tests.sh run. 

```
Test Summary

PASS: cupsd exited with no errors.
FAIL: 62 job control files were not purged.
PASS: Printer 'Test1' correctly produced 60 page(s).
PASS: Printer 'Test2' correctly produced 23 page(s).
PASS: Printer 'Test3' correctly produced 2 page(s).
PASS: 165 requests logged.
PASS: CUPS-Get-Default not logged.
PASS: 0 emergency messages.
PASS: 0 alert messages.
PASS: 0 critical messages.
PASS: 33 error messages.
PASS: 8 warning messages.
PASS: 0 notice messages.
PASS: 734 info messages.
PASS: 22724 debug messages.
PASS: 20531 debug2 messages.

1 tests failed.
Log files can be found in /tmp/cups-pbuser/log.
A HTML report was created in /tmp/cups-pbuser/cups-str-2.2-2017-03-30-pbuser.html.

Copies of the error_log and cups-str-2.2-2017-03-30-pbuser.html files are in
/tmp/build-debs.elDewS/build/test.

make[2]: *** [check] Error 1
make[2]: Leaving directory `/tmp/build-debs.elDewS/build'
make[1]: *** [override_dh_auto_test] Error 2
make[1]: Leaving directory `/tmp/build-debs.elDewS/build'
make: *** [build] Error 2
```

However, editing the line 2743 in scheduled/job.c from
`	else if (!JobHistory && !job->printer)
`
back to (as was changed from 2.2.2 to 2.2.3)

`	else if (!job->printer)
`
seems to fix the issue. 

Report file (rename to .html)
[cups-str-2.2-2017-03-30-pbuser.html.txt](https://github.com/apple/cups/files/882981/cups-str-2.2-2017-03-30-pbuser.html.txt)

**Comment by OdyX** [comment]
I can confirm this bug, and I have `git bisect`'ed it to point to https://github.com/apple/cups/commit/875ef65a9e735fc27aa15b54d720d00ccca6bdf1 ; it appears that the fix for https://github.com/apple/cups/issues/4915 actually introduces this regression.

**Comment by michaelrsweet** [comment]
[master 57543d87b] Fix regression in job file preservation (Issue #4987)
