### ISSUE TITLE
How to build a virtual printer server like Printer Simulator

### ISSUE THREAD

**Issue by guofengld** [apple/cups#4988]
seriously, this is not an issue to cups, but I still write to ask for help.

I need to create a virtual printer server similar to *Printer Simulator* provided by Apple in *Additional Tools for Xcode*, after spending days on studying cups and other documents, still have no idea where to start, will you please give me some suggestions to let me on the way?

thanks.

**Comment by michaelrsweet** [comment]
You probably want to use the ippserver program, either as provided in CUPS (simple version) or in the PWG ippsample project (https://istopwg.github.io/ippsample).
