### ISSUE TITLE
Lexmark E260dn only prints one page (works fine with Windows)

### ISSUE THREAD

**Issue by JazzTp** [apple/cups#4994]
Hi,

I have a **Lexmark E260dn** monochromatic laser printer, it works perfectly fine with Windows, but it **only prints one page** (perfectly fine, too) with Linux Ubuntu 16.04, nothing more until I reboot.

The same had been happening since various years ago with an older Linux Fedora (22.3 I think it was)... it was worse actually, because after the first page it kept printing a few garbage characters per page, thus ejecting many sheets (which was besides probably decreasing the infamous counter in the toner chip).

This obliges me (sic) to export pdf files and boot Windows to print.

**Comment by michaelrsweet** [comment]
@JazzTp How is this printer connected to your Linux system?

If via USB, what is the output of "lsusb"?

If via network, what is the output of "lpstat -v"?

Finally, what version of CUPS are you using?

This sounds very much like a common Lexmark USB printer issue where we've added the following to the /usr/share/cups/usb/org.cups.usb-quirks file:

    0x043d 0xNNNN no-reattach

where "NNNN" is the second ID number from lsusb.

For testing purposes, you can create a file called "lexmark" in /usr/share/cups/usb containing:

    0x043d no-reattach

to force this workaround for all Lexmark models...

**Comment by JazzTp** [comment]
@michaelrsweet Thank you very much for replying.

I have now created a file called "lexmark" in /usr/share/cups/usb containing

`0x043d 0xNNNN no-reattach
`

and rebooted (unnecessary?).

Then, I tried a two pages print (from evince, the default reader app which opens pdf files here) and for the first time it was **successful**.

**cups** installed **version** is **2.1.3-4** (I'm launching the software updater on this Linux 16.04 almost every day, I did so a couple of hours ago).

Output of **lsusb**:

```
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 008 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 007 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 006 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 001 Device 004: ID 12bd:a02f Gembird 
Bus 001 Device 003: ID 0458:003a KYE Systems Corp. (Mouse Systems) NetScroll+ Mini Traveler / Genius NetScroll 120
Bus 001 Device 005: ID 043d:0123 Lexmark International, Inc.   <===================
Bus 001 Device 002: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 005 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
Bus 003 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
```

The /usr/share/cups/usb/**org.cups.usb-quirks** file actually contains:

```
# Lexmark International, Inc. (e250d), https://bugs.launchpad.net/bugs/1084164
0x043d 0x00f3 no-reattach
```

as well as

```
# Lexmark E238 (<rdar://problem/14493054>)
0x043d 0x00d7 no-reattach

# Lexmark E238 (STR #4448)
0x043d 0x009a no-reattach

# Lexmark C540n (STR #4778)
0x043d 0x0139 no-reattach
```

**Comment by michaelrsweet** [comment]
Correct, we've added the "no-reattach" option for several printers, just not this one yet. Will include this in the next CUPS update...

0x043d 0x0123 no-reattach

**Comment by michaelrsweet** [comment]
Oh, and rebooting is unnecessary...

**Comment by JazzTp** [comment]
@michaelrsweet Understood everything... 

... Just great, so it will work with out-of-the-box cups...

If life was always like this, with such a fast solution to all problems...   :D

**Thank you!**

**Comment by michaelrsweet** [comment]
Reopening until I push the change for the next release...

**Comment by gqbgqb** [comment]
Hi Michaelrsweet,

Sorry to hijack this thread. I'm having the same symptoms in Mac OS X Sierra using SATO thermal printers. We already have 2.2.0 CUPS installed in the system. Could it be the "no-reattach" is not available for this model? Thank you so much

**Comment by JazzTp** [comment]
Hi,

No idea, but if you read Michael's first answers to me you might be able to
create a file which activates the no-reattach option for your printer.

**Comment by michaelrsweet** [comment]
@gqbgqb The macOS USB backend does NOT use "quirks" files, it uses a codeless kernel extension called a USB class driver, which is provided by the manufacturer when they provide drivers for their printer. USB printing issues in macOS should be reported to Apple directly (bugreport.apple.com) and not to the CUPS project since few driver issues actually involve the core CUPS code...

**Comment by gqbgqb** [comment]
Hi JazzTp, michaelrsweet ,

Thank you for your both reply. I'm quite stuck with this issue for while and I don't know where to look. This gives me a direction where to ask at least.

**Comment by JazzTp** [comment]
You're welcome (I'm sorry my answer was actually misleading).

**Comment by michaelrsweet** [comment]
[master ef338d0c8] Add USB quirk rule for Lexmark E260dn (Issue #4994)
