### ISSUE TITLE
page-ranges doesn't check syntax

### ISSUE THREAD

**Issue by archenemies** [apple/cups#4997]
If I try a command like

    lp doc.pdf -o page-ranges=8-

then Cups will print the whole document. It should either print pages 8 onward, or tell me that I've made a syntax error in the page specification. Any other behavior is a waste of my time and my paper and toner.

**Comment by michaelrsweet** [comment]
What OS/Linux distribution?

What version of CUPS?

**Comment by archenemies** [comment]
Arch Linux

Linux 4.9.18-1-lts #1 SMP x86_64 GNU/Linux

cups 2.2.2-2

Let me know if you need more help reproducing this. I had almost thought it would be a known bug. It seems much more general, indeed if I execute

    lp -o blah t.pdf

then the file is printed with no error, even though "blah" is not a recognized option (is it?). I will be surprised if this is system-specific.

**Comment by michaelrsweet** [comment]
It is, indeed, OS-specific. The bug lies in the print filters used on Linux, specifically the cups-filters package. Please report this to the openprinting folks.

(the "blah" option is just silently ignored...)

**Comment by archenemies** [comment]
Can you give me a URL for that?

**Comment by michaelrsweet** [comment]
Here is the bug tracker for cups-filters:

https://bugs.launchpad.net/ubuntu/+source/cups-filters

**Comment by archenemies** [comment]
Thanks. Reported here: https://bugs.launchpad.net/ubuntu/+source/cups-filters/+bug/1689948
