### ISSUE TITLE
In driverless PPD generator use case-insensitive comparisons

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#4998]
See the following Ubuntu bug report:
https://bugs.launchpad.net/ubuntu/+source/cups-filters/+bug/1689803
The user has an Epson EP-879A which is recognized as an IPP printer with driverless printing support (PWG Raster) by cups-browsed and automatically set up. Principally the printer prints, but not in color.
The same happens when generating the PPD file with
`lpadmin -p epson-ep-879a-series -E -v ipp://EPSONxxxxx.local:631/ipp/print -m everywhere`
So it is not caused by any bug in cups-browsed.
The PPD and the IPP attributes list of the printer are attached. The problem is caused by the upper-case writing of the PWG Raster color spaves in the IPP attributes:
`pwg-raster-document-type-supported (1setOf keyword) = Sgray_8,Srgb_8`
The PPD generator of CUPS uses the strcmp() function and not strcasecmp() for comparing and so does not match these color spaces, leaving the PPD without "ColorModel" option and so the pdftoraster filter defaulting to monochrome output.
I recommend to always use case-insensitive comparing (strcasecmp()) as manufacturers seem to use different upper/lower-case versions and there are no attributes where upper/lower-case results in different meanings.

PPD file:
[epson-ep-879a-series.ppd.txt](https://github.com/apple/cups/files/990894/epson-ep-879a-series.ppd.txt)

Output of "`ipptool -tv <URI> get-printer-attributes.test > out.txt`":
[epson-ep-879a-series-ipp-attr.txt](https://github.com/apple/cups/files/990914/epson-ep-879a-series-ipp-attr.txt)

**Comment by michaelrsweet** [comment]
OK, this printer is non-conforming. I will consider making this change but you'll need to report this bug to Epson so they can provide a firmware update.

**Comment by michaelrsweet** [comment]
[master d2817c9f0] Allow PWG Raster types to vary by case (non-conformant behavior for Issue #4998)
