### ISSUE TITLE
Purge Jobs says 'Unknown operation purge-jobs' in non english interface 2.1.3

### ISSUE THREAD

**Issue by maddeer** [apple/cups#4999]
Trying to Purge All jobs for printer in web interface. 
Going to printer page -> Cancel All Jobs 
It's not asking for password but saying "Unknown operation "purge-jobs" 

It 100% repeats in Russian langpack of Firefox  
If I switch Firefox to english langpack it`s working good.

**Comment by michaelrsweet** [comment]
This is likely a bug in the Russian printers.tmpl web localization file...

**Comment by michaelrsweet** [comment]
[master 143286bce] Fixed the "cancel all jobs" function in the web interface for several languages (Issue #4999)

**Comment by 346L3** [comment]
The exact same bug exists in the "class.tmpl" of the localizations & english default.

Please replace "purge" with "cancel" as well, thanks!
