### ISSUE TITLE
extra page printed by -o outputorder=reverse -o page-set=even

### ISSUE THREAD

**Issue by archenemies** [apple/cups#5000]
I tried to write a little script to automate manual duplex printing.

The last command is:

    lp -o page-set=even -o outputorder=reverse $FILE

However, this prints an extra page before the pages I want.

If I don't specify "-o page-set=even" then the extra page is not printed.

I'm attaching the postscript file and PPD which causes this problem.

[t.zip](https://github.com/apple/cups/files/1002197/t.zip)

**Comment by michaelrsweet** [comment]
What OS/Linux distribution are you using?

This sounds like a cups-filters issue...

**Comment by archenemies** [comment]
Arch Linux, sorry for the delay.

I submitted the bug to cups-filters last week:

https://bugs.launchpad.net/ubuntu/+source/cups-filters/+bug/1691574

**Comment by michaelrsweet** [comment]
OK, closing this bug unless their investigation turns up something in CUPS...
