### ISSUE TITLE
How do i disable lp ppdev parport_pc

### ISSUE THREAD

**Issue by apbonn** [apple/cups#5004]
Hi,

im using a raspberry pi 3 with jessie lite and cups, untill yesterday evening everything went well, but since today my pi boots in security mode and displays the errros:

`Failed to find module 'lp'`
`Failed to find module 'ppdev'`
`Failed to find module 'parport_pc'`

i figured out that reason could be cups, so im trying to disable these ports, in the internet i found a way to do it in 

`/etc/modules-load.d/cups-filters.conf`

but in this file, there is nothing in it.

so how do i disable these ports?

**Comment by michaelrsweet** [comment]
I don't know, that isn't something we use in stock CUPS. Please contact Debian for support on this issue...
