### ISSUE TITLE
Command line tool to execute cupsEnumDests() needed

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5005]
cupsEnumDests() is the recommended function to list the available printers in a print dialog, as it does not only list the queues set up with the local CUPS daemon but also available network printers advertised by DNS-SD, like IPP network printers and remote CUPS queues.
If you want to print from the command line, the "lpstat" command only shows the queues of the local CUPS daemon and no DNS-SD-advertised remote printers, whereas the "lp" and "lpr" commands allow printing on such remote printers, with CUPS auto-creating a temporary print queue. So command line users cannot find out which printers are available.
My suggestion is to add an extra command line option to "lpstat" which makes the network printers being included in the output of "lpstat" (the full output of cupsEnumDests()).

**Comment by michaelrsweet** [comment]
[master 4b17d76f2] Add support for "-e" option in lpstat (Issue #5005)

**Comment by tillkamppeter** [comment]
This is principally working, but after having done an operation which triggers the creation of a temporary queue, the name of the queue is shown twice, once because it is one of the current CUPS queues and once because it is an available network printer. The output needs to get filtered for duplicates.

**Comment by michaelrsweet** [comment]
[master 9022d60bb] Rework lpstat -e to use cupsGetDests to eliminate duplicates (Issue #5005)

**Comment by tillkamppeter** [comment]
Now it is working perfectly. Thanks.
