### ISSUE TITLE
Cannot print on remote printer with "lp" and "lpr"

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5006]
Running the cupsEnumDests() function I get a list of the queues of the local CUPS daemon and also of DNS-SD-advertised remote printers for which there is no CUPS queue available at the local CUPS daemon. On the former I can print with "lp" and "lpr" without problem, as it always was.
If I supply the queue name of one of the remote printers with the "-d" option of "lp", the command errors with "No such file or directory" after a delay of around 1 sec and it also errors this way if I supply a completely non-existing queue name with "-d".
For me it seems that the problem is that "lp" and "lpr" request the dest record from CUPS with the cupsGetNamedDest() function which seems only to work with CUPS queues which already exist at the local CUPS daemon. This function does not trigger CUPS to create a queue for a remote driverless printer.
I have now played around with the new CUPS functionality using the sample code of my GSoC student:
https://github.com/NilanjanaLodh/cups_tinker
myLibrary.c contains some functions using the API. listDests uses cupsEnumDests(), once to only show the queues of the local CUPS daemon and another time to show also the remote printers. Shown are the queue names (in the case of the remote printers the names CUPS would use when creating a temporary queue).
listOpts calls one of the functions to show options, depending on the command line arguments. These functions applied to a remote printer make CUPS generating the queue, they all create a list of all destinations via cupsEnumDests() first and then get the dest record for the user-chosen destination via the cupsGetDest(). This way CUPS generates a temporary queue and then is able to return the desired list of options.
The printJob program uses cupsGetNamedDest() as "lp" does and so is also not able to trigger CUPS to create a temporary queue for a remote printer.
So either the command line utilities ("lp", "lpr", ...) need to be modified to use cupsEnumDests() and then cupsGetDest() or the cupsGetNamedDest() function needs to be modified so that it triggers CUPS to create a temporary queue if needed.

**Comment by michaelrsweet** [comment]
The correct solution here is to update cupsGetNamedDest to use cupsEnumDests as needed.

**Comment by michaelrsweet** [comment]
[master 4a3662511] Add support for lp and lpr to print to network printers that haven't been added yet (Issue #5006)

**Comment by tillkamppeter** [comment]
It is working now. Thank you very much.
