### ISSUE TITLE
Temporary queues are created with the printer-is-shared bit set, turning them permanent immediately

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5008]
I have tried out the current GIT state of CUPS to see whether Issue #5003 is actually fixed and observed that the temporary print queue does not go away after some time and not even on shutting down CUPS. After starting CUPS again the queue was still there. I had a look in printers.conf then and seen that the "Shared" field is set to "Yes" for the queue which CUPS has auto-created.
I have printer sharing turned on ("cupsctl" shows "_share_printers=1" in its output. But even then, auto-created queues should get created with the printer-is-shared argument unset to keep them temporary.

**Comment by michaelrsweet** [comment]
[master 42deee7ea] Clear the shared flag on local queues (Issue #5008)
