### ISSUE TITLE
CUPS web UI - creating RSS subscription creates bad name and link

### ISSUE THREAD

**Issue by zdohnal** [apple/cups#5012]
Hi,

I found a bug in CUPS-2.2.0 web UI - when I create RSS subscription, then subscription has bad name (f.e. it has {notify_recipient_name} instead "test") and when I click on link it shows "Not Found" (link is http://localhost:631/{notify_recipient_uri}). But when I manually insert link in format, which is used in CUPS-1.4.2 (in our case http://localhost:631/rss/test.rss), it works. It seems CUPS create correct page, but with bad name and bad link, which makes page inaccessible. I'll look more into it.

**Comment by zdohnal** [comment]
I tracked it down to CUPS-1.5b1 or 1.5b2.

**Comment by zdohnal** [comment]
Hi,
sorry, I found out it is not a bug - it works correctly when I do correct changes to SubscriptionsPrivate* tags. Sorry for inconvenience.

**Comment by michaelrsweet** [comment]
No this

**Comment by michaelrsweet** [comment]
No this actually is a real issue; the privacy values should not prevent the administrative interface from working since you are supposed to login as an admin when you go to the admin page...

**Comment by michaelrsweet** [comment]
and after much discussion we've decided to drop the RSS management from the web interface. You can still create RSS subscriptions, just not through the web interface.

**Comment by michaelrsweet** [comment]
[master b00c84094] Drop RSS subscription management from the web interface (Issue #5012)
