### ISSUE TITLE
CUPS web UI - Can't access administration task depending on password

### ISSUE THREAD

**Issue by YoyPa** [apple/cups#5013]
Hi,

On cups 2.2.3, I can't authenticate if my password contain "§" (https://en.wikipedia.org/wiki/Section_sign).
I get : "pam_authenticate() returned 7 (Authentication failure)" in /var/log/cups/error_log

Step by step : 
    http://localhost:631/admin
        Administration tab
            Click add printer
            Login dialog
                Enter my normal user and password containing a "§"
                Error above in the cups error file

Working as expected after changing user password.

**Comment by michaelrsweet** [comment]
Please see the [https://www.cups.org/faq.html](FAQ page) (this is the number 2 most frequently asked question). The short answer is that Unicode passwords are not supported at this time.

**Comment by jsmeix** [comment]
Only an addedum:
I think the same applies also for usernames.
Simply put:
Use ASCII for identification and autentication values.
