### ISSUE TITLE
ubuntu 16.04 can't get marker-levels

### ISSUE THREAD

**Issue by szhgoldeneye** [apple/cups#5014]
cups version 2.2.3 Hp printer 
i use ipptool get-printer-attributes.test in ubuntu and mac
ubuntu can't get marker-levels but mac can

**Comment by michaelrsweet** [comment]
What HP printer?

What driver?

**Comment by szhgoldeneye** [comment]
printer HP LaserJet Pro MFP M226dn
driver HP LaserJet Pro MFP M225-M226 Postscript

I found that through dnssd connection can get marker-levels, but it doesn't work through socket connection, and my ubuntu's 631 port can't discover the dnssd connection printer.

**Comment by michaelrsweet** [comment]
That sounds like you need to enable Bonjour (Avahi) on your Ubuntu system, then the dnssd backend will start working...

**Comment by szhgoldeneye** [comment]
so through socket connection marker-levels is not available?

**Comment by michaelrsweet** [comment]
Not unless the printer supports the SNMP Printer MIB or the driver does its own in-band queries to the printer over the socket connection.

(this particular printer *should* support SNMP)

**Comment by szhgoldeneye** [comment]
Thanks a lot

**Comment by szhgoldeneye** [comment]
oh... I found that when the driver OK, socket protocol also can get marker-* attributes ,it may not issues about protocol connection
socket+m1225 works fine...
