### ISSUE TITLE
German Documentation file displays incorrect CUPS version

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5019]
Reported to Ubuntu as
https://bugs.launchpad.net/bugs/1695876
Original report:
The /doc/de/index.html.in file in the package source has an incorrect
version number written into a header instead of using '`@CUPS_VERSION@`'
to populate this file as in the other languages' version of the same
file, seemingly resulting in /usr/share/cups/doc-root/de/index.html
having the wrong version once CUPS is installed:

`...
    <div class="body">
      <div class="row">
        <h1>CUPS 2.0.2</h1>
...`

instead of:

`...
    <div class="body">
      <div class="row">
        <h1>CUPS @CUPS_VERSION@</h1>
...`

resulting in 'CUPS 2.0.2' instead of 2.1.3 being shown.

**Comment by michaelrsweet** [comment]
This isn't the case in CUPS master - the German template appears to have been fixed in April of 2016 so it likely was fixed in 2.1.4...
