### ISSUE TITLE
cupsEnumDests() does not enumerate the local printers added during enumeration.

### ISSUE THREAD

**Issue by NilanjanaLodh** [apple/cups#5023]
CUPS version: latest snapshot of this repo.
I am using the cupsEnumDests() function without timeout ( i.e msec= -1 ) 
i.e  `cupsEnumDests(CUPS_DEST_FLAGS_NONE, -1,NULL,  0,  0, print_destination_name, user_data)`

Here `print_destination_name()` is a callback function which prints the destination's name to stdout.

If **while this program is running**, I manually set up a printer ( I did it using system-config-printer) , the newly added printer is not enumerated by the program.

`lpstat -e` does list the newly added printer , however.

If I stop my program and run it again, it lists the added printer; But the issue is that, it's not able to list the printers added **after cupsEnumDests() has been called**.
Maybe I missed something in the CUPS-PM , but it doesn't seem to mention about any such limitation.

**Comment by michaelrsweet** [comment]
Duping this to Issue #5024, which provides the details/reasons for this.
