### ISSUE TITLE
Epson Stylus photo 1390 support needed

### ISSUE THREAD

**Issue by hotxboy** [apple/cups#5026]
I have a Epson Stylus photo 1390 printer and I installed CUPS and cups-driver-gutenprint, but no PPD driver is available for this printer. 
The official Windows (x64 & X86) and Mac OS X driver is attached below.
http://www.epson.cn/resource/Download/Service/driver/Inkjet/SP1390/SP1390_x64_651CN_s.exe
http://www.epson.cn/resource/Download/Service/driver/Inkjet/SP1390/SP1390_W2K_651CN_s.exe
http://www.epson.cn/store/downloads/200987102327.dmg
Not sure how to extract the correct PPD file for this printer. Need help here.

**Comment by michaelrsweet** [comment]
The Mac/Windows drivers won't be of help - you need to use the Gutenprint driver for this printer (if one is available). Best thing is to contact the Gutenprint developers (<http://gutenprint.sf.net/>) to help you find a compatible driver.
