### ISSUE TITLE
cupsEnumDests(): Add printer-is-temporary attribute to the destination options

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5028]
I want to perform an operation only on the permanent queues (the ones manually set up) of the local CUPS daemon, not on temporary queues (the ones CUPS auto-creates when one accesses a driverless remote printer advertised by DNS-SD).
I can call cupsEnumDests() with flags so that only queues of the local CUPS daemon and not remote printers without local CUPS queues are shown), but the queues of the local CUPS daemon which I get listed then are both the permanent queues and temporary queues. Problem is that one cannot distinguish which of these are permanent and which are temporary. There is also no way to call cupsEnumDests() in a way that on gets only permanent or only temporary queues.
Adding a printer-is-temporary attribute to the options of the destination records would easily solve this problem.
See also the thread "cupsEnumDests(): Suppress listing temporary CUPS queues or distinguish temporary queues in resulting queue list" on the cups-devel mailing list.

**Comment by michaelrsweet** [comment]
[master 12b798a07] Report the value of the printer-is-temporary attribute (Issue #5028)
