### ISSUE TITLE
cupsCheckDestSupported() does not work as expected when value = NULL

### ISSUE THREAD

**Issue by NilanjanaLodh** [apple/cups#5031]
CUPS version: latest snapshot of repo
The [CupsPM ](https://github.com/apple/cups/blob/500fca270aaff7cf513662ae4ddb3c71bf32abe5/cups/cupspm.md) states that 

> If the value argument is NULL, the cupsCheckDestSupported function returns whether the option is supported by the destination. Otherwise, the function returns whether the specified value of the option is supported.

However, this is not working as expected for me. For instance, 
`cupsCheckDestSupported(http, dest, dinfo, CUPS_COPIES , NULL)` returns 0;
But 
`cupsCheckDestSupported(http, dest, dinfo, CUPS_COPIES , "1" )` returns 1.

Also,  `cupsFindDestSupported(http, dest, dinfo, "job-creation-attributes")`  lists `"copies"` as one of the values.

Shouldn't `cupsCheckDestSupported(http, dest, dinfo, CUPS_COPIES , NULL)`  have returned `1` according to the CUPS PM ?
Am I missing something in the CUPS Manual?

**Comment by michaelrsweet** [comment]
Will investigate; the API should definitely work as documented.

**Comment by michaelrsweet** [comment]
[master 49b6c6af7] The cupsCheckDestSupported function did not support NULL values (Issue #5031)

**Comment by NilanjanaLodh** [comment]
I pulled the latest changes of the repo; but the problem seems to persist. :disappointed_relieved:

**Comment by michaelrsweet** [comment]
Hmm, that should definitely not be the case. I've pushed a change to the "testdest" unit test program to verify this - after making CUPS the "testdest" program will be found in the "cups" directory, which can then be run with:

    cups/testdest PRINTER-NAME supported copies

this works as expected with one printer I tested with:

    cups/testdest Brother_MFC_J6920DW supported copies
    copies (supported)
      1-9999
