### ISSUE TITLE
Not building RPM with SYSTEMD options 

### ISSUE THREAD

**Issue by kesterriley** [apple/cups#5034]
According to the instructions this switch when building a command says to not use systemd support:

> --without systemd: Build without systemd support

I have used this command to build the RPM:

`rpmbuild -ta cups-2.2.3-source.tar.gz --without libusb1`

So I would assume it should support systemd.

However when installing the built RPM I get this error:

```
error reading information on service cups: No such file or directory
error reading information on service cups: No such file or directory
Redirecting to /bin/systemctl stop  cups.service
Failed to stop cups.service: Unit cups.service not loaded.
Redirecting to /bin/systemctl start  cups.service
Failed to start cups.service: Unit not found.
warning: %post(cups-1:2.2.3-0.x86_64) scriptlet failed, exit status 5
```

On checking the script file for the RPM it suggests it has compiled the RPM without systemd support.

```
# rpm -qp --scripts cups-2.2.3-0.x86_64.rpm
postinstall scriptlet (using /bin/sh):
/sbin/chkconfig --add cups
/sbin/chkconfig cups on

# Restart cupsd if we are upgrading...
if test $1 -gt 1; then
        /sbin/service cups stop
        /sbin/service cups start
fi
preuninstall scriptlet (using /bin/sh):
if test $1 = 0; then
        /sbin/service cups stop
        /sbin/chkconfig --del cups
fi
postuninstall scriptlet (using /bin/sh):
if test $1 -ge 1; then
        /sbin/service cups stop
        /sbin/service cups start
fi
```

I tried a "with" option as well:

 rpmbuild -ta cups-2.2.3-source.tar.gz --without libusb1 --with systemd

But this made no difference.

**Comment by kesterriley** [comment]
I think this is maybe fixed in 2.2.4 - looking at the version history.

Where can I get the latest "cups-2.2.4-source.tar.gz" from?

**Comment by michaelrsweet** [comment]
CUPS 2.2.4 is not yet released, however you can clone the CUPS repository and use the "tools/testrpm" script to build RPMs with various options.

**Comment by kesterriley** [comment]
@michaelrsweet - Michael, do you have any idea when 2.2.4 will be released? I have downloaded the source and can not see a tools folder or a testrpm script.

I am restricted by what I can do, by company firewalls, so can only download the zip files. I am happy to try and help, but not sure I can!

**Comment by michaelrsweet** [comment]
@kesterriley we are getting close to a release. In the meantime you can download a snapshot tarball from the main github repository page <https://github.com/apple/cups> which contains the testrpm script.

**Comment by michaelrsweet** [comment]
OK, well, it is time for a release so I will close this issue for now as fixed; please let me know if you continue to have issues once 2.2.4 is out.

**Comment by kesterriley** [comment]
Thanks @michaelrsweet - as soon as the package is ready for download I will try it!
