### ISSUE TITLE
Missing error_log

### ISSUE THREAD

**Issue by vhradice** [apple/cups#5036]
I am trying to fix a problem I am having with Cups.  Before I can fix the problem another one has shown up.  I go to localhost:631 to get into Cups and check the error log.  I go to Administration and click the View Error Log button and I get a message that the error log cannot be found - a page with only the words "Not Found" on it.  I had looked in /var/log/cups and there was no error_log.  I created an empty one.  I set the owner to root and the permissions to rw.rw.rw. Are these the proper values?
I am running Fedora 25 64 bit kernel 4.10.14.200

**Comment by vhradice** [comment]
Update - Found it.  While looking through the archives at lists.cups.org I found a post that indicated the locations of the log files are in cups-files.conf.  I checked mine and it was set to syslog.  I changed it to /var/log/cups/error_log and then restarted cups.  It was now visible.  Now I can pursue my real problem - cannot print from my laptop to a printer on my desktop.

**Comment by imsedgar** [comment]
Changing the locations of log files in cups-files.conf is the wrong method on Fedora 25. Logs on Fedora 25 go to journald by default. /var/log/cups/ is intentionally empty. Just read the logs by journalctl. For example:
"journalctl -b -u cups" (as root, or with prefix "sudo"). See "man journalctl".

PS: Why do you run such an old kernel with security holes? Current kernel for Fedora 25 is kernel-4.11.6-201.fc25 .

**Comment by vhradice** [comment]
If journalctl -b -u cups is the recommended way to look at the error log, then why doesn't the "View Error Log" button the the Administrator panel at localhost:631 use it?  
I have also updated the kernel.  Thank you for the reminder.
