### ISSUE TITLE
Is this an error?

### ISSUE THREAD

**Issue by vhradice** [apple/cups#5038]
I tried to print a text file from my laptop to the printer on my desktop and nothing happened.  I looked at the error log in cups at the time I tried to print the file.  What I found I have stored in a Google drive as it is quite large.  About 500 lines like this:
D [25/Jun/2017:11:42:53 -0400] [Client 5053] con->http=0x55ec362980c0
D [25/Jun/2017:11:42:53 -0400] [Client 5053] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=520543, response=(nil)(), pipe_pid=0, file=18
What does this mean?  Do I have a setting wrong?  Aside from copying the file to my desktop, what do I have to do to print it?
Thank you in advance for your help.

**Comment by michaelrsweet** [comment]
Those log messages *should* only appear at "debug2" level (with a lowercase d at the start of the line) and just indicate normal IO processing of a request.

Anyways, it would be useful to know what operating system/Linux distro you are using, what version of CUPS you are using, what printer you are using, and what printer driver you are using (if any)?
