### ISSUE TITLE
CUPS web UI - Troubles when using a password with a "²"

### ISSUE THREAD

**Issue by ExarKun64** [apple/cups#5039]
Hy,

I don't know if here is the right place for this, but I have identified a bug.

It seems that CUPS Web Interface cannot handle a password with a ² inside... It then indefinitely ask for a username and a password when you try to access adminstration tools from the Web UI.

Hope this will help improve CUPS!

**Comment by michaelrsweet** [comment]
Please see <https://www.cups.org/faq.html>

This isn't a CUPS issue, but a browser, HTTP, and PAM issue, and not one that has a solution at present...

**Comment by jsmeix** [comment]
@ExarKun64 
only as addedum for the fun of weirdness
you may have a look at "Use non-ASCII characters
in usernames and passwords to lock yourself out" in
https://en.opensuse.org/SDB:Plain_Text_versus_Locale
May the Force be with you!
