### ISSUE TITLE
Typo in the cups programming manual: wrong arguments to ippTagString

### ISSUE THREAD

**Issue by NilanjanaLodh** [apple/cups#5042]
In the section in the CUPS programming manual about [processing IPP responses](https://github.com/apple/cups/blob/master/cups/cupspm.md#processing-the-ipp-response) , the following snippet is provided as an example:

`if ((attr = ippFindAttribute(response, "printer-state",
                             IPP_TAG_ENUM)) != NULL)
{
  printf("printer-state=%s\n",
         ippTagString("printer-state", ippGetInteger(attr, 0)));
}`

However, this doesn't compile.
The function prototype of `ippTagString` is mentioned in the manual as 
`const char *ippTagString (
    ipp_tag_t tag
);`

But the arguments provided to `ippTagString` in the above snippet don't match.

**Comment by michaelrsweet** [comment]
Whoops, that should be "ippEnumString". Will fix.

**Comment by michaelrsweet** [comment]
[master db5424ea5] Fix a typo in the CUPS Programming Manual (Issue #5042)
