### ISSUE TITLE
2.2.4 Rpm Build Fails

### ISSUE THREAD

**Issue by kesterriley** [apple/cups#5043]
@michaelrsweet 

I have tried building an RPM from the latest "cups-2.2.4-source.tar.gz" 

However, I get this error:

```
Checking for unpackaged file(s): /usr/lib/rpm/check-files /root/rpmbuild/BUILDROOT/cups-2.2.4-0.x86_64
error: Installed (but unpackaged) file(s) found:
   /usr/share/locale/zh_CN/cups_zh_CN.po


RPM build errors:
    Installed (but unpackaged) file(s) found:
   /usr/share/locale/zh_CN/cups_zh_CN.po
```

Any chance of having an updated file?!

Thanks

**Comment by michaelrsweet** [comment]
Rats, will need to see why got past my automated build bots...

We won't spin a new release right away for this, but it will be fixed in the next patch release.

**Comment by michaelrsweet** [comment]
I've merged your pull request...

**Comment by kesterriley** [comment]
Great, I compiled this locally and it built the RPM for me.


________________________________
