### ISSUE TITLE
"lpoptions -p ... -l" does not show option list of DNS-SD-discovered printers

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5045]
If I run
`lpoptions -p ... -l`
on a DNS-SD-discovered printer for which CUPS did not yet create a temporary queue (printers listed by `lpstat -e` I get an error message telling that the printer does not exist, but if I print a job the temporary queue gets immediately created and the job printed.
The queue should also get immediately created when applying the "lpoptions" command, so that a command line user can also check available options for such printers.

**Comment by michaelrsweet** [comment]
Will consider...

**Comment by michaelrsweet** [comment]
[master df4101bff] lpoptions now works with discovered but un-added printers (Issue #5045)

[branch-2.2 4fb44b270] lpoptions now works with discovered but un-added printers (Issue #5045)

**Comment by debiantriage** [comment]
On Thu 06 Dec 2018 at 16:25:18 +0000, Michael R Sweet wrote:

> [master df4101bff] lpoptions now works with discovered but un-added printers (Issue #5045)
> 
> [branch-2.2 4fb44b270] lpoptions now works with discovered but un-added printers (Issue #5045)

Much appreciated.

-- 
Brian.
