### ISSUE TITLE
2.2.4 breaks printing from Qt applications

### ISSUE THREAD

**Issue by antonio-rojas** [apple/cups#5046]
With CUPS 2.2.4, no printers show up in the Qt print dialog on Linux. The printers are correctly configured in the CUPS web interface and show up in the GTK print dialog. This regressed in commit 7536de1a4a4ad68d51318a51b4aaa38fad216b74

**Comment by michaelrsweet** [comment]
We need more information - the commit in question just adds bonjour printers to the list that is returned.

Can you point me to the Qt code that is calling cupsGetDests?

**Comment by antonio-rojas** [comment]
https://github.com/qt/qtbase/blob/dev/src/plugins/printsupport/cups/qcupsprintersupport.cpp

**Comment by michaelrsweet** [comment]
Thanks, aside from some inefficiency with getting the default printer (cupsGetNamedDest is better for this) the code looks reasonable and should work. What OS and version of Qt are you using?

**Comment by antonio-rojas** [comment]
Arch Linux, Qt 5.9.1

**Comment by michaelrsweet** [comment]
Hmm, I've looked at the rest of the CUPS print support code and I don't see anything that would cause this behavior. 

What error messages (if any) or core dumps (if any) do you get if you run the application from the command-line?

**Comment by antonio-rojas** [comment]
There are no error messages whatsoever, the printers are simply not detected.
To make sure this is a cups regression, I've added some debug in Qt right after `int count = cupsGetDests(&dests);` and indeed:

with cups 7536de1 count is 0
with cups d2817c9 count is 3

**Comment by antonio-rojas** [comment]
Forget about Qt, this code:
`
#include <iostream>
#include <cups/ppd.h>

using namespace std;

int main() {
    cups_dest_t *dests;
    int count = cupsGetDests(&dests);
    cout << count << endl;
}
`

prints 0 with cups 7536de1 and 3 with cups d2817c9

**Comment by michaelrsweet** [comment]
I definitely can not reproduce that with the unpatched (original) CUPS sources on Ubuntu or Fedora/RHEL.

Are you using an Arch Linux package or version of the sources? Is cupsd running? Does “lpstat-v” list the printers?

**Comment by antonio-rojas** [comment]
Recompiled the package without any patches - same result. cupsd is running, lpstat -v sees all printers.

For reference, this is the Arch build script: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/cups

**Comment by michaelrsweet** [comment]
Well, aside from some questionable systemd changes, the Arch package is surprisingly light on patches...

I don't know what to tell you. GNOME is making the same cupsGetDests call that KDE makes, and you say GNOME apps work. lpstat does the low-level IPP calls that cupsGetDests does as well.

Perhaps let's look at a couple other things:

    lpstat -H
    lpstat -e

Also, maybe grab the CUPS sources and do:

    tar xvzf cups-2.2.4-source.tar.gz
    cd cups-2.2.4
    ./configure --enable-unit-tests
    make check

That will do a full build and automated test suite and give you a unit test program (cups/testcups) that tests the basic CUPS API functionality as well.

**Comment by benkohler** [comment]
I'm also seeing this over on gentoo.  It's affecting my qt apps (qt-5.7.1) but also others like libreoffice.  Firefox is one that seems unaffected.

**Comment by michaelrsweet** [comment]
Do either of you have AppArmor or SELinux enabled on those systems? Any security logging (i.e. preventing applications from using Avahi) going on?

**Comment by benkohler** [comment]
Nothing like that in use here.  I ran the test suite via make check, "All tests were successful."  But cups/testcups returns "cupsGetDests: FAIL"

**Comment by michaelrsweet** [comment]
@benkohler Can you re-run the configure script with the following options:

    ./configure --enable-unit-tests --enable-debug --enable-debug-printfs
    make clean all

and then run the testcups program with:

    CUPS_DEBUG_LOG=testcups.txt CUPS_DEBUG_LEVEL=4 cups/testcups

and attach the resulting "testcups.txt" file?

Thanks!

**Comment by benkohler** [comment]
sure

[testcups.txt](https://github.com/apple/cups/files/1131518/testcups.txt)

**Comment by antonio-rojas** [comment]
Here's mine

[testcups.txt](https://github.com/apple/cups/files/1131784/testcups.txt)

**Comment by michaelrsweet** [comment]
OK, I just pushed a change that adds more debug printfs - I *think* I know what is happening but I want to be sure before I make a change.

Please do a git pull, make, and then re-run the testcups program as above and attach a fresh log... Thanks!

**Comment by antonio-rojas** [comment]
New log

[testcups.txt](https://github.com/apple/cups/files/1131914/testcups.txt)

**Comment by michaelrsweet** [comment]
OK, thanks @antonio-rojas that has cinched it - cupsLastError() is set to an error because there is no default printer (client-error-not-found).

I'm just going to remove the error check there since the dest array will be filled or not based on the ability to get the list of printers and not on the presence of a single error.

**Comment by michaelrsweet** [comment]
[master b2f85109d] The `cupsGetDests` function incorrectly returned an empty list of printers if there was no default printer (Issue #5046)

Please test and confirm this fixes the problem...

**Comment by antonio-rojas** [comment]
Confirmed, thanks!

**Comment by benkohler** [comment]
Yep tested successfully here as well

**Comment by Potomac** [comment]
the patch for fixing "cupsGetDests" works but there is a drawback : the "print dialog box" takes much more time to appear on the screen ( 5 seconds instead of 1 second ) in Qt application,

I use archlinux 64 bits, plasma 5, the archlinux patch is this  : 

https://git.archlinux.org/svntogit/packages.git/tree/trunk/cupsGetDests.diff?h=packages/cups

maybe to much "debug printf" statements, which slows the process ?

**Comment by aschweiz** [comment]
We had the same issue in an application (cupsGetDests returns no results). As a workaround, I've replaced the call to cupsGetDests with cupsEnumDests (all flags 0, timeout -1).
