### ISSUE TITLE
Can not get this post to work! Reinstall USB Fax Modem Capabilities on macOS Sierra 

### ISSUE THREAD

**Issue by GVCCbob** [apple/cups#5047]
https://gist.github.com/essandess/8c0722794562821a24e6cd6fcec3bb8b

**Comment by GVCCbob** [comment]
Has anyone made this work.  Is it doable or not!  I reloaded everything again checked and rechecked and it will not work.  It wants to, but will not dial or send a fax.  CUPS generates a fax printer in Preferences but it will not work.

Comment and help appreciated.

**Comment by michaelrsweet** [comment]
Mac-specific bugs should be filed through bugreport.apple.com. That said, at least some (if not all) of the USB fax modem support is no longer in the kernel...
