### ISSUE TITLE
the new feature "bonjour printers" in cup 2.2.4 triggers lag, long delay when trying to display print dialog box in Qt applications

### ISSUE THREAD

**Issue by Potomac** [apple/cups#5049]
in the release log of cups 2.2.4 there is a new feature : 

"The cupsGetDests and cupsCreateJob functions now support Bonjour printers
(Issue #4993)"

I suspect a bug in this new feature : on Qt application when I click to the menu "File, print" then the print dialog box takes a long time to appear ( 5 seconds ),

If I disable the "avahi-daemon" ( a systemd service in archlinux ) the bug disappears, the print dialog box appears quickly ( less than 1 second )

**Comment by tsujan** [comment]
Confirming the existence of this issue (on Manjaro). When Qt print dialog is called by any Qt5 app, it takes 5-6 seconds for it to appear. This didn't happen before upgrading to cups 2.2.4.

I use the print dialog only to export to PDF.

**Comment by michaelrsweet** [comment]
@tsujan What Linux distro are you using?

**Comment by tsujan** [comment]
> @tsujan What Linux distro are you using?

Manjaro (said above), which is 99% Arch.

**Comment by michaelrsweet** [comment]
Can either of you try the current Github code to see if it exhibits the same symptoms?

**Comment by tsujan** [comment]
I will.

**Comment by tsujan** [comment]
@michaelrsweet 
I'm afraid it made no difference. I compiled and installed the latest git source and then rebooted but there's still a 5-second delay.

**Comment by michaelrsweet** [comment]
@tsujan If you have the source handy can you make the "testcups" unit test program and time it on your system?

    cd cups
    make testcups
    time ./testcups

On my Ubuntu VM it takes just over a second (1.015s) to complete, which it what I would expect with the default 1 second browse timeout.

**Comment by tsujan** [comment]
@michaelrsweet 

The result:
````
real    0m1.010s
user    0m0.003s
sys     0m0.000s
````

**Comment by michaelrsweet** [comment]
Strange, something in the Qt stack must be calling cupsGetDests 5 times then. I will investigate providing a cups_dest_t cache that is returned if subsequent calls come in within a certain timeframe (say, 10 seconds).

**Comment by tsujan** [comment]
As @Potomac mentioned, this didn't happen before 2.2.4. That might help in finding the cause.

**Comment by michaelrsweet** [comment]
@tsujan Before 2.2.4 cupsGetDests didn't look for Bonjour printers so we didn't have the same kinds of networking delays (usually all local domain socket traffic).

**Comment by peturbg** [comment]
this is not only the lag it is ssl insecure ciphers, here you can see the ciphers it used. how i can change for my client his ciphers. here i explain other big issue with servertokens none and this is false it show all information. I just can't know why you can't modified cups like apache2, but yes i just answer on my question, cups works for apple and we all know that apple is closed and not transparency of they source code, but remember apple is made from unix and linux, if you don't know, open terminal in apple,macbook,imac and apple produtcts and write: ls, ls is linux nad unix command this will show you what has in this directory, rm is unix and linux command to delete... do i need to continue... windows and linux are different, so in windows you can't write ls becouse in windows command don't exist this mean, windows is private closed source and they can not to share the source of the programs, but apple is propietary of unix and linux and they need to be transparency, if not jail all who works for apple, this is crime who robbery car with other person and second person after that say no, she was complicity of crime, so apple is commiting crime, apple use free source code but don't show they propietary when they create something, include this is slavery you works for someone and she use it. knowing the law don't make apple skip the law, the law is above all the human, apple is make in apple works peoples so they are obeyed to comply with the law, nobody have the rights to dissobey. now i understand why cups is so limited in options, this is good becouse now i can explain in my youtube video tutorials this times for cups.  hey hackers cups use apache 1 version and insecure ciphers, but apple don't use it, apple will never use apache 1 version and less secure. now i understand why my client give tls error.

**Comment by tsujan** [comment]
@peturbg
I'm not a CUPS developer but should say that your comment wasn't helpful AT ALL!

**Comment by peturbg** [comment]
tsujan you are not helpful AT ALL! but you live.

**Comment by Potomac** [comment]
@michaelrsweet  : maybe there is recently a change in avahi API ?
or in Qt ?

I use archlinux, which is a rolling release linux distro like manjaro ( all packages are up-to-date, last release version), and if there is a bug you can be sure that archlinux users will be the first to see the bug, 

I don't know if you use a rolling release distro, but using a rolling release distro is the best way to check that every feature in cups run as expected, if you use a non-release distro ( like ubuntu LTS, debian stable ) then there is a risk that some bugs will be hidden from you if some packages ( Qt, avahi ) are too old on your system

**Comment by tsujan** [comment]
I completely agree with @Potomac and wanted to suggest the same thing.

**Comment by tsujan** [comment]
I just checked with Qt4 print dialog and saw a 1-sec delay. IMHO, even a 1-sec delay is a problem and generally, using fixed delays to do something in the code isn't a good option.

**Comment by michaelrsweet** [comment]
@tsujan I agree completely, and there wouldn't be a delay if the Qt folks would simply adopt the cupsEnumDests API which has been part of CUPS since CUPS 1.6 (first released ~6 years ago...)

**Comment by michaelrsweet** [comment]
OK, dropped the maximum delay to 250ms, please let me know how that works for you.

**Comment by tsujan** [comment]
I confirm that https://github.com/apple/cups/commit/e3b9d1f5205449216211c8e4072b7ea89ebc5f24 reduces the delay to ~1 second, which is quite tolerable. So, this can be closed.

Please think about removing all fixed delays at some point! Thank you very much!

**Comment by tsujan** [comment]
And if any bug should be reported to Qt developers, you could do it better than anyone.

**Comment by michaelrsweet** [comment]
Bugs have been reported to the Qt devs, and they've even had GSoC volunteers, but no mentors... :/

**Comment by tsujan** [comment]
> Bugs have been reported to the Qt devs, and they've even had GSoC volunteers, but no mentors... :/

Will vote up or leave a comment if I find it/them.
