### ISSUE TITLE
libtool support is currently broken

### ISSUE THREAD

**Issue by rohieb** [apple/cups#5050]
Hi,
I (accidentally) tried to compile with `--enable-libtool-unsupported`, but there were two issues:

First, `./configure --enable-libtool-unsupported` leads to `@LIBTOOL@` being replaces with `yes` – this makes the build very verbose and leads to no file being built at all, only a lot of console output (34 GB in my case, before SIGKILL). The documentation does not mention that `--enable-libtool-unsupported` actually takes the path to the libtool binary as a parameter.

Second, `Makedefs` uses libtool by setting `CC = libtool gcc` (or similar). Newer libtool versions (2.4.6 in my case) don't support that call anymore, and need an additional `--mode=compile` to work.

Both issues would be easy to fix, and I would be willing to send patches if those are welcome. On the other hand, I see that libtool support in CUPS is officially unsupported (in big letters) and issues relating to it are closed with WONTFIX. So I think whether a better solution would be to remove libtool support completely so users don't get confused about it.

**Comment by michaelrsweet** [comment]
OK, I think I've fixed things up for this...

[master a621d151e] Update libtool support to include --mode=foo stuff - surprise, libtool changed in incompatible ways again...  (Issue #5050)
