### ISSUE TITLE
SATO WS4 doesn't print in USB interface (Windows is okay)

### ISSUE THREAD

**Issue by gqbgqb** [apple/cups#5052]
Hi,

We are facing issues printing using USB connection in Ubuntu with our SATO WS408 printer (SBPL and SZPL mode). we also test out Zebra drivers but still has the same issues. We have verified the print data being sent is correct. I just can't confirm if it's a hardware issue or Cups but I can confirm our driver and LAN works. I hope you can help me point on how to debug or find solutions.

OS:  Ubuntu 16.04 LTS - 32 bit
Logs: [Flipkart error_log.txt](https://github.com/apple/cups/files/1134255/Flipkart.error_log.txt)

1. With WS408 (USB) SATO CUPS driver settings, using lpr -o, lp -l commands are not still working.
2. Connecting WS408 (USB) with Generic Text Only using lpr -o, lp -l commands are not still working.
3. Connecting WS408 SZPL with LAN using Generic Text Only Driver the print out is coming.
4. Connecting WS408 using USB with Zebra Driver (used to do for SA408) also not working. 

Please let me know if you need more information. Thanks in advance.

**Comment by michaelrsweet** [comment]
More than likely this is a bug in the printer's USB support. Please provide the output of "lsusb -v".

**Comment by gqbgqb** [comment]
Hi michaelrsweet, You are right. After investigating thoroughly, we found out that its the printer firmware issue which cause the disconnection.  I was about closing this issue but you beat me. Thank you for your support.
