### ISSUE TITLE
how to create printer queue

### ISSUE THREAD

**Issue by vilianfung** [apple/cups#5055]
HI,I want to create printer queue ,but it seems no api available for that.according to the docs,it says cupsAddDest and cupsRemoveDest will not add or remove printer/class queue,If so,How do I do that?

**Comment by michaelrsweet** [comment]
The "CUPS Implementation of IPP" documentation provides the details of the IPP operations that CUPS implements for creating print queues.  In general, if the printer supports IPP then you don't need to create a queue manually anymore, a CUPS-Create-Local-Printer request will be used automatically for a network printer as needed when using the CUPS API to send print jobs. For a manually created queue use a CUPS-Add-Modify-Printer request (which allows you to specify the driver/PPD...)

The CUPS Programming Manual provides some examples of sending IPP requests...
