### ISSUE TITLE
How to get localized attributes using IPP Apis

### ISSUE THREAD

**Issue by SUGE2016** [apple/cups#5056]
we want to get localized printer attributes, but failed:
```
ipp_t *req = ippNewRequest(IPP_GET_PRINTER_ATTRIBUTES);
ippAddString(req, IPP_TAG_OPERATION, IPP_TAG_LANGUAGE,
             "attributes-natural-language",
             nullptr,
             "zh");
...
```

use ipptool launch get-printer-attributes.test, change **attributes-natural-language** to **zh** can get english attributes only.

Is there a way to resolve this? @michaelrsweet, and thanks

**Comment by SUGE2016** [comment]
found that *cgi-bin/admin.c* read PPD file get localized attributes, but PPD API is deprecated, how then ?

**Comment by michaelrsweet** [comment]
@SUGE2016 The proper way to localize attributes and values is through a printer's "strings" files (referenced by the "printer-strings-uri" attribute returned by the printer). There are a number of CUPS APIs specifically for doing this - see the new CUPS Programming Manual for details.

**Comment by SUGE2016** [comment]
@michaelrsweet is any way set the locale for these ** cupsLocalizeDest* ** apis? not accroding to only locale setting of local machine. 
request to switch language setting in application.
thanks.

**Comment by michaelrsweet** [comment]
We use the currently set locale, so you can use setlocale() for that. But if you need to grab arbitrary locales you'll want to grab the strings files directly.

**Comment by SUGE2016** [comment]
can not get localized option value, 
```
setlocale(LC_ALL, "zh_CN");
http_t *http = cupsConnectDest(dest, CUPS_DEST_FLAGS_NONE, 30000, NULL, NULL, 0, NULL, NULL);
cups_dinfo_t *dinfo = cupsCopyDestInfo(http, dest);
const char* copies = cupsLocalizeDestOption(CUPS_HTTP_DEFAULT, dest, dinfo, CUPS_COPIES);
cout << "copies: " << copies << "\n";
```
english **copies** printed

We compiled testdest.c, but there is no chinese (zh_CN) localization,
```
./testdest 226 localize copies
copies (copies)
  1-9999
``` 

is attribute ``printer-strings-uri`` always exists for any printer? there must be something wrong ... we have not any more ideas to trying, any auggestions ? @michaelrsweet 

thanks

**Comment by michaelrsweet** [comment]
You need to use CUPS_DEST_FLAGS_DEVICE with cupsConnectDest to make sure you connect to the printer and not the local queue; this was introduced in CUPS 2.2.4 so you'll probably want the following conditional code:

    #ifndef CUPS_DEST_FLAGS_DEVICE
    #  define CUPS_DEST_FLAGS_DEVICE CUPS_DEST_FLAGS_NONE
    #endif /* !CUPS_DEST_FLAGS_DEVICE */

(prior to 2.2.4 it was undefined which host you'd connect to...)

That said, it looks like we are not providing backup localizations for the standard attributes and values; will use this bug to track the addition of those strings (although standard options normally don't depend on CUPS or the printer for localization - all queues support copies, duplex (sides) is standardized, etc.

**Comment by michaelrsweet** [comment]
[master a9357c9da] Implement standard localizations in cupsLocalizeDest* (Issue #5056)

**Comment by SUGE2016** [comment]
Wow, thank you, and for the quick fix.
