### ISSUE TITLE
cups for linux servers that support all in one. printer + scanners + fax

### ISSUE THREAD

**Issue by peturbg** [apple/cups#5059]
Hi again guys.

I like to see cups feature that has 100 % printer + scanners + fax, imagine, you wake up one morning and open https://yourdomain.com:631 and you see you have fax, or you need to send photo image from printer scanner to the governments complaint for all inhumans. 

best regards

**Comment by michaelrsweet** [comment]
CUPS supports outgoing print and fax queues. Scanning depends on different software (SANE on Linux, ICA on macOS), and incoming fax yet again something different (several solutions). Most MFPs do not support incoming fax via computer, and many don't even support outgoing fax via computer. That combined with the slow death of fax has caused us to basically give up on standardizing fax with CUPS.

There is some interest in implementing an IPP Scan solution using SANE, but that is happening in the PWG's ippsample project, not as part of CUPS.
