### ISSUE TITLE
on ubuntu 17.04 lppasswd command not found

### ISSUE THREAD

**Issue by peturbg** [apple/cups#5060]
on ubuntu 17.04 lppasswd command not found
ls -la /usr/bin/dontextst
in ubuntu default directory is:
/usr/bin/lppasswd

now someone want like windows, becouse in windows you can copy one file and paste it in another computer and it will work. In linux it is not possible. now from where i can get lppasswd 
apt-get install cups-client
cups-client is already installed at the requested version (2.2.1-8)
so how i say before in /etc/cups and i don't have client.conf and now i don't have lppasswd and i have obsolete version of cups 2.2.1 maybe i start like windows, becouse you can paste one file to another computer, you can update the new version without to know compile knowledge, in windows when you install program it install 100 % complety with all programs and commands. So for 1 day i open 2 issues and 1 request it is only for one linux program. If i start use like developer do you imagine how much program i will find they missing commands.

**Comment by michaelrsweet** [comment]
@peturbg The lppasswd command and support for Digest authentication was dropped in CUPS 2.0 due to numerous security and interop issues. The recommended replacement is to use PAM with HTTP Basic authentication over TLS encrypted connections.
