### ISSUE TITLE
ubuntu 17.04 Unknown browse protocol "CUPS" ignored.

### ISSUE THREAD

**Issue by peturbg** [apple/cups#5061]
hi again guys.
i don't have client.conf so i need to put somewhere to tell of cups /etc/cups/cupsd.conf and when i put this commands: 
AuthType Digest
BrowseLocalProtocols cupsd dnssd
include i try with BrowseLocalProtocols CUPSD dnssd
E [14/Jul/2017:21:07:42 +0200] Unknown browse protocol "CUPS" ignored.
W [14/Jul/2017:21:59:57 +0200] Unknown default authorization type Digest on line 9 of /etc/cups/cupsd.conf.
E [14/Jul/2017:22:00:25 +0200] Unknown directive AuthType on line 9 of /etc/cups/cupsd.conf.

**Comment by imsedgar** [comment]
This is not an error. Cups doesn't support protocol "CUPS" since a long time. See "man cupsd.conf" (if this exists on Ubuntu).

cups protocol for linux is supported by cups-browsed. You may check if a package with a name like this is available on Ubuntu. Then you can configure it in /etc/cups/cups-browsed.conf, and you need to start service cups-browsed. (I don't use Ubuntu. This works on Fedora.)

You don't need a client.conf file if you don't need (or want) to change the defaults.

And please: Read the man pages (check "man -k cups" for a list) and the manuals before asking open an issue about questions that are answered there.

**Comment by peturbg** [comment]
imsedgar if you don't use ubuntu this is your problem and second imsedgar you are aggresive person third, there is human on this planet earth that use ubuntu 17.04, and this cups is becouse i find all forums that i find they comment cups and they use ubuntu. Now if cups protocol don't work in ubuntu how for other peopels work and another i read that autentication digest too exist and when i change it to digest cups comment it don't exist, so for other peoples exist, include i read https://linux.die.net/man/5/cupsd.conf this is one of the web pages " see the letters pages " that i read and try lost all 1 days to configure cups. They comment autentication digest exist. Now i think to start youtube canal and what im gonna speak for linux will be the truth, that linux in general is obsolete, include i will post web pages, new pages that they comment digest exist, i will speak about compile that not all peoples are developers and they can't compile and if i have time i will speak other things. If linux was normal documented this will not happend to configure 1 all day cups and in finall to comment me ssl error. And other imsedgar i didn't say error imsedgar you are very aggresive person and you need to relax becouse you are damaging others humankind, if you have problems that is your problems. and i don't care if you use mac, or linux or other shit operation system. this don't mean if you don't use it it the other peoples too are prohibited to use it. i'm human and will do what i want. As for the client.conf in cups official webpage they don't comment if exist or not, so they comment go to /etc/cups an there you will see client.conf LIE when i go /etc/cups/ there is no client.conf So developers need to tell client.conf don't exist in ubuntu. And i don't want cups-browsed i give client support, give them help server support and yes my cleints are pissed becouse linux os obsolete.

**Comment by peturbg** [comment]
imsedgar and i'm gonna put all errors and all that don't work be cups or every linux program. I help my client with windows server and they are most happy peoples, include less problems than linux. Now i'm gonna put all errors becouse there are errors who are from 3 years and in version 2.2.1 and maybe in 2.2.4 are not repaired i too tell this on ubuntu and debian, compare debian with ubuntu, debian is the worse obsolete operation linux system. I had client and told him all the problems, obsolete versions and etc. and he change it with windows server, include the pirate server programs are working, compare pirate server programs and linux free compile programs, is that compile it can take 2 hours to compile 10 mb and in windows 10 mb. windows server with 32 gb. ram, minimum video card 10 mb are installed for less 2 minute. Do you want lost human time simply to compile 10 mb. for 1 hour, include think when you need to compile 100 mb. pfuuu, i can't remember when i compile one simply program and had to seek in internet for manuals and after some times i start compile i don't remember the name of the program but it was more than 100 mb. and time was more than 2 hours, for simply after  that the program don't work. Im gonna make a video with this post too.

**Comment by michaelrsweet** [comment]
@peturbg HTTP digest authentication support was dropped in CUPS 2.0 - aside from the fact that CUPS never implemented the most recent HTTP Digest spec (which is incompatible with the original Digest and not widely supported by browsers), the lppasswd program was a constant source of security vulnerabilities and MD5 is not all that secure. PAM + HTTP Basic authentication over TLS is far more flexible and secure.

CUPS browsing was dropped in CUPS 1.6 (deprecated in 1.4) as it wasn't (and still isn't) compatible/performant with modern networks or with large numbers of servers and printers.
