### ISSUE TITLE
CUPS 2.2.0 Reinstall USB Fax Modem Capabilities on macOS Sierra

### ISSUE THREAD

**Issue by GVCCbob** [apple/cups#5064]
The owner of this link claims that this is doable.
https://gist.github.com/essandess/8c0722794562821a24e6cd6fcec3bb8b#file-macos-sierra-usb-fax-modem-reinstallation-md

Essandess claims is was able to create a workable fax printer.

I am close to making this work.
I can get the FaxPrinter and Fax to display and to get into the clue.
However, I can not get it to dial the modem to send the fax.

Please look at the screen shots.

Can someone help me finish this project.

However, CUPS does not find Local Printer USB Modem to add or modify printer so I had to create a connection at:
fax://dev/cu.usbmodem2468024

How do I get CUPS to see this local printer connection?

Do I need to replace Sierra /usr/libexec/cups with either Maverick, or El Capitan  /usr/libexec/cups.

[Modify Printer.pdf](https://github.com/apple/cups/files/1153401/Modify.Printer.pdf)

However, modem can be pinged with modem application.

https://gist.github.com/essandess/8c0722794562821a24e6cd6fcec3bb8b#file-macos-sierra-usb-fax-modem-reinstallation-md

![fax print screen shot 2017-07-17 at 9 13 40 am](https://user-images.githubusercontent.com/29715402/28279630-eb5b1048-6ad5-11e7-9335-a4e5476e4a4f.png)

![cups 2 2 0 2017-07-17 at 9 15 52 am](https://user-images.githubusercontent.com/29715402/28279669-07ef9c74-6ad6-11e7-8b42-da442d443d89.png)

![faxprint screen shot 2017-07-17 at 9 14 40 am](https://user-images.githubusercontent.com/29715402/28279755-5ef8b280-6ad6-11e7-8bb3-8228d50b8a95.png)

![screen shot 2017-07-17 at 9 15 46 am](https://user-images.githubusercontent.com/29715402/28279784-73dbdd12-6ad6-11e7-9657-7327caebdeb3.png)

[Modify Printer.pdf](https://github.com/apple/cups/files/1153385/Modify.Printer.pdf)

**Comment by michaelrsweet** [comment]
Sorry, but we do not support fax modems anymore.
