### ISSUE TITLE
"ServerTokens None" does not disable Server header in responses

### ISSUE THREAD

**Issue by peturbg** [apple/cups#5065]
Hi guys.

now i received this error: kernel: [ 7273.363575] TCP: request_sock_TCP: Possible SYN flooding on port 631. Sending cookies.  Check SNMP counters.

Not accepting cups answer. And this confirm all concerns:

in /etc/cups/cupsd.conf

ServerTokens None

Now i put on my client ServerTokens none this mean that cups will not show version, but this is false:
DNS resolves mydomain.com to 8.8.8.8

HTTP Server Header: CUPS/2.2.4

Remember server tokens is none, so why it display cups 2.2.4
And this is for cry and is big issue:
this cyphers are insecure, less secure, easy hackable, man in the middle and etc. This crypters are comming default from cups 2.2.4
Second big issue:
SSL ciphers supported by the server

TLS_RSA_WITH_CAMELLIA_256_CBC_SHA256
TLS_RSA_WITH_CAMELLIA_128_CBC_SHA256
TLS_RSA_WITH_AES_256_GCM_SHA384
TLS_RSA_WITH_AES_128_GCM_SHA256
TLS_RSA_WITH_CAMELLIA_256_CBC_SHA
TLS_RSA_WITH_CAMELLIA_128_CBC_SHA
TLS_RSA_WITH_AES_256_CBC_SHA256
TLS_RSA_WITH_AES_128_CBC_SHA256
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_3DES_EDE_CBC_SHA

Now how i can put my line ciphers.

Big issue:

SSL Certificate is not trusted

The certificate is not signed by a trusted authority (checking against Mozilla's root store). If you bought the certificate from a trusted authority, you probably just need to install one or more Intermediate certificates. Contact your certificate provider for assistance doing this for your server platform.

Client certificate are paid so in client shop webpage his certificate works great and only fail in cups 2.2.4
this fail becouse cups don't have options to put itermidate sertificate and in apache there is option.

Low issue, but recommended:

OCSP Staple: | Not Enabled
-- | --
OCSP Origin: | Not Enabled
CRL Status: | Not Enabled

ocsp staple: this is reccomended to be enabled.
and crl status too.

Now i want to ask developers of cups, so you put option ServerTokens None but it don't work, why then you put this option, why there is no option to put peoples ciphers, do cups leaks peoples data. So cups works for apple, then why don't apple use this less ciphers, that come by default in cups 2.2.4 i don't care if they use TLS this ciphers that cups use are insecure

And lastly, why cups 2.2.4 don't use http2 the new version of http, it is more secure, more fast, include has push features. Message to all developers we leave in 21 century, we don't live in ice age.

**Comment by michaelrsweet** [comment]
OK, lots of issues in one bug report, but let me see if I can respond:

1. "ServerTokens None" regression; this turns out to have originated in CUPS 1.7 when we refactored the server-side response generation into libcups, which uses a default Server header when none is configured for the connection. Will fix.

2. Add "SSLOptions DenyCBC" to your cupsd.conf file. The default is to allow CBC cipher suites because a lot of existing clients (100s of millions of them) do not support the corresponding GCM cipher suites. This sucks, but hopefully we can change the default in another year or so. Unfortunately, cipher suite selection is VERY different with the different TLS libraries we support, so the SSLOptions method is our compromise for disabling/enabling groups of them...

3. Support for linking intermediate certs varies WIDELY between TLS libraries; the solution on systems using GNU TLS (basically everybody but macOS and Windows, who do their own thing) is to concatenate the certificate with the intermediate(s), e.g.:

    cat mycert.crt cacert.crt >cupscert.crt

   (This method isn't exclusive to CUPS and is how you used to have to do things with Apache, BTW...)

4. OCSP staple/origin: We can look into implementing this in the future, however I don't know whether any of the TLS libraries we use expose the functionality in a way we can use it. CRL support should be automatic once you concatenate your cert with the CA's intermediate cert.

5. HTTP/2 is NOT a replacement for HTTP/1.1. I participated in its definition, and even included it as an experimental transport for IPP/1.1 when I did the updates to those RFCs, but there are a) no complete prototypes of IPP using HTTP/2 and b) no printers in existence that support HTTP/2. HTTP/2 is NOT more secure, NOT faster than HTTP/1.1 for IPP usage (I've prototyped that much), and HTTP/2 push is useless for IPP and unnecessary for the CUPS web interface. HTTP/2 is also a LOT harder to debug, requires significantly greater resources than HTTP/1.1, and is complete overkill when most communications happen over a single, persistent connection (as happens with IPP). Newer doesn't always mean better, and if something isn't broken why "fix" it?

Anyways, it looks like the only bug that needs to be fixed in the short term is to fix "ServerTokens None" so that it does the right thing. I'm changing the title to reflect this...

**Comment by peturbg** [comment]
hi michaelrsweet
lets see what bother is 

section 2: but hopefully we can change the default in another year or so.
So fixing a security holes get you another year or so.  michaelrsweet so you buy a computer and they put you insecure cipher and you tell them, change my security ciphers, so they comment you this sucks but hopefully we can change the default in another year or so, or maybe we can leave them " indirectly your comment mean, we will not change them " michaelrsweet comment me, michaelrsweet you have mother and father, brother or sister, so michaelrsweet are you recommend this that you comment on me. michaelrsweet No i'm sure you will not recommend them this, michaelrsweet include for your mother, for your father, for your sister, for your brother you will get secure ciphers but you will SUCK the other peoples with the SHIT insecure ciphers. michaelrsweet i understand you do you know why, becouse i had worked in the most SHIT company IBM and HP " hewlet packard " and barcelona and i can't tell you how much big and popular is the company MORE INHUMAN, CRUEL, and all bad the humans know is, so cups is from apple and we all know that shit is apple, much SHIT is from IBM and HP " hewlet packard " now i remember to add other video about cups and about that secure is not BIG issue. michaelrsweet tell on apple to use cups ciphers and let see how much days apple will stay until someone breach they servers and how we say what it will be called CRIME. but why crime, when they use insecure ciphers.

So lets move to section 3: Support for linking intermediate certs varies WIDELY between TLS libraries;
michaelrsweet you are developer or you are name yourself developer. So cups is maked insecure, cups is like apple not to be modified. Now apache and apache2 is free and is totaly 100 % modified, you can add private certs and public certs, now you open web page and there is problem, hmmm so you go to apache and apache2 and put intermediate certs, when you restart apache and apache2, you again open web page and now it have ssl, tls. So it is working. Now case in cups, you open https://localhost:631/ it give green bar, but this is lie, when you see in log it comment tls error connection is insecure, but how it is insecure when in browser it give green bar. So where peoples can know how to put intermediate ceritificate like apache and apache2 when cups is not 100 % free, transparency, in the moment day 23, month Jul, year 2017 cups version 2.2.4 for ubuntu is closed, it is not transparency, is limited in everything. cups is like apple in the moment SHIT. michaelrsweet do you prefer to make good food or michaelrsweet do you want to make bad food, michaelrsweet are you gonna eat bad food. michaelrsweet i know and everybody know you michaelrsweet will not eat bad food. michaelrsweet if i had a email of ceo i'm gonna tell him the true and belive me, it will not be good, first becouse apple use low performance and other truth, but this is for ceo. michaelrsweet i read what you comment
now cat mycert.crt cacert.crt >cupscert.crt this command don't exist in manual. So in human language this commands are off from manual. Now if someone has a problem the first he will go to manual and lost his life in seeking how to encancenate this three certificate becouse cups developers works for apple and apple IS TOTALY SHIT.
michaelrsweet in the moment i don't have work, so speak with apple ceo to hire me to documentate the documentation and tell him the true THAT I SAY apple IS SHIT.
michaelrsweet other is if someone want to change name certificate in cups he can't do it, he need to use the defaults, michaelrsweet  do you know what unix and linux stand for FREE OPERATION SYSTEM change to work for me. michaelrsweet lets return to the main section 3, michaelrsweet linux is the same from where you see it, now if ubuntu is different from slack that is they problem, becouse linus torvall make linux to be same in all views, be black or be white. But we all know when someone in 21 century give money all can be do. michaelrsweet  i read time ago that gnu tls has a problem and too is insecure, it is recommended openssl, so michaelrsweet  you try to redirect the problem to gnu tls when the problem directly is in cups. michaelrsweet tell of SHIT apple to make cups 100 % free, modified, transparency, humankind understandable and you will see cups will not have problems. include cups homepage is broken, if person wants manual webpage of cups comments him to come here, but homepage has 2.2.4 versions this mean this is indirect LAUGHTING peoples, it is making them like clown.
I just see that " (This method isn't exclusive to CUPS and is how you used to have to do things with Apache, BTW...) " A no, michaelrsweet so when i first install cups i didn't read manual i just write apt-get install cups and it install cups, i go to https://localhost:631 and it show insecure connection, hmmm strange becouse ssl, tls certificate is buy so it it trusted, when i start see cupsd.conf very bad.... i read comments or maybe you comment cupsd menu is like apache and apache2, what you read in apache and apache2 this is the same in cupsd, THIS IS FALSE. Now if i write in cupsd.conf this SSLCertificateKeyFile and restart /etc/init.d/cups restart it will comment something like that it don't exist... so lets see another, maybe SSLCertificateKeyFile don't exist becouse developers works for apple and we all know apple are SHIT. lets see second command:  in apache and apache2 there is SSLCipherSuite now i write in /etc/cups/cupsd.conf and i write SSLCipherSuite  then i restart /etc/init.d/cups restart and maybe it will give it don't exist. So no it is not developer error it is just becouse cups is not the apache and apache2 like. cups and apache and apache2 are two 100 % differenty, the only different cups use some version of apache first generation, but peoples can't see what version use cups becouse apple is blocked in they heads and in all they body.
michaelrsweet in section 5: you try lie: HTTP/2 is NOT a replacement for HTTP/1.1.
The true is that wikipedia comment https://en.wikipedia.org/wiki/HTTP/2 HTTP/2 (originally named HTTP/2.0) is a major revision of the HTTP network protocol used by the World Wide Web. michaelrsweet  mayor mean replacement. michaelrsweet number 2 replace in all cases number 1. michaelrsweet  you too confirm http2 replace http 1.1 HTTP/2 replacement for HTTP/1.1. michaelrsweet you are developer so you can see where is the difference. michaelrsweet   i don't care if you participated in defition and etc.  michaelrsweet the diploma is not important, you can drive porsche but it is metal and when you drive with more than 220 km/h. if you crush " krush " do you imagine if this car is gonna safe your life, i'm gonna tell you first porsche iS SHIT, and second you can try your seeing.

michaelrsweet do you really want to develope a program that really help humankind then make it like you make this program for your father, your mother, your sister and your brother. michaelrsweet you work for apple so speak with ceo and tell him apple is SHIT and tell him if they really want documentation i can write documentation and tell him apple need to be 100 % transparency becouse i don't work with corrupted company. now im gonna prepare the second video for youtube and im gonna paste this message in my video becouse there are more peoples who will complaint against apple. michaelrsweet thanks for the program and have nick day.

**Comment by peturbg** [comment]
michaelrsweet i just found that i tell you before for cups problem and you michaelrsweet  comment me this: 
 The Ubuntu and Debian developers are responsible for packaging CUPS on those distributions - the Ubuntu version of CUPS (like any other Linux distribution) contains many patches necessary for that distribution, so if we tried to provide our own packages we'd probably just mess things up even more.

michaelrsweet cups is maked from you and from apple. So peoples themself imagine distros get your source or deb change something or nothing and put it normal peoples download it. In generaly michaelrsweet you are LIER and michaelrsweet you are untrusted person. 

E [14/Jul/2017:14:34:54 +0200] [Client 13] Unable to encrypt connection: Error in the pull function.
E [14/Jul/2017:14:34:54 +0200] [Client 15] Unable to encrypt connection: A TLS fatal alert has been received.
E [14/Jul/2017:14:35:05 +0200] [Client 21] Unable to encrypt connection: Error in the pull function.
E [14/Jul/2017:14:35:05 +0200] [Client 22] Unable to encrypt connection: A TLS fatal alert has been received.
E [14/Jul/2017:14:35:05 +0200] [Client 26] Unable to encrypt connection: A TLS fatal alert has been received.
E [14/Jul/2017:14:35:15 +0200] [Client 27] Unable to encrypt connection: Error in the pull function.
E [14/Jul/2017:14:35:15 +0200] [cups-deviced] PID 25939 (gutenprint52+usb) stopped with status 1!
E [14/Jul/2017:14:35:29 +0200] [Client 31] Unable to encrypt connection: Error in the pull function.
E [14/Jul/2017:14:35:30 +0200] [Client 32] Unable to encrypt connection: A TLS fatal alert has been received.
E [14/Jul/2017:14:35:41 +0200] [Client 33] Unable to encrypt connection: A TLS fatal alert has been received.
E [14/Jul/2017:14:35:51 +0200] [Client 34] Unable to encrypt connection: Error in the pull function.
E [14/Jul/2017:14:35:52 +0200] [Client 35] Unable to encrypt connection: A TLS fatal alert has been received.
E [14/Jul/2017:14:36:02 +0200] [Client 42] Unable to encrypt connection: Error in the pull function.
E [14/Jul/2017:14:36:02 +0200] [Client 43] Unable to encrypt connection: A TLS fatal alert has been received.
E [14/Jul/2017:14:36:12 +0200] [Client 44] Unable to encrypt connection: Error in the pull function.
W [14/Jul/2017:14:37:02 +0200] Unknown SSL option DenyTLS1.0 at line 11.
W [14/Jul/2017:14:37:43 +0200] Unknown SSL option [DenyTLS1.0] at line 11.
W [14/Jul/2017:14:37:52 +0200] Unknown SSL option [DenyTLS1.0] at line 11.
W [14/Jul/2017:14:37:54 +0200] Unknown SSL option [DenyTLS1.0] at line 11.
W [14/Jul/2017:14:38:46 +0200] Unknown SSL option AllowDH at line 11.
W [14/Jul/2017:14:39:14 +0200] Unknown SSL option DenyTLS1.0 at line 6.

michaelrsweet this is what you comment from section 3:
Support for linking intermediate certs varies WIDELY between TLS libraries; the solution on systems using GNU TLS (basically everybody but macOS and Windows, who do their own thing) is to concatenate the certificate with the intermediate(s), e.g.:

cat mycert.crt cacert.crt >cupscert.crt

(This method isn't exclusive to CUPS and is how you used to have to do things with Apache, BTW...)

michaelrsweet now do you understand THAT PEOPLES NEED OPTIONS TO PUT intermediate option in cups. michaelrsweet in homepage cups the latest version don't work, so how someone will know the command to write in /etc/cups/cupsd.conf to acivate intermediate certificate. cups is not apache and apache2 so he will have hole in his cups server and when he print everybody will know what he print. michaelrsweet so you use cups and you print to your printer this night will have sex will walking woman, road woman, now when it goes to printer everybody will know you will have sex with walking woman, road woman. crucial documentation is important and in every new release.

**Comment by michaelrsweet** [comment]
@peturbg we will not be bullied into negatively affecting hundreds of millions of users for the sake of something that is not a practical issue. CUPS uses the most secure cipher suite available and the newest TLS version supported, and it can be configured by a customer (or a disto) to not use (not offer and not accept) CBC or TLS/1.0.

Regarding certificates, you just need to concatenate the server and root carts to provide the correct validation chain.

**Comment by michaelrsweet** [comment]
Pushed a change for GNU TLS that catches the rest of the CBC cipher suites with the DenyCBC option; note that this caused Firefox to fail to work with the CUPS web interface and I'm still investigating why - Firefox should still support one of the remaining cipher suites.

I will also be pushing the changes for fixing "ServerTokens none" tomorrow.

**Comment by michaelrsweet** [comment]
[master 5cc8588e8] Fix the `ServerTokens None` option (Issue #5065)

**Comment by michaelrsweet** [comment]
OK, it appears that disabling TLS/1.0 causes Firefox to fail... Closing this bug out but will continue to investigate...
