### ISSUE TITLE
Unable to print client hostname on page log in cups server

### ISSUE THREAD

**Issue by gauravsalve0** [apple/cups#5069]
Hello Everyone

I want to configure cups server, in that i wanted to print client hostname instead of ip address in the the page log of the cups server.

i am using CUPS 1.7.5 and  os "openSUSE Leap" VERSION="42.2"

i have made setting in cupsd.conf as follows.

   1. HostNameLookups On
   2.PageLogFormat %p %u %j %T %P %C %{job-billing} %{job-originating-host-name} %{job-name} %{media} %{sides}

On client side In /etc/hosts file we have enter localhost   <hostname>but when i go to the address in browser  http://localhost:631 >> Administration>> page_log
we can only see the IP Address instead of hostname in the page log. what else changes is needed????
Apart this Everything is working well , need solution for the hostname entity.

Please Help To Resolve this issue ...!!

**Comment by michaelrsweet** [comment]
Hmm, this *should* work but might have been fixed in a subsequent CUPS release (1.7.5 is a few years old...)
