### ISSUE TITLE
ServerName not really added to ServerAlias array

### ISSUE THREAD

**Issue by efuss** [apple/cups#5072]
The _ServerName_ attribute is not really added to the _ServerAlias_ array despite a log message pretending it was.

There is a
`cupsdAddAlias(ServerAlias, ServerName)`
missing before
`cupsdLogMessage(CUPSD_LOG_DEBUG, "Added auto ServerAlias %s", ServerName);`
in scheduler/conf.c, isn't it?

**Comment by michaelrsweet** [comment]
[master a2a13afb4] Fix the default ServerAlias value (Issue #5072)
