### ISSUE TITLE
Way to create date and time footer for all documents via CUPS

### ISSUE THREAD

**Issue by kdamianakis** [apple/cups#5073]
I wonder if there is a way to create date and time footer for all documents via CUPS, perhaps via a preprocessor or via an installation of a custom apple PDF printer? There is a requirement to have date and time in all printed documents from the mac so version control can be instigated - any advice or pointers would be appreciated.

**Comment by michaelrsweet** [comment]
There isn't a way to add the date and time via CUPS, but most office applications offer this functionality. And you might find third-party solutions that add a date and time.

That said, using the date and time of printing for version control won't work - the values will change with every print job, regardless of whether the content has been changed.
