### ISSUE TITLE
strange adminurl TXT record for non-.local ServerName

### ISSUE THREAD

**Issue by efuss** [apple/cups#5074]
With a fqdn `ServerName`, the value is copied intro `DNSSDHostName` variable, and `dnssdBuildTxtRecord()` ends up building a strange `adminurl` TXT RR as in
`adminurl=http://cups-ea.math.uni-bonn.de.local.:631/printers/heissmangel`.
I'm not sure what the code starting with `if (strstr(DNSSDHostName, ".local"))`
is intended to do, but apart from it not verifying the .local is actually at the end of `DNSSDHostName`, it appends .local even to fqdns.

**Comment by michaelrsweet** [comment]
The code was not designed to support FQDNs since the TXT record registrations are normally only exported via mDNS, so we want to export the .local hostname. But we can update this code to only append .local for unqualified hostnames.

**Comment by michaelrsweet** [comment]
[master ada342124] Fix the adminurl field in the TXT record for fully-qualified `ServerName` values (Issue #5074)
