### ISSUE TITLE
Point of device-uri included in Get-Printer-Attributes response

### ISSUE THREAD

**Issue by efuss** [apple/cups#5075]
What's the point of the `device-uri` attribute being included in the `Get-Printer-Attributes` response? That's the URI the CUPS backend uses to talk to the printer, so which clients are supposed to meke use of it?

Some clients (namely OSX 10.9 and 10.10), when presented a ipp:// `device-uri`, try to download the PPD directly from there, which is bound to fail in different ways (unless that's a cascaded CUPS server behind the URI), leading to timeouts, error messages or default PPDs being used.

The attached hack eliminates the `device-uri` from the `Get-Printer-Attributes` response by excluding it from the set copied by `copy_printer_attrs()` and makes said clients behave again (downloading the PPD from the CUPS server).
Of course, other clients may rely on that attribute or need a dummy substituted instead.

[exclude-device-uri.txt](https://github.com/apple/cups/files/1182959/exclude-device-uri.txt)

**Comment by michaelrsweet** [comment]
@efuss The device-uri attribute is a core part of how CUPS supports printing. If we removed the attribute from the Get-Printer-Attributes response, a lot of functionality would stop working...

**Comment by michaelrsweet** [comment]
And if there are clients that don't work properly, please file bugs against those clients.

**Comment by efuss** [comment]
> @efuss The device-uri attribute is a core part of how CUPS supports printing. If we removed the attribute from the Get-Printer-Attributes response, a lot of functionality would stop working...
Can you provide me with an example how a client can sensibly use the device-uri attribute? There must be something I'm missing: In my world, it's the CUPS server's job to talk to the printer and no-one else's. I've learned that cups-browsed (ab)uses the field trying to tell if two printers it has been learned of by different means are identical, but that's probably not the intended use case.

> And if there are clients that don't work properly, please file bugs against those clients.
Working with Apple now, you can probably hint me at how to correctly file a bug against the Add Printer part of the Control Panel (of 10.9/10.10), whatever that component is called internaly?

**Comment by michaelrsweet** [comment]
Aside from administrative tools (which manage print queues, etc.), the device-uri is also used by regular client software to associate discovered printers with existing print queues, and for determining the proper authorization service/domain to use (typically for Kerberos).

As for where to file Apple bug reports, that would be <http://bugreport.apple.com>. They will pass the bug over to the printing team who can then determine whether the bug still exists or has been fixed in a subsequent macOS release.
