### ISSUE TITLE
Patch to create a PID file

### ISSUE THREAD

**Issue by efuss** [apple/cups#5080]
The cupsd daemon doesn't write a PID file.
BSD's _newsyslog_ needs one for logfile rotation. The _check_pid_ monitoring plugin needs it, too. The _rc.d_ init system benefits from one. Nevertheless, requests to add one have repeatedly been turned down with Michael Sweet suggesting to patch the local distribution instead. This is what I did (for _pkgsrc_) and the sole purpose of this report (which I expect to be closed "wontfix" immediately) is to make [that patch](https://github.com/apple/cups/files/1190555/pidfile.patch.txt) readily available to whoever is looking for it (and doesn't use _pkgsrc_ anyway).
One caveat: There is another patch floating around (incorporated by Debian) which uses `cups.pid` for the filename while this one defaults to `cupsd.pid`.

**Comment by michaelrsweet** [comment]
You know what, I think I *will* add PID file support, but just for platforms that don't have an intelligent service interface (i.e. platforms without launchd, systemd, or upstart).

**Comment by michaelrsweet** [comment]
[master 03bc3ef4c] The scheduler now creates a PID file when not running on demand with a modern service launcher (Issue #5080)

**Comment by OdyX** [comment]
This change doesn't build where

```
