### ISSUE TITLE
Linux Jessie & cups 1.7.5-11 misses the last 2 lines of each page printed.

### ISSUE THREAD

**Issue by CptDangerous** [apple/cups#5082]
I have an HP Deskjet 6840 which is shared by several PCs (Mac & Linux) around the house.

Under Jessie (kernel 4.9.35-v7+) on a Raspberry Pi 3 (fully updated/upgraded) using HPLIP 3.16.11 and using A4 paper, the printer consistently misses the last 2 lines off every page when using lpr to queue a job.

It is possible to discern that the printer has attempted to print the first of these two lines as there is a feint dotted line along the bottom of the page but  the second of these two lines disappears into a black hole! I suspect that these two lines should actually be the top two lines on the next page.

I haven't selected any particular font, opting for whatever font is the default.

I wondered if the driver was ignoring the paper size in the config and assuming 8.5" x 11" but A4 is approx 11.7" (297mm) long so the page would be adequately long.

The printer test page reports:
Media Limits: 0.12 x 0.12 to 8.15 x 11.56 inches

Has anyone else noticed this "feature"?

**Comment by michaelrsweet** [comment]
I'm guessing this is a margins issue with this printer, which has larger margins when printing duplex output. But not a CUPS issue...

(probably file a bug with the HPLIP folks...)

**Comment by CptDangerous** [comment]
Hmmm... perhaps, as it only happens with Linux (of just about any flavour). Thanks Michael.
