### ISSUE TITLE
Support newer language IDs in web interface

### ISSUE THREAD

**Issue by xfengs** [apple/cups#5083]
I'd like to set the language to Chinese, but after  add line _DefaultLanguage zh_CN_ and restart cups, the web interface still shows english . In fact , not just **zh_CN** , other languages like **fr, ja ,ru**... also don't work. 
_(I have translated all the files down below into chinese :
doc/index.html 
locale/cups_zh_CN.po
templates/*.tmpl   )_

My system is ubuntu 17.04, locale of system is china, so is the browser.

thanks very much

**Comment by xfengs** [comment]
anyone can help me

**Comment by michaelrsweet** [comment]
Sorry, I've been on vacation so haven't had time to respond.

What browser are you using? Generally setting the browser language (which isn't automatically the same as your UI language/locale) in the preferences of your browser should provide the correct results.

If not, set the log level to debug (run `cupsctl --debug-logging`), visit the CUPS web interface, and attach the /var/log/cups/error_log from your system.

**Comment by xfengs** [comment]
thank you michaelrsweet 
That works after I set the  browser language , and  Chrome and Firefox can show chinese well (zh_CN  translated by myself).  

But a new little problem is that I use Windows10 to access the interface,  IE browser can't show chinese (zh_CN) , still in english. I test  other language works well , like ja/es , by add the language in system control panel, really confused.

**Comment by michaelrsweet** [comment]
Are you using IE or Edge on Windows 10?

Also, if you can do the following, that'll provide the info I need to help you:

> If not, set the log level to debug (run `cupsctl --debug-logging`), visit the CUPS web interface, and attach the /var/log/cups/error_log from your system.

**Comment by xfengs** [comment]
Both IE and Edge. 
Here is my debug information: [https://github.com/xfengs/baidupanunzip/blob/master/error_log](url)
I found when I use IE and Edge , there shows "LANG=zh_HANS-CN.UTF8" ,  then I copy all the /doc/zh_CN, /tempplates/zh_CN, /locale/cups_zh_CN.po to zh_HANS-CN*, and add it in makedefs , then make install,  that's really works (.po file need be copied manully, i dont know why, maybe because the symbol "-"?) besides the home page is still in english, :-(, if you can solve it , that's perfect, if not , it doesn't matter. 
Thank you very much.

**Comment by michaelrsweet** [comment]
OK, Windows is using the newer-style region codes which CUPS doesn't (yet) support for the web interface. Will update accordingly... (just did it for the libcups localization stuff in 2.2.5).

**Comment by michaelrsweet** [comment]
[master 2793a478d] The web interface did not support newer language identifiers used by Microsoft web browsers (Issue #5803)
