### ISSUE TITLE
HP 2420 Comm error on toner low indication

### ISSUE THREAD

**Issue by satch89450** [apple/cups#5087]
I have a HP 2420 printer.  Printer has been working fine, until I get the printer indication that Toner is reported by the printer to be at 15%, which triggers a "Low reached" status both in the status page (which the printer will print) and on the printer display screen. Printer status page says I have an estimated 1600 pages worth of toner remaining. All attempts to print using CUPS results in the job going into a "black hole":  data is sent, but nothing prints.  Here is the /var/log/messages log output of my latest attempt to print the Test page:

Aug 16 07:20:32 c7-admin systemd: Started CUPS Printing Service.
Aug 16 07:20:32 c7-admin systemd: Starting CUPS Printing Service...
Aug 16 07:20:32 c7-admin gnome-session: (gnome-settings-daemon:4672): color-plugin-WARNING **: failed to connect to device: Failed to connect to missing device /org/freedesktop/ColorManager/devices/cups_hp_LaserJet_2420
Aug 16 07:20:32 c7-admin gnome-session: (gnome-settings-daemon:4672): color-plugin-WARNING **: failed to connect to device: Failed to connect to missing device /org/freedesktop/ColorManager/devices/cups_HP_LaserJet_Professional_P1109w
Aug 16 07:20:32 c7-admin colord: (colord:2803): Cd-WARNING **: failed to get session [pid 1715]: Unknown error -2
Aug 16 07:20:32 c7-admin colord: (colord:2803): Cd-WARNING **: failed to get session [pid 1715]: Unknown error -2
Aug 16 07:20:41 c7-admin hp[1729]: io/hpmud/musb.c 426: Found interface conf=0, iface=0, altset=1, index=1
Aug 16 07:20:41 c7-admin hp[1729]: io/hpmud/musb.c 388: Active kernel driver on interface=0 ret=0
Aug 16 07:20:41 c7-admin hp[1729]: io/hpmud/musb.c 531: claimed 7/1/2 interface
Aug 16 07:20:41 c7-admin hp[1729]: io/hpmud/musb.c 776: read actual device_id successfully fd=1 len=141
Aug 16 07:20:41 c7-admin hp[1729]: io/hpmud/musb.c 557: released 7/1/2 interface
Aug 16 07:20:41 c7-admin hp[1729]: io/hpmud/musb.c 956: new PRINT channel=2 clientCnt=1 channelCnt=1
Aug 16 07:20:41 c7-admin hp[1729]: io/hpmud/musb.c 426: Found interface conf=0, iface=0, altset=1, index=1
Aug 16 07:20:41 c7-admin hp[1729]: io/hpmud/musb.c 388: Active kernel driver on interface=0 ret=0
Aug 16 07:20:41 c7-admin hp[1729]: io/hpmud/musb.c 531: claimed 7/1/2 interface
Aug 16 07:21:33 c7-admin hp[1729]: io/hpmud/musb.c 1449: unable to write data hp:/usb/hp_LaserJet_2420?serial=CNGKJ66402: 45 second io timeout
Aug 16 07:21:38 c7-admin hp[1729]: io/hpmud/musb.c 765: invalid deviceid ret=-7: No data available
Aug 16 07:21:38 c7-admin hp[1729]: prnt/backend/hp.c 630: ERROR: 5021 device communication error!
Aug 16 07:21:38 c7-admin hp[1729]: io/hpmud/musb.c 546: aborting outstanding 7/1/2 write
Aug 16 07:21:38 c7-admin kernel: usb 1-4: Process 1729 (hp) called USBDEVFS_CLEAR_HALT for active endpoint 0x02
Aug 16 07:22:21 c7-admin kernel: usb 1-4: USB disconnect, device number 8
Aug 16 07:22:21 c7-admin udev-configure-printer: Disabled printer ipp://localhost:631/printers/hp-LaserJet-2420 as the corresponding device was unplugged or turned off
Aug 16 07:22:21 c7-admin systemd: Unit printer.target is not needed anymore. Stopping.
Aug 16 07:22:21 c7-admin systemd: Stopped target Printer.
Aug 16 07:22:21 c7-admin systemd: Stopping Printer.

**Comment by michaelrsweet** [comment]
The HP driver is returning this status, nothing we can do.
