### ISSUE TITLE
PPD Generator for driverless printing: Workaround if printer reports faulty resolution

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5088]
There are some IPP Everywhere/PWG Raster printers with a firmware bug which report a wrong resolution as pwg-raster-document-resolution-supported IPP attribute. If this happens (horizontal and/or vertical resolution is < 75 dpi) the attached patch tries the printer-resolution-supported attribute and if this is also wrong (< 75 dpi) it falls back to 300 dpi.
The problem was reported on the Brother MFC-9340CDW (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=868360) which reports that it support PWG Raster but has the pwg-raster-document-resolution-supported IPP attribute reporting a resolution of 600x2dpi which the PPD generator of CUPS uses and then the filters of CUPS and cups-filters generate a wrong bitmap for the pages. Note that the poster of the Debian bug has returned the printer to the store before he could finally test the fix, so he cannot give further input.
I have applied the fix already to cups-filters, therefore the problem now only occurs when it is actually CUPS generating the PPD file (CUPS creates driverless queue fully automatically on-demand or "lpadmin -m everywhere").
Patch for CUPS: 
[pwg-raster-resolution-fallback.patch.txt](https://github.com/apple/cups/files/1233078/pwg-raster-resolution-fallback.patch.txt)
IPP attributes of Brother MFC-9340CDW: 
[Brother-MFC-9340CDW-ipp-attrs.txt](https://github.com/apple/cups/files/1233083/Brother-MFC-9340CDW-ipp-attrs.txt)

**Comment by tillkamppeter** [comment]
Also the patch of Issue #5091 solves this.

**Comment by michaelrsweet** [comment]
We are not going to add infinite workarounds for buggy printers. This is an obvious bug that the printer vendor needs to fix - we are not going to add a workaround.
