### ISSUE TITLE
cupsGetDests() returns more than number of valid printers

### ISSUE THREAD

**Issue by DennisYY** [apple/cups#5089]
cupsGetDests(cups_dest_t **dests) in CUPS 2.2.4 of macOS 10.13 beta 4 returns more than number of valid printers in some cases, which remain in CUPS 2.2.5 of macOS 10.13 beta 5~7.
For example, 5 or 6 printers may be returned even there are only 3 printers, deleted printers will be listed as 4th or later printers, we could see their name in dests->name.

cupsGetDests() in CUPS 2.2.4 of macOS 10.13 beta 4 returns empty list in some cases, which was fixed in CUPS 2.2.5 of macOS 10.13 beta 5~7.

**Comment by michaelrsweet** [comment]
This is as designed - cupsGetDests now returns both local queues and network printers.
