### ISSUE TITLE
Make ippserver emulating printers based on IPP attributes files (for remote debugging)

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5093]
Since I have added driverless printing support to Ubuntu via CUPS and cups-filters I get sometimes bug reports of users complaining that their printer does not work in driverless mode. Then I usually ask the user for the PPD file, the error_log and also (as you also usually do) I as to run the command
`ipptool -tv URI get-printer-attributes.test > printer-ipp-attrs.txt`
This file then tells me what the data is which CUPS and cups-filters use for their decisions and I can often imagine what goes wrong by that.
But sometimes it would be much better if I could actually test it locally, do changes in the code, re-test and find out how to get it going. My idea is now, why should one not use these files to emulate the printer, at least its IPP attribute reporting. Imagine one could run the following command on a virtual machine:
`ippserver --ipp-attrs-file=printer-ipp-attrs.txt`
The ippserver utility reads then the file which the complaining user has supplied using the ipptool command from above and emulates a printer with exactly these attributes. Then CUPS and cups-browsed on the host (or another virtual machine) see this emulated printer and should do the same thing (especially in terms of creating a queue for driverless printing) as if the user's printer was actually in the local network.
WDYT?

**Comment by michaelrsweet** [comment]
This is an interesting request, but we'll want to update ipptool to write the right format rather than make ippserver try to read the plain text output from ipptool.

**Comment by tillkamppeter** [comment]
The advantage of ippserver reading the attributes from a text file is that you (for CUPS) or I (for cups-filters) only need to ask the bug-reporting user once for the usual command
`ipptool -tv URI get-printer-attributes.test > printer-ipp-attrs.txt`
and we can first browse his file immediately as it is human-readable, second, immediately emulate the user's printer with ippserver, and third, we do not need a binary file from the user which GitHub's Issue tracker does not accept.

**Comment by michaelrsweet** [comment]
The output from "ipptool -t" is often truncated for large attributes and is not something we could parse easily.

I am suggesting that I just need to add another output format for ipptool that generates the existing ippserver/ipptool attribute syntax ("ATTR value-tag name value(s)", etc.) which IS parseable and would not be truncated.

**Comment by tillkamppeter** [comment]
Great, this makes it also easier to copy and paste IPP attributes from the ipptool output into a .test file to perform an action with ipptool.

**Comment by michaelrsweet** [comment]
[master 6646208ba] Add support for writing ippserver attributes files from ipptool (Issue #5093)
