### ISSUE TITLE
"Print" messed up manual duplex printing 

### ISSUE THREAD

**Issue by gloschtla** [apple/cups#5094]
I am using Samsung SCX-3400 Series in Linux Mint 18.
This printer cannot turn papers to print on both sides, so I often did this manually and it was successful.

But this time the page numbers got messed up. I made these settings:
print pages 14-48 
print odd pages - so it should print 15, 17, 19 ,.., 47 !

result: it printed the pages 14, 16, .., 48

The concerning document is a PDF, created by MS Office 2016 with password protection.

**Comment by michaelrsweet** [comment]
The page-ranges option gets applied BEFORE page-set (even/odd/all), so page 14 becomes page 1 in the set. If you ask for pages 15-48 and print only odd pages you'll get the correct pages.

**Comment by gloschtla** [comment]
Yeah, I also guessed, that this was the reason. Because CUPS first exports a temporary PDF based on the given range of pages, and then prints out of this new PDF in /tmp 

I think the issue is not to be closed, until a preview of the to-be-printed pages will be shown, which lets the user check before using ink and paper. This would be a crucial work-around, until a real software-solution can be developed.
