### ISSUE TITLE
lp error message when the configured default printer isn't available could be clearer

### ISSUE THREAD

**Issue by OdyX** [apple/cups#5096]
As highlighted by martin in https://bugs.debian.org/870463 where the default printer as configured in `~/.cups/lpoptions` was not available anymore; they were getting:
> lp: Error - no default destination available.

but the error message could be improved to read:

> Invalid default destination specified in config file: mfc9465cdn

or something along these lines.

**Comment by michaelrsweet** [comment]
I don't know how far we want to go with this, but holding for 2.3.x.

**Comment by michaelrsweet** [comment]
[master d6db9ea1d] The `lp` and `lpr` commands now provide better error messages when the default printer cannot be found (Issue #5096)
