### ISSUE TITLE
testlang.c test fails under C.utf-8

### ISSUE THREAD

**Issue by OdyX** [apple/cups#5097]
I've uploaded [2.2.4-62-g4f272af7b](https://github.com/apple/cups/commit/4f272af7bbf4c6f409998e3b1d1f89df4bda8a28) to Debian and the `testlang` test broke all builds (e.g. [amd64](https://buildd.debian.org/status/fetch.php?pkg=cups&arch=amd64&ver=2.2.4-62-g4f272af7b-1&stamp=1503785126&raw=0) ) with the following confusing error:
```
Running language API tests...
./testlang
Language = "C"
Encoding = "utf-8"
No       = "No" (FAIL)
Yes      = "Yes" (FAIL)
_cupsStrScand("1") number=1.000000
_cupsStrFormatd(1.000000) buffer="1"
_cupsStrScand("-1") number=-1.000000
_cupsStrFormatd(-1.000000) buffer="-1"
_cupsStrScand("3") number=3.000000
_cupsStrFormatd(3.000000) buffer="3"
_cupsStrScand("5.125") number=5.125000
_cupsStrFormatd(5.125000) buffer="5.125"
Makefile:517: recipe for target 'testlang' failed
```

It seems that the test expects a different result between the original locale and the build locale. Above, when built with `C.UTF-8` it breaks although with my `fr_CH.utf-8` it succeeds:
```
./testlang
Language = "fr_CH"
Encoding = "utf-8"
No       = "Non" (PASS)
Yes      = "Oui" (PASS)
```

This seems quite fragile to me.

**Comment by michaelrsweet** [comment]
a) this is a unit test, and b) the code is testing whether it gets a different pointer (i.e. it has a localization) for each of the strings, showing that the underlying localization code is working (i.e. this is a unit test).

If you don't use a locale with a localization, this unit test will fail. Using even "en" will make it work.

I will look at updating the unit test program to override the default locale if it is any variant of "C".

**Comment by OdyX** [comment]
> If you don't use a locale with a localization, this unit test will fail. Using even "en" will make it work.

That's not what I see here:
```
$ LC_MESSAGES=en ./cups/testlang ; echo $?
Language = "en"
Encoding = "utf-8"
No       = "No" (FAIL)
Yes      = "Yes" (FAIL)
_cupsStrScand("1") number=1.000000
_cupsStrFormatd(1.000000) buffer="1"
_cupsStrScand("-1") number=-1.000000
_cupsStrFormatd(-1.000000) buffer="-1"
_cupsStrScand("3") number=3.000000
_cupsStrFormatd(3.000000) buffer="3"
_cupsStrScand("5.125") number=5.125000
_cupsStrFormatd(5.125000) buffer="5.125"
1
```
… where …
```
$ LC_MESSAGES=fr ./cups/testlang ; echo $?
Language = "fr"
Encoding = "utf-8"
No       = "Non" (PASS)
Yes      = "Oui" (PASS)
_cupsStrScand("1") number=1.000000
_cupsStrFormatd(1.000000) buffer="1"
_cupsStrScand("-1") number=-1.000000
_cupsStrFormatd(-1.000000) buffer="-1"
_cupsStrScand("3") number=3.000000
_cupsStrFormatd(3.000000) buffer="3"
_cupsStrScand("5.125") number=5.125000
_cupsStrFormatd(5.125000) buffer="5.125"
0
```

I stand to saying that this is fragile: a unit-test should not depend on the environment.

**Comment by michaelrsweet** [comment]
When the unit test is explicitly testing the environment (i.e. test language localization using the current locale), it ABSOLUTELY MUST DO ITS JOB AND FAIL IF NO LOCALIZATION IS FOUND.

Again, this unit test is working exactly as it is supposed to. The failure (even for "en" in this case, since on Linux different localization files are involved) is 100% valid and points to an implementation bug.

**Comment by OdyX** [comment]
Fair enough.

Debian buildds have restricted environments with only C.utf-8 available and I make a point to run all available tests. How would you proceed there? Comment the test out?

**Comment by michaelrsweet** [comment]
First, testlang uses the message catalogs in the locale directory so it doesn't matter what the host OS has available/installed - we are testing the internal localization features of libcups.

Second, once I fix the bug in this unit test (and make sure there is a cups_en.po file), the test will work for both the POSIX ("C" locale) and other locales... The goal here is to catch localization bugs as soon as possible, and this unit test was updated for 2.2.4 to address a macOS localization bug that wasn't caught.

**Comment by OdyX** [comment]
I debugged this further and found out why it worked locally but not during a build: it seems `testlang` uses the configured `LOCALEDIR` aka `/usr/share/cups/locale`. So `./testlang` succeeds on a system with CUPS installed, but not during a clean build.

It seems a mechanism like the one in `testppd` (creating a fake symlink tree of the locale files to test) would be needed here.

**Comment by michaelrsweet** [comment]
[master 9964a31a7] Fix the localization unit test on Linux (Issue #5097)

**Comment by michaelrsweet** [comment]
OK, this appears to be fixed now.
