### ISSUE TITLE
cupsd wakes up once per second to expire stale local queues (inefficient)

### ISSUE THREAD

**Issue by jeffersonchua** [apple/cups#5100]
The following commit causes high CPU load. Run cups. after 60 seconds, cupsd will run with very high CPU load eventually up to 100%. Revert this commit, and cpu usage drops to zero. Don't need to send any job to cause this.

Thanks,
Jeff.

commit e1bb4a6e98056c1abb29e59c46d86bfdcbd662f5
Author: Michael Sweet <michael.r.sweet@gmail.com>
Date:   Fri May 26 09:53:34 2017 -0400

        Make local printer deletion independent of job history updates.

**Comment by michaelrsweet** [comment]
Funny, I can't reproduce - been running now for 15 minutes and cupsd seems to be checking for stale printers once a second; can you attach an error_log with debug logging enabled, along with your printers.conf file?

**Comment by michaelrsweet** [comment]
(the once a second bit is not what I want to see, but that isn't causing 100% CPU)

**Comment by jeffersonchua** [comment]
Michael,
> Funny, I can't reproduce - been running now for 15 minutes and cupsd seems to be checking for stale printers once a second;

After 60 seconds, the cpu utilization will start to go up ... don't need to wait 15 minutes.

     PID  PPID  %MEM  %CPU COMMAND
   12778     1   0.0  54.0 cupsd -C /etc/cups/cupsd.conf -s /etc/cups/cups-files
1 process listed.


> can you attach an error_log with debug logging enabled, along with your printers.conf file?

Attached.

[printers.conf.txt](https://github.com/apple/cups/files/1267929/printers.conf.txt)
[error_log.txt](https://github.com/apple/cups/files/1267931/error_log.txt)

cups compiled with ...
  $ ./configure --prefix=/usr --sysconfdir=/etc --enable-ssl --disable-avahi --disable-browsing --disable-cdsassl --disable-dbus --disable-dnssd --disable-gssapi --disable-launchd --disable-pam --disable-static --without-java --without-php --without-python
uname -m = x86_64
uname -r = 4.13.0-rc7
uname -s = Linux
uname -v = #6 SMP Wed Aug 30 08:57:28 SGT 2017

**Comment by michaelrsweet** [comment]
OK, I'm still not having any luck reproducing this...  Setting up a fresh VM to see if I can reproduce there...

**Comment by michaelrsweet** [comment]
No joy there either. I get the once-a-second wakeup but not the high CPU usage you are experiencing.

Your error_log also doesn't show a lot of activity.

We'll use this bug to track the once-a-second wakeup's, but I can't reproduce the 100% CPU.

**Comment by jeffersonchua** [comment]
On Fri, Sep 8, 2017 at 5:09 AM, Michael R Sweet <notifications@github.com>
wrote:

> No joy there either. I get the once-a-second wakeup but not the high CPU
> usage you are experiencing.
>
> Your error_log also doesn't show a lot of activity.
>
> We'll use this bug to track the once-a-second wakeup's, but I can't
> reproduce the 100% CPU.
>
No worries. It's there somewhere in cupsd ... I'll add debugs to find out
where ... just want to inform you in case it's something that you have come
across or someone seeing this as well.

Jeff.

**Comment by jeffersonchua** [comment]
On Sat, Sep 9, 2017 at 12:40 PM, Jeff Chua <jeff.chua.linux@gmail.com> wrote:
>
>
> On Fri, Sep 8, 2017 at 5:09 AM, Michael R Sweet <notifications@github.com>
> wrote:
>>
>> No joy there either. I get the once-a-second wakeup but not the high CPU
>> usage you are experiencing.
>>
>> Your error_log also doesn't show a lot of activity.
>>
>> We'll use this bug to track the once-a-second wakeup's, but I can't
>> reproduce the 100% CPU.
>
> No worries. It's there somewhere in cupsd ... I'll add debugs to find out
> where ... just want to inform you in case it's something that you have come
> across or someone seeing this as well.

Michael,

It's local patch I did to change the default retry interval to
something other than 10 sec and for some reason, it doesn't work with
the "local printer deletion" patch.

Reverting my changes solved the high-cpu-load issue.

Please close the issue.

Thanks,
Jeff.

**Comment by michaelrsweet** [comment]
Well, we still want to eliminate the wake-up every second part - that isn't good for system performance or power consumption...
