### ISSUE TITLE
issues when originating-user-name not same as authenticated username

### ISSUE THREAD

**Issue by dkosovic** [apple/cups#5104]
**CUPS client:** macOS Sierra 10.12.6
**CUPS server:** CUPS 2.2.4 Linux

I have an issue with macOS clients when the local username is not the same as the centrally authenticated username on the server. The username argument passed to the filters on server is the originating local username on the macOS client, so PaperCut denies the job.

I've attached a log file, for clarity, I've renamed the macOS client originating username to "localuser" and centrally authenticated user on the server to "centraluser"

On the server, I'm guessing  _requesting-user-name_  might need to be set to the value of _job-accounting-user-id_ to do the right thing in some situations. 
[error_log.txt](https://github.com/apple/cups/files/1273750/error_log.txt)

**Comment by michaelrsweet** [comment]
Per the definition of IPP in RFC 8011 (previously 2911 and 2566 before that), the job-originating-user-name attribute gets the value of the most authenticated user name, and so it needs to be the "centraluser" value, not "localuser".

**Comment by dkosovic** [comment]
> and so it needs to be the "centraluser" value, not "localuser".

But that isn't what is happening, _job-originating-user-name_ is being set to "localuser" and not "centraluser".

_requesting-user-name_ is also being set to "localuser" and not "centraluser". Extract from the server side logs :
```
add_job: requesting-user-name="localuser"
``` 

In previous versions of CUPS (but I can't say from which version things changed), on the server side, _job-originating-user-name_ was "localuser" and _requesting-user-name_ was "centraluser". Consequently the server side filters had no problem with processing "centraluser", but with the new CUPS version don't know what to do with "centraluser".
