### ISSUE TITLE
Build fails with GCC 7.2.0: error: unknown type name '__float128'

### ISSUE THREAD

**Issue by paulmenzel** [apple/cups#5106]
[Building CUPS in Travis CI with GCC 7.2.0 fails with the errors below.](https://travis-ci.org/paulmenzel/cups/jobs/272545457)

```
[…]
Compiling ppdc-constraint.cxx...
Compiling ppdc-driver.cxx...
In file included from ppdc-attr.cxx:18:
In file included from ./ppdc-private.h:20:
In file included from ./ppdc.h:22:
In file included from /usr/lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/stdlib.h:36:
In file included from /usr/lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/cstdlib:77:
/usr/lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/std_abs.h:101:3: error: unknown type name '__float128'
  __float128
  ^
/usr/lib/gcc/x86_64-linux-gnu/7.2.0/../../../../include/c++/7.2.0/bits/std_abs.h:102:7: error: unknown type name '__float128'
  abs(__float128 __x)
      ^
[…]
```

**Comment by michaelrsweet** [comment]
This looks like a GCC or libstdc++ bug - we never reference or use the__float128 type.

**Comment by jwakely** [comment]
I don't think it's a libstdc++ bug. That line is only present in the libstdc++ header if `_GLIBCXX_USE_FLOAT128` is defined, and if that's defined then `__float128` would be valid. So it looks like something in your build is defining that macro when it shouldn't be defined.

**Comment by michaelrsweet** [comment]
Like I said, there is nothing in the CUPS code that would trigger or use this.

**Comment by jwakely** [comment]
The error at https://travis-ci.org/paulmenzel/cups/jobs/272545457#L1172 is not one that G++ ever issues, but it is a Clang error, so the build seems to be using Clang with headers from libstdc++ 7.2.0, and failing.

I suspect the version of Clang in the Travis setup is too old to use those headers.

**Comment by paulmenzel** [comment]
It looks like this is an [old issue](https://bugs.llvm.org/show_bug.cgi?id=13530#c3), that Clang doesn’t support this type.

> Clang doesn't support the __float128 type. Here are some workarounds: 
>
>  1) build with -D__STRICT_ANSI__
>  2) edit bits/c++config.h (somewhere inside /usr/include/c++/4.7.0) so it doesn't define _GLIBCXX_USE_FLOAT128
>  3) configure libstdc++ with clang instead of gcc
>  4) add 'struct __float128;' before you include any STL header
>
> Experimentation with the LLVM fp128 and ppc_fp128 types a few months ago 
> indicated that we have essentially no backends which support __float128 yet,
> so if we want to work around this directly in Clang, I think option (4) is
> probably the best way (add a __float128 type which is always incomplete).

**Comment by jwakely** [comment]
**Don't use `-D__STRICT_ANSI__`!!** That's an internal macro that is defined by the compiler and not for users to touch. Get off my lawn. The correct approach is to use `-std=c++14` instead of `-std=gnu++14` (or `-std=c++11` instead of `-std=gnu++11` etc.) and then the compiler will define `__STRICT_ANSI__`.

Anyway that info is out of date, Clang supports the type now (since 3.9.0 I believe).

**Comment by noloader** [comment]
Sorry to dig up an old report. I'm looking for a workaround. Also see GCC Issue 88078, [error: '__float128' was not declared in this scope on PowerPC](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88078)
