### ISSUE TITLE
Use more standard Git commit messages

### ISSUE THREAD

**Issue by paulmenzel** [apple/cups#5107]
It’d be great, if all commit messages could follow the format of having a short commit message summary as the first line, then one blank line, and then a longer description. [The Git documentation has a good template][1].

Commit ea4dcf9ff now looks quite long for example.

```
$ git log --oneline -1
ea4dcf9ff (origin/master) The `ipptool` program did not compare URI scheme or hostname components correctly for the WITH-ALL-HOSTNAMES, WITH-ALL-SCHEMES, WITH-HOSTNAME, or WITH-SCHEME predicates.
```

[1]: https://git-scm.com/book/en/v2/Distributed-Git-Contributing-to-a-Project

**Comment by michaelrsweet** [comment]
Most messages are a single short line, and we *do* have guild lines for this in our developer docs. Anyways, the best place to discuss this is on the cups-devel list and not in the issue tracker...
