### ISSUE TITLE
Format truncation warnings by GCC 7

### ISSUE THREAD

**Issue by paulmenzel** [apple/cups#5110]
GCC 7 shows [several warnings](https://travis-ci.org/paulmenzel/cups/jobs/274367672) like the one below.

```
Compiling dir.c...
dir.c: In function ‘cupsDirRead’:
dir.c:383:46: warning: ‘%s’ directive output may be truncated writing up to 255 bytes into a region of size between 0 and 1023 [-Wformat-truncation=]
     snprintf(filename, sizeof(filename), "%s/%s", dp->directory, entry->d_name);
                                              ^~
In file included from /usr/include/stdio.h:937:0,
                 from string-private.h:23,
                 from dir.c:20:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:64:10: note: ‘__builtin___snprintf_chk’ output between 2 and 1280 bytes into a destination of size 1024
   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        __bos (__s), __fmt, __va_arg_pack ());
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by michaelrsweet** [comment]
This isn't a type of warning we care about, particularly when PATH_MAX is much less than either.

It would be useful to know what the GCC option is to disable this...

**Comment by jwakely** [comment]
The warning prints `[-Wformat-truncation=]` so use `-Wno-format-truncation` to suppress it.

**Comment by fengshuicoin** [comment]
@jwakely Where would i add the -Wno-format-truncation?  Im having this issue on other repo such as bytecoin. Do i write this in make file?

**Comment by michaelrsweet** [comment]
@fengshuicoin That varies based on the project - some put the options in the makefiles, some in an include file (like CUPS), others in alternate build files (cmake, Xcode, etc.)

For an autoconf-based project with a configure script, you can set CFLAGS when you run the configure script, e.g.:

    CFLAGS="-Wno-format-truncation" ./configure ...

**Comment by fengshuicoin** [comment]
Ok thanks ill try cflags first then go from there.
