### ISSUE TITLE
New purpose of 'lpadmin -i' is confusing

### ISSUE THREAD

**Issue by leoarnold** [apple/cups#5111]
CUPS V2.2b1 dropped support for SysV interface scripts. If one still tries to use such a script with CUPS in the traditional way, they now get the error message:

```
$ lpadmin -p Office -i sysVinterface.sh -v /dev/null
lpadmin: Unable to open PPD "sysVinterface.sh": Missing PPD-Adobe-4.x header on line 0.
```

or

```
$ lpadmin -p Office -i sysVinterface.sh -v /dev/null
lpadmin: Unable to open PPD "sysVinterface.sh": Missing asterisk in column 1 on line 1.
lpadmin: Bad PPD file.
```

This is rather confusing, because a shell script obviously is not the same as a PPD file. It would be more helpful if the error message would say that support of this feature was dropped. Having '-i' be the same as '-P' is superfluous and unintuitive.

**Comment by michaelrsweet** [comment]
Will see what we can do to clear up the error messages and documentation.

**Comment by michaelrsweet** [comment]
[master d0df9cd33] Update lpadmin documentation and show a meaningful error message for interface scripts (Issue #5111)
