### ISSUE TITLE
Document supported toolchains

### ISSUE THREAD

**Issue by paulmenzel** [apple/cups#5116]
Several issues were closed with the argument, that the toolchain is not supported. The file `INSTALL.md` only contains the sentences below.

> You'll need ANSI-compliant C and C++ compilers, plus a make program and POSIX-
> compliant shell (/bin/sh).  The GNU compiler tools and Bash work well and we
> have tested the current CUPS code against several versions of GCC with excellent
> results.
>
> The makefiles used by the project should work with most versions of make.  We've
> tested them with GNU make as well as the make programs shipped by Compaq, HP,
> SGI, and Sun.  BSD users should use GNU make (gmake) since BSD make does not
> support "include".
>
> Besides these tools you'll want ZLIB library for compression support, the GNU
> TLS library for encryption support on platforms other than iOS, macOS, or
> Windows, and either MIT (1.6.3 or higher) or Heimdal Kerberos for Kerberos
> support.  CUPS will compile and run without these, however you'll miss out on
> many of the features provided by CUPS.
>
> On a stock Ubuntu install, the following command will install the required
> prerequisites:
>
>     sudo apt-get install autoconf build-essential libavahi-client-dev \
>          libgnutls28-dev libkrb5-dev libnss-mdns libpam-dev \
>          libsystemd-dev libusb-1.0-0-dev zlib1g-dev
>
> Also, please note that CUPS does not include print filters to support PDF or
> raster printing.  You *must* download GPL Ghostscript and/or the Open Printing
> CUPS filters package separately to print on operating systems other than macOS.

So could you please exactly document, which toolchain you use internally to build the project?

**Comment by michaelrsweet** [comment]
For macOS, the only supported (as in, something we will bother making fixes for) toolchain is clang as supplied with Xcode, which is what we use to build all components of macOS. And because of code signing and SIP, you can't actually replace the CUPS on macOS anymore - there is already a note about this in the INSTALL.md file...

But I will add huge disclaimer at the top of INSTALL.md to make things clear on macOS.

**Comment by michaelrsweet** [comment]
[master fd2f0a7af] Update INSTALL.md (Issue #5116)
[master 2cf3a36a4] One more thing for macOS (Issue #5116)
