### ISSUE TITLE
undefined reference to `httpConnect2' - CentOS

### ISSUE THREAD

**Issue by sarat12us** [apple/cups#5120]
I am compiling an existing program on CentOS that was written on Susi. It compiples well on Susi.
I get this error  : **undefined reference to `httpConnect2' - CentOS**
Do we have different version of Cups for CentOS?

_My Cups version is :_ cups-2.1.0

_My CentOS Details:_

CentOS Linux release 7.3.1611 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

**Comment by michaelrsweet** [comment]
The httpConnect2 function appeared in CUPS 1.7. Make sure your cups-libs package is up to date.

But ultimately the best place to get support for CentOS issues is from the CentOS folks (bug reporting URL is in your details above...)

**Comment by sarat12us** [comment]
Hi Mike, 
thanks for the reply 
> httpConnect2 function appeared in CUPS 1.7? 

that means it isnt present in ups version is : cups-2.1.0

**Comment by michaelrsweet** [comment]
httpConnect2 first appeared in CUPS 1.7, and IS part of CUPS 2.1.0. Please contact the CentOS folks to see what is going on for your system.

**Comment by sarat12us** [comment]
I just left a message to CentOS bugs report.
Meanwhile I am curious : The same CUPS 2.1.0 compiles and linked great in Susi. I just want to understand what could be the reason? Why not other function report issues other than : httpConnect2

**Comment by sarat12us** [comment]
Hi Mike,
I get this response from Cent OS 


> ~0030202TrevorH	(developer)2017-09-25 15:47 | This is not a bug and bugs.centos.org is not a support venue. We supply cups packages already and do not support building from source.
> -- | --

can you help me interpret the above?

**Comment by sarat12us** [comment]
Hi Mike,

Here is another response from Cent OS :

"
This is not a bug and bugs.centos.org is not a support venue.

We do not supply cups 2.1.0, our version is cups-1.6.3-29.el7.x86_64. According to https://www.cups.org/doc/api-httpipp.html#httpConnect2 the API call you're trying to use was introduced in 1.7. If you have cups 2.1.0 on CentOS then please ask then people you got 2.1.0 from as it's not our package.

I repeat this is NOT a support venue.
"
