### ISSUE TITLE
Long delay before printing the last page on HP Laserjet 1160 via USB

### ISSUE THREAD

**Issue by hawajrambo** [apple/cups#5121]
Dear Mike,

The Issue #4549, delay-close problem exists on HP Laserjet 1160.
Adding the following to org.cups.usb-quirks has solved the issue:

```
# HP LaserJet 1160
0x03f0 0x1e17 delay-close
```

Could you please include this in the future versions?

Gabor

**Comment by michaelrsweet** [comment]
[master aa2a77dec] Add USB quirk for HP LaserJet 1160 (Issue #1160)
