### ISSUE TITLE
postscript printer driver fails - laserjet 6MP on parallel port

### ISSUE THREAD

**Issue by thx1111** [apple/cups#5126]
Arch Linux
linux 4.13.3-1
cups 2.2.4-2
cups-filters 1.17.7-1
hplip 3.17.7-1

$ lpstat -v
device for laserjet6mp: hp:/par/HP_LaserJet_6MP?device=/dev/parport0

$ lpinfo --make-and-model "6mp" -m
drv:///hp/hpijs.drv/hp-laserjet_6mp-hpijs-pcl3.ppd HP LaserJet 6mp hpijs pcl3, 3.17.7
lsb/usr/HP/hp-laserjet_6mp-hpijs-pcl3.ppd.gz HP LaserJet 6mp hpijs pcl3, 3.17.7
drv:///hp/hpcups.drv/hp-laserjet_6mp-pcl3.ppd HP LaserJet 6mp pcl3, hpcups 3.17.7
lsb/usr/HP/hp-laserjet_6mp-pcl3.ppd.gz HP LaserJet 6mp pcl3, hpcups 3.17.7
lsb/usr/HP/hp-laserjet_6mp-ps.ppd.gz HP LaserJet 6P/6MP - PostScript
lsb/usr/HP/hp-laserjet_6p-ps.ppd.gz HP LaserJet 6P/6MP - PostScript

Printing using the hpijs or pcl3 drivers works normally.  Printing using the postscript driver sends a zero-length file to the printer, and uses 100% cpu from process "hp:/par/HP_LaserJet_6MP?device=/dev/parport0".

Would this be a cups bug or an hplip bug?

**Comment by michaelrsweet** [comment]
Hplip
