### ISSUE TITLE
Help needed Building Cups on CentOS

### ISSUE THREAD

**Issue by sarat12us** [apple/cups#5129]
Hi All,
I am new to Linux and new to Cups
I want to build libcups for CentOS as we do not have any rpm installer for CentOS. when i went to cups folder and run make i get this error 

```
cups]$ make
Makefile:18: ../Makedefs: No such file or directory
make: *** No rule to make target `../Makedefs'.  Stop.
```

Can Someone help me with instructions how to build cups on CentOS?
I could not find anything on google

**Comment by michaelrsweet** [comment]
Start by reading the file "INSTALL.md" that is included with the CUPS sources.

Note that most Linux distributions include many patches to the stock CUPS, and you'll also need the current versions of things like Ghostscript and cups-filters installed as well.

**Comment by sarat12us** [comment]
Do we need cups client to install cups 2.2.4?
