### ISSUE TITLE
cups client - help needed

### ISSUE THREAD

**Issue by sarat12us** [apple/cups#5130]
When I try to install cups 2.2.4 it complains I have cups client 1.6 installed and need cups version 1.6
Can some one help me how to get cups version compatible with 2.2.4 
And also please  help me understand , do we need cups-client at all?

**Comment by michaelrsweet** [comment]
This is not the cups user forum, it is a bug tracking page. Please post questions like this to the cups user forum on cups.org.

**Comment by sarat12us** [comment]
Hi mike 
cups.org redirects to github 
i am not sure what else to do

**Comment by imsedgar** [comment]
No,  cups.org doesn't redirect to github. Just read the page! In the menu line is a menu "Lists", which contain "User": https://lists.cups.org/mailman/listinfo/cups . This is the cups user forum.
