### ISSUE TITLE
cups-client - help needed

### ISSUE THREAD

**Issue by sarat12us** [apple/cups#5131]
When I try to install cups 2.2.4 on CentO it complains I have cups client 1.6 installed and need cups version 1.6 Can some one help me how to get cups version compatible with 2.2.4, even source code will do

**Comment by michaelrsweet** [comment]
You really need to use the mailing lists for questions like this.

**Comment by sarat12us** [comment]
I sent may mails to mailing list... no one responds, here I can at-least see your response which helped me may times..
