### ISSUE TITLE
difference between httpConnect and httpConnect2

### ISSUE THREAD

**Issue by sarat12us** [apple/cups#5132]
Can some one tell me the difference between cups httpConnect and cups httpConnect2
since CentOS ships cups version 1.6 the httpConnect2 is not available but httpConnect, 
So I am planning to use httpConnect, will there be any problems?

**Comment by michaelrsweet** [comment]
Please look at the cups/http.h header and use the CUPS developer list: <https://lists.cups.org/mailman/listinfo/cups-devel>

In the absence of the httpConnect2 API, use httpConnectEncrypt which allows you to control whether TLS encryption is used.
