### ISSUE TITLE
is it possible to reprint a completed job?

### ISSUE THREAD

**Issue by kirk86** [apple/cups#5137]
Hi,  I was wondering if it's possible to reprint a completed job?
I'm on mac os.
I've located my previously successful print job and issued the command to reprint the document, it says that the job has been restarted but nothing gets printed.

In the printers state menu its says `stopped filter failed`. I don't understand what that message means.

Here's a dump of the error log:

```
E [05/Oct/2017:12:34:10 +0100] [Job 303] Job stopped due to filter errors; please consult the error_log file for details.
D [05/Oct/2017:12:34:10 +0100] [Job 303] The following messages were recorded from 11:33:40 to 12:34:10
D [05/Oct/2017:12:34:10 +0100] [Job 303] Unloading...
D [05/Oct/2017:12:34:10 +0100] [Job 303] Loading attributes...
D [05/Oct/2017:12:34:10 +0100] [Job 303] Unloading...
D [05/Oct/2017:12:34:10 +0100] [Job 303] Loading attributes...
D [05/Oct/2017:12:34:10 +0100] [Job 303] Job restarted by user.
D [05/Oct/2017:12:34:10 +0100] [Job 303] time-at-processing=1507203250
D [05/Oct/2017:12:34:10 +0100] [Job 303] 2 filters for job:
D [05/Oct/2017:12:34:10 +0100] [Job 303] commandtops (application/vnd.cups-command to printer/_143_239_81_77/application/postscript, cost 100)
D [05/Oct/2017:12:34:10 +0100] [Job 303] - (printer/_143_239_81_77/application/postscript to printer/_143_239_81_77, cost 0)
D [05/Oct/2017:12:34:10 +0100] [Job 303] job-sheets=none,none
D [05/Oct/2017:12:34:10 +0100] [Job 303] argv[0]="_143_239_81_77"
D [05/Oct/2017:12:34:10 +0100] [Job 303] argv[1]="303"
D [05/Oct/2017:12:34:10 +0100] [Job 303] argv[2]="anonymous"
D [05/Oct/2017:12:34:10 +0100] [Job 303] argv[3]="Set Default Options"
D [05/Oct/2017:12:34:10 +0100] [Job 303] argv[4]="1"
D [05/Oct/2017:12:34:10 +0100] [Job 303] argv[5]="job-uuid=urn:uuid:e25b6e13-df42-3ec5-4ef8-339996a04748 job-originating-host-name=localhost date-time-at-creation= date-time-at-processing= time-at-creation=1501101827 time-at-processing=1507203250"
D [05/Oct/2017:12:34:10 +0100] [Job 303] argv[6]="/private/var/spool/cups/d00303-001"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[0]="<CFProcessPath>"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[1]="CUPS_CACHEDIR=/private/var/spool/cups/cache"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[2]="CUPS_DATADIR=/usr/share/cups"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[3]="CUPS_DOCROOT=/usr/share/doc/cups"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[4]="CUPS_FONTPATH=/usr/share/cups/fonts"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[5]="CUPS_REQUESTROOT=/private/var/spool/cups"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[6]="CUPS_SERVERBIN=/usr/libexec/cups"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[7]="CUPS_SERVERROOT=/private/etc/cups"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[8]="CUPS_STATEDIR=/private/etc/cups"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[9]="HOME=/private/var/spool/cups/tmp"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[10]="PATH=/usr/libexec/cups/filter:/usr/bin:/usr/sbin:/bin:/usr/bin"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[11]="SERVER_ADMIN=root@insight026.local"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[12]="SOFTWARE=CUPS/2.2.0"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[13]="TMPDIR=/private/var/spool/cups/tmp"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[14]="USER=root"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[15]="CUPS_MAX_MESSAGE=2047"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[16]="CUPS_SERVER=/private/var/run/cupsd"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[17]="CUPS_ENCRYPTION=IfRequested"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[18]="IPP_PORT=631"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[19]="CHARSET=utf-8"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[20]="LANG=en_US.UTF-8"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[21]="APPLE_LANGUAGE=en-US"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[22]="PPD=/private/etc/cups/ppd/_143_239_81_77.ppd"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[23]="RIP_MAX_CACHE=128m"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[24]="CONTENT_TYPE=application/vnd.cups-command"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[25]="DEVICE_URI=ipp://143.239.81.77/"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[26]="PRINTER_INFO=143.239.81.77"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[27]="PRINTER_LOCATION="
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[28]="PRINTER=_143_239_81_77"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[29]="PRINTER_STATE_REASONS=cups-ipp-conformance-failure-report,cups-ipp-missing-job-id"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[30]="CUPS_FILETYPE=document"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[31]="FINAL_CONTENT_TYPE=application/postscript"
D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[32]="AUTH_I****"
D [05/Oct/2017:12:34:10 +0100] [Job 303] Started filter /usr/libexec/cups/filter/commandtops (PID 484)
D [05/Oct/2017:12:34:10 +0100] [Job 303] Started backend /usr/libexec/cups/backend/ipp (PID 485)
D [05/Oct/2017:12:34:10 +0100] [Job 303] Restarted by "user".
D [05/Oct/2017:12:34:10 +0100] [Job 303] Sending stdin for job...
D [05/Oct/2017:12:34:10 +0100] [Job 303] update_reasons(attr=0(), s=\"+connecting-to-device\")
D [05/Oct/2017:12:34:10 +0100] [Job 303] op=\'+\', new_reasons=1, state_reasons=2
D [05/Oct/2017:12:34:10 +0100] [Job 303] STATE: +connecting-to-device
D [05/Oct/2017:12:34:10 +0100] [Job 303] Looking up \"143.239.81.77\"...
D [05/Oct/2017:12:34:10 +0100] [Job 303] backendWaitLoop(snmp_fd=5, addr=0x7fe240f021e8, side_cb=0x1002fde8f)
D [05/Oct/2017:12:34:10 +0100] [Job 303] Unable to auto-configure PostScript Printer - no bidirectional I/O available!
D [05/Oct/2017:12:34:10 +0100] [Job 303] PID 484 (/usr/libexec/cups/filter/commandtops) stopped with status 1.
D [05/Oct/2017:12:34:10 +0100] [Job 303] Hint: Try setting the LogLevel to "debug" to find out more.
D [05/Oct/2017:12:34:10 +0100] [Job 303] PID 485 (/usr/libexec/cups/backend/ipp) exited with no errors.
D [05/Oct/2017:12:34:10 +0100] [Job 303] End of messages
D [05/Oct/2017:12:34:10 +0100] [Job 303] printer-state=3(idle)
D [05/Oct/2017:12:34:10 +0100] [Job 303] printer-state-message="Filter failed"
D [05/Oct/2017:12:34:10 +0100] [Job 303] printer-state-reasons=cups-ipp-conformance-failure-report,cups-ipp-missing-job-id
````

Especially this `Unable to auto-configure PostScript Printer - no bidirectional I/O available!` is something that concerns me because if I use the `printers & scanners` program interface from mac os, it prints normally without any issues.

Any hints?

**Comment by michaelrsweet** [comment]
It *is* possible to reprint jobs as long as the documents associated with those jobs have been retained.  The default is for documents to be retained for 24 hours.

That said, the job you attempted to retry was a CUPS command file intended to reconfigure the PPD file based upon responses from the printer.  However, since you are using IPP there is no way for the PostScript command filter to interrogate the printer's PostScript interpreter - IPP does not provide a low-level socket interface to the PostScript interpreter, instead you use IPP's high-level interface to obtain the supported options and values.

So I guess the question is, what are you trying to do?


> On Oct 5, 2017, at 7:48 AM, kirk86 <notifications@github.com> wrote:
> 
> Hi, I was wondering if it's possible to reprint a completed job?
> I'm on mac os.
> I've located my previously successful print job and issued the command to reprint the document, it says that the job has been restarted but nothing gets printed.
> 
> In the printers state menu its says stopped filter failed. I don't understand what that message means.
> 
> Here's a dump of the error log:
> 
> E [05/Oct/2017:12:34:10 +0100] [Job 303] Job stopped due to filter errors; please consult the error_log file for details.
> D [05/Oct/2017:12:34:10 +0100] [Job 303] The following messages were recorded from 11:33:40 to 12:34:10
> D [05/Oct/2017:12:34:10 +0100] [Job 303] Unloading...
> D [05/Oct/2017:12:34:10 +0100] [Job 303] Loading attributes...
> D [05/Oct/2017:12:34:10 +0100] [Job 303] Unloading...
> D [05/Oct/2017:12:34:10 +0100] [Job 303] Loading attributes...
> D [05/Oct/2017:12:34:10 +0100] [Job 303] Job restarted by user.
> D [05/Oct/2017:12:34:10 +0100] [Job 303] time-at-processing=1507203250
> D [05/Oct/2017:12:34:10 +0100] [Job 303] 2 filters for job:
> D [05/Oct/2017:12:34:10 +0100] [Job 303] commandtops (application/vnd.cups-command to printer/_143_239_81_77/application/postscript, cost 100)
> D [05/Oct/2017:12:34:10 +0100] [Job 303] - (printer/_143_239_81_77/application/postscript to printer/_143_239_81_77, cost 0)
> D [05/Oct/2017:12:34:10 +0100] [Job 303] job-sheets=none,none
> D [05/Oct/2017:12:34:10 +0100] [Job 303] argv[0]="_143_239_81_77"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] argv[1]="303"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] argv[2]="anonymous"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] argv[3]="Set Default Options"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] argv[4]="1"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] argv[5]="job-uuid=urn:uuid:e25b6e13-df42-3ec5-4ef8-339996a04748 job-originating-host-name=localhost date-time-at-creation= date-time-at-processing= time-at-creation=1501101827 time-at-processing=1507203250"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] argv[6]="/private/var/spool/cups/d00303-001"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[0]="<CFProcessPath>"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[1]="CUPS_CACHEDIR=/private/var/spool/cups/cache"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[2]="CUPS_DATADIR=/usr/share/cups"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[3]="CUPS_DOCROOT=/usr/share/doc/cups"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[4]="CUPS_FONTPATH=/usr/share/cups/fonts"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[5]="CUPS_REQUESTROOT=/private/var/spool/cups"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[6]="CUPS_SERVERBIN=/usr/libexec/cups"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[7]="CUPS_SERVERROOT=/private/etc/cups"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[8]="CUPS_STATEDIR=/private/etc/cups"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[9]="HOME=/private/var/spool/cups/tmp"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[10]="PATH=/usr/libexec/cups/filter:/usr/bin:/usr/sbin:/bin:/usr/bin"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[11]="SERVER_ADMIN=root@insight026.local"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[12]="SOFTWARE=CUPS/2.2.0"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[13]="TMPDIR=/private/var/spool/cups/tmp"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[14]="USER=root"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[15]="CUPS_MAX_MESSAGE=2047"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[16]="CUPS_SERVER=/private/var/run/cupsd"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[17]="CUPS_ENCRYPTION=IfRequested"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[18]="IPP_PORT=631"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[19]="CHARSET=utf-8"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[20]="LANG=en_US.UTF-8"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[21]="APPLE_LANGUAGE=en-US"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[22]="PPD=/private/etc/cups/ppd/_143_239_81_77.ppd"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[23]="RIP_MAX_CACHE=128m"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[24]="CONTENT_TYPE=application/vnd.cups-command"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[25]="DEVICE_URI=ipp://143.239.81.77/"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[26]="PRINTER_INFO=143.239.81.77"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[27]="PRINTER_LOCATION="
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[28]="PRINTER=_143_239_81_77"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[29]="PRINTER_STATE_REASONS=cups-ipp-conformance-failure-report,cups-ipp-missing-job-id"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[30]="CUPS_FILETYPE=document"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[31]="FINAL_CONTENT_TYPE=application/postscript"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] envp[32]="AUTH_I****"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] Started filter /usr/libexec/cups/filter/commandtops (PID 484)
> D [05/Oct/2017:12:34:10 +0100] [Job 303] Started backend /usr/libexec/cups/backend/ipp (PID 485)
> D [05/Oct/2017:12:34:10 +0100] [Job 303] Restarted by "user".
> D [05/Oct/2017:12:34:10 +0100] [Job 303] Sending stdin for job...
> D [05/Oct/2017:12:34:10 +0100] [Job 303] update_reasons(attr=0(), s=\"+connecting-to-device\")
> D [05/Oct/2017:12:34:10 +0100] [Job 303] op=\'+\', new_reasons=1, state_reasons=2
> D [05/Oct/2017:12:34:10 +0100] [Job 303] STATE: +connecting-to-device
> D [05/Oct/2017:12:34:10 +0100] [Job 303] Looking up \"143.239.81.77\"...
> D [05/Oct/2017:12:34:10 +0100] [Job 303] backendWaitLoop(snmp_fd=5, addr=0x7fe240f021e8, side_cb=0x1002fde8f)
> D [05/Oct/2017:12:34:10 +0100] [Job 303] Unable to auto-configure PostScript Printer - no bidirectional I/O available!
> D [05/Oct/2017:12:34:10 +0100] [Job 303] PID 484 (/usr/libexec/cups/filter/commandtops) stopped with status 1.
> D [05/Oct/2017:12:34:10 +0100] [Job 303] Hint: Try setting the LogLevel to "debug" to find out more.
> D [05/Oct/2017:12:34:10 +0100] [Job 303] PID 485 (/usr/libexec/cups/backend/ipp) exited with no errors.
> D [05/Oct/2017:12:34:10 +0100] [Job 303] End of messages
> D [05/Oct/2017:12:34:10 +0100] [Job 303] printer-state=3(idle)
> D [05/Oct/2017:12:34:10 +0100] [Job 303] printer-state-message="Filter failed"
> D [05/Oct/2017:12:34:10 +0100] [Job 303] printer-state-reasons=cups-ipp-conformance-failure-report,cups-ipp-missing-job-id
> 
> Especially this Unable to auto-configure PostScript Printer - no bidirectional I/O available! is something that concerns me because if I use the printers & scanners program interface from mac os, it prints normally without any issues.
> 
> Any hints?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

________________________
Michael Sweet

**Comment by kirk86** [comment]
> It *is* possible to reprint jobs as long as the documents associated with those jobs have been retained.  The default is for documents to be retained for 24 hours

Unfortunately I have deleted the file from the computer that's why I wanted to reprint it!

> So I guess the question is, what are you trying to do?

What I am trying to do is the following. I had a file which I successfully printed and after some time I deleted the file, now I'm trying to reprint that file because I forgot something written in the file. That's why I was trying to reprint in order to recreate the contents of the file.  Am I making myself clear?

Thanks!

**Comment by michaelrsweet** [comment]
Well, the job you tried to reprint wasn’t a regular document, it was a special job used to setup the defaults in the ppd file...

**Comment by kirk86** [comment]
> Well, the job you tried to reprint wasn’t a regular document, it was a special job used to setup the defaults in the ppd file...

Is there a way in which I can also differentiate between special document and regular jobs? Because in that particular printer I only printed one and only document that's why I assumed that it was the document, since the date corresponded to the date of the actual printing

**Comment by michaelrsweet** [comment]
The file format of the job (and often the job's title) will tell you.
