### ISSUE TITLE
question about Kerberos authentication when a client connects throuhg local socket on cups 1.7.5

### ISSUE THREAD

**Issue by frazhome** [apple/cups#5138]
Hello Mike,
this question is a little bit outdated for you because it is only a cups 1.7.5 issue.
on SLES 12 is is not possible to stop and start queues with samba in cause of this issue, which seems to be solved with the fix descripted at 
https://lists.cups.org/pipermail/cups-devel/2017-August/017043.html

could you please review the attached patch?

regards
Franz

**Comment by michaelrsweet** [comment]
This is PR #5101, which is still going through a lot of review...
