### ISSUE TITLE
ippserver is not installed

### ISSUE THREAD

**Issue by albert-astals-cid-kdab** [apple/cups#5141]
Seems that debian/ubuntu are installing the ippserver command line on their own, since looking at the Makefile it seems cups doesn't install it.

Is it on purpose? It seems there's indeed interest on having ippserver available without having to compile cups. Would you accept a patch to make ippserver installed?

**Comment by michaelrsweet** [comment]
I wish they wouldn’t - ippserver in CUPS is experimental sample code and not intended for any kind of regular use.

The ippserver program included with the separate [ippsample project](https://Istopwg.github.io/ippsample) is what you are looking for.
