### ISSUE TITLE
ERROR with TLS paket again

### ISSUE THREAD

**Issue by SiNGhKs** [apple/cups#5156]
Hello,
@michaelrsweet
 So now i install cups 2.2.5 on Ubuntu Server. With this tutorials :
https://opensource.apple.com/source/cups/cups-69/doc/fr/sam.html#CLIENT_AUTO

I have same error.
`[Client 34] Unable to encrypt connection: An unexpected TLS packet was received. ` when i do my lpr

Help please, really urgent.

Cordialy,

**Comment by michaelrsweet** [comment]
First, that document is completely out of date (14 years out of date to be exact)

Second, there really isn’t much we can do to help you with the cups on specific Linux distributions. They are responsible for providing a working CUPS installation, which includes all of the supporting libraries such as GNU TLS. It sounds like you probably need the fix from issue #5145 but the Ubuntu folks have not provided a fixed package.
