### ISSUE TITLE
No Airprint after upgrade to CUPS 2.2.6

### ISSUE THREAD

**Issue by excellapay** [apple/cups#5157]
My CUPS is not longer visible on AirPrint.  I installed upgraded to my CUPS from older version to 2.2.6.  I kept having some issues with the queue getting stuck. After the upgrade I had to remove printer and add back. The printer is connected to RaspberryPI 3 over USB Cable. 

I am able to print test pages to the printer via Web Interface. lpstat -p looks normal.
The issue is that it no longer is broadcasting as AirPrint queue. I don't see it MacLaptop as Bonjour either.

**Comment by michaelrsweet** [comment]
CUPS does not support sharing queues as AirPrint.
