### ISSUE TITLE
how to custom pagesize with borderless print

### ISSUE THREAD

**Issue by kssssssssss** [apple/cups#5158]
I hava a PDF,and I wanto print it with the A4 borderless size.
`lp -d HP_Officejet_Pro_6230   -o fit-to-page -o media=A4.Fullbleed  /Users/apple/Desktop/test.pdf`
it is not work.

But I print it with Adobe Reader application inner 'Print', it works.Here is my print setting.
<img width="750" alt="7a4480ec-f9eb-4fe6-a313-237c79e7561c" src="https://user-images.githubusercontent.com/3314016/32132699-ff87d80e-bb8d-11e7-9990-84ce3c668cb3.png">

**Comment by michaelrsweet** [comment]
Please attach the PPD file for this queue (in /etc/cups/ppd).

**Comment by kssssssssss** [comment]
[HP_Officejet_Pro_6230.ppd.zip](https://github.com/apple/cups/files/1425814/HP_Officejet_Pro_6230.ppd.zip)

**Comment by michaelrsweet** [comment]
Closing for now; if you have additional information I can re-open as needed.
