### ISSUE TITLE
Adobe Reader comments not getting printed out?

### ISSUE THREAD

**Issue by sw7tch** [apple/cups#5160]
Hi all,

I'm not sure if this is the best place to ask? Sorry in advance if it is not.

I've set up a Raspberry Pi to print some drawings that are in pdf format with a shell script using the 'lp' command. To make sure that the drawings don't get clipped off the side of the page I added the option '-o fit-to-page'

Some of these pdf's have comments added to them using adobe reader. If I use the '-o fit-to-page' option the comments do not get printed out but if I don't add the '-o fit-to-page' option the comments do get printed out?

Is there any other way to make sure that the printed pdf will fit to the page and that the comments will get printed out too?

Thanks for your help.

**Comment by michaelrsweet** [comment]
All I can guess is that the crop box is not getting updated by Adobe Reader to reflect the comments.

However, the PDF filters are part of the [cups-filters project](https://github.com/OpenPrinting/cups-filters) so you'll need to contact them for this issue...

**Comment by sw7tch** [comment]
Thanks @michaelrsweet 
:)
