### ISSUE TITLE
lp ignores ~/.cups/lpoptions

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5163]
Thiis bug got reported to Ubuntu:

https://bugs.launchpad.net/ubuntu/+source/cups/+bug/1729910

Original description:
```
LP ignores the settings defined in ~/cups/lpoptions in artful

Steps to reproduce:

1) Define a default print in lpoptions that differs from one in /etc/cups/printers.conf
2) Execute lpstat -d
3) Above will output default defined in prints.conf instead of ~/cups/lpoptions
```
The problem happens in released Ubuntu 17.10 which uses CUPS 2.2.4.

**Comment by michaelrsweet** [comment]
@tillkamppeter Have you tested 2.2.6 to see if the problem was already fixed?

**Comment by tillkamppeter** [comment]
Not yet, I have only forwarded the bug report now.

**Comment by tillkamppeter** [comment]
Update to 2.2.6 indeed fixes the problem. Thank you very much.

Can you tell me which change in the GIT actually fixed it? So I could backport this patch to the CUPS in Ubuntu 17.10.

**Comment by michaelrsweet** [comment]
The fix will be in cups/dest.c; I *think* it was c536b6c583abd9ea1b750f15e887b313ed7ad951 but I'm not sure.

**Comment by tillkamppeter** [comment]
Thank you very much. Reported back in the original bug report.
