### ISSUE TITLE
job's user name is displayed as "{job_originating_user_name}" when showing completed print jobs

### ISSUE THREAD

**Issue by sjvudp** [apple/cups#5164]
See https://bugzilla.opensuse.org/show_bug.cgi?id=1066203 for the original bug report.
It seems there's a problem with expanding the variable job_originating_user_name in `https://localhost:631/printers/PRINTER?which_jobs=completed`.
I found this in the jobs template (other languages are similar):
`de/jobs.tmpl:<TD>{?job_originating_user_name=?Zurückbehalten:{job_originating_user_name}}&nbsp;</TD>`

**Comment by michaelrsweet** [comment]
The current template replaces the empty user name with "withheld" (or the localized equivalent) when the (default) JobPrivateAccess/Values settings are in place. Basically, since the job listing is (by default) not authenticated we don't expose potentially private information in the web page.

This was fixed in 2.0...

**Comment by michaelrsweet** [comment]
"man cupsd.conf" and look at the documentation on JobPrivateAccess and JobPrivateValues. The following will allow all users to see the private values of all jobs:

    JobPrivateAccess all

**Comment by sjvudp** [comment]
Does "_Basically, since the job listing is (by default) not authenticated_" mean that even though authenticated as admin, I'll never see the variables expanded?

**Comment by sjvudp** [comment]
My settings are:
  ```
JobPrivateAccess default
JobPrivateValues default
SubscriptionPrivateAccess default
SubscriptionPrivateValues default
```
and the manual says: "_The "default" access list is "@OWNER @SYSTEM"._"
So when authenticated as root, shouldn't that be "@SYSTEM"?

**Comment by michaelrsweet** [comment]
If you are authenticated as root, then you'll see all of the private values. But by default the web interface showing the jobs is NOT authenticated, so even if you authenticate for /admin, the same credentials are not automatically supplied for /printers or /jobs.

**Comment by sjvudp** [comment]
Is there an URI for the older versions that force authentication for the job display?

**Comment by michaelrsweet** [comment]
? No version of CUPS has ever authenticated the job display by default.

You can add the following to your cupsd.conf file to get /jobs to be authenticated on the web interface:

```
<Location /jobs>
  Order deny,allow
  <Limit GET HEAD>
    Require valid-user
  </Limit>
</Location>
```
