### ISSUE TITLE
print text file fails with "no usable font available"

### ISSUE THREAD

**Issue by juanitotc** [apple/cups#5165]
Using cups-2.2.4 and hplip-3.17.10 compiled from source on an RPi3.

I can print a test page with the cups browser interface or "hp-testpage", but cannot print a text file.

There are fonts available, is this a locale or mime error perhaps?

The cups error logs shows:

D No viable font found
W Ignored bad font \"monospace\"
E No usable font available
...
D OUTFORMAT=\"(null)\", so output format will be CUPS/PWG Raster
D PID 3077 (/usr/local/lib/cups/filter/texttopdf) stopped with status 1
...
D PID 3079 (/usr/local/lib/cups/filter/gstoraster) stopped with status 1.
D prnt/hpcups/HPCupsFilter.cpp 565: cupsRasterOpen failed, fd = 0
D PID 3081 (/usr/local/lib/cups/backend/socket) exited with no errors.
D PID 3080 (/usr/local/lib/cups/filter/hpcups) stopped with status 1.
...
E Job stopped due to filter errors; please consult the error_log file for details.
...
D printer-state-message="Can't detect file type"

**Comment by juanitotc** [comment]
Ah - I forgot to mention that I can print *ps and *pdf files

**Comment by michaelrsweet** [comment]
Please report this problem to the [cups-filters project](https://github.com/OpenPrinting/cups-filters), as CUPS does not provide the text filter you are using...
