### ISSUE TITLE
"Satisfy any"  + auth + JobPrivateAccess

### ISSUE THREAD

**Issue by kenshin33** [apple/cups#5169]
I'm trying to force auth from anywhere except localhost on /. The snippet bellow works fines except for one thing JobPrivateAccess. Usernames and documents names are not shown  althout  logs show that 
cupsdIsAuthorized: username is not empty and is valid !

lpstat works fine but the web interface doesn't.
If I remove satisfy any it works but  printing directly from localhost fails. 

    <Location />
      AuthType Default
      Require valid-user
      Order allow,deny
      Allow  localhost
      deny all
      satisfy any
    </Location>

**Comment by michaelrsweet** [comment]
OK, so first change the Order to "deny,allow", or drop the "deny all".

Second, what is your JobPrivateAccess directive set to?

**Comment by kenshin33** [comment]
JobPrivateAccess  is set to default as is JobPrivateValues. the default auth is Negotiate and the default policy is authenticated 

I didn;t mention it but the cups instance is supposed to be a remote print server. The goal of this was to show the Private values only to those who are authenticated on the web interface.
As I said lpq and lpstat  (with -h remote) works. the web interface on the other hand doesn't (only if I remove the satisfy any)

**Comment by michaelrsweet** [comment]
Are you accessing the web interface locally (http://localhost:631) or remotely?

Have you made the change to the Order directive or dropped the "deny all"?

**Comment by kenshin33** [comment]
remotely  (https://fqdn:631/.
I changed the order, but still the same : webinterface no info  lpstat works as it is supposed (shows ne the info if @SYSTEM or @OWNER  unknown otherwise).

**Comment by michaelrsweet** [comment]
Hmm, tracking this for CUPS 2.3...

**Comment by michaelrsweet** [comment]
@kenshin33 Do you get an authentication prompt when you access the web interface? If so, what user are you authenticating as?

**Comment by kenshin33** [comment]
no authentication prompt since I'm using 'Negotiate' (KERBEROS)

**Comment by michaelrsweet** [comment]
... but then the browser is most likely not providing anything since the request is not authenticated.

With Negotiate the browser can force a Kerberos/AD login as needed, or show an "unauthorized" page if it doesn't implement that UI.

Since I cannot reproduce with Basic, I am assuming this is a bug in the browser, not in CUPS... Closing.
