### ISSUE TITLE
Use translating platform

### ISSUE THREAD

**Issue by raspi** [apple/cups#5171]
It would be faster and easier to contribute localisations if it was moved to proper platform such as:

* translatewiki
* transifex
* launchpad
* or other (hosted pootle?)

This way `.po` files could be pushed/committed from that platform and also tested/verified automatically when committing to this repository.

Are there any plans for this?

**Comment by michaelrsweet** [comment]
We were not aware of any of these services - we've relied on contributed localizations for the past 15 years...

Will investigate...

**Comment by michaelrsweet** [comment]
OK, so several of these services rely on write access to the CUPS repository, which is a non-starter for various reasons. I tried using Zanata for a subset of strings (basically all of the IPP registered strings) - over the last month I have *0* translations done. Zip. Nada.

So, for the present I'm sorry but it looks like the current translation platforms are incompatible with the CUPS project.

**Comment by yarons** [comment]
Would you be willing to consider Weblate? It's possible to create a localization repository which will be separate from the main repo, what do you think?

**Comment by michaelrsweet** [comment]
@yarons Not sure whether they would accept CUPS as a "libre" project with almost 4000 strings...

**Comment by yarons** [comment]
Allow me to introduce you to Godot Engine, the app itself has 2643 strings while the documentation has 12987 strings so I'm guessing 4000 is not such a burden :)

Reference:
https://hosted.weblate.org/projects/godot-engine/godot/he/ - App
https://hosted.weblate.org/projects/godot-engine/godot-docs/he/ - Docs
