### ISSUE TITLE
lpr: Unsupported document-format "application/vnd.cups-banner".

### ISSUE THREAD

**Issue by titusece** [apple/cups#5173]
Hello,
I have compiled the cups-branch 1.7 version on my ARM Linux board.
And able to successfully add my network printer but not able to print anything.

Can you please help me to solve this issue ?

```
linux-host$ lpr -P Brother_HL-L2340D_series  /usr/share/cups/data/testprint
lpr: Unsupported document-format "application/vnd.cups-banner".
```

**Comment by michaelrsweet** [comment]
You also need to install [cups-filters](https://github.com/OpenPrinting/cups-filters).
