### ISSUE TITLE
Cups doesn't clear error states.

### ISSUE THREAD

**Issue by marklist** [apple/cups#5178]
Whenever my hp LaserJetP110w on an Ubuntu 16.04 system gets into some kind of error state ("out of paper" or "unplugged or turned off" it doesn't clear when the problem is fixed like adding paper or plugging it in or turning it on.  

I've tried everything I can think of.  Rebooting with it disconnected or turned off and then reconnecting or turning it on.  A hard reboot with the previously mentioned variations.  Deleting and reinstalling the printers.  

After a while, it seems to get better by itself but this doesn't help me. when I need to print something now.  

It seems as if it just isn't rechecking error conditions.  

Here's the relevant portion of /etc/cups/printers.conf

```
<DefaultPrinter HP-P1102w>
UUID urn:uuid:ca61377d-a7af-3923-60d1-fbc6aad91745
Info Hewlett-Packard HP LaserJet Professional P1102w
Location In Desk
MakeModel HP LaserJet Pro P1102w Foomatic/foo2zjs-z2 (recommended)
DeviceURI hp:/usb/HP_LaserJet_Professional_P1102w?serial=000000000Q942G48PR1a
State Stopped
StateMessage Unplugged or turned off
StateTime 1510276568
ConfigTime 1477777402
Reason paused
Type 8425476
Accepting Yes
Shared Yes
JobSheets none none
QuotaPeriod 0
PageLimit 0
KLimit 0
OpPolicy default
ErrorPolicy retry-job
Option job-cancel-after 10800
Option media 0
Option output-bin 0
Option print-color-mode monochrome
Option print-quality 5
</DefaultPrinter>
```

How do I force it to do so?  Or better yet can someone fix it?

**Comment by michaelrsweet** [comment]
You need to contact the hplip project to get support for this issue - the driver and backend are responsible for state management, and they are clearly not doing their job... :/
