### ISSUE TITLE
Add Samsung SCX-3400

### ISSUE THREAD

**Issue by mikhailnov** [apple/cups#5183]
Hello, Samsung SCX-3400 works perfectly with the CUPS driver for SCX-3200 on Linux (Ubuntu 16.04), but that driver is not suggested automatically. 
If you need printer information such as IDs, I can provide.

**Comment by michaelrsweet** [comment]
We don't provide drivers for this printer, you probably want to report this to the [cups-filters](https://github.com/OpenPrinting/cups-filters) project...

**Comment by mikhailnov** [comment]
ok
