### ISSUE TITLE
local root not access to include printer

### ISSUE THREAD

**Issue by infomatico** [apple/cups#5185]
Hello Michael,

I installed the cups via source and am not getting administrative access to include printers. At the moment that is requested the login and password I put the login as root and the password of the root, but it does not access.

I created the group lpadmin, but I do not know if in the creation of it is configured something regarding the cups.
`groupadd -g 19 lpadmin`

and I put the root user into the lpadmin group
`usermod -a -G lpadmin root`

**cupsd.conf**

> SystemGroup lpadmin
> LogLevel warn
> PageLogFormat
> Listen 631
> Listen /var/run/cups/cups.sock
> Browsing On
> BrowseLocalProtocols
> DefaultAuthType Basic
> WebInterface Yes
> <Location />
>   Allow From 127.0.0.1
>   Allow From 172.16.*
>   Order allow,deny
> </Location>
> <Location /admin>
>   Allow From 127.0.0.1
>   Allow From 172.16.*
>   Allow 172.16.11.11
>   Order allow,deny
> </Location>
> <Location /admin/conf>
>   AuthType Default
>   Require user @SYSTEM
>   Order allow,deny
> </Location>
> <Location /admin/log>
>   AuthType Default
>   Require user @SYSTEM
>   Order allow,deny
> </Location>

Any idea about the problem?

**Comment by infomatico** [comment]
Michael,

I fixed the "bug"!!!

The file **_cups_** in **_/etc/pam.d/_** has a invalid entry after installation from source.

In the file have:

> auth    required        pam_unknow.so nodelay
> account required        pam_unknow.so

and should be:

> auth    required        pam_unix.so nodelay
> account required        pam_unix.so

Correct?

**Comment by michaelrsweet** [comment]
Sounds like the PAM module check isn't working. Where are your PAM modules installed on your system?

**Comment by michaelrsweet** [comment]
(checking on current Ubuntu, it looks like things have moved to /lib/x86_64-linux-gnu/security.

**Comment by infomatico** [comment]
@michaelrsweet 

> Sounds like the PAM module check isn't working. Where are your PAM modules installed on your system?

/var/lib/pam

> (Checking on current Ubuntu, it looks like things have moved to /lib/x86_64-linux-gnu/security.)

I installed cups in debian 9.2

**Comment by michaelrsweet** [comment]
[master ac05c6306] Fix PAM module detection and add support for the "common-*" includes used on Ubuntu (Issue #5185)
