### ISSUE TITLE
Typo in latest commit to 'scheduler/ipp.c'

### ISSUE THREAD

**Issue by KurtPfeifle** [apple/cups#5190]
The last commit introduced a typo (*`'reqeusting-user-name'`*) in the new code:

```c
attr = ippAddString(con->request, IPP_TAG_JOB, IPP_TAG_NAME, "reqeusting-user-name", NULL, "anonymous");
```

[Line #L1628 of `scheduler/ipp.c`](https://github.com/apple/cups/blob/6d14c1bbc690ff302842e6a65aeb4685ef3796c2/scheduler/ipp.c#L1628)

**Comment by michaelrsweet** [comment]
[master 0e4593c0b] Fix typo (Issue #5190)

(push pending)
