### ISSUE TITLE
Cups automatic search shows my Epson printer as an HP printer.

### ISSUE THREAD

**Issue by Lloyd-H1** [apple/cups#5191]
In going through the printer setup using Knoppix 8.1, CUPS setup shows my Epson 837 printer/scanner as an HP printer. It did not give me the option of inserting the printer or the driver for it. I did not try to go further with the setup.

I am using Knoppix from a memory stick. The system recognizes the rest of my attached hardware. Only the Epson equipment seems to be a problem. I have the Epson 837 printer/scanner attached, and also the the Epson V600 print/negative scanner. The system does not recognize the V600 scanner at all.

**Comment by michaelrsweet** [comment]
This is something you'll need to ask your Linux distribution about - we don't provide scanner support in CUPS, nor do we provide specific printer drivers that would cause this sort of problem.
