### ISSUE TITLE
cupsd doesn't recognize some FQDNs as valid hosts

### ISSUE THREAD

**Issue by zdohnal** [apple/cups#5193]
Hi Mike,

I was testing following CUPS configuration - server machine, which has network printer and USB printer connected to it, and client machine, where I want to see both remote cups queues from server. Server has a hostname print.server.lan, I have cups-browsed daemon running and 'BrowsePoll print.server.lan' in /etc/cups/cups-browsed.conf, but I cannot get print queues because of errors:

[Client 2392] Request from "192.168.2.105" using invalid Host: field "print.server.lan:631".

These errors are created because valid_host() function returns 0, so it seems cupsd cannot recognize that hostname (it is defined dns name and I can ping it from other machines). When I use 'BrowsePoll print', I can see print queues on client again.
That seems like issue (I think cupsd should accept such FQDN) or do I configure something wrong? I have cups-2.2.2 on server and cups-2.2.4+cups-filters-1.16.1 on client.

**Comment by michaelrsweet** [comment]
"man cupsd.conf"

You need to use the ServerAlias directive to tell cupsd about the other host names the local system is using, since it is unable to find them itself.

**Comment by zdohnal** [comment]
Hmm, that's interesting - I get it from code that ServerAlias can be an option to solve it, but it worked in the past without sweat and ServerAlias... maybe a change in dns resolver?

**Comment by michaelrsweet** [comment]
That would be my guess - the auto-configuration code in cupsd has its limitations... :/

**Comment by zdohnal** [comment]
Ok, thank you, Mike!
