### ISSUE TITLE
Broken queue for HP LaserJet 4 Plus in Mac OS Sierra

### ISSUE THREAD

**Issue by sparky672** [apple/cups#5200]
**Operating System:**

Mac OS Sierra 10.12.6 (16G1114)

**Printer Software:**

Driver Version: 10.4
PPD: HP LaserJet 4 Plus v2013.111
PPD File Version: 19.13
PostScript Version: (2013.111) 0
CUPS Version: 2.2.0 (cups-450)

The printer is on my LAN with a static IP address and a JetDirect card.

**Problem Description:**

Ever since upgrading to Sierra, the queue for my HP LaserJet 4 Plus is not working properly.  I can print a single job, the first job in the queue, but subsequent print jobs simply vanish from the queue whenever the printer is "busy".  The next job goes into the queue window saying *"Ready to Print"*.  Then the pending job is finishing up and says *"Waiting for printer to finish"* until it disappears, and the next job goes to the top and says "Printing", but only for a second... it very quickly vanishes... 

[Watch Screen Capture Movie](https://streamable.com/s93nf)

It never makes it to the printer (no busy light, no blinking), it never prints, and there are no log entries or errors; it's as if this print job never existed.  If there are x number of jobs waiting, they'll each quickly fail in the same manner until the printer status changes back to "ready", and then if there are any jobs left, only the top one will print.

There is nothing wrong with the printer as another Mac running 10.5.8 can queue up as many jobs as desired and they all print.  This other Mac is using the same PPD version "HP LaserJet 4 Plus v2013.111" and Driver version 10.4.  My previous OS, Yosemite never had any trouble printing all jobs in the queue for this same printer & driver setup.

I've deleted and reinstalled the printer.  [I've reset the printing system as per Apple procedure](https://support.apple.com/kb/PH25565?viewlocale=en_US&locale=en_US).  I've also tried a different HP JetDirect card.   None of this has resolved the issue.

I realize this printer is very old, however, it's a little workhorse and this model is on [Apple's official list of supported printers](https://support.apple.com/en-us/HT201465#HP).  The actual printing works perfectly well, and only the queue is not working properly.

On the same OS, I also have an old HP Color LaserJet 5/5M printer on the network and its queue is working properly with all computers, FWIW.

**Comment by michaelrsweet** [comment]
Please file macOS bugs with Apple directly (bugreport.apple.com) as CUPS does not include the driver you are using.
