### ISSUE TITLE
Sharing printers as raw que (question)

### ISSUE THREAD

**Issue by Kalle72** [apple/cups#5201]
Hello,

I have installed a printer (LaserJet2100) locally and wish to share it on my network. The problem is:

Locally I use the printer with the "HP LaserJet 2100 hpijs" driver, but from other machines (Windows with it's own drivers) on the network I will use the printer as a "raw que" 

Therefore: Is one of the following solutions possible and if, how?
1) Install a second "raw que" for it and **hide** this raw que locally from the printer dialogue
2) Tell cups that all "jobs" which comes from network should be send "raw" to the printer. 

Thanks in advance
Kalle

**Comment by michaelrsweet** [comment]
Please ask questions on the [CUPS user list](https://lists.cups.org/mailman/listinfo/cups) first. The issue tracker is for tracking bugs/software changes.

There is a third option of adding MIME typing rules that match the application/vnd.cups-raw for jobs coming from the Windows system - you'll see some existing rules for PCL printing already in the standard mime.types file.
