### ISSUE TITLE
More precise firewall documentation (preferaby with use cases)

### ISSUE THREAD

**Issue by jsmeix** [apple/cups#5202]
This documentation enhancement request is a follow up of
https://github.com/apple/cups/issues/5192#issuecomment-351955407
for
https://github.com/apple/cups/blob/master/doc/help/firewalls.html

I think the current CUPS firewall documentation
should be more precise if on the CUPS server machine a port
must be open for incoming or outgoing network traffic (or both).

Additionally documentation of some usual use cases
(e.g. using a network printer via TCP socket plus SNMP
versus using a modern IPP network printer only via IPP
or making a CUPS server fully accessible in a trusted network)
could help a lot so that firewall administrators can actually
do the right firewall settings in their particular environments.

**Comment by michaelrsweet** [comment]
We necessarily need to be as generic as possible as every OS (and Linux distribution) has different ways of setting up a firewall.

**Comment by michaelrsweet** [comment]
[master 3f76968f9] Expand a bit on the firewall documentation (Issue #5202)

Let me know what you think...

(but we won't add iptables examples or other firewall-specific documentation)

**Comment by jsmeix** [comment]
Much better now!

But at least for me the wording "outgoing port" still looks confusing, cf.
https://github.com/apple/cups/issues/5192#issuecomment-352479636
Perhaps "outgoing port" might be replaced by "destination port"
or even by "destination port for outgoing network traffic"
to avoid possible misunderstanding?

I do fully agree to not provide any firewall-specific documentation.
Only generic documentation about what ports are used and how.
Firewall-specific documentation is too much a snakepit
that basically calls for user complaints when things doen't work
and in general it is a potential security risk to provide
firewall-specific examples.

**Comment by michaelrsweet** [comment]
[master 77401306b] Reword firewall docs - "outgoing ports" -> "port for outgoing network traffic".

**Comment by jsmeix** [comment]
Only a possibly reasonable further change request
for the upcoming CUPS 2.3 series:

Because not any firewall-specific documentation should be
provided I wonder if then the file name 'firewalls.html'
is really the right one.

I think what actually is provided is generic documentation
about CUPS-related network traffic so that the file name
should be accordingly to avoid false expectations what
is actually documented therein.

Of course with that documentation firewall administrators
can set up their particular firewalls as they need it in their
particular environments - but that is (strictlky speaking)
only a (intended) side effect of what is actually documented.
