### ISSUE TITLE
OSX  10.13 (may be bellow) remote IPP printing and authentication (Negotiate) 

### ISSUE THREAD

**Issue by kenshin33** [apple/cups#5203]
Hi, 
I set up a cups server to use Kerberos to authenticate users.
Windows clients have no problem  printing, Linux clients use  either /etc/cups/client.conf or cups-browsed and have no problem printing.
the above holds wether the client is joined to the domain or not.

OSX on the other hand seams problematic.

since client.conf is no longer supported  setting CUPS_SERVER/CUPS_USER and  acquiring a kerberos ticket (kinit) seams to be the way to go. and it works  for all apps except Preview :-/

I played around with the idea of adding a local queue like so:
lpadmin -p print_queue -E -v ipps://server/printers/printer_queue -m raw

the printer is addeed but the minutes I try to print it gets stuck in 'hold for authentication', it doesn't seam to accept any username/password combination. 

and on the server I don't see any attempt to authentication  (running with debug2).
I'm guessing that it is trying to authenticate on the client  ???

Just modified the policy for one of the printers to use  Basic  I get thins if I try to print for my macbook
It asks for a username/password pair (as before) I provide it with "testuser" and a good password: 

D [19/Dec/2017:21:45:49 -0500] [Client 245] Authorized as "testuser" using Basic.
...
D [19/Dec/2017:21:45:49 -0500] cupsdIsAuthorized: username="testuser"
E [19/Dec/2017:21:45:49 -0500] Authorized using Negotiate, expected Basic.

**Comment by michaelrsweet** [comment]
Please report this issue using the form at bugreport.apple.com - this issue tracker is just for the core CUPS software and not for the whole printing stack on macOS.

**Comment by kenshin33** [comment]
Sorry about that. I did report the preview at bugreport.apple.com, thanks for the tip.

Turns out that the cups-browsed comment above wasn't true. Under that light a theme is forming
there's no other way to authenticate to a remote cups server using anything other than basic (to be tested)  if there is a local queue to a printer on said remote server ???

i.e:
the Only way I can authenticate remote users using their KERBEROS tickets is ask them to  set CUPS_SERVER or ServerName in /etc/cups/client.conf ???  

(here I'm talking about linux/OSX clients, windows clients have no problem at all)

**Comment by michaelrsweet** [comment]
No, as long as the queue is configured properly the IPP backend will run as the printing user on the client machine and provide the necessary Kerberos credentials to the server.

**Comment by kenshin33** [comment]
That is precisely what I was hoping for. but I can't seem to find how. | I've seem people talk about auth-info-required=negotiate  ? is that it ? I tried it and it  didn;t change the outcome.
OSX keeps asking for a username and a password.
Linux asks for a password,
meanwhile on the server I see that it has refused the Create-Job action, and it asks for authentication  (D [20/Dec/2017:20:36:02 -0500] [Client 17] WWW-Authenticate: Negotiate) then the client drops the connection and does nothing else.

D [20/Dec/2017:20:36:02 -0500] [Client 17] WWW-Authenticate: Negotiate
d [20/Dec/2017:20:36:02 -0500] select_timeout: JobHistoryUpdate=1513884602
d [20/Dec/2017:20:36:02 -0500] [Client 17] cupsdReadClient: error=0, used=0, state=HTTP_STATE_WAITING, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=0, request=0x558dd9581ff0(IPP_STATE_DATA), file=-1
D [20/Dec/2017:20:36:02 -0500] [Client 17] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
D [20/Dec/2017:20:36:02 -0500] [Client 17] Closing connection.
D [20/Dec/2017:20:36:02 -0500] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
d [20/Dec/2017:20:36:02 -0500] cupsdAddSelect(fd=26, read_cb=0x558dd89bf370, write_cb=(nil), data=0x558dd95778c0)
D [20/Dec/2017:20:36:02 -0500] [Client 17] Waiting for socket close.
d [20/Dec/2017:20:36:02 -0500] select_timeout: JobHistoryUpdate=1513884602
d [20/Dec/2017:20:36:02 -0500] [Client 17] cupsdReadClient: error=32, used=0, state=HTTP_STATE_WAITING, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=0, request=0x558dd9581ff0(IPP_STATE_DATA), file=-1
D [20/Dec/2017:20:36:02 -0500] [Client 17] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
D [20/Dec/2017:20:36:02 -0500] [Client 17] Closing connection.


Setting the CUP_SERVER works flawlessly  (with lp* and with GUI), with the exception of Preview.app and losing any local printer.

**Comment by michaelrsweet** [comment]
CUPS_SERVER has not been supported on macOS for a very long time, and will not work from any sandboxed application that doesn’t have a network access entitlement.

Using auth-info-required with a share printer queue is the correct solution -please work with Apple support to get that configured properly.
