### ISSUE TITLE
CUPS and Mac OS X bluetooth connection

### ISSUE THREAD

**Issue by gqbgqb** [apple/cups#5204]
Hi,

I'm trying out to connect my printer using bluetooth in Mac OS X Sierra/CUPS. But I wasn't able to establish connection or discover it from CUPS. I can pair but couldn't add the printer, my guess it Mac OS/device issue. 

However in Linux, I can use LPD and enter "bluetooth://<device mac address>" to add the printer and I was able print. Maybe it's because of the blue-cupz component. This method doesn't work in Mac OS X I get a "filter failed" then "Connection failed. Unknown error".

Is there any way to make it the same with Linux (Ubuntu)? Do I need to modify the printer driver (filter) or install another component to make it work? I hope someone can point me in the right direction.

Thanks and Best Regards,
Glenn

**Comment by michaelrsweet** [comment]
macOS support requests should be submitted through bugreport.apple.com, as the CUPS does *not* provide the bluetooth backend on any platform...

I believe that you must pair the Bluetooth printer with the Mac before it will show up in the Add Printer window - that can be done through the Bluetooth system preferences. After pairing, it *should* show up in the Add Printer window, but if it doesn't then you need to contact Apple for support.
