### ISSUE TITLE
Human-readable strings in auto-generated PPDs for driverless printing inconsistent

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5205]
First issue reported on my first tests with CUPS 2.3.x (2.3b1):

If a temporary queue for a driverless printer is created (or `lpadmin-m everywhere` is used) the resulting auto-created PPD file (by `_ppdCreateFromIPP()` function in `cups/ppd-cache.c`) has some inconsistencies in the human-readable strings:
1. The "PageSize"/"PageRegion" options do not have human-readable strings for the choices at all (but there are appropriate strings in the `cups_XX.po` files).
2. The "MediaType" option has only correct human-readable strings for the choices if LC_ALL is set to a CUPS-supported (by `cups_XX.po` file) language but not English (`en` or `en_US` or `C`). On a system set to English the human-readable choice names are even more cryptic than the machine-readable ones.
3. Only a part of the option and choice names are translated to the selected locale language, like for example "cupsPrintQuality" and its 3 standard choices. "PageSize" for example is not translated at all.
For obtaining these results and for generating the attached files I have run the following commands:
```
$ driverless
ipp://localhost:60000/ipp/print
$ ipptool --ippserver ~/HP-DeskJet_2540-ipp-attr-ippserver.txt ipp://localhost:60000/ipp/print get-printer-attributes.test
$ lpadmin -p HP-DeskJet_2540-everywhere-en -E -v ipp://localhost:60000/ipp/print -m everywhere
$ LC_ALL=de lpadmin -p HP-DeskJet_2540-everywhere-de -E -v ipp://localhost:60000/ipp/print -m everywhere
```
The printer hardware is an HP DeskJet 2540 connected via USB and accessed via IPP-over-USB using [ippusbxd](https://github.com/OpenPrinting/ippusbxd), therefore the "localhost" URI.

Here are the files resulting from the commands above:
IPP attributes of the printer, ready to emulate this printer with `ippserver`:
[HP-DeskJet_2540-ipp-attr-ippserver.txt](https://github.com/apple/cups/files/1576683/HP-DeskJet_2540-ipp-attr-ippserver.txt)
English PPD file:
[HP-DeskJet_2540-everywhere-en.ppd.txt](https://github.com/apple/cups/files/1576688/HP-DeskJet_2540-everywhere-en.ppd.txt)
German PPD file:
[HP-DeskJet_2540-everywhere-de.ppd.txt](https://github.com/apple/cups/files/1576691/HP-DeskJet_2540-everywhere-de.ppd.txt)

**Comment by michaelrsweet** [comment]
Strange, it shouldn't matter which language is used. Will investigate after the holiday break.

**Comment by michaelrsweet** [comment]
The reason is because English is not an installed locale right now...  Fixing...

**Comment by michaelrsweet** [comment]
[master a8b28f184] IPP Everywhere PPDs were not localized to English (Issue #5205)

**Comment by tillkamppeter** [comment]
I have tested your fix (by simply copying the locale/cups.pot file of the CUPS source to /usr/share/cups/locale/en/cups_en.po) and it fixes point (2) of my original posting. Point (1) and (3) still need to get fixed.

**Comment by michaelrsweet** [comment]
@tillkamppeter localization of page sizes never uses the text from the PPD. Similarly, print quality is always just one of three values and shouldn’t be displaying the strings from the PPD... not “fixing” those...
