### ISSUE TITLE
Cups-2.2.5 display printing complete, but actually nothing is done.

### ISSUE THREAD

**Issue by Alan-GitHub** [apple/cups#5207]
1. I printed a very much simple file (have only one line text content "newdomain Home"). "lpstat -t" and GUI can see the job had finished. but actually nothing is done. 

2. Additinal, usb printer would disappear in "lpinfo -v" result after start a print job, debug file "cups-2.2.5\backend\usb-unix.c" know the cause printer disappear is that the device is busy... 

Console command result as below:
*********************************************************************
[3384:RG]# lpinfo -v
network ipp
network lpd
direct usb://HP/Deskjet%205520%20series?serial=CN36A1665W05SW
network http
network socket
network beh
file cups-brf:/
serial serial:/dev/ttyS0?baud=115200
[3384:RG]# 
[3384:RG]# lp /var/resolv.conf 
request id is HP_Deskjet_5520_series-6 (1 file(s))
[3384:RG]# 
[3384:RG]# lpstat -t
scheduler is running
system default destination: HP_Deskjet_5520_series
device for HP_Deskjet_5520_series: usb://HP/Deskjet%205520%20series?serial=CN36A1665W05SW
HP_Deskjet_5520_series accepting requests since Thu Jan  1 00:46:11 1970
printer HP_Deskjet_5520_series now printing HP_Deskjet_5520_series-6.  enabled since Thu Jan  1 00:46:11 1970
        Printing page 1, 42% complete.
HP_Deskjet_5520_series-6 admin             1024   Thu Jan  1 00:46:11 1970
[3384:RG]# 
[3384:RG]# lpstat -t
scheduler is running
system default destination: HP_Deskjet_5520_series
device for HP_Deskjet_5520_series: usb://HP/Deskjet%205520%20series?serial=CN36A1665W05SW
HP_Deskjet_5520_series accepting requests since Thu Jan  1 00:46:11 1970
printer HP_Deskjet_5520_series now printing HP_Deskjet_5520_series-6.  enabled since Thu Jan  1 00:46:11 1970
        Printing page 1, 72% complete.
HP_Deskjet_5520_series-6 admin             1024   Thu Jan  1 00:46:11 1970
[3384:RG]# 
[3384:RG]# 
[3384:RG]# lpstat -t
scheduler is running
system default destination: HP_Deskjet_5520_series
device for HP_Deskjet_5520_series: usb://HP/Deskjet%205520%20series?serial=CN36A1665W05SW
HP_Deskjet_5520_series accepting requests since Thu Jan  1 00:46:11 1970
printer HP_Deskjet_5520_series now printing HP_Deskjet_5520_series-6.  enabled since Thu Jan  1 00:46:11 1970
        Finished page 1.
HP_Deskjet_5520_series-6 admin             1024   Thu Jan  1 00:46:11 1970
[3384:RG]# 
[3384:RG]# cat /var/resolv.conf   
newdomain Home
[3384:RG]# 
[3384:RG]# lpinfo -v            
network lpd
network ipp
network http
network socket
network beh
file cups-brf:/
serial serial:/dev/ttyS0?baud=115200
[3384:RG]# 
[3384:RG]# 
*********************************************************************

Is it driver result to that issue? but i don't know how to debug the driver...
The driver my printer's is hplip-3.17.8.

Do you have any idea? 

I can't find any useful info in file (/var/log/cups/error_log), so i haven't post it. i can if you need.

Thanks.
Alan

**Comment by tillkamppeter** [comment]
Did you also report [this bug on cups-filters](https://bugs.linuxfoundation.org/show_bug.cgi?id=1418)?

**Comment by Alan-GitHub** [comment]
@tillkamppeter 

Yes, you are right. That bug is reported by me.

**Comment by Alan-GitHub** [comment]
I'm sorry, there is a mistake, my driver of printer is hplip-3.11.7, not hplip-3.17.8.

Br,
Alan

**Comment by michaelrsweet** [comment]
I don't see anything here that is obviously a CUPS issue; what operating system/Linux distribution are you using? And did you compile CUPS from source or are you using an existing package?

**Comment by Alan-GitHub** [comment]
Dear michaelrsweet,
My system is embeded linux OS, not desktop system. Kernel version is 3.14.28, mips arch.
[3384:RG]# uname -a
Linux (none) 3.14.28-rg5.8.0mp3 #1 SMP Tue Jan 16 09:32:43 CST 2018 mips GNU/Linux

Where is CUPS from?  
==> From source code compiled

Except CUPS itself, i also porting the cups-filters-1.17.8 package into the board, Driver tried hplip-3.17.9, issue is still exist...

**Comment by michaelrsweet** [comment]
@Alan-GitHub Can you try raw printing to verify that the USB backend is working - "lp -oraw sometextfile.txt" is enough.

**Comment by Alan-GitHub** [comment]
@michaelrsweet  
Thanks for your reply in time, and sorry for making you to wait for so long time...  I delayed this issue due to other things.

A good news share to you, my printer can print "Test Page" on GUI, before is printer itself trouble...

Thanks,
Alan
