### ISSUE TITLE
cups v2.3b1: Default Printer incorrect in Firefox / Qt (cupsGetDests / cupsGetDefault)

### ISSUE THREAD

**Issue by jolz** [apple/cups#5208]
qt (and probably firefox) uses `cupsGetDests` to get a printer list, and the flag `printers[i]->is_default` to get default printer. this fails in 2.3 beta 1.

sample to reproduce: 
```c++
#include <stdio.h>
#include <cups/cups.h>

int main(void)
{
  int i;
  cups_dest_t *dests, *dest;
  int num_dests = cupsGetDests(&dests);
  const char *pcDefault = cupsGetDefault ();

  for (i = num_dests, dest = dests; i > 0; i --, dest ++)
  {
    if (strcmp(pcDefault, dest->name) == 0) {
		printf("Default printer: %s (is_default=%d)\n", dest->name, dest->is_default);
    }
  }
  return (0);
}
```

output: `Default printer: it1 (is_default=0)`
expected: `Default printer: it1 (is_default=1)`

compile with 
```bash
gcc -o cupstest `cups-config --cflags` cupstest.cpp `cups-config --libs`
```

tested on OpenSUSE 42.3 with repository "Printing" (https://build.opensuse.org/project/show/Printing)
cups <= 2.2.6 was good
cups 2.3b1 introduces this bug

**Comment by michaelrsweet** [comment]
cupsGetDefault returns the *server* default, cupsGetDests returns the *client* default which can be overridden by the user or local system admin.

What we need to see is the /etc/cups/lpoptions and ~/.cups/lpoptions on this system...

**Comment by jolz** [comment]
easy trest for me is on two system with $HOME on nfs.


good system:   
```
> LANG=C ls -l /etc/cups/lpoptions ~/.cups/lpoptions 
ls: cannot access /etc/cups/lpoptions: No such file or directory
ls: cannot access .../.cups/lpoptions: No such file or directory
> echo $PRINTER
it1
> rpm -qi cups-client | grep Version
Version     : 1.7.5
```


bad system: 
```
> LANG=C ls -l /etc/cups/lpoptions ~/.cups/lpoptions
ls: cannot access '/etc/cups/lpoptions': No such file or directory
ls: cannot access '.../.cups/lpoptions': No such file or directory
> echo $PRINTER
it1
> rpm -qi cups-client | grep Version
Version     : 2.3b1
```

We set out default printer via environment variable. 

I tried to set default printer via `lpoptions -d it1` (=> "Default it1"), but this did not change anything. 

the "bad system" worked correct until the update last week. All systems with this change lost their default printer. https://build.opensuse.org/package/rdiff/Printing/cups?linkrev=base&rev=344
(cups 2.2.6 -> cups 2.3b1)

We have an organisation with multiple similar systems. All systems with this update loose their default printer setting in firefox, no matter which user is logged in.

**Comment by jolz** [comment]
P.S.: is_default=0 is set for _all_ printer with cups 2.3b1.

**Comment by michaelrsweet** [comment]
Hmm, will investigate further after the break...

**Comment by michaelrsweet** [comment]
Testing with testdest unit test shows that cupsEnumDests works properly but not cupsGetDests. Very strange.

**Comment by michaelrsweet** [comment]
Ahah! cupsCopyDest doesn't copy the is_default value...

**Comment by michaelrsweet** [comment]
[master 3145b7e6a] Copy the is_default value in cupsCopyDest so that cupsGetDests reports the correct default printer (Issue #5208)
