### ISSUE TITLE
It cause windows spoolsv.exe process to raise cpu usage and temperature high.

### ISSUE THREAD

**Issue by queenmedley** [apple/cups#5214]
Local Epson L310 printer 's connected to Archlinux cups printer sever with usb.
I installed the driver from aur. (https://aur.archlinux.org/packages/epso … er-201401w)
It works well self test and local printing.
And network printing also works well  (client is windows 7),
but spoolsv.exe process in windows7 cause 100% cpu  usage and 100 degree temerature.
I didn't noticed that problem for long time and my cpu suffered for long time but still alive.
I have to stop that process in task manager to low cpu usage and temperature.
When the printer conneted to window 7 and shared , spoolsv.exe process cause nothing.
Doing pacman -Syu, and recompile the driver doesn't solve that.
and I have no idea how to diagnose ....

**Comment by michaelrsweet** [comment]
Windows barely supports IPP - more than likely you have run into a Windows bug, which isn't something we can support here, sorry...
