### ISSUE TITLE
cups v2.2.6 no wine printers and no QT4 printers

### ISSUE THREAD

**Issue by gearhead** [apple/cups#5215]
Running Arch Linux. This is very similar to the 2.2.4 issue which was closed. This used to work properly, but sometime along the upgrade path, it stopped working. My printers are not local and are on my server and all of them 'just show up' under gnome and most applications. If I select 'print' from Firefox, gedit, etc, I can select which printer I want and all goes well. I am also running Eagle 6.6.0 which, I believe is QT4 based. When I attempt a print from that application, and all I get is print to file. In all wine programs, It shows no printers installed. Under the localhost:631 web interface, no printers are shown. From the command line:
```
desktop:~$ lpstat -e
HP_LaserJet_1012_Printserver
HP_LaserJet_6P_Printserver
Virtual_PDF_Printer_Printserver
desktop:~$ lpinfo -v
<cut>
network dnssd://HP%20LaserJet%201012%20%40%20Printserver._ipp._tcp.local/cups?uuid=a2da4cd1-3834-340b-700d-31222432044c
network dnssd://HP%20LaserJet%206P%20%40%20Printserver._ipp._tcp.local/cups?uuid=960e1d44-91b5-33b5-53c1-42c75842d055
network dnssd://Virtual%20PDF%20Printer%20%40%20Printserver._ipp._tcp.local/cups?uuid=470fe45d-0614-32e1-5b22-69b3845c7a81

```
so they are 'there', but when I look for them in wine I get nothing:
```
desktop:~$ wineboot -u
002a:trace:winspool:WINSPOOL_EnumPrintersW Found 0 printers
002a:trace:winspool:WINSPOOL_EnumPrintersW Found 0 printers
0030:fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x6a0cb608, context 0x958860, init_notify 0, handle 0x119fc88): stub
desktop:~$ lpstat -t
scheduler is running
no system default destination
lpstat: No destinations added.
lpstat: No destinations added.
lpstat: No destinations added.
lpstat: No destinations added.
desktop:~$ lpstat -s
no system default destination
lpstat: No destinations added.
lpstat: No destinations added.

```

On my other 2 Ubuntu 16.04 machines, this works as expected. The printers show up on all programs. Ubuntu 16.04 runs Cups 2.1.3. All network printers show up automatically in the localhost:631 web interface and I can print from all applications.

**Comment by michaelrsweet** [comment]
Do you have a CUPS_SERVER environment variable set, or ServerName in /etc/cups/client.conf or ~/.cups/client.conf set?  If so, that will disable IPP Everywhere printer detection and require persistent queues for them to show up in any application (automatically-created IPP Everywhere queues only work when you use the default local server configuration...)

**Comment by gearhead** [comment]
Michael,

I appreciate the help. I do not have any of those set. There is no reference to CUPS in the environment nor are any of the other files present.
```
desktop:~$ ls .cups/
lpoptions
desktop:~$ ls /etc/cups
classes.conf        cupsd.conf.O             snmp.conf
classes.conf.O      cups-files.conf          snmp.conf.default
cups-browsed.conf   cups-files.conf.default  ssl
cupsd.conf          ppd                      subscriptions.conf
cupsd.conf.1        printers.conf            subscriptions.conf.O
cupsd.conf.default  printers.conf.O
```

**Comment by michaelrsweet** [comment]
Not sure what patches that ArchLinux applies to the stock CUPS, but this isn't something I can reproduce on Ubuntu or Fedora...
