### ISSUE TITLE
Print blank

### ISSUE THREAD

**Issue by ihussain1024** [apple/cups#5218]
Hi
I'm using Zebra TLP 2844 barcode printer.  Linux platform and installed cups. I have tried commands like 
`lp -d Zebra-TLP2844 filename.txt`
`lpr -P Zebra-TLP2844 filename.txt`
`lp -o raw filename.txt`
`lpr -o raw filename.txt`
`lpr -P Zebra-TLP2844 -o raw filename.zpl`

Every time it prints blank. Am I missing something ?

**Comment by michaelrsweet** [comment]
What version of CUPS?

How is the printer connected?

What driver are you using?
