### ISSUE TITLE
Pages printed in reverse order

### ISSUE THREAD

**Issue by AppIns** [apple/cups#5220]
On every system I have used with cups installed, they have always printed pages in the reverse order on my HP Envy 5660. They print the page that should be on the top first, instead of last.

I found this problem persists no matter what application I use to print.

**Comment by michaelrsweet** [comment]
@AppIns What operating system has every system you have tried been running?

What driver are you using?

What version of CUPS"

**Comment by AppIns** [comment]
I am using the newest version of cups.
I have tried on a newer MacBook and a few machines running linux (arch and
ubuntu)

**Comment by michaelrsweet** [comment]
@AppIns "The newest version of CUPS".

Even macOS doesn't currently ship with the newest version of CUPS (2.3b1). I need to know the actual versions (OS version is OK).

Also, I need to know what driver you are using.
