### ISSUE TITLE
Too much of "Read ... bytes of back-channel data" causes printer to slow down

### ISSUE THREAD

**Issue by phizaz** [apple/cups#5221]
I use **cups** to host a print server on elementary OS (I think I can say ubuntu 16.04). 

I have two clients: Windows 10 and Android phone. 

The topology looks like this:

```
Windows 10 ==> Ubuntu ==> CUPS 2.2.6 ==(driver: Canon MP280 series Ver.3.40)==> Canon MP287
Android 7.0 => 
```

The problem can be observed most prominently from the printing speed:
- Windows 10: the printer prints very slowly (it prints and wait for a period of time and continues)
- Android 7.0: the printer prints almost as it should be (there is a single pause still)

When I inspected cups' error_log (/var/log/cups/error_log) in real time I could see it contain so much of this:

```
D [11/Jan/2018:18:08:02 +0700] [Job 82] Read 436 bytes of back-channel data...
D [11/Jan/2018:18:08:02 +0700] [Job 82] Read 512 bytes of back-channel data...
D [11/Jan/2018:18:08:02 +0700] [Job 82] Read 436 bytes of back-channel data...
D [11/Jan/2018:18:08:02 +0700] [Job 82] Read 512 bytes of back-channel data...
```

alternating with some of this, which I presume to be a _good sign_ of something is printed onto the paper:

```
D [11/Jan/2018:17:51:33 +0700] [Job 80] Wrote 8192 bytes of print data...
D [11/Jan/2018:17:51:33 +0700] [Job 80] Read 8192 bytes of print data...
```

I managed to count the occurrences of these and found them to be in order of **many hundreds to many thousands of "back-channel" to one "print data"**. 

Consider the purpose of `cupsBackChannelRead(..)` to be reading output from the printer, I would wonder is there that much of the output from the printer?

I also observed high CPU usage (100% of one core) during the printing, the processes are as follows:
1. `usb://Canon/MP280%20series?serial=B13E3C&interface=1`
2. `cupsd -L`

I wonder if this problem might relate to #2019.

Anyhow, I am very new to this I tried my best to put all I know here. Hope someone might find a solution for me. Thanks.

**Comment by michaelrsweet** [comment]
@phizaz Many printers are "chatty" - depending on the driver in use, it may not be necessary to have back channel data at all. And a lot of Canon MP printers are already flagged as unidirectional.

Try adding a file called "/usr/share/cups/usb/canon" with the following in it:

    0x04a9 unidir

If that restores proper performance, run "lsusb -v" to get the vendor and product IDs for this printer and we'll add them to the base USB "quirks" file.

**Comment by phizaz** [comment]
@michaelrsweet  Works like a charm! Here is the output from `lsusb -v`

```
  idVendor           0x04a9 Canon, Inc.
  idProduct          0x1746
  bcdDevice            0.02
  iManufacturer           1 Canon
  iProduct                2 MP280 series
  iSerial                 3 B13E3C
```

Thank you so much!

**Comment by michaelrsweet** [comment]
[master 43bcc47b5] Add a USB quirk rule for Canon MP280 series printers (Issue #5221)

**Comment by samueldy** [comment]
> @phizaz Many printers are "chatty" - depending on the driver in use, it may not be necessary to have back channel data at all. And a lot of Canon MP printers are already flagged as unidirectional.
> 
> Try adding a file called "/usr/share/cups/usb/canon" with the following in it:
> 
> ```
> 0x04a9 unidir
> ```
> 
> If that restores proper performance, run "lsusb -v" to get the vendor and product IDs for this printer and we'll add them to the base USB "quirks" file.

@michaelrsweet, Just wanted to say that I had this same issue for a Canon MP480, and the associated fix worked for me too. Would recommend adding this info to the quirks file, too:

```
  idVendor           0x04a9 Canon, Inc.                                                                                                                                                                                                                                                                                       
  idProduct          0x1731 PIXMA MP480                                                                                                                                                                                                                                                                                       
  bcdDevice            1.02                                                                                                                                                                                                                                                                                                   
  iManufacturer           1 Canon                                                                                                                                                                                                                                                                                             
  iProduct                2 MP480 series                                                                                                                                                                                                                                                                                      
  iSerial                 3 11618B                     
```

**Comment by michaelrsweet** [comment]
@samueldy Posting a request like that in a comment for a closed but isn't the best way to get this changed. Please file a bug over on the [OpenPrinting CUPS](https://github.com/OpenPrinting/cups) project with this information and we'll make sure to merge those changes in.

**Comment by samueldy** [comment]
Sorry about that. Will file an issue. Thanks!
