### ISSUE TITLE
"ippserver" sample code does not support multi-value attributes from ipptool output.

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5222]
I have 2 driverless-capable printers available (see the output of the "driverless" command below), one is an actual HP DeskJet 2540 connected via USB and available as IPP printer via ippusbxd (IPP-over-USB), as in issue #5205, therefore the "localhost" URI. The second is an IPP printer emulated by `ippserver` on the virtual machine `virt-devel.local`.
To emulate these printers without having access to the real printers I want to use the new functionality of the `ipptool` and `ippserver` utilities. So I create the appropriate attributes files with the `ipptool --ippserver ...` commands and call `ippserver -a ...` to start the emulation:
```
$ driverless
ipp://localhost:60000/ipp/print
ipp://virt-devel.local:8000/ipp/print
$ ipptool --ippserver ~/HP-DeskJet_2540-ipp-attr-ippserver.txt ipp://localhost:60000/ipp/print get-printer-attributes.test
$ ippserver -a HP-DeskJet_2540-ipp-attr-ippserver.txt xxx
Listening on port 8000.
Ignore Avahi state 2.
ippserver: Unknown directive "," on line 11 of "HP-DeskJet_2540-ipp-attr-ippserver.txt".
$ ipptool --ippserver ~/ippserver-ipp-attr-ippserver.txt ipp://virt-devel.local:8000/ipp/print get-printer-attributes.test
$ ippserver -a ~/ippserver-ipp-attr-ippserver.txt xxx
Listening on port 8000.
Ignore Avahi state 2.
ippserver: Unknown directive "," on line 1 of "/home/till/ippserver-ipp-attr-ippserver.txt".
```
Unfortunately, the emulation does not work. `ippserver` errors out when parsing the first line containing a comma. It seems that there is a bug in parsing comma-separated lists.
I post this report under CUPS as I use `ipptool` and `ippserver` of CUPS 2.3b1. Possibly this also affects ippsample.
Here are the attributes files:
[HP-DeskJet_2540-ipp-attr-ippserver.txt](https://github.com/apple/cups/files/1623715/HP-DeskJet_2540-ipp-attr-ippserver.txt)
[ippserver-ipp-attr-ippserver.txt](https://github.com/apple/cups/files/1623719/ippserver-ipp-attr-ippserver.txt)

**Comment by michaelrsweet** [comment]
The ippserver in CUPS is just sample code that isn't a shipping program (and no Linux distro should be doing so!) Will look at supporting the extended syntax here, but right now we only have plans of fixing this in ippsample...

**Comment by KurtPfeifle** [comment]
See also [issue #67 in ippsample](https://github.com/istopwg/ippsample/issues/67).

**Comment by michaelrsweet** [comment]
Not fixing for the sample code.
