### ISSUE TITLE
Documentation needed: All general options provided by CUPS for all print queues

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5228]
When creating clients (print dialogs) the client does not only need to show all options which the printer provides by its PPD file (or get-printer-attributes IPP request on the CUPS queue) but also general options which are available for any CUPS queue.
These options are for example number-up, page-ranges, output-order, ... and at least for driverless (IPP Everywher, AirPrint, ...) printers with auto-generated PPD options like print-rendering-intent, print-content-optimize, print-scaling, ...
For these there would be needed a full list in the CUPS documentation so that client developers canmake these options completely available in their software.

**Comment by michaelrsweet** [comment]
@tillkamppeter Please review the CUPS Programming Guide (the new one I did for CUPS 2.2.x) and let me know what gaps there are.
