### ISSUE TITLE
Printing speed of multiple jobs degraded dramatically

### ISSUE THREAD

**Issue by OhGonneck** [apple/cups#5242]
Since (at least) 1.7.5 the finishing of the following print command takes significantly longer (over 40% on fast printers):

lp Sheet01.pdf ... Sheet10.pdf

than printing a single document with the same (and same amount) pages. 
Duplex printing - meaning the single PDFs have 2 pages and  the cumulated document has 20 pages. 

In 1.5 4 there was no recognizable difference in printing speed.
Since at least 1.7.5 the printer stops in between one or multiple times) and processes something.

Tested on openSUSE 13.2 (1.5.4), LEAP 42.3 (1.7.5), LEAP 42.3 (2.3b2) and Netrunner / Debian 9 (2.2.4-5) and multiple printers.

Examples:
A HP 553 printer needs 56 instead of 40 seconds (with 1.5.4)
A HP M608 needs 40 instead of 27 seconds to complete the job.

If i upgrade the system now the workday will be 40% longer which is why i think this is a severe bug.

**Comment by michaelrsweet** [comment]
How are these printers configured? We need to know the device URIs and PPDs (drivers) being used.

Also, please keep in mind that there are multiple software components involved, not just CUPS, that could be affecting print speed -what version of cups-filters are installed, for example?

**Comment by OhGonneck** [comment]
These are the printers of the new(slow) LEAP system. Don't worry because of the weird IP addresses.
The printer where i first recognized the problem has the .12.20. (HP M608, also called E60065)
HP_E60065: Installed with hplib
HP_M608_TEST: Tried without hplib and another driver
M608: And another
M608_Test: Copied the driver from the old "fast" working 1.5.4 System over to the new one (modified printers.conf, /etc/printcap and lpoptions)

`lpstat -v
Gerät für HP_E60065: hp:/net/HP_LaserJet_E60065?ip=133.98.12.20
Gerät für hp_M553: hp:/net/HP_Color_LaserJet_M553?zc=NPI112A52
Gerät für hp_m553_Werkstatt: socket://133.98.6.6:9100
Gerät für HP_M608_TEST: socket://133.98.12.20:9100
Gerät für M608: socket://133.98.12.20:9100
Gerät für M608_Test: socket://133.98.12.20:9100
`
They all show the same behaviour. 

The M553 are different printers that also show the behaviour albeit hp_M553 is worse: 
While the other M553 stops only onec after the 5th page, this one stops four or five times resulting in a printing time of over 100 seconds (more than double).

To test this a sufficiently fast printer is needed. Since these are all HP printers i will test it with another fabricate.

[LEAP42.3_PPDs.tar.gz](https://github.com/apple/cups/files/1689622/LEAP42.3_PPDs.tar.gz)

**Comment by michaelrsweet** [comment]
You might try adding "?waiteof=false" to the device URIs of the printers using the "socket" backend. The "hp" backend is part of HPLIP and there is nothing we can do to help you there...

You can also turn off SNMP accounting for the printers using "socket" with:

    lpadmin -p printer -o cupsSNMPSupplies=false

The other variable is the print filters being used - the (separate) [cups-filters](https://github.com/openprinting/cups-filters) project is responsible for those, and a change in the generated PostScript could also have this affect.

**Comment by OhGonneck** [comment]
Hey everyone
 
I am really sorry that this took so long, but i had a really hard time creating a reproducible example that shows the problem. I had only internal documents that had to be stripped from company logos and anonymized - but with these the problem suddenly didn't show up that clearly anymore while the original documents keep being problematic. Obviously it depends on the files that have to be printed. 

I first have tested /?waiteof=false and the cupsSNMPSupplies=false options. None of them seems to have an effect - neither alone or together.

After a lot of testing i am relatively sure that:
1. It is not not driver/ppd related - at least not with postscript drivers.
(Because i installed a printer with lpadmin in one of the old/fast systems with the same URI and PPD that the new/slow system uses. The resulting printer definition is fast on the old system.)
2. It is strongly dependent on the type of documents that are printed. After tearing my hair out i recognized that some of the testing-pages are PDF forms. 

Attached are two documents which reliable show the performance problem when printed several times in succession. One is s page i created and the other one is one of the demo PDF forms that are included with the newer CUPS versions in /usr/share/cups/data. 
See results.txt for command and system details.

Here are the printing times of the four different Systems. The inner ones are the "new" ones with CUPS 2.x while the old ones use 1.5.x.

```        Ubuntu 12.04  Netrunner/Debian 9    SUSE 42.3       SUSE 13.2
M553:   40 Seconds      76 Seconds          54 Seconds      41 Seconds
M608:   27 Seconds      71 Seconds          41 Seconds      27 Seconds
```

[test_PDFs_and_protocol.tar.gz](https://github.com/apple/cups/files/1698840/test_PDFs_and_protocol.tar.gz)


PS: It may be possible the removing the form elements from the pdf before printing solves the problem. But then these documents have to be additionally pre-processed every time. Getting the old print speed back would clearly be a better solution. 

PPS: I even tried with our Samsung copiers but they are so awfully slow that they are insufficient for testing.

**Comment by michaelrsweet** [comment]
OK, so this is almost certainly being cause by the PDF filter on your Linux distribution and *not* by CUPS, which does not include a PDF filter by default. Typically Ghostscript and/or Poppler are used by the Linux pdftops filter, so one of those has caused the regression.

Probably the best place to get help on this is via the [cups-filters project](https://github.com/OpenPrinting/cups-filters).
