### ISSUE TITLE
Flexible page ranges for lp

### ISSUE THREAD

**Issue by madduck** [apple/cups#5243]
The Debian CUPS maintainer [explained in Debian bug report #889178](https://bugs.debian.org/889178) the reason why `lp -P <page-range>` only takes a very restrictive page range specification, referencing RFC8011, and specifically section 5.2.7:

> 5.2.7.  page-ranges (1setOf rangeOfInteger(1:MAX))
> 
> This RECOMMENDED attribute identifies the range(s) of Input Pages
> that the Printer uses for each Set to be printed prior to imposition
> of those pages onto Impressions.  Nothing is printed for any pages
> identified that do not exist in the Set/Document(s).  Ranges MUST be
> in ascending order (1-3, 5-7, 15-19, etc.) and MUST NOT overlap so
> that a non-spooling Printer can process the Job in a single pass.  If
> the ranges are not ascending or are overlapping, the Printer MUST
> reject the request and return the 'client-error-bad-request'
> status-code.

I understand the reasoning here, and yet can't help but notice that this is a case where history impedes upon usability.

Couldn't things be made such that CUPS reorders the page range as required for non-spooling printers  (surely that's a flag in the PPD somewhere), while simultaneously allowing users of spooling printers to specify free-form page ranges, including reverse ranges, page duplications, and possibly even selectors such as even and odd?

Some examples:

- `lp -P 3-1 …`: print pages 1,2,3 in reverse order
- `lp -P 1-3,2 …`: print pages 1,2,3 and then 2 again
- `lp -P odd …`: print all odd pages
- `lp -P 1-5/2 …`: print every second page in the range 1–5
- `lp -P -3--1 …`: print the last three pages
- …

Thanks for your consideration.

**Comment by michaelrsweet** [comment]
If the primary use case for CUPS was command-line printing, and if we didn’t care about locale-specific number systems, and if we didn’t have to deal with a bunch of different print file formats,  then I might be inclined to agree with this request. However, none of those statements are true, and we really really don’t want to introduce a complicated/fancy new way of specifying page ranges from the command-line at this point in the CUPS life cycle. The mapping alone (setting aside how to support a locale-neutral syntax) would require changes to all of the print filters, and potentially changes to cupsd to know the number of input pages. And then there is multiple document support which for page-ranges has never worked right in CUPS...

Sorry...
