### ISSUE TITLE
Decoding of QUOTEDCHAR in cupsParseOptions() 

### ISSUE THREAD

**Issue by svarshavchik** [apple/cups#5244]
https://www.cups.org/doc/cupspm.html#cupsParseOptions describes cupsParseOptions() as follows:

"This function converts space-delimited name/value pairs according to the PAPI text option ABNF specification."

From https://opensource.apple.com/source/cups/cups-218/cups/standards/papi-1.0.pdf at the bottom of page 120:

```
QUOTEDCHAR    = %x5C %x5C / %x5C DQUOTE / %x5C SQUOTE /
                %x5C 3OCTALDIGIT / %x21 / %x23-26 / %x28-5B /
                                 %x5D-7E / %xA0-FF
```

But cupsParseOptions() does not appear to implement "%x5C 3OCTALDIGIT", i.e. octal encoding of a single octet, and it unescapes just a single character:

```
#include <cups/cups.h>
#include <stdio.h>

int main(int argc, char **argv)
{
	cups_option_t *options=0;
	int num_options;
	int i;

	num_options=cupsParseOptions("foo=\"bar\\040baz\"", 0, &options);

	for (int i=0; i<num_options; ++i)
		printf("%s=%s\n", options[i].name,
		       options[i].value);
	return 0;
}
```

This results in the following output:

`foo=bar040baz
`

While I parse the PAPI specification as specifying that the expected output of this should be "foo=bar baz".

See also: sections 11.2.4 and 11.2.5 at the top of page 122 in the same documentation, which appear to support this interpretation.

Note that `STRINGCHAR` also specifies the same octal encoding.

**Comment by michaelrsweet** [comment]
Will consider fixing this in a future release but in practice octal escapes are unnecessary and were added to the PAPI spec late in its development (PAPI was based on CUPS' option handling, not the other way around; the reference in the documentation is for convenience...)

**Comment by michaelrsweet** [comment]
Sorry, not fixing.
