### ISSUE TITLE
Problème redirection http to https in de container docker 

### ISSUE THREAD

**Issue by blindman78** [apple/cups#5245]
Hello,

I'm trying to use your program in a docker but I got some issues with the redirection when I try to add a new printer.
If I connect myself in http and try to add the printer, the adress for the redirection in https is the adress of the container of the docker and not the one declare at the beginning. Do you have I idea why? 
example : 

case  http as first:
	http://192.168.0.1:631/admin (connection)
 	redirection => https://172.20.0.2:631/admin/ (http => click on add a printer => result for redirection)

case https at first :
	https://192.168.0.1:631/admin 
	no redirection, just authentification page.

**Comment by michaelrsweet** [comment]
@blindman78 Does your cupsd.conf file declare a server name or are you relying on the default?

**Comment by blindman78** [comment]
on a Default i try why other value

**Comment by michaelrsweet** [comment]
OK, you need to specify the server name because the default name will be based on the internal name/IP, not the externally accessible name/IP.

**Comment by blindman78** [comment]
ok thx i try it
