### ISSUE TITLE
A blank page is added at the end of some documents when printing

### ISSUE THREAD

**Issue by OhGonneck** [apple/cups#5246]
[creates_additional_page_at_duplex.pdf](https://github.com/apple/cups/files/1704082/creates_additional_page_at_duplex.pdf)

Printing this 2-sided document with duplex enabled - 2 pages get actually printed instead of one.

`
lp -o Duplex=DuplexNoTumble -d brother creates_additional_page_at_duplex.pdf`

(Tested on 4 different printers from 3 verdors, on CUPS version 1.5.4 and 2.3b2.)

**Comment by michaelrsweet** [comment]
What operating system?

If Linux, what version of CUPS filters?

Does the same thing happen if you use:

    lp -o sides=two-sided-long-edge -d PRINTER FILENAME

???

**Comment by OhGonneck** [comment]
Operating systems:
Linux openSUSE Leap 42.3 cups 2.3b2:
cups-filters 1.8.2
Linux openSUSE 13.2 cups 1.5.4: (there is no "cups-filters" package installed, but:)
cups-filters-ghostscript 1.0.58
cups-filters-foomatic-rip 1.0.58
 
It happens on both systems with a brother and a hp m553 printer.

I can install other operating systems and package versions for testing if needed.

**Comment by jsmeix** [comment]
@OhGonneck 
this may not directly help you, nevertheless you may have a look at
https://en.opensuse.org/SDB:How_to_Report_a_Printing_Issue
because it also describes some basic things that can help
to diagnose the cause of a printing issue.

**Comment by OhGonneck** [comment]
@jsmeix 
Ok, here is some more info in case it might be helpful (i did not think so - but that is also stated in the document you referenced :-) )

brother: socket://133.98.6.190:9100  ( "Brother HL-2250DN" )
egrep 'NickName|cupsFilter' /etc/cups/ppd/brother.ppd 
*cupsFilter:    "application/vnd.cups-postscript 100 foomatic-rip"
*cupsFilter:    "application/vnd.cups-pdf 0 foomatic-rip"
*ShortNickName: "Brother HL-2170W hpijs-pcl5e"
*NickName:      "Brother HL-2170W Foomatic/hpijs-pcl5e (recommended)"

hp_m553_Werkstatt: socket://133.98.6.6:9100/?waiteof=false  ("HP Colour LaserJet Enterprise M553")
*ShortNickName: "HP Color LaserJet M553"
*NickName: "HP Color LaserJet M553 Postscript (recommended)"
*cupsFilter: "application/vnd.cups-postscript 0 hpps"
*da.Translation ShortNickName/HP Color LaserJet M553: ""
*da.Translation NickName/HP Color LaserJet M553: ""
(the other languages are all the same)

M608_Test: socket://133.98.12.20:9100 ("HP Laserjet Enterprise M608")
*ShortNickName: "HP LaserJet M806"
*NickName: "HP LaserJet M806 Postscript (recommended)"
*cupsFilter: "application/vnd.cups-postscript 0 hpps"
*da.Translation ShortNickName/HP LaserJet M806: ""
*da.Translation NickName/HP LaserJet M806: ""

Messraum: socket://133.98.1.248:9100 ("Samsung MultiExpress 8123")
*ShortNickName: "SCX-8230 8240"
*NickName: "Samsung SCX-8230 8240 Series PS"

I also set up a test-queue with the default postscipt driver. The resulting file actually seems not to have that ominous third page. (But then - it hasn't a third page . only the printing process creates one.)

Could you please try to print out the test page i submitted and see if your printer spits out two separate pages despite duplex is enabled?

**Comment by michaelrsweet** [comment]
OK, the problem with this file is that page 1 is ISO A4 and page 2 is US Letter. Because the second page is a different size than the first, the printer has to start a new sheet.

**Comment by OhGonneck** [comment]
Gosh. You are right of course. 
I had ruled that out, because all other documents created by that system printed ok - but it turns out that this is the only document that can have an odd page count and therefore gets this letter page added. 
Every "other software" i have tried to print the document with worked well - but since i don't know any other printing system that can handle pdf directly these other softwere all were pdf-viewers like Okular or Adobe Reader. All these pdf readers obviously process the pdf themselves and do not pass on the original pdf data and so the new sheet does not show up in these cases.

I wish i had a totally different printing system that also can handle pdf documents to compare with.
