### ISSUE TITLE
It seems since CUPS v2.3b3 the filters are no longer installed

### ISSUE THREAD

**Issue by jsmeix** [apple/cups#5247]
Since CUPS v2.3b3 (it worked with v2.3b2) the filters are no longer installed.
At the end of building a RPM package I get
<pre>
RPM build errors:
File not found: /home/abuild/rpmbuild/BUILDROOT/cups-2.3b3-227.1.i386/usr/lib/cups/filter/commandtops
File not found: /home/abuild/rpmbuild/BUILDROOT/cups-2.3b3-227.1.i386/usr/lib/cups/filter/gziptoany
File not found: /home/abuild/rpmbuild/BUILDROOT/cups-2.3b3-227.1.i386/usr/lib/cups/filter/pstops
File not found: /home/abuild/rpmbuild/BUILDROOT/cups-2.3b3-227.1.i386/usr/lib/cups/filter/rastertoepson
File not found: /home/abuild/rpmbuild/BUILDROOT/cups-2.3b3-227.1.i386/usr/lib/cups/filter/rastertohp
File not found: /home/abuild/rpmbuild/BUILDROOT/cups-2.3b3-227.1.i386/usr/lib/cups/filter/rastertolabel
File not found: /home/abuild/rpmbuild/BUILDROOT/cups-2.3b3-227.1.i386/usr/lib/cups/filter/rastertopwg
</pre>

The filters are still compiled and linked,
e.g. for commandtops excerpts from my build log
<pre>
Compiling commandtops.c...
cc  -Wall -Wno-format-y2k -Wunused -fPIC -g -fstack-protector -Wno-unused-result -Wsign-conversion -Wno-tautological-compare -Wno-format-truncation -D_GNU_SOURCE -I.. -D_CUPS_SOURCE -fomit-frame-pointer -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -fstack-protector -fPIE -fPIC -I/usr/include/libusb-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -DDBUS_API_SUBJECT_TO_CHANGE -DDEBUG -D_REENTRANT -I/usr/include/p11-kit-1 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE -D_REENTRANT   -c -o commandtops.o commandtops.c
...
Linking commandtops...
cc -L../cgi-bin -L../cups -L../filter -L../ppdc -L../scheduler -pie -Wl,-z,relro,-z,now -fPIE -pie -Wall -Wno-format-y2k -Wunused -fPIC -g -fstack-protector -Wno-unused-result -Wsign-conversion -Wno-tautological-compare -Wno-format-truncation -D_GNU_SOURCE -o commandtops commandtops.o -lcups -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lavahi-common -lavahi-client -lgnutls -lz -lpthread -lm -lcrypt   -lz
</pre>
it seems the filters only get no longer installed.

**Comment by jsmeix** [comment]
FYI:
My current 2.3b3 build sources are here:
https://build.opensuse.org/package/show/home:jsmeix:branches:Printing/cups
and a current RPM build log is e.g. here
https://build.opensuse.org/package/live_build_log/home:jsmeix:branches:Printing/cups/openSUSE_Tumbleweed/x86_64

**Comment by jsmeix** [comment]
For me this is a fix:
https://build.opensuse.org/package/view_file/home:jsmeix:branches:Printing/cups/fix_filter_Makefile.patch?expand=1

**Comment by michaelrsweet** [comment]
Not sure why this didn't show up on my build farm, but will investigate and fix...

**Comment by jsmeix** [comment]
I submitted my home:jsmeix:branches:Printing/cups
to Printing/cups so that now the sources are in
https://build.opensuse.org/package/show/Printing/cups
any my fix is
https://build.opensuse.org/package/view_file/Printing/cups/fix_filter_Makefile.patch?expand=1

**Comment by michaelrsweet** [comment]
[master ab89234de] Fix installation of filters (Issue #5247)
