### ISSUE TITLE
lp is 5x slower in CUPS 2.2.5

### ISSUE THREAD

**Issue by burpy** [apple/cups#5249]
Hi,

I print a lot of files on a Mac with the command line like this:

`lp -d MYPRINTER -t MYFILENAME -o SelectColor=Grayscale /path/to/my/pdffile.pdf`

I use PHP with shell_exec to do this in my script. It works fine, but after the macOS update from Sierra to High Sierra these commands are five times slower. I need the result that the line print command returns (= "request id is MYPRINTER-1111 (1 file(s))")

With High Sierra comes the CUPS version 2.2.5. I don't know which version it was with Sierra, but I tested it with CUPS version 1.7.5 and it was much faster with the same file.

with CUPS 1.7.5:   0.0792 seconds
with CUPS 2.2.5:    0.4058 seconds

Thanks for your help!

**Comment by michaelrsweet** [comment]
I'm not sure where the difference might lie (in CUPS or some other component), however a difference of 327ms (just shy of 1/3 second) is not significant and could be caused by any number of things (even filesystem changes).

Sorry, but we don't have the resources to track this down for you.

**Comment by burpy** [comment]
ok, thanks anyway.

With my PHP script I print with each session 400 pdf-files in a row and so the script runs now 2min and 17sec longer :)

My workaround is to discard the response by adding a ` >/dev/null 2>/dev/null &` at the end of the lp command line and search afterwards if the request was successful. Maybe I will write a logfile instead of /dev/null

**Comment by michaelrsweet** [comment]
FWIW, you can always create a single job with multiple files, if the overhead is somehow associated with running the command itself.

**Comment by burpy** [comment]
Thanks, I keep that in mind. In my case every lp command is different (some are colored, some are duplex...). I will do it now like this and read the results in the next step.

`echo 'MYFILENAME' $(lp -d MYPRINTER -t MYFILENAME -o KMDuplex=Double -o page-ranges=1-1 -o SelectColor=Grayscale -o KMInputSlot=TrayLCT -o MediaType=CustomMedia5 /path/to/my/pdffile.pdf) >>/var/log/lp_request.log 2>>/var/log/lp_request.log &`

**Comment by burpy** [comment]
it is now faster again with mac os mojave and cups 2.2.9
