### ISSUE TITLE
Printing working via smbspool and not via lpr on windows printer

### ISSUE THREAD

**Issue by jeosspee** [apple/cups#5250]
Good evening.

I have an Active Directory (AD) on Windows Server 2012. This machine also shares printers and only allows printout from authenticated AD users. I have an ArchLinux machine added to the AD via samba and sssd. I log in the ArchLinux machine with AD credentials and can access Windows shares.

I set up a printer queue in CUPS with URI smb://server/printer. If I send jobs via the command 'lpr -P printer file.pdf', the printer responds with 'Tree connect failed (NT_STATUS_ACCESS_DENIED)'. However, if I send them via the command 'smbclient -k //server/printer -c "print file.pdf"', AD credentials are taken from the kerberos ticket and the jobs are printed appropriately. I have tried the URI smb://user:password@server/printer and it works. Although the user and password do not appear in the URI after installing the printer, they appear in /etc/cups/printers.conf without encryption. I do not want this approach because it is not secure.

I have tried Basic and Negotiate for DefaultAuthType in /etc/cups/cupsd.conf and all values for 'OpPolicy' in /etc/cups/printers.conf. No combination works.

The file /usr/lib/cups/backend/smb looks like this:
lrwxrwxrwx 1 root root 17 dic 27 11:54 /usr/lib/cups/backend/smb -> /usr/bin/smbspool

Package versions:
cups 2.2.6-4
samba 4.7.4-1
sssd 1.16.0-4
krb5 1.16.1

I have tried winbind instead of sssd and have got the same result.

¿Someone can help me?

Thanks in advance.

**Comment by michaelrsweet** [comment]
This is a packaging problem - please report this to your Linux distribution.

What you need to do is remove the symlink and then copy smbspool to the backend directory with the proper permissions:

    sudo rm /usr/lib/cups/backend/smb
    sudo cp /usr/bin/smbspool /usr/lib/cups/backend/smb
    sudo chmod 700 /usr/lib/cups/backend/smb
