### ISSUE TITLE
Delay 4s before printing page

### ISSUE THREAD

**Issue by tasmaniski** [apple/cups#5256]
I have installed CUPS on Ubuntu server and try to print ZPL page to the remote printer.  
After adding the printer to CUPS I send one file to printer:
> lpadmin -p 'printer_name' -v 'socket://*******:9100/?waitprinter=false' -P 'zebra.ppd' -E
> lp -d printer_name -o raw file.zpl

The file is printed fine, but on every printing job there is **exactly 4s delay before page start printing**.
From cups error_log I can see:
> ...
> D [28/Feb/2018:13:27:27 +0100] Discarding unused printer-state-changed event...
> D [28/Feb/2018:**13:27:27** +0100] **[Job 303] Looking up** \"*******\"...
> D [28/Feb/2018:**13:27:31** +0100] [Job 303] prtGeneralCurrentLocalization type is 0, expected 2!
> D [28/Feb/2018:13:27:31 +0100] [Job 303] Connecting to *******:9100
> I [28/Feb/2018:13:27:31 +0100] [Job 303] Connecting to printer.

So there is that **Looking up for IP** which lasts exactly 4 seconds.   
even if there is jobs in a line, on every job there is same "Looking up" delay.

Is there a way to avoid this check?

I am using CUPS 2.1.3 on Ubuntu 16.04

**Comment by michaelrsweet** [comment]
If you use an IP address the “looking for printer” time (resolve address and connect) will be shorter. Also, you can try doing the following to turn off SNMP:

    lpadmin -p printer -o cupsSNMPSupplies=false

**Comment by tasmaniski** [comment]
I am using IP and I tried with `cupsSNMPSupplies=false` but unfortunately, it didn't change anything. 

Do you have maybe some other idea what to do?
I am willing to setup windows server if printing time can be shorter.

**Comment by michaelrsweet** [comment]
@tasmaniski What does your nsswitch.conf file contain? An IP address lookup should be instantaneous.

**Comment by tasmaniski** [comment]
It seems that I had a version of CUPS that doesn't support SNMP settings via the lpadmin command.  
I put it in the config and it works like a charm :)
thank you!

**Comment by michaelrsweet** [comment]
OK, I'm going to reopen this bug for the purpose of adding the cupsSNMPSupplies keyword to the label printer PPDs - none of the supported printers support SNMP anyways, so this will avoid having to make this configuration change.

**Comment by tasmaniski** [comment]
Ah, I try and add cupsSNMPSupplies false in PPD file, and it also works! 
It didn't work when I added it through the command.

**Comment by michaelrsweet** [comment]
[master c6dbbca1f] Disable SNMP supplies for all label printers (Issue #5256)

[branch-2.2 30c8d1abb] Disable SNMP supplies for all label printers (Issue #5256)
