### ISSUE TITLE
All printers in simgle page

### ISSUE THREAD

**Issue by ran-j** [apple/cups#5257]
I open te link http://myserver:631/printers/ and se my printers, but I wave a lot of prints and appears a button "Show Next", but a dont wanted. There is a http request to show me all printer in the table ?.

like http://myserver:631/printers/QUERY=ALL
or
like http://myserver:631/printers/QUERY=**

**Comment by michaelrsweet** [comment]
Sorry, that’s how things used to be and we moved away from it because of performance problems.
