### ISSUE TITLE
Yet another Lexmark no-reattach quirk (E310)

### ISSUE THREAD

**Issue by colingibbs1** [apple/cups#5259]
This is for an Optra E310. I just get a flashing error light after a few seconds, no output.

This saves the day:
    # echo 0x043d 0x000c no-reattach > /usr/share/cups/usb/lexmark-e310

I found this following these bug reports: #4448, #4778, #4994.

**Comment by michaelrsweet** [comment]
For 2.2.7 and 2.3...

**Comment by michaelrsweet** [comment]
[master ea95f7fe1] Add USB quirk rule for Lexmark Optra E310 printers (Issue #5259)

[branch-2.2 5e1869029] Add USB quirk rule for Lexmark Optra E310 printers (Issue #5259)
