### ISSUE TITLE
Search by IP ?

### ISSUE THREAD

**Issue by 7ussana** [apple/cups#5260]
Hello,

I have migrated 600 printers on a new CUPS server.
On the old server (1.3.8), the search by IP works fine but on your new server (2.2.6) this doesn't works.

Is there an option ? This option is very useful for us.

Thanks

**Comment by michaelrsweet** [comment]
We never had a "search by IP" feature in the web interface, although in older versions of CUPS the printer page did not optimize the printer query using the values that were shown by the template - perhaps it was picking up on the device-uri value?

You can edit the /usr/share/cups/templates/printers.tmpl file and add "" after the "{printer_name}" cell to get the device-uri included in the search (but not displayed).
