### ISSUE TITLE
Printing with Lexmark CX510de

### ISSUE THREAD

**Issue by Papipio** [apple/cups#5262]
L'OS de mon PC est Mageia Linux 6.
Pour certaines impressions (je n'ai pas réussi à comprendre pourquoi), l'imprimante sort d'abord une page avec un peu de texte (..., @PJL SET USERNAME = "*****", @PJL ENTER LANGUAGE = POSTS) en haut, avant d'imprimer ensuite le document (= 1 page gaspillée). Je ne sais pas si il s'agit d'une page générée par la nouvelle impression ou si il s'agit d'une page qui "traine" depuis l'impression précédente.
Que puis-je faire ? Est-ce un problème de paramètres dans l'imprimante ? Ou est-ce un problème de paramètres du pilote d'impression ?
Même si j'utilise ensuite ces pages en trop comme brouillons, je n'utilise pas mon imprimante pour me générer des pages de brouillons !!!

If necessary I can write this comment in English.

Pierre

**Comment by michaelrsweet** [comment]
This is probably a printer driver issue - you can try deleting the following line in your PPD file (/etc/cups/ppd/queuename.ppd):

    *JCLBegin: "..."

but otherwise there isn't much we can do. Sorry...

**Comment by Papipio** [comment]
Thank you Michael for your answer.
When I apply your solution I no longer get these useless pages. But it is then impossible to print in black and white a colour document ... !

Pierre
