### ISSUE TITLE
cups.service exit when configuration file reload in systemd environment

### ISSUE THREAD

**Issue by reddevillg** [apple/cups#5263]
#4760 With this change, we should add `Restart=on-failure` in systemd unit file.

**Comment by michaelrsweet** [comment]
Not sure why this should be needed (cupsd isn't exiting with a non-zero exit code) but will investigate. We haven't had any reports of problems with this...

**Comment by debiantriage** [comment]
There is Debian bug #861470

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=861470

I thought the issue had already been reported upstream by Arch Linux. That was from reading

https://bugs.archlinux.org/task/51774

It says there:

> Correction. The service doesn't crash. CUPS rather shuts down gracefully whenever a 
> restart is intended. That's very likely the way its meant to be done. CUPS shuts down
> to reload the new configuration and waits for the system to restart it.  But the Arch
> release doesn't have any 'restart=' member in the systemd unit so once CUPS shuts
> down it remains down. Neither logs nor GDB show any abnormal runtime paths or errors. 

Regards,

Brian.

**Comment by michaelrsweet** [comment]
If I am reading the [systemd.service "documentation"](https://www.freedesktop.org/software/systemd/man/systemd.service.html) correctly, it sounds like we should be using:

    Restart=always

as "on-failure" won't do a damned thing if cupsd exits with status 0.

**Comment by michaelrsweet** [comment]
[master 0dfe69905] Fix systemd integration with cupsd (Issue #5263)

[branch-2.2 82c4785a4] Fix systemd integration with cupsd (Issue #5263)

**Comment by liuxiaomeng2270** [comment]
I‘m a new in cups, I don't know which file to add "Restart=always"
Is /etc/cups/cupsd.conf be the correct file?

**Comment by michaelrsweet** [comment]
On my Ubuntu 17.10 system, the service file is /lib/systemd/system/cups.service. The `[Service]` section in this file should look like this once you've added the "Restart=always" part:

```
[Service]
ExecStart=/usr/sbin/cupsd -l
Type=simple
Restart=always
```

Once you make the change and save it, run `systemctl daemon-reload` to have systemd reload the cups.service file.
