### ISSUE TITLE
cupsd crashed with SIGSEGV in finalize_job()

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5266]
I got following bug report by an Ubuntu user:

https://bugs.launchpad.net/ubuntu/+source/cups/+bug/1756336

The bug happened when the user printed a job.

The report contains all needed information, especially stack traces:
https://bugs.launchpad.net/ubuntu/+source/cups/+bug/1756336/+attachment/5081406/+files/ThreadStacktrace.txt

The problem occurred on the upcoming Ubuntu 18.04 with CUPS 2.2.6.

**Comment by michaelrsweet** [comment]
Strange - job->printer can't be NULL at that point since it would have crashed in the call to cupsdSetPrinterReasons prior to this line, and device_uri is never NULL.

**Comment by michaelrsweet** [comment]
@tillkamppeter If this problem is reproducible, we need a debug/debug2 error_log file to understand how they are getting in this state.

**Comment by michaelrsweet** [comment]
Unable to reproduce. Unless we get more information I'll need to close this issue...
