### ISSUE TITLE
cupsd crashed with SIGSEGV in mime_compare_srcs()

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5267]
I got following bug report by an Ubuntu user:
https://bugs.launchpad.net/ubuntu/+source/cups/+bug/1756160
The problem occurred just after a system update.
The report contains all needed information, especially stack traces:
https://bugs.launchpad.net/ubuntu/+source/cups/+bug/1756160/+attachment/5080844/+files/ThreadStacktrace.txt
The problem occurred on the upcoming Ubuntu 18.04 with CUPS 2.2.6.

**Comment by michaelrsweet** [comment]
@tillkamppeter Can you get a copy of the PPD being used? I can't reproduce locally.
