### ISSUE TITLE
cupsd service stopped but not restart on demand

### ISSUE THREAD

**Issue by liuxiaomeng2270** [apple/cups#5272]
Hi, I'm do printing jobs on Ubuntu system. Firstly, it works fine, cups can create jobs and the printer can print correctly, but hours later, when I do the print again, the system shows an error that, no printers are added, I run the system-printer-configure, It says can not connect cups server, and there is no cupsd process run on the system. 

then I checked the error_log, it says 
Printer sharing is off and there are no jobs pending, will restart on demand.
scheduler shutting down normally.
Discarding unused server-stopped event ...
Creating keep-alive file "/var/cache/cups/org.cups.cupsd"
saving job.cache...
cupsdStopSelect()

no matter what I tried, the cupsd does not restart unless I use service cups restart to restart the cups service.

It happens frequently, I have no idea how to resolve it.

Any ideas?

THX

**Comment by michaelrsweet** [comment]
This is issue #5263 - the fix is to add a "Restart=always" to the org.cups.cupsd.service file used by systemd.

**Comment by liuxiaomeng2270** [comment]
thanks for your reply
but I‘m a new in cups, I don't know which file to add "Restart=always"
Is /etc/cups/cupsd.conf be the correct file?
