### ISSUE TITLE
Unable to create ppd files, "Preview" extremly slow

### ISSUE THREAD

**Issue by randomJoel** [apple/cups#5275]
Cheers,

I'm struggling with an unpleasant problem. 

We have a Cups server (latest version) running for Mac's and Linux computer. The problem only affects Mac's.

While accessing the Cups server and Creating the IPP printer the cups-browsed doesn't create any ppd files. Oddly this is only a problem for the program "Preview" as printing takes way to long in Preview without ppd files. Any other program doesn't seems to be affected.

I've took a look at it and I found a executable named "ipp2ppd" on my Mac, which seems to create those ppd files. When I use the executable and create a ppd file from a single IPP printer, located on our Cups server, and set this printer as a Default. The problem with the Preview application is gone, and printing is super fast.
The problem is that those ppd files are local and not affected by changes on the IPP printers on the Cups server.

Is there any way to create local ppd files each time the Mac checks for the printers on the server?

Best wishes 
Joel

**Comment by michaelrsweet** [comment]
Joel,

How are you creating the print queues on the Mac?

The cups-browsed program cannot be used to create print queues on the Mac. Similarly, you cannot use local raw queues pointing at the server as they are not supported on macOS and are incompatible with sandboxed applications that have no direct network access (Preview is one of them). You have to have a local PPD.

Ordinarily you should be able to just pick a shared printer from the nearby printer list in the Print dialog and a local queue will be created automatically. Alternatively you can add the printer from the Print & Scan system preferences where you can enter the server name (if Bonjour isn’t reaching your segment of the network).

**Comment by michaelrsweet** [comment]
@randomJoel Ping.
