### ISSUE TITLE
error: Installed (but unpackaged) file(s) found: /usr/share/locale/en/cups_en.po

### ISSUE THREAD

**Issue by pconklin** [apple/cups#5276]
CentOS 7.4 x86_64

following command fails with below error
rpmbuild -ta cups-2.3b3-source.tar.gz

Checking for unpackaged file(s): /usr/lib/rpm/check-files /root/rpmbuild/BUILDROOT/cups-2.3b3-0.x86_64
error: Installed (but unpackaged) file(s) found:
   /usr/share/locale/en/cups_en.po
    Installed (but unpackaged) file(s) found:
   /usr/share/locale/en/cups_en.po

**Comment by michaelrsweet** [comment]
[master b056061b2] Add cups_en.po file (Issue #5276)
