### ISSUE TITLE
CUPS-Get-Printers not listing printers anymore

### ISSUE THREAD

**Issue by xinix00** [apple/cups#5279]
Starting of v2.1, CUPS doesn't list all the printers anymore when sending IPP "CUPS-Get-Printers"

Sending to: ipp://username:password@localhost:631
{
            "operation": "CUPS-Get-Printers",
            "operation-attributes-tag": {
                "attributes-charset": 'utf-8',
                "attributes-natural-language": 'en-us'
             }
}

I'm expecting to see a list of printers in the printer-attribute tag. I first thought it was the new added printer_id, which would filter (and thus skip printers) though having tested version 2.1 I can exclude this.

The above request is working on 1.7.5, however failed since 2.1 and also fails the latest 2.2 build 2.2.7.

I saw the test itself is only checking for successfull-ok, but not if there is an array of printers (which should be expected).

**Comment by michaelrsweet** [comment]
I'm not familiar with exactly how the Node.js IPP library works, but I can say that if something like this broke we would have heard about it long before now. I suspect you have run into a bug in the Node.js library you are using.
