### ISSUE TITLE
CUPS  can't authenticate

### ISSUE THREAD

**Issue by constatinus** [apple/cups#5282]
I recently installed cups from git. I also tried older cupses ( 2.2.5, 2.2.1 ) and they had the same issue. See, when i get to localhost:631 and go to Administration/Add Printer on anything that requires access, i get an authentication promprt witch i can't auth into because no matter what i type it won't accept the username and password as the correct one. I compiled cups from source. Help ?

[pastebin](https://pastebin.com/QTGQeRZs)

**Comment by michaelrsweet** [comment]
See https://www.cups.org/faq.html
