### ISSUE TITLE
Printouts with ZPL driver resist rotation

### ISSUE THREAD

**Issue by crishoj** [apple/cups#5284]
Using the ZPL driver, I am unable to get CUPS to print on 80x50mm labels when the label is fed along the long edge. The output always ends up being printed across the label, regardless of the setting for `requested-orientation`, media size, scaling and auto-rotation:

![image](https://user-images.githubusercontent.com/20393/38212673-e413b26c-36be-11e8-859e-d7386e13f8a1.jpeg)

The issue affects both CUPS versions 2.2.7 on Ubuntu and 2.2.5 on High Sierra.

Here's what the desired output looks like:

<img width="187" alt="screen shot 2018-04-03 at 01 29 17" src="https://user-images.githubusercontent.com/20393/38221211-a1f6f892-36de-11e8-8726-d91c8d2adcd8.png">

What makes the issue so odd is that
1. it Just Works™  with CUPS version 1.7.5, and
2. it also works if I artificially expand the PDF document to double height (by adding whitespace below and rotation 180°). It seems that when the document is taller than it is wide, the rotation suddenly behaves as expected. Example of a layout with which the output ends up being rotated correctly:

<img width="206" alt="screen shot 2018-04-03 at 01 31 15" src="https://user-images.githubusercontent.com/20393/38221250-c85911fa-36de-11e8-9327-f5d01d3b90b6.png">

The printer in question is a Citizen CL-S631 (in Zebra mode):

![untitled](https://user-images.githubusercontent.com/20393/38212927-d1dd426a-36bf-11e8-99ef-b57df9a9f853.png)

Any suggestions on how to debug this would be much appreciated.

[material.pdf](https://github.com/apple/cups/files/1869732/material.pdf)
[expanded.pdf](https://github.com/apple/cups/files/1869731/expanded.pdf)

**Comment by crishoj** [comment]
Some previous discussion: https://askubuntu.com/questions/796716/how-do-i-prevent-cups-from-auto-rotating-my-pdf

**Comment by michaelrsweet** [comment]
The PDF is landscape orientation. You don't specify a size and the printer supports the landscape size directly, so it gives you a landscape (long-edge feed) bitmap.

That said, the Zebra driver options also control the media type and other settings - you need to make sure that the defaults are set properly so that the label is not rotated and the printer does the right thing. Until I changed the default media size to a label of the proper width (>= the width of what you want to print) and media tracking (continuous or non-continuous web/mark), I wasn't able to get your label to print correctly.

**Comment by crishoj** [comment]
Editing the PPD to specify the actual label size does indeed produce the desired orientation.

```
*DefaultPageSize: w142h227
*PageSize w142h227/1.97x3.15": "<</PageSize[142 227]/ImagingBBox null>>setpagedevice"
*PageRegion w142h227/1.97x3.15": "<</PageSize[142 227]/ImagingBBox null>>setpagedevice"
*ImageableArea w142h227/1.97x3.15": "0 0 142 227"
*PaperDimension w142h227/1.97x3.15": "142 227"
```

Thank you very much!

BTW: I was not able to make it work using the command line option `-o media`.

**Comment by patrickchoi** [comment]
The PPD editing was the only thing that solved it for me. Zebra ZD410, default Zebra ZPL settings in CUPS only has 3"x2". To print landscape CUPS required PPD to be told 2"x3".

Swapped width / length around and label instantly came out in landscape.

Also strange that custom size setting in CUPS did not work as mentioned above, probably similar to how it was reported the switch -o media also did not work.
