### ISSUE TITLE
Can't print from IOS device. No error log

### ISSUE THREAD

**Issue by jerwij** [apple/cups#5285]
I have a small problem. I can't get printing working from my mobile IOS devices. The devices are finding the printer, en CUPS recieved the job. Under tab Jobs I can see that CUPS recieved the file and that it should be printing but it isn't. I can't find anny error in the log files. Printing from my PC's works fine and reacts in the UI the same as from an IOS device.

Access log:
192.168.2.21 - pi [03/Apr/2018:11:01:32 +0200] "GET /admin/log/error_log? HTTP/1.1" 200 1014 - -
[v1.2a02:a448:f7a2:1:50e4:ec2a:6c3e:d98a] - - [03/Apr/2018:11:01:51 +0200] "POST /printers/Brother_DCP-7030 HTTP/1.1" 200 489 Validate-Job successful-ok
[v1.2a02:a448:f7a2:1:50e4:ec2a:6c3e:d98a] - - [03/Apr/2018:11:01:51 +0200] "POST /printers/Brother_DCP-7030 HTTP/1.1" 200 473 Create-Job successful-ok
[v1.2a02:a448:f7a2:1:50e4:ec2a:6c3e:d98a] - - [03/Apr/2018:11:01:51 +0200] "POST /printers/Brother_DCP-7030 HTTP/1.1" 200 23126 Send-Document successful-ok
192.168.2.21 - pi [03/Apr/2018:11:01:56 +0200] "GET /admin/log/access_log? HTTP/1.1" 200 557 - -

Error log:
W [03/Apr/2018:10:52:11 +0200] Max clients reached, holding new connections...
W [03/Apr/2018:11:02:03 +0200] Max clients reached, holding new connections...

Page log:
Brother_DCP-7030 mobile 54 [03/Apr/2018:11:02:05 +0200] 1 1 - [v1.2a02:a448:f7a2:1:50e4:ec2a:6c3e:d98a] iBooks - one-sided

**Comment by michaelrsweet** [comment]
Sorry, but we don't support using CUPS as a server for iOS or AirPrint - it doesn't support everything needed for it to work reliably.
