### ISSUE TITLE
first time

### ISSUE THREAD

**Issue by karbovskibg** [apple/cups#5291]
HI first time in github. My brother has installed ubuntu server and shared brother hl1110 laser printer, Now ubuntu come with obsolte drivers maybe 2.17 so my brother install developer drivers and printer from lan computers didn't work, printer from smartphone was working, but something happendro in the nights and in the other day printer just dissapear. So my brother return in home this night and he update developer drivers to 2.3~b4-2 and there is no printer, include in smartphone it comment : this printer is not disponible, if my borther force it to accept printer it comment: Printer is not respondng. PLease check it is powered on and avaible at: https;//yourdomain.com:631/printers/printerishere

In version 2.2.x how i say in developer version it works, smartphone has printers but something has happend and my brother for that update to version  2.3~b4-2 but again it don;t work. I don;t know who is developer but they had to make smartphone direct printing too. direct is: you install android application that cups developers make and when you configure your printer it only come and return to your domain " it only come and return to your domain mean that it don't go to apple servers, or google servers " we don't like governments illegaly spy. We use linux and linux is free software, it is illegal governments spy we want android application that connect to your domain and from your domain it connet to printer, after that printer print it.

My brother speak with his friend how to break cups .deb and change ssl to be high, becouse in the moment ssl is some cheap 128 tls_ecdhe that is insecure i hear my brother say there is documentation that it is breakable, how is that possible cups don't allow peoples change it, include why there is no http2 support when http2 bring more security. I don't know what my brother will do, but he need inmediatelly actions becouse he need printer for the university, fault of cups developers one professor of my brother scream him, but i defend my brother and tell my brother professor RESPECT MY BROTHER you shit women, my brother is HUMANKIND too. i complaint in the police about women violence to men.

Now i don;t know computer science but i will help my brother so i want to know it can be configured cups latest 2.3~b4-2 to work in home and in smartphone.

**Comment by karbovskibg** [comment]
this is our printer, it can be cheap, becouse it is not our fault we in the moment are not rich:
Device: uri = usb://Brother/HL-1110%20series?serial=whatyouarelooking
        class = direct
        info = Brother HL-1110 series
        make-and-model = Brother HL-1110 series
        device-id = MFG:Brother;CMD:PJL,HBP;MDL:HL-1110 series;CLS:PRINTER;CID:Brother Laser Type3;
        location = 
Include i just remember my brother make tests: he put create Brother HL-1110 series and when he print from chrome web site it send to server and from server to printer and it comment it is printed but our printer didn't print it. So my brother go to https;//yourdomain.com:631/admin and there it comment it was printed, so my brother go and write: lp 1.txt and BINGO it print what was in 1.txt. Now my brother switch off and connect localy printer to usb and when he print from chrome web site it inmediatelly print. What is happening, why when my brother connect cups to printer to domain it don't print and in old version 2.2 it only print from smartphone and from computer it don't print and it broke in new version 2.3 bla... and in new version in the first message i explain what it comment. Guys developers please repair.

**Comment by michaelrsweet** [comment]
OK, I will try to respond to all of your questions, however please note that the [CUPS user list](https://lists.cups.org/mailman/listinfo/cups) is the preferred place to go to ask questions and not the Github issue tracker.

CUPS 2.3b4 is an unstable beta release of CUPS. Currently CUPS 2.2.7 is the most recent stable version and is what you should be using, *not* CUPS 2.3b4.

We have no experience with Android printing software, so I cannot speak to whether it can/should work with CUPS.

We likewise have no experience with Brother printer drivers and cannot provide support for third-party software. I advise you to contact Brother for support of their drivers.

There are options to configure the supported SSL/TLS versions and cipher suites that have known vulnerabilities - "man client.conf" and "man cupsd.conf" for information on the SSLOptions directives. WRT the 128-bit ECDHE cipher suites, I am not aware of any known vulnerabilities, and in fact 128-bit AES-GCM with ECDHE negotiation is one of the mandatory cipher suites for TLS 1.3.

HTTP 2 is not more secure than HTTP 1.1. By default, HTTP 2 uses TLS, but then so does HTTP 1.1 when you use https URLs, and https is the default for CUPS when accessing the software remotely. HTTP 2 *does* offer performance improvements for complex web sites accessed over the Internet, however that does not apply to CUPS or printing over the local network.

As to why CUPS does not work with Apache 2, doing so would be vastly slower and much harder to configure, not to mention exposing your system to a multitude of attacks specific to Apache server.

Finally, there are a LOT of wi-fi (and multi-function!) printers available for the same price (and less) than the one you chose. But I suspect that if you stick with a stable release of CUPS with a popular Linux distribution, you should be able to get things to work.
