### ISSUE TITLE
michaelsweet 2.2.7 stable comment error

### ISSUE THREAD

**Issue by karbovskibg** [apple/cups#5292]
michaelsweet you close first thread so i open this.

michaelsweet you didnt comment where is manual that comment what program with all drivers need to install cups. my brother is sleeping in the moment, so michaelsweet how i say on the first topic and yoi michaelsweet close it the other day i hear my brother he install 2.3b nevouse 2.2.7 was commenting issues, i dont know what issue they have but it was unpleseant that my brother update to latest 2.3b, inclhde i like more 2.3b that 2.2.7, michaelsweet if you repair 2.3b my brother maybe will leave it working. i just remember that when cuos was in veraion 1.x my brother comment cups comment him certifocate error, this was latest 1.x version inmediatelly after cups 2.x ssl vertificate was working. So michaelsweet if yoi really make cups then you will have braim to inderstand that ubuntu or linux stable version dont work and peoples are forcing to install latest versions. my brother didnt like to install SHIT developer version, becouse stable cups was lacking ssl and was working on http. the other day i was with my brother in his university and they use cups latest developer version. theu too belive stable versions are more problematics. my brother university was complaining ubuntu, debian more than 10 times and response. i see otber university that completly use windows server and they work just perfectly. if someone complaint about problematic women inmediately jail women. include there is discount about wimdows lperation system. now my brother univeraity use linux, and they use latest debeloper cups.  michaelsweet so using latest cups developer version is recommended from obsolete stable version. michaelsweet you didnt comment when cups is installed what port haa to be open, becouse my brother has speak with his friemd and he commemt him to open only port 631 and stay ooen port 80 for apache2. michaelsweet how is possible that my brother friends and university is working they cups with latest developer version and our printer in home dont work from internet include it dont work from lan, but it work from directly usb and jow i say when my brother has installed 2.2.x it was only working smartphone..now i remember that my brother wjem speak with colleges friends they use debian developer edition... but how is that possible when developer is unstable... include other day i go with my brother in they house and some of they was playing on ps4... they have apache2 and cups on the same computer and it was working with ssl.

**Comment by michaelrsweet** [comment]
This issue tracker is not a discussion forum. Please post your questions to the [CUPS user list](https://lists.cups.org/mailman/listinfo/cups)!

Thank you.
