### ISSUE TITLE
Question/inconsistency about ErrorPolicy

### ISSUE THREAD

**Issue by bwolf** [apple/cups#5301]
The man page cupsd.conf states `retry-this-job`
https://github.com/apple/cups/blob/master/man/cupsd.conf.man.in#L145

but the code in scheduler/conf.c validates something different:
https://github.com/apple/cups/blob/master/scheduler/conf.c#L1229

The code doesn't contain a case for `retry-this-job`. Is this an inconsistency or I'm misunderstanding the documentation?

**Comment by michaelrsweet** [comment]
D'oh, should be "retry-current-job".

[master b95156db4] Update ErrorPolicy in cupsd.conf man page (Issue #5301)

[branch-2.2 9d1d11a46] Update ErrorPolicy in cupsd.conf man page (Issue #5301)
