### ISSUE TITLE
Zebra Labels are upside down on CUPS 2.2.5

### ISSUE THREAD

**Issue by gcedillos** [apple/cups#5302]
Hey all, here's my issue:

- We are printing labels from an installed application on Mac desktop units. Each unit is printing from a Zebra LP 2824 Plus, and each printer has been configured using CUPS 2.2.5. 
- Right now all stations that are using CUPS 2.2.5 are printing the text upside down. Adjusting the label specs through CUPS does not correct this issue.
- Some stations are running CUPS 2.2.0. These stations are printing their labels in the correct format.
- The stations with CUPS 2.2.5 are running off Mac OS High Sierra 10.13.4. 
- The stations with CUPS 2.2.0 are running off an older version of Mac OS.
- When we update the Mac OS it bumps up the version of CUPS from 2.2.0 to 2.2.5. 
- The software application that generates the label info is configured to run on Windows OS. We are able to run it on our Macs using XQuartz version 2.7.9. 

Any help on correcting this issue would be much appreciated.

Is there a way to downgrade CUPS from 2.2.5 to 2.2.0?

Another option would be to update to CUPS 2.2.7. 

Thanks again in advance!

**Comment by michaelrsweet** [comment]
This was a long-standing bug in the ZPL driver - the current behavior is the correct one.

**Comment by gcedillos** [comment]
@michaelrsweet Thanks for the information. Do you have any advice on how to correct the text format on CUPS 2.2.5?

**Comment by michaelrsweet** [comment]
All you can do it revert the rastertolabel filter (in /usr/libexec/cups/filter) from an older macOS release.

(Longer term you should look at rotating your label images to work with the top of the image on the leading edge *or* using orientation-requested=6 to request reverse-portrait orientation)
