### ISSUE TITLE
lpadmin's '-E' option can lead to invalid queues being created

### ISSUE THREAD

**Issue by michaelweghorn** [apple/cups#5305]
In certain situations, `lpadmin` rightly refuses to create printer queues, e.g. when invalid parameters where given or a remote device is not available when setting up a printer with the `-m everywhere` option, e.g.

    $ sudo lpadmin -p myprinter -v ipp://myprinter.example.org/ipp/ -m everywhere
    lpadmin: Unable to connect to "myprinter.example.org:631": Name or service not known
    $ echo $?
    1
    $ lpstat -v | grep myprinter
    

However, when the `-E` option is given in addition, an invalid queue is created instead, even though `lpadmin` does return a non-zero exit status, e.g.

    $ sudo lpadmin -p myprinter -v ipp://myprinter.example.org/ipp/ -m everywhere -E
    lpadmin: Unable to connect to "myprinter.example.org:631": Name or service not known
    $ echo $?
    1
    $ lpstat -v | grep myprinter
    device for myprinter: ///dev/null

Side note: The `cupsaccept` and `cupsenable` commands work as expected when called with a non-existent printer:

    $ sudo cupsaccept myprinter
    cupsaccept: Operation failed: client-error-not-found
    $ sudo cupsenable myprinter
    cupsenable: Operation failed: client-error-not-found

**Comment by michaelrsweet** [comment]
[master 997b67343] Use Enable-Printer and Resume-Printer operations so we don't create a bogus printer (Issue #5305)

[branch-2.2 2b4e4ed7d] Use Enable-Printer and Resume-Printer operations so we don't create a bogus printer (Issue #5305)
