### ISSUE TITLE
Redirection to port 631 without regard to the actual accessed port

### ISSUE THREAD

**Issue by etlel** [apple/cups#5307]
Steps:
1. Access to the administration remotely with port forwarding (eg. :3631->631)
1. Change settings. The server is restarted and the page redirects user to :631 whatsoever port was used for access by the browser.

**Comment by michaelrsweet** [comment]
This is a known limitation of using things like port forwarding, and unfortunately there isn't anything we can do (no notion of a relative URL that changes the scheme from HTTP to HTTPS).
