### ISSUE TITLE
HP LaserJet P1102 needs option usb-no-reattach=true when printing from remote client

### ISSUE THREAD

**Issue by pezcurrel** [apple/cups#5310]
Hi, I'm running Arch Linux with kernel 4.16.6-1-ARCH and CUPS 2.2.7-2 on all the pcs involved.

My HP LaserJet P1102 always worked just fine with CUPS when printing from the same pc it is attached to (via usb). Instead, when printing from other clients on the LAN it could only print the first document; after that no other document (from local and remote) could be printed until I turned the printer off and then back on. (Strangely, the documents which didn't get printed showed as printed in the jobs history).
Today I managed to overcome this issue by doing...

`lpadmin -p [MyPrinterName] -o usb-no-reattach-default=true`

It seems strange to me that the problem only presented when printing from a remote client, so I don't know wether it would be ok to add...

`# HP LaserJet P1102`
`0x03F0 0x002A no-reattach`

...to `/usr/share/cups/usb/org.cups.usb-quirks`

**Comment by michaelrsweet** [comment]
Can’t hurt...

**Comment by michaelrsweet** [comment]
[master 050d26570] Add a USB quirks rule for the HP LaserJet P1102 (Issue #5310)

[branch-2.2 ff52b652c] Added a USB quirks rule for the HP LaserJet P1102 (Issue #5310)
