### ISSUE TITLE
Feature: support certificate transparency with CUPS Web UI

### ISSUE THREAD

**Issue by akorobkin** [apple/cups#5314]
http://www.certificate-transparency.org/what-is-ct

As CT is going to be adopted by major browsers soon, it would make it hard for IT managers to manage CUPS Web UI in corp environment without CT support. 

Could it be added to the web server please?

**Comment by michaelrsweet** [comment]
I'm not sure what the ask is here? CT is a CA thing and doesn't apply to the self-signed certificates we usually use. Your existing CA certificate should have the ESCTL extension record in it, which is what is needed for CT support.

We will NOT be adding more configuration directives to artificially add them in...

**Comment by akorobkin** [comment]
I was looking at http://www.certificate-transparency.org/resources-for-site-owners expecting TLS Extension to be implemented, but I'm ok figuring it with my CA instead. Thanks!
