### ISSUE TITLE
Drivers For Epson L130 in Raspberry Pi3(OS- Debian) 

### ISSUE THREAD

**Issue by Dheerajss** [apple/cups#5318]
In my project i want to print the color  image using lpr command for Epson L130 printer . i am using raspberry pi 3 which has debian os install in it .But in cups services when i try to add my printer my model has not  been listed in their model list and when i try ti print with another model  the driver doesnt support and because of that either the output is error print or my image is printed thrice with improper colors.
So anyone can guide me with proper drivers or solution.

**Comment by michaelrsweet** [comment]
You want Gutenprint. This isn't a printer that is supported out-of-the-box with CUPS.
