### ISSUE TITLE
Where does CUPS expect to find libgs?

### ISSUE THREAD

**Issue by Michael-IDA** [apple/cups#5320]
Ref:  https://askubuntu.com/questions/983970/where-does-cups-expect-to-find-libgs

CUPS is crashing with "Cannot load libgs or libgs version too old then 8.0"

What needs to be symlinked where to fix it?

CUPS 1.7.2
Ubuntu 14.04.5 LTS
Linux anon 4.2.0-27-generic #32~14.04.1-Ubuntu SMP Fri Jan 22 15:32:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Copy/Paste of crash file (as "we can't process that file"):

troubleshoot-Panasonic-KX-MB2030series.txt

Page 1 (Scheduler not running?):
{'cups_connection_failure': False}
Page 2 (Choose printer):
{'cups_dest': <cups.Dest Panasonic-KX-MB2030series>,
 'cups_instance': None,
 'cups_queue': u'Panasonic-KX-MB2030series',
 'cups_queue_listed': True}
Page 3 (Check printer sanity):
{'cups_device_uri_scheme': u'socket',
 'cups_printer_dict': {'device-uri': u'socket://192.168.1.216:9100',
                       'printer-info': u'Panasonic KX-MB2030series',
                       'printer-is-shared': False,
                       'printer-location': u'192.168.1.216',
                       'printer-make-and-model': u'Panasonic KX-MB2030series',
                       'printer-state': 3,
                       'printer-state-message': u'(PID 24605) Cannot load libgs or libgs version too old then 8.0',
                       'printer-state-reasons': [u'none'],
                       'printer-type': 10490052,
                       'printer-uri-supported': u'ipp://localhost:631/printers/Panasonic-KX-MB2030series'},
 'cups_printer_remote': False,
 'is_cups_class': False,
 'local_cups_queue_attributes': {'charset-configured': u'utf-8',
                                 'charset-supported': [u'us-ascii', u'utf-8'],
                                 'color-supported': False,
                                 'compression-supported': [u'none', u'gzip'],
                                 'copies-default': 1,
                                 'copies-supported': (1, 9999),
                                 'cups-version': u'1.7.2',
                                 'device-uri': u'socket://192.168.1.216:9100',
                                 'document-format-default': u'application/octet-stream',
                                 'document-format-supported': [u'application/octet-stream',
                                                               u'application/pdf',
                                                               u'application/postscript',
                                                               u'application/vnd.adobe-reader-postscript',
                                                               u'application/vnd.cups-command',
                                                               u'application/vnd.cups-pdf',
                                                               u'application/vnd.cups-pdf-banner',
                                                               u'application/vnd.cups-postscript',
                                                               u'application/vnd.cups-raw',
                                                               u'application/x-cshell',
                                                               u'application/x-csource',
                                                               u'application/x-perl',
                                                               u'application/x-shell',
                                                               u'image/gif',
                                                               u'image/jpeg',
                                                               u'image/png',
                                                               u'image/tiff',
                                                               u'image/urf',
                                                               u'image/x-bitmap',
                                                               u'image/x-photocd',
                                                               u'image/x-portable-anymap',
                                                               u'image/x-portable-bitmap',
                                                               u'image/x-portable-graymap',
                                                               u'image/x-portable-pixmap',
                                                               u'image/x-sgi-rgb',
                                                               u'image/x-sun-raster',
                                                               u'image/x-xbitmap',
                                                               u'image/x-xpixmap',
                                                               u'image/x-xwindowdump',
                                                               u'text/css',
                                                               u'text/html',
                                                               u'text/plain'],
                                 'finishings-default': 3,
                                 'finishings-supported': [3],
                                 'generated-natural-language-supported': [u'en-us'],
                                 'ipp-versions-supported': [u'1.0',
                                                            u'1.1',
                                                            u'2.0',
                                                            u'2.1'],
                                 'ippget-event-life': 15,
                                 'job-creation-attributes-supported': [u'copies',
                                                                       u'finishings',
                                                                       u'ipp-attribute-fidelity',
                                                                       u'job-hold-until',
                                                                       u'job-name',
                                                                       u'job-priority',
                                                                       u'job-sheets',
                                                                       u'media',
                                                                       u'media-col',
                                                                       u'multiple-document-handling',
                                                                       u'number-up',
                                                                       u'output-bin',
                                                                       u'orientation-requested',
                                                                       u'page-ranges',
                                                                       u'print-color-mode',
                                                                       u'print-quality',
                                                                       u'printer-resolution',
                                                                       u'sides'],
                                 'job-hold-until-default': u'no-hold',
                                 'job-hold-until-supported': [u'no-hold',
                                                              u'indefinite',
                                                              u'day-time',
                                                              u'evening',
                                                              u'night',
                                                              u'second-shift',
                                                              u'third-shift',
                                                              u'weekend'],
                                 'job-ids-supported': True,
                                 'job-k-limit': 0,
                                 'job-k-octets-supported': (0, 476173360),
                                 'job-page-limit': 0,
                                 'job-priority-default': 50,
                                 'job-priority-supported': [100],
                                 'job-quota-period': 0,
                                 'job-settable-attributes-supported': [u'copies',
                                                                       u'finishings',
                                                                       u'job-hold-until',
                                                                       u'job-name',
                                                                       u'job-priority',
                                                                       u'media',
                                                                       u'media-col',
                                                                       u'multiple-document-handling',
                                                                       u'number-up',
                                                                       u'output-bin',
                                                                       u'orientation-requested',
                                                                       u'page-ranges',
                                                                       u'print-color-mode',
                                                                       u'print-quality',
                                                                       u'printer-resolution',
                                                                       u'sides'],
                                 'job-sheets-default': (u'none', u'none'),
                                 'job-sheets-supported': [u'none',
                                                          u'classified',
                                                          u'confidential',
                                                          u'form',
                                                          u'secret',
                                                          u'standard',
                                                          u'topsecret',
                                                          u'unclassified'],
                                 'jpeg-k-octets-supported': (0, 476173360),
                                 'jpeg-x-dimension-supported': (0, 65535),
                                 'jpeg-y-dimension-supported': (1, 65535),
                                 'marker-change-time': 1527712187,
                                 'marker-colors': [u'none', u'none'],
                                 'marker-levels': [-1, -1],
                                 'marker-names': [u'Toner', u'Drum'],
                                 'marker-types': [u'toner', u'opc'],
                                 'media-bottom-margin-supported': [423],
                                 'media-col-default': u'(unknown IPP value tag 0x34)',
                                 'media-col-supported': [u'media-bottom-margin',
                                                         u'media-left-margin',
                                                         u'media-right-margin',
                                                         u'media-size',
                                                         u'media-source',
                                                         u'media-top-margin',
                                                         u'media-type'],
                                 'media-default': u'na_letter_8.5x11in',
                                 'media-left-margin-supported': [423],
                                 'media-right-margin-supported': [423],
                                 'media-size-supported': [u'(unknown IPP value tag 0x34)',
                                                          u'(unknown IPP value tag 0x34)',
                                                          u'(unknown IPP value tag 0x34)',
                                                          u'(unknown IPP value tag 0x34)',
                                                          u'(unknown IPP value tag 0x34)',
                                                          u'(unknown IPP value tag 0x34)',
                                                          u'(unknown IPP value tag 0x34)',
                                                          u'(unknown IPP value tag 0x34)'],
                                 'media-source-supported': [u'tray1',
                                                            u'manual'],
                                 'media-supported': [u'na_letter_8.5x11in',
                                                     u'na_legal_8.5x14in',
                                                     u'iso_a4_210x297mm',
                                                     u'jis_b5_182x257mm',
                                                     u'iso_b5_176x250mm',
                                                     u'om_16-k_195.09x269.88mm',
                                                     u'oe_85x13in_85x13in',
                                                     u'oe_85x134in_85x134in'],
                                 'media-top-margin-supported': [423],
                                 'media-type-supported': [u'stationery',
                                                          u'thin-paper',
                                                          u'labels'],
                                 'multiple-document-handling-supported': [u'separate-documents-uncollated-copies',
                                                                          u'separate-documents-collated-copies'],
                                 'multiple-document-jobs-supported': True,
                                 'multiple-operation-time-out': 300,
                                 'natural-language-configured': u'en-us',
                                 'notify-attributes-supported': [u'printer-state-change-time',
                                                                 u'notify-lease-expiration-time',
                                                                 u'notify-subscriber-user-name'],
                                 'notify-events-default': [u'job-completed'],
                                 'notify-events-supported': [u'job-completed',
                                                             u'job-config-changed',
                                                             u'job-created',
                                                             u'job-progress',
                                                             u'job-state-changed',
                                                             u'job-stopped',
                                                             u'printer-added',
                                                             u'printer-changed',
                                                             u'printer-config-changed',
                                                             u'printer-deleted',
                                                             u'printer-finishings-changed',
                                                             u'printer-media-changed',
                                                             u'printer-modified',
                                                             u'printer-restarted',
                                                             u'printer-shutdown',
                                                             u'printer-state-changed',
                                                             u'printer-stopped',
                                                             u'server-audit',
                                                             u'server-restarted',
                                                             u'server-started',
                                                             u'server-stopped'],
                                 'notify-lease-duration-default': 86400,
                                 'notify-lease-duration-supported': (0,
                                                                     2147483647),
                                 'notify-max-events-supported': [100],
                                 'notify-pull-method-supported': [u'ippget'],
                                 'notify-schemes-supported': [u'dbus',
                                                              u'mailto',
                                                              u'rss'],
                                 'number-up-default': 1,
                                 'number-up-supported': [1, 2, 4, 6, 9, 16],
                                 'operations-supported': [2,
                                                          4,
                                                          5,
                                                          6,
                                                          8,
                                                          9,
                                                          10,
                                                          11,
                                                          12,
                                                          13,
                                                          14,
                                                          16,
                                                          17,
                                                          18,
                                                          19,
                                                          20,
                                                          21,
                                                          22,
                                                          23,
                                                          24,
                                                          25,
                                                          26,
                                                          27,
                                                          28,
                                                          34,
                                                          35,
                                                          37,
                                                          38,
                                                          56,
                                                          57,
                                                          59,
                                                          16385,
                                                          16386,
                                                          16387,
                                                          16388,
                                                          16389,
                                                          16390,
                                                          16391,
                                                          16392,
                                                          16393,
                                                          16394,
                                                          16395,
                                                          16396,
                                                          16397,
                                                          16398,
                                                          16399,
                                                          16423,
                                                          14],
                                 'orientation-requested-default': None,
                                 'orientation-requested-supported': [3,
                                                                     4,
                                                                     5,
                                                                     6],
                                 'output-bin-default': u'face-down',
                                 'output-bin-supported': [u'face-down'],
                                 'page-ranges-supported': True,
                                 'pages-per-minute': 24,
                                 'pdf-k-octets-supported': (0, 476173360),
                                 'pdf-versions-supported': [u'adobe-1.2',
                                                            u'adobe-1.3',
                                                            u'adobe-1.4',
                                                            u'adobe-1.5',
                                                            u'adobe-1.6',
                                                            u'adobe-1.7',
                                                            u'iso-19005-1_2005',
                                                            u'iso-32000-1_2008',
                                                            u'pwg-5102.3'],
                                 'pdl-override-supported': [u'attempted'],
                                 'port-monitor': u'none',
                                 'port-monitor-supported': [u'none'],
                                 'ppd-timestamp': u'*',
                                 'print-color-mode-default': u'monochrome',
                                 'print-color-mode-supported': [u'monochrome'],
                                 'print-quality-default': 4,
                                 'print-quality-supported': [4],
                                 'printer-commands': [u'AutoConfigure',
                                                      u'Clean',
                                                      u'PrintSelfTestPage'],
                                 'printer-current-time': u'(IPP_TAG_DATE)',
                                 'printer-dns-sd-name': None,
                                 'printer-error-policy': u'retry-job',
                                 'printer-error-policy-supported': [u'abort-job',
                                                                    u'retry-current-job',
                                                                    u'retry-job',
                                                                    u'stop-printer'],
                                 'printer-icons': u'http://localhost:631/icons/Panasonic-KX-MB2030series.png',
                                 'printer-info': u'Panasonic KX-MB2030series',
                                 'printer-is-accepting-jobs': True,
                                 'printer-is-colormanaged': True,
                                 'printer-is-shared': False,
                                 'printer-location': u'192.168.1.216',
                                 'printer-make-and-model': u'Panasonic KX-MB2030series',
                                 'printer-more-info': u'http://localhost:631/printers/Panasonic-KX-MB2030series',
                                 'printer-name': u'Panasonic-KX-MB2030series',
                                 'printer-op-policy': u'default',
                                 'printer-op-policy-supported': [u'authenticated',
                                                                 u'default'],
                                 'printer-resolution-default': (300, 300, 3),
                                 'printer-resolution-supported': [(300,
                                                                   300,
                                                                   3),
                                                                  (300,
                                                                   300,
                                                                   3)],
                                 'printer-settable-attributes-supported': [u'printer-info',
                                                                           u'printer-location'],
                                 'printer-state': 3,
                                 'printer-state-change-time': 1527712187,
                                 'printer-state-message': u'(PID 24605) Cannot load libgs or libgs version too old then 8.0',
                                 'printer-state-reasons': [u'none'],
                                 'printer-type': 10490052,
                                 'printer-up-time': 1527712219,
                                 'printer-uri-supported': [u'ipp://localhost:631/printers/Panasonic-KX-MB2030series'],
                                 'printer-uuid': u'urn:uuid:64af5828-f565-3e83-6843-131568919db1',
                                 'queued-job-count': 2,
                                 'server-is-sharing-printers': False,
                                 'sides-default': u'one-sided',
                                 'sides-supported': [u'one-sided'],
                                 'uri-authentication-supported': [u'requesting-user-name'],
                                 'uri-security-supported': [u'none'],
                                 'which-jobs-supported': [u'completed',
                                                          u'not-completed',
                                                          u'aborted',
                                                          u'all',
                                                          u'canceled',
                                                          u'pending',
                                                          u'pending-held',
                                                          u'processing',
                                                          u'processing-stopped']}}
Page 4 (Check PPD sanity):
{'cups_printer_ppd_defaults': {u'General': {u'InputSlot': u'Tray1',
                                            u'MediaType': u'Plain',
                                            u'PageRegion': u'Letter',
                                            u'PageSize': u'Letter',
                                            u'Poster': u'None'},
                               u'Output': {u'Collate': u'True'},
                               u'Quality': {u'Resolution': u'Standard',
                                            u'TonerSave': u'False'}},
 'cups_printer_ppd_valid': True,
 'missing_pkgs_and_exes': ([], [])}
Page 5 (Local or remote?):
{'printer_is_remote': False}
Page 6 (Printer state reasons):
{'printer-state-message': u'(PID 24605) Cannot load libgs or libgs version too old then 8.0',
 'printer-state-reasons': [u'none']}
Page 7 (Error log checkpoint):
{'cups_server_settings': {'BrowseLocalProtocols': 'dnssd',
                          'DefaultAuthType': 'Basic',
                          'JobPrivateAccess': 'default',
                          'JobPrivateValues': 'default',
                          'MaxLogSize': '0',
                          'SubscriptionPrivateAccess': 'default',
                          'SubscriptionPrivateValues': 'default',
                          'WebInterface': 'Yes',
                          '_debug_logging': '0',
                          '_remote_admin': '0',
                          '_remote_any': '0',
                          '_share_printers': '0',
                          '_user_cancel_any': '0'},
 'error_log_checkpoint': 28060,
 'error_log_debug_logging_set': True}
Page 8 (Error log fetch):
{'error_log': ['D [30/May/2018:15:31:29 -0500] [Client 14] Sending file.',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=28060, response=(nil)(), pipe_pid=0, file=15',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=26012, response=(nil)(), pipe_pid=0, file=15',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=23964, response=(nil)(), pipe_pid=0, file=15',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=21916, response=(nil)(), pipe_pid=0, file=15',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=19868, response=(nil)(), pipe_pid=0, file=15',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=17820, response=(nil)(), pipe_pid=0, file=15',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=15772, response=(nil)(), pipe_pid=0, file=15',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=13724, response=(nil)(), pipe_pid=0, file=15',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=11676, response=(nil)(), pipe_pid=0, file=15',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=9628, response=(nil)(), pipe_pid=0, file=15',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=7580, response=(nil)(), pipe_pid=0, file=15',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=5532, response=(nil)(), pipe_pid=0, file=15',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=3484, response=(nil)(), pipe_pid=0, file=15',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=1436, response=(nil)(), pipe_pid=0, file=15',
               'D [30/May/2018:15:31:29 -0500] [Client 14] Waiting for request.',
               'D [30/May/2018:15:31:29 -0500] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] POST / HTTP/1.1',
               'D [30/May/2018:15:31:29 -0500] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"',
               'D [30/May/2018:15:31:29 -0500] [Client 14] No authentication data provided.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] 2.0 Get-Jobs 99',
               'D [30/May/2018:15:31:29 -0500] Get-Jobs ipp://localhost/printers/',
               'D [30/May/2018:15:31:29 -0500] [Job 19] Loading attributes...',
               'D [30/May/2018:15:31:29 -0500] [Job 20] Loading attributes...',
               'D [30/May/2018:15:31:29 -0500] [Client 14] Returning IPP successful-ok for Get-Jobs (ipp://localhost/printers/) from localhost',
               'D [30/May/2018:15:31:29 -0500] [Client 14] Content-Length: 291',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] cupsdWriteClient error=0, used=0, state=HTTP_STATE_POST_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=291, response=0x55eb2d8221a0(IPP_IDLE), pipe_pid=0, file=-1',
               'D [30/May/2018:15:31:29 -0500] [Client 14] Writing IPP response, ipp_state=DATA, old wused=0, new wused=0',
               'D [30/May/2018:15:31:29 -0500] [Client 14] bytes=0, http_state=0, data_remaining=0',
               'D [30/May/2018:15:31:29 -0500] [Client 14] Waiting for request.',
               'D [30/May/2018:15:31:29 -0500] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] POST / HTTP/1.1',
               'D [30/May/2018:15:31:29 -0500] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"',
               'D [30/May/2018:15:31:29 -0500] [Client 14] No authentication data provided.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] 2.0 Get-Jobs 100',
               'D [30/May/2018:15:31:29 -0500] Get-Jobs ipp://localhost/printers/',
               'D [30/May/2018:15:31:29 -0500] [Job 1] Loading attributes...',
               'D [30/May/2018:15:31:29 -0500] [Job 2] Loading attributes...',
               'D [30/May/2018:15:31:29 -0500] [Job 3] Loading attributes...',
               'D [30/May/2018:15:31:29 -0500] [Job 4] Loading attributes...',
               'D [30/May/2018:15:31:29 -0500] [Job 5] Loading attributes...',
               'D [30/May/2018:15:31:29 -0500] [Job 6] Loading attributes...',
               'D [30/May/2018:15:31:29 -0500] [Job 7] Loading attributes...',
               'D [30/May/2018:15:31:29 -0500] [Job 13] Loading attributes...',
               'D [30/May/2018:15:31:29 -0500] [Job 14] Loading attributes...',
               'D [30/May/2018:15:31:29 -0500] [Job 15] Loading attributes...',
               'D [30/May/2018:15:31:29 -0500] [Job 16] Loading attributes...',
               'D [30/May/2018:15:31:29 -0500] [Job 17] Loading attributes...',
               'D [30/May/2018:15:31:29 -0500] [Job 18] Loading attributes...',
               'D [30/May/2018:15:31:29 -0500] [Client 14] Returning IPP successful-ok for Get-Jobs (ipp://localhost/printers/) from localhost',
               'D [30/May/2018:15:31:29 -0500] [Client 14] Content-Length: 1259',
               'D [30/May/2018:15:31:29 -0500] [Job 1] Removing document files.',
               'D [30/May/2018:15:31:29 -0500] [Job 2] Removing document files.',
               'D [30/May/2018:15:31:29 -0500] [Job 3] Removing document files.',
               'D [30/May/2018:15:31:29 -0500] [Job 4] Removing document files.',
               'D [30/May/2018:15:31:29 -0500] [Job 5] Removing document files.',
               'D [30/May/2018:15:31:29 -0500] [Job 6] Removing document files.',
               'D [30/May/2018:15:31:29 -0500] [Job 7] Removing document files.',
               'D [30/May/2018:15:31:29 -0500] [Job 13] Removing document files.',
               'D [30/May/2018:15:31:29 -0500] [Job 14] Removing document files.',
               'D [30/May/2018:15:31:29 -0500] [Job 15] Removing document files.',
               'D [30/May/2018:15:31:29 -0500] [Job 16] Removing document files.',
               'D [30/May/2018:15:31:29 -0500] [Job 17] Removing document files.',
               'D [30/May/2018:15:31:29 -0500] [Job 18] Removing document files.',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 14] cupsdWriteClient error=0, used=0, state=HTTP_STATE_POST_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=1259, response=0x55eb2d7e9160(IPP_IDLE), pipe_pid=0, file=-1',
               'D [30/May/2018:15:31:29 -0500] [Client 14] Writing IPP response, ipp_state=DATA, old wused=0, new wused=0',
               'D [30/May/2018:15:31:29 -0500] [Client 14] bytes=0, http_state=0, data_remaining=0',
               'D [30/May/2018:15:31:29 -0500] [Client 14] Waiting for request.',
               'D [30/May/2018:15:31:29 -0500] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 15] Accepted from localhost (Domain)',
               'D [30/May/2018:15:31:29 -0500] [Client 15] Waiting for request.',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 15] PUT /admin/conf/cupsd.conf HTTP/1.1',
               'D [30/May/2018:15:31:29 -0500] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"',
               'D [30/May/2018:15:31:29 -0500] [Client 15] No authentication data provided.',
               'D [30/May/2018:15:31:29 -0500] cupsdIsAuthorized: username=""',
               'D [30/May/2018:15:31:29 -0500] [Client 15] WWW-Authenticate: Basic realm="CUPS", trc="y"',
               'D [30/May/2018:15:31:29 -0500] [Client 15] Closing connection.',
               'D [30/May/2018:15:31:29 -0500] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 15] Accepted from localhost (Domain)',
               'D [30/May/2018:15:31:29 -0500] [Client 15] Waiting for request.',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 16] Accepted from localhost (Domain)',
               'D [30/May/2018:15:31:29 -0500] [Client 16] Waiting for request.',
               'D [30/May/2018:15:31:29 -0500] [Client 15] HTTP_STATE_WAITING Closing on EOF',
               'D [30/May/2018:15:31:29 -0500] [Client 15] Closing connection.',
               'D [30/May/2018:15:31:29 -0500] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 15] Accepted from localhost (Domain)',
               'D [30/May/2018:15:31:29 -0500] [Client 15] Waiting for request.',
               'D [30/May/2018:15:31:29 -0500] [Client 16] HTTP_STATE_WAITING Closing on EOF',
               'D [30/May/2018:15:31:29 -0500] [Client 16] Closing connection.',
               'D [30/May/2018:15:31:29 -0500] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'D [30/May/2018:15:31:29 -0500] [Client 15] PUT /admin/conf/cupsd.conf HTTP/1.1',
               'D [30/May/2018:15:31:29 -0500] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"',
               'D [30/May/2018:15:31:29 -0500] [Client 15] Authorized as root using PeerCred',
               'D [30/May/2018:15:31:29 -0500] cupsdIsAuthorized: username="root"',
               'D [30/May/2018:15:31:29 -0500] cupsd is not idle any more, canceling shutdown.',
               'I [30/May/2018:15:31:29 -0500] Installing config file "/etc/cups/cupsd.conf"...',
               'D [30/May/2018:15:31:29 -0500] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"',
               'D [30/May/2018:15:31:29 -0500] [Client 14] Closing connection.',
               'D [30/May/2018:15:31:29 -0500] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"',
               'D [30/May/2018:15:31:29 -0500] [Client 15] Closing connection.',
               'D [30/May/2018:15:31:29 -0500] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"',
               'E [30/May/2018:15:31:29 -0500] Unknown directive JobPrivateAccess on line 84 of /etc/cups/cupsd.conf.',
               'E [30/May/2018:15:31:29 -0500] Unknown directive JobPrivateValues on line 85 of /etc/cups/cupsd.conf.',
               'E [30/May/2018:15:31:29 -0500] Unknown directive SubscriptionPrivateAccess on line 86 of /etc/cups/cupsd.conf.',
               'E [30/May/2018:15:31:29 -0500] Unknown directive SubscriptionPrivateValues on line 87 of /etc/cups/cupsd.conf.',
               "W [30/May/2018:15:31:29 -0500] CreateProfile failed: org.freedesktop.ColorManager.AlreadyExists:profile id 'Officejet_6700-Gray..' already exists",
               "W [30/May/2018:15:31:29 -0500] CreateProfile failed: org.freedesktop.ColorManager.AlreadyExists:profile id 'Officejet_6700-RGB..' already exists",
               "W [30/May/2018:15:31:29 -0500] CreateProfile failed: org.freedesktop.ColorManager.AlreadyExists:profile id 'Officejet_6700_fax-Gray..' already exists",
               "W [30/May/2018:15:31:29 -0500] CreateProfile failed: org.freedesktop.ColorManager.AlreadyExists:profile id 'Officejet_6700_fax-RGB..' already exists",
               "W [30/May/2018:15:31:29 -0500] CreateProfile failed: org.freedesktop.ColorManager.AlreadyExists:profile id 'Panasonic-KX-MB2030series-Gray..' already exists",
               "W [30/May/2018:15:31:29 -0500] CreateProfile failed: org.freedesktop.ColorManager.AlreadyExists:profile id 'Panasonic-KX-MB2030series-RGB..' already exists",
               "W [30/May/2018:15:31:29 -0500] CreateProfile failed: org.freedesktop.ColorManager.AlreadyExists:profile id 'PDF-Gray..' already exists",
               "W [30/May/2018:15:31:29 -0500] CreateProfile failed: org.freedesktop.ColorManager.AlreadyExists:profile id 'PDF-RGB..' already exists"],
 'error_log_debug_logging_unset': True}
Page 9 (Locale issues):
{'printer_page_size': u'Letter',
 'system_locale_lang': None,
 'user_locale_ctype': 'en_US',
 'user_locale_messages': 'en_US'}

**Comment by michaelrsweet** [comment]
*CUPS* doesn't look for libgs anywhere, because it is not part of CUPS. You should file an issue against the [cups-filters](https://github.com/openprinting/cups-filters) project instead...

**Comment by Michael-IDA** [comment]
Ah, thanks Michael!
