### ISSUE TITLE
CUPS 2.2.8: Tests fail

### ISSUE THREAD

**Issue by OdyX** [apple/cups#5322]
Thanks for the 2.2.8 update! But unfortunately, the tests fail quite early:

```
Running IPP compliance tests...
Performing 4.1-requests.test: PASS 
Performing 4.2-cups-printer-ops.test: FAIL
Performing 4.3-job-ops.test: ipptool: Bad integer value '' for "job-id" on line 65.
FAIL
Performing 4.4-subscription-ops.test: ipptool: Bad integer value '' for "notify-subscription-id" on line 51.
FAIL
Performing ipp-2.1.test: ipptool: Bad integer value '' for "job-id" on line 806.
FAIL

Running command tests...
Waiting for jobs to complete...
Performing 5.1-lpadmin.sh: FAIL
Waiting for jobs to complete...
Performing 5.2-lpc.sh: PASS
Waiting for jobs to complete...
Performing 5.3-lpq.sh: FAIL
Waiting for jobs to complete...
Performing 5.4-lpstat.sh: FAIL
Waiting for jobs to complete...
Performing 5.5-lp.sh: FAIL
Waiting for jobs to complete...
Performing 5.6-lpr.sh: FAIL
Waiting for jobs to complete...
Performing 5.7-lprm.sh: FAIL
Waiting for jobs to complete...
Performing 5.8-cancel.sh: FAIL
Waiting for jobs to complete...
Performing 5.9-lpinfo.sh: PASS
Performing restart test: ../systemv/lpstat: Invalid destination name in list "Test1".
FAIL (got '', expected 'Test Printer 1')
Test Summary
(…)
```

After a tedious `git bisect` session, I've come to the conclusion that commit 4c37eb9f77910f6f856fc540fc9a94a5885af17c is the culprit. Indeed, if I `git revert` it, the build succeeds.

**Comment by michaelrsweet** [comment]
Strange that I haven't seen this error when I run "make check" on macOS or Ubuntu... Investigating...

**Comment by OdyX** [comment]
Here's the full log:
[cups-str-2018-06-06-didier.html.txt](https://github.com/apple/cups/files/2076501/cups-str-2018-06-06-didier.html.txt)

And here's the patched tree that fails to build: https://github.com/OdyX/cups/commits/355576a29ac7a47c8d1ed29d12fb9116bf5ad866

**Comment by OdyX** [comment]
In order to avoid any doubt from the Debian patches; I've extracted a simple build script:
```bash
#!/bin/sh
set -e
aclocal
autoconf
./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=\${prefix}/include --mandir=\${prefix}/share/man --infodir=\${prefix}/share/info --sysconfdir=/etc --localstatedir\
        --with-docdir=/usr/share/cups/doc-root \
        --localedir=/usr/share/cups/locale \
        --enable-libpaper \
        --enable-ssl \
        --enable-gnutls \
        --enable-threads \
        --enable-static \
        --enable-debug \
        --enable-dbus \
        --with-dbusdir=/etc/dbus-1 \
        --enable-gssapi \
        --enable-avahi \
        --disable-launchd \
        --with-cups-group=lp \
        --with-system-groups=lpadmin \
        --with-rundir=/run/cups \
        --with-printcap=/run/cups/printcap \
        --with-log-file-perm=0640 \
        --with-local_protocols='dnssd' \
        --with-systemd=/lib/systemd/system \
        --enable-libusb
make -j4

CUPS_TESTBASE=$(shell mktemp -d /tmp/cups.XXXXXX) make check
```

I can confirm that in a current Debian `sid` chroot, https://github.com/apple/cups/tree/v2.2.8 directly from the git repository builds but has tests failures whereas https://github.com/apple/cups/tree/v2.2.7 succeeds (minus some error_log counting glitches).

**Comment by OdyX** [comment]
I can confirm that the patch https://github.com/apple/cups/commit/455c52a027ab3548953372a0b7bdb0008420e9ba from https://github.com/apple/cups/pull/5330 addressing https://github.com/apple/cups/issues/5325 fixes the 2.2.8 build on Debian. So this and #5325 seem to be duplicates. Good that the tests fail! :-)

**Comment by michaelrsweet** [comment]
and strange that I still cannot reproduce in my local checkouts... :/

**Comment by michaelrsweet** [comment]
OK, I did a fresh checkout in a fresh VM and was able to reproduce...  Fixes have been pushed:

[master 592a7a7b5] Fix regressions in ippValidateAttribute (Issue #5322, Issue #5330)

[branch-2.2 18545a5e7] Fix regressions in ippValidateAttribute (Issue #5322, Issue #5330)
