### ISSUE TITLE
Filter failed?

### ISSUE THREAD

**Issue by foxxx** [apple/cups#5333]
Cant print on CUPS 2.2.1
 stopped 
"Filter failed"

Can anyone give me some insight in what to do here? 

We are trying to print to a thermal printer, on a different server running CUPS 1.5.4 we can print OK, but on a newly built fresh server with CUPS 2.2.1, with the printer drivers/ppd/filter installed we get this error.

Thanks.

**Comment by michaelrsweet** [comment]
Generally speaking, look at your /var/log/cups/error_log file which should contain the debug log messages leading up to the failure.  More than likely you are missing one of the drivers you are using on the other server.

**Comment by foxxx** [comment]
D [11/Jun/2018:12:56:59 +0000] [Job 4] execv failed: Exec format error
D [11/Jun/2018:12:56:59 +0000] [Job 4] PID 988 (/usr/lib/cups/filter/rastertoprinter) stopped with status 108 (Exec format error)

**Comment by michaelrsweet** [comment]
"rastertoprinter" is Gutenprint - probably you copied the binary over but the new server can't run it.

Try installing Gutenprint on the new server.

**Comment by foxxx** [comment]
Trying now, thanks

**Comment by foxxx** [comment]
printer-driver-gutenprint is installed already (tried to remove then install again) still same error. should i try to build from source?

**Comment by foxxx** [comment]
Actually I think you might be talking about the drivers for the printer I have, I've re-copied them into the folders, still have the issue. could it be a different error i need to find?

**Comment by michaelrsweet** [comment]
I think the filter name changed, so try updating the printer with a newer PPD.

**Comment by foxxx** [comment]
Newer ppd from the manufacturer?

**Comment by michaelrsweet** [comment]
Newer Gutenprint PPD. If you use the web interface, you can modify the print queue and select the correct make/model from there. From the GNOME UI the process will be similar.

**Comment by RobertKrawitz** [comment]
rastertoprinter is ancient - it was renamed in 2003, prior to the rename from Gimp-Print to Gutenprint (between 4.3.23 and 4.3.24).  That would have to be a very badly out of date PPD file.  Gutenprint can't auto-update PPD files that old.

**Comment by foxxx** [comment]
The make & model isn't in the list by default, I have the PPD from the manufacturer which I have installed and a rastertoprinter filter which they also sent. I take it that's probably the issue? The code?

**Comment by michaelrsweet** [comment]
Yes, if the manufacturer provided a PPD and an old Gutenprint, that is likely the issue there.

What is the make and model of the printer?

**Comment by foxxx** [comment]
I can discuss with the manufacturer, but I don't think they will write new code, is the answer to do like I was trying previously, using cups 1.5.4? Printer is an 80mm OEM thermal printer from China.

**Comment by foxxx** [comment]
OK thank you

**Comment by foxxx** [comment]
could it be a 32 vs 64 bit compilation issue? if they supply a new driver that we compile on a 64bit machine could that solve it?

**Comment by michaelrsweet** [comment]
Possibly, but there is no way to know from the error message...

**Comment by foxxx** [comment]
Ok thanks, I'll keep persisting. 4 different brand printers and a solid week plus of effort and I've been getting nowhere so I thought I'd ask here! Appreciate the feedback and your time to help. Thanks

**Comment by jhcloos** [comment]
If the printer accepts ESCPOS, try out a web search for:

  rastertozj

You’ll get a number of hits for software which can accept cups' raster format and output escpos for (most of) those printers.

**Comment by foxxx** [comment]
Thanks, i'll try

**Comment by foxxx** [comment]
This worked -- however the print speed is slow, and the paper cutting doesn't work. I'll keep at it. Thanks.
