### ISSUE TITLE
gcrypt.h: No such file or directory

### ISSUE THREAD

**Issue by foxxx** [apple/cups#5334]
When trying to build 1.5.4 from source, I get this error, is there any way to resolve it?

~/cups-1.5.4 $ sudo make
Using ARCHFLAGS=
Using ALL_CFLAGS=-I.. -D_CUPS_SOURCE -isystem /usr/include/mit-krb5  -isystem /usr/include/mit-krb5  -I/usr/include/libusb-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/arm-linux-gnueabihf/dbus-1.0/include -DDBUS_API_SUBJECT_TO_CHANGE -I/usr/include/p11-kit-1 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE -D_REENTRANT
Using ALL_CXXFLAGS=-I.. -D_CUPS_SOURCE -isystem /usr/include/mit-krb5   -I/usr/include/p11-kit-1 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_THREAD_SAFE -D_REENTRANT
Using CC=gcc
Using CXX=gcc
Using DSOFLAGS=-L../cups  -Wl,-soname,all -shared -Wall -Wno-format-y2k -Wunused -fPIC -Os -g -fstack-protector -Wno-tautological-compare -D_GNU_SOURCE
Using LDFLAGS=-L../cgi-bin -L../cups -L../filter -L../ppdc -L../scheduler -fPIE -pie -Wall -Wno-format-y2k -Wunused -fPIC -Os -g -fstack-protector -Wno-tautological-compare -D_GNU_SOURCE
Using LIBS=-lcups -L/usr/lib/arm-linux-gnueabihf/mit-krb5 -Wl,-z,relro -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lgnutls  -lz -lpthread -lcrypt -lm
Making all in cups...
Compiling adminutil.c...
In file included from cups-private.h:29:0,
                 from adminutil.c:33:
http-private.h:96:24: fatal error: gcrypt.h: No such file or directory
 #    include <gcrypt.h>
                        ^
compilation terminated.
../Makedefs:281: recipe for target 'adminutil.o' failed
make[1]: *** [adminutil.o] Error 1
Makefile:31: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by foxxx** [comment]
installing libgcrypt20-dev solved it

**Comment by amansmarters** [comment]
yes it worked for me today

**Comment by whmcs-smarters** [comment]
Yes, it worked for me, too, Actually, I changed the ubuntu version from 18 to 20.04 that's why I need this command to make plugin files too. Thanks
