### ISSUE TITLE
undefined symbol: _httpWriteGNUTLS

### ISSUE THREAD

**Issue by foxxx** [apple/cups#5335]
using 1.5.4, when we try to restart we have this error,

sudo /etc/init.d/cups restart
/usr/sbin/cupsd: symbol lookup error: /usr/sbin/cupsd: undefined symbol: _httpWriteGNUTLS
cups: unable to restart scheduler.

is anyone able to help on what that might be and how to resolve it? 

Thanks

**Comment by michaelrsweet** [comment]
This usually means you have a mismatch between the cupsd and libcups on your system.

**Comment by foxxx** [comment]
What's the difference? Can you point me towards a fix / where I can look for a fix?

**Comment by michaelrsweet** [comment]
More than likely you have tried to install CUPS from source over your distro packages, which generally doesn't work out too well... :/

Try reinstalling the OS packages, or remove them and then reinstall from source. (but generally installing an older version of CUPS is a recipe for disaster)

**Comment by foxxx** [comment]
Yeah, I'm trying 2 ways at the moment and I'm stuck at both ends. 1 server running 2.2.1 installed from apt-get where I am having the filter issue, and the other running 1.5.4 from source with the other issue described here. I have another much older server that has 1.5.4 installed and i can print from there OK, however I can't use that server in the long term. I'll find the error on the 2.2.1 version and go from there...
