### ISSUE TITLE
Migration from CUPS from 1.3.7 to 1.6.3

### ISSUE THREAD

**Issue by irfkhan** [apple/cups#5336]
We have had roughly 400 active printer in 1.3.7 running on ## RHEL 4 , 32BIT (Very stable) and we have started migrating them on the piecemeal basis to ## RHEL 7 1.6.3 64 BIT. Had fair amount of success until we went in critical high visibility label printing printers (Zebra)

Became complete chaos, orientation was mess, labels couldnt print. :( .

Unfortunately , Zebra printers are last leg of migration and most critical piece to get me to latest CUPS. Right now I am running both CUPS in parallel. 

Any idea is welcome. 

So we reverted those printers back to 1.3.7. After reading lots of other posts , I believe the issue is with filter rastertolabel

Now rastertolabel which works is of 32BIT and thus would want to know how do I get same old version which works for me in 32BIT and how do I compile the same in 64BIT.

This is 32BIT Info
************************************************
cups4 /usr/lib/cups/filter# uname -a
Linux cups4.us.colorcon.com 2.6.18-238.12.1.el5PAE #1 SMP Sat May 7 20:37:06 EDT 2011 i686 i686 i386 GNU/Linux
cups4 /usr/lib/cups/filter# rpm -qa | grep cups
cups-devel-1.3.7-30.el5_9.3
libgnomecups-0.2.2-9
pwd
cups-libs-1.3.7-30.el5_9.3
hal-cups-utils-0.6.2-5.2.el5
gimp-print-cups-4.2.7-22.2.el5
cups-1.3.7-30.el5_9.3
cups-pdf-2.5.0-1
libgnomecups-devel-0.2.2-9
cups-lpd-1.3.7-30.el5_9.3
cups4 /usr/lib/cups/filter# pwd
/usr/lib/cups/filter
cups4 /usr/lib/cups/filter# ls -tlr rastertolabel
-rwxr-xr-x 1 root root 22012 Feb 25  2013 rastertolabel

This is 64BIT Info
************************************************
[root@cupsprd1 filter]# ls -tlr rastertolabel
-rwxr-xr-x. 1 root root 23696 Apr 10 22:05 rastertolabel

[root@cupsprd1 ~]# uname -a
Linux cupsprd1.us.colorcon.com 4.1.12-94.3.9.el7uek.x86_64 #2 SMP Fri Jul 14 20:09:40 PDT 2017 x86_64 x86_64 x86_64 GNU/Linux

[root@cupsprd1 filter]# rpm -qa | grep cups
cups-filters-libs-1.0.35-22.el7.x86_64
cups-1.6.3-35.el7.x86_64
cups-filesystem-1.6.3-35.el7.noarch
cups-libs-1.6.3-35.el7.x86_64
cups-filters-1.0.35-22.el7.x86_64
cups-client-1.6.3-35.el7.x86_64
python-cups-1.9.63-6.el7.x86_64
ghostscript-cups-9.07-28.el7_4.2.x86_64

**Comment by michaelrsweet** [comment]
Sorry, but both CUPS 1.3.7 and 1.6.3 are *obsolete*, so there is very little we can do to help you. Red Hat provides support for CUPS on Enterprise Linux...

As for the rastertolabel drivers, you *may* be able to grab the sources for rastertolabel in CUPS 1.3.x and recompile against 1.6.x, but the orientation issues might also be coming from the Linux RIP filters (likely Ghostscript given your RPM packages), which is not software we support, either... :/

CUPS 2.2 has an updated ZPL driver for the Zebra printers that fixes a number of issues with ZPL II compatibility (needed for newer printers) as well as the orientation being wrong (a bug that probably got introduced in CUPS 1.4 and was only noticed last year...)

**Comment by irfkhan** [comment]
Thanks for quick response, appreciate your support.

where can I find the source of rastertolabel.c on 1.3.7? or for 1.3.7 64bit? Would it be here on github?

**Comment by irfkhan** [comment]
Never mind, found it, thanks

**Comment by irfkhan** [comment]
Hi Michael

So we upgrade to 2.2.8 and I have indeed same issue, can you point in direction of where to see?

I can enable debug2 would that give me any hint as to why its not rotating? I have PDF that I can attach here.

Wanted to ask before I start uploading the info, if u could help

Thanks in Advance

IK

**Comment by michaelrsweet** [comment]
So, for starters how do you mean "not rotating"? The current label drivers all operate so that the top of the page starts at the leading edge of the label/roll - the labels thus will appear "upside down" when printed.

You can use the "orientation-requested=6" option to flip the labels around - if that "fixes" the problem for you then the following command will set the default orientation:

    lpadmin -p printer -o orientation-requested-default=6

**Comment by zdohnal** [comment]
Hi @irfkhan ,
would you mind reporting the issue (with cups-1.6.3) to Red Hat? Preferably as support case at access.redhat.com .
Just checking - 'orientation was a mess, labels couldn't print' - do you mean you use options '-o landscape -o page-label="Some-Label"' when you print?

**Comment by irfkhan** [comment]
Hi

I'm sorry but we did figure out the issue and have fixed the same.

In the previous version of cups the rotation would not work and thus we had to make the RTF template for report to size differently than the actual size of the label for rotation to kick in.

In the new version of cups and we had to revert the template size back to normal for the rotation to kick in automatically.

Thanks
IK
________________________________
