### ISSUE TITLE
Question: Regarding cups API functions for cups standard/common options.

### ISSUE THREAD

**Issue by ayush268** [apple/cups#5340]
Is there a way (function) in the cups API to get supported/default values for cups standard/common options e.g. page-border ?
Also how can we get the options shown by doing `lpoptions` via cups API functions, passing option_name as "job-creation-attributes" to `cupsFindDestSupported` does not give me all the options.

**Comment by michaelrsweet** [comment]
What version of CUPS are you using?

WRT things like "page-border", the list of supported values has been unchanged for over 15 years (last changes early in CUPS 1.1.x development) and so can be considered static. We can look at providing a page-border-supported attribute but it won't help you today...

What printing options are not listed in the "job-creation-attributes-supported" attribute?

**Comment by ayush268** [comment]
The CUPS version is 2.2.7.
The printing options that are not listed in the "job-creation-attributes" -> collate, fit-to-page, mirror, number-up-layout, outputorder, page-border.

I tried using these options with `lp` command and they were working fine. I was thinking why these options were not included as "job-creation-attributes-supported" because they work for files of all types.

**Comment by michaelrsweet** [comment]
Of those options, only `number-up-layout` and `page-border` are generally supported for documents (but not for images). Of the rest:

- `collate` is a PPD option. The `multiple-document-handling` option/attribute is the proper replacement for copy collation, with `separate-documents-uncollated-copies` for uncollated copies and `separate-documents-collated-copies`, `single-document`, or `single-document-new-page` for collated copies.
- `fit-to-page` is deprecated in favor of the `print-scaling` option/attribute.
- `mirror` is a PPD option. There is currently no generic replacement (but there are some possibilities).
- `outputorder` is a PPD option. The `page-delivery` option/attribute (values `same-order` or `reverse-order`) is the correct IPP replacement but is not yet supported by the cups-filters project (I am looking at changed in cupsd to do a mapping at print-time...)

**Comment by michaelrsweet** [comment]
[master 91505c0a3] Report all supported Job Creation attributes and their values (Issue #5340)

**Comment by tillkamppeter** [comment]
The `page-delivery` option/attribute (values `same-order` or `reverse-order`) is supported by cups-filters (in the `pdftopdf` filter now (version 1.20.4 which I released some days ago).
