### ISSUE TITLE
MacOS10.14 Printer Driver

### ISSUE THREAD

**Issue by glockyb** [apple/cups#5341]
1.Before OS10.14, can load pde to the print interface normally.

Q：But 10.14 Later,PDE never loads properly to the print interface.
Please give me some advice, Thanks.

**Comment by michaelrsweet** [comment]
Please report macOS bugs, particularly for pre-release betas, to bugreport.apple.com.

(this is not a new issue, library validation and sandboxing have interfered with PDEs for many years now - this is documented in the CUPS PPD specification available on cups.org)

**Comment by glockyb** [comment]
For example:The following records in PPD
*APDialogExtension:	"/Library/Printers/Brother/PDEs/BRInkQuality10.bundle"
But there is no corresponding PDE in the UI interface of print.

**Comment by michaelrsweet** [comment]
@glockyb Please report macOS bugs to <bugreport.apple.com>. This is not a new issue, and will increasingly affect your drivers as security is tightened on macOS.

**Comment by glockyb** [comment]
Ok, thank you.
