### ISSUE TITLE
SNMPv3 Support

### ISSUE THREAD

**Issue by nayners** [apple/cups#5342]
"SNMPv1 only" forces printers to have this legacy functionality enabled. For environments that want to make the switch to v3 for secure traffic and authentication, this keeps printers in a privacy-exposed state.

Privacy concerns stem from the information available on devices that are exposed via SNMP walking which includes print job header data and the individual user who printed them. There are potential PII and privacy concerns associated with this.

Changing the community name is only (partially) effective against outside visibility, however, if someone has access to a corp machine it is trivial to determine what the community name is (clear text).

What are the plans to migrate to SNMPv3 support for printer enumeration and

**Comment by michaelrsweet** [comment]
Sorry, SNMP support is basically on life support. We have no plans to support SNMPv3 and the future of CUPS printing is all DNS-SD or LDAP for discovery and IPP for printing and status monitoring.
