### ISSUE TITLE
Can't open CUPS raster file.DEBUG

### ISSUE THREAD

**Issue by upuil** [apple/cups#5346]
I can print in the windows client but can't print in the mac.  In my server cups web interface, the job state is showing `stopped  "Filter failed".`

`Job stopped due to filter errors; please consult the error_log file for details.`

Any ideas as to what's going on?
## The error_log  indicate that `Can't open CUPS raster file.DEBUG:`
```
D [30/Jun/2018:00:11:59 -0400] [Job 46] PID 19569 (/opt/epson-inkjet-printer-201601w/cups/lib/filter/epson_inkjet_printer_filter) stopped with status 1.
D [30/Jun/2018:00:11:59 -0400] [Job 46] Hint: Try setting the LogLevel to "debug" to find out more.
D [30/Jun/2018:00:11:59 -0400] [Job 46] Can't open CUPS raster file.DEBUG: Printing on printer with URI: usb://EPSON/L380%20Series?serial=583251373038393410&interface=1
D [30/Jun/2018:00:11:59 -0400] [Job 46] libusb_get_device_list=4
D [30/Jun/2018:00:11:59 -0400] [Job 46] STATE: +connecting-to-device
D [30/Jun/2018:00:11:59 -0400] [Job 46] STATE: -connecting-to-device
D [30/Jun/2018:00:11:59 -0400] [Job 46] Printer found with device ID: MFG:EPSON;CMD:ESCPL2,BDC,D4,D4PX,END4;MDL:L380 Series;CLS:PRINTER;DES:EPSON L380 Series;CID:EpsonStd10;FID:FXN,DPN,WFN,ETN,AFN,DAN,WRN;RID:60;DDS:011180;ELG:0E64; Device URI: usb://EPSON/L380%20Series?serial=583251373038393410&interface=1
D [30/Jun/2018:00:11:59 -0400] [Job 46] Device protocol: 2
D [30/Jun/2018:00:11:59 -0400] [Job 46] Sending data to printer.
D [30/Jun/2018:00:11:59 -0400] [Job 46] Sent 0 bytes...
D [30/Jun/2018:00:11:59 -0400] [Job 46] Waiting for read thread to exit...
D [30/Jun/2018:00:11:59 -0400] [Job 46] Read 190 bytes of back-channel data...
D [30/Jun/2018:00:11:59 -0400] [Job 46] PID 19570 (/usr/lib/cups/backend/usb) exited with no errors.
D [30/Jun/2018:00:11:59 -0400] [Job 46] End of messages
D [30/Jun/2018:00:11:59 -0400] [Job 46] printer-state=3(idle)
D [30/Jun/2018:00:11:59 -0400] [Job 46] printer-state-message="Sending data to printer."
D [30/Jun/2018:00:11:59 -0400] [Job 46] printer-state-reasons=none
E [30/Jun/2018:00:14:19 -0400] [Job 54] Stopping unresponsive job.
E [30/Jun/2018:00:17:02 -0400] [Job 46] Stopping unresponsive job.
```

**Comment by michaelrsweet** [comment]
Sorry, there is not enough information to help you with, and we don't develop the driver you are using (looks like an Epson driver). If I was to guess, the Epson driver is trying to run Ghostscript directly but the version of Ghostscript bundled with your Linux distribution is not compatible or missing.

**Comment by apolinux** [comment]
I had same problem with xubuntu 19 and after following the config steps from: 
https://wiki.archlinux.org/index.php/CUPS/Printer_sharing#Between_GNU/Linux_systems
linux by it self configured printer. It appears in device URI as:
implicitclass://EPSON_L3110_Series_REMOTESERVNAME
and make and model: Remote printer: Epson L3110 Series - epson-inkjet-printer-escpr 1.6.35-1lsb3.2 (Seiko Epson Corporation LSB 3.2)
may be it could serve as help.
