### ISSUE TITLE
CUPS shouldn't undefine __attribute__ in versioning.h

### ISSUE THREAD

**Issue by simonis** [apple/cups#5349]
CUPS undefines "\_\_attribute__" in cups/versioning.h if "\_\_GNUC__" isn't defined. Unfortunately this breaks compilers like SunStudio on Solaris which support the "\_\_attribute__" builtins but don't define "\_\_GNUC__".

I don't think it is necessary to undefine "\_\_attribute__" at all. We take great care to detect if "\_\_attribute__" is supported by the compiler and if it is supported to detect which actual attributes the compiler supports. Only on supported platforms we finally define macros which expand to "\_\_attribute__" builtins. 

So there's really no reason to undefine "\_\_attribute__" at  the end of cups/versioning.h

See also: https://lists.cups.org/pipermail/cups-devel/2018-July/017150.html

**Comment by michaelrsweet** [comment]
We don't undefine it, we define it to replace to nothing because it is a GNU extension and there are a bunch of places in the CUPS source code where we'd like to use it without a lot of `#ifdef __GNUC__` conditionals.

I will investigate whether we can safely change how we do this - sometimes macro replacements of __attribute__ don't work... :/

**Comment by michaelrsweet** [comment]
@simonis I've pushed initial changes to move away from using __attribute__ directly in any of the portable code sections (now defining specific `_CUPS_xxx` macros) although I still haven't updated the versioning.h code to enable the annotations for the Sun/Oracle C compiler.

Right now my focus is on CUPS 2.3.x. If I have time I'll try backporting to 2.2.x but no promises.

**Comment by michaelrsweet** [comment]
OK, I've incorporated these changes into the 2.2.x branch as well.

**Comment by simonis** [comment]
Thanks a lot Michael!
