### ISSUE TITLE
Custom Options 

### ISSUE THREAD

**Issue by glockyb** [apple/cups#5351]
Hello, I need to use the custom text input box when modifying PPD, using the following code：
**********************************************
*OpenUI HPPinToPrint/PIN To Print: PickOne
*OrderDependency: 10 AnySetup *HPPinToPrint
*DefaultHPPinToPrint: 
*HPPinToPrint Title/PIN To Print: ""
*CloseUI: *HPPinToPrint

*CustomHPPinToPrint True: ""
*ParamCustomHPPinToPrint PIN/PIN To Print:  1 string 0 64 
**********************************************
But there is a drop-down arrow at the end of the input box. How can we remove this drop-down arrow?

**Comment by michaelrsweet** [comment]
@glockyb You don't mention what platform you are running on or where you are seeing this UI?

**Comment by michaelrsweet** [comment]
The primary UI is a list of choices. That is the UI that macOS presents.

That said, the macOS UI is not something we can support here. Please file a bug report on <bugreport.apple.com> if you'd like macOS-specific help.

**Comment by glockyb** [comment]
If I want to customize a text input box that can enter a string in PPD, but the optional value provided by Custom options does not meet the current requirements, is this related to the system?
