### ISSUE TITLE
Plotter Printing : Ability to print long side first

### ISSUE THREAD

**Issue by SoniaBalodi** [apple/cups#5352]
Hello,

I am trying to print images of different sizes (A4, A3 and A2) to plotter HP Designjet T520 using cups server and ipp library. 
Data flow is : Application sends image to cups server using ipp library - https://github.com/williamkapke/ipp . Cups server doesnt have driver for model HP Designjet T520 plotter, an alternate driver HP Designjet T1100 pcl is used. CUPs server prints to plotter using HP Jet Direct connection on port 9100. 
Everything works ok except one thing - to print long side of the image first. Plotter always prints short side of the image always.

It would be helpful if you could suggest any alternative through which this requirement could be achieved. Any ipp attribute which could be used for the same ?

Many thanks !
Regards,
Sonia

**Comment by michaelrsweet** [comment]
You need to specify a custom roll size for "media":

    roll_custom_WIDTHxLENGTHin
    roll_custom_WIDTHxLENGTHmm

e.g.:

    roll_custom_297x210mm

for long-edge A4.

**Comment by SoniaBalodi** [comment]
Thankyou @michaelrsweet , I will definitely try this. right now I am passing media : iso_a4_210x297mm for A4 images.
And now that you mentioned this attribute, I also found a media value - 'om_a-4-transverse_297.04x209.9mm' for A4 long-edge in drivers default settings in cups.  Is it pointing to the same thing - printing A4 with long edge first ?

**Comment by michaelrsweet** [comment]
@SoniaBalodi Yes, that is a CUPS-generated media size from the driver's PPD...

**Comment by SoniaBalodi** [comment]
@michaelrsweet : I would like to inform you that your suggestion to use media-size from driver's PPD worked for me :+1: 
Somehow copies ipp attribute doesnt seems to do any change to print count.
Print request consists of : 
1) job-attributes-tag having 'copies' and 'media'='om_a-4-transverse_297.04x209.9mm' attributes 
2) operation tag having 'job-name' and 'document-format'='image/png'

I also checked printer attributes using 'Get-Printer-Attributes' operation and found copies attribute is supported. (Below I pasted it). But looks like plotter doesn't seem to understand this attribute .. Any suggestions with this ?


---------------------------


{"version":"2.0","statusCode":"successful-ok","id":86288381,"operation-attributes-tag":{"attributes-charset":"utf-8","attributes-natural-language":"en-us"},"printer-attributes-tag":{"marker-change-time":0,"printer-config-change-date-time":"2018-08-17T03:25:43.000Z","printer-config-change-time":1531812343,"printer-current-time":"2018-08-17T11:57:45.000Z","printer-dns-sd-name":"UAStore10 @ msp-cups-dev-1","printer-error-policy":"retry-job","printer-error-policy-supported":["abort-job","retry-current-job","retry-job","stop-printer"],"printer-icons":"http://10.97.179.208:631/icons/UAStore10.png","printer-is-accepting-jobs":true,"printer-is-shared":true,"printer-more-info":"http://10.97.179.208:631/printers/UAStore10","printer-op-policy":"default","printer-state":"idle","printer-state-change-date-time":"2018-08-17T03:25:04.000Z","printer-state-change-time":1531812304,"printer-state-message":"Waiting for printer to finish.","printer-state-reasons":"none","printer-type":8450124,"printer-up-time":1531843065,"printer-uri-supported":"ipp://10.97.179.208:631/printers/UAStore10","queued-job-count":0,"uri-authentication-supported":"requesting-user-name","uri-security-supported":"none","printer-name":"UAStore10","printer-location":"UAStore10","printer-info":"UAStore10","printer-organization":"","printer-organizational-unit":"","printer-uuid":"urn:uuid:6728a684-8213-3097-7794-9f3da076df5a","job-quota-period":0,"job-k-limit":0,"job-page-limit":0,"job-sheets-default":["none","none"],"device-uri":"socket://10.141.148.196","document-format-supported":["application/octet-stream","application/pdf","application/postscript","application/vnd.adobe-reader-postscript","application/vnd.cups-command","application/vnd.cups-pdf","application/vnd.cups-pdf-banner","application/vnd.cups-postscript","application/vnd.cups-raster","application/vnd.cups-raw","application/x-cshell","application/x-csource","application/x-perl","application/x-shell","image/gif","image/jpeg","image/png","image/pwg-raster","image/tiff","image/urf","image/x-bitmap","image/x-photocd","image/x-portable-anymap","image/x-portable-bitmap","image/x-portable-graymap","image/x-portable-pixmap","image/x-sgi-rgb","image/x-sun-raster","image/x-xbitmap","image/x-xpixmap","image/x-xwindowdump","text/css","text/html","text/plain"],"pwg-raster-document-resolution-supported":[[150,150,"dpi"],[300,300,"dpi"],[600,600,"dpi"]],"pwg-raster-document-sheet-back":"normal","pwg-raster-document-type-supported":["adobergb-8","adobergb-16","black-1","black-8","black-16","cmyk-8","cmyk-16","rgb-8","rgb-16","sgray-1","sgray-8","sgray-16","srgb-8","srgb-16"],"copies-default":1,"document-format-default":"application/octet-stream","job-cancel-after-default":10800,"job-hold-until-default":"no-hold","job-priority-default":50,"number-up-default":1,"notify-lease-duration-default":86400,"notify-events-default":"job-completed","print-quality-default":"normal","color-supported":true,"pages-per-minute":1,"pages-per-minute-color":1,"print-quality-supported":["draft","normal","high"],"printer-make-and-model":"HP DesignJet T1100 pcl, 1.0","media-default":"om_a-4-transverse_297.04x209.9mm","media-col-default":{"media-size":{"x-dimension":29704,"y-dimension":20990},"media-bottom-margin":1016,"media-left-margin":508,"media-right-margin":508,"media-top-margin":1016,"media-source":"main-roll","media-type":"paper"},"media-supported":["na_letter_8.5x11in","na_ledger_11x17in","na_c_17x22in","na_d_22x34in","na_e_34x44in","na_arch-a_9x12in","oe_archa-transverse_12x9in","na_arch-b_12x18in","oe_archb-transverse_18x12in","na_arch-c_18x24in","oe_archc-transverse_24x18in","na_arch-d_24x36in","oe_archd-transverse_36x24in","om_a-0-d_841.02x4755.44mm","om_a-0-c_841.02x3566.58mm","om_a-0-b_841.02x2377.72mm","iso_a0_841x1189mm","iso_a1_594x841mm","om_a-1-transverse_841.02x594.08mm","iso_a2_420x594mm","om_a-2-transverse_594.08x420.16mm","iso_a3_297x420mm","om_a-3-transverse_420.16x297.04mm","iso_a4_210x297mm","om_a-4-transverse_297.04x209.9mm","iso_a5_148x210mm","om_a-5-transverse_209.9x148.17mm","custom_min_70.56x70.56mm","custom_max_42x109.068in"],"media-size-supported":[{"x-dimension":21590,"y-dimension":27940},{"x-dimension":27940,"y-dimension":43180},{"x-dimension":43180,"y-dimension":55880},{"x-dimension":55880,"y-dimension":86360},{"x-dimension":86360,"y-dimension":111760},{"x-dimension":22860,"y-dimension":30480},{"x-dimension":30480,"y-dimension":22860},{"x-dimension":30480,"y-dimension":45720},{"x-dimension":45720,"y-dimension":30480},{"x-dimension":45720,"y-dimension":60960},{"x-dimension":60960,"y-dimension":45720},{"x-dimension":60960,"y-dimension":91440},{"x-dimension":91440,"y-dimension":60960},{"x-dimension":84102,"y-dimension":475544},{"x-dimension":84102,"y-dimension":356658},{"x-dimension":84102,"y-dimension":237772},{"x-dimension":84102,"y-dimension":118886},{"x-dimension":59408,"y-dimension":84102},{"x-dimension":84102,"y-dimension":59408},{"x-dimension":42016,"y-dimension":59408},{"x-dimension":59408,"y-dimension":42016},{"x-dimension":29704,"y-dimension":42016},{"x-dimension":42016,"y-dimension":29704},{"x-dimension":20990,"y-dimension":29704},{"x-dimension":29704,"y-dimension":20990},{"x-dimension":14817,"y-dimension":20990},{"x-dimension":20990,"y-dimension":14817},{"x-dimension":[7056,106680],"y-dimension":[7056,4572000]}],"media-source-supported":["manual","main-roll"],"media-type-supported":["paper","transparency","velum","polyester","translucent","special","photographic-glossy"],"media-bottom-margin-supported":1016,"media-left-margin-supported":508,"media-right-margin-supported":508,"media-top-margin-supported":1016,"output-bin-supported":"face-down","output-bin-default":"face-down","print-color-mode-supported":["monochrome","color"],"print-color-mode-default":"color","printer-resolution-supported":[[150,150,"dpi"],[300,300,"dpi"],[600,600,"dpi"]],"printer-resolution-default":[300,300,"dpi"],"sides-supported":"one-sided","sides-default":"one-sided","printer-commands":["AutoConfigure","Clean","PrintSelfTestPage"],"port-monitor":"none","port-monitor-supported":"none","finishings-supported":"none","finishings-default":"none","charset-configured":"utf-8","charset-supported":["us-ascii","utf-8"],"compression-supported":["none","gzip"],"copies-supported":[1,9999],"cups-version":"2.1.3","generated-natural-language-supported":"en-us","ipp-features-supported":"subscription-object","ipp-versions-supported":["1.0","1.1","2.0","2.1"],"ippget-event-life":15,"job-cancel-after-supported":[0,2147483647],"job-creation-attributes-supported":["copies","finishings","ipp-attribute-fidelity","job-hold-until","job-name","job-priority","job-sheets","media","media-col","multiple-document-handling","number-up","output-bin","orientation-requested","page-ranges","print-color-mode","print-quality","printer-resolution","sides"],"job-hold-until-supported":["no-hold","indefinite","day-time","evening","night","second-shift","third-shift","weekend"],"job-ids-supported":true,"job-k-octets-supported":[0,50758760],"job-priority-supported":100,"job-settable-attributes-supported":["copies","finishings","job-hold-until","job-name","job-priority","media","media-col","multiple-document-handling","number-up","output-bin","orientation-requested","page-ranges","print-color-mode","print-quality","printer-resolution","sides"],"job-sheets-supported":["none","classified","confidential","form","secret","standard","topsecret","unclassified"],"jpeg-k-octets-supported":[0,50758760],"jpeg-x-dimension-supported":[0,65535],"jpeg-y-dimension-supported":[1,65535],"media-col-supported":["media-bottom-margin","media-left-margin","media-right-margin","media-size","media-source","media-top-margin","media-type"],"multiple-document-handling-supported":["separate-documents-uncollated-copies","separate-documents-collated-copies"],"multiple-document-jobs-supported":true,"multiple-operation-time-out":300,"multiple-operation-time-out-action":"process-job","natural-language-configured":"en-us","notify-attributes-supported":["printer-state-change-time","notify-lease-expiration-time","notify-subscriber-user-name"],"notify-lease-duration-supported":[0,2147483647],"notify-max-events-supported":100,"notify-events-supported":["job-completed","job-config-changed","job-created","job-progress","job-state-changed","job-stopped","printer-added","printer-changed","printer-config-changed","printer-deleted","printer-finishings-changed","printer-media-changed","printer-modified","printer-restarted","printer-shutdown","printer-state-changed","printer-stopped","server-audit","server-restarted","server-started","server-stopped"],"notify-pull-method-supported":"ippget","notify-schemes-supported":["dbus","mailto","rss"],"number-up-supported":[1,2,4,6,9,16],"operations-supported":["Print-Job","Validate-Job","Create-Job","Send-Document","Cancel-Job","Get-Job-Attributes","Get-Jobs","Get-Printer-Attributes","Hold-Job","Release-Job","Pause-Printer","Resume-Printer","Purge-Jobs","Set-Printer-Attributes","Set-Job-Attributes","Get-Printer-Supported-Values","Create-Printer-Subscriptions","Create-Job-Subscription","Get-Subscription-Attributes","Get-Subscriptions","Renew-Subscription","Cancel-Subscription","Get-Notifications","Enable-Printer","Disable-Printer","Hold-New-Jobs","Release-Held-New-Jobs","Cancel-Jobs","Cancel-My-Jobs","Close-Job",16385,16386,16387,16388,16389,16390,16391,16392,16393,16394,16395,16396,16397,16398,16399,16423,"Restart-Job"],"orientation-requested-supported":["portrait","landscape","reverse-landscape","reverse-portrait"],"page-ranges-supported":true,"pdf-k-octets-supported":[0,50758760],"pdf-versions-supported":["adobe-1.2","adobe-1.3","adobe-1.4","adobe-1.5","adobe-1.6","adobe-1.7","iso-19005-1_2005","iso-32000-1_2008","pwg-5102.3"],"pdl-override-supported":"attempted","printer-get-attributes-supported":"document-format","printer-op-policy-supported":["authenticated","default"],"printer-settable-attributes-supported":["printer-geo-location","printer-info","printer-location","printer-organization","printer-organizational-unit"],"server-is-sharing-printers":true,"which-jobs-supported":["completed","not-completed","aborted","all","canceled","pending","pending-held","processing","processing-stopped"]}}

**Comment by michaelrsweet** [comment]
The copies issue is probably a filter issue on Linux - if printing the same file from the command line doesn’t work with multiple copies, go ahead and file a bug against the cups-filters project.

**Comment by SoniaBalodi** [comment]
@michaelrsweet I finally managed to send print from command line from cups and there too copies didnt work. command i used : 
lp -d UAStore10 -n 3 -o media=A4.Transverse PlotterA4.png

UA Store 10 printer has HP DesignJet T1100 pcl, 1.0 (color) driver mapped in CUPS.

I will go ahead and raise a bug at https://github.com/OpenPrinting/cups-filters/issues
