### ISSUE TITLE
Printer Driver missing

### ISSUE THREAD

**Issue by sprakash-nbu** [apple/cups#5353]
Dear Team,

We use CUPS 1.4.2 for our organisation and CUPS is completely new platform for me. Please help or if this is the wrong place, guide me to the right direction please.

I am trying to set up CAB printer CAB SQUIX 4/600Mon CUPS. But the driver for this model is missing in the list (Attached is the list I see). Is there anyways you know or help me understand how we can update the Driver list on CUPS. 
I tried using the PPD file but no Success. When I do the test print, its shows completed but printer doesn't respond. the message I see with completed is that the printer model is unknown.

Kindly help.

Best 
Soumya
![cab driver list_li](https://user-images.githubusercontent.com/41116103/42572622-20471cca-851a-11e8-8d73-d0927a843dba.jpg)

**Comment by michaelrsweet** [comment]
@sprakash-nbu We don't actually provide a driver for these label printers, so you'll need to contact the manufacturer. Typically the driver PPDs are installed in /usr/share/cups/model, /usr/share/ppd, /opt/share/ppd, or /usr/local/share/ppd depending on the driver and Linux distribution. Once installed the driver will automatically show up in the model list.
