### ISSUE TITLE
Question : Printing to plotter T7200

### ISSUE THREAD

**Issue by SoniaBalodi** [apple/cups#5355]
Hello,

I am trying to print to plotter T7200 from CUPs using ipp library : https://github.com/williamkapke/ipp. This plotter does not have postscript upgrade kit, hence doesn't support postscript language. 
Supported languages include : HP-GL/2, HP-RTL, CALS G4. Is there any way which can work as a workaround to print to this plotter. Any driver or change in ipp attributes  ?

Thank you in advance.
Regards,
Sonia

**Comment by SoniaBalodi** [comment]
Hey @michaelrsweet , I am not sure If I understand what changes I will have to do to support this model.
Right now it looks like I will have to add this printer to CUPS with an external PPD file.
In this case will i also need rastertopclx driver ? Maybe you could point me to some documentation where I can first read about these. ?
Thank you very much.
Regards,
Sonia

**Comment by frazhome** [comment]
Hello Sonia,

when you are on linux install the cups-filter package. I think this is always installed on Linux, when your are doing something with printing.

Configure the HP DesignJet T1100 pcl printer model. This should do the need work.

regards
Franz

**Comment by SoniaBalodi** [comment]
Hey @frazhome 

Thankyou for providing information.
Is it possible for you to give me some pointers on what parameters i should be sending to the printer setup with HP Designjet T1100 pcl model which will use cups-filter package ?
I am assuming some settings has to be made also ? Otherwise T7200 plotter will error out saying - PCL Language not supported.
Regards,
Sonia

**Comment by frazhome** [comment]
Hello Sonia,

does the plotter support pclx? Is Graphics language setting on automatic?

I take a look on our company plotters via snmp and the all show
MFG:Hewlett-Packard;CMD:PJL,DW-PCL,POSTSCRIPT,HP-GL/2,RTL,JPEG,TIFF,PDF,CALSRASTER,ASCII

regards
Franz

**Comment by SoniaBalodi** [comment]
Hey @frazhome ,

Standard language supported are : HP-GL/2, HP-RTL, CALS G4.
Graphic language is set to HP-GL/2. Do you know any way to print after setting graphic language to automatic ? I just tried with a postscript driver and plotter gave error that the format is not supported because it doesnt have Postscript upgrade kit installed, so i am looking for alternatives.
![capture](https://user-images.githubusercontent.com/24384676/43398270-dda62da0-9407-11e8-89e5-673c78992b02.PNG)
![capture1](https://user-images.githubusercontent.com/24384676/43398271-ddbe72c0-9407-11e8-863b-ca50311ad116.PNG)

regards,
Sonia

**Comment by frazhome** [comment]
please set to automatic

**Comment by frazhome** [comment]
hp rtl is a flavour fo pclx

**Comment by SoniaBalodi** [comment]
ok.. to make it clear
1) I should set Graphics language to automatic.
2) Add printer to cups with HP Designjet T1100 pcl driver

Do I also need cups-filter package now ?

**Comment by SoniaBalodi** [comment]
Its Ubuntu 16.04. 
I will check the option you suggested. Basically the print request will have an image to be printed, with 'job-attributes-tag' - 'orientation-requested', 'copies','media'.
document-format is image/png.
I will set up cups with T1100 pcl driver and will send print after changing graphics language to Automatic.

**Comment by SoniaBalodi** [comment]
Hi,

It worked fine. Thank you very much. closing this issue.

Regards,
Sonia
