### ISSUE TITLE
Cups don't display jobname and username 

### ISSUE THREAD

**Issue by andreluizpr** [apple/cups#5356]
Hello,

We have a Cups Server 2.2.8 running in a CentOS Linux release 7.5.1804 (Core). In the same machine we have too samba 4 integrated with Active Directory. When our user send a page from Windows Machine (same network and domain) the job name stay as "Untitled" and user as "anonymous".   We changed JobPrivateValues in <Policy default> to "none" however nothing happens. 

Someone have a tip to help me solve this?

In others versions of Cups (like 1.6 default in CentOS repo) when we change JobPrivateValues to "none" is possible to see username and Job Name in Admin Page.

More information:

/var/log/cups/page_log
PRN4IT anonymous 17974 [18/Jul/2018:14:51:55 -0300] 1 1 - 192.168.2.15 Página de teste - -

Thanks 

Andre

**Comment by michaelrsweet** [comment]
"man cupsd.conf". You want to change the JobPrivateAccess and/or JobPrivateValues settings.

The defaults will hide a lot of values unless you are authenticated as the job owner or an admin.

**Comment by rnagy** [comment]
I can confirm that even with JobPrivateValues set to none cups only logs anonymous. This worked in v2.2.4 and after upgrading to 2.2.8 it fails to log the username.
