### ISSUE TITLE
Cups can't locate installed printer with a local domain name

### ISSUE THREAD

**Issue by JackGrinningCat** [apple/cups#5357]
Hi, 

tltr: Due to a mix of used Technics CUPS failed to resolve a beforehand discovered printers host name and reported and error that it's "Unable to connect to "NPI2EEE6B.local:631": Name or service not known".
While submitting this issue, I recognize that I have to install an additional service (nss-mdns) to resolve such .local hostnames by _standard means_ of connection build up.  I was convinced that CUPS should have used a API equivalent to `avahi-resolve -n NPI2EEE6B.local` to resolve such specialized names. I'll leave this pointer for others or documentation means of a FAQ and considered it closed or open for discussion.

I recently used a small printer environment and as I was trying to check if I can use the printer with CUPS with IPP (driverless). 
Everything worked well until I wanted to print the testfile. The error message "can't localize the [printer name]" popped up in the overview of the printer-page. 

For this issue I'll try it with the command line interface, the output will be easier to copy it here.
Environment: 
  - locale network, DHCP-Server active, HP Laserjet m254, DNS not reachable) 
  - arm Beagle Bone Black, ARCH Linux, CUPS, avahi, smb installed(daemon not activate)

```
[root@test ~]# lpinfo -v
network beh
network https
network http
network socket
network ipp
network lpd
file cups-pdf:/
network ipps
network smb
network socket://192.168.100.150
network dnssd://HP%20Color%20LaserJet%20M254nw%20(2EEE6B)._ipp._tcp.local/?uuid=564e4334-3631-3336-3333-b4b6862eee6b
network ipp://NPI2EEE6B.local:631/ipp/print
```

In the web interface, there was an entry with (driverless) so i expected that the model "everywhere" is fitting.

```
[root@test ~]# lpadmin -p myprinter -E -v ipp://NPI2EEE6B.local/ipp/print -m everywhere
lpadmin: Unable to connect to "NPI2EEE6B.local:631": Name or service not known
[root@test ~]# ping NPI2EEE6B.local
ping: NPI2EEE6B.local: Name or service not known
```

As i know that the entries written by lpinfo -v are produced with the help of mDNS/avahi.
I tried to resolve it with mDNS/avahi. And it worked.

```
[root@test ~]# avahi-resolve -n NPI2EEE6B.local
NPI2EEE6B.local 192.168.100.150

```
I think in cases that the host was found by mDNS and is a ".local", CUPS should resolve this over the mDNS provider if reachable.

After writing all this and checking some options I just recently found an entry that I have to install nss-mdns package and add the entry mdns_minimal to have mDNS resolution of .local host names. 

**Puuh, now I get it. But it is kind of a unlucky thing that actually I could discover the printer but couldn't connect it due to resolution problems of the hosts.**

**Comment by archenemies** [comment]
Thank you for this. I had a problem when I was trying to share a printer in a "standard" way, I also found that CUPS is expecting to find "servername.local" when I just wanted it to resolve "servername". Is it no longer possible to get CUPS to use plain old DNS, is that what you're saying? Maybe you can answer this question and that would also be a way to document your solution:

https://unix.stackexchange.com/questions/465608/how-do-i-share-a-cups-printer-easily-in-linux/465609#465609

I found that most Linux users don't actually print stuff, it's very difficult to get help debugging these issues.

https://github.com/OpenPrinting/cups-filters/issues/61#issuecomment-421502868

**Comment by JackGrinningCat** [comment]
> I also found that CUPS is expecting to find "servername.local" when I just wanted it to resolve "servername". 
The string "servername.local" is provide from cups method to find "reachable" printers. It has three means for it. 

- Finding a usb-printer over the usb device identifier (little magic for me)
- Request avahi to find printer by 
   - sending a broadcast to every node in the local net (mDNS)
   - sending a request to the DNS Server that has special entries for printer (DNS-SD)
- Make a SNMP broadcast and request for every answering node if it has printing capabilities

Every of those found printers build some URLs which are used as is in CUPS. It then has a list of urls and you choose one with ".local". 

> Is it no longer possible to get CUPS to use plain old DNS, is that what you're saying? 
No. Cups does not care about how the url is resolved. He delegates to open a connection to the host to glibc (Correct me if I'm wrong). 
The nss-mdns package I mentions provides a extension for glibc. It basically provides the means to talk to avahi to let it resolve the host name. 

When you say to resolve "servername" I guess you mean the hostname without a domain. 
Afaik those are not plain old DNS but netbios/winbind related names. On the user site it looks like a stripped domains without "local" or just the host name. 

If you install libnss-winbind it provides the same means as nss-mdns.

> I found that most Linux users don't actually print stuff, it's very difficult to get help debugging these issues.
Jeah, in that sense I wrote this note, but "nooooo" I no longer think this way. It's only when you got problems that you can solve some of it. I think most UI-based distributions do include all those packages needed and already care about it. It was a bit of a curve but I'm on the wave.

**Comment by archenemies** [comment]
A *single-label domain name* is not a Windows thing, it is very standard and very much used by Linux. I have a consumer-grade Linksys router and it records the hostnames of my various computers from their DHCP requests, and serves DNS entries for the same (single-label) names. I am surprised that CUPS does not support these. I've actually never encountered the ".local" form and I don't know where it comes from or how to use it.

**Comment by archenemies** [comment]
A single-label domain name is not a Windows thing, it is very standard and very much used by Linux. I have a consumer-grade Linksys router and it records the hostnames of my various home computers from their DHCP requests, and serves DNS entries for the same (single-label) names to the local network. I am surprised that CUPS does not support these. I've actually never encountered the ".local" form and I don't know where it comes from.

**Comment by michaelrsweet** [comment]
@archenemies A single label host name will get resolved using the default search domain for a computer, often your ISP's domain (e.g. "comcast.net" or whatever) - they will NEVER resolve as "name.local" since ".local" is never the default search domain.

CUPS absolutely supports single label host names, but when it comes to printers discovered via DNS-SD and mDNS we will get a .local name. If the local system is not properly configured to support mDNS lookups then we will never find the address(es) corresponding to the .local name.

Yes, both Avahi and mDNSResponder provide functions for resolving the addresses of a .local name, but the point of these software packages is that they are hooked into the system's resolver library so that ALL applications can support .local names without changes - those functions are there for the resolver library/plugins and not regular applications... So please just make sure the the nss-mdns package is installed...

**Comment by michaelrsweet** [comment]
@archenemies CUPS uses the standard networking APIs (getaddrinfo, in particular) for resolving DNS names to get IP addresses, just like every other network service on Linux. Rolling our own DNS resolver really isn't an option - we'd cause more problems on systems with working resolvers...

**Comment by phuhl** [comment]
For anybody needing an easy to follow guide to fix the issue, I found this: 

https://people.math.rochester.edu/faculty/akrish11//2016/01/09/cups-unable-to-automatically-locate-printer-2.html
