### ISSUE TITLE
IPP Everywhere: ppd encoding

### ISSUE THREAD

**Issue by reddevillg** [apple/cups#5362]
LanguageEncoding in generated ppd file is always ISOLatin1, but it may contains utf-8 encoded characters.

**Comment by michaelrsweet** [comment]
Will investigate.

**Comment by michaelrsweet** [comment]
Confirmed.

[branch-2.2 9e7efee57] Fix localization of IPP Everywhere PPD (Issue #5362)

[master c96cc7c0e] Fix localization of IPP Everywhere PPD (Issue #5362)
