### ISSUE TITLE
cups.org help page needs updates or corrections of stale links

### ISSUE THREAD

**Issue by JackGrinningCat** [apple/cups#5363]
Hi, 

I'm new to cups and due to the long history it sometimes hard to find the current state of features or which was dropped. As example LDAP, on some pages they mention LDAP ([cupsd.conf](https://linux.die.net/man/5/cupsd.conf)) but certainly in the moment it is not part of the code base (or badly named) as I cannot find any code to browse LDAP-directories for printer, nor I'm aware of forks of the code base. 

But back to something what we can change:

- [ ] Update stale link on [documentation](https://www.cups.org/documentation.html) to the Administrative APIs is going to https://www.cups.org/doc/api-array.html 
- [ ] note the tool or version to read the EPUB within the line **CUPS Programming Manual (New EPUB)**.
I tried three tools (chrome extension, FBreader (version from 2010) and also the internet explorer but none of them worked.

Kind Regards

**Comment by michaelrsweet** [comment]
LDAP was supported using a private schema a long time ago, but was dropped. There is an issue tracking standard LDAP printer schema support for a future version of CUPS.

Will look at fixing the documentation links on the web site.

The EPUB file can be read using any conforming EPUB viewer. The EPUB file passes the public EPUB validator. I personally test using iBooks on my Mac and Bookworm and Okular on Linux. An 8-year-old version of FBreader probably isn't going to work, as the EPUB we publish conforms to a standard newer than 2010. I've never tried using a Chrome extension for EPUB files, and Internet Explorer is obsolete.

**Comment by JackGrinningCat** [comment]
Hey, 

couldn't believe that it is possible that anything is wrong with the epub.
I tried to upload the downloaded file on the on this page (http://validator.idpf.org/application/validate)

File | Line | Position | Message
-- | -- | -- | --
FATAL | ./tmp/uploads/1534427859037_0000008125/inputFile/cupspm.epub/cupspm.epub | - | - | Corrupted EPUB ZIP header.
FATAL | ./tmp/uploads/1534427859037_0000008125/inputFile/cupspm.epub/cupspm.epub | - | - | Unable to read file 'error in opening zip file'.

I know that it doesn't mean anything. I'll check this at my home place again. 
Here my file got the sha256 sum
```
Downloads>CertUtil -hashfile cupspm.epub SHA256
SHA256-Hash von cupspm.epub:
8a35fe25b78454071b24eaf5920925cb7be61b330883410645b0c627491d7c6a
```

**Comment by michaelrsweet** [comment]
I did some more checking myself and it looks like the Github-published file was corrupted somehow (and only 7k?!?). I've pushed an update and it looks like the problem is resolved now...
