### ISSUE TITLE
Is there an issue with the Zebra ZPL driver in CUP 2.2.5

### ISSUE THREAD

**Issue by ordercup** [apple/cups#5364]
I've configured my Zebra GK420D printer with the Zebra CUPS ZPL driver on CUPS 2.2 5 (OS X version 10.13.6), but whenever I print a ZPL label to it it prints the ZPL text and not the image!!

I've tried ZPL labels from two different carriers (USPS and FedEx) and they both print the ZPL text, so I'm fairly confident that is is not the the ZPL label being generated but something in the configuration and /or the driver.

Anyone else having issues printing ZPL labels on CUPS 2.2.5 or higher with the ZPL driver and how do I debug what the issues is .

Thanks,
Aloke

**Comment by frazhome** [comment]
Did you send a pdf to the printer or ZPL Language.
Try to print a testpage and see what is happening. When one letters are printed take a look on the setup of the printeremulation ZPL/ EPL1 legacy.

regards
Franz

**Comment by ordercup** [comment]
Fanz,

Thanks. To answer your questions:

1. It is set up as a ZPL printer - I chose the Zebra CUPS  ZPL driver when
I set up the printer via System Preferences and also confirmed this via the
CUPS Admin.

2.I am sending it ZPL commands, not a PDF or an image. Instead of
interpreting the ZPL commands the printer prints the actual ZPL text
commands  FYI, the same ZPL label on the same printer configured in Windows
works absolutely fine!!

.


Aloke Nath | OrderCup
www.ordercup.com
D: 949-482-6186
O: 877-240-3545

**Comment by frazhome** [comment]
Hello Aloke,

the printiing is "as designed". You want to print letters and the printer is doing so ...

Ok, I stopp kidding.

A ruleset for raw printing is missing.

at https://github.com/apple/cups/issues/5294 I try to get something like this, but Michael told mit this is unusal.

you have the following possibilities. 

1) You say raw-printing on the command line lp -o document-format=application/octet-stream -d <printername> printfile.zpl
2) you extend the mime type rules as desribted in issue#5294.
3) you install the device as raw printer 

regards
Franz

**Comment by ordercup** [comment]
Michael,

I have to come to the source, since I've tried every thing possible to get the default Zebra ZPL driver in CUPS 2.2.5 on my Mac OS X High Sierra 10.13.6  to work on my GK420D, including resetting my Zebra printer to factory defaults. I can't believe I am the only one having the problem. Can you confirm:

1. Is there a known problem with the Zebra ZPL Driver in CUPS 2.2.5, and if so is there a fix. I have googled and looked on the the CUPS site but cannot find anything suggesting there is.

2 If there is a known issue with Zebra ZPL Driver in CUPS 2.2.5, can I downgrade my CUPS version to solve the issue. If so. **which version** and  can you provide the directions on how I do this.

3. If neither of the above is true, can you assist with instructions on debugging what the issue may be. The exact same ZPL label prints fine on the GK420D configured on Windows with Zebra's provided printer driver!

Thanks,
Aloke

**Comment by michaelrsweet** [comment]
ZPL is really (really) hard to auto-detect properly, and we also don't have an explicit ZPL == raw rule.

You need to use "-o raw" or "-o document-format=application/vnd.cups-raw" to tell CUPS the file is printer-ready data, otherwise it will probably treat it as plain text and try to convert it for you to ZPL...

**Comment by michaelrsweet** [comment]
@ordercup Use the `-oraw` option when printing ZPL files. There is currently no ZPL file matching rule due to the number of false positives we’d get for plain text files...

**Comment by michaelrsweet** [comment]
@frazhome we have tried in the past to auto-detect ZPL but the sequence ^XA happens enough in plain text files (really!) that we can’t just use that to auto-detect without causing plain text printing to fail.
