### ISSUE TITLE
CUPS 100% CPU usage

### ISSUE THREAD

**Issue by KimBrodowski** [apple/cups#5366]
This bug might be related to #5360. I've originally reported the issue at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=841028 . Since we haven't yet received any feedback there we're trying here instead.

Our cups process sits idling at around 100% CPU usage. While some devices may connect to that server for the purpose of printer discovery etc. it's not actually used for printing. We have setup a couple of dummy printers though - none of them being actively used on this specific server. The log doesn't show any obvious signs of errors. I'll post a full log once the problem occurs again with debug logging enabled. We believe that the cause is related to network activity as we were able to reproduce the issue at least once when restarting the CUPS daemon on the workstation mentioned below. The cups daemon will use 100% CPU usage after unspecific amount of time running on the server as long as it isn't restarted.

strace (scrolling through rapidly):
```
poll([{fd=19, events=POLLIN}], 1, 0)    = 1 ([{fd=19, revents=POLLIN}])
recv(21, "\247", 1, MSG_PEEK)           = 1
poll([{fd=21, events=POLLIN}], 1, 0)    = 1 ([{fd=21, revents=POLLIN}])
epoll_wait(5, [{EPOLLIN, {u32=1468342600, u64=83072721224}}, {EPOLLIN, {u32=1468196936, u64=91662510152}}], 4096, 1000) = 2
recv(19, "\303", 1, MSG_PEEK)           = 1
poll([{fd=19, events=POLLIN}], 1, 0)    = 1 ([{fd=19, revents=POLLIN}])
recv(21, "\247", 1, MSG_PEEK)           = 1
poll([{fd=21, events=POLLIN}], 1, 0)    = 1 ([{fd=21, revents=POLLIN}])
epoll_wait(5, [{EPOLLIN, {u32=1468342600, u64=83072721224}}, {EPOLLIN, {u32=1468196936, u64=91662510152}}], 4096, 1000) = 2
```

The file descriptors correspond to the following sockets:
```
cupsd     32123                   root   19u     IPv4           33857634       0t0        TCP iserv.dev2.iserv.eu:ipp->Dogmeat.dev2.iserv.eu:43696 (CLOSE_WAIT)
cupsd     32123                   root   21u     IPv4           33865820       0t0        TCP iserv.dev2.iserv.eu:ipp->Dogmeat.dev2.iserv.eu:43706 (CLOSE_WAIT)
```
iserv.dev2.iserv.eu being the server CUPS is installed on and Dogmeat.dev2.iserv.eu being a workstation on our network.

When inspecting network traffic we don't see any traffic related to this connection.

We're currently running:
cups				2.2.1-8+deb9u1
cups-bsd			2.2.1-8+deb9u1
cups-client			2.2.1-8+deb9u1
cups-common			2.2.1-8+deb9u1
cups-core-drivers		2.2.1-8+deb9u1
cups-daemon			2.2.1-8+deb9u1
cups-filters			1.20.3-1+b1
cups-filters-core-drivers	1.20.3-1+b1
cups-ipp-utils			2.2.1-8+deb9u1
cups-pdf			2.6.1-22
cups-ppdc			2.2.1-8+deb9u1
cups-server-common		2.2.1-8+deb9u1
cupsddk				1.5.3-5+deb7u6

The versions refer to Debian package versions as we're on Debian Stretch (Yes Stretch, not Buster. Since the original answer suggested a newer version might fix our issue). Stretch's default versions are affected by the same issue.

I'll provide more information as needed. I'm no expert when it comes to network printing, so bear with me.

**Comment by KimBrodowski** [comment]
Sadly the error log doesn't provide much more insight:

`[...]
D [03/Aug/2018:15:05:54 +0200] [Client 81] Read: status=100
D [03/Aug/2018:15:05:54 +0200] [Client 59] Read: status=100
D [03/Aug/2018:15:05:54 +0200] [Client 62] Read: status=100
D [03/Aug/2018:15:05:54 +0200] [Client 81] Read: status=100
D [03/Aug/2018:15:05:54 +0200] [Client 59] Read: status=100
D [03/Aug/2018:15:05:54 +0200] [Client 62] Read: status=100
D [03/Aug/2018:15:05:54 +0200] [Client 81] Read: status=100
I [03/Aug/2018:15:05:54 +0200] Scheduler shutting down normally.
D [03/Aug/2018:15:05:54 +0200] Discarding unused server-stopped event...
D [03/Aug/2018:15:05:54 +0200] [Client 59] Closing connection.
D [03/Aug/2018:15:05:54 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
D [03/Aug/2018:15:05:54 +0200] [Client 62] Closing connection.
D [03/Aug/2018:15:05:54 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
D [03/Aug/2018:15:05:54 +0200] [Client 81] Closing connection.
D [03/Aug/2018:15:05:54 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
D [03/Aug/2018:15:05:54 +0200] Creating keep-alive file "/var/cache/cups/org.cups.cupsd".
I [03/Aug/2018:15:05:54 +0200] Saving job.cache...
D [03/Aug/2018:15:05:54 +0200] cupsdStopSelect()
`

**Comment by michaelrsweet** [comment]
Please attach your cupsd.conf file.

**Comment by KimBrodowski** [comment]
https://gist.github.com/KimBrodowski/b0db8ddd5060f216d35acc1a9d79c7ce

Thank you for looking into this.

**Comment by michaelrsweet** [comment]
OK, try adding "Allow @LOCAL" to the `<Location />` section.

**Comment by KimBrodowski** [comment]
I've deployed the recommended change above and will monitor the service.

**Comment by KimBrodowski** [comment]
Good morning,
unfortunately this didn't resolve the issue for us:

New strace. same symptoms otherwise.
```
open("/etc/group", O_RDONLY|O_CLOEXEC)  = 19
lseek(19, 0, SEEK_CUR)                  = 0
fstat(19, {st_mode=S_IFREG|0644, st_size=1848, ...}) = 0
mmap(NULL, 1848, PROT_READ, MAP_SHARED, 19, 0) = 0x7f6b42f75000
lseek(19, 1848, SEEK_SET)               = 1848
munmap(0x7f6b42f75000, 1848)            = 0
close(19)                               = 0
gettimeofday({tv_sec=1536828573, tv_usec=553930}, NULL) = 0
write(6, "D [13/Sep/2018:10:49:33 +0200] ["..., 61) = 61
poll([{fd=15, events=POLLIN}], 1, 0)    = 1 ([{fd=15, revents=POLLIN}])
recvfrom(18, "+", 1, MSG_PEEK, NULL, NULL) = 1
open("/etc/group", O_RDONLY|O_CLOEXEC)  = 19
lseek(19, 0, SEEK_CUR)                  = 0
fstat(19, {st_mode=S_IFREG|0644, st_size=1848, ...}) = 0
mmap(NULL, 1848, PROT_READ, MAP_SHARED, 19, 0) = 0x7f6b42f75000
lseek(19, 1848, SEEK_SET)               = 1848
munmap(0x7f6b42f75000, 1848^Cstrace: Process 4268 detached

```

**Comment by michaelrsweet** [comment]
Sorry, I'm still not able to reproduce using the stock CUPS sources. I suspect this is being caused by one of their patches to CUPS... :/

**Comment by KimBrodowski** [comment]
CUPS 2.2.9 built from source is also affected. This is NOT a Debian specific bug.

**Comment by zdohnal** [comment]
It is possible an other program sends a lots of requests in small time frame, which causes high CPU load in CUPS, f.e. cups-browsed (part of cups-filters project, not cups project) can cause it in certain circumstances - I'm currently working on https://bugzilla.redhat.com/show_bug.cgi?id=1648697 , which causes high load in CUPS, when cups-browsed doesn't manage to update print queue in time.

You can check cups-browsed logs for what's going on there then...

**Comment by KimBrodowski** [comment]
Thank you for your suggestion. However we don't ship cups-browsed, so I'm afraid it can't be the origin. As we don't actually make use of cups much on the server I'm using I doubt it's an external source, but I'll see what I can find. 

What surprises me is that cups appears to access /etc/group in one of the previous straces directly, since our user backend is handled by LDAP. I don't think this is related however.

**Comment by KimBrodowski** [comment]
Actually maybe it is. This looks very similar to https://github.com/apple/cups/issues/4901

I bet it's actually the same issue.

**Comment by Francewhoa** [comment]
This is to confirm this challenge. We’re facing the same challenge on one device.

## Steps to reproduce

1. Before trying to reproduce this challenge, I suggest to reproduce it only on a disposable non-production device. Such as a QEMU virtual machine. Because there is a very high risk that the Debian will slow down. In turn, the boot volume will fill very quickly. In turn, the Debian will crash. In turn, you will not be able to log-in Debian GNOME. In turn, Debian GNOME is not usable. In turn, only Terminal in rescue mode will be available.

1. Using:
 
   1. Debian 10 Buster
   1. CUPS 2.2.10
   1. GNOME 3.30.2 with Wayland

1. Using Terminal/Console, as a user with the Sudo permission, execute this command to change the chmod permissions on this "cups" with recursive

   `sudo chmod -R "g+w" "/var/log/cups"`

   * Note: 

      * Changing this permission is the primary cause of this challenge
      * What this command does is it add the "Group" permission to the "cups" folder and all its sub-folders and files
      * According to CUPS, adding this "Group" permission is insecure
     

1. Reboot your device

1. Using GNOME, open `Printers`. This error message is display `Sorry! The system printing service doesn’t seem to be available`. If you do not yet see this error message, try again later. Depending on the available storage on the volume it might need more time. This is the 1st challenge.

1. Using GNOME "Monitor", search for `cupsd -l`. Notice that it permanently used 100% of one CPU. This is the 2nd challenge.

1. Using Terminal/Console, as a user with the Sudo permission, execute this command to see the last 100 lines of the cups "error_log" log file

   `tail -n 100 "/var/log/cups/error_log"`

  * Note:

       * This file is likely very large. Up to GB or TB. So I suggest to use this command. Which is able to open very large text file. In comparison Gedit or Nano are not able to do this.


1. Notice that the "error_log" file contains millions or trillions of those lines below. This is the 3rd challenge.:

```
W [15/Jul/2015:11:23:03 -0700] Notifier for subscription 911 (dbus://) went away, retrying!
E [15/Jul/2015:11:23:03 -0700] File "/usr/lib/cups/notifier/dbus" has insecure permissions (0100777/uid=0/gid=0).
```


1. Notice that this error recorded for a very large amount of time. Using GB or TB of space. The volume fills up very quickly. Depending on the space of your device and hardware, the volume is full within minutes or hours. This is the 4th challenge. 

1. Using Terminal/Console, as a user with the Sudo permission, execute this command to find the available space on the boot volume

   `df -h`

1. Periodically execute again this `df -h` command. Notice that the boot volume fill up very quickly.


1. The expected result is that CUPS would not infinitely fill the volume, then crash Debian. While at the same time CUPS would still report the "insecure permissions" warning to its log.



## Suggested Resolution

How about this, before writing this "insecure permissions" warning to the log, how about CUPS would detect if the error was already recently reported, then write it less frequently. For example, maximum once every 5 minutes. Instead of multiple time per seconds. Optionally, a new configuration could be added to CUPS. So that user could customize this frequency to their liking.

**Comment by Francewhoa** [comment]
This workaround below permanently resolved the challenge for us

1. Using Terminal, as a user with the Sudo permission, execute this command to activate Sudo for all the following commands

   `sudo su`


1. Using Terminal, as a user with the Sudo permission, execute this command to set the cups folder OWNER to root for both its folder and files.

   `chown -R root:root /usr/lib/cups/* && \`


1. Using Terminal, as a user with the Sudo permission, execute this command to set the cups folder PERMISSION to 755 for both its folder and files.

   `chmod -R 755 /usr/lib/cups/* && \`


1. Using Terminal, as a user with the Sudo permission, execute this command to restart CUPS

   `/etc/init.d/cups restart`

1. Using Terminal, as a user with the Sudo permission, execute this command to TBD

   `ÀD`


1. Using Terminal, as a user with the Sudo permission, execute this command to permanently erase the present CUPS log file

   `sudo rm -rf /var/log/cups/error_log`

   * Note: In the future, after a reboot, this file will automatically be recreated by CUPS. But a smaller file.

1. Using Terminal, as a user with the Sudo permission, execute this command to TBD

   `ÀD`

1. Using Terminal, as a user with the Sudo permission, execute this command to TBD

   `ÀD`

**Comment by Francewhoa** [comment]
This workaround below permanently resolved the challenge for us

1. Using:
 
   1. Debian 10 Buster
   1. CUPS 2.2.10
   1. GNOME 3.30.2 with Wayland

1. Using Terminal, as a user with the Sudo permission, execute this command to activate Sudo for all the following commands

   `sudo su`


1. Using Terminal, as a user with the Sudo permission, execute this command to set the cups folder OWNER to root for both its folder and files.

   `chown -R root:root /usr/lib/cups/* && \`




1. Using Terminal, as a user with the Sudo permission, execute this command to set the cups folder PERMISSION to 755 for both its folder and files.

   `chmod -R 755 /usr/lib/cups/* && \`


1. Using Terminal, as a user with the Sudo permission, execute this command to restart CUPS

   `/etc/init.d/cups restart`




1. Using Terminal, as a user with the Sudo permission, execute this command to permanently erase the present CUPS "error_log" file

   `sudo rm -rf /var/log/cups/error_log`

 * Notes:

     * This "error_log" was very large and using the boot volume available space. In turn, we were not able to login Debian GNOME. Thus the need to delete this file.
     * In the future, after a reboot, this file will automatically be recreated by CUPS. But a smaller file.



1. Using Terminal, as a user with the Sudo permission, execute this command to stop CUPS

   `sudo service cups end`



1. Using Terminal, execute this command to find the present available space of the boot volume. If successful, the available space has increased.

   `df -h`


1. Using Terminal, as a user with the Sudo permission, execute this command to restart your device

   `sudo service cups end`


1. Done. You have successfully resolve this challenge :)

Attribution and thanks to voy for this commands to set the chmod
