### ISSUE TITLE
CUPS not printing if media option

### ISSUE THREAD

**Issue by leobel96** [apple/cups#5367]
Hi. I've installed CUPS on my Raspberry Pi 3 B+ running the last version of Raspbian. I've got a Canon Pixma MG2950 connected via LAN to the Raspberry and I'm trying to print some images on 10x15cm photo paper. If I run `lp -d Canon_MG2900_series image.jpg` everything works as expected. If I try to add the media option and I run `lp -d Canon_MG2900_series -o media=Custom.10x15cm image.jpg`, from cups server everything seems to be ok and "job state" changes to "completed" in CUPS server but nothing is printed and my printer acts like nothing is received. I've also tested it with CUPS-PDF printer running `lp -d PDF_printer -o media=Custom.10x15cm image.jpg` and it works fine. I've also tried changing drivers from "Canon MG2900" to "Canon Pixma MG2950" but nothing changed.

**Comment by michaelrsweet** [comment]
You can't use "Custom.10x15cm" with media, just with PageSize. Media values need to match the PWG media standardized names standard, which would mean either om_small-photo_100x150mm or na_index_4x6in.

**Comment by leobel96** [comment]
PageSize is not well documented and, before now, I didn't know it existes. Anyway `lp -d Canon_MG2900_series -o PageSize=Custom.10x15cm image.jpg` nothing is printed like with media option... I also tried converting cm to points as shown in [your issue](https://github.com/apple/cups/issues/1771) but nothing changed...

**Comment by michaelrsweet** [comment]
Run `lpoptions -p printer -l` to see a list of supported PPD options and values.

**Comment by leobel96** [comment]
This isn't much different from manually changing paper dimension from printer menu...

**Comment by leobel96** [comment]
I run it. I tried to change the value of PageSize with one of the possible values using `lpoptions -p printer PageSize=supported_value` but nothing changes. Using CUPS printer menu seems to be the only working way.
