### ISSUE TITLE
landscape not printing correctly

### ISSUE THREAD

**Issue by giancarlo64** [apple/cups#5368]
Hi to all,
I have cups on a raspberry PI with raspbian Stretch. I use a script to print all the files decoded and saved in a directory. The files are plain text, ps or pdf. With the first two type of files I have no problem. With PDF I get problems if the PDF include portrait and landscape pages. I noticed that if the the page is landscape and not portrait, only a part of the landscape page will be printed. I have a PDF with 3 pages and the second page is landscape. This page will be printed only a part. The 1st and the 3rd are printed ok.
I noticed also that for this kind of PDF cups tell me that the state "canceled" instead of completed
The command (bash) to print is 

LP_OPTIONS="-o media=A4,tray1 -o fit-to-page -o position=top -o scaling=100"
LP_OUTPUT=$(lp $LP_OPTIONS "$f") 

where $f is a file in the print folder

Gian Carlo

**Comment by debiantriage** [comment]
On Mon 06 Aug 2018 at 09:37:19 -0700, giancarlo64 wrote:

> Hi to all,
> I have cups on a raspberry PI with raspbian Stretch. I use a script to print all the files decoded and saved in a directory. The files are plain text, ps or pdf. With the first two type of files I have no problem. With PDF I get problems if the PDF include portrait and landscape pages. I noticed that if the the page is landscape and not portrait, only a part of the landscape page will be printed. I have a PDF with 3 pages and the second page is landscape. This page will be printed only a part. The 1st and the 3rd are printed ok.
> I noticed also that for this kind of PDF cups tell me that the state "canceled" instead of completed
> The command (bash) to print is 
> 
> LP_OPTIONS="-o media=A4,tray1 -o fit-to-page -o position=top -o scaling=100"
> LP_OUTPUT=$(lp $LP_OPTIONS "$f") 
> 
> where $f is a file in the print folder

Read

https://wiki.debian.org/pdftopdfandPageRotation

and use pdfAutoRotate.

-- 
Brian.

**Comment by michaelrsweet** [comment]
This isn't a CUPS issue, but a [cups-filters](https://github.com/OpenPrinting/cups-filters) issue...
