### ISSUE TITLE
Print custom sizes on HP Designjet T1300 from CUPS

### ISSUE THREAD

**Issue by andreimoise** [apple/cups#5371]
Hello,
We currently have an issue with HP Designjet T1300, when trying to print custom sizes. The printer is added in CUPS with the following driver: HP Designjet T1300 PostScript (color).

We have tried the following options:
- set Media Size to Custom: when we introduced sizes in mm, it would simply get ignored. After setting the custom size in mm and returned to "Set default options" page , the default Media Size will be displayed instead. We then tried to set the size in cm and this one gets saved; however, we queried for the driver information through an IPP request and the media default is unknown. (IPP response is attached)

Could you, please, advise on how to send custom sizes to this plotter? We are sending print requests from our application to CUPS and don't know what mediaSize attribute to send for this.

Thank you in advance,
Andrei Moise

[IPP_response.txt](https://github.com/apple/cups/files/2270539/IPP_response.txt)

**Comment by michaelrsweet** [comment]
Please attach the PPD file you are using with CUPS.

Also, what operating system are you using, and what version of CUPS?

**Comment by andreimoise** [comment]
Hello,
1. CUPS version is 2.1.3.
2. OS: 
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:   xenial
Linux 4.4.0-128-generic #154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

3. Regarding the PPD file: we are not using an external PPD file - we are using the driver from cups. The driver name is: HP Designjet T1300 PostScript (color)

Thank you!
Andrei Moise

**Comment by michaelrsweet** [comment]
@andreimoise That is not a CUPS-supplied driver. It probably comes with Ubuntu...  So if you can attach the PPD file from /etc/cups/ppd for the queue then we might have a chance of helping you...

**Comment by andreimoise** [comment]
[PT_1_HP_Designjet_T1300.zip](https://github.com/apple/cups/files/2293169/PT_1_HP_Designjet_T1300.zip)

Hello,
Please find, attached, the requested file.
Thank you!

**Comment by michaelrsweet** [comment]
OK, so this is a standard PostScript PPD and you can use either "PageSize=Custom.WIDTHxHEIGHT" where "WIDTH" and "HEIGHT" are in points (72 points = 1 inch) *or* "media=om_custom_WIDTHxHEIGHTmm" (WIDTH and HEIGHT in millimeters) *or* "media=oe_custom_WIDTHxHEIGHTin" (WIDTH and HEIGHT in inches).

If you submit using the CUPS API then you'd snprintf the size string and add it to an options array, e.g.:

```
int num_options = 0;
cups_option_t *options = NULL;
char temp[255];
double width_mm, height_mm;

snprintf(temp, sizeof(temp), "om_custom_%.1fx%.1fmm", width_mm, height_mm);
num_options = cupsAddOption("media", temp, num_options, &options);
```

Hope this helps!

**Comment by SoniaBalodi** [comment]
Hi @michaelrsweet 

I tried your suggestion to use media=om_custom_WIDTHxHEIGHTmm, it worked. 
Plotter has roll width of 840 mm. I tested with om_custom_840x594mm, plotter was able to cut the roll at 594 height, however the image was printed rotated. It did not cover full roll width as i expected it to be. Can you help with any attribute which can be used to print image of 840X594 as it is and not rotated ?

**Comment by michaelrsweet** [comment]
@SoniaBalodi You can try passing "orientation-requested=3" to specify "portrait" orientation (no rotation), but you might be running into a cups-filters bug... :/
