### ISSUE TITLE
CUPS Leaking IPP(S) authentication details to users?

### ISSUE THREAD

**Issue by Stoatwblr** [apple/cups#5372]
If a printer is added to CUPS using the ipp(s)//user:pass@printer{:port}/[path] URI format, the login and password is visible to users who use the "loptions -p printer" command

If admins are intending to keep users from directly accessing printers by passwording them, I'm pretty sure they'd see this as undesirable behaviour, whether or not they require passwords to access CUPS.

It may happen there are already ways to prevent this kind of credential leakage occurring -  but if they exist, they are poorly documented.

**Comment by michaelrsweet** [comment]
Unable to reproduce on Git master. What version of CUPS are you using, and what OS/Linux distribution?

(cupsd normally filters out auth info from the device-uri, and has done so since CUPS 1.2)

**Comment by Stoatwblr** [comment]
CUPS 2.2.8 compiled locally on RHEL7.5

**Comment by Stoatwblr** [comment]
I've found the reproducer: When extra backends are introduced (such as tea4cups or papercut), the filter fails.

> lpoptions -p printerF-funnel

auth-info-required=username,password copies=1 cpi=12 device-uri=tea4cups:ipps://printerF:wibble@printerf.mydomain.example.com:443/ipp/print?waitjob=true&version=2.0 finishings=3 job-hold-until=no-hold job-priority=50 job-sheets=none,none lpi=7 marker-change-time=1533834519 marker-colors=#000000,#00FFFF,#FF00FF,#FFFF00 marker-high-levels=100,100,100,100 marker-levels=40,36,57,53,-1 marker-low-levels=7,7,7,7 marker-names='Canon\ Cartridge\ 040\ Black\ Toner,Canon\ Cartridge\ 040\ Cyan\ Toner,Canon\ Cartridge\ 040\ Magenta\ Toner,Canon\ Cartridge\ 040\ Yellow\ Toner' marker-types=toner,toner,toner,toner media=A4 number-up=1 page-bottom=86 page-left=57 page-right=57 page-top=72 pageregion=A4 printer-commands=AutoConfigure,Clean,PrintSelfTestPage printer-info='DO NOT USE (tester)' printer-is-accepting-jobs=true printer-is-shared=true printer-location='DO NOT USE (tester)' printer-make-and-model='Canon LBP712C PPD' printer-state=3 printer-state-change-time=1533834519 printer-state-reasons=none printer-type=8425564 printer-uri-supported=ipp://localhost:631/printers/printerF-funnel scaling=100 wrap=true

**Comment by Stoatwblr** [comment]
This reproduces on Ubuntu 18.04 / Cups 2.2.7 too.

In my case I'm using multiple backends:  papercut:tea4cups:ipps://user:pass@printer:443/ipp/print and of course cups allows for more to be chained.

**Comment by michaelrsweet** [comment]
Ok, that is the problem. Cupsd can filter out credentials for standard URI schemes but not for third party backends. Sorry, but there is nothing we can do for this (we don’t support tea4cups).

**Comment by Stoatwblr** [comment]
Fine. I'll file a CERT advisory for it then.
