### ISSUE TITLE
ipps/https printer has 30s interval between TCP connections of a printer job

### ISSUE THREAD

**Issue by pedrosardinha** [apple/cups#5376]
There are a different connections behavior between a ipp/http and ipps/https printer.
When it is using ipp/http, it establish the print job connections in 2s or 3s. But if it is using ipps/https each connection from cups to the ipps/https printer has 30s interval.
A print job can has 3 or 4 TCP connections and it takes more then 1 minute to complete.
Can this 30s interval between connections of a print job be set to a different value? Which is causing 

cups version: 1.4.2-79.el6
IPP URI options: version=1.0&waitprinter=false&waitjob=false
ipp/http printer: Windows Server 2012 R2

**Comment by michaelrsweet** [comment]
That is probably the TLS negotiation time -given the age of the Windows server you are connecting to and the version of CUPS in use, there isn’t much you can do to speed things up unfortunately.
