### ISSUE TITLE
If I want to print 2 pages on 1. But it prints the 2 pages in the size of 4 pages

### ISSUE THREAD

**Issue by apbonn** [apple/cups#5378]
Hi,

im using cups 1.7.5 on a pi3. 
It worked great, but since 2 weeks i got this issue.

I want to print 2 pages on 1 page.
But the result is, that the 2 pages have the size, like when i would like to print 4 pages on 1.
So each page has not 50% size on the page, it has 25%.

If I just print one page on one page it works great.
If I connect the printer to my pc, it also works with 2 on 1 .

I rebooted and of course reinstalled my printer. No change.
The settings in word are correct or in the chrome browser.

So there must be an issue with cups.

Any ideas how to solve it ?

**Comment by michaelrsweet** [comment]
This isn’t CUPS, it is [cups-filters](https://github.com/openprinting/cups-filters) that is doing the formatting.
