### ISSUE TITLE
ppdc JCLui error

### ISSUE THREAD

**Issue by Stoatwblr** [apple/cups#5379]
Yes, I know that PPDS are deprecated. A lot of stuff still uses them - like cupsaddsamba - especially when you're still using 20 year old printers.

ppdc is generating JCLOpenUI statements, but incorrectly closing them with "CloseUI" instead of JCLCloseUI.:

*OpenGroup: JCL/JCL
*JCLOpenUI *JCLTrapping/Trapping: PickOne
*OrderDependency: 6 JCLSetup *JCLTrapping
*DefaultJCLTrapping: Light
*JCLTrapping Off/Off: "KTRAPPING=0"
*JCLTrapping Light/Light: "KTRAPPING=1"
*JCLTrapping Medium/Medium: "KTRAPPING=2"
*JCLTrapping Heavy/Heavy: "KTRAPPING=3"
*JCLTrapping VeryHeavy/Very heavy: "KTRAPPING=4"
*CloseUI: *JCLTrapping
^^^^^^^^^^^^^^^^^^^^^^^^^^^^ This breaks cupsaddsmb in "interestingly misleading" ways (it complains about missing doublequotes)
*CloseGroup: JCL

Adobe ppd spec document  5.2, yadda yadda (symetricallity)

**Comment by Stoatwblr** [comment]
Conversely ppdi is converting things like ```<ESC> and <CR><LF>``` into their 8-bit equivalents in the .drv files. which isn't helpful when trying to debug/rewrite poorly written manufacturer provided PPDs as it adds to the "fun" (Score = 2 CUPS bugs, 1 minor syntax error in manufacturer PPD. Guess which took 40 chargeable hours to find and which was easy once the bugs were accounted for?)

This bug has been there forever, ISTR reporting it back in 1.1 days with no response

**Comment by michaelrsweet** [comment]
The PPD compiler and related stuff didn't exist prior to CUPS 1.2 and didn't get merged into CUPS proper until CUPS 1.4...

The JCLCloseUI bug is pretty simple and is fixed:

[branch-2.2 215b547e0] Fix JCL option support in PPD compiler (Issue #5379)

[master 604783214] Fix JCL option support in PPD compiler (Issue #5379)

Unfortunately, fixing the ppdi import bug for this edge case is a lot more involved and is not something we will be fixing, sorry...
