### ISSUE TITLE
It asks for the make of KONICA MINOLTA printer, how would the user know what the make is?

### ISSUE THREAD

**Issue by yurivict** [apple/cups#5382]
![20180828_094553-x](https://user-images.githubusercontent.com/271906/44737893-0f234f00-aaa8-11e8-90da-0229da4d968d.jpg)

```cups-2.2.8``` installed on FreeBSD.

**Comment by michaelrsweet** [comment]
Presumably you would have installed the Open Printing driver package(s), but essentially you need to "guess" if you don't have drivers installed and are not using IPP (which from the screenshot is the case here...)

However, if you use IPP (or DNS-SD/Bonjour to discover the printer), you can use the IPP Everywhere driver with this printer instead. From the command-line this would look like:

    lpadmin -p printername -E -v ipp://address-or-hostname/ipp/print -m everywhere
