### ISSUE TITLE
KONICA_MINOLTA_C658Series doesn't work

### ISSUE THREAD

**Issue by yurivict** [apple/cups#5383]
"Add printer" finds the printer ```KONICA_MINOLTA_C658Series```.
The actual model is ```C458```.
On Konica website I found the corresponding to C658Series file ```KOC759U.ppd```.
cups accepted it and installed the printer:
```
Description: KONICA MINOLTA C658Series
Location: KONICA-C458
Driver: KONICA MINOLTA C759SeriesPS(P) (color)
Connection: lpd://KMBA5BCB.TheLanName.local/print
Defaults: job-sheets={job_sheets_default} media=na_letter_8.5x11in
sides=one-sided
```

However, "Print test page" fails:
```
Print Test Page KONICA_MINOLTA_C658Series
Error
Unable to print test page:
No such file or directory
```

This printer appears in the printer list in browsers, but everything that is printed there disappears.
Print jobs aren't shown in the list of jobs.

```cups-2.2.8``` installed on FreeBSD 11.2 from the package.

**Comment by michaelrsweet** [comment]
Well, the "no such file or directory" error is probably a missing cups-filters file/package.

The C458 is also AirPrint/IPP and can be used directly with the IPP Everywhere driver and device URI "ipp://hostname/ipp/print".

**Comment by yurivict** [comment]
Is ```cups-filters``` supposed to be always installed along with ```cups```?

**Comment by michaelrsweet** [comment]
Yes, or its equivalent. CUPS doesn't include the necessary PDF and raster generation filters (hasn't for about 10 years now...), which are system-specific. On macOS we have something called "CoreGraphics" that provides this, but for open source we rely on the cups-filters project (which contains the original CUPS 1.0 filters plus a lot of newer stuff that uses Ghostscript, MuPDF, Poppler, and other software as needed/available.

**Comment by yurivict** [comment]
Why isn't ```/usr/local/share/cups/data/testprint``` a part of ```cups```?

**Comment by yurivict** [comment]
After ```cups-filters``` is installed, all jobs are:
> Processing - "Unable to locate printer "KMBA5BCB.TheLanName.local"."

They don't move anywhere.

**Comment by michaelrsweet** [comment]
Because there is no filter to convert the testprint file in the core sources and because the test file is different depending on the OS you use.
