### ISSUE TITLE
Instructions regarding sharing printers is one step short of working

### ISSUE THREAD

**Issue by baitisj** [apple/cups#5385]
Per documentation at [https://www.cups.org/doc/sharing.html](https://www.cups.org/doc/sharing.html) if I:
```
cupsctl --share-printers
lpadmin -p printer -o printer-is-shared=true
```

I still have to add @LOCAL access to my Create-Job Print-Job Print-URI and Validate-Job in `<cupsd.conf>` as follows:
```
  <Limit Create-Job Print-Job Print-URI Validate-Job>
 +  Allow @LOCAL
    Order deny,allow
  </Limit>```
```

**Comment by michaelrsweet** [comment]
This is not correct.

"Order deny,allow" allows requests by default.

Furthermore, --share-printers adds an "Allow @LOCAL" to the root (/) location unless --remote-any is also specified in which case "Allow all" is used.

It would be useful to know what version of CUPS you are using and what operating system/Linux distribution you are using. The stock CUPS cupsd.conf works out-of-the-box with this (I just confirmed to be sure).

**Comment by baitisj** [comment]
In that case, it may be because I'm using FreeBSD with Cups 2.6. For some reason I thought we were using 2.7 over here -- the issue could well have been resolved.

**Comment by michaelrsweet** [comment]
The newest released version of CUPS is 2.2.8. We haven't gotten to 2.6 or 2.7 yet. :)

It could be useful to see your cupsd.conf.default file - that might point us to the cause...

**Comment by baitisj** [comment]
Updated comment with missing .2's.
My distribution includes the attached cupsd.conf.sample file which, upon installation, is the same as the /usr/local/etc/cups/cupsd.conf 

[cupsd.conf.sample.txt](https://github.com/apple/cups/files/2346659/cupsd.conf.sample.txt)

**Comment by michaelrsweet** [comment]
Hmm, well if you enable printer sharing with:

    cupsctl --share-printers

what does the cupsd.conf file look like then?
