### ISSUE TITLE
Missing filters cause print jobs to disappear

### ISSUE THREAD

**Issue by yurivict** [apple/cups#5386]
When ```cups-filters``` isn't installed, all print jobs just disappear. They are accepted from the programs, but aren't shown in cups.

Expected behavior: Jobs should be shown in the cups interface as failed with explanation.

**Comment by michaelrsweet** [comment]
First, you will get an error if there is no filter for the given file format. If there *is* a filter or the driver indicates the printer accepts the format as-is, then it will use it.

Second, we say the following in the installation instructions:

> Using CUPS requires additional third-party support software and printer drivers.
> These are typically included with your operating system distribution.  Apple
> does not endorse or support third-party support software for CUPS.

**Comment by yurivict** [comment]
> First, you will get an error if there is no filter for the given file format. If there is a filter or the driver indicates the printer accepts the format as-is, then it will use it.

This isn't what I observed. The printer doesn't support pdf, browsers print pages in pdf, filter was missing, and jobs were just lost without any error.

**Comment by michaelrsweet** [comment]
Then it is your application that is not showing the error message coming back from cupsd - no job will be created if the format is not supported by the printer.
