### ISSUE TITLE
cupd 2.2.6 client, "lpr" command failing with "Bad Request" against old cups 1.3.9 server

### ISSUE THREAD

**Issue by jjkeijser** [apple/cups#5388]
after upgrading a laptop to Fedora 28, I ran into a strange problem with an old printer server. I have no control over the printer server, running cups 1.3.9. My local client.conf lists
  ServerName  host/version=1.1
and lpq/lpstat work as expected. However, the "lpr" always fails with a "Bad Request". By running wireshark I found the following:
- the initial IPP messages correctly list the protocol as IPP version 1.1, as picked up from the client.conf setting; this causes lpq/lpstat to function
- during an "lpr" run, the initial message lists protocol = IPP 1.1 but subsequent messages all have protocol = IPP 2.0 in the header, causing the printer server to return a "Bad Request" message.

What can I do to work around this issue?

Fedora 28 Linux comes with cups 2.2.6 (as listed in the title of this issue). A CentOS 7 client (cups 1.6.3) and Fedora 22 client (cups 2.0.2) work fine with the same printer server.

**Comment by michaelrsweet** [comment]
This is fixed in the current release of CUPS (2.2.8)
