### ISSUE TITLE
Zebra ZD420 ZPL driver issue

### ISSUE THREAD

**Issue by OggVorbis** [apple/cups#5395]
Using CUPS a random 10% to 30% of all print commands on this printer fail. When this happens the status light on the printer blinks shortly, but nothing is being printed. The print job just vanishes. In all other cases (70% to 90%) the printer just works fine. It doesn't matter what I print, the Ubuntu test page, a short text string, ZPL or a PDF, every time it is 10 to 30% that fails.
I also use an older Zebra GK420d printer, that works flawless using the same driver.

Systems I tested the ZD420 on: Raspbian OS (CUPS 2.2.1), Ubuntu 16.04 (CUPS 2.1.3) and Ubuntu 18.04 (CUPS 2.2.7). I also tried different hardware. On all systems the behaviour was exactly the same. I even tried another ZD420 printer, same results.

**Comment by michaelrsweet** [comment]
How is the printer connected?

**Comment by OggVorbis** [comment]
Sorry, it's USB connected. The full type is ZD42042-D0E000E, which is USB only.

**Comment by michaelrsweet** [comment]
Hmm, I'll need to try this with my GK420 (which I normally have setup over Ethernet) - but it might be something wonky with the USB side of things on Linux...

**Comment by michaelrsweet** [comment]
Sorry, I tried this with my GK420 and was unable to reproduce. You might try running "lsusb" and adding a USB quirks rule to a new file in /usr/share/cups/usb to force a few options:

    0xVVVV 0xPPPP unidir no-reattach

where VVVV is the first hex number reported by lsusb and PPPP is the second.

**Comment by OggVorbis** [comment]
Thanks. I tried this, but the problem remains. It is even worse, when the problem occurs the 'printing' led just blinks forever and nothing is printed. This keeps the printer occupied, no new jobs can be printed as well. Before it only blinked very briefly, and afterwards new print job could be started.

Anyway, I now have a brand new printer I can't use. Zebra doesn't help, according to them this is a driver problem and they don't give support on that. If you wish I could send the printer to you for debugging purposes. I can't use it anyway, and as I own a webshop it isn't too expensive to ship it to you.

**Comment by OggVorbis** [comment]
Well I found something interesting now. If the printing led is blinking I just have to push the 'paper feed' button on the printer and it starts to print the job! It's a bit tedious I have to push this button every few jobs, but at least I can use the printer now.

**Comment by michaelrsweet** [comment]
Ah, that is a good hint - the media configuration is wrong.

With these printers you need to tell them whether your media is continuous (i.e. receipt roll), labels separated by webs (holes), or labels separated by visible marks.

I'm not sure how to configure a USB-only printer, but the web interface on my printer allows me to select the default. Alternately you can make sure your ZPL files contain the `^MNY` command for web tracking and `^MNM` for mark tracking. If you are doing a continuous label/receipt, you'll need `^MNN` and the label length (`LLnnnn`) command, where the length is in dots.

**Comment by OggVorbis** [comment]
Thanks! If anyone needs this info: in the CUPS settings I had to change Printer Options > Print Mode from "Printer Default" to "Tear-Off". It had nothing to do with "Media Tracking" as that was set correctly to "Non-continuous (Web sensing)" already.

**Comment by jonathanernst** [comment]
@michaelrsweet Thanks so much for the 0xVVVV 0xPPPP unidir no-reattach trick it fixed our intermittent problems with Zebra ZD420 !

Wouldn't it be needed to add this quirck to org.cups.usb-quirks ?

# Zebra ZD420 (https://github.com/apple/cups/issues/5395)
0x0a5f 0x0120 unidir no-reattach

**Comment by michaelrsweet** [comment]
[master 3043e3a53] Add USB quirk rule for Zebra ZD420 (Issue #5395)

[branch-2.2 ca1f57fc5] Add USB quirk rule for Zebra ZD420 (Issue #5395)

**Comment by alexvandijk** [comment]
@michaelrsweet Thank you for the tip! I had a problem with a ZD620 printer in combination with Raspbian OS (CUPS 2.2.1). 30% of the time the first label of the print job didn't print. I tried everything, it was driving me nuts. Until I saw your post!
The Zebra ZD620 is fairly new so maybe the quirck for the ZD620 also needs to be added to org.cups.usb-quirks ?
```
# Zebra ZD620
0x0a5f 0x0141 unidir no-reattach
```

Thanks again for your help.

**Comment by michaelrsweet** [comment]
@alexvandijk Looking at the current quirks file, we already have a blanket unidir override for Zebra printers, so I think I'll just add no-reattach to that and call it a day... :)

**Comment by michaelrsweet** [comment]
[master a7c0c36cf] Updated the USB quirks rule for Zebra label printers (Issue #5395)

[branch-2.2 b1648391c] Updated the USB quirks rule for Zebra label printers (Issue #5395)

**Comment by carstenbaumhoegger** [comment]
Thanks to all for your help!

We've been suffering the same behavior since we were using the ZD420 (about 2 months now). We've tried to delay our print jobs etc. but nothing seemed to help.
I've just followed the instructions inside this issue and was able to eliminate the all the problems we've had with printing multiple files in short time. 🎉

**Comment by Webunity** [comment]
Since i will be receiving my networked ZD420d tomorrow; is this setting somehow also needed if you print using a ethernet connected ZD420d?

**Comment by michaelrsweet** [comment]
@Webunity You won't have the same issues over ethernet, and IIRC we also disabled SNMP supplies a while back (but if have an older version of CUPS do "lpadmin -p printer -o cupsSNMPSupplies=false" to disable SNMP supply level processing since the Zebra printers do not support SNMP).
