### ISSUE TITLE
CUPS 2.2.4 versus CUPS 2.2.7

### ISSUE THREAD

**Issue by rickrich** [apple/cups#5397]
If I use CUPS 2.2.4 everything is normal.

If I use CUPS 2.2.7, I get "Process is dying with \"Encountered error Broken pipe during fwrite\", exit stat 1" and no printout.

CUPS 2.2.4 Fedora 27 [el861.txt](https://github.com/apple/cups/files/2366564/el861.txt)
CUPS 2.2.7 Linux Mint 19 [error_log.txt](https://github.com/apple/cups/files/2366569/error_log.txt)

I think its in this area, but who can tell:

D [10/Sep/2018:01:13:00 -0500] [Job 1] New page: %%Page: 1 1
D [10/Sep/2018:01:13:00 -0500] [Job 1] \"Setup\" section is missing, inserting it.
D [10/Sep/2018:01:13:00 -0500] [Job 1] Inserting option code into \"Setup\" section.
D [10/Sep/2018:01:13:00 -0500] [Job 1] Found: %%BeginPageSetup
D [10/Sep/2018:01:13:00 -0500] [Job 1] Inserting option code into \"PageSetup\" section.
D [10/Sep/2018:01:13:00 -0500] [Job 1] Embedded document, nesting level now: 1
D [10/Sep/2018:01:13:00 -0500] [Job 1] PID 11228 (pstops) exited with no errors.
D [10/Sep/2018:01:13:00 -0500] [Job 1] End of embedded document, nesting level now: 0
D [10/Sep/2018:01:13:00 -0500] [Job 1] PID 11227 (gs) exited with no errors.
D [10/Sep/2018:01:13:00 -0500] [Job 1] Flushing FIFO.
D [10/Sep/2018:01:13:00 -0500] [Job 1] Starting renderer with command: \"foo2zjs-wrapper -z2 -P -L0     -r1200x600 -p1 -T3 -m1 -s7   -n1 \"
D [10/Sep/2018:01:13:00 -0500] [Job 1] Starting process \"kid3\" (generation 1)
D [10/Sep/2018:01:13:00 -0500] [Job 1] Starting process \"kid4\" (generation 2)
D [10/Sep/2018:01:13:00 -0500] [Job 1] Starting process \"renderer\" (generation 2)
D [10/Sep/2018:01:13:00 -0500] [Job 1] JCL: \033%-12345X@PJL
D [10/Sep/2018:01:13:00 -0500] [Job 1] <job data>
D [10/Sep/2018:01:13:00 -0500] [Job 1] GPL Ghostscript 9.22: Unrecoverable error, exit code 1
D [10/Sep/2018:01:13:00 -0500] [Job 1] Not a pbm file!
D [10/Sep/2018:01:13:00 -0500] [Job 1] renderer exited with status 0
D [10/Sep/2018:01:13:00 -0500] [Job 1] Process is dying with \"Encountered error Broken pipe during fwrite\", exit stat 1
D [10/Sep/2018:01:13:00 -0500] [Job 1] Cleaning up...
D [10/Sep/2018:01:13:00 -0500] [Job 1] Killing pdf-to-ps

Note, this works from the command line on CUPS 2.2.4 *and* CUPS 2.2.7:

$ foo2zjs-wrapper -z2 -P -L0 -r1200x600 -p1 -T3 -m1 -s7 -n1 testpage.ps > xxx.prn
$ ncat 192.168.1.15 9100 < xxx.prn
... printed OK...

Any idea???

**Comment by michaelrsweet** [comment]
I believe this is a known Ghostscript/glibc bug. See Issues #5392, #5394, and #5396.

**Comment by rickrich** [comment]
Thanks!

FYI: http://foo2zjs.rkkda.com/forum/read.php?63,4215

**Comment by rickrich** [comment]
Ghostscript 9.22 is on both OSes: CUPS 2.2.4 Fedora 27 *and* CUPS 2.2.7 Linux Mint 19.  

But it works on Fedora 27, and it doesn't work on Linux Mint 19.

For both OSes:
$ gs
GPL Ghostscript 9.22 (2017-10-04)

It is weird! Please open this bug again!

**Comment by rickrich** [comment]
I compiled and tried Ghostscript 8.71 on Linux Mint 19.   I get  no printout! 

It is NOT Ghostscript!!!

**Comment by zdohnal** [comment]
@rickrich I think this is foomatic-rip issue with glibc-2.28 (or with earlier glibc version with backported patch which causes it). See https://github.com/OpenPrinting/cups-filters/issues/58  . What glibc version is on Linux Mint 19?

**Comment by rickrich** [comment]
$ sudo apt list | grep glibc

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

clisp-module-bindings-glibc/bionic 1:2.49.20170913-4build1 amd64
glibc-doc/bionic,bionic,now 2.27-3ubuntu1 all [installed]
glibc-doc-reference/bionic,bionic,now 2.27-1 all [installed]
glibc-source/bionic,bionic,now 2.27-3ubuntu1 all [installed]

**Comment by rickrich** [comment]
Well, there are two problems.  

The current Arch Linux has a glibc2.28/foomatic-rip problem. 
2cc7bad0ae0a412e75270b - [BZ 1190] Make EOF sticky in stdio.
It is solved by: https://github.com/OpenPrinting/cups-filters/issues/58

The Linux Mint 19 does not have this problem. Its glibc is at 2.27. So there is no "Make EOF sticky in stdio" which is part of glibc 2.28. 

The Linux Mint 19 does not have a solution, yet.

**Comment by rickrich** [comment]
FYI: http://foo2zjs.rkkda.com/forum/read.php?63,4215
