### ISSUE TITLE
strange ".O" (dot-O) files appearing in /etc/cups/

### ISSUE THREAD

**Issue by archenemies** [apple/cups#5401]
At first I thought these files were created by my package manager, but then I saw that they only appear in /etc/cups and no other places in /etc. Are they being created by CUPS? Where is it documented?

One time I noticed that /etc/cups/cupsd.conf had been replaced by a version with no comments - nothing like the package default, not anything I had created by hand. Is this a bug in CUPS?

**Comment by michaelrsweet** [comment]
The .O files are backup files after cupsd replaces an existing configuration file. This is an implementation-specific detail and not something we have documented (nor shall we).

(but I will note that the use of .O, .bck, ~, and other suffixes on backup files is extremely common)

**Comment by archenemies** [comment]
Thanks. I take it that cupsd edits printers.conf, classes.conf, subscriptions.conf, ppd/*.ppd -- but never cupsd.conf? So my issue with finding a strangely modified cupsd.conf must be unrelated?

**Comment by michaelrsweet** [comment]
It also writes cupsd.conf, based on what a client sends in a PUT request. cupsctl and the web interface use the cupsAdminGet/SetServerSettings API which parses the cupsd.conf file and writes a new one. This (necessarily) causes the loss of any comments in the original file.

**Comment by archenemies** [comment]
Thank you, that helps clarify some mysteries.

Can I make two suggestions:

1. cupsd.conf(5), at the bottom of DESCRIPTION add:

    This file can be edited manually, but you must restart cupsd
    before changes take effect. This file is also regenerated by the
    server when cupsctl is invoked, removing any comments in the
    process.

2. conf/cupsd.conf.in, after the initial comments

       # Configuration file for the CUPS scheduler.  See "man cupsd.conf" for a
       # complete description of this file.

   I would add a warning:

       # Note that certain invocations of cupsctl cause this file to
       # be parsed and regenerated by the server. Please be aware that
       # comments are lost in the process.

3. Wherever cupsd/cupsctl regenerates cupsd.conf, the regenerated file
should start with the above comment text, as well as a timestamp like
I see in printers.conf:

       # Written by cupsd on 2018-09-25 04:25

I hope this seems reasonable? Let me know if you want a pull request for these changes.
