### ISSUE TITLE
Print job taking 5 minutes before releasing job

### ISSUE THREAD

**Issue by cupsuser** [apple/cups#5405]
I am working on a Linux mint 19 OS client machine with a Zebra GTK420D printer and using CUPS on a different Linux OS machine as my print server with the printer connected to it via USB to handle all requests from a python application that sends raw data to the printer. It always takes 5 minutes (300 seconds) to hold the job and then it prints without issue after the 5 minutes is up. I am able to release it manually through 'lp -i (job#) -H resume' and through the web browser (localhost:631), but the purpose of the application is to print the job automatically and instantly when the details are sent to the printer.

How do I get the job to print instantly instead of having to wait 5 minutes for each print job?

**Comment by michaelrsweet** [comment]
That sounds like the application is submitting the print files directly over IPP but isn't setting the "last-document" attribute to true in the Send-Document operation? 300 seconds is the multiple-operation-time-out value, at which point a print job will be resumed or aborted (if there are no files).

**Comment by cupsuser** [comment]
Is there a way I can set the "last-document" attribute to true either within the application or on the CUPS server? The application is not returning any errors when I send the job to the CUPS server.

`s.send("\002"+str(len(ctrl))+" "+ctrlfile+"\n")
s.send(ctrl + "\000") # send control file || file complete indicator
print "Sent control file"

# --------[ RFC 1179 | 6.3 03 - Receive data file ]---------------------

s.send("\003"+str(len(data))+" "+datafile+"\n")
s.send(data + "\000") # send data file || file complete indicator
print "Sent data file "`

**Comment by michaelrsweet** [comment]
Are you really submitting jobs via LPD? And not checking the status bytes coming back after every command?!?

What version of CUPS is on your Linux distro? It is possible you might be running into a cups-lpd bug - the solution is to actually submit the job using IPP - there is a native python IPP client library, not to mention running the lp command pointed to the server...

**Comment by cupsuser** [comment]
Yes I have a separate function to check the returning bytes, but removed it for the above example. They are always returning 0. The function mentioned below is being called after every time the bytes are being sent to ensure they are received properly without issues. When I look in my syslogs, it shows that my job was received successfully:

Sep 27 08:10:24 nate-Aspire-TC-780 cups-lpd[13296]: Connection from (IPv4 192.168.1.150)
Sep 27 08:10:24 nate-Aspire-TC-780 cups-lpd[13296]: Receive print job for P1
Sep 27 08:10:24 nate-Aspire-TC-780 cups-lpd[13296]: Print file - job ID = 392
Sep 27 08:10:24 nate-Aspire-TC-780 cups-lpd[13296]: Closing connection

The version of CUPS is 2.2.7 according to 'cups-config --version'

Function to check bytes returned:
# get lpd acknowledgement
def check_acknowledgement():
  if s.recv(4096) != "\000":
	print "Negative acknowledgement"
	s.send("\001\n") # [ RFC 1179 | 6.1 01 - Abort job ]
	s.close()
	sys.exit()

**Comment by michaelrsweet** [comment]
Well, that *should* just work as long as the control file is properly formed (you didn't include that particular code).

At this point I don't see anything *we* can do to help - the cups-lpd code in CUPS 2.2.7 does set the last-document value when sending the print file when the control file is well-formed, so unless the control file in the python code is bad or the Linux distro you are using has a patch to cups-lpd that breaks the last-document support, I'm not sure what is going wrong here.

**Comment by cupsuser** [comment]
I have attached errors within the CUPS error_log file. The only error that looks to be present is:
'[Client 40] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)'

I adjusted the cupsd.conf file and included 'MultipleOperationTimeout 5' and now it prints after 5 seconds as I read your comment from earlier.

Full log for 1 print job:
[errors.txt](https://github.com/apple/cups/files/2428649/errors.txt)

**Comment by michaelrsweet** [comment]
Well, that just confirms my assessment - either the control file in the python code is bad OR the Linux distro you are using has a buggy cups-lpd.
