### ISSUE TITLE
Canon IR C1225 - driverless problems

### ISSUE THREAD

**Issue by tudor2k3** [apple/cups#5406]
Hello.

     I'm using Kubuntu 18.04 and when installing the Canon IR C1225 printer i have the following problems:
- printer ignores duplex page flipping choice: always flips on short edge
- printer does not respect A4 (haven't tried others) page setting: always uses letter
- printer does not respect colour/grayscale settings: always prints colours

     The above have been tried with Libreoffice, Okular, Adobe Reader DC (with wine).
     The printer had the above options set as default as well in it's menu (flip long edge, grayscale, A4), but it makes no difference.
     When using the official Canon driver everything works, except printing is VERY slow (starts printing a page in 30-40s) and if it's a document (or PDF) with more than 5 pages, it takes forever to even start printing. Printing in Windows works perfectly (and fast). Also, with the driverless install, printing is as fast as in Windows, except for the above problems.
     Please tell me if you need any logs or any other details.

                            Thank you.

**Comment by michaelrsweet** [comment]
Please report this problem to the Ubuntu folks - it sounds like either an issue with the cups-filters PPD generator or one of its filters.
