### ISSUE TITLE
Environment variable AR provided to configure cannot override the result of  AC_PATH_PROG(AR,ar)

### ISSUE THREAD

**Issue by dannftk** [apple/cups#5412]
Branch 2.2
I have already mentioned this issue happening [here](https://github.com/apple/cups/pull/5411)

There is a file *config-script/cups-common.m4* that has a line setting AR variable by searching for 'ar' program by means of PATH
```
...
AC_PATH_PROG(AR,ar)
...
```

When I try to configure and execute 'make' the following way
```
AR=llvm-ar CC=clang CXX=clang++ ./configure --with-optim="-g"
```
, I get the following line as a linker is linking a static library
```
/usr/bin/ar crvs libcups.a adminutil.o array.o auth.o backchannel.o backend.o debug.o dest.o dest-job.o dest-localization.o dest-options.o dir.o encode.o file.o getdevices.o getifaddrs.o getputfile.o globals.o hash.o http.o http-addr.o http-addrlist.o http-support.o ipp.o ipp-support.o langprintf.o language.o md5.o md5passwd.o notify.o options.o ppd.o ppd-attr.o ppd-cache.o ppd-conflicts.o ppd-custom.o ppd-emit.o ppd-localize.o ppd-mark.o ppd-page.o ppd-util.o pwg-media.o request.o sidechannel.o snmp.o snprintf.o string.o tempfile.o thread.o tls.o transcode.o usersys.o util.o 
```
*/usr/bin/ar* imposed as a result of AC_PATH_PROG having ignored AR provided from environment

I like somehow to override *AR* variable, now it seems impossible

In the [PR](https://github.com/apple/cups/pull/5411) I have offered the solution, please take it in consideration or suggest another way 

Thank you

**Comment by michaelrsweet** [comment]
You need to specify the full path in the environment variable, otherwise the configure script will ignore it.

(This is someplace in the autoconf documentation, but not in the help shown by the generated configure script for some reason - probably worth a bug against the autoconf project...)
