### ISSUE TITLE
Last page delayed on HP LaserJet 2200

### ISSUE THREAD

**Issue by niclasboy** [apple/cups#5414]
Hello,
i use a Raspberry Pi 3 with Cups as a printserver. When i print something, the last page is printed out after several minutes. How can I fix the problem?
Niclas

**Comment by michaelrsweet** [comment]
What driver are you using?

How is the printer connected?

What version of CUPS are you using?

**Comment by niclasboy** [comment]
I think I am using the latest version. I installed it today with apt-get install cups. The printer is connected with usb. I’m using following driver: „HP LaserJet 2200 - CUPS+Gutenprint v5.2.11 (schwarz-weiß, 2-seitiges Drucken)“

**Comment by niclasboy** [comment]
It is version 2.2.1

Thanks for your help!

**Comment by niclasboy** [comment]
With this driver it works: HP LaserJet 2200 pcl3, hpcups 3.16.11
