### ISSUE TITLE
Add support for dynamic IP with networked printers

### ISSUE THREAD

**Issue by domichel** [apple/cups#5415]
First thank you for the good work with CUPS.

Mac OS and even most windows versions work out of the box with printers which have dynamic IP on the network. It would be great if CUPS can do the same.

For now you have to reinstall these printers each time you want to use them, which is a pity, or to follow numerous forums threads which give me a headache just when I try to understand them and to figure out what to do, which also is a pity for the casual desktop user. To have dynamic IP support in CUPS would definitively be a great step forward for the gnu/linux desktop.

**Comment by michaelrsweet** [comment]
Um, CUPS *does* support “dynamic ip” addresses for printers, using mDNS and DNS-SD (Bonjour) at the time of each print job. It has done so for many years using the dnssd backend.

There are some Linux distributions that do not ship with Avahi (the chosen project for supporting mDNS/DNS-SD on Linux) properly enabled or configured - that is the most common reason for networking problems on Linux.
