### ISSUE TITLE
cups-browsed and sleep mode

### ISSUE THREAD

**Issue by andribas404** [apple/cups#5416]
Hello!
In cups 2.2.8 we have encountered following problem:
in /etc/cups/cups-browsed.conf set
CreateIPPPrinterQueues All
cups discovers and add printer queue.
When printer enters sleep mode queue disappears and we have to turn on printer manually to discover it again.
Is there a way to not remove created queues?

**Comment by zdohnal** [comment]
Hi,

this is actually question on other project, cups-filters https://github.com/OpenPrinting/cups-filters , because cups-browsed goes from cups-filters project.
