### ISSUE TITLE
cupsd IPC USB power on/connected state

### ISSUE THREAD

**Issue by Matteljay** [apple/cups#5417]
Hi i'm writing a label printing program. When trying to use CUPS i came across some issues when trying to determine if an USB printer is currently connected and/or powered on.

lpinfo --timeout 0 -v
Doesn't show the cups-printer name and is too slow as it forces me to wait at least 1 second for network devices

lpstat -p -d
lpstat -a -d
These commands show the printer_name, 'accepting'/'idle' state doesn't do much for determining wheter the printer is even connected

lpstat -v
It shows the printer_name + URI, unfortunately not useful for determining if a real /dev/usb/lpX exists

lpadmin
Great for messing with settings, not useful for device status afaik

/usr/lib/cups/backend/usb
Pretty good but this is not part of CUPS or Linux baseutils, but it is part of hplip. I'm assuming not all Linux systems have this. It comes close but doesn't really show the cups_printer_name

lsusb -v (not part of CUPS)
Pretty good but it doesn't show the printer_name and the output shows a lot of irrelevant info

Are there other (more reliable) ways to do IPC (inter-process-communication) with cupsd?

**Comment by michaelrsweet** [comment]
@Matteljay The USB backend is part of CUPS, not HPLIP. And we haven't use the USB character devices in a VERY long time.

If you run the backend and look at the reported device URIs, you can look for the device URI that matches what "lpstat -v" reports. If so, the printer is connected and powered on.
