### ISSUE TITLE
Server redirects to different server when used through ssh tunnel.

### ISSUE THREAD

**Issue by jolmg** [apple/cups#5419]
To reproduce:
1. have a cups server running locally on localhost:631
2. have a cups server running in another machine also on localhost:631
3. make a ssh-tunnel to access the cups server of the remote machine: `ssh -L 9000:localhost:631 remoteserver`
4. access the remote server via web-browser by visiting `http://localhost:9000`
5. add a printer

On the last page of the wizard for adding printers, you're asked to "Set Default Options". On hitting the button, one's taken to a page that says "Printer foo default options have been set successfully". Then, a couple seconds later, we're taken from `http://localhost:9000/admin` to `http://localhost:631/printers/foo`.

Here are some screenshots:

![cups-page-1](https://user-images.githubusercontent.com/17855790/47606459-b8af8f80-d9c8-11e8-8585-7ba55c57ff83.png)

![cups-page-2](https://user-images.githubusercontent.com/17855790/47606464-bcdbad00-d9c8-11e8-9074-9d816aabdbce.png)

![cups-page-3](https://user-images.githubusercontent.com/17855790/47606465-bfd69d80-d9c8-11e8-8311-4697f05d5fb5.png)

I imagine what's happening is that the server is seeing what port is listening on and putting that in the URL, but I don't think there is any reason why we can't just use the path and let the browser continue to use the domain and port it's been using. If it's necessary for that couple second delay and the intermediary page, why not just go directly to the third page? It seems to me that ssh tunneling to access remote servers that are bound only to localhost is a very common scenario.

**Comment by jolmg** [comment]
It just occurred to me to check closed issues, and I see this issue pops up every now and then. :)

I saw [this comment](https://github.com/apple/cups/issues/5307#issuecomment-385740669):

> This is a known limitation of using things like port forwarding, and unfortunately there isn't anything we can do (no notion of a relative URL that changes the scheme from HTTP to HTTPS).

However, I'm not redirected to HTTPS, so I'm not sure what it's referring to. In this case, where we're not configured to use HTTPS, can we have a relative reference in the Location header?

**Comment by jolmg** [comment]
I mean, I don't think there'll be many cases where one wants to use HTTPS **and** work through a SSH tunnel. While there are other uses for tunnels, I would think that most cases it's used as a simpler alternative to HTTPS to authenticate and encrypt traffic without having to deal with making certificates and whatnot.

**Comment by jolmg** [comment]
In fact, it doesn't really make sense to use HTTPS when the request is coming from localhost, so I think even if HTTPS were configured, the server could simply not require it when connecting from localhost. Wouldn't that make tunneling always work?

Wouldn't the ideal fix be to use relative URLs in the Location header when not using HTTPS and not use HTTPS when responding to localhost?

**Comment by jolmg** [comment]
On checking, it seems that second change is already done. If I try to add a printer on a server configured to use HTTPS, it doesn't require it if I'm coming in from localhost. It just does basic auth on HTTP it seems.

So this is really just about using relative URLs when not using HTTPS.

**Comment by michaelrsweet** [comment]
There are many dupes of this. The short answer is that we don't support SSH tunnels for the web interface, and have no plans of doing so in the future. Sorry.

**Comment by imsedgar** [comment]
... many dupes of this ... 
This means that many people run into the same problem. Its is a common issue - and a common problem. The solution (a fix) would be simple (just save the part before the path of the url, and use it for the answer instead of a fixed value).

Is there an understandable reason why a solution to the problem is rejected?

Would it help if someone would provide a patch for it?
