### ISSUE TITLE
Lexmark ms317dn needs no-reattach

### ISSUE THREAD

**Issue by euidzero** [apple/cups#5420]
Same as :

 https://github.com/apple/cups/issues/4900

Please add in /usr/share/cups/usb/org.cups.usb-quirks
0x043d 0x0226 no-reattach

**Comment by michaelrsweet** [comment]
[master 08761c26a] Add USB quirks rule for Lexmark MS317dn (Issue #5420)

[branch-2.2 3cc99f971] Add USB quirks rule for Lexmark MS317dn (Issue #5420)
