### ISSUE TITLE
Error when compiling from source

### ISSUE THREAD

**Issue by gerrat** [apple/cups#5423]
In a docker image based on Ubuntu 16.04, I'm trying to build from source:

    git clone https://github.com/apple/cups.git cups-2.3.5
    cd cups-2.3.5
    ./configure
    make

This results in: 

    Compiling ppd-cache.c...
    ppd-cache.c: In function ‘_ppdCreateFromIPP’:
    ppd-cache.c:3191:28: error: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
           memset(pattern, '1', maxlen);
                                ^
    ppd-cache.c:3193:28: error: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
           memset(pattern, 'A', maxlen);
                                ^
    ppd-cache.c:3195:28: error: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
           memset(pattern, 'C', maxlen);
                                ^
    ppd-cache.c:3197:28: error: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
           memset(pattern, '.', maxlen);
                                ^
    ppd-cache.c:3199:28: error: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
           memset(pattern, 'N', maxlen);
                                ^
    ppd-cache.c:3201:28: error: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
           memset(pattern, 'U', maxlen);
                                ^
    ppd-cache.c:3203:28: error: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
           memset(pattern, '*', maxlen);
                                ^
    ppd-cache.c:3967:32: error: conversion to ‘size_t {aka long unsigned int}’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
             memcpy(tray, tray_ptr, tray_len);
                                    ^
    ppd-cache.c: At top level:
    cc1: error: unrecognized command line option ‘-Wno-tautological-compare’ [-Werror]
    cc1: all warnings being treated as errors
    ../Makedefs:267: recipe for target 'ppd-cache.o' failed
    make[1]: *** [ppd-cache.o] Error 1
    Makefile:26: recipe for target 'all' failed
    make: *** [all] Error 1
    root@3fc63c9dbf0e:/srv/cups-2.3.5#

Is there a reason this shouldn't just compile from source?

**Comment by michaelrsweet** [comment]
This is probably the recent changes to re-enable -Werror on builds from a Git clone. As a temporary workaround you can pass "--with-option='-Os -g'" to the configure script.

PS: It isn't CUPS 2.3.5, master is currently what will become CUPS 2.3b6 (beta 6) - NOT a production release!

**Comment by michaelrsweet** [comment]
OK, I think we have things fixed, at least on Ubuntu 18.04.
