### ISSUE TITLE
Use LC_MESSAGES folder and converter po to mo

### ISSUE THREAD

**Issue by scootergrisen** [apple/cups#5424]
In Fedora i notice the translations are places in:

    /usr/share/locale/es/cups_es.po
    /usr/share/locale/pt_BR/cups_pt_BR.po
    /usr/share/locale/zh_CN/cups_zh_CN.po
    /usr/share/locale/de/cups_de.po
    /usr/share/locale/ja/cups_ja.po
    /usr/share/locale/fr/cups_fr.po
    /usr/share/locale/ru/cups_ru.po
    /usr/share/locale/ca/cups_ca.po
    /usr/share/locale/cs/cups_cs.po
    /usr/share/locale/it/cups_it.po

It seems other software converts the po files to mo files and places them in the LC_MESSAGES folder and they does not have the "_xx" part.

Perhaps use this instead to be consistent with how other software is placing/using translations:

    /usr/share/locale/es/LC_MESSAGES/cups.mo
    /usr/share/locale/pt_BR/LC_MESSAGES/cups.mo
    /usr/share/locale/zh_CN/LC_MESSAGES/cups.mo
    /usr/share/locale/de/LC_MESSAGES/cups.mo
    /usr/share/locale/ja/LC_MESSAGES/cups.mo
    /usr/share/locale/fr/LC_MESSAGES/cups.mo
    /usr/share/locale/ru/LC_MESSAGES/cups.mo
    /usr/share/locale/ca/LC_MESSAGES/cups.mo
    /usr/share/locale/cs/LC_MESSAGES/cups.mo
    /usr/share/locale/it/LC_MESSAGES/cups.mo

**Comment by michaelrsweet** [comment]
Since CUPS does NOT use GNU gettext (just the po format), we cannot do this. Files moved to the LC_MESSAGES subdirectory will not be found or be loadable, and so CUPS will NOT be able to localize anything.

**Comment by guoyunhe** [comment]
It is a great thing to have. It currently messed the file structure on Linux...
