### ISSUE TITLE
CUPS: Meaning of "Waitof" in socket backend

### ISSUE THREAD

**Issue by ThomasGBauer** [apple/cups#5425]
Hello everybody,

I'm now adressing my issue to your list, because neither anybody from SuSe support nor the conultants we contacted could answer our questions.

In our company we have the need to make sure that certain documents are really printed. If the print job is deleted from the queue before it is printed, a printer shutdown would kill the print job. 
Therefore we took a look at the CUPS documentation, and when using the socket backend we found the following statement:
...
AppSocket Protocol (aka JetDirect) 
... 
The "waiteof" option controls whether the socket backend waits for the printer to complete the printing of the job. The default is to wait (waiteof=true). Add waiteof=false to the URI to tell the backend not to wait. 
...

Now my questions:
What does "complete the printing of the job" really means?
We hoped that the print jobs stays in the queue until the printer has finished printing. In rare cases, typically after testing it on a newly created printer, it really worked that way (once). 
Further tests, where we tried to reproduce it, the print job was deleted from the queue directly after the printer has received the data, but not after printing it! 
Are than any restrictions to that? Does the printer has to meet certain requirements, or did we only misinterpret the CUPS documentation?

We are currently running cups-1.7.5 on SLES 12 SP3 and tried it with different HP Laserjet printers. 

Your issue
https://github.com/apple/cups/issues/2325
gave me the hope that we might be able to solve our problem with cups.

Any help would be apreciated.

Best regards
Thomas Bauer

**Comment by michaelrsweet** [comment]
The AppSocket protocol defines the behavior - the client device does a half-close of the socket when it is done sending data and then waits for the printer to close its half of the socket. The Printer closes its half of the socket when all media sheets have been delivered.

The "waiteof" option controls whether the socket backend waits for the printer to close its side of the socket.

**Comment by ThomasGBauer** [comment]
Thank you very much for this explanation. This already helps to get one step further. 
With HP-UX where we are using hpnpf instead of CUPS the print job is only deleted when it is completely printed. So we have there our desired behaviour. Therefore we think it is not an issue of the printer. 
We would assume that an information is missing telling the printer to only close the connection after printing. But who is responsible for this "information"? Is the information configured within the ppd files or somewhere else? Who might help me with that?
Any further ideas are very welcome.

**Comment by michaelrsweet** [comment]
In CUPS, the socket backend does the client-side close, then waits for the printer to close the other end of the socket - that's what the waiteof option controls.

**Comment by ThomasGBauer** [comment]
Now my hope is that, when preparing the job for printing there is a chance to add a command which tells the printer to only close the other end of the socket, when the job is really printed. Which "CUPS" component, e.g. ppd file, filter, etc. could do so? Or do we really have to develop / use a different backend?

**Comment by michaelrsweet** [comment]
It’s not a driver thing, it is a network controller thing you get “for free” (if the printer supports it)

**Comment by michaelrsweet** [comment]
It is not the case, there is no command controlling this behaviour.

**Comment by ThomasGBauer** [comment]
In specific I think about encapsulating a print job in PJL commands, becasue there is a PJL command USTATUS to tell the printer to send unsolicited status messages for device status changes, end-of-job status, and pages printed.
