### ISSUE TITLE
Missing declaration in compiling from source

### ISSUE THREAD

**Issue by jwith** [apple/cups#5430]
I am trying to build cups from master branch as of today under macOS 10.12.6 and Xcode 9.2 from the command line by means of ./configure;make;

```
Compiling tls.c...
In file included from tls.c:41:
./tls-darwin.c:1329:7: error: use of undeclared identifier 'kTLSProtocol13'
      kTLSProtocol13
      ^
```
First lines from configure output:

```
checking build system type... x86_64-apple-darwin16.7.0
checking host system type... x86_64-apple-darwin16.7.0
host_os_version=167
```

I am working with Linux since a very long time, but have only little experience with compiling from source on macOS, so I don't know if I missed updating/installing something.
Usually I would assume a missing test in configure.

**Comment by michaelrsweet** [comment]
No, this definition is new in macOS 10.13’s SDK, which the CUPS source requires,
