### ISSUE TITLE
How to save files in the CUPS server

### ISSUE THREAD

**Issue by wendraw** [apple/cups#5431]
I‘m installed CUPS2.2.1 in the Raspberry Pi. And now I want save the file sent from the client(Windows、macOS or iOS). What should I do?

**Comment by michaelrsweet** [comment]
There are a number of third-party CUPS backends that basically save print jobs to a directory, email them, etc. A quick google of "CUPS save backends" should get you going.

Alternately you can look in the /var/spool/cups directory for the "d" files - those will be the submitted print files. They are normally kept for 24 hours before deletion.

**Comment by wendraw** [comment]
> There are a number of third-party CUPS backends that basically save print jobs to a directory, email them, etc. A quick google of "CUPS save backends" should get you going.
> 
> Alternately you can look in the /var/spool/cups directory for the "d" files - those will be the submitted print files. They are normally kept for 24 hours before deletion.

I just can find "c0005" and "tmp/cups-dbus-notifier-lockfile" files in the /var/spool/cups. But I don't know the role of these files. Now I want to create a script to save the file send from the client and then print it using the "lp filename" command , Because the DNP printer is not working properly.

**Comment by jsmeix** [comment]
@wendraw 
I think
https://en.opensuse.org/SDB:Using_Your_Own_Backends_to_Print_with_CUPS
could help you.

Regarding 'd...' versus 'c...' files in CUPS' spool directory and
other general things about CUPS you may also have a look at
https://en.opensuse.org/SDB:CUPS_in_a_Nutshell

Regarding printing from Windows clients you may have a look at
https://en.opensuse.org/SDB:Printing_from_Windows_to_Linux

Some details might be different depending on what operating system
you run on your Raspberry Pi but in general CUPS behaves same.

**Comment by debiantriage** [comment]
> I just can find "c0005" and "tmp/cups-dbus-notifier-lockfile" files in the /var/spool/cups. But I don't know the role of these files. Now I want to create a script to save the file send from the client and then print it using the "lp filename" command , Because the DNP printer is  not working properly.

Tea4CUPS will do this.

-- 
Brian.

**Comment by wendraw** [comment]
> > I just can find "c0005" and "tmp/cups-dbus-notifier-lockfile" files in the /var/spool/cups. But I don't know the role of these files. Now I want to create a script to save the file send from the client and then print it using the "lp filename" command , Because the DNP printer is  not working properly.
> 
> Tea4CUPS will do this.
> 
> --
> Brian.

Tea4CUPS is what I want, you have helped me a lot!
