### ISSUE TITLE
'client-error-not-possible' on Linux Mint 19

### ISSUE THREAD

**Issue by jonathanpeixoto** [apple/cups#5432]
Hello!

Since my installation of Linux Mint 19, i can not print on both of my computers with it installed on them.
My printer model is DCPJ715W, from Brother.

Let me explain the situation : i have a router from which i receive the Internet. All of my computers are connected on it, and so is my printer (in USB).
I could print before (i can print from another computer with Linux Mint 18 installed on it and also with a computer under Windows).

The URI of my system where printing works (on Linux Mint 18), is: "ipp14://192.168.1.1".

And, on my Linux Mint 19 system (where printing doesn't work), when i put that URI, it gives me the error i contact you for, which is, "CUPS server error... client-error-not-possible".

I tried different things, like checking the packages in common between my system where printing works and the one in problem, trying to delete cups, etc, but...

I precise that it always worked before! Everything, i only had to install the packages from Brother's website.

I'd like to understand how to get more information from the problem on the computer! Is that possible?
I checked in the journal but, the problem is that i can not get an error when i put the good URI because, as the error appears when i try to apply the modification, i can not test a printing with this URI configuration.

Would an update of the version resolve the problem?

Thank you very much!

-Jonathan-

**Comment by michaelrsweet** [comment]
"ipp14" is not a standard URI scheme (backend) for CUPS.

You can enable debug logging with "cupsctl --debug-logging".
