### ISSUE TITLE
cupsManualCopies is not set by _ppdCreateFromIPP

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5433]
The `pdftopdf` does a wide range of page management options (multiple copies, N-up, page-ranges, page-set, ...) but modern IPP printers do many of the page management, too. This often leads to cases where an option supplied to the job is applied twice, for example instead of the requested n copies one gets n*n copies.
What is needed is that `pdftopdf` gets somehow informed about which options the printer already supports and therefore should not get applied by `pdftopdf`. As `pdftopdf` cannot IPP-query the printer to check by itself (it even does not know whether the printer is an IPP printer) and as the printer's capabilities do not change, the probably best way is to use the PPD file.
So the PPD generator for auto generation of the PPDs for driverless printing should put hints into the PPD about which options the printer already takes care of internally, so that `pdftopdf` can skip these options.
The options handles by `pdftopdf` are the following:
- copies
- print-scaling/fitplot/fit-to-page
- orientation-requested/landscape
- number-up
- number-up-layout
- page-border
- page-delivery/output-order/OutputOrder
- page-label
- page-set (even/odd)
- page-ranges
- mirror/MirrorPrint
- booklet
- booklet-signature
- position
- collate/Collate
- scaling
- natural-scaling

AFAIK Copies and OutputOrder are already handled. Am I correct that I should let `pdftopdf` only generate copies if the PPD has the entry `*cupsManualCopies: True`?
So for the other options we would need entries in the generated PPD, telling which options `pdftopdf` should skip.
In addition, there should be an entry added to the PPD, telling that the printer is an IPP driverless printer, so that options which are done by all IPP printers do not need to get mentioned individually.
Once we have this facility in the PPD generator I can add appropriate support to `pdftopdf`.

**Comment by RobertKrawitz** [comment]
Some of these options might be handled most efficiently on the host even if the printer supports them.  In particular, applying page-ranges on the host will reduce the amount of network traffic.

(Remember also that we're getting away from PPD files.  Finally.)

**Comment by michaelrsweet** [comment]
@tillkamppeter PDF-capable printers are always capable of collated/uncollated copies, so your filter should NEVER generate the copies itself unless you see cupsManualCopies: True (which indicates a non-PDF printer that needs copies to be generated).

**Comment by michaelrsweet** [comment]
PDF = copies supported
JPEG = copies supported
Others = assume no copies supported

cupsManualCopies is true if the printer can’t do both collated and uncollated copies. It is all you need.

**Comment by tillkamppeter** [comment]
The PPD generator of CUPS never sets "`*cupsManualCopies: True`". Does it mean that ALL IPP driverless printers, including Apple-Raster-only ones do support copies and collate in the printer?

**Comment by michaelrsweet** [comment]
Renaming this bug and re-opening - this keyword should be set for raster printers.

**Comment by tillkamppeter** [comment]
Another remark: You recommend all page management operations except copies, collate, and output-order be done by the client. Does the IPP backend filter the appropriate options (in the 5th command line argument) to not being passed on to the IPP printer to avoid duplicate application?

**Comment by michaelrsweet** [comment]
@tillkamppeter Yes, the backend omits attributes when sending raster data streamed to the backend.
