### ISSUE TITLE
CUPS fails to communicate with pstoufr2cpca (Canon UFR II filter )

### ISSUE THREAD

**Issue by esternin** [apple/cups#5434]
The error showed up once I updated from CUPS 2.1 to 2.2, on a Slackware64 v14.2, as a part of a routine update to the system from the standard distribution channel. It does not depend on the Canon driver version (310, 320, 340, 360 - the latest, October 2018), and all exhibit the same symptoms: error_log reports that pstoufr2cpca fails with:
   `ERROR: can't make parameter.`
It appears that a calling sequence from CUPS to invoke the filter may have changed between v.2.1 and 2.2, as the error seems to come from this part of the filter code:
```
   if( make_cmd_arg(p_cups_opt, num_opt, p_ps_param, cmd_arg, copies, argv[2], argv[3]) < 0 ) {
	    fputs("ERROR: can't make parameter.\n", stderr);
	    goto error_return;
	    } 
```
The error has been [reported previously (May 2017)](https://www.pclinuxos.com/forum/index.php?topic=141916.0) with no apparent resolution.

All Canon executables report no ldd errors, CUPS is able to communicate directly with an HP network printer (using lpr, PCL or PostScript), but not directly to the Canon UFRII printer (MF4370dn, if it matters), also using lpr but via pstoufr2cpca to pre-process files before sending.

Can anybody suggest what happened here? Why would there be a change to the standard filter invocation sequence? The log file on the working CUPS 2.1 Slackware 14.1 node seems to report nothing different. I held off updating that node, but this approach cannot be maintained for long. The problem persisted through several version updates in CUPS 2.2.* series.

**Comment by michaelrsweet** [comment]
The calling sequence has not changed.

Almost certainly this is either Ghostscript or glibc, both of which have been responsible for a number of recent printing-related bugs on various distros.

**Comment by esternin** [comment]
Not sure what to make of this.  Several other filters from Ghostscript seem to complete without erro, so gs engine seems to be just fine.  ldd and hand-invoking the pstoufr2cpca filter executable produce no glib errors. Can you point to a debugging/resolution example, perhaps for another printer, that I could learn from?

**Comment by esternin** [comment]
Thanks for the pointers, Johannes. I did look into most of what you mention.

Canon support responds:
"The Linux driver package includes code components that were not written by Canon or its affiliates. In addition, Linux exists in many different versions, and the driver cannot be tested against all of them. Thus, Canon is not able to provide a support program for this driver software."

You are right about this being the pstoufr2cpca issue:

```
$ pstoufr2cpca 344 username "tiger test" 1 "" tiger.eps
DEBUG: pstoufr2cpca start.
ERROR: can't make parameter.

```
I was **hoping** it was caused by a change in CUPS, because it coincided with a 2.1 -> 2.2 transition in CUPS. [I now think it is a 32b/64b issue in the  pstoufr2cpca.c code, as it has not changed in years, while the 32b compatibility has been eroding.] I see no changes to the pstoufr2cpca code in https://github.com/krichter722/cndrvcups-lb/tree/master/pstoufr2cpca in years, and the source of the Canon-distributed version seems indistinguishable from this though the version numbers increase, so this driver appears to be unmaintained.

ghostscript fails on an empty pipe from pstoufr2cpca, it's a spurious log entry, so 'wedgetail' comment is correct, but not helpful in tracing the problem itself.

If somebody is maintaining the How_to_Report_a_Printing_Issue and similar guides, it would be helpful if the actual calling sequence for a filter was documented there; as it was, I could not find it documented anywhere and had to reverse-engineer the above parameter sequence (job# username title #copies options filename) from the code.

I'll spend some time trying to sort out the error, but discarding Canon hardware might be cheaper.

Thanks again.

**Comment by jsmeix** [comment]
@esternin 
I am the author and maintainer and the "anything-else-one" ;-) for
https://en.opensuse.org/SDB:How_to_Report_a_Printing_Issue
cf.
https://en.opensuse.org/index.php?title=SDB:How_to_Report_a_Printing_Issue&action=history

This article is primarily meant to guide unexperienced Linux users
how to _report_ a printing issue
so that others (experienced Linux users) have at least a chance
to understand what goes on to be able to provide useful help.

What is missing is a separated new article that is about
"how to analyze and debug a printing issue"
for experienced Linux users.
Such an article is much more complicated to write
because there are many different cases of printing issues
and each case is usually complicated in its own specific way
(this issue here is a good example).
As time permits I will try to make such an article but no promises
because nowadays my main working area is "disaster recovery"
cf. https://en.opensuse.org/SDB:Disaster_Recovery

**Comment by jsmeix** [comment]
@esternin 
a side note regarding 32-bit versus 64-bit issues in printer driver software:
Because print job data processing to get the final printer specific data
happens via a traditional Unix pipe of separated filtering programs,
cf. the section "The Filter (includes the Driver)" in
https://en.opensuse.org/SDB:CUPS_in_a_Nutshell
and
https://en.opensuse.org/SDB:Using_Your_Own_Filters_to_Print_with_CUPS
I think it should not matter if one filtering program is 64-bit
and another one is 32-bit.
The precondition on a 64-bit system is that all needed 32-bit libraries exist
to run 32-bit programs on a 64-bit system.
I think when a needed 32-bit library is not there a 32-bit program should
not even start but fail early during its initial dynamic linking phase
with an `error while loading shared libraries`.

**Comment by esternin** [comment]
Good on ya, they are some of the most detailed guides I have encountered, well done.

I agree about the difficulty writing the next level manuals, but I do think the basic structural information is hidden at the moment, an executive summary of the CUPS flow. A chain of filters is the strength  - and a weakness, when something goes wrong, because the error reported isn't necessarily where the problem is.

What I meant by 32b is that the original code was written for 32b world, with little if any maintenance for years while the runtime libraries and compilers evolved rapidly. I almost wish small filters like this one were static compiled!

Somebody, make a printer with CUPS supported in firmware!

On November 13, 2018 3:43:01 AM EST, Johannes Meixner <notifications@github.com> wrote:
>@esternin 
>I am the author and maintainer and the "anything-else-one" ;-) for
>https://en.opensuse.org/SDB:How_to_Report_a_Printing_Issue
>cf.
>https://en.opensuse.org/index.php?title=SDB:How_to_Report_a_Printing_Issue&action=history
>
>This article is primarily meant to guide unexperienced Linux users
>how to _report_ a printing issue
>so that others (experienced Linux users) have at least a chance
>to understand what goes on to be able to provide useful help.
>
>What is missing is a separated new article that is about
>"how to analyze and debug a printing issue"
>for experienced Linux users.
>Such an article is much more complicated to write
>because there are many different cases of printing issues
>and each case is usually complicated in its own specific way
>(this issue here is a good example).
>As time permits I will try to make such an article but no promises
>because nowadays my main working area is "disaster recovery"
>cf. https://en.opensuse.org/SDB:Disaster_Recovery
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/apple/cups/issues/5434#issuecomment-438182774

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by debiantriage** [comment]
How joyously this comment is greeted is anyone's guess. :)

I installed a print queue for a Canon MF4010 and, heeding the warning in filters(7), ran cupsfilter (see the Debian wiki). All filters exited without an error. I'm on Debian unstable.

-- 
Brian.

**Comment by esternin** [comment]
I do not quite understand... did anything show up on the printer?

Because this is the problem: when cups runs the filter chain, it does not pick up a failure in the ps2ufr2cpca filter. The print job is reported as completed, and the log files look clean.  Except nothing reaches the printer itself (in my case, it remains asleep).

However, if you run the filter executable as I've shown above, it crashes out.

If you increase the reporting level to debug, a subtle message can be found in error_log, which is how I tracked down the error. If you just tested the standard cupsfilter reporting, without an attempt to communicate with an actual printer, you would not have seen anything wrong.

I guess, this is why this discussion is continuing here, because CUPS error detection/logging has failed in this case.

**Comment by debiantriage** [comment]
> I do not quite understand... did anything show up on the printer?

I do not have the printer. But do not need it to see that ps2ufr2cpca did not fail when tested via cupsfilter.

> However, if you run the filter executable as I've shown above, it crashes out.

I too get "can't make parameter". It is not intended that the filter be run in the way you did. Please read the filter manual.

> I guess, this is why this discussion is continuing here, because CUPS error detection/logging has failed in this case.

Not at all. The failure is in the user's misuse of /usr/lib/cups/filter/pstoufr2cpca.

-- 
Brian.

**Comment by debiantriage** [comment]
> Not at all. The failure is in the user's misuse of /usr/lib/cups/filter/pstoufr2cpca.

PPD=/etc/cups/ppd/4010.ppd /usr/lib/cups/filter/pstoufr2cpca 1 1 1 1 1 test.ps > out.ufr

succeeds here.

-- 
Brian.

**Comment by jsmeix** [comment]
FYI
an addedum regarding my above
https://github.com/apple/cups/issues/5434#issuecomment-438182774
therein "how to analyze and debug a printing issue":

I made now as a first step the section
"A filter that sends its input into a file for debugging" in
https://en.opensuse.org/SDB:Using_Your_Own_Filters_to_Print_with_CUPS
which is referenced at "See also" in
https://en.opensuse.org/SDB:How_to_Report_a_Printing_Issue
together with the already existing section
"A backend that sends its input into a file for debugging" in
https://en.opensuse.org/SDB:Using_Your_Own_Backends_to_Print_with_CUPS
