### ISSUE TITLE
cups2.2.8,I still can not open https://127.0.0.1:631,why??

### ISSUE THREAD

**Issue by pc666** [apple/cups#5436]
always forbidden,no matter how to solve

**Comment by jsmeix** [comment]
?

**Comment by michaelrsweet** [comment]
@pc666 What operating system/Linux distribution are you using?

What browser are you using?

Can you attach a screenshot?

**Comment by pc666** [comment]
when I view http://127.0.0.1:631,I always be forbidden. so sad...

**Comment by pc666** [comment]
> @pc666 What operating system/Linux distribution are you using?
> 
> What browser are you using?
> 
> Can you attach a screenshot?

chrome and firefox,they all fail

**Comment by pc666** [comment]
> ?

when I view http://127.0.0.1:631,I always be forbidden. so sad.

**Comment by michaelrsweet** [comment]
@pc666 What operating system/Linux distribution are you using?

**Comment by pc666** [comment]
> @pc666 What operating system/Linux distribution are you using?
> 
> What browser are you using?
> 
> Can you attach a screenshot?



> @pc666 What operating system/Linux distribution are you using?

I wanted to use cups on my raspberry pi,yeah,that is raspberry pi. It uses linux 9.1

**Comment by michaelrsweet** [comment]
@pc666 Can you try running:

    sudo service cups start

**Comment by pc666** [comment]
> @ pc666你可以尝试运行：
> 
> ```
> sudo service cups start
> ```

yes，I have tried it。

**Comment by pc666** [comment]
> @pc666 Can you try running:
> 
> ```
> sudo service cups start
> ```

I have tried 2.2.8，2.2.7,2.2.6，they all failed。Now，I will try 1.7.5.

**Comment by pc666** [comment]
> @ pc666你可以尝试运行：
> 
> ```
> sudo service cups start
> ```

![image](https://user-images.githubusercontent.com/44314180/48417140-f6fccb00-e78c-11e8-94d3-9379b10faed8.png)

**Comment by michaelrsweet** [comment]
You probably don't have the OpenSSL developer package installed - that or the GNU TLS developer package are required to build CUPS 1.x with HTTPS support. In CUPS 2.x only GNU TLS is supported...

**Comment by pc666** [comment]
> GNU TLS

oh，let me try try try。thank big boss

**Comment by pc666** [comment]
> 您可能没有安装OpenSSL开发人员包 - 或者需要GNU TLS开发人员包来构建具有HTTPS支持的CUPS 1.x. 在CUPS 2.x中，仅支持GNU TLS ...

why it always have errors in http.c
![image](https://user-images.githubusercontent.com/44314180/48418587-9ec7c800-e790-11e8-921e-e89a1057d0f4.png)

**Comment by pc666** [comment]
> 您仍在使用OpenSSL构建 - 尝试使用--enable-gnutls配置选项。

oh,thanks,I am installing gnutls.

**Comment by pc666** [comment]
> You are still building with OpenSSL - try the --enable-gnutls configure option.

I tried the --enable-gnutls configure option. 
It still failed.
cups.service - CUPS Scheduler
   Loaded: loaded (/lib/systemd/system/cups.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Wed 2018-11-14 17:01:58 HKT; 8s ago
     Docs: man:cupsd(8)
  Process: 11306 ExecStart=/usr/sbin/cupsd -l (code=exited, status=0/SUCCESS)
 Main PID: 11306 (code=exited, status=0/SUCCESS)

11月 14 17:01:58 xiphoray systemd[1]: Started CUPS Scheduler.
11月 14 17:01:58 xiphoray cupsd[11306]: cupsd: On-demand support not compiled in, running in normal mode.

**Comment by pc666** [comment]
c

**Comment by pc666** [comment]
> You are still building with OpenSSL - try the --enable-gnutls configure option.

now I have accessed in 127.0.0.1 successfully,but ,no matter which button I clicked,they all displayed"Internal server error"

**Comment by pc666** [comment]
> You are still building with OpenSSL - try the --enable-gnutls configure option.

oh，thank dalao ， I succeed finally.
It needs command "sudo service cups reload" firstly.
