### ISSUE TITLE
MaxJobTime does not match documentation for a value of 0

### ISSUE THREAD

**Issue by nahall** [apple/cups#5438]
According to the documentation:

> MaxJobTime seconds
> Specifies the maximum time a job may take to print before it is canceled. Set to "0" to disable cancellation of "stuck" jobs. The default is "10800" (3 hours).
> 

But setting "MaxJobTime 0" as the document suggests, instead of disabling the cancellation of stuck jobs, causes jobs to be canceled as "stuck" basically immediately. In my testing, perhaps half of the jobs made it through and were printed and half were canceled immediately by CUPS before they could be printed.

Relevant log line:

`I [13/Nov/2018:21:41:11 -0600] [Job 2513920] Canceling stuck job after 0 seconds.
`

**Comment by michaelrsweet** [comment]
Investigating...

**Comment by michaelrsweet** [comment]
Probably best to set the job-cancel-after-default value to "no-value" (IPP_TAG_NOVALUE) so that we don't default it...

**Comment by michaelrsweet** [comment]
[master 8c7143551] Fix handling of MaxJobTime 0 (Issue #5438)

[branch-2.2 3e4dd4145] Fix handling of MaxJobTime 0 (Issue #5438)
