### ISSUE TITLE
Backport Page Accounting Fixes to CUPS 2.2.x

### ISSUE THREAD

**Issue by zdohnal** [apple/cups#5439]
Hi Mike,

I was going to rebase CUPS in Fedora to 2.2.9, so I ran 'make check' above the source (without any downstream patches applied) and I found out one test is failing:

PASS: cupsd exited with no errors.
PASS: All job control files purged.
PASS: Printer 'Test1' correctly produced 113 page(s).
PASS: Printer 'Test2' correctly produced 23 page(s).
FAIL: Printer 'Test3' produced 5 page(s), expected 4.
PASS: 163 requests logged.

Test3 is ipp everywhere printer, created in test by:
 lpadmin -p Test3 -E -v ipp://localhost:8631/printers/Test2 -m everywhere

Here are the logs: 
[cups-str-2018-11-16-zdohnal.html.txt](https://github.com/apple/cups/files/2588769/cups-str-2018-11-16-zdohnal.html.txt)

The test passed with cups-2.2.8. Would you mind looking into it?

**Comment by michaelrsweet** [comment]
I've done a bunch of runs of 'make check' - some pass, some fail. I believe the issue is that the page accounting isn't 100% reliable. I will investigate back-porting the CUPS 2.3 accounting changes.

In the meantime, this particular failure shouldn't prevent you from using 2.2.9...

**Comment by michaelrsweet** [comment]
Original changes in Issue #4991.

**Comment by michaelrsweet** [comment]
[branch-2.2 450310bd9] Back-port accounting changes from CUPS 2.3 (Issue #5439)
