### ISSUE TITLE
2.2.9 lpadmin -E regression for raw printers ?

### ISSUE THREAD

**Issue by OdyX** [apple/cups#5440]
After uploading 2.2.9 to Debian unstable, the CI runner (which run a test on an _installed_ CUPS instance) started to fail: https://ci.debian.net/packages/c/cups/testing/amd64/

Specifically: https://ci.debian.net/data/autopkgtest/testing/amd64/c/cups/1329969/log.gz

The following command is launched:
```
lpadmin -p test-printer0 -E -m raw -v file:///dev/null
```
It spits "incorrect request" and the printer is not created, but reading from the logs didn't allow me to understand why.

This only started to fail in 2.2.9; and running `lpadmin` without the `-E` then `cupsenable` seems to work.

What has changed?

**Comment by michaelrsweet** [comment]
This could be a regression caused by the fix for Issue #5305.

**Comment by OdyX** [comment]
Indeed. Reverting both a83658fac59537cf1caf99791fa7edb0deb95c6f and 2b4e4ed7d80b47f9aaf6b98aaa85cf2c0e9273a9 fixes this. No good idea how to go forward with this though.

**Comment by michaelrsweet** [comment]
I'll need to trace things through to make sure we are still creating the queue properly. Raw support has been deprecated, of course, but it is still supposed to work...

**Comment by michaelrsweet** [comment]
(and I've been able to reproduce locally, at least, so we'll see where this goes...)

**Comment by michaelrsweet** [comment]
[master c29d06f9f] Fix -E option (Issue #5440)

[branch-2.2 d3cfe0652] Fix -E option (Issue #5440)
