### ISSUE TITLE
USB Star Receipt Printers (TSP743) don't finish printing raw queue (solution inside)

### ISSUE THREAD

**Issue by markalston** [apple/cups#5443]
Cups 2.4b4

Raw Queue USB Star Micronics receipt printers are failing to print the entire receipt and fail to cut the receipt at the end.  

Tested that the cups saved job works fine when cat'ed directly to the /dev/usb/lp0 device but fail via lpr or lp.

Solved the issue by creating a /usr/share/cups/usb/starprinter file with 
```
#Star receipt printer fixes
0x0519 0x0001 delay-close
```

**Comment by michaelrsweet** [comment]
OK, we'll add this to our quirks file....

**Comment by michaelrsweet** [comment]
[branch-2.2 944861cf8] Add USB quirk rule for Star printer (Issue #5443)

[master ffcecff2d] Add USB quirk rule for Star printer (Issue #5443)
