### ISSUE TITLE
basic authentication not promted in google chrome

### ISSUE THREAD

**Issue by pager72** [apple/cups#5444]
Currently google chrome for linux does not prompt user for authentication under cups administration pages such as adding printers. However it works fine for Firefox and likely several other browsers but not google chrome.

**Comment by michaelrsweet** [comment]
@pager72 What version of CUPS?

What version of Chrome?

What Linux distro?

**Comment by pager72** [comment]
Cups 2.2.9
Google-Chrome 70
Gento AMD 64

**Comment by michaelrsweet** [comment]
This could be Chrome not supporting auth with a self-signed certificate. Investigating...

**Comment by michaelrsweet** [comment]
OK, I just went through a full sweep of tests of the base CUPS sources and was able to authenticate using Chrome and other browsers. I suspect you are running into a Gentoo-specific issue...

**Comment by pager72** [comment]
what issue can it be?

**Comment by michaelrsweet** [comment]
A gentoo specific patch to CUPS or something else that only gentoo does.

**Comment by pager72** [comment]
The following things are disabled in my cups build on gentoo - zeroconf xinetd systemd static-libs lprng-compat kerberos java debug.

**Comment by dbrsseau** [comment]
Why this is closed? What is the solution? What is gentoo? I've just finish my installation of a fresh copie of Linux Mint 19.1 and I can't login in to the cups administration page with Chrome. It work only with Firefox... Am I missing something?

**Comment by pager72** [comment]
It wasn'tt a gentoo problem its a chrome on linux issue.
