### ISSUE TITLE
Defining PaperDimension and ImageableArea for labels on roll-fed media

### ISSUE THREAD

**Issue by crishoj** [apple/cups#5446]
I'm unsure how to properly define `PaperDimension` and `ImageableArea` for adhesive labels on liner paper (for use in a Citizen label printer).

The labels themselves are exactly 80 mm wide and 50 mm tall, and are placed with a 1.9 mm margin on each side on the liner paper, and 1.6 mm of gap between labels.

Should I include include one or both margins of the liner in `PageSize`, for a total of 232 or 238 points, respectively, and then define the non-printable margin using `ImageableArea`?

**Comment by michaelrsweet** [comment]
If the printer does not account for the gaps, then the ImageableArea will provide the location of the label within the gapped region. So for the values you gave you'd probably use:

    *PaperDimension 80x50mm: "237.54 146.27"
    *ImageableArea 80x50mm: "5.39 2.27 232.16 144"

**Comment by crishoj** [comment]
Thank you!
