### ISSUE TITLE
cupstestppd DefaultGuaranteedMaxSeparations/DefaultColorModel without options issues warning

### ISSUE THREAD

**Issue by carrotGrass** [apple/cups#5447]
My PPD contains the line "*DefaultGuaranteedMaxSeparations: 4" and cupstestppd generates the following warning:
        WARN    DefaultGuaranteedMaxSeparations has no corresponding options.

According to the 5645.PPD_Update spec:
If only one value for *GuaranteedMaxSeparations is applicable for a product, then only *DefaultGuaranteedMaxSeparations may be supplied. 
Here is an example.
   *DefaultGuaranteedMaxSeparations: 2

The same issue applies the the DefaultColorModel keyword.

I've added attached a patch fixing the issue:
[cupstestppd.c.patch.zip](https://github.com/apple/cups/files/2629985/cupstestppd.c.patch.zip)

**Comment by michaelrsweet** [comment]
Since PPDs and printer drivers are deprecated, we won't be addressing this issue. Sorry.
