### ISSUE TITLE
[feature request] Please add support of systemd built-in bonjour service (nss_resolve).

### ISSUE THREAD

**Issue by enihcam** [apple/cups#5452]
Please add support of systemd built-in bonjour service (nss_resolve). According to https://www.freedesktop.org/software/systemd/man/nss-resolve.html, systemd-resolved(nss_resolve) is the successor of avahi(nss_mdns).

**Comment by michaelrsweet** [comment]
Based on the available documentation, this is not a replacement for Avahi - all it does is handle resolving .local hostnames, but we also use Avahi for discovery.

**Comment by enihcam** [comment]
@michaelrsweet systemd-resolved itself is a `full Multicast DNS responder`.
https://systemd.network/resolved.conf.html#MulticastDNS=

**Comment by michaelrsweet** [comment]
@enihcam systemd-resolved does not support service browsing, which makes it useless for CUPS.

**Comment by michaelrsweet** [comment]
Please look at the DBUS API "documentation" provided for the systemd resolver - you'll notice an absence of anything that can be used to browse for service types or register a service instance and its TXT/LOC records. DNS-SD support is more than resolving the address for a name...

**Comment by michaelrsweet** [comment]
https://www.freedesktop.org/wiki/Software/systemd/resolved/

**Comment by michaelrsweet** [comment]
And digging deeper I find that only systemd services can register DNS-SD records - there is no support for anything more...

**Comment by nursoda** [comment]
According to https://www.freedesktop.org/wiki/Software/systemd/resolved/ , systemd-resolved does have service discovery implemented by now, right? I'm just asking here since https://wiki.archlinux.org/index.php/CUPS#Network still points to this issue stating that "CUPS does not support using systemd-resolved for DNS-SD".

Not sure about your last comment on which services can register DNS-SD records though …

**Comment by michaelrsweet** [comment]
@nursoda systemd's resolved only handles mDNS hostname lookups (something.local) and not generic service discovery. WRT my comment two years ago about service registration, systemd supports registering a SRV and TXT record for a systemd service (e.g. a _ipps-system._tcp service registration for cupsd, if it supported the IPP System Service), but not "sub-services" under that systemd service (like the individual printer registrations to _ipp._tcp and _ipps._tcp), nor does it support DNS-SD sub-types (like _print._sub._ipp._tcp for IPP Everywhere), flagship naming (_printer._tcp is used to reserve service instance names for network printers).

**Comment by quentinmit** [comment]
> @nursoda systemd's resolved only handles mDNS hostname lookups (something.local) and not generic service discovery. WRT my comment two years ago about service registration, systemd supports registering a SRV and TXT record for a systemd service (e.g. a _ipps-system._tcp service registration for cupsd, if it supported the IPP System Service), but not "sub-services" under that systemd service (like the individual printer registrations to _ipp._tcp and _ipps._tcp), nor does it support DNS-SD sub-types (like _print._sub._ipp._tcp for IPP Everywhere), flagship naming (_printer._tcp is used to reserve service instance names for network printers).

systemd-resolved now supports both service discovery and runtime service registration.

There's a blog post at https://daenney.github.io/2021/11/14/replacing-avahi-exploring-dnssd/ that explains how to do service discovery, but the gist is:

```
$ dbus-send --system --print-reply --dest=org.freedesktop.resolve1 \
   /org/freedesktop/resolve1 \
   org.freedesktop.resolve1.Manager.ResolveRecord \
   int32:0 string:"_ipp._tcp.local" uint16:1 uint16:12 \
   uint64:0
# then using one of the returned service names
$ dbus-send --system --print-reply --dest=org.freedesktop.resolve1 \
   /org/freedesktop/resolve1 \
   org.freedesktop.resolve1.Manager.ResolveService \
   int32:0 string:"Printer Name" string:"_ipp._tcp" string:"local" \
   int32:2 \
   uint64:0
```

and dynamic service registration is done with the `RegisterService` and `UnregisterService` methods.

Can this issue please be reopened now that systemd-resolved appears to have the necessary discovery and advertisement features?
