### ISSUE TITLE
Unable to send postscript print to Xerox 100 EPS printer from CUPS 1.63

### ISSUE THREAD

**Issue by Rashi-Sonthalia3** [apple/cups#5456]
Below is the error log :+1: 

d [10/Dec/2018:09:23:39 -0500] select_timeout: JobHistoryUpdate=1544461913
d [10/Dec/2018:09:23:39 -0500] cupsdAcceptClient(lis=0x563a1fa4ce00(10)) Clients=1
D [10/Dec/2018:09:23:39 -0500] cupsdAcceptClient: skipping getpeercon()
D [10/Dec/2018:09:23:39 -0500] [Client 14] Accepted from 10.230.4.36:631 (IPv4)
d [10/Dec/2018:09:23:39 -0500] cupsdAddSelect(fd=14, read_cb=0x563a1d797a20, write_cb=(nil), data=0x563a1fb77700)
d [10/Dec/2018:09:23:39 -0500] select_timeout: JobHistoryUpdate=1544461913
d [10/Dec/2018:09:23:39 -0500] [Client 14] cupsdReadClient error=0, used=0, state=HTTP_WAITING, data_encoding=HTTP_ENCODE_LENGTH, data_remaining=0, request=(nil)(), file=-1
d [10/Dec/2018:09:23:39 -0500] [Client 14] Saw first byte 16, auto-negotiating SSL/TLS session.
D [10/Dec/2018:09:23:39 -0500] [Client 14] Encrypting connection.
D [10/Dec/2018:09:23:39 -0500] Connection from 10.230.4.36 now encrypted.
d [10/Dec/2018:09:23:39 -0500] select_timeout: JobHistoryUpdate=1544461913
d [10/Dec/2018:09:23:40 -0500] [Client 14] cupsdReadClient error=0, used=0, state=HTTP_WAITING, data_encoding=HTTP_ENCODE_LENGTH, data_remaining=0, request=(nil)(), file=-1
D [10/Dec/2018:09:23:40 -0500] [Client 14] HTTP_WAITING Closing on EOF
D [10/Dec/2018:09:23:40 -0500] [Client 14] Closing connection.
D [10/Dec/2018:09:23:40 -0500] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
d [10/Dec/2018:09:23:40 -0500] cupsdAddSelect(fd=14, read_cb=0x563a1d797a20, write_cb=(nil), data=0x563a1fb77700)
d [10/Dec/2018:09:23:40 -0500] select_timeout: JobHistoryUpdate=1544461913
d [10/Dec/2018:09:23:40 -0500] [Client 14] cupsdReadClient error=32, used=0, state=HTTP_WAITING, data_encoding=HTTP_ENCODE_LENGTH, data_remaining=0, request=(nil)(), file=-1
D [10/Dec/2018:09:23:40 -0500] [Client 14] HTTP_WAITING Closing on EOF
D [10/Dec/2018:09:23:40 -0500] [Client 14] Closing connection.
D [10/Dec/2018:09:23:40 -0500] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
d [10/Dec/2018:09:23:40 -0500] cupsdRemoveSelect(fd=14)
d [10/Dec/2018:09:23:40 -0500] select_timeout: JobHistoryUpdate=1544461913
d [10/Dec/2018:09:23:41 -0500] select_timeout: JobHistoryUpdate=1544461913
d [10/Dec/2018:09:23:41 -0500] select_timeout(0): 299 seconds to timeout a client connection
d [10/Dec/2018:09:23:42 -0500] [Client 16] cupsdReadClient error=0, used=0, state=HTTP_WAITING, data_encoding=HTTP_ENCODE_LENGTH, data_remaining=0, request=(nil)(), file=-1
D [10/Dec/2018:09:23:42 -0500] [Client 16] GET /admin/log/error_log? HTTP/1.1
D [10/Dec/2018:09:23:42 -0500] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"
d [10/Dec/2018:09:23:42 -0500] cupsdFindBest: uri = "/admin/log/error_log?"...
d [10/Dec/2018:09:23:42 -0500] cupsdFindBest: Location /admin/conf Limit 7f
d [10/Dec/2018:09:23:42 -0500] cupsdFindBest: Location /admin Limit 7f
d [10/Dec/2018:09:23:42 -0500] cupsdFindBest: Location / Limit 7f
d [10/Dec/2018:09:23:42 -0500] cupsdFindBest: best = /admin

**Comment by michaelrsweet** [comment]
@Rashi-Sonthalia3 The log doesn't show the creation of a job or the processing (`[Job nnn]`) comments, so it is impossible to diagnose why things aren't working for you.

**Comment by Rashi-Sonthalia3** [comment]
[cups_error_log.txt](https://github.com/apple/cups/files/2664244/cups_error_log.txt)
Attaching the log

**Comment by michaelrsweet** [comment]
The log just shows the printer accepting the job data but it doesn't respond with success or failure. There is nothing showing the job processing filters, so there is nothing more we can help you with...

**Comment by Rashi-Sonthalia3** [comment]
Hi Michael,

Thanks for reviewing the logs. Now the cups system is able to send the files but we are getting the error message 'The printer did not respond' at CUPS front end.

Just to add this is USB printer which we are trying to connect to via CUPS 1.63 . below is the configuration for this printer. Could you please verify if the set up is correct ? Thanks a lot for your help !!

![cups](https://user-images.githubusercontent.com/45763367/49788472-6ec00600-fcf7-11e8-8456-fd34e8c99bb4.png)

**Comment by jsmeix** [comment]
@Rashi-Sonthalia3 
FYI
perhaps the following general information might also help:

https://en.opensuse.org/SDB:How_to_Report_a_Printing_Issue
also contains some basic tests to diagnose the cause of a printing issue.

For more profound debugging you may have a look at the section
"A filter that sends its input into a file for debugging" in
https://en.opensuse.org/SDB:Using_Your_Own_Filters_to_Print_with_CUPS
and the section
"A backend that sends its input into a file for debugging" in
https://en.opensuse.org/SDB:Using_Your_Own_Backends_to_Print_with_CUPS

**Comment by michaelrsweet** [comment]
@Rashi-Sonthalia3 The screenshot does not show a USB connection.
