### ISSUE TITLE
CUPS should be able to use different paper(tray) for job-sheets (support IPP attribute 'job-sheets-col')

### ISSUE THREAD

**Issue by KurtPfeifle** [apple/cups#5459]
CUPS is playing a core role in many educational institutions and other large organisations where thousands of users print their documents on a few dozen "public" printers. In these environments it is very common to enforce *`-o job-sheets=some-custom-postscript`* for each job to be printed on colorized paper so that they serve as separator sheets, with the actual job-sheet containing PostScript code to do the magic of tray switching (*`setpagedevice`*) as well as code to fill its page contents with *`time-at-processing`*, *`job-originating-user-name`* and what-not variable values.

To be honest, this method has always been a mild "hack", only necessitated because CUPS did never have a "canonical" support to pick a different tray for job-sheets.

By default, "legacy" CUPS always printed job-sheets on the same paper as the main job documents. The lack of direct support for banner pages from a different tray has always been one of the biggest deficiencies of CUPS -- and it was easily overcome by many organizations in need of it through their usage of custom PostScript "hacks".

But this situation has worsened now: When using the "new" job-sheet format (*`application/vnd.cups-banner`*), where the job-sheet is supposed to be dynamically created as a PDF for each job by a *`x-bannertopdf`* filter there is no means any more to get banners printed on different media as compared to the main job.

It is time to fill the gap. Else PostScript job-sheets will still be the holdout and prevent a full-scale PDF workflow.

It looks like IPP (but only the IPP extension for "production printing" purposes) already provides an appropriate job attribute for what's needed: **`job-sheets-col`**.

However, CUPS does not support this yet. It should, soon!

**Comment by mschee** [comment]
Yes, this is would be an important and valuable feature for CUPS!
Colored _separator sheets_ that are deposited in a special paper tray are especially important when using CUPS for a large number of daily print jobs from different users like in educational institutions.
It considerably simplifies and  accelerates the process of sorting the print jobs.
Thumbs up for this feature.

**Comment by michaelrsweet** [comment]
Considering for a future release.

**Comment by michaelrsweet** [comment]
Now tracking this over in OpenPrinting CUPS as [issue #138](https://github.com/OpenPrinting/cups/issues/138).
