### ISSUE TITLE
Extend CUPS banner format (application/vnd.cups-banner) to allow background/foreground PDF template

### ISSUE THREAD

**Issue by KurtPfeifle** [apple/cups#5460]
The current [*`application/vnd.cups-banner`* file format specification](https://www.cups.org/doc/spec-banner.html) does not allow for much customization by users. 

It consists of lines with initial keywords *Header*, *Footer*, *Show*, *Notice* and *Image* with additional values or variables to describe elements which should appear on the printed banner page.

I as well as at least some other users would like to extend that format by at least one keyword: ***Background***, which should indicate a "template" PDF to be used as the background for the complete page, onto which the other elements of the banner would then be "stamped"...

If it is not too much of an effort the same could be done for keyword *Foreground* (which would point to a foreground PDF that would be overlayed on top of the other content).

This functions should be similar to what the command line tool `pdftk` would achieve by running *`pdftk original-banner.pdf background banner-background.pdf output new-banner.pdf`*

----

<sub>(Of course, the various *x-bannertopdf* filters, CUPS' own as well as third-party ones, also need to be extended so they understand this new keyword [or simply ignore it if they don't know what it means]).</sub>

**Comment by michaelrsweet** [comment]
I don't see us extending the format at this point, but will hold for possible future use...

**Comment by michaelrsweet** [comment]
Sorry, we've done a review of pending issues and decided not to support this.
