### ISSUE TITLE
Limit for log files

### ISSUE THREAD

**Issue by mat646** [apple/cups#5462]
Due to some unknown reason CUPS daemon created a 4,5 GB log file on my linux root partition (leaving 0kB of unused space) and breaking my workstation (system couldn't reboot due to not enough space for process descriptors I guess) (using kubuntu 18.04). 

Having removed some programs with usb bootable ubuntu from "/" partition  I could boot my system again (not knowing the reason of the issue yet). 
Then after start-up, monitoring the processes and disc usage I realised an ongoing 'cupsd' process is writing constantly to log file. And again just after few minutes my root partition ran out of free space!
Repeated inspection with usb ubuntu image showed the reason was 4,5 GB 'cupsd' log file. 
I hadn't used printer for a long time I have no idea what could be the reason.
In attachment I attached some images. I apologise for attaching pictures instead of print-screens but I was not able to take any in recovery mode.

As mentioned I have no clue what was the reason, I would like only suggest to introduce some limit for log files? Or Is it system's job to manage log files limits? Also I would be thankful for some piece of information on how it works for my better understanding. 

https://i.ibb.co/mbqN0LJ/1.jpg
https://i.ibb.co/Kj6KKzr/2.jpg
https://i.ibb.co/YB43jm2/3.jpg

**Comment by michaelrsweet** [comment]
The MaxLogSize directive controls the size of log files. The default is 1mb...

Not knowing which Linux distro you are using, it is possible that they have changed the defaults in order to use their own log rotation infrastructure...
