### ISSUE TITLE
reminder me input the userid and password frequncely

### ISSUE THREAD

**Issue by im2058** [apple/cups#5464]
i use raspberrypi as a server, after i **sudo apt-get install cups**  and  **sudo usermod -a -G lpadmin pi**  then i use chronim to logon localhost:631 and i can get the homepage.
The problem is : 
when i click the **add printer** button , it remind me to input the usrid and password. i input pi and raspberry(the initial pasword) but it popped up the window all the time. and i can't add a printer!
pls help me.   (and i have also use my windows-googlechrom to login 192.168.0.3:631,i can reach the homepage but can't add printer)

the cups version is as below
as the version is as below.
pi@raspberrypi:~ $ **apt-cache show cups**
Package: cups
Version: 2.2.1-8+deb9u2
Architecture: armhf
Maintainer: Debian Printing Team <debian-printing@lists.debian.org>
Installed-Size: 720

**Comment by michaelrsweet** [comment]
Please report this problem to the debian printing team...
