### ISSUE TITLE
PDF print very slow

### ISSUE THREAD

**Issue by lbricchi** [apple/cups#5465]
Hello, 
we have a server Linux with Centos 7 with:
  Static hostname: localhost.localdomain
  con name: computer-desktop
  Chassis: desktop
  Machine ID: cf80fa656ac04e5d87b4f73ed333e575
  Boot ID: 63809566b5dc41a58a8eb3bb53fd9381
  Operating System: CentOS Linux 7 (Core)
  CPE OS Name: cpe:/o:centos:centos:7
  Kernel: Linux 3.10.0-862.14.4.el7.x86_64
  Architecture: x86-64

and Cups version is 1.6.3.

We use a java application, running on the server linux, to create the pdf and print it. From the logs we can see that the pdf is generated immediately, while to start the print, through cups, it takes a few minutes. The more pages that need to be printed the more time it takes to get the print started.

If the same java application run on a server Windows or on a server linux(Linux version 2.6.31.5-127.fc12.i686.PAE (mockbuild@x86-3.fedora.phx.redhat.com)) with another version of cups (1.4.3), the print is almost immediate.

I attach the error_log from our server linux with Centos 7 where you will notice that there are these lines that are repeated n times:

D [21/Dec/2018:11:08:41 +0100] [Job 10] ATTR: marker-levels=24,-1
D [21/Dec/2018:11:08:41 +0100] cupsdMarkDirty(P----)
D [21/Dec/2018:11:08:41 +0100] cupsdSetBusyState: newbusy="Dirty files", busy="Dirty files"
D [21/Dec/2018:11:08:41 +0100] [Job 10] new_supply_state=0, change_state=0
D [21/Dec/2018:11:08:41 +0100] cupsdMarkDirty(----S)
D [21/Dec/2018:11:08:41 +0100] cupsdSetBusyState: newbusy="Dirty files", busy="Dirty files"
D [21/Dec/2018:11:08:41 +0100] [Notifier] state=3
D [21/Dec/2018:11:08:41 +0100] [Notifier] PrinterStateChanged
D [21/Dec/2018:11:08:41 +0100] [Client 11] POST /admin/ HTTP/1.1
D [21/Dec/2018:11:08:41 +0100] cupsdSetBusyState: newbusy="Active clients and dirty files", busy="Dirty files"
D [21/Dec/2018:11:08:41 +0100] [Client 11] No authentication data provided.
D [21/Dec/2018:11:08:41 +0100] [Client 11] 1.1 Get-Printer-Attributes 38584
D [21/Dec/2018:11:08:41 +0100] Get-Printer-Attributes ipp://utf-8@localhost:631/printers/test
D [21/Dec/2018:11:08:41 +0100] Returning IPP successful-ok for Get-Printer-Attributes (ipp://utf-8@localhost:631/printers/test) from localhost
D [21/Dec/2018:11:08:41 +0100] cupsdSetBusyState: newbusy="Dirty files", busy="Active clients and dirty files"
D [21/Dec/2018:11:08:41 +0100] [Client 11] POST / HTTP/1.1
D [21/Dec/2018:11:08:41 +0100] cupsdSetBusyState: newbusy="Active clients and dirty files", busy="Dirty files"
D [21/Dec/2018:11:08:41 +0100] [Client 11] No authentication data provided.
D [21/Dec/2018:11:08:41 +0100] [Client 11] 1.1 Get-Jobs 38585
D [21/Dec/2018:11:08:41 +0100] Get-Jobs ipp://utf-8@localhost:631/printers/
D [21/Dec/2018:11:08:41 +0100] Returning IPP successful-ok for Get-Jobs (ipp://utf-8@localhost:631/printers/) from localhost
D [21/Dec/2018:11:08:41 +0100] cupsdSetBusyState: newbusy="Dirty files", busy="Active clients and dirty files"
D [21/Dec/2018:11:08:41 +0100] [Client 11] POST /admin/ HTTP/1.1
D [21/Dec/2018:11:08:41 +0100] cupsdSetBusyState: newbusy="Active clients and dirty files", busy="Dirty files"
D [21/Dec/2018:11:08:41 +0100] [Client 11] No authentication data provided.
D [21/Dec/2018:11:08:41 +0100] [Client 11] 1.1 Get-Printer-Attributes 38586
D [21/Dec/2018:11:08:41 +0100] Get-Printer-Attributes ipp://utf-8@localhost:631/printers/test
D [21/Dec/2018:11:08:41 +0100] Returning IPP successful-ok for Get-Printer-Attributes (ipp://utf-8@localhost:631/printers/test) from localhost
D [21/Dec/2018:11:08:41 +0100] cupsdSetBusyState: newbusy="Dirty files", busy="Active clients and dirty files"
D [21/Dec/2018:11:08:41 +0100] [Job 10] new_state=0, change_state=0

After the umpteenth time finally starts the print, but it always takes at least a minute and a half.

We can not figure out whether it is a configuration problem or a problem with the cups version, since without cups (on Windows) or previous versions of cups, the problem is not addressed. 
Could You help us?

Thank you

[error_log.txt](https://github.com/apple/cups/files/2702972/error_log.txt)

**Comment by michaelrsweet** [comment]
This is probably a difference in the PDF filters on the two Linux distros, which are part of the cups-filters project, *not* CUPS.
