### ISSUE TITLE
Create a backend for cups

### ISSUE THREAD

**Issue by GreatBahram** [apple/cups#5466]
Hi,
I want to create a backend in order to emulate a printer for users, and when my backend get the print do some process on the input and change then send it out to cloud to my print server.
* My question is is there any tutorial or document about this topic?
* What PPD file should I use?
* Should I send the print file and its options to my clould's printer or just the file?
* What's the purpose of PPD file?

**Comment by debiantriage** [comment]
A search on Tea4CUPS might answer all your questions.

-- 
Brian.

**Comment by michaelrsweet** [comment]
@GreatBahram The best path is to implement an IPP Everywhere service in your cloud environment, which will allow any CUPS/iOS client to use your service and will allow your service to continue working once printer drivers are no longer supported (which is happening in a few years).

Please check out the IPP resources here: https://www.pwg.org/ipp

If you are determined to create a printer driver (that's what your request amounts to), please see the developer documentation on the CUPS web site: https://www.cups.org/documentation.html

**Comment by jsmeix** [comment]
@GreatBahram only FYI:

If you prefer some quick and simple backend
(i.e. bash script) you may have a look at
https://en.opensuse.org/SDB:Using_Your_Own_Backends_to_Print_with_CUPS

Regarding "What's the purpose of PPD file" you may have a look
at the section "What is a PPD file and how does it work" in
https://en.opensuse.org/SDB:CUPS_in_a_Nutshell

Regarding "Deprecate printer drivers" see
https://github.com/apple/cups/issues/5270
