### ISSUE TITLE
cant print from windows 10 for canon ip4500

### ISSUE THREAD

**Issue by elschman** [apple/cups#5467]
I tried to convince windows by lpr und by direct network printer but without success..
Any proposal is welcome

the error.log is attached

**Comment by michaelrsweet** [comment]
Most Canon printers depend on bidirectional communications, so this is unlikely to work.

**Comment by elschman** [comment]
Quite fast closed... To fast ?
Its Wirkung properly from Windows 7 but not Windows 10!
