### ISSUE TITLE
I want to know the previous CUPS versions on macOS

### ISSUE THREAD

**Issue by nomore12** [apple/cups#5468]
I am developing a printer control program for Mac os using cups. There is one requirement of customer to develop. It should also be possible to control the old Mac OS. I know Mojave's cups version is 2.2.9. However, I do not know the previous version of cups version. Could you tell me the cups version of Mavericks, Yosemite, El Capitan, Sierra, and High Sierra?

**Comment by michaelrsweet** [comment]
The version varies based on the software update that are installed. Generally, however:

- Mojave and High Sierra: CUPS 2.2.x
- Sierra: CUPS 2.1.x
- El Capitan: CUPS 2.0.x
- Yosemite: CUPS 1.7.x
- Mavericks: CUPS 1.6.x

Please note, however, that Apple does not support third-party applications that attempt to configure or control CUPS on macOS...
