### ISSUE TITLE
Add http write buffer for improved performance

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#547]
Version: 1.2-feature
CUPS.org User: jlovell

Adding a small buffer to http writes provides a dramatic performance increase. Before applying the attached patch testspeed reports numbers like:

testspeed(2801): 100 requests in 1.3s (0.013s/r, 74.1r/s)
testspeed: 5x100=500 requests in 1.0s (0.002s/r, 500.0r/s)

After the patch I'm seeing 2 to 3 times the throughput:

testspeed(3519): 100 requests in 0.4s (0.004s/r, 230.7r/s)
testspeed: 5x100=500 requests in 1.0s (0.002s/r, 500.0r/s)

The important part of this to flush the buffer in all the right places; please check to make sure I got them. In particular I didn't try any TLS upgrades.

I'd be curious to know if the results on others systems match MacOSX.

Comments?

Thanks!

**Comment by jgrumboe** [comment]
Hi Michael,

would it be possible to get the http_buffered_write.patch file for download?
I've got an old 1.1.23 installation, updating of this system is PITA, but i would like to apply this patch.

Thx,
Johannes

**Comment by michaelrsweet** [comment]
I've fixed the formatting of the patch, but I'm not sure it will apply cleanly to 1.1.23.

**Comment by jgrumboe** [comment]
Great, thx for your support!
A few line modifications and it worked!
