### ISSUE TITLE
how to email alert any tutorial?

### ISSUE THREAD

**Issue by YaPaY** [apple/cups#5476]
I found a webpage which explain the cups email notficition but if a change the subscription.conf according to the tutorial the file changing itself own after cups restart. I couldn't find any information about this. How can I add my mail and get notification instantly a job printed or server stopped, etc?

**Comment by michaelrsweet** [comment]
NEVER directly edit the subscriptions.conf file unless cupsd is not running, and even then you need to be very careful.

Subscriptions can be added from the command-line when printing using the "-m" option. For other conditions you'll need to use ipptool to create the subscription, for example the /usr/share/cups/ipptool/create-printer-subscription.test file will send notifications when the printer state or configuration changes:

```
ipptool -drecipient=mailto:user@example.com ipp://localhost/admin create-printer-subscription.test
```

You can copy the file to change the list of events, for example the following will send you an email when a job is printed or a printer stops:

```
ATTR keyword notify-events printer-stopped,job-completed
```
