### ISSUE TITLE
Remove ".in" from header.tmpl.in

### ISSUE THREAD

**Issue by scootergrisen** [apple/cups#5487]
Should templates/header.tmpl.in be templates/header.tmpl without ".in"?

The trailer.tmpl file name does not contain ".in".

If the ".in" is removed then also fix file names inside the subfolders with translations.

**Comment by michaelrsweet** [comment]
The header.tmpl file is generated from header.tmpl.in at build time - @CUPS_VERSION@ (among other strings) gets inserted automatically.
