### ISSUE TITLE
doc/index.html.in does not use header.tmpl.in and trailer.tmpl

### ISSUE THREAD

**Issue by scootergrisen** [apple/cups#5488]
I notice the templates folder contains header.tmpl.in and trailer.tmpl which i guess is reused by the other .tmpl files.

But in the doc/index.html.in file (and subfolders with translations) the same text is inside the file and does not seem to be taken from the template files.

I suggest that the header and trailer is always taken from the same place (header.tmpl.in and trailer.tmpl) so they are always the same.

**Comment by michaelrsweet** [comment]
That's not how the CUPS web interface is setup. The home page is static (so you can always see it) but the rest is dynamically generated by CGI programs which use the header/trailer.tmpl files.

So while we do have some duplication between the three files, we won't be changing that now - as it is the web interface is on life support.
