### ISSUE TITLE
General update of translation page

### ISSUE THREAD

**Issue by scootergrisen** [apple/cups#5497]
https://www.cups.org/doc/translation.html says:

    After you have translated all of the templates, add the locale to the LANGUAGES variable in the Makedefs file

But https://github.com/apple/cups/blob/master/Makedefs.in#L78 says:

    LANGUAGES = @LANGUAGES@

So maybe that text does not apply anymore and should be deleted if it is not necessary for the translators to add a locale to LANGUAGES.

**Comment by michaelrsweet** [comment]
@scootergrisen So the "LANGUAGES" value in Makedefs gets set by the configure script, which looks for localizations and (by default) tries to install all that exist. If you are just testing things out you can edit the Makedefs file (not Makedefs.in) to affect the currently configured sources.

As for changing www.cups.org to Software, I'd rather not. The location of the sources has changed over the years and the best place to grab the current sources is from the CUPS home page (www.cups.org). I can add a mention of the Github repository, but again we have a link on the home page and *that* has also changed over the years...

I will keep this bug open to track updates to the translation page, including Issue #5498.

**Comment by michaelrsweet** [comment]
Also tracking changes from issue #5496.

**Comment by michaelrsweet** [comment]
Hopefully this update addresses all of your concerns...

[master 2cb772b87] Update the translation guide to reflect current links, files, etc. (Issue #5497)
