### ISSUE TITLE
How to translate Conditional Tests in templates

### ISSUE THREAD

**Issue by scootergrisen** [apple/cups#5498]
I just translated the files in /templates/da/ but i am unsure if i translated all the Conditional Tests correctly as mentioned on https://www.cups.org/doc/translation.html:

    {variable?true:false}
    {variable=value?true:false}
    {variable!value?true:false}
    {variable<value?true:false}
    {variable>value?true:false}

Example:

    <A HREF="/{is_class?classes:printers}/{job_printer_name}">{job_printer_name}</A>.</P>

Seems "classes" and "printers" are used for folder names so i am unsure if i have to translate it.

Should "true" and "false" always be translated?

Are there some code that checks it so i can see if i made a mistake or not?

**Comment by michaelrsweet** [comment]
Will track this change in issue #5497.

**Comment by scootergrisen** [comment]
One example from templates\ru\job-moved.tmpl:

    <A HREF="/{is_class?группы:принтеры}/{job_printer_name}">{job_printer_name}</A>
