### ISSUE TITLE
Untranslated string in japanese translations

### ISSUE THREAD

**Issue by scootergrisen** [apple/cups#5502]
This is for any japanese translator that might want to translate it.

I noticed the following string is not translated:

    CUPS and the CUPS logo are trademarks of <a href="http://www.apple.com">Apple Inc.</a> Copyright &copy; 2007-2018 Apple Inc. All rights reserved.

Can be found in both these files:
https://github.com/apple/cups/blob/master/templates/ja/trailer.tmpl
https://github.com/apple/cups/blob/master/doc/ja/index.html.in#L52

**Comment by michaelrsweet** [comment]
@scootergrisen Thank you for filing this bug, but generally we do not track specific localization tasks in the CUPS issues as we have no dedicated translators on the project...
