### ISSUE TITLE
CUPS is failing to interpret the Job name if the same is in DBCS chars.

### ISSUE THREAD

**Issue by AveekBasu** [apple/cups#5505]
The problem is if we print a document having name in DBCS characters (like 你好.txt) then the @PJL SET JOBNAME value coming in prn file is a garbage. 

The PJLs are getting set by the custom filters. The filters are mentioned in the PPD file with mime type and CUPS itself calls the filters according to the mime type with few arguments. 

The job name is within the arguments sent by CUPS to the filter. To crosscheck the issue, I printed the arguments from the filter and checked that the job name is a garbage value there also.

Impact: When someone submits a job having the file name in DBCS chars, the job name that is getting displayed in the Printer Panel is a Junk Character.

![junkchars injob name](https://user-images.githubusercontent.com/43844537/52053055-4679b880-257e-11e9-8053-d441b3c56984.png)

![junkchars in log](https://user-images.githubusercontent.com/43844537/52053063-4e395d00-257e-11e9-80ec-e997e0923af0.png)

Regards,
Aveek

**Comment by michaelrsweet** [comment]
We'll need to see what is getting sent to CUPS (so attach one of the "c" files in the spool directory if you can), but this looks like the string being sent to CUPS is *not* UTF-8...

**Comment by michaelrsweet** [comment]
OK, I've confirmed that the job-name in c00002 is, in fact, valid UTF-8. So this looks like a driver bug.
