### ISSUE TITLE
Thin vertical white lines when printing from Mojave / CUPS 2.2.9

### ISSUE THREAD

**Issue by mikaeylinen** [apple/cups#5508]
I have an issue where printed sheets get thin vertical white lines scattered over them when printed on Mojave / CUPS 2.2.9 (see the attached photo). If printed using High Sierra / CUPS 2.2.5 the problem disappears.

![white_lines_highlighted](https://user-images.githubusercontent.com/34382995/52271867-95906680-294d-11e9-8eb3-b9a368984921.jpg)

I first tried this on a Mac mini 2014 with clean installed Mojave, and the stripes appeared, then downgraded to High Sierra on the same machine, and the problem disappeared. Also tried this on a brand new Mac mini 2018 with Mojave, and the problem reappeared.

All tests have been using the same Canon CUPS driver (files submitted using IPP to the CUPS server):
[Canon PRO-4000S v. 18.10.2.0 CUPS driver](https://www.canon-europe.com/support/products/imageprograf/imageprograf-pro-4000s.aspx?type=drivers)

We have 15 identical Canon iPF PRO-4000 large format printers and they all show these lines.

Any ideas where to look for a solution to this?

**Comment by mikaeylinen** [comment]
Lines highlighted in this version:

![white_lines_highlighted](https://user-images.githubusercontent.com/34382995/52271776-54985200-294d-11e9-840c-b86ba11df9a8.jpg)

**Comment by michaelrsweet** [comment]
Sorry, since a printer driver is involved it could be something as simple as an incompatibility with a system library - have you contacted Canon for support?
