### ISSUE TITLE
Device URI containing workgroup not sanitized

### ISSUE THREAD

**Issue by JakobStruye** [apple/cups#5510]
Some configurations require a device URI of the form
smb://workgroup/username:password@hostname/printername

(https://wiki.archlinux.org/index.php/CUPS/Printer_sharing#Permission_errors_on_Windows)

The URI sanitizer intended to remove the password from the URI only checks between "scheme://" and the next forward slash, so the workgroup in this case. It misses the actual password, making it plainly visible without requiring root access.

The sanitizer should probably also detect and remove the password for this format.

Sanitizer code: https://github.com/apple/cups/blob/e625fa13200089ccca1a48a94deb8b00f4ed8591/scheduler/printers.c#L1947-L1983

**Comment by michaelrsweet** [comment]
@JakobStruye The SMB URI scheme isn't well-defined, but following the guidance in [STD 66](https://tools.ietf.org/html/std66) and the provisional reservation with IANA we believe the expected separator between the workgroup/domain name and user credentials is ";" and *not* "/'. From <https://www.iana.org/assignments/uri-schemes/prov/smb>:

```
Scheme syntax:
   smb://[<user>@]<host>[:<port>][/[<path>]][?<param1>=<value1>[;<param2>=<value2>]] or 
   smb://[<user>@]<workgroup>[:<port>][/] or
   smb://[[<domain>;]<username>[:<password>]@]<server>[:<port>][/[<share>[/[<path>]]][?[<param>=<value>[<param2>=<value2>[...]]]]]     
   example: smb://workgroup;user:password@server/share/folder/file.txt
```

Also see <http://ubiqx.org/cifs/Appendix-D.html> which mirrors this advice.

*We do not recommend hardcoding user credentials in URIs*. But we can only sanitize URIs that conform to STD 66, and we have no plans of trying to sanitize custom URI schemes or URIs that do not conform to STD 66.

**Comment by JakobStruye** [comment]
For anyone else running into this: while domain;username:password@server did not allow me to connect, username:password@domain/server did work, and leads to proper sanitization.

**Comment by jsmeix** [comment]
FYI:
`man smbspool` reads (excerpts)
```
smbspool - send a print file to an SMB printer
...
smbspool specifies the destination using
a Uniform Resource Identifier ("URI") with a method
of "smb". This string can take a number of forms:
* smb://server[:port]/printer
* smb://workgroup/server[:port]/printer
* smb://username:password@server[:port]/printer
* smb://username:password@workgroup/server[:port]/printer
```
