### ISSUE TITLE
PPD retrieval issues with MacOS Mojave 10.14.(3?)

### ISSUE THREAD

**Issue by kabassanov** [apple/cups#5511]
Hello,

We actually experience some (random) issues with Apple computers when we try to install printers shared by Bonjour.

Automatic driver selection often fails to "Generic PostScript Printer" instead of the right one, and according to tcpdump  captures, it seems to be related to the presence of a field called "If-Modified-Since" in the get PPD cups request like: 
If-Modified-Since: Fri, 28 Oct 432601864 03:13:58 GMT\r\n

User-Agent: CUPS/2.2.9 (Darwin 18.2.0; x86_64) IPP/2.0\r\n

Sometimes the field is absent in the packet and driver selection succeeds, sometimes (not really sure about this) it succeeds for some particular values of the year… supposing that 432601864  is a year.

Any hint?

Thanks.

**Comment by michaelrsweet** [comment]
Please file a bug report directly with Apple: <https://bugreport.apple.com>

The 432601864 is indeed a year, but it isn't clear to me where it would be getting such a large date/time value.

**Comment by efuss** [comment]
Until Apple fixes the GUI, you can safely ignore these garbage dates in the server because RFC 7231 says the year field in a HTTP-date it of type 4DIGIT.

[This patch](https://github.com/apple/cups/files/3749724/year-4DIGIT.patch.txt) made our clients work again.

**Comment by efuss** [comment]
Since it looks I cannot re-open this issue, I created Pull request #5724 for the work-around.
