### ISSUE TITLE
lpadmin: Unable to create PPD file: No such file or directory - for an Airprint printer

### ISSUE THREAD

**Issue by Motherboard** [apple/cups#5512]
Trying to add a permanent queue for iP7250 (which should work with Airprint)

I am able to print using `lp -d Canon_iP7200_series <file name>`, - and a temporary queue is created for a minute, but ` lpadmin -p ip7200 -v ipp://Canon%20iP7200%20series._ipp._tcp.local/ -E -m everywhere ` (the URI I get from `lpstat -l -e`) fails with `lpadmin: Unable to create PPD file: No such file or directory`.

The same error message occurs when trying the URI I get from `driverless` (ipp://411824000000.local:631/ipp/print). 

Attached is the output from `ipptool -tv ipp://411824000000.local:631/ipp/print get-printer-attributes.test`
[cups-queue-driverless-ip7250.txt](https://github.com/apple/cups/files/2848296/cups-queue-driverless-ip7250.txt)

Why can't I add a permanent queue, but can print and have a temporary one?

**Comment by michaelrsweet** [comment]
@Motherboard What version of CUPS are you using? What operating system?

**Comment by Motherboard** [comment]
CUPS version 2.2.7, OS mint 19.1.

**Comment by Motherboard** [comment]
Do you think [this](https://github.com/OpenPrinting/cups-filters/issues/22) is related?

Here's the output for the modified test from that issue: 
[ipp_attr2.txt](https://github.com/apple/cups/files/2861788/ipp_attr2.txt)

**Comment by michaelrsweet** [comment]
@Motherboard Possibly, there have been many changes to the IPP Everywhere support since CUPS 2.2.7... Can you try using the current stable release of CUPS (2.2.10)?

**Comment by Motherboard** [comment]
Yes, it happens with CUPS 2.2.10 on Ubuntu 19.04 daily.

**Comment by michaelrsweet** [comment]
OK, thank you.

This might be related to Issue #5484, particularly since this vendor's printers don't seem to conform to the rules for requested-attributes (no support for attribute group names, just "all").

**Comment by tillkamppeter** [comment]
There are several users complaining about driverless printing not working with Canonm printers. See also the (here already mentioned earlier) [cups-filters issue #22](https://github.com/OpenPrinting/cups-filters/issues/22). It seems that the Canon cannot cope with the added "media-col-database" attribute. Then the response to the get-printer-attribute requests comes out incomplete. Either there is a firmware bug in the Canon printers or the response gets perhaps somehow too long for the client-side implementation of IPP (libcups in case of both CUPS and cups-filters). So testing with the alternative implementation [ippsample](https://github.com/istopwg/ippsample) is needed.

**Comment by michaelrsweet** [comment]
@tillkamppeter The client-side implementation has no limits on the number of attributes, and any size limits are in the protocol and not in the software. It is far more likely there is a firmware bug, given that their printers don't seem to properly support attribute groups.

I'll see if I can get access to a recent Canon AirPrint printer and do some testing...

**Comment by michaelrsweet** [comment]
OK, I have a printer on the way - won't have it until next Wednesday but I think the issue is the same as #5484. Will confirm next week...

**Comment by Motherboard** [comment]
By the way, CUPS 2.2.10 behaves even worse for me than 2.2.7 - I can no longer see any output for `driverless`, `lpstat -e` only occasionally sees the printer, and `lp -d ` says `lp: No such file or directory
` when trying to print a file using it (which worked fine with the previous version).

**Comment by michaelrsweet** [comment]
I don't think there were any DNS-SD changes between 2.2.7 and 2.2.10, just IPP Everywhere changes, but as soon as I get my printer I'll start testing (on multiple platforms) to make sure we have this nailed down.

**Comment by tillkamppeter** [comment]
In the cups-filters issue #22 a user tried the `ipptool` of PWG's ippsample and runs into the same problem. So it seems that the problem occurs with both libcups and ippsample.

**Comment by michaelrsweet** [comment]
@tillkamppeter If the attributes being reported by ippserver are the same as those returned by the printer (with the incorrect implementation of "requested-attributes"), then it will have the same behavior. Please refrain from drawing conclusions until we have more information...

**Comment by michaelrsweet** [comment]
OK, so I have a Canon PIXMA TS5120 hooked up. It seems to work as expected from CUPS master, without changes. Now testing with older versions of CUPS to see where things break...

**Comment by michaelrsweet** [comment]
2.2.11 (branch-2.2) seems to be working.

**Comment by michaelrsweet** [comment]
2.2.10 seems to be working.

**Comment by michaelrsweet** [comment]
2.2.9 seems to be working.

2.2.8 fails with "requesting-user-name attribute with wrong syntax"

**Comment by michaelrsweet** [comment]
(not sure what is wrong there with 2.2.8, but I'm not duplicating the PPD creation failure...)

**Comment by michaelrsweet** [comment]
2.2.7 seems to be working.

Beginning IPP conformance testing of the printer...

**Comment by michaelrsweet** [comment]
[get-printer-attributes-suite.test.txt](https://github.com/apple/cups/files/2881603/get-printer-attributes-suite.test.txt)

Running this test file with:

    ipptool -tI ipp://hostname/ipp/print get-printer-attributes-suite.test.txt

shows that the implementation is somewhat lacking, but at least "all+media-col-database" works as necessary. So I think the changes we have queued up for CUPS 2.2.11 will yield a working solution for you (and that release should be coming out soon...)

In the meantime, hopefully Ubuntu will push out updates for the older CUPS with the changes from Issue #5484.

**Comment by srd424** [comment]
I've jumped over here from [cups-filter #22](https://github.com/OpenPrinting/cups-filters/issues/22) ..

Running the ipptool from https://github.com/istopwg/ippsample.git with the file you linked earlier against my MG3150 yields: [mg3150.txt](https://github.com/apple/cups/files/2885860/mg3150.txt)

Which I guess means I still have a problem? Or is that OK?

**Comment by michaelrsweet** [comment]
@srd424 That should be OK, with the changes in place we'll still get the attributes we need.

**Comment by Motherboard** [comment]
@michaelrsweet Can you try and get your hands on iP7250? As I've said earlier, I tried to use it with Mint's CUPS (2.2.7) and Ubuntu Disco's CUPS (2.2.10), and I wasn't able to print (unless using the gutenprint drivers). 

While your printer worked both on 2.2.7 and on 2.2.10 - and you had a different error on 2.2.8 - I think it wasn't the same issue.

**Comment by michaelrsweet** [comment]
@Motherboard Sorry, we don't seem to have that model in our labs and it doesn't look like the printer is still available for sale. Please make sure the firmware on the printer is up-to-date, and if the problem persists you'll need to contact Canon for support...

**Comment by atbakken** [comment]
I seem to be having the same issue with a Canon Pixma MX532 as well. This is on Fedora 30 using cups 2.2.11

`ipptool -tv ipp://pixma.local:631/ipp/print get-printer-attributes.test > attribs.txt`

[attribs.txt](https://github.com/apple/cups/files/3433485/attribs.txt)

**Comment by michaelrsweet** [comment]
@atbakken Can you open a new issue for your printer? Also, it would be helpful to see the output with the "get-printer-attributes-2.0.test" file since the non-2.0 file doesn't request media-col-database, and also the PPD file that is created for your queue?
