### ISSUE TITLE
Printing the attached pdf results in a rotated and clipped output

### ISSUE THREAD

**Issue by aselalee** [apple/cups#5514]
Attached zip file [pdf_to_print_and_driver_ppd.zip](https://github.com/apple/cups/files/2857921/pdf_to_print_and_driver_ppd.zip) has two files.
pdl.pdf - Input pdf
GenericPS.ppd - Driver ppd file

Problem:
When printing the attached pdf file the output is rotated and clipped.
Did some investigation and narrowed it down to the PS file generated by CUPS which is sent to the printer.
To reproduce simply run the following command and examine output ps file.
cupsfilter -p GenericPS.ppd -m application/postscript pdl.pdf > pdl-mod.ps

Filter List:
cupsfilter --list-filters -p GenericPS.ppd -m application/postscript pdl.pdf
cgpdftops

Expected Output:
The pdl-mod.ps should look as same as the input pdl.pdf.

Versions:
cups-config --version
2.2.9

Additional Info:
Initially encountered problem when trying to print the pdf using lpr command.
When this pdf is printed on windows, it prints correctly.

**Comment by michaelrsweet** [comment]
@aselalee Looking at this today, but the filter in question is part of macOS so you will likely need to file a bug report via <https://bugreport.apple.com>...

**Comment by michaelrsweet** [comment]
@aselalee OK, I've confirmed this is a macOS software bug - please file a bug on the apple bugreport page instead as we can't track cgpdftops changes here... :(

**Comment by aselalee** [comment]
@michaelrsweet Thanks for the followup. I'll open a bug report with Apple.
