### ISSUE TITLE
IPP printer gets paused after MaxJobTime even though the policy is retry-job

### ISSUE THREAD

**Issue by akorobkin** [apple/cups#5517]
I found that when a job is sent to a printer over IPP, and the printer reports back any kind of an issue (cover open, no toner, jam, etc). the job is held in the queue for the MaxJobTime. 

However, after MaxJobTime not only the job gets cancelled, but the printer itself gets paused as well and never unpaused. It's surprising because server-wide policy is retry-job and printer's own policy is retry-job. 

Here is the printer setup:
```
<Printer blip-color>
UUID urn:uuid:c2ed813e-507b-30b4-7bc6-698a9226378e
AuthInfoRequired none
Info blip-color
MakeModel Ricoh Aficio MP C3004 PS
DeviceURI ipp://blip-color:631/printer
State Idle
StateTime 1550157235
ConfigTime 1549568815
Type 8434172
Accepting Yes
Shared Yes
JobSheets none none
QuotaPeriod 0
PageLimit 0
KLimit 0
OpPolicy default
ErrorPolicy retry-job
</Printer>
```
Attached is a debug log for a Job 72, that was sent on 20:55, got cancelled on 21:55 (because printer cover was open), and the printer itself had become paused. ([error_log_Job_72.txt](https://drive.google.com/file/d/105fkn90rEtY2OEKFcRRraFgUKsTqHyvN/view?usp=sharing))
Also attached cupsd.conf, cups-files.conf, and whole [error_log](https://drive.google.com/file/d/1M6NuT_0bjgs_sRQOmbKCDNUKuWrM8YzV/view?usp=sharing) from 20:55 to 21:55. 

Could this please be looked at? It seems to be an unexpected behaviour of IPP backend for such a setup. 

Relevant feature request: please add a line to the log showing when the printer was paused and why. It exists for manual cupsenable/cupsdisable (Printer "blip-color" started by "admin"), but doesn't seem to exist for internal events like this one.

**Comment by michaelrsweet** [comment]
Investigating; as for logging, such logging already exists when debug logging is enabled and for job errors...

**Comment by akorobkin** [comment]
Thank you. 

If have a moment, could you please point out how the logging message looks in the referenced error_log? The printer had got paused around 21:55, but I couldn't find a relevant line in the debug log that would clearly tell me that it happened.

**Comment by michaelrsweet** [comment]
The log snippet you sent contains the following at the end:

```
D [13/Feb/2019:21:56:40 +0000] [Job 72] PID 56831 (/usr/lib/cups/backend/ipp) stopped with status 4.
I [13/Feb/2019:21:56:40 +0000] [Job 72] Backend returned status 4 (stop printer)
```

Tracing things back it looks like it is returning status 4 because the Create-Job request was interrupted:

```
D [13/Feb/2019:21:56:39 +0000] [Job 72] Create-Job: server-error-internal-error (Interrupted system call)
```

which tells me this printer doesn't implement IPP properly (Create-Job MUST NOT hang like this, Send-Document and Print-Job *might* but at that point we are able to track the progress of the remote job...)

Seems like a) cupsd should ignore the exit status when a job has been canceled and b) the IPP backend should return OK when it gets SIGTERM.

**Comment by michaelrsweet** [comment]
[master 45cae1bc0] Don't stop a printer after a job is canceled/aborted (Issue #5517)

[branch-2.2 3a66aedf8] Don't stop a printer after a job is canceled/aborted (Issue #5517)

**Comment by akorobkin** [comment]
Thank you so much. 
Would be so helpful if there was an additional info line: "Printer blip-color was stopped by IPP backend." or something. "Backend returned status 4 (stop printer)" isn't apparent enough that it was the cause that stopped the printer.

i understand this one is fixed, it's just for any future situations where a backend stops the printer for any other reason.

**Comment by akorobkin** [comment]
I added this patch to my 2.2.8 server and confirmed that it works. Thanks again!

**Comment by UliWehner** [comment]
> The log snippet you sent contains the following at the end:
> 
> ```
> D [13/Feb/2019:21:56:40 +0000] [Job 72] PID 56831 (/usr/lib/cups/backend/ipp) stopped with status 4.
> I [13/Feb/2019:21:56:40 +0000] [Job 72] Backend returned status 4 (stop printer)
> ```
> Tracing things back it looks like it is returning status 4 because the Create-Job request was interrupted:
> 
> ```
> D [13/Feb/2019:21:56:39 +0000] [Job 72] Create-Job: server-error-internal-error (Interrupted system call)
> ```
> which tells me this printer doesn't implement IPP properly (Create-Job MUST NOT hang like this, Send-Document and Print-Job _might_ but at that point we are able to track the progress of the remote job...)
> 
> Seems like a) cupsd should ignore the exit status when a job has been canceled and b) the IPP backend should return OK when it gets SIGTERM.

Mike,

what exactly should happen on the printer side? Cover open can easily be rectified by a user, at which point the job would continue to print. Should it time out?
Should it return a particular status?

I asked Alex to send me a capture that i can share with the developers, but if you have a particular solution in mind, please share it.

regards

Uli

**Comment by michaelrsweet** [comment]
@UliWehner The printer should accept the Create-Job request *or* reject it with server-error-service-unavailable or server-error-busy so that the client retries at a later time. The only time you have the printer pause the data transfer during a print is with the Print-Job and Send-Document requests.

Otherwise, it looks like the printer is correctly returning the cover-open printer-state-reason, so the issue is just that the IPP backend is hung waiting for the printer to respond to the Create-Job request.
