### ISSUE TITLE
3 page test page

### ISSUE THREAD

**Issue by paulmenzel** [apple/cups#5518]
Printing a test page with CUPS 2.2.10 from Debian Sid/unstable for the Canon iR-ADV C2225 PCL, I am surprised that three pages on two sheets were printed. All three pages were supposed the same, I guess.

Is that expected?

Is it documented somewhere, how many test pages are printed on what printer types?

**Comment by michaelrsweet** [comment]
@paulmenzel The cups-filters project is responsible for test pages on Debian. That said, the original filter (that they took over) would produce 1 page for a printer without duplexer and 2 pages for a printer with duplexer.
