### ISSUE TITLE
8-10 Sec delay between jobs DYMO 450 Turbo USB

### ISSUE THREAD

**Issue by aspecteleven** [apple/cups#5521]
I've got a DYMO 450 Turbo hooked up via USB and CUPS on a Raspberry Pi 3 running Ubuntu Mate 16.04.2. It prints immediately for the first print, but has a delay of 8-10 seconds between every job after that. My buddy and I have been searching the internet for over a week trying to find a solution, but haven't found anything that works.

I've tried a suggestion you made to another user of adding the 0xVENDOR 0xMODEL unidir, but that didn't work (0x0922 0x0021 unidir).

Noted from the syslog, it appears the printer disconnects between jobs:
`usblp0: removed`

The driver I have installed is from http://www.dymo.com/en-US/dymo-label-sdk-and-cups-drivers-for-linux-dymo-label-sdk-cups-linux-p--1#

Any suggestions?

**Comment by michaelrsweet** [comment]
Does the same issue happen for the bundled Dymo label printer driver?

You might try using "no-reattach" in the quirks file as well.

**Comment by aspecteleven** [comment]
Ok, so I did a fresh install, updated/upgraded. Installed CUPS, and the DYMO 450 Turbo using the bundled driver (which I didn't know even existed until you mentioned it). That didn't immediately fix it. 

I then tried using "unidir" and this time it worked like a charm!

In summary - Raspberry Pi 3, Ubuntu Mate 16.04.5 LTS, DYMO 450 Turbo, installed DYMO with bundled driver, set quirks file with "0x0922 0x0021 unidir"

Thanks, Michael!

**Comment by michaelrsweet** [comment]
[master 76bb0a3b9] Add a USB quirks rule for the DYMO 450 Turbo (Issue #5521)

[branch-2.2 534af3a30] Add a USB quirks rule for the DYMO 450 Turbo (Issue #5521)

**Comment by codeprofis** [comment]
I have the same problem, or a similar one.
The tips used here do not bring improvement.

When I start a print on a LabelWriter 450 Turbo, it takes about 6-7 seconds until the print starts. The printing itself is then very slow. At the end of printing, the printer pauses for about 1-2 seconds and then advances the last piece of the label.

System is a Raspberry Pi 4 with Raspian - but I have the same problem on a current Ubuntu on my workstation.

Does anyone know about this problem or have an idea where I could tackle this problem?

**Comment by AdrianwithaW** [comment]
> I have the same problem, or a similar one.
> The tips used here do not bring improvement.
> 
> When I start a print on a LabelWriter 450 Turbo, it takes about 6-7 seconds until the print starts. The printing itself is then very slow. At the end of printing, the printer pauses for about 1-2 seconds and then advances the last piece of the label.
> 
> System is a Raspberry Pi 4 with Raspian - but I have the same problem on a current Ubuntu on my workstation.
> 
> Does anyone know about this problem or have an idea where I could tackle this problem?

Did you ever find a solution to the delay @codeprofis? Just set this up and having the same issue!

**Comment by AdrianwithaW** [comment]
> Ok, so I did a fresh install, updated/upgraded. Installed CUPS, and the DYMO 450 Turbo using the bundled driver (which I didn't know even existed until you mentioned it). That didn't immediately fix it.
> 
> I then tried using "unidir" and this time it worked like a charm!
> 
> In summary - Raspberry Pi 3, Ubuntu Mate 16.04.5 LTS, DYMO 450 Turbo, installed DYMO with bundled driver, set quirks file with "0x0922 0x0021 unidir"
> 
> Thanks, Michael!

Hey @aspecteleven, what do you mean when you say you tried using the "unidir". Just set this up and the delay is really annoying!

**Comment by labiloute** [comment]
Hi,

Still experiencing exactly the same issue as @codeprofis describe.
On Debian 10, with bundled driver or official driver.
Tried various changes on the quirks file, unidir, no-reattach, with no success.

Does anybody have solved this one ? Any idea ?
Cheers

**Comment by grintor** [comment]
Same issue here. Looking forward to an answer.

**Comment by kfazz** [comment]
unidir breaks the driver, as it is expecting backchannel data to be able to print. The slowness is caused by all the backchannel reads having a 2.5 second timeout value

**Comment by thinhdd13** [comment]
Hi @aspecteleven, @michaelrsweet 
Could you please help to show how to use bundled driver for dymo labelWriter 450 Turbo?
I also have the same delay issue on Ubuntu 18.04.6
