### ISSUE TITLE
lpadmin add "gutenprint52+usb" printer error

### ISSUE THREAD

**Issue by wendraw** [apple/cups#5522]
My working environment is CUPS 2.2.1-8+deb9u2, raspberrypi 3b+, system version is raspberrypi stretch.

```
$ lpinfo -v | grep usb
direct gutenprint52+usb://Dai+Nippon+Printing/DS-RX1?serial=CY2D83040412&backend=dnpds40
$ /usr/sbin/lpadmin -p DNP-RX1 -E -m DNP-RX1.ppd -v gutenprint52+usb://Dai+Nippon+Printing/DS-RX1?serial=CY2D83040412&backend=dnpds40
[1] 20784
$ lpstat -v
device for Dai_Nippon_Printing_DS-RX1: gutenprint52+usb://Dai+Nippon+Printing/DS-RX1?serial=CY2D83040412&backend=dnpds40
device for DNP-RX1: gutenprint52+usb://Dai+Nippon+Printing/DS-RX1?serial=CY2D83040412
```
Dai_Nippon_Printing_DS-RX1 is add on the web, It can work. But DNP-RX1 can't work, Because its "device url" is not complate.

So, What should i do now?

**Comment by michaelrsweet** [comment]
Please contact the Gutenprint developers - this backend is not maintained by the CUPS project...
