### ISSUE TITLE
TLS connection fails with untrusted certificate

### ISSUE THREAD

**Issue by zdohnal** [apple/cups#5525]
Hi!
I was checking CUPS TLS connectivity with gnutls-cli command like:

# gnutls-cli -d 1 localhost -p 631

with cups-2.2.10, but it ends with error:

- Status: The certificate is NOT trusted. The certificate issuer is unknown. The name in the certificate does not match the expected.
*** PKI verification of server certificate failed...
*** Fatal error: Error in the certificate.

I have full gnutls log 
[gnutls_debug_output.txt](https://github.com/apple/cups/files/2880911/gnutls_debug_output.txt) and cups logs 
[cups_log.txt](https://github.com/apple/cups/files/2880947/cups_log.txt) . I tried it with cups-2.2.7 in Ubuntu, with same results.
I found three commits which could be connected to the issue - ff82ce17bf30 af62b316e7e1800e0 e625fa13200089ccca1 , but none of them fixed the issue.
Is it expected behavior or my misconfiguration? Or it is a bug? When I try it in RHEL 7 with cups-1.6.3, it worked correctly.

**Comment by michaelrsweet** [comment]
This is a recent GNU TLS change that breaks things. Issue #5506 has the fix.

**Comment by michaelrsweet** [comment]
I take it back, even with the fix I'm seeing the same issue, it might be something to do with localhost vs. hostname. Or it could just be because the certificate is self-signed.

**Comment by michaelrsweet** [comment]
OK, when I look at the certificate that is generated, the common name is set to the hostname and localhost isn't included in the Subject Alt Name list.

**Comment by michaelrsweet** [comment]
OK, I've pushed changes to correctly populate the subject alternate names portion of the certificate.

gnutls-cli will still not validate the certificates because they are self-signed, but they no longer complain about the mismatch of hostname for the cert...

[master 1df7a4615] Add subject alternate names for self-signed certificates (Issue #5525)

[branch-2.2 f7d8c89ec] Add subject alternate names for self-signed certificates (Issue #5525)

**Comment by michaelrsweet** [comment]
Use the "--tofu" option to gnutls-cli to handle trusting the self-signed certificate...

**Comment by zdohnal** [comment]
Thank you for the quick fix and the tip!
