### ISSUE TITLE
Pause printing for selected days and time.

### ISSUE THREAD

**Issue by dbashyal** [apple/cups#5526]
Hi,

Is it possible to hold printing new jobs from Friday 6pm to Monday 6am?

https://superuser.com/questions/1407635/how-to-hold-release-print-jobs-using-cups

Thank you.
Damu

**Comment by michaelrsweet** [comment]
@dbashyal There isn't a direct way to do it, but you can use the `cupsdisable --hold` and `cupsenable --release` commands with cron at the appropriate times.
