### ISSUE TITLE
Test page printing and restart jobs without auth from everywhere over web.

### ISSUE THREAD

**Issue by BytEvil** [apple/cups#5537]
Hi. Please fix this ability, because it is not quite good. It would be correct to run these tasks with administrators rights only.

CUPS 2.3b7

Thanks in advance!

**Comment by michaelrsweet** [comment]
Um, we need more information, like your cupsd.conf file. Nothing in cups would allow this by default!

**Comment by BytEvil** [comment]
Here is my [cupsd.conf](https://pastebin.com/xmGLg4Mv).

**Comment by michaelrsweet** [comment]
Your policy definition is allowing the Cancel-Job, Restart-Job, Resubmit-Job, and Reprocess-Job operations without any authentication or access control.

(this is not the default policy)

**Comment by BytEvil** [comment]
this is default config from official archlinux repo with my small modifications, ssl etc...

**Comment by BytEvil** [comment]
thanks for reply! ))
