### ISSUE TITLE
cups 2.2.8 and papercut compatibility (Possible CUPS 2.2.8 windows lpd bug?)

### ISSUE THREAD

**Issue by Stoatwblr** [apple/cups#5539]
I've been having some "issues" working with cups 2.2.8 on Linux and Papercut Windows Mobility Client.

Specifically:
The Papercut Windows Mobility Client/Server setup validates a user _once_ (when the printer queue is setup) then never bothers do so so again (ie, takes no notice of password changes or if the user has been disabled). 
The server side of the Papercut software submits to CUPS via LPD to localhost.
 
On Linux RHEL7,  CUPS 2.2.8 "lpd localhost" asks for a password by default - at which point the Papercut software barfs and silently drops the job. 
If CUPS is set to not require authentication then the job prints OK, but user is smashed to "anonymous" and print accounting fails (I'm happy with this. Blocking paths to spoofing is a good thing)

Papercut claim that the Windows version of CUPS 2.2.8 doesn't exhibit the same behaviour, that CUPS shouldn't be asking for passwords, that it's too hard for them to fix their software so that it verifies passwords at least once per session like every other (well-behaved) print client does and that the correct fix is to disable authentication or to use a Windows CUPS server.

I tend to disagree....

I believe that the cause of their misguided behaviour and advice is down to CUPS 2.2.8 LPD on windows accepting unauthenticated jobs without smashing them down to "anonymous" .

Would the devs mind looking into this and see what the defaults are and fixing it if need be?

(Of course, if there actually WAS a properly decent IPP interface for windows, a lot of these outfits would be out of business, but that's another issue.)

**Comment by Stoatwblr** [comment]
(WRT the comment about an IPP interface - it may not be common knowledge yet, but MS have stated that the Samba print interface is going away in 2019, so a MS Windows IPP printer GUI is about to become a critical issue for many people)

**Comment by michaelrsweet** [comment]
@Stoatwblr The default for printer sharing is not authenticated - you have to choose the policy. Since LPD does not support authentication at all, enabling authentication effectively disables (incoming) LPD print jobs.

I'm not aware of a CUPS package for Windows that offers LPD support. Certainly Windows has/had an LPD listener service to support legacy clients, but AFAIK it isn't widely used.

Do you have any public references/URLs on MS dropping SMB printing? That would be a surprise to me given that CIFS has been a central part of Windows networking...

**Comment by michaelrsweet** [comment]
@Stoatwblr Ping...

**Comment by Stoatwblr** [comment]
Sorry, illness getting in the way.

Yes, CIFS _has_ been a central part of MS networking and appears to be being retained for filehandling but my interpretation of the report is that print shares will be phased out - and more importantly the handing off of print drivers via CIFS will be removed earlier than that, which will cripple print-via-samba  even if print shares are retained as being unable to manage printer drivers will result in network chaos on any medium sized network.

(CIFS hs a lot of issues WRT mixed environments performance and compatibility-wise anyway. Whilst not an issue for printing it's not uncommon to find that file latencies are in the order of a few milliseconds via samba when the underlaying disks are shared via other means, due to the need to avoid lock/write contention. This may not sound like much but it translates to complaints of Samba file shares being 1/3 the speed (Linux and BSD servers) of native NT ones, and opening directories with hundreds-to-thousands of files being a major performance hit (likewise opening 2500 16kB files - almost instant on local disk, a few seconds when on a NT fileserver, yet can take 5 minutes when on a *nix fileserver nfs exporting over 10GB/s to a samba server re-exporting to windows clients thanks to uncacheable lock checks)

I will have to dig the MS report up, but what's clear is that MS seem to be determined to remove a lot of the legacy networking protocols. Please give me a day or so.

As you should be aware, network browsing (groups/neighbourhoods) was disabled in Win10 a few months back. One of the reasons for needing Papercut is the issue that whilst CUPS provides mDNS (multicast) support for unrouted networks, similar support for DNSSD (service discovery) isn't there and that's another critical need in complex routed networks - yes you _can_ set DNSSD up statically on a BIND server, but that means if a CUPS server or queue goes down, things can start breaking.

DNSSD is (of course) critical for both OSX and WIN10 systems to find printers

Back to the other issues: 

The LPD I'm testing with is your cups-lpd, which on our test RHEL7 environment (cups 2.2.8 local build) either smashes everything to anonymous or requires anthentication enabled. (I'm not overly complaining about this. Whilst Kerberos works to keep the *nixen and SSO systems in line, trusting that supplied IPP userIDs will be accurate on jobs coming from portable systems is "optimistic" at best.)

Papercut are testing with cups on Windows, and a windows-specific LPD (not cups-lpd)

Longer-term there is a crying need for a decent IPP interface on Windows. 

The existing MS IPP interface is beyond user-unfriendly. Commercial alternatives aren't much better - and they're expensive for what they do. Needing to deploy a hefty java-based print management/accounting system primarily to be able to cope with windows users (portables and desktops) which have constant driver updates and subsequently keep "losing" printers is a support nightmare in an academic environment.

Is there any way of implementing a workable CUPS gui client on WIn8/10? (the older OSes are EOL, so no need to bother)

The constant refrain of users is "This works fine at home. Why is it so ********ing broken at work?" and I've heard it in virtually every complex networked environment I've stepped into. "We" (the geeks) are felt to be making things too hard, for no good reason. The result is frequently "guerilla printing" - unauthorised printers deployed in offices over USB connections, with their associated costs and security risks - We've run into a couple which were effectively bridging their host computer onto printer-based Wifi APs as one example (with knock on effects on the wifi network too)

**Comment by michaelrsweet** [comment]
@Stoatwblr Again, current CUPS does *not* run on Windows (you can run ippfind and ipptool and build applications against libcups, but that's it) so I have no idea what Papercut is doing on Windows.

Unfortunately, the current Windows print system is not friendly to CUPS - Win10 can send PWG Raster data now (as an IPP Everywhere client) but Win8 is a lost cause. And PWG Raster isn't the ideal format to be sending to a print server - we'd really want PDF but MS doesn't do PDF...
