### ISSUE TITLE
[Web UI] Unable to add printer because cups_sid_cookie and cups_sid_form are different

### ISSUE THREAD

**Issue by zdohnal** [apple/cups#5542]
Hi!
I found the issue with cups_sid_cookie in cups-2.2.8, which breaks adding a printer through web ui. According the logs 
[cups-log.txt](https://github.com/apple/cups/files/2953773/cups-log.txt) when I click on 'Add printer' in 'Administration' tab, cups_sid_cookie is missing at the first place and when it is generated, it is different from cups_sid_form, which causes loading of main 'admin' page instead of 'add-printer' form. I can get into 'add-printer' form after several clicks, but a printer won 't be successfully installed, because the admin main page is loaded again in most cases...
Ad logs - I added two other debug fprintf()s into the code, so I could see values of cups_sid_cookie and cups_sid_form in the same scope.
I looked into current code, but it doesn't seem to be changed in the relevant places (cgi-bin/var.c, cgi-bin/admin.c), so the problem could be in the master branch too. Would you mind looking into it?

**Comment by michaelrsweet** [comment]
@zdohnal What browser are you using? And what are your cookie settings?

**Comment by zdohnal** [comment]
@michaelrsweet I have firefox-65.0.2 and I have default cookie settings I think... I tried the issue on clear machine and I was not able to reproduce it. It will be probably some garbage in the browser after upgrade. I'll close the issue, if I will be able to give correct steps to reproduce, I'll reopen it.

**Comment by zdohnal** [comment]
It was really some garbage in my browser cookies after upgrade, sorry for the noise.
