### ISSUE TITLE
"job-password" operation attribute doesn't work properly.

### ISSUE THREAD

**Issue by Nikitosh** [apple/cups#5545]
I have Lexmark printer (Lexmark MC2325adw) supporting PIN printing feature. 

When I test it with ipptool, sending "print-job-password.test" to the printer, it adds the job to held jobs and prints it correctly after entering correct PIN.

But when I'm trying to pass "job-password" option in cupsCreateDestJob() CUPS function (together with "copies", "sides" and other options) the printer doesn't add anything to held jobs. The sent value is "1234" (the same as in "print-job-password.test") and the value of "job-password-encryption" is "none".

When I remove "job-password" option back and send my print job only with "copies" and "sides" options everything works fine.

**Comment by michaelrsweet** [comment]
@Nikitosh Please attach the PPD file for the print queue and the device URI being used for the print queue ("lpstat -v" will show you this...)

**Comment by Nikitosh** [comment]
@michaelrsweet 
Thanks for the fast reply!
Device URI is ipp://100.107.70.144:631/ipp/print 
PPD is also attached.
[lexmark.ppd.log](https://github.com/apple/cups/files/2993253/lexmark.ppd.log)

**Comment by Nikitosh** [comment]
@michaelrsweet
Hi, are there any updates on this issue?

**Comment by Nikitosh** [comment]
@michaelrsweet 
I made a bit more investigation. 

It turned out that when we log the received options here https://github.com/apple/cups/blob/master/scheduler/job.c#L920 we have argv[5] (this stands for options) equal to "job-password=0000auto ..." instead of "job-password=0000".
When I'm trying to set job-password equal to "1" I get "job-password=1[<A0>\002auto".
So it seems that job-password attribute overwrites something and that's why it doesn't work correctly.

Do you have any ideas what can cause such behavior? You may point out some suspicious places in code that I can look into deeper.

Thanks!

**Comment by michaelrsweet** [comment]
Looks like a bug in the scheduler - treating octetString values the same as plain text.

**Comment by michaelrsweet** [comment]
Duping this to Issue #5558.
