### ISSUE TITLE
Race condition on boot between cups and sssd

### ISSUE THREAD

**Issue by vtapia** [apple/cups#5550]
When cups has set the "SystemGroup" directive to an external group provided through sss and cups starts before sssd has finished booting, cups will crash because the group does not exist. For instance, with a group named lpadmins@tests.local served from Active Directory through sssd, if the sssd service hasn't booted before cups:

Mar 27 10:10:33 cups-sssd systemd[1]: Started CUPS Scheduler.
Mar 27 10:10:33 cups-sssd systemd[1]: Started CUPS Scheduler.
Mar 27 10:10:33 cups-sssd systemd[1]: Started Make remote CUPS printers available locally.
Mar 27 10:10:33 cups-sssd cupsd[21463]: Unknown SystemGroup "lpadmins@tests.local" on line 19 of /etc/cups/cups-files.conf.
Mar 27 10:10:33 cups-sssd cupsd[21463]: Unable to read "/etc/cups/cups-files.conf" due to errors.
Mar 27 10:10:33 cups-sssd systemd[1]: cups.service: Main process exited, code=exited, status=1/FAILURE
Mar 27 10:10:33 cups-sssd systemd[1]: cups.service: Failed with result 'exit-code'.
Mar 27 10:10:33 cups-sssd systemd[1]: cups.service: Service hold-off time over, scheduling restart.
Mar 27 10:10:33 cups-sssd systemd[1]: cups.service: Scheduled restart job, restart counter is at 2.
Mar 27 10:10:33 cups-sssd systemd[1]: Stopping Make remote CUPS printers available locally...
Mar 27 10:10:33 cups-sssd systemd[1]: Stopped Make remote CUPS printers available locally.
Mar 27 10:10:33 cups-sssd systemd[1]: Stopped CUPS Scheduler.

If sssd is available before cups starts, everything works as expected.

**Comment by vtapia** [comment]
Adding "After=sssd.service" to the [Unit] section in scheduler/org.cups.cupsd.service.in should be enough to fix this issue. I'll prepare a PR with the change.

**Comment by michaelrsweet** [comment]
Closing this issue; will track changes in the referenced pull request instead.
