### ISSUE TITLE
Problem with CUPS USB enumeration mechanism.

### ISSUE THREAD

**Issue by AveekBasu** [apple/cups#5552]
Hi,

We are currently observing an issue with respect to printing over USB for IPP over USB enabled printers.The issue is actually for all the PDF documents and actually it is ultimately not printing at all. 

We have analysed the CUPS logs and found that CUPS is enumerating the USB interfaces and finding IPP alternate interface as Print interface and sending the print job through this interface. Printer is rejecting the job as it is not coming through proper "Print" interface. 

Looks like there might be something going wrong in the CUPS USB enumeration mechanism. Please let me know if you need any supporting logs for the case.

Regards,
Aveek

**Comment by michaelrsweet** [comment]
@AveekBasu Yes, a debug log would be useful.

**Comment by AveekBasu** [comment]
Hi Mike,

PFA the error log file.

OS: Mac 10.14
Cups Version: 2.2.9

Regards,
Aveek
[Cups2_2_9_Mac10_14_ErrorLog.zip](https://github.com/apple/cups/files/3034287/Cups2_2_9_Mac10_14_ErrorLog.zip)

**Comment by michaelrsweet** [comment]
Ok if this issue is on macOS, please file a bug through Apple’s bugreport.apple.com form.
