### ISSUE TITLE
Unpredictable behavior of cupsd 

### ISSUE THREAD

**Issue by artemcarabash** [apple/cups#5554]
I'm testing my implementation of Ipp server on Mac client, and getting very strange behavior.
Environment specs:
Mac Mini, macOS High Sierra Version 10.13.6
CUPS/2.2.5 (Darwin 17.7.0; x86_64) IPP/2.0

Printer is succesfully added after that I send first printjob to the printer, it succeeds.
On printing the second job, some magic happens - printer dissappears from the list, job will fail.

cups access_log shows next message:
localhost - - [03/Apr/2019:16:16:36 +0200] "POST /printers/sss HTTP/1.1" 200 4141 Create-Job client-error-not-found

error_log:
E [03/Apr/2019:16:16:36 +0200] [Job 3] Unable to queue job for destination "ipp://Devs-Mac-mini.local/printers/sss".

system.log:
Apr  3 16:16:36 Devs-Mac-mini cupsd[1991]: cupsd(1991,0x7fffa2b78380) malloc: *** error for object 0x7f80c3c39164: pointer being freed was not allocated
	*** set a breakpoint in malloc_error_break to debug

And the strangest thing that its happens unpredictable. Sometimes everything works just fine, sometimes - crashes. Can you give some advices what can it be?

Best regards,
Artiom

**Comment by michaelrsweet** [comment]
@artemcarabash Can you attach the crash report from your Mac? It will be available in the Console application.

**Comment by artemcarabash** [comment]
Of course, I'm not sure why I can't find the crash report with the same timestamp but just in case here are 2 the closest ones.



[crash_cupsd.zip](https://github.com/apple/cups/files/3040648/crash_cupsd.zip)

**Comment by michaelrsweet** [comment]
@artemcarabash OK, this is a long-standing issue that we haven't been able to duplicate on our end. Can you attach a copy of the files in /etc/cups and /var/spool/cups?

**Comment by artemcarabash** [comment]
@michaelrsweet , I continued testing and noticed a strange pattern. So it's not so unpredictable as I though. The pattern is - if first print job will be sent to the printer in the first 6 minutes after adding the printer, then printer will crash and disappear, otherwise if first print job will be sent at the expiration of 6 minutes ( literally job was sent after 6 minutes 1 second) then everything will work fine. So seems it can be some connection timeout which is set to 6 mins. 
Here are the files right after crash. Printer called aaas.
[Archive.zip](https://github.com/apple/cups/files/3047222/Archive.zip)

**Comment by michaelrsweet** [comment]
OK, so as near as I can tell the most recent changes in CUPS have actually fixed this issue but haven't made it into a macOS release yet.

**Comment by markknopper** [comment]
I am getting this exact crash on macOS Big Sur 11.1 (20C69). 
[cupsd_2020-12-18-212827_Sues-MacBook-Pro.crash.zip](https://github.com/apple/cups/files/5718822/cupsd_2020-12-18-212827_Sues-MacBook-Pro.crash.zip)

**Comment by xxlsuper** [comment]
Hi 
I am getting this exact crash on macOS Big Sur 11.2.1 (20D74). It happens about 50% of the time when printing via Airprint to a Samsung M283DW printer.

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld3 mode
[cupsd_2021-02-17-212044_slawa-mbp.crash.zip](https://github.com/apple/cups/files/5997798/cupsd_2021-02-17-212044_slawa-mbp.crash.zip)

abort() called
cupsd(66396,0x10de88e00) malloc: *** error for object 0x7fb5c1c13224: pointer being freed was not allocated
