### ISSUE TITLE
.travis.yml: The 'sudo' tag is now deprecated in Travis CI

### ISSUE THREAD

**Issue by cclauss** [apple/cups#5563]
[Travis are now recommending removing the __sudo__ tag](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration).

"_If you currently specify __sudo: false__ in your __.travis.yml__, we recommend removing that configuration_"

**Comment by michaelrsweet** [comment]
Since we can't enable Travis CI on the CUPS repository, I've just now removed the file.

[master a3390b63a] Remove Travis CI file since we can't enable it for the CUPS repository.
