### ISSUE TITLE
cups 2.2.11 - web interface internal server error

### ISSUE THREAD

**Issue by mihha** [apple/cups#5565]
Hi,

I have raspberrypi with the default cups 2.2.1 installed. That version has some issues with printing PDF files from Windows 10 machines on which cups printer is installed

Since RaspberryPi OS is Debian Stretch based and there is no way to receive an officially updated cups binaries, I have compiled the latest stable version from source

After that, if I send a PDF file to the printer, it prints perfectly well.

The only issue that I have now is that no matter which page (except the Home page) on the cups web interface I try to access I just receive "Internal Server Error" page and nothing else.

I tried to enable full debugging but I have no idea what to look in the cups error_log

Would really appreciate help to resolve this issue!

Thank you all for your attention and possible help!

Regards,
Igor

**Comment by michaelrsweet** [comment]
Check for authentication errors. You can also attach the error_log here (just add .txt to the filename) and we can look at things.

**Comment by mihha** [comment]
Hi,

thank you very much for offering your help. Please find attached error_log as requested

[error_log.txt](https://github.com/apple/cups/files/3104598/error_log.txt)

I am also attaching cupsd.conf and cups-files.conf files in case you would need them.

[cupsd.conf.txt](https://github.com/apple/cups/files/3104608/cupsd.conf.txt)
[cups-files.conf.txt](https://github.com/apple/cups/files/3104609/cups-files.conf.txt)

I did check error_log for authentication errors but I have to admit that I don't understand them. There are lots of "No authentication data provided" messages, which looks perfectly valid to me since this cups instance should be configured to allow access from everyone without the authentication.

Thank you very much for the help in advace!

**Comment by michaelrsweet** [comment]
The error_log shows that sometime must have updated libcups underneath you:

/usr/lib/cups/cgi-bin/jobs.cgi: symbol lookup error: /usr/lib/cups/cgi-bin/jobs.cgi: undefined symbol: cupsHashString

Try re-installing your local CUPS to get the updated libcups for the version of CUPS you are using.
