### ISSUE TITLE
Total page counts are reported strangely for IPP jobs

### ISSUE THREAD

**Issue by akorobkin** [apple/cups#5571]
When a print job is sent via socket://, CUPS reports printed pages straightforwardly: 
`printer user job# [date] page_number copies ...`

However, when a print job is sent via IPP, in addition to processed pages CUPS reports back intermittent number of pages printed as reported by the printer:
```
printer user job# [date] total 1 ...
printer user job# [date] total 3 ...
printer user job# [date] total 8 ...
```

These numbers are more confusing than helpful in the log. If anything, it should report final "total" number, or not report it at all. This information looks to be more pertaining to the debug log, rather than page log. 

Or maybe there is a configuration option to suppress these totals in the log?

Please change it to report just final total number of pages, or none whatsoever. 
Typical [page log](https://drive.google.com/file/d/1T6DcH-jcJA1GZNNg5BEdhSApchMLMOv-/view?usp=sharing) attached, and [job_log](https://drive.google.com/file/d/10VlkrtJB-Nx186pgSVkT3aTsyuT56qMN/view?usp=sharing) attached.

**Comment by michaelrsweet** [comment]
This change is part of CUPS 2.2.10 and 2.3 (Issue #5439) - we now only log pages when the job is completed.

**Comment by akorobkin** [comment]
Quick question: is it expected that the number of copies is no longer reported in 2.2.11? 
If I print 2 pages with two copies, see "total 4 -" in the log, with 
PageLogFormat being the default ""%p %u %j %T %P %C %{job-billing} %{job-originating-host-name} %{job-name} %{media} %{sides}""

**Comment by michaelrsweet** [comment]
@akorobkin Yes, in order to fix the accounting values we've dropped the per-page reporting in favor of getting accurate totals. You can always add the copies attribute to the PageLogFormat...
