### ISSUE TITLE
why?print only one page per time?

### ISSUE THREAD

**Issue by wicatu** [apple/cups#5572]
I install cups in rasperberry 3B .but hp lj 1020 works poor.
Print only one page per time.
Why?how can i solve it?
Thanks a lot!

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by wicatu** [comment]
Someone say the reason is cups’ cache mem is short.
If it is true ,how can I move the cache from /var/cache/cups to my usb harddisk?

**Comment by michaelrsweet** [comment]
As we do not package or support CUPS on the Raspberry Pi, I'm not sure there is much we can do to help you... :/
