### ISSUE TITLE
Network printer does not authenticates

### ISSUE THREAD

**Issue by dmiranda2** [apple/cups#5573]
I upgraded the cups package to the last version. Printing looks good in the first seconds and it seems as if the dox are sent over the network. Then a dialog window pops up reading "Authentication required for printing document "..."." The dialog contains a field "negotiate" and a checkbox "Remember password". It doesn't matter what I enter into the "negotiate" text box, none seems right, neither the local user's or root's passwd, nor the passwd of the account creds' passwd I'm supplied with. The only option that makes the dialog vanish is Cancel. A look into the printer queue then shows an entry reading "Tree connect failed (NT_STATUS_ACCESS_DENIED)".

A look into /etc/cups/printer.conf tells me that "AuthInfoRequired none" has changed to "AuthInfoRequired negotiate". When I stop cups and the change that entry back to "none", start cups, the same happens again: The dialog pops up and the entry in /etc/cups/printers.conf has been overwritten and reads "AuthInfoRequired negotiate" again.

Steps to reproduce:

-Add samba printer that requires authentication.
-Print a document

**Comment by michaelrsweet** [comment]
What OS? What version of Samba?

**Comment by dmiranda2** [comment]
Arch Linux:
Samba 4.10.2
Cups 2.2.11
--

**Comment by michaelrsweet** [comment]
OK, you'll need to contact the Samba or Arch Linux folks - we don't handle the Kerberos stuff on Linux...

**Comment by simonlui** [comment]
@dmiranda2 Hi, I was having similar issues updating to Fedora 30 with the same cups and samba versions and It seems to be Samba's fault here. From the release notes for the 4.10 release at https://www.samba.org/samba/history/samba-4.10.0.html, there is an interesting snippet included.

> REMOVED FEATURES
> ================
> 
> MIT Kerberos build of the AD DC
> -------------------------------
> 
> While not removed, the MIT Kerberos build of the Samba AD DC is still
> considered experimental.  Because Samba will not issue security
> patches for this configuration, such builds now require the explicit
> configure option: --with-experimental-mit-ad-dc
> 
> For further details see
> https://wiki.samba.org/index.php/Running_a_Samba_AD_DC_with_MIT_Kerberos_KDC

Hope that helps out you and others that may stumble on this issue.
