### ISSUE TITLE
footer is covering submit button

### ISSUE THREAD

**Issue by scootergrisen** [apple/cups#5574]
The footer on localhost:631 uses CSS `position:fixed;` which is annoying because the footer can be on top of e.g. a submit button that is at the bottom of a page.

`<div class="footer">CUPS and the CUPS logo are trademarks of <a href="http://www.apple.com">Apple Inc.</a> Copyright &copy; 2007-2018 Apple Inc. All rights reserved.</div>
`

So if i go to the admin page and click the advanced link and scroll to the bottom of the page i can hardly see the submit button and there is only 4 pixels height area for me to be able to click the button.

![button](https://user-images.githubusercontent.com/1836590/57184240-f8e05500-6eb8-11e9-8955-29124b74a3b4.jpg)

**Comment by michaelrsweet** [comment]
The CSS should be adding a bottom margin to leave space for the footer... Should be an easy fix.

@scootergrisen What browser are you using?

**Comment by michaelrsweet** [comment]
Hmm, OK the issue is the split ("responsive") CSS being used on the admin page (and it only affects the admin page). The padding that normally prevents this from happening is not getting used...

**Comment by michaelrsweet** [comment]
[master 0e17f4c94] Fix CSS on short browsers (Issue #5574)

[branch-2.2 971bdfe04] Fix CSS on short browsers (Issue #5574)
