### ISSUE TITLE
How to debug an issue with backend ipp 

### ISSUE THREAD

**Issue by nycnewman** [apple/cups#5578]
I have a number of users on Mojave 10.14.4 where the printer queue pauses whilst attempting to print to a Xerox printer via ipp. An example error message is:

D [08/May/2019:18:06:08 -0400] [Job 2] final_content_type=\"application/vnd.cups-postscript\", document_format=\"application/octet-stream\"
D [08/May/2019:18:06:08 -0400] [Job 2] Validate-Job IPP/2.0
D [08/May/2019:18:06:08 -0400] [Job 2] printer-uri=\"ipp://10.1.70.2:631/ipp/print\"
D [08/May/2019:18:06:08 -0400] [Job 2] requesting-user-name=\"edwardnewman\"
D [08/May/2019:18:06:08 -0400] [Job 2] job-name=\"Administration - CUPS 2.2.9\"
D [08/May/2019:18:06:08 -0400] [Job 2] document-format=\"application/octet-stream\"
D [08/May/2019:18:06:08 -0400] [Job 2] IPP/2.0 Validate-Job #2
D [08/May/2019:18:06:08 -0400] [Job 2] ---- operation-attributes-tag ----
D [08/May/2019:18:06:08 -0400] [Job 2] attributes-charset charset utf-8
D [08/May/2019:18:06:08 -0400] [Job 2] attributes-natural-language naturalLanguage en-us
D [08/May/2019:18:06:08 -0400] [Job 2] printer-uri uri ipp://10.1.70.2:631/ipp/print
D [08/May/2019:18:06:08 -0400] [Job 2] requesting-user-name nameWithoutLanguage edwardnewman
D [08/May/2019:18:06:08 -0400] [Job 2] job-name nameWithoutLanguage Administration - CUPS 2.2.9
D [08/May/2019:18:06:08 -0400] [Job 2] document-format mimeMediaType application/octet-stream
D [08/May/2019:18:06:08 -0400] [Job 2] ---- end-of-attributes-tag ----
D [08/May/2019:18:06:08 -0400] Discarding unused printer-state-changed event...
D [08/May/2019:18:06:08 -0400] [Job 2] Validate-Job: server-error-internal-error (Undefined error: 0)
D [08/May/2019:18:06:08 -0400] [Job 2] ---- end-of-attributes-tag ----
D [08/May/2019:18:06:08 -0400] [Job 2] PID 29613 (/usr/libexec/cups/backend/ipp) stopped with status 4.
D [08/May/2019:18:06:09 -0400] [Job 2] Wrote 1 pages...
D [08/May/2019:18:06:09 -0400] [Client 2] POST /printers/_10_1_70_2 HTTP/1.1

or the following:
D [08/May/2019:13:41:28 -0400] [Job 18] ---- end-of-attributes-tag ----
D [08/May/2019:13:41:28 -0400] [Job 18] Validate-Job: server-error-internal-error (Undefined error: 0)
D [08/May/2019:13:41:28 -0400] [Job 18] ---- end-of-attributes-tag ----
D [08/May/2019:13:41:28 -0400] [Job 18] PID 23074 (/usr/libexec/cups/backend/ipp) stopped with status 4.
D [08/May/2019:13:41:28 -0400] [Job 18] PID 23073 (/Library/Printers/Xerox/Filters/pstoxrps) did not catch or ignore signal 13.
D [08/May/2019:13:41:28 -0400] [Job 18] Wrote 1 pages...
D [08/May/2019:13:41:28 -0400] [Job 18] PID 23072 (/usr/libexec/cups/filter/pstops) exited with no errors.
D [08/May/2019:13:41:28 -0400] [Job 18] PID 23071 (/usr/libexec/cups/filter/cgpdftops) exited with no errors.
I [08/May/2019:13:41:28 -0400] [Job 18] Backend returned status 4 (stop printer)

I see in the TCP trace that the laptop is connecting to the printer and getting attributes but when it is attempting to send a Validate-Job the connection is terminated by the client side (assume the process failure).

So how can I debug ipp errors as I assume this could be:

- ipp binary (unlikely as other IPP connections work)
- some renderer (challenging as I rried the default PS renderer and Xerox specific without change for one printer and it works with different Xerox driver for another printer)
- some form of data parsing or config issue

Thoughts appreciated.

**Comment by michaelrsweet** [comment]
@nycnewman This is almost certainly a Xerox printer firmware bug - depending on the age of the printer (anything older than about 2013 for Xerox), you may be better off using the socket backend instead, particularly when sending PostScript.

As for debugging the connection issues, grab a copy of Wireshark and record the IPP traffic between your system and the printer. The network trace will show when the connection to the printer goes bad...

**Comment by nycnewman** [comment]
Yes. The Wireshark trace show that the connection to the printer is being reset during Validate-Job communication. So when cups backend ipp fails the network connect is reset. So now trying to figure out how to debug the ipp chain. Looks like the version shipped with Mojave does not include debug symbols (83K vs 100+K that I got from compiling cups library). However not clear if there is a way (config file) to enable more debugging in ipp. Code suggests passing environment parameters but not sure how as this is a backend (pun intended) process.

**Comment by nycnewman** [comment]
Printer is relatively new (Xerox Altalink C8030 with latest drivers). However ipp fails even when Default Postscript driver is selected instead of vendor specific driver.

**Comment by michaelrsweet** [comment]
This printer supports AirPrint, try using that..

Many MFPs in this class do not support PostScript over IPP (🤷‍♂️) but are completely happy getting a PDF file instead over IPP.

**Comment by michaelrsweet** [comment]
@nycnewman Oh, and if you want to send me the wireshark trace (privately if you wish) I can take a look. Having a version of the IPP backend built for debugging won't help too much since the IPP backend is failing *after* the connection is reset.

**Comment by nycnewman** [comment]
Attached is a Wireshark trace of two attempts to send a print job. This was a basic text file in TextEdit with minimal text sent from command line using lp. The associated debug log is also attached with cups in debug mode. My interpretation based on your comments is the following:
- cups is successfully getting details from the printer via SNMP and IPP Get-Printer-Attibutes
- cups then attempts to send to printer via Validate-Job but during rendering of PDF ipp gets a failure - most likely from the Xerox render / filter drivers and exits mid transmission. Thus you see it send the correct packet to printer but then immediately sends a FIN packet to close TCP socket

I have figured out how to enable debugging in CUPS but as yet not clear on how to enable DEBUG fprint in ipp binary. Github source suggests this needs to set as environment variables so do I just need to restart cupsd with those set. The debug fag for cups doesn't appear (from the code) to affect backends and there is no separate config. The Apple binaries in 10.14.4 appear to have the DEBUG strings.

Thanks for your thoughts.

[Archive 2.zip](https://github.com/apple/cups/files/3162239/Archive.2.zip)

**Comment by nycnewman** [comment]
As a test I removed (hopefully) all the Xerox drivers, filters, PPDs, etc and did a connect directly to printer with IPP and Generic Postscript driver. Still seeing issue and same network traffic. Error log showed:
D [09/May/2019:09:15:21 -0400] [Job 13] final_content_type=\"application/vnd.cups-postscript\", document_format=\"application/octet-stream\"
D [09/May/2019:09:15:21 -0400] [Job 13] Validate-Job IPP/2.0
D [09/May/2019:09:15:21 -0400] [Job 13] printer-uri=\"ipp://10.1.70.2:631/ipp/print\"
D [09/May/2019:09:15:21 -0400] [Job 13] requesting-user-name=\"edwardnewman\"
D [09/May/2019:09:15:21 -0400] [Job 13] job-name=\"Administration - CUPS 2.2.9\"
D [09/May/2019:09:15:21 -0400] [Job 13] document-format=\"application/octet-stream\"
D [09/May/2019:09:15:21 -0400] [Job 13] IPP/2.0 Validate-Job #2
D [09/May/2019:09:15:21 -0400] [Job 13] ---- operation-attributes-tag ----
D [09/May/2019:09:15:21 -0400] [Job 13] attributes-charset charset utf-8
D [09/May/2019:09:15:21 -0400] [Job 13] attributes-natural-language naturalLanguage en-us
D [09/May/2019:09:15:21 -0400] [Job 13] printer-uri uri ipp://10.1.70.2:631/ipp/print
D [09/May/2019:09:15:21 -0400] [Job 13] requesting-user-name nameWithoutLanguage edwardnewman
D [09/May/2019:09:15:21 -0400] [Job 13] job-name nameWithoutLanguage Administration - CUPS 2.2.9
D [09/May/2019:09:15:21 -0400] [Job 13] document-format mimeMediaType application/octet-stream
D [09/May/2019:09:15:21 -0400] [Job 13] ---- end-of-attributes-tag ----
D [09/May/2019:09:15:21 -0400] Discarding unused printer-state-changed event...
D [09/May/2019:09:15:21 -0400] [Job 13] Validate-Job: server-error-internal-error (Undefined error: 0)
D [09/May/2019:09:15:21 -0400] [Job 13] ---- end-of-attributes-tag ----
D [09/May/2019:09:15:21 -0400] [Job 13] PID 77310 (/usr/libexec/cups/backend/ipp) stopped with status 4.
D [09/May/2019:09:15:21 -0400] [Job 13] Wrote 1 pages...
D [09/May/2019:09:15:21 -0400] [Job 13] PID 77309 (/usr/libexec/cups/filter/pstops) exited with no errors.
D [09/May/2019:09:15:21 -0400] [Job 13] PID 77308 (/usr/libexec/cups/filter/cgpdftops) exited with no errors.
I [09/May/2019:09:15:21 -0400] [Job 13] Backend returned status 4 (stop printer)
D [09/May/2019:09:15:21 -0400] Discarding unused job-state-changed event...
I [09/May/2019:09:15:21 -0400] [Job 13] Printer stopped due to backend errors; please consult the error_log file for details.
D [09/May/2019:09:15:21 -0400] cupsdMarkDirty(---J-)
D [09/May/2019:09:

So ipp bombing out for some reason that seems unrelated to Xerox drivers. Any possibility that it failing due to config returned from printer?

**Comment by nycnewman** [comment]
Also - tried to enable Airprint but under the covers this IPP protocol so similar failure.

**Comment by michaelrsweet** [comment]
OK, it looks like they don't have keep-alive enabled at the HTTP level (a required part of IPP support), which is causing the subsequent Validate-Job request to fail (CUPS is sending a second request while the printer is closing its connection). Short of you getting a firmware fix from Xerox (and please do pursue that!), your best bet is to configure the print queue with the socket backend instead (socket://10.1.70.2).
