### ISSUE TITLE
Raspbian Login Loop for cups 2.2.1-8+deb9u2

### ISSUE THREAD

**Issue by genifycom** [apple/cups#5579]
Just installed "cups 2.2.1-8+deb9u2" on a Raspberry Pi Model 3B+ using "Linux raspberrypi 4.14.98-v7+"

Cups installs and the GUI runs. I have not changed the user at all. So I added the user pi as in:

sudo usermod -a -G lpadmin pi

and rebooted.

When I attempt to Add Printer, the login box will not accept the username pi and password raspberry. The resulting page indicated Unauthorized.

I see this was reported in 2017 https://www.raspberrypi.org/forums/viewtopic.php?t=197447
but no resolution for the user pi.

I have modified the cupsd.conf file to allow all users on the LAN to access the web interface as per that document.

Is this a known issue and is there a resolution?

**Comment by michaelrsweet** [comment]
I am not aware of any issues but if you enable debug logging ("sudo cupsctl --debug-logging") the /var/log/cups/error_log file *may* provide a pointer to the issue (PAM configuration?)
