### ISSUE TITLE
Printer does not accept user-set options

### ISSUE THREAD

**Issue by christianlupus** [apple/cups#5581]
I have a Brother QL-500 label printer at home. The device can print a bunch of different formats and will only work if the format installed and the one specified in the driver match up.

OK, let's assume we have some formats _A_ and _B_ (e.g. 23x23mm and 29x90). Let format _A_ be installed physically in the printer.
If I set the server default option (via web frontend) and user option (via `lpoptions`) to _A_ the printer is working as expected.
If I change the server defaults in the web frontend (_Administration_ -> _Set Default Options_) to _B_, I would assume the user specified option might be overriding the setting back to _A_. Also some printing applications allow to set the page size. All this is not working, as soon as the server defaults to _B_ the printer refuses to print on _A_.

The only solution is to have a cups printer installed for all possible paper sizes that might be of interest which blows up the number of printers (exponentially).

To be honest I do not know where this problem lies exactly. Is this a CUPS daemon related problem (my personal guess) or due to the PPD file or the source of the print job (aka the user's programs).

I am running Archlinux (up to date) with the bundled cups package. If you need special information, please tell me.

**Comment by michaelrsweet** [comment]
@christianlupus What application are you using to print?

What options are you passing in from the application?

Can you provide a debug CUPS error_log? (run "cupsctl --debug-logging", print something, look in the /var/log/cups/error_log file, assuming that's where ArchLinux puts things...)

FWIW, the default set in the PPD (which is what the web interface changes) is overridden by any user-specified size at print time. The expected behavior is that a single queue can support multiple media sizes, depending on the printer's capabilities, and that users can choose which size to use at print time.

**Comment by christianlupus** [comment]
> @christianlupus What application are you using to print?

I tried with glabels. I also tried with okular as far as I remember but just to be sure that the problem is not purely within glabels. I could of course make a PDF of matching size and see if okular can print and override the server settings if this helps.

> What options are you passing in from the application?

As it is a GTK/QT GUI I do not know how to obtain this information exactly. I tried to set the information both as user defaults using `lpoptions` as well as in the options of the print job within the GUI. 

> Can you provide a debug CUPS error_log? (run "cupsctl --debug-logging", print something, look in the /var/log/cups/error_log file, assuming that's where ArchLinux puts things...)

I will do so but I need to be close to the printer to turn it on. So this might take a few hours until I am at home.

> FWIW, the default set in the PPD (which is what the web interface changes) is overridden by any user-specified size at print time. The expected behavior is that a single queue can support multiple media sizes, depending on the printer's capabilities, and that users can choose which size to use at print time.

This was my intention and assumption as well but I had to aks in case it was a feature and not bug ;-).

**Comment by christianlupus** [comment]
OK, sorry for my late reply. I did the testing and I got an debugging output. As it is quite lengthy, [I put it in a gist](https://gist.github.com/christianlupus/25956a3629fb221177e80bafdfb551f6).

One other thing I am seeing (but I am unsure if this is related at all):
The screenshot of glabels' print dialog shows that I cannot change the page size in it. In the other tabs there is no option to set it as well. Normally it is under "Eigenschaften" (German for properties) in other applications.

![Screenshot_20190518_124730_glabels](https://user-images.githubusercontent.com/8202922/57968461-3342fb00-796b-11e9-9d5b-b2b26f7af499.png)

**Comment by michaelrsweet** [comment]
OK, so there is a bunch of stuff going wrong here.

First, you are doing client-side filtering and sending the raw print data to another CUPS server, which likely won't auto-detect the print format correctly.

Second, I'm seeing some error messages from the Brother driver - not sure what they mean, but I suspect if you just use a local raw queue *or* use the IPP Everywhere driver instead on the client.

**Comment by christianlupus** [comment]
So all in all you are telling me that I should be doing this as in my `QL-500-server` or `QL-500-server-raw` configuration? I can redo the test, the same macroscopic effect does happen. I will provide you with the corresponding logs soon.

**Comment by christianlupus** [comment]
OK, sorry for my late reply, I was a bit ill and could not drive to my parent's home where the issue is located.

I updated the gist to reflect the problematic case's logs. In the newly uploaded logs I use the IPP Everywhere printer driver on the client and the Brother driver on the server.
Maybe you can tell me more, what the problem is.

Thanks a lot
