### ISSUE TITLE
CUPS server error: 'Transport endpoint is not connected'.

### ISSUE THREAD

**Issue by SuffolkPunch** [apple/cups#5582]
I have 2 PCs at home both running Linux Mint 18.3 64-bit Cinnamon.

PC2 has 2 usb local printers, PC1 uses cups to print to PC2. Both PCs had CUPS v 2.1.3-4ubuntu0.7 installed.

After updating cups on both PCs to 2.1.3-4ubuntu0.8, PC1 could no longer print to PC2. Instead, when trying to print a test page on PC2, PC1 popped-up the following errors:
1.  "CUPS server error: There was an error during the CUPS operation: 'Transport endpoint is not connected'."
2. "Raw queue: Unable to get queue details. Treating queue as raw."

As a fix I  used TimeShift to revert back to cups v 2.1.3-4ubuntu0.7 on both PCs. And everything then worked fine.

Is this a known bug?  How do I figure-out what's causing this?

Martin

**Comment by michaelrsweet** [comment]
@SuffolkPunch I don't know what the difference would be between those two packages, but it definitely sounds like a distribution-specific issue. I'd contact the Linux Mint maintainer about the problem...

**Comment by SuffolkPunch** [comment]
Thanks, Michael. I'll try the Ubuntu maintainer of cups.
