### ISSUE TITLE
#5261 broke linking on Debian

### ISSUE THREAD

**Issue by OdyX** [apple/cups#5584]
This change broke linking (at least on Debian):

- https://travis-ci.org/OdyX/cups/builds/533693955
```
/usr/bin/ld: ippeveprinter.o: undefined reference to symbol 'avahi_string_list_add_printf'
```

With a revert of 3e391a8e76dcaf3859de3a90a398d9e4c9e6a6bb, it builds fine:

- https://travis-ci.org/OdyX/cups/builds/533701196

**Comment by OdyX** [comment]
The minimal patch I could find (but which is probably not correct) is:

```
diff --git a/Makedefs.in b/Makedefs.in
index 65ae345bc..62352486f 100644
--- a/Makedefs.in
+++ b/Makedefs.in
@@ -172,7 +172,7 @@ DNSSDLIBS   =       @DNSSDLIBS@
 IPPFIND_BIN    =       @IPPFIND_BIN@
 IPPFIND_MAN    =       @IPPFIND_MAN@
 LDFLAGS                =       @LDFLAGS@
-LINKCUPS       =       @LINKCUPS@
+LINKCUPS       =       @LINKCUPS@ $(DNSSDLIBS) $(COMMONLIBS)
 LINKCUPSSTATIC =       ../cups/$(LIBCUPSSTATIC) $(LIBS)
 LIBS           =       $(LIBGSSAPI) $(DNSSDLIBS) $(SSLLIBS) $(LIBZ) $(COMMONLIBS)
 ONDEMANDFLAGS  =       @ONDEMANDFLAGS@
```

(It feels really suboptimal that I have to run Travis tests on my side to identify build-failures on Debian. I'm aware that Travis-CI (.com or .org) cannot be enabled on the apple namespace (#5113, #5531, …); but could you not get some CI system run tests on every commit/push on non-Apple hosts? Happy to help getting something along those lines started; just ask! )

**Comment by michaelrsweet** [comment]
@OdyX I wish I had the resources to setup automated build/test VMs for CUPS, but those are no longer available to me. In its place I run periodic (~weekly) build tests with the default configuration on Fedora and Ubuntu, and I just haven't gotten to doing those yet this week...

Your proposed change is incorrect - the point is to minimize the amount of extra linking that is performed, so instead ippeveprinter needs to link against $(DNSSDLIBS) in addition to the $(LINKCUPS) macro. I will do a sweep this morning to fix any of these build issues.

**Comment by michaelrsweet** [comment]
[master 7c11d5aea] Fix Linux build issues with new LINKCUPS macro
