### ISSUE TITLE
 Why does CUPS not see my USB printer Intermec?

### ISSUE THREAD

**Issue by Michal2005** [apple/cups#5585]
Hi,
why does CUPS not see my USB printer?
I have 4 printers Intermec easycoder pc4 and Datamax, ZEBRA - Printer from year aprox 2000.

Thank you for answer.

**Comment by michaelrsweet** [comment]
@Michal2005 What operating system are you using?

What kind of hardware do you have?

**Comment by Michal2005** [comment]
@michaelrsweet OS is Windows 7 PRO x64
And Printer is Label printer Intermer Easycoder PC4 :+1: https://www.google.com/search?q=intermec+easycoder+pc4&client=firefox-b-d&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiQrtbLpaPiAhVMxcQBHYlUClYQ_AUIDigB&biw=1376&bih=663

**Comment by Michal2005** [comment]
CUPS version is latest: CUPS 2.3b8

**Comment by michaelrsweet** [comment]
OK, first we DO NOT support CUPS on Windows, and I doubt any of the USB ports are accessible from the Linux subsystem. Second, CUPS 2.3b8 is a developer snapshot, NOT a stable release.

Sorry, we can't help you...

**Comment by Michal2005** [comment]
> 
> 
> OK, first we DO NOT support CUPS on Windows, and I doubt any of the USB ports are accessible from the Linux subsystem. Second, CUPS 2.3b8 is a developer snapshot, NOT a stable release.
> 
> Sorry, we can't help you...

No Printer is directly conected to linux PC Debian with USB cable.
