### ISSUE TITLE
not the make and model

### ISSUE THREAD

**Issue by markosjal** [apple/cups#5586]
I have a Xerox Phaser 6125 that I run on Ubuntu 16.04 .  This printer works in Linux only with the Fuji Xerox C525 driver. CUPS displays the following in web portal

▼ Queue Name ▼ | Description | Location | Make and Model | Status
Xerox_Phaser-6125 | Xerox_Phaser-6125 | Office | FX DocuPrint C525 A-AP v1.0 | Idle

The problem is that "Make and Model" shows the driver name not the make and model . This also propogates to Avahi and when someone is looking for the Xerox they see FX .

Here is another example of a HP Color Laserjet that even shows "recommended" as if in some way it is the "recommended Printer" . In fact it is the "recommended" driver for that printer!

▼ Queue Name ▼ | Description | Location | Make and Model | Status

HP-Color-LaserJet-2600n | HP Color LaserJet 2600n |   | HP Color LaserJet 2600n Foomatic/foo2hp (recommended) | Paused - "Paused"

I know back in the day I used a HP Laserjet PS driver on a Laserwriter and I am sure that there are many instances where a drriver is different from the printer model . 

When this all propagtes downstream to things like Avahi it is important that it is accurate from the beginning

This was reported and supposedly fixed over 10 years ago 
https://github.com/apple/cups/issues/2256

**Comment by michaelrsweet** [comment]
The make and model comes from the PPD file, always has. And normally this matches the real device (Particularly for any recent printer with IPP support)

**Comment by markosjal** [comment]
But the PPD does not always match the printer model installed. Sodtware does no kow if I am using a Postscript friver with a Xerox Printer or an HP

**Comment by michaelrsweet** [comment]
The software shouldn't care.

**Comment by markosjal** [comment]
You fail to understand the pont. The point is if that is driver infor then it should say DRIVER not Make and Model

**Comment by markosjal** [comment]
This was reported and supposedly fixed in 2007 #2256

**Comment by michaelrsweet** [comment]
This issue will NOT be fixed. The notion of drivers is a legacy of PPDs and is NOT something we wish to propagate.
