### ISSUE TITLE
make install fails when GZIP defined in environment

### ISSUE THREAD

**Issue by sambltc** [apple/cups#5595]
"env GZIP=-n make install" fails, ending with:

gzip: /bin/gzip.gz: Permission denied
Makefile:151: recipe for target 'install-data' failed
make[1]: *** [install-data] Error 1
Makefile:166: recipe for target 'install-data' failed
make: *** [install-data] Error 1

It seems to be because a variable named "GZIP" is used in the makefiles.
(The existence of GZIP in the environment causes Make to export "GZIP" with it's value (the path to the gzip binary) but gzip itself expects to find command line options in it and fails.)

**Comment by michaelrsweet** [comment]
Lovely. But also install-sh looks for GZIPPROG and not GZIP, so that too needs to be corrected.

Will change everything to use GZIPPROG (and do the right configure test for its availability...)

**Comment by michaelrsweet** [comment]
[master 3001a140d] Use GZIPPROG instead of GZIP to avoid install issues (Issue #5595)

[branch-2.2 3676fc318] Use GZIPPROG instead of GZIP to avoid install issues (Issue #5595)

**Comment by sambltc** [comment]
Thanks so much for the fix! :-)
