### ISSUE TITLE
(feature request) add FTP support

### ISSUE THREAD

**Issue by bruceleerabbit** [apple/cups#5599]
Some printer servers [support FTP](https://www.brooksnet.com/content/ftp-printing).  It would be useful if CUPS would support this method.

It could help troubleshoot cases where CUPS gives the status: "The printer is not responding", when in fact the printer server otherwise seems to be online.

**Comment by michaelrsweet** [comment]
Sorry, we have no interest in supporting an insecure protocol whose usage for printing is totally non-standard and undocumented. Almost every network printer sold today supports IPP.

**Comment by jsmeix** [comment]
@bruceleerabbit 
FYI how you could implement your own CUPS backend for FTP printing
that you may use in your fully trusted network environment where an insecure
protocol may not matter in your particular case, you may have a look at
https://en.opensuse.org/SDB:Using_Your_Own_Backends_to_Print_with_CUPS
and in general regarding printing related network security considerations see
https://en.opensuse.org/SDB:CUPS_and_SANE_Firewall_settings
