### ISSUE TITLE
Cups Curios Behavior -Security issue

### ISSUE THREAD

**Issue by circuitikzuser** [apple/cups#5602]
Cups stops working, I then go to the administration page and find that about 20 RSS feeds appeared. RSS why and who are automatically subscribing. 
**Once I delete theses bogus RSS feeds the printers work again**.  The automatic RSS feeds are clearly the source of the printer problem.
It is not a few days later and orders of 10s of RSS feeds appear again.

More important,
1)  To have your printer output get RSS feeds is really serious. Who are the bogus recipients ?
2) Furthermore there is NO way in the manual I could find how to completely disable these RSS feeds. This is a big security hole if it cannot be disabled. It seems to be on by default.
3) Again, these feeds interrupts printing AND cannot be switched off. Where does it feed information to ?

I attached a screenshot of these RSS feeds automatic appearing.
It is malicious it seems and **CUPS seemingly do not allow to dissssable RSS feeds**, which is an even worse problem

![20190618_124754](https://user-images.githubusercontent.com/37168019/59809693-c0150780-92cf-11e9-8241-174ff4a0dc95.jpg)

**Comment by michaelrsweet** [comment]
@circuitikzuser You can do the following on Linux to purge these subscriptions:

```
sudo systemctl stop org.cups.cupsd.service
sudo rm /etc/cups/subscriptions.conf
sudo systemctl start org.cups.cupsd.service
```

(the service name and command may vary depending on which Linux distribution you are using)

Current CUPS doesn't actually allow RSS subscriptions to be created from the web interface anymore. (I can't determine which version of CUPS you are using from the screenshot)

**Comment by circuitikzuser** [comment]
Is purging subscriptions actually switching off the subscriptions ?
It seems like you suggest I must remove the config file.

This is really wreaking havoc with printing and would help if I can permanently disable RSS.
BTW, who are the supposed recipients for RSS feeds in CUPS and why did cups developers create it?

I have several machines with this problem, and they have different versions of cups.
I will go check what the version of cups it is.

**Comment by michaelrsweet** [comment]
@circuitikzuser Purging turns those subscriptions off. It doesn't prevent them in the future - to do that you need to remove the rss notifier:

```
sudo rm /usr/lib/cups/notifier/rss
```

The RSS notifier was created because, at the time, RSS feeds were a popular thing and providing an RSS feed was an easy way to allow admins and operators to monitor the state of the printing system. Of course they can still be used for that, but RSS isn't as popular anymore so we removed the web subscription interface.

**Comment by circuitikzuser** [comment]
Also;
You stated
"Current CUPS doesn't actually allow RSS subscriptions to be created from the web interface anymore."
So why was the RSS creationdisabled in later Cups versions.
What was the reason or incentive for dropping it?

**Comment by circuitikzuser** [comment]
You wrote "sudo rm /usr/lib/cups/notifier/rss"
Thanks
I will do a one minute cronjob to make sure that doesnt reinstall ever again.

**Comment by circuitikzuser** [comment]
OK Done, Cron now tests for it and removes the files every minute.

**Comment by circuitikzuser** [comment]
Last question, 

I never created subscriptions I have no need for that although I am a sysadmin.

What is the procedure by which these RSS feeds automatically appear in their 10s.
Your config file for RSS which I did look at in the past is binary and not text, so no one knows what that file actually does.

**Comment by michaelrsweet** [comment]
@circuitikzuser these may not be rss subscriptions - the web interface listed all subscriptions and some would be dbus ones created by the desktop tools and other system daemons like cups-browsed.

The subscriptions.conf file contains a list of active subscriptions. The rss binary is the notifier that posts the events in an RSS feed. There is nothing malicious about either file, and at this point you haven’t provided enough information to determine whether the subscriptions are valid or the result of a bug in some software you are using.

**Comment by circuitikzuser** [comment]
Oh my... my favorite dbus.... Now that is a box of junk. I think Cups made a mistake to let Dbus have any access to printers through RSS. As the original reply stated, this problem is absent in the newer versions, but I will disable RSS with cron by deleting the file. So far it works on one of the machines and I dont have the problem anymore.

This is serious for cups as it rings the printers down when these automatic RSS is added by G'd knows what automatically.

**Comment by circuitikzuser** [comment]
Last Question:
It was stated that the newest version of Cups do not allow RSS feeds from the interface anymore.
Does the newest version also block these automatic RSS feeds from other applications as mentiond ?

It went well for a while, but these automatic RSS feeds started to appear again after I did everything to the letter that was suggested, and the printers stalled again as a result due to the myriad of automatically added feeds.

**Comment by michaelrsweet** [comment]
@circuitikzuser If you can attach the current subscriptions.conf file from your system I might be able to help diagnose what it creating the subscriptions. I do recall a bug in the print monitor on Linux that caused multiple subscriptions to be created...

**Comment by michaelrsweet** [comment]
(the print monitor is part of GNOME, not CUPS...)

**Comment by circuitikzuser** [comment]
michaelrsweet wrote
 "If you can attach the current subscriptions.conf"

 subscriptions.conf  was deleted as per instruction early on in the thread, therefore it doesnt exist anymore.

thank you for the lead with the print monitor. This really smells like the problem as gnome is a huge systemd/dbus supporter, and based on the trouble I had with systemd/dbus in the past I have the hunch that this must be it. I will look into it and report back.
