### ISSUE TITLE
the value of 'printer-info' is set to 'printer-name' automatically.

### ISSUE THREAD

**Issue by ChoiChoongHo94** [apple/cups#5603]
CUPS version: 2.2.10

1. Enter ` lpadmin -p {printer-name} -D '' `-> 'Info' in '/etc/cups/printers.conf' become blank .
2. when I enter  `lpoptions -p {printer-name}` , 'printer-info' is printed.
3. cups restart or reboot.
4. 'Info' still is blank.
5. but, when I enter  `lpoptions -p {printer-name}`  , 'printer-info={printer-name}' is printed.

How can I avoid 'printer-info' is set to 'printer-name' automatically?

**Comment by michaelrsweet** [comment]
Investigating; ordinarily the printer-info value isn't going to be blank but will see what is going on here...

**Comment by michaelrsweet** [comment]
[master 614efb7a8] Don't default printer-info, printer-location, printer-geo-location (Issue #5603)

[branch-2.2 2062d366e] Don't default printer-info, printer-location, printer-geo-location (Issue #5603)
