### ISSUE TITLE
Provide small IPP framework for iOS/macOS printer support applications

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#5607]
Printer support applications provided for iOS currently must embed their own libcups, if they use the CUPS IPP API, but several of the HTTP functions use deprecated functions and constants from the Security framework (Issue #5516).

Try creating a new wrapper library that consists only of the basic IPP and string functions from libcups with an Objective C wrapper - this will work on all versions of macOS and iOS.

**Comment by michaelrsweet** [comment]
[PAPPL](https://github.com/michaelrsweet/pappl).

**Comment by lingxuxiong** [comment]
Hi @michaelrsweet, am working on sending IPP requests from iOS devices to a printer, how to achieve this thru PAPPL instead of writing our own SWIFT or OC wrappers? I mean using C APIs from PAPPL instead of HTTP-related APIs from UIKit or other networking frameworks.
