### ISSUE TITLE
'lpadmin -p <print_queue> -o cupsSNMPSupplies=false' does not work

### ISSUE THREAD

**Issue by zdohnal** [apple/cups#5609]
Hi,

Bryan, our support engineer, found out in https://bugzilla.redhat.com/show_bug.cgi?id=1726383 the setting of cupsSNMPSupplies and cupsIPPSupplies do not work, because the updated ppd is not sent in request, but only the old one. IMO it is caused by not setting 'ppdchanged' variable to 1, so the new file is not sent.

I'll create a pull request for the fix, please let me know if it is correct way of fixing it or if you want to do some enhancements.

**Comment by michaelrsweet** [comment]
Duping to Issue #5610 (the pull request)...
