### ISSUE TITLE
lpinfo  -v can't show my Label Printer(Gprinter GP5860III)

### ISSUE THREAD

**Issue by sherwinkh** [apple/cups#5612]
root@xxx:# ll /dev/usb/lp0 
crw-rw---- 1 root lp 180, 0 Jul 11 08:18 /dev/usb/lp0
but I can't see it in "lpinfo  -v"

root@xxx:# lpinfo -v
network ipp
network ipps
network https
network http
network lpd
network socket
root@xxx:# 

someone can help?

**Comment by jsmeix** [comment]
No specific info so only a generic reply:

It is usually no issue in CUPS itself when a CUPS backend
(in this case the CUPS backend `usb`) cannot detect
a printer device.

Since a longer time the CUPS backend `usb`
does no longer use the usblp kernel module
that is "behind" /dev/usb/lp0
but instead nowadays libusb is used.

Usually the root cause in such cases is at a lower level
e.g. kernel or USB subsystem or USB hardware or whatever
when the CUPS backend `usb` cannot detect a USB printer.

You may have a look at "The Backends" at
https://en.opensuse.org/SDB:CUPS_in_a_Nutshell
and
https://en.opensuse.org/SDB:Using_Your_Own_Backends_to_Print_with_CUPS
and
https://en.opensuse.org/SDB:How_to_Report_a_Printing_Issue

**Comment by sherwinkh** [comment]
libusb has been installed,and GP5860III still can't be detected.anthoer printer can be detected.
###
root@rk3288:/usr/local/cups/lib/cups/backend# ./usb 
direct usb://Deli/DL-888B(NEW) "Deli DL-888B(NEW)" "Deli DL-888B(NEW)" "MFG:Deli ;CMD:XPP,XL;MDL:DL-888B(NEW);CLS:PRINTER;DES:DL-888B(N" ""
root@rk3288:/usr/local/cups/lib/cups/backend# uname -a
Linux rk3288 3.0.36+ #78 SMP PREEMPT Mon Feb 20 18:08:23 CST 2017 armv7l armv7l armv7l GNU/Linux
root@rk3288:/usr/local/cups/lib/cups/backend# cat /etc/issue
Ubuntu 14.04.1 LTS \n \l

**Comment by michaelrsweet** [comment]
I believe this printer uses the USB serial class and not the USB parallel class. It therefore will not appear as a printer.

You can enable the file device (in the "cups-files.conf" file) and then specify the corresponding USB serial device file.

**Comment by sherwinkh** [comment]
@michaelrsweet 
I modify “FileDevice Yes” in cups-files.conf.
What does this mean:specify the corresponding USB serial device file?
my printer info from "lsusb -v"

```
Bus 002 Device 009: ID 6868:0600  
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x6868 
  idProduct          0x0600 
  bcdDevice            1.00
  iManufacturer           1 Gprinter
  iProduct                2 GP-58
  iSerial                 3 6A8209AD1831
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           55
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xc0
      Self Powered
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         7 Printer
      bInterfaceSubClass      1 Printer
      bInterfaceProtocol      2 Bidirectional
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x84  EP 4 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval              10
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x03  EP 3 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval              10
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass         8 Mass Storage
      bInterfaceSubClass      6 SCSI
      bInterfaceProtocol     80 Bulk-Only
      iInterface              4 GP-58
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0040  1x 64 bytes
        bInterval               0
Device Status:     0x0001
  Self Powered
```

**Comment by michaelrsweet** [comment]
OK, the lsusb output looks like the printer implements both Mass Storage and Printer classes, so more than likely the printer has been claimed by a block device... Not sure what you can do to override this behavior, unfortunately...

**Comment by michaelrsweet** [comment]
Also, you should NOT be using a beta release of CUPS - we can't support that (particularly when it is so out-of-date), and you could easily be running into an issue that is fixed by using the current stable release of the CUPS software...

**Comment by sherwinkh** [comment]
> OK, the lsusb output looks like the printer implements both Mass Storage and Printer classes, so more than likely the printer has been claimed by a block device... Not sure what you can do to override this behavior, unfortunately...

Yes
```
root@rk3288:~# lsusb -t
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=usb20_host/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/4p, 480M
        |__ Port 1: Dev 3, If 0, Class=Printer, Driver=, 12M
        |__ Port 1: Dev 3, If 1, Class=Mass Storage, Driver=usb-storage, 12M
        |__ Port 3: Dev 4, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
        |__ Port 4: Dev 5, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
        |__ Port 4: Dev 5, If 1, Class=Human Interface Device, Driver=usbhid, 1.5M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=usb20_otg/1p, 480M
root@rk3288:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/mtdblock1  2.9G  2.5G  296M  90% /
udev            188M  4.0K  188M   1% /dev
tmpfs            77M  264K   77M   1% /run
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            192M   88K  192M   1% /run/shm
none            100M   20K  100M   1% /run/user
/dev/sda        3.0M  2.6M  392K  88% /media/firefly/0C79-5D53
```

**Comment by sherwinkh** [comment]
@michaelrsweet I had tried on cups-2.3rc1."lpinfo -v" still can't find the printer.
In storage of /media/firefly/0C79-5D53,I found the printer driver for windows....
As you mentioned: `the printer has been claimed by a block device`
Could you give me some suggestion?

**Comment by michaelrsweet** [comment]
Sorry, I really have no suggestions for you. You should contact your Linux distributor for help.
