### ISSUE TITLE
Shared Label Printer can't work

### ISSUE THREAD

**Issue by sherwinkh** [apple/cups#5614]
I use cups-2.3rc1, adding my label printer(Deli_DL-888B(New)) as a shared Printer in web browser .
Then add printer device(http://192.168.1.101:631/printers/Deli-888B) in the control panel of Win7.
![image](https://github.com/sherwinkh/hello/raw/master/deli888B.png)
![image](https://github.com/sherwinkh/hello/raw/master/add_printer.jpg)
When I print a Label by BarTender(Deli's label edit software for Win7),nothing comes out.
someone can help? 
error_log: https://pastebin.com/CShcizrX
Deli_DL-888B.ppd: https://pastebin.com/tHJQCiSb

**Comment by michaelrsweet** [comment]
@sherwinkh I suspect the windows driver needs bidirectional access to the printer and just won’t work in this configuration. Sorry.

**Comment by sherwinkh** [comment]
@michaelrsweet I have tried some diffrent configrations in web browser,but no one can works.
`I suspect the windows driver needs bidirectional access to the printer`
about this ,can you give me some advices?
