### ISSUE TITLE
ERROR CUPS Unable to get PPD file 

### ISSUE THREAD

**Issue by VeronicaMinango** [apple/cups#5615]
Please I need some help, I have my print server on a server with oracle Solaris 11.3 for sparc, for some reason the 12 printers stop printing and right now I just have 2 of them working, this happen eventualy and I donpt know what is the problem. these is the error_log

W [15/Jul/2019:23:30:22 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
E [15/Jul/2019:23:38:20 +0500] [CGI] Bad SNMP packet from 10.10.207.16: variable-bindings uses indefinite lengthDEBUG2: cgiCopyTemplateLang(tmpl="
E [15/Jul/2019:23:38:20 +0500] [cups-deviced] PID 6525 (smb) stopped with status 1!
E [15/Jul/2019:23:39:38 +0500] [cups-deviced] PID 6678 (smb) stopped with status 1!
W [16/Jul/2019:05:32:11 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:05:33:52 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:05:34:38 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:05:49:37 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:05:50:15 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:05:52:49 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:06:08:11 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:06:10:26 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:06:12:00 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:06:13:16 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:06:19:25 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:06:21:33 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:06:25:36 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:06:32:39 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:06:45:48 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:06:50:42 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:06:52:46 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:06:53:45 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:06:54:50 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:06:56:29 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:07:03:05 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:07:06:02 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:07:07:03 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:07:09:53 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:07:37:54 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
E [16/Jul/2019:07:40:26 +0500] [cups-deviced] PID 9488 (smb) stopped with status 1!
W [16/Jul/2019:07:44:44 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:07:58:41 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:08:00:19 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:08:02:47 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:08:04:01 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
E [16/Jul/2019:08:09:25 +0500] [CGI] Bad SNMP packet from DEBUG2: 10.10.207.16  Starting at file position 804...
E [16/Jul/2019:08:09:25 +0500] [cups-deviced] PID 12979 (smb) stopped with status 1!
W [16/Jul/2019:08:11:45 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:08:12:19 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:08:16:24 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:08:18:46 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:08:19:28 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:08:22:19 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:08:23:59 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:08:26:14 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:08:28:01 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:08:29:57 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:08:31:12 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:08:34:30 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:08:36:07 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:08:37:37 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:08:39:07 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
E [16/Jul/2019:08:52:15 +0500] [cups-deviced] PID 22398 (smb) stopped with status 1!
W [16/Jul/2019:08:52:16 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
E [16/Jul/2019:08:53:58 +0500] [CGI] Unable to get PPD file /printers/PRTPICKING02.ppd: 404 - Not Found
E [16/Jul/2019:08:53:59 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/kyocera_ppd_8.2.txt"!
E [16/Jul/2019:08:53:59 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/ReadMe.htm"!
E [16/Jul/2019:08:54:06 +0500] [CGI] Unable to get PPD file /printers/PRTPICKING02.ppd: 404 - Not Found
E [16/Jul/2019:08:54:07 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/kyocera_ppd_8.2.txt"!
E [16/Jul/2019:08:54:07 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/ReadMe.htm"!
W [16/Jul/2019:08:54:34 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
E [16/Jul/2019:08:55:34 +0500] [CGI] Bad SNMP packet from 10.10.207.16: variable-bindings uses indefinite lengthDEBUG2: 
E [16/Jul/2019:08:55:34 +0500] [cups-deviced] PID 22973 (smb) stopped with status 1!
W [16/Jul/2019:08:55:36 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
E [16/Jul/2019:08:57:25 +0500] [cups-deviced] PID 23274 (smb) stopped with status 1!
W [16/Jul/2019:08:57:28 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
E [16/Jul/2019:08:58:24 +0500] [cups-deviced] PID 23303 (smb) stopped with status 1!
W [16/Jul/2019:08:58:34 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:08:59:38 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:00:42 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
E [16/Jul/2019:09:03:23 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/kyocera_ppd_8.2.txt"!
E [16/Jul/2019:09:03:23 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/ReadMe.htm"!
E [16/Jul/2019:09:03:33 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/kyocera_ppd_8.2.txt"!
E [16/Jul/2019:09:03:33 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/ReadMe.htm"!
W [16/Jul/2019:09:03:45 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
E [16/Jul/2019:09:04:14 +0500] [CGI] Bad SNMP packet from DEBUG2:   10.10.207.16Returning at file position : variable-bindings uses indefinite length
E [16/Jul/2019:09:04:14 +0500] [cups-deviced] PID 23925 (smb) stopped with status 1!
E [16/Jul/2019:09:04:21 +0500] [CGI] Unable to get PPD file /printers/PRTPICKING02.ppd: 404 - Not Found
E [16/Jul/2019:09:04:21 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/kyocera_ppd_8.2.txt"!
E [16/Jul/2019:09:04:21 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/ReadMe.htm"!
E [16/Jul/2019:09:04:40 +0500] [CGI] Bad SNMP packet from DEBUG2: 10.10.207.16  : variable-bindings uses indefinite length
E [16/Jul/2019:09:04:40 +0500] [cups-deviced] PID 23952 (smb) stopped with status 1!
E [16/Jul/2019:09:04:53 +0500] [CGI] Unable to get PPD file /printers/PRTPICKING11.ppd: 404 - Not Found
E [16/Jul/2019:09:04:53 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/kyocera_ppd_8.2.txt"!
E [16/Jul/2019:09:04:53 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/ReadMe.htm"!
W [16/Jul/2019:09:06:12 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:07:33 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
E [16/Jul/2019:09:12:48 +0500] [cups-deviced] PID 24329 (smb) stopped with status 1!
E [16/Jul/2019:09:13:56 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/kyocera_ppd_8.2.txt"!
E [16/Jul/2019:09:13:56 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/ReadMe.htm"!
E [16/Jul/2019:09:14:06 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/kyocera_ppd_8.2.txt"!
E [16/Jul/2019:09:14:06 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/ReadMe.htm"!
W [16/Jul/2019:09:14:10 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:14:45 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:16:21 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:17:41 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:18:35 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:19:11 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:21:10 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:21:54 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:22:26 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:23:01 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
E [16/Jul/2019:09:23:39 +0500] Returning IPP client-error-not-authorized for Print-Job (ipp://10.10.205.143:631/printers/rec2) from 10.10.205.143
W [16/Jul/2019:09:24:10 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:25:11 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:26:46 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
E [16/Jul/2019:09:28:08 +0500] Returning IPP client-error-not-authorized for Print-Job (ipp://10.10.205.143:631/printers/rec2) from 10.10.205.143
W [16/Jul/2019:09:28:40 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:31:29 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:32:20 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:32:56 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
E [16/Jul/2019:09:35:39 +0500] Returning IPP client-error-not-authorized for Print-Job (ipp://uiortbidbp02:631/printers/rec2) from 10.10.205.143
W [16/Jul/2019:09:36:16 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:38:42 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:39:37 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
E [16/Jul/2019:09:41:08 +0500] [cups-deviced] PID 27694 (smb) stopped with status 1!
E [16/Jul/2019:09:41:27 +0500] [CGI] Unable to get PPD file /printers/REC1.ppd: 404 - Not Found
E [16/Jul/2019:09:41:27 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/kyocera_ppd_8.2.txt"!
E [16/Jul/2019:09:41:27 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/ReadMe.htm"!
E [16/Jul/2019:09:41:38 +0500] [CGI] Unable to get PPD file /printers/REC1.ppd: 404 - Not Found
E [16/Jul/2019:09:41:38 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/kyocera_ppd_8.2.txt"!
E [16/Jul/2019:09:41:38 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/ReadMe.htm"!
W [16/Jul/2019:09:42:40 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:43:13 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:44:26 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:45:10 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:47:51 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:49:21 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:50:01 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
E [16/Jul/2019:09:52:20 +0500] [cups-deviced] PID 28777 (smb) stopped with status 1!
E [16/Jul/2019:09:52:51 +0500] [CGI] Unable to get PPD file /printers/PRTPICKING02.ppd: 404 - Not Found
E [16/Jul/2019:09:52:52 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/kyocera_ppd_8.2.txt"!
E [16/Jul/2019:09:52:52 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/ReadMe.htm"!
E [16/Jul/2019:09:53:01 +0500] [CGI] Unable to get PPD file /printers/PRTPICKING02.ppd: 404 - Not Found
E [16/Jul/2019:09:53:01 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/kyocera_ppd_8.2.txt"!
E [16/Jul/2019:09:53:01 +0500] [cups-driverd] Bad driver information file "/usr/share/cups/model/foomatic-db-ppds/Kyocera/ReadMe.htm"!
W [16/Jul/2019:09:55:32 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:56:48 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:57:23 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:58:21 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:09:59:59 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:06:51 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:07:22 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:13:08 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:16:45 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:18:51 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:21:15 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:22:41 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:23:40 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:24:23 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:26:29 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:27:26 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:28:37 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:31:16 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:32:02 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:32:34 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:34:54 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:35:52 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:37:19 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:39:16 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:40:44 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:42:30 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:44:09 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:45:28 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:47:37 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:49:58 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:51:16 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:51:52 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!
W [16/Jul/2019:10:53:23 +0500] Notifier for subscription 42 (rss:///.rss?max_events=20) went away, retrying!

**Comment by michaelrsweet** [comment]
@VeronicaMinango That sounds like the PPD files were deleted from the /etc/cups/ppd directory...

**Comment by michaelrsweet** [comment]
No response from reporter, closing...

**Comment by slorquet** [comment]
Hi, I have a similar problem with a samsung c430w, and /etc/cups/pppd is empty. How do I get the files back?
