### ISSUE TITLE
 Unable to get paper colors from cups 2.0.1 using cups4j

### ISSUE THREAD

**Issue by Bahnstreik** [apple/cups#5616]
I'm currently using Cups Version 1.2.4 for a print-application.
A mandatory feature is to read the paper color (White Paper, Blue Paper, ..). This is done by reading the mediaSupported tag with an old print library called jipsi.

The print-application is now going to be updated with a new CUPS version 2.0.2 and the print library Cups4j. 
If I try to read the paper color with the mediaSupported tag, the resultset outputs me papersizes like "iso_b4_250x352mm" instead of the paper colors I need to get.
The other data that Cups4j provides me for the printer also doesnt include the paper color.
[Cups4j printer information new Cups](https://i.imgur.com/d6UnXHu.png)

If I use the old Cups Version 1.2.4 and cups4j, the mediaSupported tag contains the paper colors, that I need to get.
[Cups4j printer information old Cups](https://i.imgur.com/r12Z74a.png)

However the webinterface of the new Cups lists the paper colors that I need to access.
[Pic of Cups Webinterface](https://i.imgur.com/AP7NJSX.png)

Now my question:
Is there any way to get the paper color, maybe by asking the IPP protocol directly?

**Comment by michaelrsweet** [comment]
Paper color (media-color) support is printer-specific. You may be able to query the media-col-database or media-col-ready attributes from the printer using IPP, and the media-color member attribute (If present) will tell you the color of the media, however there is no explicit support for paper color in CUPS. Some older IPP printers might even report the pre-standard color names in media-supported/media-ready.

FWIW, reporting paper color in the "media-supported" or "media-ready" attributes has been deprecated behavior for 18 years. CUPS has never supported paper color explicitly (some PPD files might include PageSize values with colors, but CUPS doesn't expose it via IPP's media-color attribute and always reports PWG media size names in the media-supported attribute), so I'm not sure where you've gotten the color information from in older CUPS releases...
