### ISSUE TITLE
Long delay before printing the last page on HP Laserjet 1015 via USB

### ISSUE THREAD

**Issue by rompic** [apple/cups#5617]
The issues described in
https://github.com/apple/cups/issues/5121
and
https://github.com/apple/cups/issues/4549
also exist on the HP LaserJet 1015

**Comment by rompic** [comment]
after adding the same quirk it works as expected https://github.com/apple/cups/pull/5618

**Comment by michaelrsweet** [comment]
Changes pushed to 2.2.x and 2.3.x.
