### ISSUE TITLE
Cups Service - High Memory Usage

### ISSUE THREAD

**Issue by narayanan-t2s** [apple/cups#5619]
I'm running Ubuntu 16.04 with cups installed for printing. I'm observing that the cups service is gradually increasing memory and reaches 100% in few hours of time.

Could someone help me to find what the actual reason could be for this high memory usage ?

**Comment by michaelrsweet** [comment]
We'll need a lot more information, but typically the thing that uses the most memory is the job history. What do the following commands return:

```
lpstat -W all | wc -l
lpstat -v | wc -l
```

**Comment by narayanan-t2s** [comment]
Hello,

Thanks for the response.

lpstat -W all | wc -l 
9
lpstat -v | wc -l
3

PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                      
5381 root      20   0  807072 722188   6016 S   0.0 18.5   0:27.90 cupsd

**Comment by michaelrsweet** [comment]
OK, so 9 print jobs and 3 print queues will not account for the memory usage you are seeing.

The only other possibility (the can be associated with the CUPS sources anyways) is that some client or program is keeping a lot of network connections open to the scheduler. What does "sudo lsof -p PID" report (where PID is the process ID of the cupsd program)?

**Comment by narayanan-t2s** [comment]
t2s@t2s-X7C-T2:~$ sudo lsof -p `pidof cupsd`
COMMAND  PID USER   FD      TYPE             DEVICE SIZE/OFF    NODE NAME
cupsd   5381 root  cwd       DIR                8,1     4096       2 /
cupsd   5381 root  rtd       DIR                8,1     4096       2 /
cupsd   5381 root  txt       REG                8,1   416328  654198 /usr/sbin/cupsd
cupsd   5381 root  mem       REG                8,1    47600  529551 /lib/x86_64-linux-gnu/libnss_files-2.23.so
cupsd   5381 root  mem       REG                8,1    47648  527967 /lib/x86_64-linux-gnu/libnss_nis-2.23.so
cupsd   5381 root  mem       REG                8,1    93128  529486 /lib/x86_64-linux-gnu/libnsl-2.23.so
cupsd   5381 root  mem       REG                8,1    35688  529803 /lib/x86_64-linux-gnu/libnss_compat-2.23.so
cupsd   5381 root  mem       REG                8,1    31104  655500 /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
cupsd   5381 root  mem       REG                8,1   101200  528062 /lib/x86_64-linux-gnu/libresolv-2.23.so
cupsd   5381 root  mem       REG                8,1    14256  523513 /lib/x86_64-linux-gnu/libkeyutils.so.1.5
cupsd   5381 root  mem       REG                8,1   522664  657045 /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
cupsd   5381 root  mem       REG                8,1   207640  657051 /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
cupsd   5381 root  mem       REG                8,1   219336  657047 /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
cupsd   5381 root  mem       REG                8,1    76192  657102 /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
cupsd   5381 root  mem       REG                8,1   207208  657055 /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
cupsd   5381 root  mem       REG                8,1   408472  656305 /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
cupsd   5381 root  mem       REG                8,1    80496  523443 /lib/x86_64-linux-gnu/libgpg-error.so.0.17.0
cupsd   5381 root  mem       REG                8,1   456632  523456 /lib/x86_64-linux-gnu/libpcre.so.3.13.2
cupsd   5381 root  mem       REG                8,1    43664  654835 /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
cupsd   5381 root  mem       REG                8,1    14648  523488 /lib/x86_64-linux-gnu/libcom_err.so.2.1
cupsd   5381 root  mem       REG                8,1   186872  656282 /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
cupsd   5381 root  mem       REG                8,1   860392  654826 /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
cupsd   5381 root  mem       REG                8,1  1088952  529929 /lib/x86_64-linux-gnu/libm-2.23.so
cupsd   5381 root  mem       REG                8,1   104864  523428 /lib/x86_64-linux-gnu/libz.so.1.2.8
cupsd   5381 root  mem       REG                8,1  1239440  668733 /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
cupsd   5381 root  mem       REG                8,1   919168  528045 /lib/x86_64-linux-gnu/libgcrypt.so.20.0.5
cupsd   5381 root  mem       REG                8,1   137400  523467 /lib/x86_64-linux-gnu/liblzma.so.5.0.0
cupsd   5381 root  mem       REG                8,1    31712  523779 /lib/x86_64-linux-gnu/librt-2.23.so
cupsd   5381 root  mem       REG                8,1   130224  523334 /lib/x86_64-linux-gnu/libselinux.so.1
cupsd   5381 root  mem       REG                8,1    14608  523881 /lib/x86_64-linux-gnu/libdl-2.23.so
cupsd   5381 root  mem       REG                8,1   117288  523474 /lib/x86_64-linux-gnu/libaudit.so.1.0.0
cupsd   5381 root  mem       REG                8,1  1868984  529740 /lib/x86_64-linux-gnu/libc-2.23.so
cupsd   5381 root  mem       REG                8,1   138696  527717 /lib/x86_64-linux-gnu/libpthread-2.23.so
cupsd   5381 root  mem       REG                8,1   301376  654812 /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
cupsd   5381 root  mem       REG                8,1   522192  654363 /usr/lib/x86_64-linux-gnu/libcups.so.2
cupsd   5381 root  mem       REG                8,1    68512  660352 /usr/lib/x86_64-linux-gnu/libavahi-client.so.3.2.9
cupsd   5381 root  mem       REG                8,1    47952  657002 /usr/lib/x86_64-linux-gnu/libavahi-common.so.3.5.3
cupsd   5381 root  mem       REG                8,1   309392  523739 /lib/x86_64-linux-gnu/libdbus-1.so.3.14.6
cupsd   5381 root  mem       REG                8,1    15984  670170 /usr/lib/x86_64-linux-gnu/libpaper.so.1.1.2
cupsd   5381 root  mem       REG                8,1    55904  523338 /lib/x86_64-linux-gnu/libpam.so.0.83.1
cupsd   5381 root  mem       REG                8,1    26464  654167 /usr/lib/x86_64-linux-gnu/libcupsmime.so.1
cupsd   5381 root  mem       REG                8,1   162632  527652 /lib/x86_64-linux-gnu/ld-2.23.so
cupsd   5381 root  mem       REG                8,1   536520  542355 /lib/x86_64-linux-gnu/libsystemd.so.0.14.0
cupsd   5381 root    0r      CHR                1,3      0t0    1029 /dev/null
cupsd   5381 root    1u     unix 0xffff8800359e4780      0t0 1485721 type=STREAM
cupsd   5381 root    2u     unix 0xffff8800359e4780      0t0 1485721 type=STREAM
cupsd   5381 root    3u     unix 0xffff8800b9bca1c0      0t0    1598 /var/run/cups/cups.sock type=STREAM
cupsd   5381 root    4r      CHR                1,9      0t0    1034 /dev/urandom
cupsd   5381 root    5u  a_inode               0,11        0   10045 [eventpoll]
cupsd   5381 root    6u      REG                8,1   108866  921350 /var/log/cups/access_log
cupsd   5381 root    7u      REG                8,1    79569  921353 /var/log/cups/error_log
cupsd   5381 root    8u      REG                8,1        0  921356 /var/log/cups/page_log
cupsd   5381 root    9u     unix 0xffff880036708f00      0t0 1489023 type=STREAM
cupsd   5381 root   10u     IPv6            1488227      0t0     TCP ip6-localhost:ipp (LISTEN)
cupsd   5381 root   11u     IPv4            1488228      0t0     TCP localhost:ipp (LISTEN)
cupsd   5381 root   12r     FIFO               0,10      0t0 1488229 pipe
cupsd   5381 root   13w     FIFO               0,10      0t0 1488229 pipe
cupsd   5381 root   14r     FIFO               0,10      0t0 1488231 pipe
cupsd   5381 root   15w     FIFO               0,10      0t0 1488231 pipe
cupsd   5381 root   17w     FIFO               0,10      0t0 1488232 pipe
t2s@t2s-X7C-T2:~$

**Comment by narayanan-t2s** [comment]
I've attached the lsof O/P in the following link :

https://pastebin.com/M81DxKib

**Comment by michaelrsweet** [comment]
Hmm, that also looks entirely normal - just listening for connections, no current client connections.

At this point my best advice is to contact Ubuntu directly to see if this is a known issue, or if they have any other tools you can use to track down the memory usage.
