### ISSUE TITLE
/etc/cups/printers.conf lost on reboot

### ISSUE THREAD

**Issue by archenemies** [apple/cups#5626]
I configured three printers on a Raspberry Pi and when I rebooted, `/etc/cups/printers.conf` was empty except for the header:

    # Printer configuration file for CUPS v2.2.1
    # Written by cupsd
    # DO NOT EDIT THIS FILE WHEN CUPSD IS RUNNING

Also, if I recall, `/etc/cups/ppd` was missing or empty.

I'm not sure if this is a CUPS bug, or some other software I installed to try to get my printers working, or a misconfiguration, or something Raspbian-specific.

This erasure has happened a couple of times in the last 24 hours.

Most recently, I am not able to reproduce - in other words I can reboot and the printers are not deleted.

Thank you.

**Comment by michaelrsweet** [comment]
Please report this to the Raspian developers...

**Comment by archenemies** [comment]
It might be more correct to close this bug as "not reproducible" rather than suspecting Raspbian, because I recall the `printers.conf.O` file contained the original version of the configuration file. My conclusion was that the problem came about because of CUPS's ability to modify its own configuration files. Something like #3715, or [this thread](https://lists.debian.org/debian-printing/2015/08/msg00041.html) which suggests

> To prevent Cups from deleting printers I had set printers.conf to immutable (chattr +i /etc/cups/printers.conf).

If you really think it is a problem in Raspbian, then you could offer a possible mechanism for how Raspbian caused this to happen.
