### ISSUE TITLE
No suitable destination host found by cups-browsed

### ISSUE THREAD

**Issue by sandroxGH** [apple/cups#5629]
I'm using RPI2 for share the printer with CUPS, on RPI is running Raspbian V stretch 9.9 , CUPS version is 2.2.1-8 and the printer is one Epson stylus SX110
When i send a print job on local CUPS browse ( my laptop with debian 9) on printer state I see "No suitable destination host found by cups-browsed." if send the job more than one time the job arrive to the server or some time i need to restart the service on the server to allow it.
When it happen on server typing "lsusb" the printer in recognized, and cups is running.
I've try to find some help on internet and I've follow some guide but ith out succes. some one can help me

**Comment by michaelrsweet** [comment]
cups-browsed is part of the [cups-filters](https://github.com/openprinting/cups-filters) project, *not* CUPS...
