### ISSUE TITLE
/printers not return printers anymore

### ISSUE THREAD

**Issue by vaurat** [apple/cups#5631]
Hello, 
A bit like the one filed by https://github.com/xinix00  in https://github.com/apple/cups/issues/5279.
With CUPS 2.2.1, the printers are no longer returned by the following request as it did in version 1.7.5 : 
```
POST /printers HTTP/1.1
Transfer-Encoding: chunked
Content-Type: application/ipp
Host: 10.116.116.230:631
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.2 (Java/1.8.0_222)
Accept-Encoding: gzip,deflate

..@......G..attributes-charset..utf-8H..attributes-natural-language..en-usE..printer-uri..http://10.116.116.230/printersB..requesting-user-name..D..requested-attributes..copies-supportedD....page-ranges-supportedD....printer-nameD....printer-infoD....printer-locationD....printer-make-and-modelD....printer-uri-supportedD....media-supportedD...
media-defaultD....sides-supportedD...
sides-defaultD....orientation-requested-supportedD....printer-resolution-supportedD....printerD....printer-resolution-defaultD....number-up-defaultD....number-up-supportedD....document-format-supportedD....print-color-mode-supportedD....print-color-mode-default.
```
We saw in commits that the insider function cupsGetPrinters was deprecated but we do not understand the changes it implies in HTTP API.
FYI, we use the latest cupsClient cups4j 0.7.6 implementation. (https://github.com/harwey/cups4j)

What are we doing wrong ? For example, is there an new API for the cupsGetDests ?

**Comment by michaelrsweet** [comment]
@vaurat We need to see the binary message you are sending, the response that cupsd is sending, and a debug log (cupsctl --debug-logging, then do your request) to see what cupsd is seeing and responding with.

**Comment by vaurat** [comment]
After a few tests, when i'm tunnelling the port 631 on the distant server, i can use it using localhost:631. This way i have the printer-attributes-tag returned.
but just changing the URL from localhost:631 to the IP:631 the HTTP 200 response does not return these printer-attributes-tag
here are the two cases captured : [cups-2-2-1_cups4j-0-7-6.zip](https://github.com/apple/cups/files/3525564/cups-2-2-1_cups4j-0-7-6.zip)

here is the error.log in the case of the distant call :

> D [21/Aug/2019:15:35:15 +0200] [Client 37] Server address is "10.116.116.230".
> D [21/Aug/2019:15:35:15 +0200] [Client 37] Accepted from 10.116.116.81:34872 (IPv4)
> D [21/Aug/2019:15:35:15 +0200] [Client 37] Waiting for request.
> I [21/Aug/2019:15:35:15 +0200] Expiring subscriptions...
> D [21/Aug/2019:15:35:15 +0200] Report: clients=2
> D [21/Aug/2019:15:35:15 +0200] Report: jobs=4
> D [21/Aug/2019:15:35:15 +0200] Report: jobs-active=0
> D [21/Aug/2019:15:35:15 +0200] Report: printers=2
> D [21/Aug/2019:15:35:15 +0200] Report: stringpool-string-count=2895
> D [21/Aug/2019:15:35:15 +0200] Report: stringpool-alloc-bytes=8448
> D [21/Aug/2019:15:35:15 +0200] Report: stringpool-total-bytes=55112
> D [21/Aug/2019:15:35:15 +0200] [Client 37] POST /printers HTTP/1.1
> D [21/Aug/2019:15:35:15 +0200] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"
> D [21/Aug/2019:15:35:15 +0200] [Client 37] Read: status=200
> D [21/Aug/2019:15:35:15 +0200] [Client 37] No authentication data provided.
> D [21/Aug/2019:15:35:15 +0200] [Client 37] 1.1 CUPS-Get-Printers 1
> D [21/Aug/2019:15:35:15 +0200] CUPS-Get-Printers http://10.116.116.230/printers
> D [21/Aug/2019:15:35:15 +0200] [Client 37] Returning IPP successful-ok for CUPS-Get-Printers (http://10.116.116.230/printers) from 10.116.116.81
> D [21/Aug/2019:15:35:15 +0200] [Client 37] Content-Length: 75
> D [21/Aug/2019:15:35:15 +0200] [Client 37] cupsdSendHeader: code=200, type="application/ipp", auth_type=0
> D [21/Aug/2019:15:35:15 +0200] [Client 37] con->http=0x55fd9c49b5f0
> D [21/Aug/2019:15:35:15 +0200] [Client 37] cupsdWriteClient error=0, used=0, state=HTTP_STATE_POST_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=75, response=0x55fd9c49eaf0(IPP_STATE_DATA), pipe_pid=0, file=-1
> D [21/Aug/2019:15:35:15 +0200] [Client 37] Writing IPP response, ipp_state=IPP_STATE_DATA, old wused=0, new wused=0
> D [21/Aug/2019:15:35:15 +0200] [Client 37] bytes=0, http_state=0, data_remaining=75
> D [21/Aug/2019:15:35:15 +0200] [Client 37] Flushing write buffer.
> D [21/Aug/2019:15:35:15 +0200] [Client 37] New state is HTTP_STATE_WAITING
> D [21/Aug/2019:15:35:15 +0200] [Client 37] Waiting for request.
> D [21/Aug/2019:15:35:15 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
> D [21/Aug/2019:15:35:15 +0200] [Client 37] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
> D [21/Aug/2019:15:35:15 +0200] [Client 37] Closing connection.
> D [21/Aug/2019:15:35:15 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
> D [21/Aug/2019:15:35:15 +0200] [Client 38] Server address is "10.116.116.230".
> D [21/Aug/2019:15:35:15 +0200] [Client 38] Accepted from 10.116.116.81:34874 (IPv4)
> D [21/Aug/2019:15:35:15 +0200] [Client 38] Waiting for request.
> D [21/Aug/2019:15:35:15 +0200] [Client 38] POST /printers HTTP/1.1
> D [21/Aug/2019:15:35:15 +0200] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"
> D [21/Aug/2019:15:35:15 +0200] [Client 38] Read: status=200
> D [21/Aug/2019:15:35:15 +0200] [Client 38] No authentication data provided.
> D [21/Aug/2019:15:35:15 +0200] [Client 38] 1.1 CUPS-Get-Default 2
> D [21/Aug/2019:15:35:15 +0200] CUPS-Get-Default http://10.116.116.230/printers
> D [21/Aug/2019:15:35:15 +0200] CUPS-Get-Default client-error-not-found: No default printer.
> D [21/Aug/2019:15:35:15 +0200] [Client 38] Returning IPP client-error-not-found for CUPS-Get-Default (http://10.116.116.230/printers) from 10.116.116.81
> D [21/Aug/2019:15:35:15 +0200] [Client 38] Content-Length: 113
> D [21/Aug/2019:15:35:15 +0200] [Client 38] cupsdSendHeader: code=200, type="application/ipp", auth_type=0
> D [21/Aug/2019:15:35:15 +0200] [Client 38] con->http=0x55fd9c49b5f0
> D [21/Aug/2019:15:35:15 +0200] [Client 38] cupsdWriteClient error=0, used=0, state=HTTP_STATE_POST_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=113, response=0x55fd9c49e920(IPP_STATE_DATA), pipe_pid=0, file=-1
> D [21/Aug/2019:15:35:15 +0200] [Client 38] Writing IPP response, ipp_state=IPP_STATE_DATA, old wused=0, new wused=0
> D [21/Aug/2019:15:35:15 +0200] [Client 38] bytes=0, http_state=0, data_remaining=113
> D [21/Aug/2019:15:35:15 +0200] [Client 38] Flushing write buffer.
> D [21/Aug/2019:15:35:15 +0200] [Client 38] New state is HTTP_STATE_WAITING
> D [21/Aug/2019:15:35:15 +0200] [Client 38] Waiting for request.
> D [21/Aug/2019:15:35:15 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
> D [21/Aug/2019:15:35:15 +0200] [Client 38] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
> D [21/Aug/2019:15:35:15 +0200] [Client 38] Closing connection.
> D [21/Aug/2019:15:35:15 +0200] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
> I [21/Aug/2019:15:35:16 +0200] Expiring subscriptions...

i hope these details may help.

**Comment by michaelrsweet** [comment]
You can't tunnel over SSH without configuring the remote server to accept alternate Host: headers (more specifically the local IP address you are using to tunnel). "localhost" cannot be used on addresses other than loopback (127.0.0.1 and ::1) for security reasons, so you'll need to either allow the specific local IP address or all addresses with the ServerAlias configuration directive on the server, for example:

    ServerAlias *

to allow any remote address or:

    ServerAlias ip-address

for a specific remote address.

Keep in mind that such a configuration is 100% NOT SUPPORTED and WILL have problems because the ssh tunnel presents *2* different addresses, only one of which the local cupsd knows about.
