### ISSUE TITLE
backend usb claim interface returns Cannot allocate memory

### ISSUE THREAD

**Issue by liuxiaomeng2270** [apple/cups#5632]
HI
I'm a pringer driver developer on linux, my dirver send data to printer via CUPS backend "usb". When I printing a Job via a USB printer, the printer do not print anything, the job still exist in the line. 
One condition shows the error：
The error_log shows [Job 146] Failed to claim interface 0 for vid:pid : Cannot allocate memory.
                                 [Job 146] Waiting for printer to beclom available.
Another condition shows the error：
                                [Job 11] Unable to send data to printer.
These errors shows accidently, not usually.
The printer still print nothing.
On which conditions the backend will show the error? 
How can I fix this error?
THX

**Comment by michaelrsweet** [comment]
As the code producing this error is not part of CUPS, I cannot say exactly what might be causing this error. My guess is that another device driver is claiming the printer, preventing libusb from accessing the interface...
