### ISSUE TITLE
Why use pwgMediaForPPD() in _ppdCacheCreateWithPPD()?

### ISSUE THREAD

**Issue by j39m** [apple/cups#5633]
This is a multi-part question prompted by a PPD containing the following `PaperDimension`s:
```
*PaperDimension B5/B5 (176 x 250 mm): "499 709"
*PaperDimension JISB5/JIS B5 (182 x 257 mm): "516 729"
```

Passing such a PPD under `cupstestppd` shows these warnings:
```
        WARN    Size "B5" should be the Adobe standard name "ISOB5".
        WARN    Size "JISB5" should be the Adobe standard name "B5".
```

CUPS writes the PPD cache with these `Size` specifications:
```
Size jis_b5_182x257mm B5 17604 25012 400 400 400 400
Size om_jisb-5_182.03x257.18mm JISB5 18203 25718 400 400 400 400
```

We have received user feedback reports that selecting either of these media to print with causes the printer to print in JIS B5; the ISO B5 (176x250mm) size is unpickable.

CUPS chooses to represent that B5 `PaperDimension` because it [calls pwgMediaForPPD()](https://github.com/apple/cups/blob/f4b0bfa2db37f134e1708cbbf4c81bb6774426bc/cups/ppd-cache.c#L1078) and gets the JIS size out of it. It won't find the ISO B5 size because it [calls _pwgMediaNearSize()](https://github.com/apple/cups/blob/f4b0bfa2db37f134e1708cbbf4c81bb6774426bc/cups/ppd-cache.c#L1124) with `epsilon = 0` (17604 != 17600; 25012 != 25000). Even if we increase the epsilon, the [selected PWG vendor ID will still only reflect what pwgMediaForPPD() initially chose](https://github.com/apple/cups/blob/f4b0bfa2db37f134e1708cbbf4c81bb6774426bc/cups/ppd-cache.c#L1186). I assume this could confuse the printer down the line.

1. Why does `_ppdCacheCreateWithPPD()` attach importance to the stated PPD media name? Can we get away with matching by size only?
1. Why choose `epsilon = 0` when calling `_pwgMediaNearSize()`? Can we get away with [a higher epsilon as `cupstestppd` does](https://github.com/apple/cups/blob/f4b0bfa2db37f134e1708cbbf4c81bb6774426bc/systemv/cupstestppd.c#L3259)?

**Comment by michaelrsweet** [comment]
I will need to do some digging on this; there was a reason but I don't remember it offhand... :/

**Comment by michaelrsweet** [comment]
Well, changing to pwgMediaForSize seems to work, so let's go with it...

**Comment by michaelrsweet** [comment]
[master 9240cd70a] Use pwgMediaForSize when looking up PPD sizes (Issue #5633)
