### ISSUE TITLE
Ubuntu 19.04 Epson TX135 Printing problems with fonts

### ISSUE THREAD

**Issue by xykogm** [apple/cups#5634]
Sorry for my poor english. My Epson TX135 stops printing text after upgrade to Ubuntu 19.04 from Ubuntu 18.10. It only prints images. Reinstalled drivers from Epson`s support site, removed the printer and added it again but no success. Thanks for any help.

**Comment by michaelrsweet** [comment]
This is probably a Ghostscript or cups-filters issue - please report this upstream to the Ubuntu folks...
