### ISSUE TITLE
Changes committed 7 months ago not in new release

### ISSUE THREAD

**Issue by scootergrisen** [apple/cups#5636]
7 months ago https://github.com/apple/cups/commit/0210d14387d552eaf0fb9f32a3558c35fb3f99df was included in cups.desktop.in but now in CUPS 2.2.12 it is not included.

Why is it not included?

**Comment by scootergrisen** [comment]
Same with templates.
da is not inlcuded in release even though it is in https://github.com/apple/cups/tree/master/templates

**Comment by scootergrisen** [comment]
And doc/da also not included: https://github.com/apple/cups/tree/master/doc
So i guess nothing i have translated is included in the release.

**Comment by michaelrsweet** [comment]
They are included in CUPS 2.3 (master) and not in the2.2 branch. CUPS 2.3.0 should be coming out in another week or so.

**Comment by scootergrisen** [comment]
They are still not included in 2.3.0.

**Comment by scootergrisen** [comment]
I created https://github.com/apple/cups/issues/5651

**Comment by michaelrsweet** [comment]
Huh, I definitely see the Danish files in 2.3.0 and Git master, am I missing something?

**Comment by scootergrisen** [comment]
They are in the source but not in the packages i can install e.g. in Debian.
