### ISSUE TITLE
CUPS 2.2.12: Choice name "custom" not allowed any more

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5639]
On Ubuntu I have updated to CUPS 2.2.12 for Eoan (19.10) and found out that the PPD file `HP-Color_LaserJet_CM3530_MFP-PDF.ppd` of the sample PPDs of cups-filters is not accepted by CUPS any more (also fails `cupstestppd`) due to the fact that one of the choices of the option "stapleoption" was named "custom".
This case was no big problem as as upstream maintainer of cups-filters I could simply [change it to "customsize"](https://github.com/OpenPrinting/cups-filters/commit/25a2c155f44) (included in the 1.25.3 release of cups-filters) but there seem to be many other PPD files out there in the wild which have an option choice named "custom". For example there are PPD files in HPLIP with this problem, as shown in [Debian bug #935918](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=935918).
Why is "custom" not allowed any more as option choice name from 2.2.12 on? For supporting custom options of CUPS only "custom.<VALUE>" is needed, not the simple "custom". Also 2.2.12 is a micro release, it should not have such kind of change.

**Comment by debiantriage** [comment]
Debian bug #935918 does not exist. Is there a revised URL?

-- 
Brian.

**Comment by debiantriage** [comment]
#935918  does exist but #9359180 is what is given when the link is clicked on.

-- 
Brian.

**Comment by zdohnal** [comment]
Users encountered the issue on Fedora too https://bugzilla.redhat.com/show_bug.cgi?id=1750904 .

**Comment by michaelrsweet** [comment]
[master 2a06655e5] PPD files containing custom option keywords did not work (Issue #5639)
