### ISSUE TITLE
systemd doesn't actually support launch-on-demand services, need to fake it

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5640]
I have updated the upcoming Ubuntu 19.10 to CUPS 2.2.12 and now I cannot do quick configuration changes with `cupsctl` any more.
When I run
```
$ cupsctl --share-printers
```
or
```
$ cupsctl --no-share-printers
```
I cannot access CUPS any more:
```
$ cupsctl
cupsctl: Unable to connect to server: Bad file descriptor
$ lpstat -v
lpstat: Bad file descriptor
$ 
```
I have to restart the daemon to get access again. At least then the configuration change gets effective:
```
$ sudo systemctl restart cups
$ cupsctl
_debug_logging=1
_remote_admin=0
_remote_any=0
_share_printers=0
_user_cancel_any=1
[...]
```
Here are my config files and error_log (in debug mode):
[cupsd.conf.txt](https://github.com/apple/cups/files/3548103/cupsd.conf.txt)
[cups-files.conf.txt](https://github.com/apple/cups/files/3548104/cups-files.conf.txt)
[error_log.txt](https://github.com/apple/cups/files/3548121/error_log.txt)

**Comment by zdohnal** [comment]
I can confirm this is the same issue as it is in Fedora 30+ where I built cups-2.2.12. Here are the logs from journal 
[cupsd_log.txt](https://github.com/apple/cups/files/3579299/cupsd_log.txt) - it mostly the same log as Till has, but there are few messages from systemd itself.
It works as before after downgrade to 2.2.11.

**Comment by zdohnal** [comment]
This commit seems to cause it:
"The scheduler would restart continuously when idle and printers were not shared (rdar://52561199)"

Specifically this part:

--- a/scheduler/main.c
+++ b/scheduler/main.c
@@ -756,7 +756,10 @@ main(int  argc,                            /* I - Number of command-line args */
 
 #ifdef HAVE_ONDEMAND
        if (OnDemand)
+       {
+         stop_scheduler = 1;
          break;
+       }
 #endif /* HAVE_ONDEMAND */
 
         DoingShutdown = 1;

**Comment by zdohnal** [comment]
It is only new assignment to stop_scheduler since 2.2.11 and setting it to 1 causes cupsd to end correctly, which breaks usage of cupsctl - cupsd ended as 'failure' before that and systemd restarted it.

**Comment by michaelrsweet** [comment]
Looks like a regression caused by c1a310ffdcd143c0e054921d416ad4ad16aa7d0a.

**Comment by michaelrsweet** [comment]
OK, so looking at the systemd documentation (ugh!) it looks like we need to return an error exit code in order for systemd to restart cupsd... There is no real support for idle exiting or minimizing the number of processes that are running... :/

**Comment by michaelrsweet** [comment]
Pushed changes reverting the "stop_scheduler" change for systemd:

[master f8688d733] Add workaround for systemd's lack of true launch-on-demand support (Issue #5640)

[branch-2.2 40a54a37a] Add workaround for systemd's lack of true launch-on-demand support (Issue #5640)

For all other supervisor programs supported by cupsd we can just exit with no error and the right thing happens - immediate restart if the "I need to be running" file is present, otherwise an on-demand restart if a socket connection is made. Why systemd doesn't support this pattern is baffling...

**Comment by tillkamppeter** [comment]
Thank you very much, it works correctly now. I have backported the patch to Ubuntu Eoan (19.10) now.

**Comment by xuiqzy** [comment]
@michaelrsweet Sorry if I misunderstood the issue, but are you looking for a way for systemd to restart the service, even when it exits cleanly? I think there is a config option `Restart=always` for that, see the table here: https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=
