### ISSUE TITLE
CUPS 2.2.12: Any get-printer-attributes IPP request fails

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5641]
If I run
```
ipptool -tv ipp://till-x1yoga.local:631/printers/<queue> get-printer-attributes.test
```
for any local print queue with PPD file I get a [FAIL] in the output and the command exits with status 1. The get-printer-attributes response itself does not show anything wrong. There are also no "EXPECTED:" lines in the output telling about what could be wrong.
It does not matter whether I use "localhost" or the network host name of my local machine in the URIs.

**Comment by tillkamppeter** [comment]
For me it looks more like a problem of ipptool and not of CUPS, as I have tried on a VM running CUPS 2.2.10 now and get the same result. The answer to the get-printer-attributes IPP request always looks absolutely correct and there is also always the "status-code = successful-ok (successful-ok)" in the beginning. The "[FAIL]" should mean that ipptool has judged that this request has failed, one can only not see why ipptool thinks that this answer is bad.

**Comment by tillkamppeter** [comment]
Here is an example of CUPS 2.2.12:
Command line
```
ipptool -tv ipp://localhost:631/printers/HP_OfficeJet_Pro_8730 get-printer-attributes.test > ipptool-out.txt
```
Related logs/PPD file:
- [error_log.txt](https://github.com/apple/cups/files/3550510/error_log.txt)
- [HP_OfficeJet_Pro_8730.ppd.txt](https://github.com/apple/cups/files/3550511/HP_OfficeJet_Pro_8730.ppd.txt)
- [ipptool-out.txt](https://github.com/apple/cups/files/3550512/ipptool-out.txt)

**Comment by tillkamppeter** [comment]
I have looked into the output again and I have seen in the end what could have caused the "[FAIL]":
```
        Duplicate "pwg-raster-document-type-supported" attribute in printer-attributes-tag group
        Duplicate "pwg-raster-document-resolution-supported" attribute in printer-attributes-tag group
```
and indeed these two attributes are reported twice:
```
        pwg-raster-document-resolution-supported (1setOf resolution) = 150dpi,300dpi,600dpi
        pwg-raster-document-sheet-back (keyword) = normal
        pwg-raster-document-type-supported (1setOf keyword) = adobergb-8,adobergb-16,black-1,black-8,black-16,cmyk-8,cmyk-16,rgb-8,rgb-16,sgray-1,sgray-8,sgray-16,srgb-8,srgb-16
[...]
        pwg-raster-document-type-supported (1setOf keyword) = black_1,sgray_8
        printer-resolution-supported (1setOf resolution) = 150dpi,300dpi,600dpi
        pwg-raster-document-resolution-supported (resolution) = 150dpi
```
and even worse, with different values and the resolutions even do not match "printer-resolution-supported" in both cases.
Looks like a bug in CUPS as the answers are provided by the local CUPS daemon.

**Comment by tillkamppeter** [comment]
A suggestions: The output of ipptool should not show error/warning messages with the same indentation as the answer to the IPP request, or with a blank line between the answer and the messages.

**Comment by prlw1** [comment]
I saw the "Cannot Reproduce" label, so just pointed a ipptool from cups 2.2.12 at a local printer with a PPD, and sure enough
```
    Get printer attributes using Get-Printer-Attributes                  [FAIL]
```

**Comment by michaelrsweet** [comment]
These attributes are added exactly once in scheduler/printers.c (load_ppd). And like I said, I can't reproduce the bug on any of my systems. Please verify that this isn't being caused by some patch you have applied to the stock CUPS sources.

**Comment by tillkamppeter** [comment]
OK, I have investigated again and it is indeed a patch. I asked the Debian guys for removing it now.

**Comment by tillkamppeter** [comment]
Patch is removed now in the cups-2.3.1-2 Debian and Ubuntu packages.
