### ISSUE TITLE
libcups does not initialize defaults in some cases

### ISSUE THREAD

**Issue by tillkamppeter** [apple/cups#5642]
I am using CUPS 2.2.12 on Ubuntu Eoan.
Attached is a sample C program testinit.c, to be compiled with
```
gcc -o testinit testinit.c -lcups
```
It demonstrates that the internal global data structure cg of libcups in some cases gets used but not initialized.
The program creates a destination record, connects to the CUPS daemon according to the printer URI of the destination and then request the destination info (here CUPS is supposed to do a get-printer-attributes IPP request on the printer URI).
When one calls the program with the name of an existing CUPS printer as argument, for example
```
./testinit Printer
```
it should display the IPP attributes of the CUPS queue, but in reality it tells that the queue does not exist. When looking into error_log (in debug mode) one sees that a get-printer-attributes IPP request is done, but to "file:/dev/null" (the device URI in the destination record) and not to the printer URI.
The code of the cupsCopyDestInfo() function contains:
```
  if (!http)
  {
    DEBUG_puts("1cupsCopyDestInfo: Default server connection.");
    http   = _cupsConnect();
    dflags = CUPS_DEST_FLAGS_NONE;
  }
#ifdef AF_LOCAL
  else if (httpAddrFamily(http->hostaddr) == AF_LOCAL)
  {
    DEBUG_puts("1cupsCopyDestInfo: Connection to server (domain socket).");
    dflags = CUPS_DEST_FLAGS_NONE;
  }
#endif /* AF_LOCAL */
  else if ((strcmp(http->hostname, cg->server) && cg->server[0] != '/') || cg->ipp_port != httpAddrPort(http->hostaddr))
  {
    DEBUG_printf(("1cupsCopyDestInfo: Connection to device (%s).", http->hostname));
    dflags = CUPS_DEST_FLAGS_DEVICE;
  }
  else
  {
    DEBUG_printf(("1cupsCopyDestInfo: Connection to server (%s).", http->hostname));
    dflags = CUPS_DEST_FLAGS_NONE;
  }
```
What happens here is that the first two "if" conditions resolve to false and the third to true, setting dflags to CUPS_DEST_FLAGS_DEVICE and so the device URI being used for the following get-printer-attributes IPP request and that fails.
The third "if" has the condition
```
((strcmp(http->hostname, cg->server) && cg->server[0] != '/') || cg->ipp_port != httpAddrPort(http->hostaddr))
```
If cg->server is "/run/cups/cups.sock" or "localhost" as expected and cg->ipp_port is 631 as expected, this would resolve to false and the last "else" would set dflags to CUPS_DEST_FLAGS_NONE and so the get-printer-attributes IPP request is applied to the CUPS queue.
The only explication that this does not happen is that cg->server contains an arbitrary string and cg->ipp_port and arbitrary number, which makes the condition resolve to true.
If I run my program with an arbitrary second argument, for example
```
./testinit Printer 1
```
it calls the function ippPort() in the very beginning before it calls any other function of libcups. The ippPort() function calls the internal function _cupsSetDefaults() of libcups which populates the cg data structure with the defaults.
It needs to get assured that the cg data structure gets always populated.

The sample program:
[testinit.c.txt](https://github.com/apple/cups/files/3557538/testinit.c.txt)

**Comment by michaelrsweet** [comment]
@tillkamppeter OK, try the same thing but using the cupsGetNamedDest function rather than allocating and initializing the cups_dest_t structure yourself (which BYPASSES all of the normal initializers!)

**Comment by tillkamppeter** [comment]
The original program ([cpdb-backend-cups](https://github.com/OpenPrinting/cpdb-backend-cups), [version 1.1.0](https://github.com/OpenPrinting/cpdb-backend-cups/releases/tag/v1.1.0)) uses  cupsEnumDests() as shown in
[testinit-2.c.txt](https://github.com/apple/cups/files/3571068/testinit-2.c.txt)
but uses an event loop and separate threads, the thread separation of the cupsEnumDests() and the later cupsCopyDestInfo() call probably leads to the cupsCopyDestInfo() call on an uninitialized libcups. In my little test program testinit-2 without multi-threading everything works as intended.

**Comment by michaelrsweet** [comment]
Will push the test program soon, but so far I haven't been able to reproduce the problem you are seeing...

**Comment by michaelrsweet** [comment]
[master cfaaa07a1] Add threading unit test program (Issue #5642)

**Comment by michaelrsweet** [comment]
@tillkamppeter Please test CUPS master's testthreads program and let me know if you can reproduce on your systems...

**Comment by michaelrsweet** [comment]
@tillkamppeter Closing for now; if you are able to reproduce using the testthreads program, please let me know.
