### ISSUE TITLE
Filter Failed PDF Lexmark MX722adhe

### ISSUE THREAD

**Issue by slipttees** [apple/cups#5645]
E [03/Sep/2019:14:25:59 -0300] [Job 11] Job stopped due to filter errors; please consult the error_log file for details.
D [03/Sep/2019:14:25:59 -0300] [Job 11] The following messages were recorded from 14:25:59 to 14:25:59
D [03/Sep/2019:14:25:59 -0300] [Job 11] Adding start banner page "none".
D [03/Sep/2019:14:25:59 -0300] [Job 11] Adding end banner page "none".
D [03/Sep/2019:14:25:59 -0300] [Job 11] File of type application/pdf queued by "secretaria".
D [03/Sep/2019:14:25:59 -0300] [Job 11] hold_until=0
D [03/Sep/2019:14:25:59 -0300] [Job 11] Queued on "Lexmark-MX720" by "secretaria".
D [03/Sep/2019:14:25:59 -0300] [Job 11] time-at-processing=1567531559
D [03/Sep/2019:14:25:59 -0300] [Job 11] 3 filters for job:
D [03/Sep/2019:14:25:59 -0300] [Job 11] pdftopdf (application/pdf to application/vnd.cups-pdf, cost 66)
D [03/Sep/2019:14:25:59 -0300] [Job 11] pdftops (application/vnd.cups-pdf to application/vnd.cups-postscript, cost 100)
D [03/Sep/2019:14:25:59 -0300] [Job 11] /usr/lib/cups/filter/fax-pnh-filter (application/vnd.cups-postscript to printer/Lexmark-MX720, cost 0)
D [03/Sep/2019:14:25:59 -0300] [Job 11] job-sheets=none,none
D [03/Sep/2019:14:25:59 -0300] [Job 11] argv[0]="Lexmark-MX720"
D [03/Sep/2019:14:25:59 -0300] [Job 11] argv[1]="11"
D [03/Sep/2019:14:25:59 -0300] [Job 11] argv[2]="secretaria"
D [03/Sep/2019:14:25:59 -0300] [Job 11] argv[3]="12 PROTOCOLO DE RECEBIMENTO DE DOCUMENTOS e COMPROVANTES.pdf — CARACTERIZAÇÃO DE TURMA / DADOS ESTATÍSTICOS"
D [03/Sep/2019:14:25:59 -0300] [Job 11] argv[4]="1"
D [03/Sep/2019:14:25:59 -0300] [Job 11] argv[5]="noPnH noFaxNumber PageSize=A4 GrayCorrection=PrinterS ColorMode=PrinterS TonerDarkness=PrinterS number-up=1 noLexMirror OutputBin=PrinterS LXResolution=1200dpi InputSlot=Tray1 Halftone=PrinterS noCollate LexBrightness=0 LexContrast=0 SepSource=PrinterS LexPixelBoost=PrinterS LexBlankPage=PrinterS Duplex=None MediaType=PrinterS SepPages=PrinterS job-uuid=urn:uuid:66709312-2b2b-3a13-7c0a-49f7e2cce1a5 job-originating-host-name=localhost date-time-at-creation= date-time-at-processing= time-at-creation=1567531559 time-at-processing=1567531559"
D [03/Sep/2019:14:25:59 -0300] [Job 11] argv[6]="/var/spool/cups/d00011-001"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[0]="CUPS_CACHEDIR=/var/cache/cups"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[1]="CUPS_DATADIR=/usr/share/cups"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[2]="CUPS_DOCROOT=/usr/share/cups/doc-root"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[3]="CUPS_FONTPATH=/usr/share/cups/fonts"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[4]="CUPS_REQUESTROOT=/var/spool/cups"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[5]="CUPS_SERVERBIN=/usr/lib/cups"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[6]="CUPS_SERVERROOT=/etc/cups"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[7]="CUPS_STATEDIR=/var/run/cups"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[8]="HOME=/var/spool/cups/tmp"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[9]="PATH=/usr/lib/cups/filter:/usr/bin:/usr/sbin:/bin:/usr/bin"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[10]="SERVER_ADMIN=root@23142361-936963"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[11]="SOFTWARE=CUPS/2.1.3"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[12]="TMPDIR=/var/spool/cups/tmp"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[13]="USER=root"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[14]="CUPS_MAX_MESSAGE=2047"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[15]="CUPS_SERVER=/var/run/cups/cups.sock"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[16]="CUPS_ENCRYPTION=IfRequested"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[17]="IPP_PORT=631"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[18]="CHARSET=utf-8"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[19]="LANG=pt_BR.UTF-8"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[20]="PPD=/etc/cups/ppd/Lexmark-MX720.ppd"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[21]="RIP_MAX_CACHE=128m"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[22]="CONTENT_TYPE=application/pdf"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[23]="DEVICE_URI=socket://20.20.2.1"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[24]="PRINTER_INFO=Lexmark MX720"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[25]="PRINTER_LOCATION=SALA SERVIDOR"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[26]="PRINTER=Lexmark-MX720"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[27]="PRINTER_STATE_REASONS=none"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[28]="CUPS_FILETYPE=document"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[29]="FINAL_CONTENT_TYPE=application/vnd.cups-postscript"
D [03/Sep/2019:14:25:59 -0300] [Job 11] envp[30]="AUTH_I****"
D [03/Sep/2019:14:25:59 -0300] [Job 11] Started filter /usr/lib/cups/filter/pdftopdf (PID 15428)
D [03/Sep/2019:14:25:59 -0300] [Job 11] Started filter /usr/lib/cups/filter/pdftops (PID 15429)
D [03/Sep/2019:14:25:59 -0300] [Job 11] Started filter /usr/lib/cups/filter/fax-pnh-filter (PID 15430)
D [03/Sep/2019:14:25:59 -0300] [Job 11] Started backend /usr/lib/cups/backend/socket (PID 15431)
D [03/Sep/2019:14:25:59 -0300] [Job 11] pdftops - copying to temp print file \"/tmp/03c455d79ec02\"
D [03/Sep/2019:14:25:59 -0300] [Job 11] /bin/sed: -e expressão #3, caractere 146: Opção desconhecida para o comando `s\' (s///?)
D [03/Sep/2019:14:25:59 -0300] [Job 11] PID 15430 (/usr/lib/cups/filter/fax-pnh-filter) stopped with status 1.
D [03/Sep/2019:14:25:59 -0300] [Job 11] Hint: Try setting the LogLevel to "debug" to find out more.
D [03/Sep/2019:14:25:59 -0300] [Job 11] STATE: +connecting-to-device
D [03/Sep/2019:14:25:59 -0300] [Job 11] Looking up \"20.20.2.1\"...
D [03/Sep/2019:14:25:59 -0300] [Job 11] backendWaitLoop(snmp_fd=7, addr=0x557f0e9436d8, side_cb=0x557f0d11f000)
D [03/Sep/2019:14:25:59 -0300] [Job 11] PID 15431 (/usr/lib/cups/backend/socket) exited with no errors.
D [03/Sep/2019:14:25:59 -0300] [Job 11] PID 15428 (/usr/lib/cups/filter/pdftopdf) exited with no errors.
D [03/Sep/2019:14:25:59 -0300] [Job 11] Printer make and model: Lexmark Lexmark MX722adhe
D [03/Sep/2019:14:25:59 -0300] [Job 11] Running command line for pstops: pstops 11 secretaria \'12 PROTOCOLO DE RECEBIMENTO DE DOCUMENTOS e COMPROVANTES.pdf — CARACTERIZAÇÃO DE TURMA / DADOS ESTATÍSTICOS\' 1 \'noPnH noFaxNumber PageSize=A4 GrayCorrection=PrinterS ColorMode=PrinterS TonerDarkness=PrinterS noLexMirror OutputBin=PrinterS LXResolution=1200dpi InputSlot=Tray1 Halftone=PrinterS LexBrightness=0 LexContrast=0 SepSource=PrinterS LexPixelBoost=PrinterS LexBlankPage=PrinterS Duplex=None MediaType=PrinterS SepPages=PrinterS job-uuid=urn:uuid:66709312-2b2b-3a13-7c0a-49f7e2cce1a5 job-originating-host-name=localhost date-time-at-creation= date-time-at-processing= time-at-creation=1567531559 time-at-processing=1567531559\'
D [03/Sep/2019:14:25:59 -0300] [Job 11] No resolution information found in the PPD file.
D [03/Sep/2019:14:25:59 -0300] [Job 11] Using image rendering resolution 300 dpi
D [03/Sep/2019:14:25:59 -0300] [Job 11] Running command line for gs: gs -q -dNOPAUSE -dBATCH -dSAFER -sDEVICE=ps2write -sOUTPUTFILE=%stdout -dLanguageLevel=3 -r300 -dCompressFonts=false -dNoT3CCITT -dNOINTERPOLATE -c \'save pop\' -f /tmp/03c455d79ec02
D [03/Sep/2019:14:25:59 -0300] [Job 11] Started filter gs (PID 15438)
D [03/Sep/2019:14:25:59 -0300] [Job 11] Started filter pstops (PID 15439)
D [03/Sep/2019:14:25:59 -0300] [Job 11] Page = 595x842; 10,12 to 589,830
D [03/Sep/2019:14:25:59 -0300] [Job 11] slow_collate=0, slow_duplex=0, slow_order=0
D [03/Sep/2019:14:25:59 -0300] [Job 11] Before copy_comments - %!PS-Adobe-3.0
D [03/Sep/2019:14:25:59 -0300] [Job 11] %!PS-Adobe-3.0
D [03/Sep/2019:14:25:59 -0300] [Job 11] %%BoundingBox: 0 0 596 842
D [03/Sep/2019:14:25:59 -0300] [Job 11] %%HiResBoundingBox: 0 0 596.00 842.00
D [03/Sep/2019:14:25:59 -0300] [Job 11] %%Creator: GPL Ghostscript 926 (ps2write)
D [03/Sep/2019:14:25:59 -0300] [Job 11] %%LanguageLevel: 2
D [03/Sep/2019:14:25:59 -0300] [Job 11] %%CreationDate: D:20190903142559-03\'00\'
D [03/Sep/2019:14:25:59 -0300] [Job 11] %%Pages: 2
D [03/Sep/2019:14:25:59 -0300] [Job 11] %%EndComments
D [03/Sep/2019:14:25:59 -0300] [Job 11] Before copy_prolog - %%BeginProlog
D [03/Sep/2019:14:25:59 -0300] [Job 11] Before copy_setup - %%Page: 1 1
D [03/Sep/2019:14:25:59 -0300] [Job 11] Before page loop - %%Page: 1 1
D [03/Sep/2019:14:25:59 -0300] [Job 11] Copying page 1...
D [03/Sep/2019:14:25:59 -0300] [Job 11] pagew = 579.0, pagel = 818.0
D [03/Sep/2019:14:25:59 -0300] [Job 11] bboxx = 0, bboxy = 0, bboxw = 595, bboxl = 842
D [03/Sep/2019:14:25:59 -0300] [Job 11] PageLeft = 10.0, PageRight = 589.0
D [03/Sep/2019:14:25:59 -0300] [Job 11] PageTop = 830.0, PageBottom = 12.0
D [03/Sep/2019:14:25:59 -0300] [Job 11] PageWidth = 595.0, PageLength = 842.0
D [03/Sep/2019:14:25:59 -0300] [Job 11] Copying page 2...
D [03/Sep/2019:14:25:59 -0300] [Job 11] pagew = 579.0, pagel = 818.0
D [03/Sep/2019:14:25:59 -0300] [Job 11] bboxx = 0, bboxy = 0, bboxw = 595, bboxl = 842
D [03/Sep/2019:14:25:59 -0300] [Job 11] PageLeft = 10.0, PageRight = 589.0
D [03/Sep/2019:14:25:59 -0300] [Job 11] PageTop = 830.0, PageBottom = 12.0
D [03/Sep/2019:14:25:59 -0300] [Job 11] PageWidth = 595.0, PageLength = 842.0
D [03/Sep/2019:14:25:59 -0300] [Job 11] Wrote 2 pages...
D [03/Sep/2019:14:25:59 -0300] [Job 11] PID 15439 (pstops) exited with no errors.
D [03/Sep/2019:14:25:59 -0300] [Job 11] PID 15438 (gs) exited with no errors.
D [03/Sep/2019:14:25:59 -0300] [Job 11] PID 15429 (/usr/lib/cups/filter/pdftops) exited with no errors.
D [03/Sep/2019:14:25:59 -0300] [Job 11] End of messages
D [03/Sep/2019:14:25:59 -0300] [Job 11] printer-state=3(idle)
D [03/Sep/2019:14:25:59 -0300] [Job 11] printer-state-message="Filter failed"
D [03/Sep/2019:14:25:59 -0300] [Job 11] printer-state-reasons=none

**Comment by debiantriage** [comment]
When using a modern printer, a wise printer admin would see the writing is on the wall for vendor-supplied drivers and take a route like

`lpadmin -p myprinter -v ipp://... -E -m everywhere`

or, on Debian,

 [https://wiki.debian.org/QuickPrintQueuesCUPS](url)

Less work for everyone.

**Comment by michaelrsweet** [comment]
@slipttees On a less confrontational note, the error is coming from the printer driver, not anything in CUPS or cups-filters. In particular:

    D [03/Sep/2019:14:25:59 -0300] [Job 11] /bin/sed: -e expressão #3, caractere 146: Opção desconhecida para o comando `s' (s///?)

points to a bug in the `fax-pnh-filter` script.

**Comment by debiantriage** [comment]
When I wrote my comment I did not view it as "confrontational" but as advice to take a different route to printing with this device. Perhaps it will lead to that; perhaps it won't. I can  see how my words could be interpreted but my intention was to get the user printing.

-- 
Brian.

**Comment by paulmenzel** [comment]
We experienced the same problem. My colleagues analyzed it, and the failing print job name had a slash in it, causing the script to fail.

    D [24/Jul/2020:11:22:55 +0200] [Job 8469] /bin/sed: -e expression #3, char 103: unknown option to `s\'
    D [24/Jul/2020:11:22:55 +0200] [Job 8469] PID 10653 (/package/tonerlow/cups-2.2.11/lib/cups/filter/fax-pnh-filter) stopped with status 1.

You seem to have something similar.

    D [03/Sep/2019:14:25:59 -0300] [Job 11] /bin/sed: -e expressão #3, caractere 146: Opção desconhecida para o comando `s' (s///?)
    D [03/Sep/2019:14:25:59 -0300] [Job 11] PID 15430 (/usr/lib/cups/filter/fax-pnh-filter) stopped with status 1.

We escaped the slashes as a workaround, and informed Lexmark.

     - myjob=`echo "$3" | sed -e 's|&|\\\&|g' | sed -e "s|\"|'|g"`
     + myjob=`echo "$3" | sed -e 's|&|\\\&|g' | sed -e "s|\"|'|g" | sed -e 's|/|\/|g'`
