### ISSUE TITLE
[Request] I think, in cupsSetDests(), event notification would be required.

### ISSUE THREAD

**Issue by ChoiChoongHo94** [apple/cups#5646]
CUPS version: 2.2.10

Hi.

When the default printer of an user(not root) is changed or set, any event is not emitted.

In a similar case, if I set a default printer using `lpoptions -d` command (i.e. modify `~/.cups/lpoptions`), any event is not emitted.
But, using `lpadmin -d` command (i.e. modify `/etc/cups/lpoptions`), `printer-state-changed` event is emitted.

I think that, in the former case, `printer-modified` or `printer-state-changed` event should be emitted.

Thank you.

**Comment by michaelrsweet** [comment]
lpoptions/cupsSetDests manipulate client-side defaults, while lpadmin manipulates server-side defaults. Notifications are only triggered by server-side changes (because it is the server generating the notification).

So no, we won't be sending an event for client-side changes...

**Comment by ChoiChoongHo94** [comment]
but, when I saw cupsSetDests code, there was an event notification code of Apple.
Then, does it mean that the event notification for client-side changes is also needed on other platform???
