### ISSUE TITLE
Unable to fetch destInfo on iOS

### ISSUE THREAD

**Issue by thomasnordquist** [apple/cups#5648]
Hi, I am working on printing PDFs (rastered as PWG) via IPP on iOS.

It appears that while retrieving the destInfo `cupsCopyDestInfo(http, destInfo)` the method tries to guess the type of service I'd like to talk to (printer vs cups server?!)

Since my destinations are network printers I would expect that `dflags = CUPS_DEST_FLAGS_DEVICE` would be used but since `cg->server == "/private/var/run/printd"` the else block is used: `dflags = CUPS_DEST_FLAGS_NONE`

https://github.com/apple/cups/blob/3ba95ec48d785979ccfe90516d8fb4567ab81fe0/cups/dest-options.c#L718-L727

On iOS devices and the Simulator `cg->server` defaults to a local socket `/private/var/run/printd` (in case of the iOS device).

I can therefore not retrieve the `destInfo`. Setting cg->server to something else resolves the issue: `cupsSetServer("non-existant-server.localdomain")`.

I am uncertain if :
- I am doing something terribly wrong
- it's a bug
- dflags should be part of the method signature

## Off-Topic
@michaelrsweet & others
Nice work on this project, it's my third day into "printing" and I'm really impressed how well everything is working!

Positive things I have noticed so far:
- The  [CUPS Programming Manual](https://cups.org/doc/cupspm.html) is very well written, everything a programmer would like to know, in the correct order
- C method documentation is very clear regarding memory management
- development speed is amazing

Negative things:
- Bridging to swift is kind of painful with CocoaPods (Clang Error: `Include of non-modular header inside framework module`)
- rasterization appears to be kind of hard (transforming images / pdfs into PWG, using a slightly modified version of ipptransform so far)

**Comment by thomasnordquist** [comment]
Just noticed that this is pretty similar to https://github.com/apple/cups/issues/5642.
From my understanding of grand central dispatch, stuff running on the `global queue` => `DispatchQueue.global(qos: .background)` may be dispatched to different threads.

I also use `cupsEnumDests` to discover printers.

So if I'm getting this correct I need to ensure that whenever I work on a "different" thread I need to find the find the destination every time, so I'm sure `_cupsGlobals()` is initialized?

Pseudo-Code
```
var allThePrinters = cupsEnumDests(***)
onThreadA {
  var dest = cupsGetNamedDest("Printer A")
  printOn(dest, "test.pdf")
)
onThreadB {
  var dest = cupsGetNamedDest("Printer B")
  printOn(dest, "test.pdf")
)
```

**Comment by michaelrsweet** [comment]
@thomasnordquist OK, I am not ready to make any changes here, but just to confirm you are connecting to the printer using `cupsConnectDest` and the `CUPS_DEST_FLAGS_DEVICE` option in the second argument?
