### ISSUE TITLE
Always include all translations

### ISSUE THREAD

**Issue by scootergrisen** [apple/cups#5651]
It seems translations are not included unless a locale/cups_*.po fil exists.

For danish i have translated everything else but the locale/cups_da.po but because locale/cups_da.po does not exists it seems the CUPS code does not include the translated templates files etc.

I would like all kinds of translations to be included regardless of what locale/cups_*.po exists.

**Comment by michaelrsweet** [comment]
Without a base localization file in the locale directory, the web interface will appear with a mix of localizations which will be very confusing...

I realize that localizing all of the messages in the po file may be daunting - even a partial translation of this file will be a move in the right direction...
