### ISSUE TITLE
No prompt for username and password

### ISSUE THREAD

**Issue by meygerjos** [apple/cups#5653]
When I click "Add printer", I am brought to a page which reads:

> Unauthorized
> Enter your username and password or the root username and password to access this page. If you are using Kerberos authentication, make sure you have a valid Kerberos ticket.

But there is no prompt to enter my username and password.

Am I doing something wrong or is this a bug?

I am using Ubuntu 18.4 at Indiana University.

**Comment by michaelrsweet** [comment]
What version of CUPS are you using?

What browser are you using?

**Comment by meygerjos** [comment]
CUPS 2.2.7

Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by michaelrsweet** [comment]
This was a bug in CUPS 2.2.7 that was fixed in 2.2.8...  Please contact the Ubuntu folks for a fix...
