### ISSUE TITLE
No Borderless printing since Debian 10 64bit update  

### ISSUE THREAD

**Issue by Maxx311** [apple/cups#5654]
"A4 Borderless" is well checked on frontend 
The printer always add a blank line, like if borderless is not accepted by the printer. 
The file is exported from Inkscape, i never had any problem with it up to now.   
When "print on a file" : all is good, the whole page is covered by the file. So it's not a file issue. 
 
Tryed to print from red painted jpg image from Gimp : the blank line is bigger, so it seems the bug is not related to the pdf file. 
Surprisely the "print a test page" is looking good on right and left borders, but wrong on up and down.    
[Document numérisé.pdf](https://github.com/apple/cups/files/3628110/Document.numerise.pdf)

Printer is Brother MFC-J5910DW (installed the Brother drivers in command line because it was not in the printer local list, either found on the install internet search. 
Drivers are the same since 2008 ... So i guess the drivers are not incriminated. 
Anyway i installed another time this printer with the famous demonipuch script, and it was the same white borders issue.   
 
Any question ? Command return ? Just ask :) 
Kindly, 
Hugo

**Comment by michaelrsweet** [comment]
This is probably the cups-filters package causing the problem...

**Comment by Maxx311** [comment]
How !! Thank you for solving the issue !! 
How come i still have the bug ?
