### ISSUE TITLE
default printer is automatically set.

### ISSUE THREAD

**Issue by ChoiChoongHo94** [apple/cups#5656]
My CUPS Version: 2.2.10

Hi.
scenario is as follows.
1. delete a printer(named 'test') set to default printer.
```
lpadmin(or lpoptions) -d test
lpadmin -x test
lpstat -d
'no system default destination'
```
2. add a printer having the same name to the deleted default printer.
('lpoptions'file is empty.)
```
lpadmin -p test -m ...
```
3. the added printer is automatically set to default printer.
(Even though I didn't enter `lpadmin(or lpoptions) -d test`, when I was open 'lpoptions' file, "Default test" is written.)
```
lpstst -d
'system default destination: test'
```

is this a bug or a basic action of CUPS?

**Comment by michaelrsweet** [comment]
The default printer is probably coming from the lpoptions - lpadmin interacts with the scheduler which will clear the server-side default printer, but not the client-side default printer set via lpoptions.

**Comment by ChoiChoongHo94** [comment]
then, when I add a printer named same to the previous default printer, is right that this printer is set to default printer automatically??

**Comment by ChoiChoongHo94** [comment]
@michaelrsweet 
Would you reply to my last question?
plz..

**Comment by michaelrsweet** [comment]
@ChoiChoongHo94 The client-side options are NOT affected by the lpadmin command, so if you add a new printer with the same name then the expected behavior is that the old client-side default will get used again.
