### ISSUE TITLE
label orientation for raster ok, for everything else wrong

### ISSUE THREAD

**Issue by daoane** [apple/cups#5659]
CUPS 2.2.7 (Ubuntu)
Zebra ZPL printer (ZD620)
Intermec PC43t printer
Firefox and Chromium on Linux for web-app (same behaviour)

##### Conditions:
* Both printers are loaded with 4x2" labels and this is set as default in the printer drivers
* Both printers print the test page correctly
* I have without success tested all possible combinations of page orientations (2x4, 4x2 in cups & landscape, portrait in the programme's settings), the cups settings used below match label size and orientation on the "web" (continuous base with 4" width and separate labels of 2" height): 4x2".

##### Behaviour:
* I create a 4x2" label in a web-app and print it (the label design itself works fine with proprietary drivers on Windows)
  => On both printers, the output is rotated by 90° (possibly 270°), only rotated on Intermec, also scaled up on Zebra (might be printer specific)
* I print the same label to pdf, convert the file to png and print this png
  => The output on both printers is correct
* Dirty fix Intermec: Edit the shell script called in cupsFilter (/usr/bin/intermec-dp-drv) and rotate the label within this script (ImageMagick)
  => Now the labels created by the webbrowser print correctly. However, also the printout of the png is rotated (in my present situation negligible)

The Intermec ppd calls cupsFilter on pdf and postscript input, the ZPL ppd calls cupsFilter on raster input. How the cupsFilter in the two ppds are "fed" by the required file format I do not know (*italics* in the list below). But for some reason, it looks like direct printing from everything except raster (I tested also text from OpenOffice Writer) is affected by rotation while direct printing of a raster file is not, i.e.
* raster *=> pdf* => cupsFilter application/vnd.cups-pdf of Intermec is fine
* raster => cupsFilter application/vnd.cups-raster of Zebra (calls rastertolabel) is fine
* non-raster 'printfile' *=> pdf* => cupsFilter application/vnd.cups-pdf of Intermec is rotated
* non-raster 'printfile' *=> raster* => cupsFilter application/vnd.cups-raster of Zebra is rotated

This is where I am stuck. Is this possibly a cups problem or do I miss something fundamentally?

**Comment by michaelrsweet** [comment]
This *could* be a cups-filters or Ghostscript issue; can you attach the generated PDF along with a debug error_log file? (enable debug logging using `cupsctl --debug-logging`, then send a print job).

**Comment by daoane** [comment]
I enabled debug logging, cleared log/cups/ and spool/cups. Then I restarted cups and sent one print job to the Zebra printer. Attached is the error_log (including cups start and the one print) and the pdf file as it was generated in cups/spool. This pdf file is exactly as it should be printed, nothing wrong with it. (Same result for Intermec).
[d00356-001.pdf](https://github.com/apple/cups/files/3685350/d00356-001.pdf)
[error_log.txt](https://github.com/apple/cups/files/3685367/error_log.txt)
Rotation of the file seems to happen after this stage.

A new observation is that the page format of both label printer appear to be propagated "upwards" to software like LibreOffice as 2x4" and not as 4x2". For example in LibreOffice Writer, I can change the print settings explicitly to 4x2", but it will always use 2x4" (this is different to the web browsers, which don't seem to care about system printer settings when the page size is declared as "custom"). Page orientation in LibreOffice has no effect either. The output in the spool folder and error_log (same proceeding as above) is as follows.
[d00357-001.pdf](https://github.com/apple/cups/files/3685441/d00357-001.pdf)
[error_log2.txt](https://github.com/apple/cups/files/3685442/error_log2.txt)
Also this pdf is then rotated during printing.

To give a better idea how the printed labels look like, I attach the photo below. All labels are printed with the Zebra printer, no settings changed from default printer installation ("add printer" in localhost:631, default page size 4x2"):

0. Print as it should be (via raster conversion)
1. Test page with the printer settings as described above
2. Label as it is printed from the web app
3. Label as it is printed from the web app, but with defaultOrientation "Any" in ppd (reverted afterwards)
4. Print from web app to Zebra printer but added to cups with the EPL printer driver (same settings as ZPL printer driver)

![labels](https://user-images.githubusercontent.com/3490465/66118511-d329ba00-e5d6-11e9-8976-ff8bba6459b3.jpg)

**Comment by michaelrsweet** [comment]
OK, the web print job log shows the following two options being passed from the browser:

    PageSize=Custom.595.28x841.89 Resolution=600dpi

The page size is approximately A4 (certainly not a size supported by the printer) and the resolution is likewise also not a supported value. So getting the wrong output isn't exactly unexpected here.

Similarly, LibreOffice is incorrectly assuming that all media sizes must be portrait - this is only valid for sheet sizes, not for label/roll sizes, and so they are sending garbage to the printing system.

So it looks like you need to file bugs against LibreOffice and the browser you are using. Once they pass the correct values and document data to the printing system, you'll get the correct output on your printer.

Wish I had a better answer for you... :/

**Comment by debiantriage** [comment]
>   This pdf file is exactly as it should be printed, nothing wrong with it. (Same result for Intermec). Rotation of the file seems to happen after this stage.

Does the autorotation section at [https://wiki.debian.org/CUPSPdfToPdf](url) help to explain this?

**Comment by daoane** [comment]
I checked the (uploaded) logs and "A4" page size appears only in the first setting. The gs command gets the correct page size (288 x 144 but still 600 dpi) and the output is correct. But I see now also  that this incorrect A4 page size (595.28x841.89) is propagated to the control file.

I can't tell whether pdftopdf is somehow involved (as sugested by debiantriage), but I guess that the main problem is the page size in the control file. As it is potentially useful for others, I will report back here on the next steps (in a couple of days, I'm presently away from the printers):
* edit the control file and replace the page size with correct values, then connect to the printer and check whether output is correct
* if output is correct, try to find where the wrong initial page size comes from

**Comment by daoane** [comment]
After installation on other computers, I can confirm that this problem is related to Firefox Linux.
Printing well defined labels from glabels works correctly, saving the labels from Firefox Linux to pdf (print -> "Print to file") produces a file with correct size and content that is printed correctly on the label printers from a pdf viewer. Definitively no issue with cups.
