### ISSUE TITLE
-d not present in lp --help

### ISSUE THREAD

**Issue by debiantriage** [apple/cups#5661]
We have a Debian user submitting #942041. https://lists.debian.org/debian-printing/2019/10/msg00022.html. 

_-d destination_ is not given in the output of `lp --help`. Note that `lpr --help`does have _-P_ destination.

Cheers,

Brian.

**Comment by michaelrsweet** [comment]
Huh, how did *that* happen. Will fix, obviously... :)

**Comment by michaelrsweet** [comment]
[master fca9a9818] Add missing "-d" help string (Issue #5661)
