### ISSUE TITLE
Dymo LabelWriter 450 - Definition for label #30859

### ISSUE THREAD

**Issue by rjs-gsp** [apple/cups#5662]
The ppd file does not have a definition for label #30359  - Paint Can Label.

Here are definitions that appear to work:

*PageSize w162h225/30859 Paint Can Label: "<</PageSize[162 225]/ImagingBBox null/cupsInteger0 0>>setpagedevice"
*PageRegion w162h225/30859 Paint Can Label: "<</PageSize[162 225]/ImagingBBox null/cupsInteger00>>setpagedevice"
*ImageableArea w162h225/30859 Paint Can Label: "4 4 158 221"
*PaperDimension w162h225/30859 Paint Can Label: "162 225"

These are available from multiple vendors such as 
https://www.amazon.com/CENTURION-30859-400-CT-White-Thermo/dp/B06XW7HWTK

**Comment by michaelrsweet** [comment]
Will consider for the next 2.3.x update.

**Comment by michaelrsweet** [comment]
[master 692b157d0] Add paint can label size (Issue #5662)
