### ISSUE TITLE
Cups job: time to finish

### ISSUE THREAD

**Issue by NelsonFrancisco** [apple/cups#5664]
Hello
I'm experiencing a funny situation with cups.
I have a configured thermal printer within my cups server.
I'm using a third-party C library, provided with an header file, that is able to open the printer, and then print custom xml files.
I know that this library requires cups, because it is on the specification, and you must configure the printer correctly before using it.

Everytime I send a print command, I can see the deployed cups job

Here's an example:
![image](https://user-images.githubusercontent.com/31771519/66570234-1bac1f00-eb65-11e9-9552-849e05a9466d.png)
The first terminal shows my custom application: it first sends a print command.
After it is successful, it sends another one.
Everytime the application receives 
```
printer.print_reply
{ success: true }
```
the job is immediately created in the cups queue.
The image shows two jobs that were triggered by the mentioned library. This means the library is working as expected.
The problem is with cups: sometimes (like in the picture) it takes a long time (like 2 seconds) to complete the first job. The printer won't print the second job before the previous one is completed, ALBEIT the paper is already out and printed.In this example, job number 199 paper was already printed, but it was blocking job 200.
Which takes me to two explanations: 
1. cups service is taking too long to understand that the previous job is already completed.
2. the printer takes too much time to reply to cups that the job is completed.

If it is the first situation, than it is a cups problem.
If it is the second one, than it is a printer problem.

If it is the first situation (I don't understand how cups works internally) then there must be a way to change the printer status sampling time, maybe?

Anyway, please let me know if there is a solution
Thank you

**Comment by michaelrsweet** [comment]
Without knowing the details of the printer connection to the system, the make and model of the printer, the driver being used, etc., it is impossible to know why you are seeing a delay.

Ultimately, cupsd will immediately proceed to the next job as soon as the previous job's filters and backend exit. If any of those components are delayed then it won't start processing the next job on that queue. And those filters and backends could be delayed due to communication errors with the printer, built-in time delays in the driver, or the printer itself waiting for some reason.

**Comment by NelsonFrancisco** [comment]
Here's the printer's details
![image](https://user-images.githubusercontent.com/31771519/66577169-c970fb00-eb70-11e9-8e2f-389089305095.png)

I'm using this printer in a Mint 19.
 I hope it is enough. If you require more information please say so.

**Comment by michaelrsweet** [comment]
Almost certainly this is a non-conforming USB printer. You *may* be able to eliminate the delay by adding a USB quirks file in /usr/share/cups/usb with the line:

    0xVVVV 0xPPPP no-reattach unidir

where "0xVVVV" and "0xPPPP" are the vendor and product IDs reported by the lsusb command.
