### ISSUE TITLE
ippeveprinter: Add DNS-SD controls

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#5666]
Currently ippeveprinter always advertises its service globally, which is only appropriate when the hostname is not "localhost". Also, there is no way to disable DNS-SD.

**Comment by michaelrsweet** [comment]
[master 7a2be9fac] Limit DNS-SD advertisements to the loopback interface for "localhost" and support "off" for subtypes to turn off advertisements (Issue #5666)

**Comment by gmuth** [comment]
I have difficulties starting ippeveprinter with docker:
```
docker run --rm anujdatar/cups ippeveprinter "Everywhere" 
Error: Unable to initialize DNS-SD.
```
