### ISSUE TITLE
trying to figure out setting a custom print size

### ISSUE THREAD

**Issue by 22350** [apple/cups#5669]
I am on cups 2.2.0  I have paper that i need to do borderless printing on.  9x13

That size is not an option on GENERAL/PAPER SIZE drop down.  

Can I go into the ppd file and add a line of code that puts that size in the list?

**Comment by michaelrsweet** [comment]
@22350 That really depends on the printer/driver. If the PPD supports custom sizes then you can define a custom size ("Custom.9x13in" at the command-line) without editing the PPD file.  Whether the application supports this depends on the OS and GUI environment used...

**Comment by 22350** [comment]
I am on a mac.  with an epson artisan 1430  currently only certain sizes are supported for "borderless" , although the physical characteristics of the printer have no limitations for this functionality.   

Is CUPS using the epson ppd file or can i manually add one with the correct parameters ?

**Comment by michaelrsweet** [comment]
@22350 This printer uses the Epson-supplied printer driver by default, which *does* support custom sizes. You can create a custom size by choosing "Manage Custom Sizes..." from the paper size popup menu. Be sure to change the default margins to 0 for your new size.

**Comment by 22350** [comment]
> @22350 This printer uses the Epson-supplied printer driver by default, which _does_ support custom sizes. You can create a custom size by choosing "Manage Custom Sizes..." from the paper size popup menu. Be sure to change the default margins to 0 for your new size.

I have tried that, but when you create a custom size, even with zero margin, it still forces a margin.  i bought a ton of paper and now i can't do borderless on it

**Comment by michaelrsweet** [comment]
@22350 I'm sorry to hear you are having difficulties with the Epson driver. However, since this printer depends on Epson's driver (not AirPrint or PostScript) there isn't a lot we can do here - you *might* be able to edit the PPD file to add another paper size (add PageSize, PageRegion, PaperDimension, and ImageableArea lines for your size) but the driver may still not honor the borderless margins. Giving Epson a call for support might be the only way to get this to work, unfortunately...

**Comment by 22350** [comment]
doesn't seem like they are going to be anxious to help me edit the ppd file.  is there a forum that I can post for help on?

**Comment by RobertKrawitz** [comment]
The Gutenprint driver allows borderless printing to all media sizes on this printer, but be careful.

The reason Epson restricts borderless printing to certain media widths, IIRC, is that the printer has slots in certain places in the tray below the print head to receive ink bleed off the edge of the paper.  If you print borderless on other media widths, that excess ink will spray into the tray and possibly make a mess.  So you can do this with Gutenprint, but at your own risk.

Disclosure: I am the project lead for Gutenprint.
