### ISSUE TITLE
custom size

### ISSUE THREAD

**Issue by 22350** [apple/cups#5670]
> I am on cups 2.2.0 I have paper that i need to do borderless printing on. 9x13

That size is not an option on GENERAL/PAPER SIZE drop down.

Can I go into the ppd file and add a line of code that puts that size in the list?

@michaelrsweet
 

@22350 That really depends on the printer/driver. If the PPD supports custom sizes then you can define a custom size ("Custom.9x13in" at the command-line) without editing the PPD file. Whether the application supports this depends on the OS and GUI environment used...>

sorry if i am using this forum incorrectly, but the subject was closed right away.

I am on a mac. with an epson artisan 1430 currently only certain sizes are supported for "borderless" , although the physical characteristics of the printer have no limitations for this functionality.

Is CUPS using the epson ppd file or can i manually add one with the correct parameters ?

**Comment by michaelrsweet** [comment]
You can continue to post comments on closed issues; I only close them to keep the issue tracker clear of questions - the mailing lists are the preferred method of asking questions...
