### ISSUE TITLE
Airprint authentication pop issue with iOS 13.1.2 and iOS 13.1.3

### ISSUE THREAD

**Issue by shalztech** [apple/cups#5672]
" When using AirPrint it is possible to specify a username/password combination for authenticated printing. CUPS (the underlying printing service on iOS) caches the username/password combo once this has been entered and never again shows a prompt except when the whole network setup or the device itself is reset".
This does not seem to be correct with iOS 13.1.2 and 13.1.3 upgrade. 
Steps to replicate issue : -
1. User print to authentication enabled queue using iOS  13.1.3 device.
2. User will be prompted for authentication.
3. Once user filled in details , job will be printed.
4. User again try to print on same queue with iOS 13.1.3, user will get authentication pop up again. With iOS 13.1.2, you can try this step after few minutes and you will get authentication pop up.
If we check on authentication server, we can see request coming from iOS device does not have any authentication token in it . 

Is there anything changed with recent version of iOS devices or anything changed in CUPS ? Does CUPS not cache credential at all ? It is causing poor user experience at iOS devices.
I can not see anything in release notes.  Please share some insight on it.

Thanks for your help!

**Comment by michaelrsweet** [comment]
Please report all AirPrint and iOS printing issues using the Apple bug report page (bugreport.apple.com).
