### ISSUE TITLE
Detect printer paper ended

### ISSUE THREAD

**Issue by boomsya** [apple/cups#5675]
I have CUSTOM Engineering TG2480H printer in kiosk.
Can I programmatically detect what printer paper is ended?

When I extract paper roll from printer - web administrator page shows what a printer in idle state. But not shows what is no paper

**Comment by michaelrsweet** [comment]
That's because cupsd does not poll the printer constantly to see what its state is, just when there is a job active. And then it depends on the printer driver or backend to report that paper is out...
