### ISSUE TITLE
Typo in German error message

### ISSUE THREAD

**Issue by debiantriage** [apple/cups#5680]
In Debian bug #931727 (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=931727) Thorsten Ehlers reports a minor issue. The relevant CUPS line appears to be:

locale/cups_de.po:msgstr "%s: Fehler - kein voreingestellted Druckziel verfügbar."

There should be an "s" instead of a "d" at the end of "voreingestelltes",

Regards,

Brian.

**Comment by michaelrsweet** [comment]
Um, at least in the master branch, this appears to be already fixed for a couple years.
