### ISSUE TITLE
lpoptions does not output anything

### ISSUE THREAD

**Issue by debiantriage** [apple/cups#5681]
In Debian Bug #799042 at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=799042 Vincent Lefevre observes on CUPS 2.3.0-7 (with a default destination set) that

> Since lip-multi-1 is the default printer (note: none of the LPDEST and                                                      
PRINTER environment variables are set, so that the default destination                                                      
is obtained from ~/.cups/lpoptions), "lpoptions" should be equivalent                                                       
to "lpoptions -plip-multi-1", as documented.

Regards,

Brian.

**Comment by michaelweghorn** [comment]
This sounds like the problem was that the default printer isn't read from `~/.cups/lpoptions` as it should, which AFAICT is a regression.
Pull request #5679 seems to fix this for me as well  (`lpoptions` doesn't give any output for me without the changes, but does again with them included).

**Comment by michaelrsweet** [comment]
OK, so the issue is that cups_enum_dests did not use the default printer from the lpoptions files.

[master 3ff5a8e39] Fix lpoptions defaults (Issue #5681)

[branch-2.2 9645531ee] Fix lpoptions defaults (Issue #5681)
