### ISSUE TITLE
Typo in https://www.cups.org/doc/cupspm.html

### ISSUE THREAD

**Issue by spider0061** [apple/cups#5682]
In **Compiling Programs That Use the CUPS API** section, for running the code snippet with C
the command wriiten is:

> gcc -o **simple** `cups-config --cflags` **simple.c** `cups-config --libs`
**./simple**

but it should be

> gcc -o **sample** `cups-config --cflags` **sample.c** `cups-config --libs`
**./sample**

as the C file name is sample.c .

**Comment by michaelrsweet** [comment]
I opted to change the initial instructions to use the filename "simple.c" instead.

[master bea505c32] Fix example source filename in CUPS PM (Issue #5682)
