### ISSUE TITLE
CUPS appears to be vulnerable to the SSL SWEET32 attack.

### ISSUE THREAD

**Issue by abcbarryn** [apple/cups#5686]
The DES ciphers (and triple-DES) only have a 64-bit block size. This enables an attacker to run JavaScript in a browser and send large amounts of traffic during the same TLS connection, creating a collision. With this collision, the attacker is able to retrieve information from a session cookie.

Fix: Disable 3DES and DES ciphers, probably in cups/https.c and scheduler/client.c. Even better, allow an option to set which ciphers are used for SSL.

**Comment by michaelrsweet** [comment]
You mean like the SSLOptions directive for client.conf and cupsd.conf?

Looking at the code in cups/tls-*.c, the DES and 3DES cipher suites are unconditionally excluded on macOS and Linux (GNU TLS), and on Windows we rely on the defaults (which exclude them, at least on Windows 10).

What version of CUPS are you testing with?

**Comment by abcbarryn** [comment]
I am testing with the versions in Redhat 6 and Redhat 7. I tried patching the code myself without success. If the current version has this fixed I guess you can close this but can you provide the full path to the file where the ciphers are set and I will try to back port the code.

**Comment by michaelrsweet** [comment]
For Linux you want to look in cups/tls-gnutls.c. We dropped OpenSSL support before the changes were added but those would be in cups/tls-openssl.c for the really old CUPS in RHEL 6.

**Comment by zdohnal** [comment]
@abcbarryn RHEL 6 has cups-1.4.2, which uses gnutls, RHEL 7 has cups-1.6.3, which uses openssl. In RHEL 7 you can try MinTLS directive, which could help. It has the same name as current CUPS directive, which Mike wrote for gnutls, darwin and sspi, but it is rewritten into openssl calls.

Either way, please check if current CUPS is vulnerable and for RHEL, please contact RH support.
