### ISSUE TITLE
kernel: cupsd[9073] general protection ip:7f3dd1338716 sp:7ffdadea62d8 error:0 in libc-2.12.so

### ISSUE THREAD

**Issue by cupsman** [apple/cups#5687]
Michael,  We have an issue since the last kernel upgrade on our server.  Randomly every morning we are getting a general protection error in cups and it crashes the daemon.  We print lots of jobs throughout the day without issue.  This doesn't occur at the same in the morning, nor could I pin point a printer that may be the cause.  

Here's some additional information about the software.

2.6.39-400.306.1.el6uek.x86_64
Oracle Linux Server release 6.8
cups-1.4.2-74.el6.x86_64  (Current rpm version running)
(Our latest version that we could upgrade to in the repository is -.81 )

(/var/log/messages)
kernel: cupsd[9073] general protection ip:7f3dd1338716 sp:7ffdadea62d8 error:0 in libc-2.12.so[7f3dd1210000+18b000]

Any help would be greatly appreciated as I can't find any hints to what the root cause is other than possibly some issue with the new kernel and version of cupsd.
Thanks!!! and let me know.

**Comment by michaelrsweet** [comment]
@cupsman Sadly, there isn't much I can do to help you on such an old version of CUPS, and one that is so heavily patched by Red Hat. Your best bet is to file a support request with Oracle so they can escalate things with Red Hat and/or determine the cause themselves...

**Comment by zdohnal** [comment]
@cupsman I'm not sure how exactly is Oracle Linux related to RHEL, but the latest kernel build for RHEL 6 is 2.6.32-754... so it could be Oracle has separate build system, where they have newer kernel, or you have kernel installed from somewhere else. To be honest, I have never seen such suffix - el6euk.
As Mike already said, please contact Oracle with the issue.
