### ISSUE TITLE
socket backend does not wait for closing connection between 2 jobs

### ISSUE THREAD

**Issue by zdohnal** [apple/cups#5689]
Hi Mike,

we have a report in RHEL 7 - https://bugzilla.redhat.com/show_bug.cgi?id=1748641 - about socket backend and Zebra printers. I checked the current socket backend in CUPS and it seems affected too by looking into code.
User has several Zebra label printers for printing barcodes and prints many jobs in quick sequence. Printers are connected by socket backends, because they do not support IPP. During printing, socket backend does not wait until the previous connection is done and send the next job. 
This behavior causes undefined behavior in the printer - sometimes the job is printed correctly, sometimes it does not print all or the previous job is printed during next job...

There is a capture of network traffic when issue happens 
[ssc-zeb-prt-03-201909031526.cap.txt](https://github.com/apple/cups/files/3879708/ssc-zeb-prt-03-201909031526.cap.txt)

User prepared patch which works for him:
```
--- cups-1.6.3/backend/socket.c	2019-08-30 05:39:34.425597602 +1000
+++ cups-1.6.3/backend/socket.c.closetimeout	2019-08-30 05:40:20.067116006 +1000
@@ -79,6 +79,7 @@ main(int  argc,				/* I - Number of comm
 #endif /* __APPLE__ */
   int		contimeout;		/* Connection timeout */
   int		waiteof;		/* Wait for end-of-file? */
+  int 		waiteoftimeout;		/* Timeout to wait for end-of-file */
   int		port;			/* Port number */
   char		portname[255];		/* Port name */
   int		delay;			/* Delay for retries... */
@@ -94,6 +95,7 @@ main(int  argc,				/* I - Number of comm
 		have_supplies;		/* Printer supports supply levels? */
   ssize_t	bytes = 0,		/* Initial bytes read */
 		tbytes;			/* Total number of bytes written */
+  int		wait_bc_result;		/* Did we timeout waiting for end-of-file? */
   char		buffer[1024];		/* Initial print buffer */
 #if defined(HAVE_SIGACTION) && !defined(HAVE_SIGSET)
   struct sigaction action;		/* Actions for POSIX signals */
@@ -187,8 +189,9 @@ main(int  argc,				/* I - Number of comm
   * Get options, if any...
   */
 
-  waiteof    = 1;
-  contimeout = 7 * 24 * 60 * 60;
+  waiteof        = 1;
+  waiteoftimeout = 90;
+  contimeout     = 7 * 24 * 60 * 60;
 
   if ((options = strchr(resource, '?')) != NULL)
   {
@@ -247,6 +250,15 @@ main(int  argc,				/* I - Number of comm
         waiteof = !value[0] || !_cups_strcasecmp(value, "on") ||
 		  !_cups_strcasecmp(value, "yes") || !_cups_strcasecmp(value, "true");
       }
+      else if (!_cups_strcasecmp(name, "waiteoftimeout"))
+      {
+       /*
+        * Set the connection timeout...
+	*/
+
+	if (atoi(value) > 0)
+	  waiteoftimeout = atoi(value);
+      }
       else if (!_cups_strcasecmp(name, "snmp"))
       {
         /*
@@ -450,6 +462,7 @@ main(int  argc,				/* I - Number of comm
       break;
 #endif /* __APPLE__ */
 
+  wait_bc_result = 0;
   if (waiteof && tbytes >= 0)
   {
    /*
@@ -460,7 +473,7 @@ main(int  argc,				/* I - Number of comm
 
     shutdown(device_fd, 1);
 
-    while (wait_bc(device_fd, 90) > 0);
+    while ((wait_bc_result = wait_bc(device_fd, waiteoftimeout)) > 0);
   }
 
  /*
@@ -487,7 +500,7 @@ main(int  argc,				/* I - Number of comm
   if (print_fd != 0)
     close(print_fd);
 
-  return (tbytes >= 0 ? CUPS_BACKEND_OK : CUPS_BACKEND_FAILED);
+  return ((tbytes >= 0 && wait_bc_result == 0) ? CUPS_BACKEND_OK : CUPS_BACKEND_FAILED);
 }
 
 
@@ -508,6 +521,7 @@ wait_bc(int device_fd,			/* I - Socket *
  /*
   * Wait up to "secs" seconds for backchannel data...
   */
+  fprintf(stderr, "DEBUG: Waiting up to %d seconds for back-channel data\n", secs);
 
   timeout.tv_sec  = secs;
   timeout.tv_usec = 0;
@@ -531,7 +545,10 @@ wait_bc(int device_fd,			/* I - Socket *
     return (bytes);
   }
   else
-    return (-1);
+  {
+    fputs("DEBUG: Timed-out waiting for back-channel data\n", stderr);
+    return (-1);  	
+  }
 }
```

It adds a option to add new string into device uri - waiteoftimeout - which allows to define timeout of wait_bc(). Then backend is allowed to end as OK only when there is no more data. The patch works for the user.

What do you think about it? Is it feasible to add the patch into the project?

**Comment by michaelrsweet** [comment]
It is necessary to wait for the other end to close the socket, otherwise the page accounting values will not be stable. This is "standard" port 9100 behavior as defined by HP, and Zebra's implementation is "non-conformant" since it does not mimic this.

The workaround for these printers is to add "?waiteof=no" to the device URI.

**Comment by zdohnal** [comment]
Ok, thank you for the tip!

**Comment by zdohnal** [comment]
@michaelrsweet  actually "?waiteof=no" worsened the issue for user - socket backend now does not wait for device at all and jobs get garbled regularly.
I probably messed up explanation - the problem is not that 'backend waits', but rather 'backend does not wait' and that's resulted to undefined behavior, which the patch mentioned in the first comment should help to fix it.

I haven't had any zebra printer yet, so I'm merely forwarding the experience of user. Is there any public specification how jetdirect port should work? Or is there a way how to find out more info about the printer than it is showed in the shop (like which document formats it supports, which IPP protocol version, release date of printer etc.)?

**Comment by michaelrsweet** [comment]
@zdohnal Indeed I have *not* had either experience. My current Zebra printer is a GX420d, which seems to be working perfectly even under load.And I can pretty much guarantee that a lot of existing users will have a fit if I add any more delays into the socket backend since it negatively affects the throughput on these printers...

Have the customer verify they are using the most current version of the CUPS driver (the one from CUPS 1.6 has a known bug in the ZPL output if they are using the rastertolabel filter at all) and that they have the most current firmware for their printer.

**Comment by jsmeix** [comment]
@zdohnal 
only as a side note FYI what could be also helpful
in special cases for a particular user with a particular printer:
https://en.opensuse.org/SDB:Using_Your_Own_Backends_to_Print_with_CUPS
