### ISSUE TITLE
A required dependency cups-devel and cups-image

### ISSUE THREAD

**Issue by tiagocab** [apple/cups#5692]
Installing hplip-3.19.11 on ubuntu 18.04.3 LTS (bionic) returns dependency error:

error: A required dependency 'cups-devel (Common Unix Printing System development files)' is still missing.
error: A required dependency 'cups-image (CUPS image - CUPS image development files)' is still missing.
error: Installation cannot continue without these dependencies.
error: Please manually install this dependency and re-run this installer.

And I can't find these dependencies. Help me please

**Comment by michaelrsweet** [comment]
I'm sorry, but we can't provide support for Ubuntu here... Have you tried "apt-get install libcupsimage2"?

Ordinarily the hplip packages for Ubuntu will use the correct dependencies - cups-image and cups-devel would be RPM dependencies, while on Ubuntu (and all Debian-based distros) it will be libcupsimage2 and libcups2-dev.
