### ISSUE TITLE
Increase PPD_MAX_TEXT?

### ISSUE THREAD

**Issue by speachy** [apple/cups#5696]
The 80 byte upper limit of PPD_MAX_TEXT is fine for ASCII text, but when UTF-8 strings are involved one can easily use 2-4 bytes per character.

The PPD specs seem to be silent on the maximum allowable length for translation strings, other than staying under PPD_MAX_LINE, so I'm curious if there's a particular reason for capping it at 80 bytes, and if it is feasible/reasonable to increase it given the impending demise of PPD support.

(What precipitated this is an updated Gutenprint translation that now has four 40-ish character UTF-8 sequences that exceed 80 bytes, causing cupstestppd to barf..)

**Comment by michaelrsweet** [comment]
This has come up before. The short answer is no, we can’t increase the limit as it would break binary compatibility. And since ppds have been deprecated for 10+ years we have no interest in engineering a solution for it.
