### ISSUE TITLE
Startup of cups takes 3-5 minutes

### ISSUE THREAD

**Issue by cupsman** [apple/cups#5698]
I'm not for sure if this is a bug or design but have noticed cups will go through all the spool files at startup and we have over 140k files from our daily jobs and it can take 3-5 minutes to start?  Is this by design or bug, or a workaround to this with startup switch?

Please let me know.
Thanks  
/ddc

**Comment by michaelrsweet** [comment]
Generally speaking, 3-5 minutes to start with 140k jobs in history is not unheard of. The jobs.cache file is normally used to speed things up, but that's still 140k sets of allocations, checks that the jobs still exist in the spool directory, etc.

That said, there is typically no need to restart (or stop and start) cupsd on a regular basis, and for a server with that much volume you should probably disable the launch-on-demand functionality the is usually enabled - you can increase the timeout to a large value (e.g., "cupsctl IdleExitTimeout=86400") to prevent that from happening.
