### ISSUE TITLE
printers.conf messes with version control - move more dynamic values into another file

### ISSUE THREAD

**Issue by maidentaiwan** [apple/cups#5699]
Several values in `/etc/cups/printers.conf` change automatically, from time to time,  without any user intervention:

```
StateTime
UUID
ConfigTime
```

These changes are problematic for anyone who keeps `printers.conf` under version control, because they are not meaningful to the operation of cups, and yet they cause the original file to differ from last saved version. Would it be possible store these dynamic values in a different file that would not be under version control?

Alternatively, is there a better way to version the settings of cups?

**Comment by maidentaiwan** [comment]
Version information:

```
$ apt list -a cups
Listing... Done
cups/bionic-updates,bionic-security,now 2.2.7-1ubuntu2.7 amd64 [installed]
cups/bionic 2.2.7-1ubuntu2 amd64
```

**Comment by michaelrsweet** [comment]
This sort of requests has come in many times over the years. Short answer: we have no plans of changing this any time soon, but since printers.conf and the other config files *are* written automatically by cupsd they should not be version controlled this way.

**Comment by maidentaiwan** [comment]
Is there another way to version-control Cups settings other than printers.conf?
