### ISSUE TITLE
[Question] Could I translate 'a self-describing media name'->'Translated name'

### ISSUE THREAD

**Issue by ChoiChoongHo94** [apple/cups#5702]
CUPS version: 2.2.10
OS: Debian buster

Hi.
(I'm not native speaker. I'd appreciate it if you could understand.)

I want to translate 'iso_a4_210x297mm' -> 'A4'.
is it possible??

I found below in `.../cups/locale/cups.strings` file.
```
...
"media.iso_a4-extra_235.5x322.3mm" = "A4 (Extra)";
"media.iso_a4-tab_225x297mm" = "A4 (Tab)";
"media.iso_a4_210x297mm" = "A4";
"media.iso_a4x3_297x630mm" = "A4x3";
"media.iso_a4x4_297x841mm" = "A4x4";
"media.iso_a4x5_297x1051mm" = "A4x5";
"media.iso_a4x6_297x1261mm" = "A4x6";
"media.iso_a4x7_297x1471mm" = "A4x7";
"media.iso_a4x8_297x1682mm" = "A4x8";
"media.iso_a4x9_297x1892mm" = "A4x9";
...
```
When I saw this, I guess the translation is possible.
Additionally, I also refered to  `issue #3603`.

**Comment by michaelrsweet** [comment]
Use the `cupsLocalizeDestMedia` function, which handles both standard and custom/dimensional sizes.

**Comment by ChoiChoongHo94** [comment]
Thank you for your reply!

Previously, I tried to  `cupsLocalizeDestMedia`, but I was using a wrong `http_t* http` argument (CUPS_HTTP_DEFAULT).
Now, I found this.
