### ISSUE TITLE
Use "[" and "]" for command line option values

### ISSUE THREAD

**Issue by scootergrisen** [apple/cups#5706]
During translation of the pot file it seems it is not clear when text should be translated and no translated.

Here is two strings with values (description and hold) for the options.
From what i can guess i think only one of them should be translated.
But from the strings it is not clear.

    -D description          Specify the textual description of the printer
    -H hold                 Hold the job until released/resumed

I think other software use "[" and "]" around words that does not seen to be precively that (can be translated).

So maybe write like this instead if this is the standard way to do it:

    -D [description]        Specify the textual description of the printer
    -H hold                 Hold the job until released/resumed

That way translators can also better see what to translate and what not to translate.
Maybe there is a standard that can be followed.

**Comment by michaelrsweet** [comment]
I don't think there is a hard-and-fast standard for this, but putting the non-literal text in square brackets sounds fine to me. We'll track this for a future update.

**Comment by scootergrisen** [comment]
Maybe "[" and "]" is used for things that is optional.

In other software (GNOME) i see sometimes capital letters being used:

    gresource [--section SECTION] COMMAND [ARGS…]

Maybe that is an indication for things to translate.

Maybe someone else have input before deciding the best way.

**Comment by michaelrsweet** [comment]
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
