### ISSUE TITLE
systemd: service doens't start properly listening on IP address

### ISSUE THREAD

**Issue by andyrtr** [apple/cups#5709]
Using Arch Linux with cups 2.3.1 and recent systemd 244.1 I have my cups server to listen on its IP address(Listen 192.168.1.90:631). The IP isn't up at boot properly so the service isn't started properly and won't advertise the printer to the networt. I have to restart org.cups.cupsd.service to find the printer from clients.

I could manage to fix the startup with adding this to the system/org.cups.cupsd.service file:
After=network-online.target
Wants=network-online.target

Is this a valid solution or do you have a better fix?

**Comment by michaelrsweet** [comment]
That sounds like the right solution, and I think is the one adopted by OpenPrinting CUPS.
