### ISSUE TITLE
-o orientation-requested not working when print with -o raw command

### ISSUE THREAD

**Issue by chiamwuixiang** [apple/cups#5711]
Hi, Im new to CUPS.

Sorry if I'm asking something that has been reported before but I can't seem to find the exact issue I'm facing now.

I tried to do a zpl template printing with printer model ZQ520.

This is my command to print the template.

_lp -d ZQ520 -o raw document.zpl_

The label is printed out in normal orientation, but i want it to be inverted orientation, so i use

_lp -d ZQ520 -o raw -o orientation-requested=4 document.zpl_

 but it seems the orientation-requested options is not read when it is printed in RAW.

Question 1:
Is RAW printing default bahavior cannot read the orientation option?

Question 2:
Is there some way we can access RAW backend to do some coding to change its default orientation?

Sorry If I am asking something silly as I am still beginner to CUPS.

**Comment by michaelrsweet** [comment]
The "raw" option basically tells CUPS not to do anything with the print file and send it directly to the printer. At that point there is no software in the filter chain that can apply the orientation change, so naturally the option has no effect.

What you want to do is either a) use a standard format and let the ZPL driver produce the printer-ready data for you or b) extend the driver to provide a MIME media type and filter for ZPL document data that can add the appropriate orientation change commands (and filter out any embedded ones in the document data).
