### ISSUE TITLE
'everywhere' model does not create default color models in created PPD when IPP printer response is insufficient

### ISSUE THREAD

**Issue by zdohnal** [apple/cups#5713]
Hi,

I tried it only with my HP LaserJet printer (monochrome) at home and with Canon ImageRunner (color and monochrome) in our office, but ppd generator did not create ppd with values similar to https://www.cups.org/doc/ppd-compiler.html#COLOR .
This issue causes the user is not able to select color mode in print dialog.
Here is the ppd of canon printer created by 'lpadmin -p printer -v uri -m everywhere -E' 
[canon.ppd.txt](https://github.com/apple/cups/files/4018470/canon.ppd.txt) and result of get-printer-attributes request 
[get-printer-attributes.log.txt](https://github.com/apple/cups/files/4018472/get-printer-attributes.log.txt) .

**Comment by bocekm** [comment]
I've got a similar issue - when choosing "IPP everywhere" while adding Canon MF645Cx through Cups web UI, the generated PDD has only `ColorModel RGB`, no Gray/B&W.

**Comment by zdohnal** [comment]
@bocekm Actually it is printer firmware issue (at least in my case) - the printer does not answer with fully usable data for preferred keyword.
ppdgenerator has sequence of keywords for color models sorted by priority  - urf-supported, pwg-raster-document-type-supported, print-color-mode-supported, output-mode-supported - if one is missing, it tries next one.
In my case the printer reports only srgb_8 for pwg-raster-document-type-supported. All usable color models are in print-color-mode-supported.

The solution could be validating the data after deciding which keyword will be used - and if it does not provide at least default values, move to other one.

**Comment by michaelrsweet** [comment]
Fixed in OpenPrinting CUPS.
