### ISSUE TITLE
Printer instances no more working

### ISSUE THREAD

**Issue by michaelweghorn** [apple/cups#5716]
As quickly described in #5679, printer instances no longer seem to work with current git master, s. more details there.
I quickly retested with current master (as of commit 1f2a315c2b3e2f78c37c1505fc66909ad01df85e), and that still seems to be the case; therefore I'm opening this separate issue to keep track of this.

(Please let me know in case I just missed something.)

**Comment by michaelweghorn** [comment]
Unfortunately, this is still broken with CUPS in current Debian testing (package version 2.3.3op1-3) as well as as a self-compiled CUPS from the master branch of https://github.com/OpenPrinting/cups (as of commit 88a68e33c1d883befe93522b16d1bc71506e8e5d ).

@michaelrsweet: Do you have any suggestion on how to continue here? Are you still planning to look into this? Or would you be willing to give more information what the problems with my original MR #5679 were so I can try to come up with a better suggestion?
(In https://github.com/apple/cups/pull/5679#issuecomment-554003711, you mentioned:

> Sorry, that change has some bad side-effects. I will push a simpler fix to cups_enum_dests against the parent bug...

but without any further information, it's not clear to me what exactly those bad side-effects were.)

**Comment by michaelrsweet** [comment]
@michaelweghorn Can you re-file this bug against the OpenPrinting CUPS repository? As I am no longer with Apple there isn't anything I'll be able to do here...

**Comment by michaelweghorn** [comment]
> @michaelweghorn Can you re-file this bug against the OpenPrinting CUPS repository? As I am no longer with Apple there isn't anything I'll be able to do here...

@michaelrsweet: Sure, I've created https://github.com/OpenPrinting/cups/issues/71

I'm closing this one here. Let's use the new issue at OpenPrinting to keep track of this.
