### ISSUE TITLE
Pos printer delay between two consecutive jobs

### ISSUE THREAD

**Issue by oguzturkaslan** [apple/cups#5718]
Hi. I want to minimize the delay between two jobs I send consecutively to the printer with an ubuntu-based pos device.Is there any way ı can do this? I would appreciate it if you could give me a detailed description of what to do.

device's "/etc/cups/printers.conf" file, the pos device's <Device URI> is written as "usb:// .... / .....".

printer pos device connected via USB

Thank you for your interest.

Good work.

**Comment by michaelrsweet** [comment]
Impossible to say without knowing what device is being used, what driver, etc. Please report this information in a new bug report for the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
