### ISSUE TITLE
Can't get `dinfo` for a printer named `"`

### ISSUE THREAD

**Issue by ChoiChoongHo94** [apple/cups#5723]
CUPS version: 2.2.10
System: Debian Buster
Prerequisite: a printer named `"` is added to CUPS.

My test code is
```
cups_dest_t* dest = cupsGetNamedDest(CUPS_HTTP_DEFAULT, "\"", NULL);
cups_dinfo_t* dinfo = cupsCopyDestInfo(CUPS_HTTP_DEFAULT, dest);
cout << cupsLastError() << '\n' << cupsLastErrorString() << '\n';
```

The result is
```
1025
Forbidden
```
and I could get the `dest` normally but the `dinfo` is NULL(0x0).

How can I solve this problem??

**Comment by michaelrsweet** [comment]
" is not a valid printer name. "man lpadmin" for information on the valid characters for a printer name.

**Comment by ChoiChoongHo94** [comment]
@michaelrsweet 
The following is the portion of `man lpadmin`.
```
CONFORMING TO
       Unlike the System V printing system, CUPS allows printer names to contain any printable character except SPACE, TAB, "/",
       or "#".  Also, printer and class names are not case-sensitive.  Finally, the CUPS version of lpadmin may ask the user for
       an access password depending on the printing system configuration.  This differs from the System V version which requires
       the root user to execute this command.
```
If a printer would be added through `IPP`, can the name include `"`??
(because `CUPS allows printer names to contain any printable character except SPACE, TAB, "/",
       or "#".`)

**Comment by ChoiChoongHo94** [comment]
> " is not a valid printer name. "man lpadmin" for information on the valid characters for a printer name.

@michaelrsweet 
The following is the portion of `man lpadmin`.
```
CONFORMING TO
       Unlike the System V printing system, CUPS allows printer names to contain any printable character except SPACE, TAB, "/",
       or "#".  Also, printer and class names are not case-sensitive.  Finally, the CUPS version of lpadmin may ask the user for
       an access password depending on the printing system configuration.  This differs from the System V version which requires
       the root user to execute this command.
```
If a printer would be added through `IPP` not `lpadmin`, is it allowed that the name include `"`??
(because `CUPS allows printer names to contain any printable character except SPACE, TAB, "/",
       or "#".`)

In the `scheduler/ipp.c`,
```
/*
 * 'validate_name()' - Make sure the printer name only contains valid chars.
 */

static int      /* O - 0 if name is no good, 1 if good */
validate_name(const char *name) /* I - Name to check */
{
  const char  *ptr;   /* Pointer into name */


 /*
  * Scan the whole name...
  */

  for (ptr = name; *ptr; ptr ++)
    if ((*ptr > 0 && *ptr <= ' ') || *ptr == 127 || *ptr == '/' || *ptr == '#')
      return (0);

 /*
  * All the characters are good; validate the length, too...
  */

  return ((ptr - name) < 128);
}
```

**Comment by ChoiChoongHo94** [comment]
@michaelrsweet 
I'd appreciate it if you could answer my last comment.

**Comment by michaelrsweet** [comment]
@ChoiChoongHo94 We are NOT supporting printers with the name ".

From systemv/lpadmin.c:

```
 /*
  * Scan the whole name...
  */

  for (ptr = name; *ptr; ptr ++)
    if (*ptr == '@')
      break;
    else if ((*ptr >= 0 && *ptr <= ' ') || *ptr == 127 || *ptr == '/' || *ptr == '\\' || *ptr == '?' || *ptr == '\'' || *ptr == '\"' || *ptr == '#')
      return (0);
```

The short of it is this: quotes cause problems in many places (shell scripts, HTML, URIs, etc.) so CUPS doesn't allow them.
