### ISSUE TITLE
job-hold-until=weekend fails on Friday

### ISSUE THREAD

**Issue by trialuser02** [apple/cups#5726]
CUPS version: 2.3.1
Unit tests fail with the following extra error message:
`E [24/Jan/2020:21:34:46.414358 +0300] [Job 4] Job held by \"user\". `
After some digging I found that "hold_until" variable is always 1579878000 (Fri, 24 Jan 2020 15:00:00 GMT).  So, unit test always fails after this time (FAIL: 34 error messages, expected 33). Here is full part of log:
`
D [24/Jan/2020:21:34:46.413630 +0300] [Client 4] Read: status=100, state=6
d [24/Jan/2020:21:34:46.413667 +0300] cupsdProcessIPPRequest(0x666cbee10310[4]): operation_id=0002(Print-Job)
d [24/Jan/2020:21:34:46.413671 +0300] cupsdProcessIPPRequest: operation-attributes-tag
d [24/Jan/2020:21:34:46.413674 +0300] cupsdProcessIPPRequest: attributes-charset charset 'utf-8'
d [24/Jan/2020:21:34:46.413679 +0300] cupsdProcessIPPRequest: attributes-natural-language naturalLanguage 'en'
d [24/Jan/2020:21:34:46.413683 +0300] cupsdProcessIPPRequest: printer-uri uri 'ipp://127.0.0.1:8631/printers/Test1'
d [24/Jan/2020:21:34:46.413685 +0300] cupsdProcessIPPRequest: requesting-user-name nameWithoutLanguage 'user'
d [24/Jan/2020:21:34:46.413688 +0300] cupsdProcessIPPRequest: job-attributes-tag
d [24/Jan/2020:21:34:46.413691 +0300] cupsdProcessIPPRequest: job-hold-until keyword 'weekend'
D [24/Jan/2020:21:34:46.413697 +0300] Print-Job ipp://127.0.0.1:8631/printers/Test1
d [24/Jan/2020:21:34:46.413701 +0300] print_job(0x666cbee10310[4], ipp://127.0.0.1:8631/printers/Test1)
D [24/Jan/2020:21:34:46.413705 +0300] [Job ???] Auto-typing file...
I [24/Jan/2020:21:34:46.413738 +0300] [Job ???] Request file type is application/pdf.
d [24/Jan/2020:21:34:46.413752 +0300] add_job(0x666cbee10310[4], 0x666cbeea8d10(Test1), 0x666cbee053c0(application/pdf))
d [24/Jan/2020:21:34:46.413756 +0300] cupsdFindPolicyOp(p=0x666cbee061f0, op=2(Print-Job))
d [24/Jan/2020:21:34:46.413759 +0300] cupsdFindPolicyOp: Found wildcard match...
d [24/Jan/2020:21:34:46.413762 +0300] cupsdIsAuthorized: con->uri="/printers/Test1", con->best=0x666cbee0aa90((null))
d [24/Jan/2020:21:34:46.413765 +0300] cupsdIsAuthorized: level=CUPSD_AUTH_ANON, type=None, satisfy=CUPSD_AUTH_SATISFY_ALL, num_names=0
d [24/Jan/2020:21:34:46.413768 +0300] cupsdIsAuthorized: op=0(0x0000)
d [24/Jan/2020:21:34:46.413771 +0300] cupsdIsAuthorized: auth=CUPSD_AUTH_ALLOW...
d [24/Jan/2020:21:34:46.413779 +0300] check_quotas(0x666cbee10310[4], 0x666cbeea8d10[Test1])
D [24/Jan/2020:21:34:46.413788 +0300] cupsdMarkDirty(---J-)
D [24/Jan/2020:21:34:46.413791 +0300] cupsdSetBusyState: newbusy="Active clients, printing jobs, and dirty files", busy="Active clients, printing jobs, and dirty files"
D [24/Jan/2020:21:34:46.413797 +0300] [Job 4] Applying default options...
D [24/Jan/2020:21:34:46.413800 +0300] add_job: requesting-user-name="user"
d [24/Jan/2020:21:34:46.413809 +0300] cupsdSetJobHoldUntil(job=0x666cbeec10f0(4), when="weekend", update=0)
d [24/Jan/2020:21:34:46.413813 +0300] cupsdSetJobHoldUntil: hold_until=1579878000
D [24/Jan/2020:21:34:46.413816 +0300] Adding default job-sheets values "none,none"...
I [24/Jan/2020:21:34:46.413820 +0300] [Job 4] Adding start banner page "none".
d [24/Jan/2020:21:34:46.413823 +0300] copy_banner(con=0x666cbee10310[4], job=0x666cbeec10f0[4], name="none")
d [24/Jan/2020:21:34:46.413830 +0300] cupsdAddEvent(event=job-created, dest=0x666cbeea8d10(Test1), job=0x666cbeec10f0(4), text="Job created.", ...)
D [24/Jan/2020:21:34:46.413879 +0300] Discarding unused job-created event...
d [24/Jan/2020:21:34:46.413891 +0300] add_file(con=0x666cbee10310[4], job=4, filetype=application/pdf, compression=0)
D [24/Jan/2020:21:34:46.413894 +0300] cupsdMarkDirty(---J-)
D [24/Jan/2020:21:34:46.413897 +0300] cupsdSetBusyState: newbusy="Active clients, printing jobs, and dirty files", busy="Active clients, printing jobs, and dirty files"
I [24/Jan/2020:21:34:46.413914 +0300] [Job 4] Adding end banner page "none".
d [24/Jan/2020:21:34:46.413918 +0300] copy_banner(con=(nil)[-1], job=0x666cbeec10f0[4], name="none")
I [24/Jan/2020:21:34:46.413921 +0300] [Job 4] File of type application/pdf queued by "user".
D [24/Jan/2020:21:34:46.413924 +0300] [Job 4] hold_until=1579878000
I [24/Jan/2020:21:34:46.413926 +0300] [Job 4] Queued on "Test1" by "user".
d [24/Jan/2020:21:34:46.413930 +0300] cupsdCheckJobs: 3 active jobs, sleeping=0, ac-power=-1, reload=0, curtime=1579890886
d [24/Jan/2020:21:34:46.413934 +0300] cupsdCheckJobs: Job 2 - dest="Test2", printer=0x666cbee273c0, state=5, cancel_time=1579901686, hold_until=0, kill_time=0, pending_cost=0, pending_timeout=0
d [24/Jan/2020:21:34:46.413937 +0300] cupsdCheckJobs: Job 3 - dest="Test1", printer=0x666cbeea8d10, state=5, cancel_time=1579901686, hold_until=0, kill_time=0, pending_cost=0, pending_timeout=0
d [24/Jan/2020:21:34:46.413941 +0300] cupsdCheckJobs: Job 4 - dest="Test1", printer=(nil), state=4, cancel_time=0, hold_until=1579878000, kill_time=0, pending_cost=0, pending_timeout=0
d [24/Jan/2020:21:34:46.413948 +0300] cupsdSetJobState(job=0x666cbeec10f0(4), state=4, newstate=3, action=0, message="Job hold expired.")
d [24/Jan/2020:21:34:46.413954 +0300] cupsdAddEvent(event=job-state-changed, dest=(nil)(), job=0x666cbeec10f0(4), text="%s", ...)
D [24/Jan/2020:21:34:46.413957 +0300] Discarding unused job-state-changed event...
I [24/Jan/2020:21:34:46.413960 +0300] [Job 4] Job hold expired.
D [24/Jan/2020:21:34:46.413963 +0300] cupsdMarkDirty(---J-)
D [24/Jan/2020:21:34:46.413966 +0300] cupsdSetBusyState: newbusy="Active clients, printing jobs, and dirty files", busy="Active clients, printing jobs, and dirty files"
D [24/Jan/2020:21:34:46.413968 +0300] cupsdSetBusyState: newbusy="Active clients, printing jobs, and dirty files", busy="Active clients, printing jobs, and dirty files"
D [24/Jan/2020:21:34:46.413972 +0300] [Client 4] Returning IPP successful-ok for Print-Job (ipp://127.0.0.1:8631/printers/Test1) from localhost.
D [24/Jan/2020:21:34:46.413976 +0300] [Client 4] Content-Length: 213
D [24/Jan/2020:21:34:46.413979 +0300] [Client 4] cupsdSendHeader: code=200, type="application/ipp", auth_type=0
d [24/Jan/2020:21:34:46.414000 +0300] cupsdAddSelect(fd=12, read_cb=0x666cbeb86df0, write_cb=0x666cbeb864d0, data=0x666cbee10310)
d [24/Jan/2020:21:34:46.414006 +0300] select_timeout: JobHistoryUpdate=1579890916
D [24/Jan/2020:21:34:46.414010 +0300] [Client 4] con->http=0x666cbee1b710
D [24/Jan/2020:21:34:46.414015 +0300] [Client 4] cupsdWriteClient error=0, used=0, state=HTTP_STATE_POST_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=213, response=0x666cbeeb4960(IPP_STATE_IDLE), pipe_pid=0, file=-1
D [24/Jan/2020:21:34:46.414027 +0300] [Client 4] Writing IPP response, ipp_state=IPP_STATE_DATA, old wused=0, new wused=0
D [24/Jan/2020:21:34:46.414031 +0300] [Client 4] bytes=0, http_state=0, data_remaining=213
D [24/Jan/2020:21:34:46.414038 +0300] [Client 4] Flushing write buffer.
D [24/Jan/2020:21:34:46.414041 +0300] [Client 4] New state is HTTP_STATE_WAITING
d [24/Jan/2020:21:34:46.414044 +0300] cupsdAddSelect(fd=12, read_cb=0x666cbeb86df0, write_cb=(nil), data=0x666cbee10310)
D [24/Jan/2020:21:34:46.414048 +0300] [Client 4] Waiting for request.
D [24/Jan/2020:21:34:46.414054 +0300] cupsdSetBusyState: newbusy="Printing jobs and dirty files", busy="Active clients, printing jobs, and dirty files"
d [24/Jan/2020:21:34:46.414057 +0300] select_timeout: JobHistoryUpdate=1579890916
d [24/Jan/2020:21:34:46.414209 +0300] [Client 4] cupsdReadClient: error=0, used=0, state=HTTP_STATE_WAITING, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=0, request=(nil)(), file=-1
D [24/Jan/2020:21:34:46.414227 +0300] [Client 4] POST /printers/Test1 HTTP/1.1
D [24/Jan/2020:21:34:46.414231 +0300] cupsdSetBusyState: newbusy="Active clients, printing jobs, and dirty files", busy="Printing jobs and dirty files"
D [24/Jan/2020:21:34:46.414237 +0300] [Client 4] Read: status=200, state=6
d [24/Jan/2020:21:34:46.414242 +0300] cupsdFindBest: uri="/printers/Test1", limit=10...
d [24/Jan/2020:21:34:46.414245 +0300] cupsdFindBest: best=NONE
d [24/Jan/2020:21:34:46.414248 +0300] [Client 4] con->uri="/printers/Test1", con->best=(nil)()
D [24/Jan/2020:21:34:46.414250 +0300] [Client 4] No authentication data provided.
d [24/Jan/2020:21:34:46.414254 +0300] cupsdIsAuthorized: con->uri="/printers/Test1", con->best=(nil)()
D [24/Jan/2020:21:34:46.414272 +0300] [Client 4] 1.1 Hold-Job 52480
d [24/Jan/2020:21:34:46.414277 +0300] cupsdProcessIPPRequest(0x666cbee10310[4]): operation_id=000c(Hold-Job)
d [24/Jan/2020:21:34:46.414280 +0300] cupsdProcessIPPRequest: operation-attributes-tag
d [24/Jan/2020:21:34:46.414283 +0300] cupsdProcessIPPRequest: attributes-charset charset 'utf-8'
d [24/Jan/2020:21:34:46.414286 +0300] cupsdProcessIPPRequest: attributes-natural-language naturalLanguage 'en'
d [24/Jan/2020:21:34:46.414288 +0300] cupsdProcessIPPRequest: printer-uri uri 'ipp://127.0.0.1:8631/printers/Test1'
d [24/Jan/2020:21:34:46.414295 +0300] cupsdProcessIPPRequest: job-id integer '4'
d [24/Jan/2020:21:34:46.414298 +0300] cupsdProcessIPPRequest: requesting-user-name nameWithoutLanguage 'user'
D [24/Jan/2020:21:34:46.414303 +0300] Hold-Job ipp://127.0.0.1:8631/printers/Test1
d [24/Jan/2020:21:34:46.414307 +0300] hold_job(0x666cbee10310[4], ipp://127.0.0.1:8631/printers/Test1)
d [24/Jan/2020:21:34:46.414310 +0300] validate_user(job=4, con=4, owner="user", username=0x7ffe78f309d0, userlen=1024)
d [24/Jan/2020:21:34:46.414314 +0300] cupsdFindPolicyOp(p=0x666cbee061f0, op=c(Hold-Job))
d [24/Jan/2020:21:34:46.414316 +0300] cupsdFindPolicyOp: Found wildcard match...
d [24/Jan/2020:21:34:46.414319 +0300] cupsdIsAuthorized: con->uri="/printers/Test1", con->best=0x666cbee0aa90((null))
d [24/Jan/2020:21:34:46.414322 +0300] cupsdIsAuthorized: owner="user"
d [24/Jan/2020:21:34:46.414325 +0300] cupsdIsAuthorized: level=CUPSD_AUTH_ANON, type=None, satisfy=CUPSD_AUTH_SATISFY_ALL, num_names=0
d [24/Jan/2020:21:34:46.414328 +0300] cupsdIsAuthorized: op=0(0x0000)
d [24/Jan/2020:21:34:46.414331 +0300] cupsdIsAuthorized: auth=CUPSD_AUTH_ALLOW...
d [24/Jan/2020:21:34:46.414334 +0300] cupsdSetJobHoldUntil(job=0x666cbeec10f0(4), when="indefinite", update=1)
D [24/Jan/2020:21:34:46.414338 +0300] cupsdMarkDirty(---J-)
D [24/Jan/2020:21:34:46.414341 +0300] cupsdSetBusyState: newbusy="Active clients, printing jobs, and dirty files", busy="Active clients, printing jobs, and dirty files"
d [24/Jan/2020:21:34:46.414344 +0300] cupsdSetJobHoldUntil: hold_until=0
d [24/Jan/2020:21:34:46.414347 +0300] cupsdSetJobState(job=0x666cbeec10f0(4), state=3, newstate=4, action=0, message="Job held by \"%s\".")
d [24/Jan/2020:21:34:46.414352 +0300] cupsdAddEvent(event=job-state-changed, dest=(nil)(), job=0x666cbeec10f0(4), text="%s", ...)
D [24/Jan/2020:21:34:46.414355 +0300] Discarding unused job-state-changed event...
E [24/Jan/2020:21:34:46.414358 +0300] [Job 4] Job held by \"user\". 
`
Changing "weekend" to "indefinite" in 4.3-job-ops.test temporary resolves this issue. Type of "Job held by.." message changes from "E" to "I".

**Comment by michaelrsweet** [comment]
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
