### ISSUE TITLE
Multiple Printers of Same Type

### ISSUE THREAD

**Issue by p0fi** [apple/cups#5727]
## Description
We are in a situation where we need to have 2 printers of exactly the same model and they need to be connected to a Linux machine and both just work. The problem is that when we install a printer, the DeviceURI contains the serial number of the printer. Therefore if we connect the other printer, the print jobs will not work until we change the serial number in the `printers.conf` file or completely reinstall the printer. 

## Suggestion 
Make the deviceURI ignore the serial number?

Or is there another way to achieve that both printers are directly working once connected to the machine?

**Comment by jsmeix** [comment]
Because you did not tell about your device URI
I blindly guess
"A careless backend for a single USB printer" in
https://en.opensuse.org/SDB:Using_Your_Own_Backends_to_Print_with_CUPS
might help you.

**Comment by PeterBurner** [comment]
hi there
I'm new to cups and I'm trying to achieve something similar
would it be possible to add both printers to the same queue/class and let cups assign the print job to the printer that is currently connected?

**Comment by jsmeix** [comment]
@PeterBurner 
I think your question points to an alternative solution
to what @p0fi asked for: Using so called "classes".

So when there are two identical printers one can create two
print queues (one for each of them) and put both queues
into a class and print via this class.

Also when there are several basically same printers
(i.e. printers with sufficiently same functionality and features)
one can create print queues for each of them and put all
those queues into a class and print via this class.

**Comment by PeterBurner** [comment]
cool
thanks for your help @jsmeix
