### ISSUE TITLE
CUPS does not report failing to start web-interface in logs.

### ISSUE THREAD

**Issue by the-vindicar** [apple/cups#5728]
I'm using CUPS on a debian machine to create a network print-server.
By default `/lib/systemd/system/cups.service` does not have `After=network.target` directive. Thus, when the machine is booted, CUPS web-interface is unreachable due to network not having been intitialized yet, and it takes a manual service restart at a later time for it to start working. 

While I fixed the initial issue by adding `After=network.target` dependency into `[Unit]` section of the aforementioned file, it took me a while to figure it out since CUPS did not log any errors.
`systemctl` reports that CUPS is running:
```
$ sudo systemctl status cups
● cups.service - CUPS Scheduler
   Loaded: loaded (/lib/systemd/system/cups.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-01-26 13:59:49 MSK; 2min 39s ago
     Docs: man:cupsd(8)
 Main PID: 364 (cupsd)
    Tasks: 3 (limit: 4664)
   Memory: 8.9M
   CGroup: /system.slice/cups.service
           ├─364 /usr/sbin/cupsd -l
           └─454 /usr/lib/cups/notifier/dbus dbus://

Jan 26 13:59:49 VindicarServer systemd[1]: Started CUPS Scheduler.
```
As you can see, there is nothing in the logs except for "Starting" line. Mind, I have `LogLevel debug` set in my [cupsd.conf](https://github.com/apple/cups/files/4113367/cupsd.conf.txt).

Perhaps CUPS should either:
a) report failing to start web-interface due to network failure. It should be easier to implement, and it will still require some configuration on user's part, but at least there will be a clear explanation of what went wrong.
b) repeat attempts to start web-interface. This is supposedly harder to implement, and complicates the behaviour, but will require no effort on user's part.

Version information:
```
> uname -a
Linux VindicarServer 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
```
CUPS Version: 2.2.10-6+deb10u1
HP-LIP Version: 3.19.12

**Comment by michaelrsweet** [comment]
The web interface is enabled but not accessible. And this is something that I think Debian's CUPS package has since fixed. If not, please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
