### ISSUE TITLE
No Plugged Printer ,Yet Cups online

### ISSUE THREAD

**Issue by DurtyDev** [apple/cups#5729]
So issue is there's no printer plugged to the machine or not, Cups service is actively handling remote requests. 
1 For Whom ? 
2 From Where? 
Why.  
Possible Security issue in that. I'm getting all kinds of errors from cups bad ipp HTML etc.

**Comment by michaelrsweet** [comment]
The standard configuration has cupsd launched on demand, and should only be running if someone is talking to it. It needs to be this way to allow a client to add a printer, for example... :)
