### ISSUE TITLE
the "printer-type" value don't match the result of cupsCheckDestSupported(...)

### ISSUE THREAD

**Issue by ChoiChoongHo94** [apple/cups#5730]
CUPS version: 2.2.10

When I want to know whether a printer supports the `duplex` capability, I know there are two ways. One is using the value of `printer-type` option, the other is using `cupsCheckDestSupported(...)` function. But, the results of both aren't same as each other. (I guess the `PPD` file of the tested printer might be wrong.)

My test code:
```
cups_dest_t* dest = cupsGetNamedDest(CUPS_HTTP_DEFAULT, argv[1], NULL);
cups_dinfo_t* dinfo = cupsCopyDestInfo(CUPS_HTTP_DEFAULT, dest);
http_t* http = cupsConnectDest(dest, CUPS_DEST_FLAGS_DEVICE, 3000, NULL, NULL, 0, NULL, NULL);

int printer_type = cupsGetIntegerOption("printer-type", dest->num_options, dest->options);

cout << cupsCheckDestSupported(http, dest, dinfo, "sides", NULL) << '\n'
  << cupsCheckDestSupported(http, dest, dinfo, "sides-supported", NULL) << '\n'
  << (printer_type & CUPS_PRINTER_DUPLEX) << '\n';

cout << printer_type << '\n';
```

Result:
```
1    << cupsCheckDestSupported(http, dest, dinfo, "sides", NULL)
1    << cupsCheckDestSupported(http, dest, dinfo, "sides-supported", NULL)
0    << printer-type & CUPS_PRINTER_DUPLEX
8401100    << printer-type
```

**Comment by michaelrsweet** [comment]
The presence of the "sides" attribute isn't sufficient, you need to look for the values 'two-sided-long-edge' and/or 'two-sided-short-edge', or just test that it has more than 1 value.
