### ISSUE TITLE
CUPS reads PPD boolean values case-sensitively

### ISSUE THREAD

**Issue by karlrelton** [apple/cups#5731]
The CUPS ppd generator can add boolean options to the ppd, with the boolean all in lower case. E.g.
cups/ppd_cache.c line 3182:
cupsFilePuts(fp, "*cupsManualCopies: true\n");

However, the CUPS ppd reader code checks options using a case-sensitive string comparison. E.g. cups/ppd.c line 882:
ppd->manual_copies = !strcmp(string, "True");

This means that some options in generated ppds appear to be correct, but in fact are then not being honoured when cups reads & uses the ppd. I can confirm this by seeing that filter pdftopdf does NOT do software copies evening though it has
*cupsManualCopies: true

If I change the ppd myself to 'True' the pdftopdf starts doing software copies as expected.

The same problem will for sure apply to other boolean options as well ... but I wonder how many IPP printers with machine-generated ppds are out there that aren't using cupsManualCopies as expected?

**Comment by michaelrsweet** [comment]
Fixed in OpenPrinting CUPS.
