### ISSUE TITLE
Suggest ipp backend use same heuristic for copies_remaining as squashing 'copies' job parameter

### ISSUE THREAD

**Issue by karlrelton** [apple/cups#5732]
Currently backend/ipp.c sets its working variable copies_remaining to either the user requested copies (from argv[4]) or truncates it to 1. The truncation happens if the printer appears to support hardware copies, OR we are streaming from stdin.

The test of hardware copies comes from copies_sup, which comes from querying the printer 'copies-supported' attribute - which on a first read seems plausible.

However there are flows out there in the wild which pass to the ipp backend a prepared raster file (argv[6]) which has had software copies already applied (e.g. by pdftopdf where *cupsManualCopies: True). The same copies argument (argv[4]) is passed to both pdftopdf and the eventual ipp backed (as is typical).

Then, if the targetted device reports back that hardware copies are not supported (or, as in my actual printer copies-supported = 1-1) the copies_remaining gets set to argv[4] and so I end up with n*n copies physically printed.
[This will become more prevalent when https://github.com/apple/cups/issues/5731 is fixed!)

If the ipp backend also honoured *cupsManualCopies in determining copies_remaining then this problem would be solved.
However I can see from comments that the aim is to lose ppds altogether - so I can understand if you didn't want to adopt that route.

---

ipp.c new_request() calls _cupsConvertOptions which has its own heuristics for dealing with the number of copies (to pass on to the printer). In particular if the format is image/... or application/vnd.cups-raster it assumes software copies have been applied upstream and so it truncates copies (to pass on to the printer) to 1.

It seems to me that if the ipp backend already has such hard-wired heuristic code here, then the same heuristic could be applied to the copies_remaining ... i.e. forcing it to 1 for certain formats where we expect upstream software copies.

**Comment by michaelrsweet** [comment]
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
