### ISSUE TITLE
how to get paper status

### ISSUE THREAD

**Issue by DeMaH4uK** [apple/cups#5734]
Sorry for my English)
I can’t understand how to get a printer status such as “no paper”, “paper is running out”, “cover is open” or “printer is turned off”.
As I just did not try to pick the depths of the Internet, there just rubbish I didn’t need was like how to print it.
Help, please, somebody.

**Comment by ShaikhShoeb01** [comment]
Use getPrinterAttributes() to get attributes of the printer, it  returns many parameters. One of the them is 'printer-state-reasons'  which changes when the state of the printer changes. When everything is ok , the printer-state-reasons is ['none']
For details just read 'Internet Printing Protocol/1.1: Model and Semantics'
I am using in python ,so don't aware if there is other function-name for getPrinterAttributes
