### ISSUE TITLE
Backend returned status 4 (stop printer)

### ISSUE THREAD

**Issue by kiambogo** [apple/cups#5735]
Hello! First off, thanks for all the efforts in maintaining this project. 

I'm using 3 instances of CUPS (v2.2.7) running on Ubuntu (v18.04) to send print jobs to a group of printers (~24 printers). Infrequently (every 800? jobs), I'm seeing that the printer will be paused in CUPS and all further requests to print will just queue up. All queued jobs will print successfully once I resume the printer in CUPS. 

I enabled debug logging and waited until it happened, and noticed that 2 of the instances reported the printer was paused. I grabbed the logs from both, and found the logs describing the issue:

```
D [07/Feb/2020:22:17:05 +0000] [Job 15] final_content_type=\"application/pdf\", document_format=\"application/pdf\"
D [07/Feb/2020:22:17:05 +0000] [Job 15] Validate-Job IPP/2.0
D [07/Feb/2020:22:17:05 +0000] [Job 15] printer-uri=\"ipp://172.20.1.232:631/\"
D [07/Feb/2020:22:17:05 +0000] [Job 15] requesting-user-name=\"root\"
D [07/Feb/2020:22:17:05 +0000] [Job 15] job-name=\"<redacted>.pdf\"
D [07/Feb/2020:22:17:05 +0000] [Job 15] document-format=\"application/pdf\"
D [07/Feb/2020:22:17:05 +0000] [Job 15] Adding standard IPP operation/job attributes.
D [07/Feb/2020:22:17:05 +0000] [Job 15] IPP/2.0 Validate-Job #2
D [07/Feb/2020:22:17:05 +0000] [Job 15] ---- operation-attributes-tag ----
D [07/Feb/2020:22:17:05 +0000] [Job 15] attributes-charset charset utf-8
D [07/Feb/2020:22:17:05 +0000] [Job 15] attributes-natural-language naturalLanguage en-us
D [07/Feb/2020:22:17:05 +0000] [Job 15] printer-uri uri ipp://172.20.1.232:631/
D [07/Feb/2020:22:17:05 +0000] [Job 15] requesting-user-name nameWithoutLanguage root
D [07/Feb/2020:22:17:05 +0000] [Job 15] job-name nameWithoutLanguage <redacted>.pdf
D [07/Feb/2020:22:17:05 +0000] [Job 15] document-format mimeMediaType application/pdf
D [07/Feb/2020:22:17:05 +0000] [Job 15] ---- job-attributes-tag ----
D [07/Feb/2020:22:17:05 +0000] [Job 15] print-color-mode keyword auto-monochrome
D [07/Feb/2020:22:17:05 +0000] [Job 15] print-quality enum normal
D [07/Feb/2020:22:17:05 +0000] [Job 15] sides keyword two-sided-short-edge
D [07/Feb/2020:22:17:05 +0000] [Job 15] multiple-document-handling keyword separate-documents-collated-copies
D [07/Feb/2020:22:17:05 +0000] [Job 15] ---- end-of-attributes-tag ----
D [07/Feb/2020:22:17:05 +0000] [Job 15] Validate-Job: server-error-internal-error (Success)
D [07/Feb/2020:22:17:05 +0000] [Job 15] ---- end-of-attributes-tag ----
D [07/Feb/2020:22:17:05 +0000] [Job 15] PID 5872 (/usr/lib/cups/backend/ipp) stopped with status 4.
I [07/Feb/2020:22:17:05 +0000] [Job 15] Backend returned status 4 (stop printer)
D [07/Feb/2020:22:17:05 +0000] Discarding unused job-state-changed event...
I [07/Feb/2020:22:17:05 +0000] [Job 15] Printer stopped due to backend errors; please consult the error_log file for details.

```

While similar to https://github.com/apple/cups/issues/5578, the difference here is that in this case it appears that the Validate-Job IPP command completes successfully. Any idea why the backend is existing with status 4 if the Validate-Job seems to be completing successfully? Do you still think that it is network related (dropped packets, etc)? 

Any ideas on how to remedy this issue, or at least prevent the printer from being paused? I have tried setting the ErrorPolicy to `retry-job` in `cupsd.conf`, but it doesn't seem to be respected. 

One additional piece of info - I'm programatically deleting the file that I issue the print command with after CUPS `lp` command exits successfully. Will the file be fully read and passed to the printer prior to CUPS `lp` returning successfully, or could that be a potential issue?

**Comment by michaelrsweet** [comment]
@kiambogo No, the file from lp is copied to the spool directory, so it is 100% safe to delete afterwards.

The Validate-Job request is failing on the printer with a status that says "this printer is broken". We are looking at alternatives for this sort of situation over in the [OpenPrinting CUPS](https://github.com/openprinting/cups) project - see [issue #111](https://github.com/OpenPrinting/cups/issues/111) and add your comments so we can improve things...
