### ISSUE TITLE
Run cups(d) without colord - new option or graceful degradation please

### ISSUE THREAD

**Issue by ned64** [apple/cups#5736]
On my system there is no `colord` due to several reasons. Mainly, as part of a part of standard security hardening I have reduced attack surface by removing daemons I don't need.

I do not need the colour management features provided by `colord` at all.

Upon one of the past updates of `cups` printing was disabled completely because `cupsd` tries to contact `colord` and fails completely as it isn't running.  The error was difficult to find, too.

Please allow the running of `cupsd` and printing without `colord`, either by ignoring colour management if `colord` cannot be found on D-Bus or doesn't reply (graceful degradation) or by adding a `cupsd` config option not to try `colord` in the first place (disable colour management by `colord` option).

Perhaps graceful degradation is perhaps more elegant - a warning could be issued but printing would continue.  The situation would be the same if `colord` ran but the printer device weren't managed by it.

**Comment by michaelrsweet** [comment]
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.

**Comment by ned64** [comment]
Thanks, I have opened https://github.com/OpenPrinting/cups/issues/193
