### ISSUE TITLE
bad error message

### ISSUE THREAD

**Issue by 532910** [apple/cups#5737]
Web interface says:
Modify Printer <PRINTER> Error
Unable to modify printer: Unable to copy PPD file.

/var/log/cups/error_log says:
```
E copy_model: empty PPD file
E [Client 28] Returning IPP server-error-internal-error for CUPS-Add-Modify-Printer (ipp://localhost/printers/<PRINTER>) from localhost.
```

The real error is that openprinting-ppds crashes with MemoryError:
https://github.com/vitorbaptista/pyppd/issues/2

**Comment by vitorbaptista** [comment]
Any ideas on how we could improve this error message from PyPPD? Or even, if we can? Maybe this is an issue with the web printer interface?

**Comment by michaelrsweet** [comment]
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
