### ISSUE TITLE
CGI scripts can only print one header, and only if they are known

### ISSUE THREAD

**Issue by betterworld** [apple/cups#5741]
Hi,

I found that in CGI scripts that print multiple HTTP headers, only the first one will be passed to the client. The reason seems to be the handling of the `sent_header` flag here.

https://github.com/apple/cups/blob/1f2a315c2b3e2f78c37c1505fc66909ad01df85e/scheduler/client.c#L2402-L2415

So for instance if you have a script like this:

```python
#!/usr/bin/env python3
print("Date: Mon, 17 Feb 2020 00:23:46 GMT")
print("Content-Type: text/plain")
print("")
```
 Only the Date header will be seen by the client.

I stumbled upon this because I have a CGI script that tries to send the `Access-Control-Allow-Origin` from a CGI script. This header will actually never work because it is not recognized by `httpFieldValue`.

My original script wanted to set the headers `Access-Control-Allow-Origin` and `Content-Type`. I'll be happy if this can be made possible in CUPS. Sorry if these are actually two seperate bug reports (1. only one header possible, 2. the origin header is not known).

By the way, this CGI script ran on an old server in CUPS 1.5.3. The old version did not have any problems with these headers.

**Comment by michaelrsweet** [comment]
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
