### ISSUE TITLE
Description not stored while adding a printer

### ISSUE THREAD

**Issue by es20490446e** [apple/cups#5746]
HOW TO REPRODUCE:
- Add a printer, selecting a different description than the default.

RESULT:
- The printer is added with the default description.

SYSTEM INFO:
- cups 2.3.1

**Comment by michaelrsweet** [comment]
@es20490446e 

What OS?

How did you add the printer?

**Comment by es20490446e** [comment]
I don't remember.

I have tested that it doesn't happen using the web interface. So either the bug is gone, or it belonged to a different component.

Thanks for the help 🍮
