### ISSUE TITLE
CUPS leaving files behind after printing in /var/spool/cups

### ISSUE THREAD

**Issue by tps800** [apple/cups#5747]
CUPS is leaving files behind after printing in /var/spool/cups. These may, in short time, fill the filesystem `/var/spool/cups` resides in.
```
# ls -la /var/spool/cups
[...]
-rw-r-----. 1 root lp 53148545 24. Feb 04:51 d28233-001
-rw-r-----. 1 root lp 53148545 24. Feb 04:51 d28234-001
-rw-r-----. 1 root lp 53148545 24. Feb 04:51 d28235-001
-rw-r-----. 1 root lp 53148545 24. Feb 04:51 d28236-001
-rw-r-----. 1 root lp 53148545 24. Feb 04:51 d28237-001
-rw-r-----. 1 root lp 53148545 24. Feb 05:20 d28238-001
-rw-r-----. 1 root lp 53148545 24. Feb 05:20 d28239-001
-rw-r-----. 1 root lp 53148545 24. Feb 05:20 d28240-001
-rw-r-----. 1 root lp 53148545 24. Feb 05:20 d28241-001
-rw-r-----. 1 root lp 53148545 24. Feb 05:21 d28242-001
[...]
```
Filling about 120GiB at the moment. All are printed. No errors. Non of them should exist any more.

```
PreserveJobFiles No
PreserveJobHistory No
```

is set in `/etc/cups/cupsd.conf` but seems ignored. Look like a bug within CUPS or CUPS dokumentation.

### Versions:
```
cups-libs-1.6.3-40.el7.x86_64
cups-filters-1.0.35-26.0.1.el7_7.1.x86_64
cups-1.6.3-40.el7.x86_64
cups-filesystem-1.6.3-40.el7.noarch
cups-pdf-2.6.1-7.el7.x86_64
ghostscript-cups-9.25-2.el7_7.3.x86_64
cups-client-1.6.3-40.el7.x86_64
cups-filters-libs-1.0.35-26.0.1.el7_7.1.x86_64
gutenprint-cups-5.2.9-18.el7.x86_64
```
and latest development cups as found on github.

**Comment by gmuth** [comment]
https://www.cups.org/doc/man-lp.html says about option `-H`:
Use a value of `restart` with the -i option to restart a completed job.
The only way to restart a completed job is to preserve the document for some time.
I expect the spooled documents to be removed by cups after one day.

**Comment by michaelrsweet** [comment]
You really need to use a current release of CUPS. I suspect this is due to a known bug that was fixed a long time ago. If not, please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
