### ISSUE TITLE
Web interface asks for password but doesn't show prompt

### ISSUE THREAD

**Issue by josvanr** [apple/cups#5748]
when ever I try to cancel a print job via the web interface, cups says I have to login, but then doesnt show a window or form where I can put the username and password. It just prints the message as text in the browser window. So I'm just stuck and have to turn off the printer or something.

My os is ubuntu 18.04

**Comment by michaelrsweet** [comment]
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
