### ISSUE TITLE
Printing issue Cups on MAC, 1 or 2 sided gets override

### ISSUE THREAD

**Issue by koen-v-o** [apple/cups#5749]
Hi all,

To start this topic I have been testing several hours on this issue.. I have tested on all versions of mac from 10.13 to the newest 10.15 and I have it anywhere.. Contacted apple support and they just redirected me to here. They can't help this is a cups issue they say.. 

So lets get started.

For a customer of mine I need to add several print queues on MAC. 

In my case the printers are added by LPD on IP. (have tested all possible combinations like ipp, AirPrint, ... and all possible drivers also generic drivers).

So you add any printer with any driver on any way..

for my case that's a printer 10.X.X.X ip added using LPD.

I add this printer several times (to use later for 1 sided, 2 sided, staple, punch , ...)

I made some workflows using automator on mac to directly speak to those queues so they must be setup like this. After adding all those printers I go to http://localhost:631 activate cups using the command the first time and go to printing defaults. I change all the defaults like i want. (So far so good).

I'm all done and think like ok cool this is working.. But then it comes.. The last printer I add and change the printing defaults decides about all other printers whether they are 1 or 2 sided.

For some strange reason the last added printer decides and changes all others printers also.. So change last printer to 1 sided and all other printers will be 1 sided. change it to 2 sided and all other printers will be 2 sided.. Even if the printers have other ip's, drivers, way to add, ...

I've searched a lot online already but can't find anything about it. One suggestion I've got is check while printing if in the printer dialog the preset option is saying "default settings" and not "last used settings" this is also how it should be at "default settings".

I hope someone can help me out on this cause it seems a large bug..

Thanks in advance!

K.

**Comment by chalmerssys** [comment]
How are you adding these printers, with lpadmin or with the web interface? How are you setting defaults, with the webinterface??

**Comment by koen-v-o** [comment]
I'm adding the printers directly on MAC, using system preferences - printers (using ipp / lpd / ...)

I'm setting the defaults in cups directly -> printers -> set default options

**Comment by chalmerssys** [comment]
When you write "in cups directly" do you mean http://localhost:631?

**Comment by koen-v-o** [comment]
exactly :-)

**Comment by chalmerssys** [comment]
In my experience, setting options in CUPS can be a bit tricky and not always intuitive...
You click  "Set default options" in the Administration menu  for each printer? 
That should work.
Can you post your /etc/cups/printers.conf file? 
Do you have an /etc/cups/lpoptions file? What are the contents of that file?

**Comment by koen-v-o** [comment]
That's the way i do it. Tried om multiple MAC's and all have the same issue..
I've added my CUPS folder :-)

thanks already!

[cups.zip](https://github.com/apple/cups/files/4267499/cups.zip)

**Comment by chalmerssys** [comment]
If you start a terminal and execute the following command, what is the output:
cat  $HOME/.cups/lpoptions
This should be done as the user that is submitting print jobs.

**Comment by koen-v-o** [comment]
Default test2

**Comment by koen-v-o** [comment]
is just showing the default printer (in my case last used printer)

**Comment by chalmerssys** [comment]
OK, so these lpoptions files are mostly/only used when printing from a terminal I think (with the lp command), so they are probably not relevant for solving your problem. 
I guess you are printing from the GUI and not from the command line?
And you need to set defaults for any account using each printer queue?

**Comment by chalmerssys** [comment]
Try changing the ppd options with the lpadmin command. 
First list options with:
lpoptions -p printername -l
Then set options with the lpadmin command:
lpadmin -p printername  -o name=value
These commands can be tricky to use because they don't always print error messages when things go wrong and sometimes they don't do what one expects them to do...

**Comment by koen-v-o** [comment]
Well i'm basically using automator (scripting) to batch print pdf files to those queues. So not using any GUI.

but the thing is you can reproduce it pretty easy..

you add two printers.. 

add the first and setup the printing defaults using (localhost:631) 2 sided
add the 2nd printer and setup the printing defaults 1 sided.

you will see both printers will be 1 sided.. Its really strange..

**Comment by chalmerssys** [comment]
I tested on my Mac, and when setting options with lpadmin command I did not get the problem you describe.

**Comment by koen-v-o** [comment]
can you try doing it without lpadmin? just using cups?

**Comment by chalmerssys** [comment]
I usually have the webinterface disabled. When I enable it says it will send my password unencrypted over the network so I don't fancy doing that.

**Comment by koen-v-o** [comment]
ok i understand. could you pass me the commands to setup 1 or 2 sided using lpadmin? then i'll try it myself :)

thanks for the help already!

**Comment by chalmerssys** [comment]
Duplex:
lpadmin -p myprinter -o Duplex=DuplexNoTumble
No duplex:
lpadmin -p myprinter -o Duplex=None
+ see above....

**Comment by koen-v-o** [comment]
I'm experiencing the same issues, i guess you added the printers using lpadmin to?

**Comment by chalmerssys** [comment]
Some of them I might have added with lpadmin, but I often use the GUI for that on this particular computer.

**Comment by michaelrsweet** [comment]
As the printing options from the GUI are controlled by the macOS print software and *not* CUPS, you'll need to report this using <bugreport.apple.com>.

**Comment by Dano1970** [comment]
Stop

Danos Gmail
