### ISSUE TITLE
Ipptool comma separated values fail to being passed as array of values

### ISSUE THREAD

**Issue by waplet** [apple/cups#5751]
When passing comma seprated value for Ipptool it won't reduce them to array. Maybe suggestion or this is a bug?

`ipptool -v -X -d events=job-completed,job-created,job-state-changed,job-stopped ipp://127.0.0.1/ /Users/w/ipp/subscribe.txt`
Inspecting a packets with Wireshark i got such bad case.

![image](https://user-images.githubusercontent.com/5472594/75784409-d46c3800-5d6a-11ea-98e5-2179d15f3735.png)

If the variable although is not used in subscribe.txt but hardcoded values, it produces correct result.

![image](https://user-images.githubusercontent.com/5472594/75784474-e77f0800-5d6a-11ea-8d50-b442c6ce68b9.png)

**Comment by michaelrsweet** [comment]
Please re-test against OpenPrinting CUPS. If the problem persists, report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
