### ISSUE TITLE
The website inferface doesn't work for anything after ":631/..."

### ISSUE THREAD

**Issue by fabianmendes** [apple/cups#5755]
Hi, I got an issue that has happened. In the beginning, I could add my printer and even print two documents but then I can't go into the localhost:631/help either!

**Comment by iwkse** [comment]
Same here. localhost:631 gives ERR_EMPTY_RESPONSE while any other command like :631/admin or :631/help gives a white page.

Any help?

**Comment by michaelrsweet** [comment]
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
