### ISSUE TITLE
how about we create a QT based application for this

### ISSUE THREAD

**Issue by bougyo** [apple/cups#5758]
Hi everyone, i was thinking of creating QT base application for CUPS aside of having the web-based. Can you tell me if we can go for this or may be not and the web-based is better for anything.

**Comment by salgernon** [comment]
There's absolutely no reason that a QT front end to the CUPS server couldn't be written - but it wouldn't need to be a part of CUPS itself.  You could either use the command line tools, executed as subprocesses from your QT application, or you could invoke the HTTP server and interpret the results.

The HTTP Server responds either with HTML, or it can be driven by sending IPP using HTTP as the transport.  The Mac UI is built this way, for example.

**Comment by michaelrsweet** [comment]
It can be done and has been done in KDE.
