### ISSUE TITLE
Fully resolve DNS-SD discovered .local hostnames using Avahi instead of NSS

### ISSUE THREAD

**Issue by unrelentingtech** [apple/cups#5759]
Let's say we have (both on the server and the client):

- an IPv6-only Avahi setup
- FreeBSD (where `nss_mdns` can't return multiple address families like on modern Linux which has the addrtuple stuff)

and we're trying to auto configure a printer with DNS-SD.

The `dnssd` backend returns a URL that still involves the `.local` hostname:

```
I [25/Mar/2020:14:38:51 +0300] [Job 3] Started backend /usr/local/libexec/cups/backend/dnssd (PID 25496)
D [25/Mar/2020:14:38:51 +0300] [Job 3] Resolving \"HP LaserJet P1102w @ solitude._ipp._tcp.local\"...
D [25/Mar/2020:14:38:51 +0300] [Job 3] STATE: +connecting-to-device
D [25/Mar/2020:14:38:51 +0300] [Job 3] Resolving \"HP LaserJet P1102w @ solitude\", regtype=\"_ipp._tcp\", domain=\"local.\"...
D [25/Mar/2020:14:38:51 +0300] [Job 3] Resolved as \"ipp://solitude.local:631/printers/HP_LaserJet_Professional_P_1102w\"...
D [25/Mar/2020:14:38:51 +0300] [Job 3] STATE: -connecting-to-device,offline-report
```

and then tries to look it up:

```
D [25/Mar/2020:14:38:51 +0300] [Job 3] Executing backend \"/usr/local/libexec/cups/backend/ipp\"...
D [25/Mar/2020:14:38:51 +0300] [Job 3] STATE: +connecting-to-device
D [25/Mar/2020:14:38:51 +0300] [Job 3] Looking up \"solitude.local\"...
D [25/Mar/2020:14:38:56 +0300] [Job 3] Unable to locate printer \"solitude.local\".
```

from a quick look at the code, the function it calls does involve Avahi for URLs with more stuff.

But the resolution of a plain `something.local` hostname fails here, because it goes through getaddrinfo → `nss_mdns`, which requests IPv4 from Avahi:

```
simple-protocol.c: Got RESOLVE-HOSTNAME-IPV4 request for 'solitude.local'.
```

and, well, I only have IPv6 enabled in Avahi. oops.

I do have a patch for `nss_mdns` that falls back to the other family in that case, I can build an IPv6-only `nss_mdns`, but like..

CUPS uses Avahi directly, so maybe it shouldn't require a working `nss_mdns` type thing at all?

**Comment by michaelrsweet** [comment]
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.

Current CUPS should be requesting both IPv4 and IPv6.
