### ISSUE TITLE
cupsBackChannelRead fails with EAGAIN

### ISSUE THREAD

**Issue by jlgonzalezpisa** [apple/cups#5760]
Hello,

I have a thermal printer connected to the USB port. And I have the following code (trying to get the status of the printer):

const int MAX_READ_BYTES = 1024;
...
char buffer[MAX_READ_BYTES] = { 0 };

bytes = cupsBackChannelRead(buffer, MAX_READ_BYTES, 10.0);

if (bytes == -1)
{
  std::cerr << "ERROR: There was an error trying to read printer response: " << std::to_string(errno) <<std::endl;
}

For that code, the log shows:
[Job 322] There was an error trying to read printer response: 11

(EAGAIN errno).

I am using:
Ubuntu 18.04
Cups: 2.2.7

Thanks in advance.

**Comment by michaelrsweet** [comment]
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project. Note that we'll need to know the make and model of the printer, along with its USB vendor and product IDs ("lsusb" will show), as some printers do not support (or are buggy about) backchannel support.
