### ISSUE TITLE
How to set webui language?

### ISSUE THREAD

**Issue by BlueMax** [apple/cups#5763]
My browser is set to `en` but CUPS webui should be `de`.
I've set `DefaultLanguage de` in `cupsd.conf` but it doesn't change anything. When i change the browser language to `de` CUPS switches properly..

How can i switch the webui language in CUPS to `de` without changing the browser?

Arch Linux 5.5.13
CUPS 2.3.1
Firefox

**Comment by jschwender** [comment]
DefaultLanguage has only effect if your browser has no language for _content negotiation_ specified. If you specify `en`, the browser sends `Accept-Language: en` in the header request. A web server returns content in the requested language, if available. All correct. Why do you expect a web server to return a language that you specifically don't ask for? That is not the purpose of content negotiation. The unorthodox solution: you could replace the english html template files by german templates in the cups installation.

**Comment by michaelrsweet** [comment]
The browser sends the Accept-Language header, which cupsd uses to determine the proper language to use for the web interface. But if the web interface isn't localized for your language it will default to English.

**Comment by BlueMax** [comment]
An option to **override** that behavior to independently select the language would help for systems which are used by people with several languages.

**Comment by michaelrsweet** [comment]
@BlueMax Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.

**Comment by narcisgarcia** [comment]
A case example:
Most people with web browser localized to "ca" also understands "es". But if cups webUI isn't localized to "ca" then it switches to "en" by default.

Solutions:

- Change default WebUI language to "es"
- Force WebUI language to "es" for all visitors.
