### ISSUE TITLE
LP hangs when printer is offline and jobs are queued

### ISSUE THREAD

**Issue by ryangriggs** [apple/cups#5764]
If a job is sent to an offline USB printer using the `lp` command, the `lp` command hangs on all subsequent calls for all printers (or even if no command-line arguments are given) until the job(s) in the offline printer's queue are deleted.

CUPS version 2.2.10 (ARM)

Steps to reproduce:

- Set up multiple printers in CUPS connected to USB ports
- Take one printer offline (turn it off, unplug, etc)
- Send a job to that printer
- Try to run the `lp` command again (any/no command line arguments) - it will hang and never terminate.

**Comment by michaelrsweet** [comment]
I can't reproduce this on my Pi Zero. If you can provide complete configuration info, please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
