### ISSUE TITLE
Lexmark E120/E120n (Machine Type: 4506-100) needs usb no-reattach quirk

### ISSUE THREAD

**Issue by maciex** [apple/cups#5766]
Please add printer Lexmark E120 to the USB quirk rules. (no-reattach)
It will not print properly without it. After few prints it fails and prints rubbish.

Bus 001 Device 006: ID 043d:00cd Lexmark International, Inc. 
Machine Type: 4506-100

Similar issues:
https://github.com/apple/cups/issues/5478
https://bugs.launchpad.net/ubuntu/+source/cups/+bug/1390921
https://bugs.launchpad.net/ubuntu/+source/cups/+bug/1335558

**Comment by maciex** [comment]
The problem still exists:
OS: Fedora 32
Package: cups-2.3.3-2.fc32.x86_64

**Comment by michaelrsweet** [comment]
Fixed in OpenPrinting CUPS:

[master 1f98f0af0] Add USB quirk for Lexmark printer (Apple #5766)
