### ISSUE TITLE
Cups Support for OAuth 2.0 

### ISSUE THREAD

**Issue by kimminger** [apple/cups#5767]
Hi all,

you [mentioned](https://github.com/apple/cups/issues/5472) that CUPS would support OAuth 2.0 in future versions. 
Is this in the scope of the next release? If so, when would it be available?

We plan to use CUPS in our Cluster, but we need to integrate it with OAuth 2.0.

**Comment by deeaitsch84** [comment]
+1

**Comment by michaelrsweet** [comment]
This is being tracked for the 2.4.0 release of [OpenPrinting CUPS](https://github.com/openprinting/cups).
