### ISSUE TITLE
rastertopwg from cups 2.3.3 dumps core when printing pdf file to IPP printer

### ISSUE THREAD

**Issue by underhillian** [apple/cups#5775]
When printing a pdf file to an IPP printer using cups 2.3.3 and cups-filters 1.27.4, the filter chain fails for me.  The system log contains:

```
alcyone kernel: rastertopwg[1255]: segfault at 0 ip 00007fca6d05f1e5 sp 00007ffdf3971b38 error 4 in libc-2.31.so[7fca6cf23000+14c000]
alcyone kernel: Code: 00 00 0f 1f 00 31 c0 c5 f8 77 c3 66 2e 0f 1f 84 00 00 00 00 00 f3 0f 1e fa 89 f9 48 89 fa c5 f9 ef c0 83 e1 3f 83 f9 20 77 2b <c5> fd 74 0f c5 fd d7 c1 85 c0 0f 85 eb 00 00 00 48 83 c7 20 83 e1
alcyone systemd[1]: Started Process Core Dump (PID 1258/UID 0).
alcyone systemd-coredump[1259]: Process 1255 (rastertopwg) of user 209 dumped core.
```
and the cups error_log contains:
[cupserror.txt](https://github.com/apple/cups/files/4566267/cupserror.txt)

Reverting to cups 2.3.1 resolves the issue.

I am using Arch Linux, linux version 5.6.8.

**Comment by pacew** [comment]
I submitted a pull request last week that addressed a rastertopwg core dump - it might help: https://github.com/apple/cups/pull/5773

**Comment by underhillian** [comment]
Indeed this resolves the issue.  Thanks very much!

**Comment by michaelrsweet** [comment]
Fixed in OpenPrinting CUPS
