### ISSUE TITLE
Disable/Remove "Reason media-empty-warning"

### ISSUE THREAD

**Issue by guest239** [apple/cups#5776]
Hi,
I am using a DELL MFP 2335dn printer with CUPS 2.2.10-6+deb10u2 and still searching how to disable/remove this media-empty-warning. When printing from IOS devices I do get a pop-up for every print job due to the out-of-paper warning (which is not the case). After pressing continue the print job is being processed. Any idea? Any solution?
A.

**Comment by michaelrsweet** [comment]
There is no way to disable this, but the state keyword means that one or more trays are empty.
