### ISSUE TITLE
Ever since 2.3.3, CUPS seesm to not be able to detect any Network printers.

### ISSUE THREAD

**Issue by PolyPaul** [apple/cups#5777]
Hello! New user here to CUPS.
I'm running Manjaro GNOME 20 with the CUPS 2.3.3 packages.
After my distro's major release, CUPS web interface seems to not be able to detect any network printers in my area.
What's concerning is that downgrading to 2.3.1 or 2.2 seems to "fix" this issue. I tested this by booting into a USB drive that has a previous version of manjaro installed. All my network printers were detected as normal with no problems(something to note here is that all the other packages were up to date. Only the CUPS printing service packages were "out of date").
Could this be a bug for the current release of CUPS? I genuinely have no idea what is going on. I would love to help, but I don't have the technical know-how to provide anything useful.
I'll be offline for a while, but when I get back, I'll make sure to answer as many details about my current issue as much as possible. 
Thanks.

**Comment by KimHono** [comment]
Same issue for me:
- version 2.3.1.1 was able to work with my network printer
- version 2.3.3 can't even detect the same printer

Checking "systemctl status org.cups.cupsd.service" showed a stopped scheduler.
So I tried to downgrade, and everything is fine again !

System : ARCH Linux 5.4.41-1-lts

**Comment by paulwin1** [comment]
> Same issue for me:
> 
>     * version 2.3.1.1 was able to work with my network printer
> 
>     * version 2.3.3 can't even detect the same printer
> 
> 
> Checking "systemctl status org.cups.cupsd.service" showed a stopped scheduler.
> So I tried to downgrade, and everything is fine again !
> 
> System : ARCH Linux 5.4.41-1-lts

Which version did you downgrade to?

**Comment by KimHono** [comment]
I downgraded "cups" and "libcups" to 2.3.1-1.
And I'm still using this version while upgrading other packages as usual.

**Comment by michaelrsweet** [comment]
Please test against [OpenPrinting CUPS](https://github.com/openprinting/cups), and if the problem persists report a bug there. Thanks!

**Comment by KimHono** [comment]
Great ! It's working perfectly with cups version 1:2.3.3op2-1
