### ISSUE TITLE
printer-commands ipp attribute in get-printer-attributes response contains 'Clean' for laser printers

### ISSUE THREAD

**Issue by zdohnal** [apple/cups#5780]
Hi,

I found during investigation for https://github.com/OpenPrinting/system-config-printer/issues/50 that CUPS defines printer-command 'Clean' for laser printers when the uri contains MDNS address like:

ipp://HP%20LaserJet%20M1536dnf%20MFP%20(42307C)._ipp._tcp.local/

or when the uri is the same as in CUPS:

ipp://<server>:631/printers/<queue>

The device is laser printer so 'Clean' command can't be available.

But when device uri is defined as:

ipp://<device_address>:631/ipp/print

printer-command atttribute contains 'none'.

**Comment by michaelrsweet** [comment]
The commands come from the PPD (cupsCommands), so please forward this to the project corresponding to the PPD...
