### ISSUE TITLE
CUPS won't generate self-signed certificate

### ISSUE THREAD

**Issue by scubajeff** [apple/cups#5781]
Fresh install of Ubuntu 20.04 on a Raspberry Pi 3B+, the CUPS version is 2.3.1. WebUI won't upgrade to https, complaining that it can not authenticate the data. `/etc/cups/ssl` directory empty. I have to use `DefaultEncryption Never` in `cupsd.conf` so that I can add a printer. There are a lot of `Unable to encrypt connection: Error while reading file.` in error log.

**Comment by zdohnal** [comment]
Hi,

I have a fresh Ubuntu 20.04 in VM and generating self-signed cert worked with following procedure:

- I only applied 'cupsctl --remote-any' to Ubuntu cupsd.conf (DefaultEncryption Required is the default)
- went to 'https://<IP>:631' in Firefox
- Firefox told about security risk (self-signed certs works that way) and I accepted
- then /etc/cups/ssl is populated with self-signed cert and key

Is something different in your steps?

**Comment by scubajeff** [comment]
Try `cupsctl --remote-any`, no luck.
Is there a command which force `cups` to generate certs?

**Comment by zdohnal** [comment]
--remote-any does not generate certs, just enables remote access from any host to server port 631.

IIRC It should be generated when you access https:// in your browser. What browser do you use?

**Comment by scubajeff** [comment]
Latest firefox on a ubuntu 18.04

**Comment by zdohnal** [comment]
I'm not quite Ubuntu person (just have one latest Ubuntu in VM, if I would need it for comparison with Fedora), so I'm not sure if there is something amiss.
Please upload a file with CUPS logs from raspberry here with .txt suffix, so someone can see what happened.

Enable CUPS debug logging by:
```
cupsctl --debug-logging
```
and then capture its logs on raspberry when you access https://ip_address:631 from your client. I'm not sure what is your log setup - whether it is in journal (so you can get incindent bound logs by journalctl -u cups -f) or in /var/log/cups (use tail -f /var/log/cups/error_log), so follow your settings and reproduce the issue.
Then put those logs into .txt file and attach them here as a file.

**Comment by michaelrsweet** [comment]
@scubajeff Make sure the /etc/cups/ssl directory has been created. I ran into the same thing with a Pi Zero W and that turned out to be the issue.

**Comment by scubajeff** [comment]
The directory is there but empty. My saved backup of last setup, which is a Raspbian Buster, had a pair of crt and key file there. So maybe this is a Ubuntu 20.04 issue after all.

**Comment by schrill** [comment]
Same issue on 20.04 getting:
`D [16/Jun/2020:14:41:32 +0000] [Client 26] Server address is "192.168.0.250".
D [16/Jun/2020:14:41:32 +0000] [Client 26] Accepted from 192.168.2.103:55610 (IPv4)
D [16/Jun/2020:14:41:32 +0000] [Client 26] Waiting for request.
E [16/Jun/2020:14:41:32 +0000] [Client 26] Unable to encrypt connection: Error while reading file.
D [16/Jun/2020:14:41:32 +0000] [Client 26] Closing connection.
D [16/Jun/2020:14:41:32 +0000] cupsdSetBusyState: newbusy="Dirty files", busy="Active clients and dirty files"
I [16/Jun/2020:14:41:33 +0000] Expiring subscriptions...
I [16/Jun/2020:14:41:56 +0000] Saving subscriptions.conf...
D [16/Jun/2020:14:41:56 +0000] cupsdSetBusyState: newbusy="Not busy", busy="Dirty files"
I [16/Jun/2020:14:41:56 +0000] Expiring subscriptions...`
Tried letsencrypt certificates from location and copy them in place in ssl folder either using ServerKeychain or using ServerCertificate and ServerKey, same result as above.
The log does show it uses the certificate and does not complain after that for anything ssl related.

**Comment by michaelrsweet** [comment]
It might be an issue of insufficient random entropy for GNU TLS to generate a private key. Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.

**Comment by siepkes** [comment]
For anyone bumping into this and Googling this issue:

It isn't documented but CUPS expects to find the certificate and key in a file named after the hostname. The `ServerName` and `ServerAlias` directives **do not** influence this. CUPS determines what the hostname is by itself. You can see the behavior here: https://github.com/apple/cups/blob/95b70607ada186ddc3308a0a41be2f1c66ec47c2/cups/tls-gnutls.c#L1407-L1416

I found out about this by using `truss` on FreeBSD to see what system calls CUPS was making. Hoping to see "File not found" errors:

```
access("/usr/local/etc/cups/ssl/office-support-1.crt",R_OK) = 0 (0x0)
access("/usr/local/etc/cups/ssl/office-support-1.key",R_OK) ERR#2 'No such file or directory'
access("/etc/letsencrypt/live/office-support-1/fullchain.pem",R_OK) ERR#2 'No such file or directory'
access("/etc/letsencrypt/live/office-support-1/fullchain.pem",R_OK) ERR#2 'No such file or directory'
access("/usr/local/etc/cups/ssl/office-support-1.crt",R_OK) = 0 (0x0)
access("/usr/local/etc/cups/ssl/office-support-1.key",R_OK) ERR#2 'No such file or directory'
open("/usr/local/etc/cups/ssl/office-support-1.key",O_RDONLY|O_CLOEXEC,0666) ERR#2 'No such file or directory'
```

**Comment by michaelrsweet** [comment]
@siepkes Note that development of CUPS has moved to [OpenPrinting](https://openprinting.github.io/cups)...

Anyways, libcups does a reverse lookup of the connection address to get the expected hostname for the X.509 certificate. If that fails, it falls back on the hostname value.

What you *can* do is install your own certificate and private key in /etc/cups/ssl, with symlinks for any alternate names listed in the cert, and CUPS will happily use it (just as it does for Let's Encrypt certs).

Also, one of the "features" on the CUPS 2.5 roadmap is to add some better control over this. [PAPPL](https://www.msweet.org/pappl) already does some of this (through its embedded web interface) and I'm hoping to get [a version of ACME](https://datatracker.ietf.org/doc/draft-sweet-iot-acme/) through the IETF to support encrypted local/IoT network services so that it is possible to move away from self-signed certificates in cupsd.
