### ISSUE TITLE
Resource Leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [apple/cups#5786]
Stream is opened
https://github.com/apple/cups/blob/bf265b3aa9e0f1f32c831000a114ecec4bfebc76/monitor/bcp.c#L61

Opened file never closed
https://github.com/apple/cups/blob/bf265b3aa9e0f1f32c831000a114ecec4bfebc76/monitor/bcp.c#L145

**Comment by michaelrsweet** [comment]
Closed on exit, but please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
