### ISSUE TITLE
CUPS filter texttopdf aborts when 'Noto Color Emoji' font is present

### ISSUE THREAD

**Issue by emk2203** [apple/cups#5787]
[Some details taken from here](https://askubuntu.com/questions/1240708/problem-with-cups-texttopdf-and-noto-truetype-fonts), own issues added.

There seems to be a problem with the `texttopdf` CUPS filter.

When printing a plain ASCII file (can be as simple as "Hello world", or a pipe like `inxi -Fxr | lp`), `texttopdf` aborts:

```
D [17/May/2020:11:48:37 -0700] [Job 513] Sending data to printer.
D [17/May/2020:11:48:37 -0700] [Job 513] Set job-printer-state-message to "Sending data to printer.", current level=INFO
D [17/May/2020:11:48:37 -0700] [Job 513] Unsupported OTF font / glyf table 
D [17/May/2020:11:48:37 -0700] [Job 513] Brother-HL-1240-series: fontembed/sfnt.c:651: otf_get_width: Assertion `0\' failed.
D [17/May/2020:11:48:37 -0700] [Job 513] PID 1520973 (/usr/lib/cups/filter/texttopdf) crashed on signal 6.
D [17/May/2020:11:48:37 -0700] [Job 513] Input is empty, outputting empty file.
```
Other system with a pipe to `lp` from the command line:

```
│D [31/May/2020:10:46:46 +0200] [Job 26] Unsupported OTF font / glyf table                                                                                     │
│D [31/May/2020:10:46:46 +0200] [Job 26] cm1415fn: fontembed/sfnt.c:651: otf_get_width: Assertion `0\' failed.                                                 │
│D [31/May/2020:10:46:46 +0200] [Job 26] PID 21089 (/usr/lib/cups/filter/texttopdf) crashed on signal 6.                                                       │
│D [31/May/2020:10:46:46 +0200] [Job 26] Input is empty, outputting empty file.                                                                                │
│D [31/May/2020:10:46:46 +0200] [Job 26] PID 21090 (/usr/lib/cups/filter/pdftopdf) exited with no errors.                                                      │
│D [31/May/2020:10:46:46 +0200] [Job 26] Input is empty, outputting empty file.                                                                                │
│D [31/May/2020:10:46:46 +0200] [Job 26] HP PS filter ENDS                                                                                                     │
│D [31/May/2020:10:46:46 +0200] [Job 26] PID 21091 (/usr/lib/cups/filter/pdftops) exited with no errors.                                                       │
│D [31/May/2020:10:46:46 +0200] [Job 26] PID 21092 (/usr/lib/cups/filter/hpps) exited with no errors.                                                          │
```

After disabling the 'Noto' (No Tofu) truetype fonts, by moving them out of `/usr/share/fonts/truetype`, the problem goes away.

The problem, apparently, is in one of the 'Noto' fonts, **NotoColorEmoji**, and `texttopdf` is choking on it.

As a workaround, this can be fixed by creating the file `/etc/fonts/local.conf` and adding the lines

```
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <selectfont>
    <rejectfont>
      <glob>/usr/share/fonts/truetype/noto/NotoColorEmoji.ttf</glob>
    </rejectfont>
  </selectfont>
</fontconfig>
```
Then running `fc-cache -f -v` to rebuild the font cache.

This disables the offending font, but it is by no means a permanent solution if recreational use of social media on the same computer is desired.

In the source code for **cups-filters**, the abort is an assert in the library **libfontembed** in the function **otf_get_width**, snippeted here:

```c
  // ensure hmtx is there
  if (!otf->hmtx) {
    if (otf_load_more(otf)!=0) {
      assert(0);
      return -1;
    }
  }
```

This is on Ubuntu 20.04.

`apt-show-versions` are:
cups:amd64/focal-security 2.3.1-9ubuntu1.1 uptodate
cups-filters:amd64/focal 1.27.4-1 uptodate

One further bit of information: If `texttopdf` is invoked from the command line, it produces a valid PDF. It appears to be something in the CUPS filter/tool chain that is involved.

**Comment by zdohnal** [comment]
Hi @emk2203 ,

> 
> One further bit of information: If `texttopdf` is invoked from the command line, it produces a valid PDF. It appears to be something in the CUPS filter/tool chain that is involved.

Did you run texttopdf with your PPD file and the options which are used during printing? It can behave quite differently than running texttopdf in the default way.

If you ran texttopdf the same way as cupsd started it and the issue didn't appear, did you report it to Ubuntu? Manjaro (according the link you shared) and Fedora (according my test, but I probably didn't use your PPD file - I used one of foomatic drivers which supports your printer) are not affected.

If you ran texttopdf differently before and now it fails, please report it to Ubuntu cups-filters maintainers or cups-filters project.

Either way, please provide them your PPD file (file from /etc/cups/ppd/<your_print_queue_name>.ppd) and logs for failing print job.

**Comment by michaelrsweet** [comment]
This is part of the [cups-filters](https://github.com/openprinting/cups-filters) project, not CUPS proper...

**Comment by DimanNe** [comment]
I was experiencing the same problem, Ubuntu 21.10 (beta).

@emk2203 
Thank you for the workaround!
