### ISSUE TITLE
double "Allow remote administration"

### ISSUE THREAD

**Issue by thibaultmol** [apple/cups#5788]
It seems like there's something wrong with the configuration file it genereted for me (just used cups as it came installed on my very recent install of Manjaro KDE).
(I haven't modified the configuration manually yet I think)
The configuration has this:
```
# Allow remote access
Port 631
Listen /run/cups/cups.sock
# Allow remote administration...
<Location />
  Order allow,deny
  Allow @LOCAL
</Location>
# Allow remote administration...
<Location /admin>
  Order allow,deny
  Allow @LOCAL
</Location>
```

I think line 4 in that code block should say " # Allow remote printing" or something, right?
Because both shouldn't be saying 'remote administration' as only one has admin access?

EDIT:
CUPS 2.3.3

**Comment by michaelrsweet** [comment]
Maybe contact the Manjaro folks?

**Comment by thibaultmol** [comment]
Doesn't seem like it's a problem anymore. Cups did switch to the openprinting version, so maybe that has something to do with it. But I did reinstall manjaro at the beginning of the year. But it's only in the config once now :+1:
