### ISSUE TITLE
Log flood on insecure permissions paralyzes system

### ISSUE THREAD

**Issue by aldoshkind** [apple/cups#5790]
Hi!
After mistakenly set permissions all over the system (please don't ask :) ) cups flooded root partition with it's logs (pics below) complaining about loose permissions of files under `/usr/lib/cups`.
System: Ubuntu 16.04.6.

Please add timeout maybe between attempts of opening those files or mechanism to avoid multiple messages and notify user in explicit way.

![photo_2020-05-29_15-44-06](https://user-images.githubusercontent.com/16011884/83964963-8e2ef380-a8da-11ea-9b1d-7a687eeae6b3.jpg)
![photo_2020-05-29_16-17-41](https://user-images.githubusercontent.com/16011884/83964964-8f602080-a8da-11ea-82fd-4845248fbefc.jpg)
![photo_2020-05-29_17-25-18](https://user-images.githubusercontent.com/16011884/83964965-8ff8b700-a8da-11ea-9871-d2dd448453b2.jpg)

**Comment by michaelrsweet** [comment]
Ubuntu problem with default log size unlimited...

**Comment by jebbyk** [comment]
I have the same problem. I've set permissions all over the system too by mistake and now I have almost the same error. Please help me to solve this. How to stop cups from writing those messages? Cups service uses 100% of one cpu core just to write a tons of error messages. 
![image](https://user-images.githubusercontent.com/40975486/124546570-a5794100-de4c-11eb-947a-5c02e776c602.png)

**Comment by michaelrsweet** [comment]
@jebbyk Restore the permissions (`chmod 755 /usr/lib/cups/notifier`)

**Comment by jebbyk** [comment]
@michaelrsweet I've tried this but it doesn't helped me. So I've purged cups with manually deleting all the related folders (at least which I found) and installed it again. After this it looks like it works normally again
