### ISSUE TITLE
apt-get install fail

### ISSUE THREAD

**Issue by amcleodUNH** [apple/cups#5791]
have tried install to an RPi4/Ubuntu 18.04 for the last 12 hours. This is what I get:

Do you want to continue? [Y/n] y
Get:1 http://archive.raspberrypi.org/debian buster/main armhf cups-filters-core-drivers armhf 1.21.6-5+rpt1 [211 kB]
Get:3 http://archive.raspberrypi.org/debian buster/main armhf libfontembed1 armhf 1.21.6-5+rpt1 [112 kB]
Get:4 http://archive.raspberrypi.org/debian buster/main armhf cups-filters armhf 1.21.6-5+rpt1 [547 kB]
Get:6 http://archive.raspberrypi.org/debian buster/main armhf cups-browsed armhf 1.21.6-5+rpt1 [167 kB]
Get:2 http://raspbian.mirror.constant.com/raspbian buster/main armhf libsane-common all 1.0.27-3.2 [583 kB]
Get:7 http://raspbian.mirror.constant.com/raspbian buster/main armhf acl armhf 2.2.53-4 [56.0 kB]
Get:8 http://raspbian.mirror.constant.com/raspbian buster/main armhf libgusb2 armhf 0.3.0-1 [21.0 kB]
Get:9 http://raspbian.mirror.constant.com/raspbian buster/main armhf libcolorhug2 armhf 1.4.3-4 [41.7 kB]
Get:11 http://raspbian.mirror.constant.com/raspbian buster/main armhf mysql-common all 5.8+1.0.5 [7,324 B]
Get:12 http://raspbian.mirror.constant.com/raspbian buster/main armhf mariadb-common all 1:10.3.22-0+deb10u1 [31.9 kB]
Get:13 http://raspbian.mirror.constant.com/raspbian buster/main armhf libmariadb3 armhf 1:10.3.22-0+deb10u1 [158 kB]
Get:14 http://raspbian.mirror.constant.com/raspbian buster/main armhf libsnmp-base all 5.7.3+dfsg-5 [1,595 kB]
Get:15 http://raspbian.mirror.constant.com/raspbian buster/main armhf libsnmp30 armhf 5.7.3+dfsg-5+b1 [2,204 kB]
Get:16 http://raspbian.mirror.constant.com/raspbian buster/main armhf libsane armhf 1.0.27-3.2 [1,906 kB]
Get:17 http://raspbian.mirror.constant.com/raspbian buster/main armhf colord-data all 1.4.3-4 [263 kB]
Get:18 http://raspbian.mirror.constant.com/raspbian buster/main armhf colord armhf 1.4.3-4 [178 kB]
Get:20 http://raspbian.mirror.constant.com/raspbian buster/main armhf cups-daemon armhf 2.2.10-6+deb10u3 [399 kB]
Get:21 http://raspbian.mirror.constant.com/raspbian buster/main armhf libqpdf21 armhf 8.4.0-2 [367 kB]
Get:22 http://raspbian.mirror.constant.com/raspbian buster/main armhf poppler-utils armhf 0.71.0-5 [158 kB]
Get:23 http://raspbian.mirror.constant.com/raspbian buster/main armhf cups-ipp-utils armhf 2.2.10-6+deb10u3 [299 kB]
Get:24 http://raspbian.mirror.constant.com/raspbian buster/main armhf cups-core-drivers armhf 2.2.10-6+deb10u3 [139 kB]
Get:5 http://raspbian-us.ngc292.space/raspbian buster/main armhf bc armhf 1.07.1-2 [101 kB]
Get:10 http://raspbian-us.ngc292.space/raspbian buster/main armhf libieee1284-3 armhf 0.2.11-13 [25.8 kB]
Get:19 http://raspbian-us.ngc292.space/raspbian buster/main armhf ssl-cert all 1.0.39 [20.8 kB]
Get:31 http://raspbian-us.ngc292.space/raspbian buster/main armhf gsfonts all 1:8.11+urwcyr1.0.7~pre44-4.4 [3,125 kB]
Get:25 http://raspbian.mirror.constant.com/raspbian buster/main armhf ghostscript armhf 9.27~dfsg-2+deb10u3 [94.5 kB]
Get:26 http://raspbian.mirror.constant.com/raspbian buster/main armhf cups-common all 2.2.10-6+deb10u3 [318 kB]
Err:5 http://raspbian-us.ngc292.space/raspbian buster/main armhf bc armhf 1.07.1-2
  File has unexpected size (114688 != 101072). Mirror sync in progress? [IP: 198.211.116.210 443]
Err:10 http://raspbian-us.ngc292.space/raspbian buster/main armhf libieee1284-3 armhf 0.2.11-13
  File has unexpected size (114688 != 101072). Mirror sync in progress? [IP: 198.211.116.210 443]
Err:19 http://raspbian-us.ngc292.space/raspbian buster/main armhf ssl-cert all 1.0.39
  File has unexpected size (114688 != 101072). Mirror sync in progress? [IP: 198.211.116.210 443]
Err:31 http://raspbian-us.ngc292.space/raspbian buster/main armhf gsfonts all 1:8.11+urwcyr1.0.7~pre44-4.4
  File has unexpected size (114688 != 101072). Mirror sync in progress? [IP: 198.211.116.210 443]
Get:27 http://raspbian.mirror.constant.com/raspbian buster/main armhf cups-server-common all 2.2.10-6+deb10u3 [582 kB]
Get:28 http://raspbian.mirror.constant.com/raspbian buster/main armhf cups-client armhf 2.2.10-6+deb10u3 [246 kB]
Get:29 http://raspbian.mirror.constant.com/raspbian buster/main armhf cups-ppdc armhf 2.2.10-6+deb10u3 [189 kB]
Get:30 http://raspbian.mirror.constant.com/raspbian buster/main armhf cups armhf 2.2.10-6+deb10u3 [348 kB]
Get:32 http://raspbian.mirror.constant.com/raspbian buster/main armhf libgutenprint-common all 5.3.1-7 [608 kB]
Get:33 http://raspbian.mirror.constant.com/raspbian buster/main armhf libgutenprint9 armhf 5.3.1-7 [383 kB]
Get:34 http://raspbian.mirror.constant.com/raspbian buster/main armhf liblouis-data all 3.8.0-2 [1,660 kB]
Get:35 http://raspbian.mirror.constant.com/raspbian buster/main armhf liblouis17 armhf 3.8.0-2 [81.9 kB]
Get:36 http://raspbian.mirror.constant.com/raspbian buster/main armhf liblouisutdml-data all 2.7.0-5 [38.5 kB]
Get:37 http://raspbian.mirror.constant.com/raspbian buster/main armhf liblouisutdml8 armhf 2.7.0-5+b1 [75.1 kB]
Get:38 http://raspbian.mirror.constant.com/raspbian buster/main armhf liblouisutdml-bin armhf 2.7.0-5+b1 [14.1 kB]
Get:39 http://raspbian.mirror.constant.com/raspbian buster/main armhf printer-driver-gutenprint armhf 5.3.1-7 [438 kB]
Get:40 http://raspbian.mirror.constant.com/raspbian buster/main armhf update-inetd all 4.49 [27.8 kB]
Get:41 http://raspbian.mirror.constant.com/raspbian buster/main armhf sane-utils armhf 1.0.27-3.2 [245 kB]
Fetched 14.8 MB in 16s (908 kB/s)                                              
E: Failed to fetch https://113store.cr/es/  File has unexpected size (114688 != 101072). Mirror sync in progress? [IP: 198.211.116.210 443]
E: Failed to fetch https://113store.cr/es/  File has unexpected size (114688 != 101072). Mirror sync in progress? [IP: 198.211.116.210 443]
E: Failed to fetch https://113store.cr/es/  File has unexpected size (114688 != 101072). Mirror sync in progress? [IP: 198.211.116.210 443]
E: Failed to fetch https://113store.cr/es/  File has unexpected size (114688 != 101072). Mirror sync in progress? [IP: 198.211.116.210 443]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

**Comment by zdohnal** [comment]
Hi,

IMO it is an Ubuntu issue, please close this ticket and report it to Ubuntu.

Thank you in advance!

**Comment by amcleodUNH** [comment]
Will work with Ubuntu
