### ISSUE TITLE
Printing from windows Client with content application/vnd.cups-raw can not be filtered

### ISSUE THREAD

**Issue by lsochanowski** [apple/cups#5794]
Hello , 
like in topic when i've set custom filter in many places ( in all *.convs files) and in ppd file . filter work fine when i've try to print over ,,test page" from cups web interface but when i've try printing from windows client over ipp filter does not apply how can i overcome that?

**Comment by michaelrsweet** [comment]
Printing via SMB *should* work. Printing via LPD will always use raw mode and bypass filtering.

Windows 10 clients with the forthcoming OpenPrinting CUPS 2.4.0 will work via IPP.
