### ISSUE TITLE
PDF/A-1b fails to validate

### ISSUE THREAD

**Issue by medmedin2014** [apple/cups#5798]
I use CUPS to print to pdf on my Manjaro KDE inside LibreOffice, the output PDF according to JHOVE is ISO PDF/A-1b, but when I use veraPDF to validate against PDF/A-1b profile it fails to pass the validation.

**NB**: Aside from the report above, is there any way to generate PDF/A-2a using CUPS ? or any known tool to do the job ?

```
cups: 2.3.3-1
cups-pdf: 3.0.1-5
Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.70.0
Qt Version: 5.15.0
Kernel Version: 5.7.0-3-MANJARO
OS Type: 64-bit
```

**Comment by jschwender** [comment]
In my opinion, it does not make any sense for a printing system to create file formats with conformity level a, as a printing system outputs to paper. For archiving print jobs visual reproducibility (level b) is enough. You probably need a tool like pdflib. In any case your application needs to create it in PDF/A-2a in a generic way. It is not possible to convert a PDF level b to level a after output. Please note that pdf-cups is a separate backend for CUPS, not a part of cups.

**Comment by medmedin2014** [comment]
@jschwender Thanks for your reply; for now every university or government branch insists on having some kind of PDF/A file to archive it and for future print if necessary. So the printing is done primary to PDFs files and paper are rarely used. And some of those organization impose that all produced/sent files are conform to PDF/A standard and passed validation with success, if not it will never be accepted as digital document.
And on Linux we have only one free virtual printer that help us to create PDF files which is CUPS.

**Comment by jschwender** [comment]
Do you use LO export to pdf function or do you print to cups-pdf virtual printer? If i use the export function validation to PDF/A-1b passed.

**Comment by debiantriage** [comment]
On Thu 02 Jul 2020 at 05:05:07 -0700, jschwender wrote:

> Do you use LO export to pdf function or do you print to cups-pdf
> virtual printer? If i use the export function validation to PDF/A-1b
> passed.

This really isn't a CUPS issue. Perhaps there is help at

  https://wiki.debian.org/CUPSTea4CUPS

Cheers,

Brian.

**Comment by jsmeix** [comment]
Only as a side note FYI you may have a look at the section
`Background Information regarding Print as PDF versus Save as PDF` in
https://en.opensuse.org/SDB:Printing_to_PDF

**Comment by medmedin2014** [comment]
> Do you use LO export to pdf function or do you print to cups-pdf virtual printer? If i use the export function validation to PDF/A-1b passed.

I used them both, LO output to PDF/A-1b always fails to pass validation test because of some annoying [rule](https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Part-1-rules#rule-635-2), but PDF/A-2b outputs pass the test without errors.

That's why I tried CUPS to produce PDFs conform to PDF/A-1b (because I inspected cups-pdf output and found them tagged "ISO PDF/A-1, Level B") but at validation they give more errors than the ones produced by LO.

**Comment by debiantriage** [comment]
On Thu 02 Jul 2020 at 07:15:19 -0700, Medin wrote:

> > Do you use LO export to pdf function or do you print to cups-pdf virtual printer? If i use the export function validation to PDF/A-1b passed.
> 
> I used them both, LO output to PDF/A-1b always fails to pass
> validation test because of some annoying
> [rule](https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Part-1-rules#rule-635-2),
> but PDF/A-2b outputs pass the test without errors.
> 
> That's why I tried CUPS to produce PDFs conform to PDF/A-1b (because I
> inspected cups-pdf output and found them tagged "ISO PDF/A-1, Level
> B") but at validation they give more errors than the ones produced by
> LO.

The PDFs produced by the cups-pdf backend are the product of Ghostscrpt,
not CUPS. All that CUPS does is run the backend.

From just recently:

  https://stackoverflow.com/questions/58813905/convert-pdf-to-pdf-a-to-use-ghostscript

The Ghostscript maintainer (KenS) appears very sure of his ground.

Cheers,

Brian.

**Comment by jschwender** [comment]
I just made a test with LO (v6.4.4.3): exporting a document to PDF/A-2b and ran the verapdf validator against it: passed. So your problem may be related to settings for the export. Made the same with PDF/A-1b and the validation failed because of the font embedding issue. So it is clear that validation depends on the document content too.
hope that helps, greetings

**Comment by medmedin2014** [comment]
> Only as a side note FYI you may have a look at the section
> `Background Information regarding Print as PDF versus Save as PDF` in
> https://en.opensuse.org/SDB:Printing_to_PDF

Thanks, I have already CUPS installed correctly and the print to file happens on the same machine, I think gs is the culprit. I will try investigate how CUPS issues print command to gs to produce the PDF.

**Comment by medmedin2014** [comment]
> I just made a test with LO (v6.4.4.3): exporting a document to PDF/A-2b and ran the verapdf validator against it: passed. So your problem may be related to settings for the export. Made the same with PDF/A-1b and the validation failed because of the font embedding issue. So it is clear that validation depends on the document content too.
> hope that helps, greetings

Thanks for your reply, and sorry for my boring questions ;) I have quite big documents with a lot of drawings and different fonts, so I will try to go with PDF/A-2b and convince them to accept it.

**Comment by medmedin2014** [comment]
> On Thu 02 Jul 2020 at 07:15:19 -0700, Medin wrote: > Do you use LO export to pdf function or do you print to cups-pdf virtual printer? If i use the export function validation to PDF/A-1b passed. I used them both, LO output to PDF/A-1b always fails to pass validation test because of some annoying [rule](https://github.com/veraPDF/veraPDF-validation-profiles/wiki/PDFA-Part-1-rules#rule-635-2), but PDF/A-2b outputs pass the test without errors. That's why I tried CUPS to produce PDFs conform to PDF/A-1b (because I inspected cups-pdf output and found them tagged "ISO PDF/A-1, Level B") but at validation they give more errors than the ones produced by LO.
> The PDFs produced by the cups-pdf backend are the product of Ghostscrpt, not CUPS. All that CUPS does is run the backend. From just recently: https://stackoverflow.com/questions/58813905/convert-pdf-to-pdf-a-to-use-ghostscript The Ghostscript maintainer (KenS) appears very sure of his ground. Cheers, Brian.

Thanks bro ;)

**Comment by jsmeix** [comment]
To investigate how CUPS issues print command to gs to produce the PDF
you need to inspect /var/log/cups/error_log (or where your cupsd logs to),
cf. the section
"Usually provide CUPS debug messages" in
https://en.opensuse.org/SDB:How_to_Report_a_Printing_Issue

E.g. on my system I get (excerpts for an overview what filters are run)
```
# grep PID /var/log/cups/error_log

I ... Started filter /usr/lib/cups/filter/texttopdf (PID 7779)
I ... Started filter /usr/lib/cups/filter/pdftopdf (PID 7780)
I ... Started filter /usr/lib/cups/filter/pdftops (PID 7781)
D ... PID 7779 (/usr/lib/cups/filter/texttopdf) exited with no errors.
D ... PID 7780 (/usr/lib/cups/filter/pdftopdf) exited with no errors.
D ... Started filter pdftops (PID 7785)
D ... Started filter pstops (PID 7786)
D ... PID 7785 (pdftops) exited with no errors.
D ... PID 7786 (pstops) exited with no errors.
D ... PID 7781 (/usr/lib/cups/filter/pdftops) exited with no errors.
```
For more details you need to inspect all the cupsd debug messages.

For further (often rather complicated) debugging actions
you may have a look at the sections
"A filter that sends its input into a file for debugging" in
https://en.opensuse.org/SDB:Using_Your_Own_Filters_to_Print_with_CUPS
and
"A backend that sends its input into a file for debugging" in
https://en.opensuse.org/SDB:Using_Your_Own_Backends_to_Print_with_CUPS

What you need to do in your particular case
depends on your particular case (what a final wisom ;-)

**Comment by michaelrsweet** [comment]
You are using non-CUPS software to create this PDF, so this isn't something we can help you with here, sorry...
