### ISSUE TITLE
A bug with encoding conversion

### ISSUE THREAD

**Issue by Igorgro** [apple/cups#5799]
I don't know is it a bag, but i've found an undocumented feature related to encoding conversion. I have the Zjiang ZJ-5890k ES/POS printer which is set up as "Generic Text-Only Printer". I need to print text with cyrillc characters so i've set both internal and CUPS driver encoding to Windows-1251(CP-1251). I use `lp` utility to perform printing. If I don't misunderstand, CUPS requires that input text is being encoded as UTF-8. Then it converts it to the specified encoding (`cp1251` in my case) and then sends converted text to the printer. Everything works well, but then i've found the following bug (or may be a feature?). When I regular text which contains only letters(both cyrillic and latin), numbers and other printable characters everything works as described above. But when I'm trying to print text which contains ESC/POS commands or unprintable characters (like `\x00`), CUPS doesn't convert it from input encoding to printer's one. Instead, it send the raw input string directly to the printer. There is an example how it works (i use cyrillc letters, because they have different codes depending on encoding):

* If input string encoded in `utf8`:
  * `Привет` prints well, because CUPS converts it to `cp1251` and send the converted string to the printer;
  * `Привет\x00` prints rubbish like `РџСЂРёРІРµС‚` because CUPS doesn't convert it to `cp1251` and sends it directly to printer (which is set up to use `cp1251`).
* If input string encoded in `cp1251`:
  * `Привет` gives the following error: `Illegal UTF-8 sequence found. Input file perhaps not UTF-8-encoded` because cups expects the `utf8` encoded string;
  * `Привет\x00` prints well, because CUPS doesn't convert it and sends it directly to the printer.

Character `\x00` is given only for example an everything will be the same if it is replaced by any ESC/POS commands. So the question is "is it a bug, or feature?"

**Comment by jschwender** [comment]
It is not clear which OS/cups version you use. That can make a difference. Please note that this printer requires a specific filter and specific PPD file, which is not part of CUPS. Please check https://github.com/klirichek/zj-58, or alternatively utilize manufacturer's driver package. They both install an additional filter, which CUPS itself can only use according to the settings in the PPD file. It is also not clear what you mean by input string. Cups requires command line strings to be UTF-8, but it generally should be able to handle other file encodings. You may utilize `lpr -o document-format='text/plain;charset=iso-8859-2'`. If your print a file has already included all control commands, then you should use a raw printer queue. This works in current version of cups, but it is marked obsolete.

**Comment by jsmeix** [comment]
@Igorgro 
in genreral CUPS itself (i.e. primarily the cupsd) does not convert any print data.
That is done by various different kind of so called "filtering programs" short "filters".
Which filters are used depends on the data format of the original print data.
E.g. when the original print data is recognized to be "text" some "text filters" are used
and when the original print data is no known data format no filter is used so the
original print data is sent unchanged (i.e. "raw") to the printer.

For more information see e.g.
"What does the filter system do and how does it work?" in
https://en.opensuse.org/SDB:CUPS_in_a_Nutshell
and follow the links therein that lead to e.g.
https://en.opensuse.org/SDB:Using_Your_Own_Filters_to_Print_with_CUPS
that contains in particular the sections
"CUPS Filter System Background Information" and
"A filter that sends its input into a file for debugging"

**Comment by Igorgro** [comment]
@jschwender, as I've already mentioned, I don't use any filters, because I've set it up as "Generic Text-Only Printer". This is how ESC/POS printer works. "Input string" means the text (the sequence of bytes) written into `lp` stdin. My OS is Debian testing and the  CUPS is latest available version in that distro (2.2.10).

**Comment by jsmeix** [comment]
@Igorgro 
when you don't use any filters your original print data is sent as is (i.e. "raw")
to your printer so there is nothing on your computer what could do anything
with your original print data - in particular there is nothing which does anything
that is related to whatever kind of "encoding" of your original print data - so
all what is done happens inside the printer. In this case you may better contact
your printer vendor/manufacturer about things that happen within their printer.

**Comment by Igorgro** [comment]
@jsmeix thank you for your advice. I've just changed **Text/Generic** filter to **Raw queue** and everything works well!

**Comment by jsmeix** [comment]
Ha!
So actually you had a filter, some "Text/Generic" thingy
(I am not a Debian user so I don't know what exactly it is).

FYI:
You could set up several different print queues for one same printer
e.g. one with the "Text/Generic" filter and another one as "raw" queue
so that you could let printing happen as you need it case by case
but see the initial part about
"Optional PCL Printing on PostScript+PCL Printers" in
https://en.opensuse.org/SDB:Using_Your_Own_Filters_to_Print_with_CUPS
that reads (excerpt):
```
The main disadvantage of using several queues for the same printer
is that it is necessary to query all queues to display all waiting or
active print jobs for that printer. Although not a problem for single
printers or stand-alone systems, the use of several queues per printer
might prove too complicated in the case of several network printers
used by many users. 
```

**Comment by michaelrsweet** [comment]
This isn't something CUPS supports or will ever support. You need a real driver that can convert Unicode to the printer's charset.
