### ISSUE TITLE
setting printer options can have some CSS scrollability issues

### ISSUE THREAD

**Issue by kristopolous** [apple/cups#5802]
So this comes from https://github.com/apple/cups/blob/master/doc/cups.css#L519 this line. So just by default the button is hidden for my Samsung C410

![button-hidden](https://user-images.githubusercontent.com/231761/86707595-f998dd80-bfcc-11ea-8349-07985b2d9d71.jpg)

But If I do an error it's even worse:
![button-hidden-onerror](https://user-images.githubusercontent.com/231761/86707815-2f3dc680-bfcd-11ea-9bb1-34426a53eebd.jpg)

Even at the full scroll I can't see the button
![button-hidden-onerror-scroll](https://user-images.githubusercontent.com/231761/86707902-42509680-bfcd-11ea-9a08-374104e42df9.jpg)

As a very simple fix, I can remove the aforementioned CSS entry and I get the following, which now is usable:
![button-hidden-onerror-simple-fix](https://user-images.githubusercontent.com/231761/86708033-644a1900-bfcd-11ea-91c1-6cf9bc3ca616.jpg)

I'm sorry if this has been brought up before, I couldn't find any prior mention.

**Comment by michaelrsweet** [comment]
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
