### ISSUE TITLE
Unsharing printers every day

### ISSUE THREAD

**Issue by K12martin** [apple/cups#5803]
Hi,

We encountered issue with MacOS that since we are using it as print server (MacPro Late 2013) it's unsharing printers every day.

In web interface every day we need to check in **Share printers connected to this system** and **Allow printing from the Internet** which is bit tedious job. Is this known issue or anyone has idea why it's doing that ? 

Printers are Ricoh IM C6000 and Ricoh MP C3004 connected to MacPro using IPP. As print server app we are using PaperCut but after tests done without papercut it still does the same thing and unshare printer (in Mac system preferences it still show that printer is shared)

Thanks a lot

**Comment by michaelrsweet** [comment]
PaperCut must be making changes to the cupsd configuration file. You need to contact them.
