### ISSUE TITLE
libcups: "True" is case-sensitive in PPDs 

### ISSUE THREAD

**Issue by nidhijainpnp** [apple/cups#5805]
cupsManualCopies: Incorrect capitalization in PPD prevents mutliple copies from being printed .It is the same issue as referenced in [#242](https://github.com/OpenPrinting/cups-filters/issues/242)
 It is fixed in the commit  [42868e7](https://github.com/OpenPrinting/cups-filters/commit/42868e742bf8db35ed95cdab48fc4c7d6b277c4e) in libppd and needs to be fixed in libcups(cups/ppd-cache.c file) also.

**Comment by michaelrsweet** [comment]
Fixed in OpenPrinting CUPS.
