### ISSUE TITLE
Peripage A6

### ISSUE THREAD

**Issue by KataPi** [apple/cups#5806]
How to use this thermal printer?
Peripage A6 on ubuntu or raspberry
Thanks

**Comment by jschwender** [comment]
It looks like it can currently be used with Linux:
https://www.openprinting.org/printer/SiPix/SiPix-Pocket_Printer_A6

**Comment by KataPi** [comment]
Hi, thanks for the reply
SiPix Pocket Printer: 10.5 mm paper and 360 dpi
My Peripage A6 accepts 58mm paper roll with 206dpi resolution
Unfortunately it doesn't work
Ubuntu with CUPS recognizes it with name A6 and generic driver but it does not work.
How can I make a PPD file?
Thank you

**Comment by KataPi** [comment]
@jschwender 

Windows has the manufacturer's driver:
http://m.ileadtek.com/appdownload
Raspberry via bluetooth does not find properties ...
on raspberry I installed CUPS but it doesn't work.
on Android (on the phone) it works great.
Manufacturer's app (http://m.ileadtek.com/appdownload) and not:
https://play.google.com/store/apps/details?id=ru.a402d.peripage.free&hl=it
https://play.google.com/store/apps/details?id=com.noble.activity.printerperipage&hl=it

does not work with ESC driver ....
If sameone explains to me how PPD files are made, I would like to try it.
Thank you

**Comment by KataPi** [comment]
I emulated Android on Ubuntu (Anbox) but no bluetooth support and I couldn't find the printer

**Comment by jsmeix** [comment]
@KataPi 
PPD files are no printer drivers, PPDs are only printer descriptions,
so making a PPD won't help - except for real PostScript printers,
cf. "PPD files: Printer-specific options"
versus "Printer drivers: Make the printer print"
in https://en.opensuse.org/Concepts_printing

**Comment by jschwender** [comment]
under linux a filter (=driver) for this printer is provided by GhostScript, which must be installed. follow the hints on openprinting,org to install and set up the driver. I don't think there is an ubuntu package available. with openprinting.org you also get a proper PPD file, which contains the control sequence to run the filter.

**Comment by KataPi** [comment]
Thanks for your help.
I'm not an expert and I started to study the information you gave me.

I have installed cups-filters and foomatic (engine, db, etc ..) but I can't find a filter that works with my printer.

((To compile cups-filters on Raspberry you have to edit the configure file (https://bugs.archlinux.org/task/47018). It points to /usr/share/fonts/dejavu/DejaVuSans.ttf but in my case the file is located in /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
I spent a lot of time making MAKE))

I will try to open an issue on openprinting to ask to add a new printer to the database

**Comment by eliasweingaertner** [comment]
I made the Peripage A6 work on Linux, see here:

https://github.com/eliasweingaertner/peripage-A6-bluetooth

**Comment by brasofilo** [comment]
> I made the Peripage A6 work on Linux (without CUPS):
> 
> https://github.com/eliasweingaertner/peripage-A6-bluetooth

This one was beautiful, Elias, thanks so much!
I ended up using a fork of your work: https://github.com/bitrate16/ppa6-python
