### ISSUE TITLE
Incorrect error message for non-existing printer when used in lp/lpr command

### ISSUE THREAD

**Issue by zdohnal** [apple/cups#5808]
Hi,

we have a report in [Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1811735) about incorrect message when you use a non-existing print queue for lp/lpr command - it is because ```cupsGetNamedDest()``` just returns NULL for a non-existing queue, it doesn't set any error and ```lpr``` nor ```lp``` check for ```IPP_STATUS_NOT_FOUND``` (looks to me as the most logical error).

I'll create a pull request with proposed fix.

**Comment by michaelrsweet** [comment]
Fixed in OpenPrinting CUPS.
