### ISSUE TITLE
IPv6 considered harmful

### ISSUE THREAD

**Issue by patch-work** [apple/cups#5814]
Please add --disable-ipv6 option to configure.

**Comment by jschwender** [comment]
Please explain why you think ipv6 is harmful? You could disable it by configuration at any time, if you don't need it.

**Comment by patch-work** [comment]
You are referring to runtime configuration. The OP refers to compile time configuration. Very different things. I read your answer as a denial of request. On explaining why IPv6 is harmful in certain contexts, this is very well known and there is no need for repetition.
