### ISSUE TITLE
Default Options delay with Airprint 

### ISSUE THREAD

**Issue by vasilijpfc88** [apple/cups#5816]
Hi,

So I have added one citizen cl-e720 printer. 
And it's working pretty well it's only the thing when I want to print something from my iPad 
I need to wait to accept default options that I have already configured on 
https://ip:631/  approx 10 sec in print preview window. You can actually see in print preview how paper will be resized after 10 sec.
If I print it immediately without waiting it will print paper with wrong measures. 
Someone knows what can be a problem?

Thanks in Advance

**Comment by michaelrsweet** [comment]
Apple does not support AirPrint sharing from CUPS.
