### ISSUE TITLE
infinite loop waiting for USB printer to be available

### ISSUE THREAD

**Issue by alejandroclaro** [apple/cups#5817]
USB backend never ends if the printer is not connected. We have been able to identify a infinity loop in print_device function in usb-libusb.c file:

``` C
  fprintf(stderr, "DEBUG: Printing on printer with URI: %s\n", uri);
  while ((g.printer = find_device(print_cb, uri)) == NULL)
  {
    _cupsLangPrintFilter(stderr, "INFO",
    _("Waiting for printer to become available."));
    sleep(5);
  }
```

It's also easy to test by invoking the backend by hand:

``` text
# export DEVICE_URI='usb://Printer/Model?serial=?'
# /usr/lib/cups/backend/usb 0 root title 1 '' data.file

DEBUG: Loading USB quirks from "/usr/share/cups/usb".
DEBUG: Loaded 159 quirks.
DEBUG: Printing on printer with URI: usb://Printer/Model?serial=?
DEBUG: libusb_get_device_list=6
INFO: Waiting for printer to become available.
DEBUG: libusb_get_device_list=6
INFO: Waiting for printer to become available.
DEBUG: libusb_get_device_list=6
INFO: Waiting for printer to become available.
DEBUG: libusb_get_device_list=6
INFO: Waiting for printer to become available.
DEBUG: libusb_get_device_list=6
INFO: Waiting for printer to become available.
...
```

Setting a job timeout policy or manually stopping work are not options for us. We may have jobs that take hours to complete.

**Comment by jsmeix** [comment]
Offhandedly I don't know if it is officially documented somewhere
but I think I remember from the past that a CUPS backend
should retry endlessly (with some reasonable delay between retries)
to establish the communication with its recipient (usually a printer device).

I think in particular for USB printers unlimited retries until the printer becomes accessible
is what users normally expect and what is "proven to work in practice behaviour" since years.
This way USB printer users can "just submit" a print job and then they have all the time they
need to connect or switch on their USB printer - or if the job was falsely submitted they can
just cancel their unwanted job.

**Comment by alejandroclaro** [comment]
Hi, @jsmeix I disagree that it should be the correct behavior. 

If you see n the pull request, by returning CUPS_BACKEND_FAILED after some tries, it is possible to adjust the behavior using the job policies (error-policy). It's possible to automatically retry after some time, cancel the jobs, suspend the queue, etc.

Just hanging the backend process looks like a terrible option to me. It will require superuser intervention to fix the problem. we tried to deal with it by configuring a timeout for the jobs, but again this is a workaround and proof to work terribly. We can no predict how long a job is to establish a good timeout. Also, we need to monitor the jobs and inform the user as soon as possible that the printer is presenting an issue, however with a long timeout the experience is terrible and frustrating.

I don't see any argument to wait forever that a device is reconnected. It's no different to any other issue that the printer may present. Why no wait infinity until the printer has paper?

**Comment by alejandroclaro** [comment]
The pull request is just an idea we have to fix the problem.

We are completely open to options to solve the problem, but we need a solution to the case the printer is off, disconnected, or damage. Due to restriction, the user does not have access to the printing queue, and it's not able to perform any action outside a simple user application that is trying to print. We need to inform the application that the printer is presenting an issue, cancel the job, and request for further action to the user (retry, or cancel the process he/she is performing).

**Comment by michaelrsweet** [comment]
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.

Retrying indefinitely is the recommended behavior unless the job is targeted at a class. It is possible we could add a general timeout value (that can be configured) for your specific situation.
