### ISSUE TITLE
Can't compile on artix linux. 

### ISSUE THREAD

**Issue by Leon-Heat** [apple/cups#5820]
Using ARCHFLAGS=
Using ALL_CFLAGS=-I.. -D_CUPS_SOURCE -I/usr/include/libusb-1.0  -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include  -DDBUS_API_SUBJECT_TO_CHANGE -D_FORTIFY_SOURCE=2 -D_REENTRANT  -I/usr/include/p11-kit-1  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT -I/usr/include/elogind  -Werror -Wno-error=deprecated-declarations -Wall -Wno-format-y2k -Wunused -Wno-unused-result -Wsign-conversion
Using ALL_CXXFLAGS=-I.. -D_CUPS_SOURCE -D_FORTIFY_SOURCE=2 -I/usr/include/p11-kit-1  -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT -I/usr/include/elogind
 -Werror -Wno-error=deprecated-declarations -Wall -Wno-format-y2k -Wunused -Wno-unused-re                 from string-private.h:19,
                 from cups-private.h:18,
                 from dest.c:15:
/usr/include/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output between 4 and 1
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dest.c:1275:42: error: ‘%s’ directive output may be truncated writing up to 255 bytes int
 1275 |       snprintf(temp, sizeof(temp), "%s @ %s", resource + 9, hostname);
      |                                          ^~                 ~~~~~~~~
In file included from /usr/include/stdio.h:867,
                 from string-private.h:19,
                 from cups-private.h:18,
                 from dest.c:15:
/usr/include/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output between 4 and 1
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[1]: *** [../Makedefs:271: dest.o] Error 1
make[1]: Leaving directory '/home/sakura/programs/cups/cups'
make: *** [Makefile:42: all] Error 1

**Comment by michaelrsweet** [comment]
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
