### ISSUE TITLE
Multiple printers with same serialnumber?

### ISSUE THREAD

**Issue by miahn** [apple/cups#5821]
I have multiple printers of same brand and model connected to same computer. However they show up with the same serialnumber. 

/usr/lib/cups/backend$ sudo ./usb
DEBUG: Loading USB quirks from "/usr/share/cups/usb".
DEBUG: Loaded 95 quirks.
DEBUG: list_devices
DEBUG: libusb_get_device_list=7
DEBUG2: Printer found with device ID: MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600; Device URI: usb://DYMO/LabelWriter%20450?serial=01010112345600
direct usb://DYMO/LabelWriter%20450?serial=01010112345600 "DYMO LabelWriter 450" "DYMO LabelWriter 450" "MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600;" ""
DEBUG2: Printer found with device ID: MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600; Device URI: usb://DYMO/LabelWriter%20450?serial=01010112345600
direct usb://DYMO/LabelWriter%20450?serial=01010112345600 "DYMO LabelWriter 450" "DYMO LabelWriter 450" "MFG:DYMO;CMD: ;MDL:LabelWriter 450;CLASS:PRINTER;DESCRIPTION:DYMO LabelWriter 450;SERN:01010112345600;" ""

but when running lsusb they show up with different serialnumber?

sudo lsusb -d 0922:0020 -v | grep iSerial
  iSerial                 3 13050802211731
  iSerial                 3 12122313335865

**Comment by michaelrsweet** [comment]
This is a well-known Dymo bug. Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
