### ISSUE TITLE
Old Version On  Raspberry Pi 4B

### ISSUE THREAD

**Issue by 123ABCDF11345** [apple/cups#5825]
On my Raspberry Pi 4B (Linux raspberrypi 5.4.51-v7l+ #1327 SMP Thu Jul 23 11:04:39 BST 2020 armv7l) install cups using'sudo apt-get install cups', but it seems that it does not have 2.3.x Version, in fact, I am using version 2.2.10 (I installed hplib (for my printer) first, is it related to their dependencies?)

In addition, I want to translate the index.html and other pages of CUPS by changing the source code. I am happy to open the source code, but does this violate the license? (I am referring to the 2.2.x license) (maybe to change the files in the index.html and templates directory)

**Comment by jschwender** [comment]
The version of software that is used in a specific distribution is a decision of the package maintainer of the distribution. 
You may connsider adding a translation that is not in the current code tree here on github, then your translation is available to everyone. If you want to do that just for yourself in an older version you can do that of course, you need to pick the source code of your distribution to get that running.

**Comment by 123ABCDF11345** [comment]
> 特定发行版中使用的软件版本是发行版程序包维护者的决定。
> 您可能会考虑在github上的当前代码树中添加不在当前代码树中的翻译，然后您的翻译对所有人都可用。如果您想只在较旧的版本中自己完成此操作，则当然可以这样做，您需要选择发行版的源代码才能使其运行。

Ok,Thanks a lot
