### ISSUE TITLE
This software is not licensed

### ISSUE THREAD

**Issue by aessig** [apple/cups#5828]
Hello, 

While trying to print on a Zebra printer I receive the following error: 'This software is not licensed'

The printer is forced in "paused" and nothing get prints. I cannot find anything on the web or in the documentation about this issue. 

The system is CUPS 2.3.1 installed on macOS 10.15.6 

The workflow works perfectly on Linux.

**Comment by eero-t** [comment]
Maybe you could add "[macOS]" to the front of bug title to indicate that it's Apple specific issue?

(CUPS is nowadays owned by Apple, so that might give it more priority.  This year CUPS has had so far only one commit, one that fixed few CVE security issues and bumped version number to v2.3.3.)

**Comment by michaelrsweet** [comment]
@aessig Which driver are you using on macOS? CUPS includes ZPL and EPL printer drivers for most of the common Zebra models, and they won't display a message like that.

**Comment by michaelrsweet** [comment]
Closing, will reopen if we get more info...

**Comment by byrneciaran** [comment]
I'm encountering this same issue. 

- macOS Monterey 12.0.1
- Zebra GK420d Printer
- Cups 2.3.4

Steps:
- I add a printer through the Printers & Scanners dialog (pusb)
- Go to the Cups Web Admin and Print Test Page
- Print fails, with the message "This software is not licensed"

https://user-images.githubusercontent.com/9086788/146384980-287ab544-df4e-4778-9b2f-dbc48da0d682.mp4

**Comment by michaelrsweet** [comment]
I have no idea what the pusb backend is, but that isn't the device you should be picking, just pick the original USB printer that shows up in the device list.
