### ISSUE TITLE
What choices do you make to add a 3D Printer to CUPS ?

### ISSUE THREAD

**Issue by nodecentral** [apple/cups#5829]
Hi,

I'm trying to work out how to share a USB - 3D Printer (ST3DI ModelSmart) via CUPS, but I'm unsure of the exact options to choose ? (Support looks like it was added back in 2015 for 3D Printers  - https://www.cups.org/blog/2015-07-31-cups-2.1rc1.html) 

Going in (under Administrator) via the UI and choosing 'Add Printer' , under local , other than the braille one, I have a USB Serial Port #1 option - which I assume is the 3D Printer I've got connected ?

If I choose that, I then apply what I assume to be the port settings (Baud/Parity etc)  - it results in serial:/dev/ttyUSB0?baud=230400) and then on the next screen I assign a name/details and location, and after than - I can only assume I have to choose 'Generic Printer' ? is that correct ?

It so, on from there, where it's looking for a model,  I have no idea what to do/choose ? 

Does anyone have any suggestions ? (Many thanks)

**Comment by nodecentral** [comment]
Anyone, any suggestions ? Is this thing on ? [tap] [tap] ? 🤪

**Comment by michaelrsweet** [comment]
Sorry, CUPS doesn't support 3D printers, and it isn't what you want to use for this.

Look at the PWG's [ippsample](https://github.com/istopwg/ippsample) project - they have an ipp3dprinter program that shares a USB serial (gcode) 3D printer over IPP and is probably what you are looking for.
