### ISSUE TITLE
Cups server slow and unresponsive every 90 seconds or so

### ISSUE THREAD

**Issue by paulrattu** [apple/cups#5830]
Centos 7.6
Cups 1.6.3

Hello, I've noticed a weird issue with my cups server recently. The cups daemon and cups commands are very unresponsive after cups has been running for around 90 seconds or so. If I try to get to the cups GUI, that'll be unresponsive. If I try to run simple commands like lpstat -d, that will also be very slow and unresponsive. This is making it so if I want to print I need to restart cups  every single time. 

A couple of things I've noticed:
Whenever I run lpstat -d after I restart cups it will tell me the default printer I have set, but when cups starts bugging out it will just say "no system default destination"
On my linux workstations, no printers will populate in the printer settings unless I restart cups and then after 90 seconds they will disappear again.

I know this issue doesn't have to do with harddisk space or memory as those seem to be fine. I spun up a new server and installed cups on there, it worked fine for about a week before it started bugging out again. 

I've done some searching online, it seems like this was an issue that was resolved in later versions of cups, but 1.6.3 is the latest version available for Centos 7 afaik

I've checked the logs and they keep looping over and over again like this:
`D [14/Sep/2020:13:28:44 -0700] Get-Notifications /printers/
D [14/Sep/2020:13:28:44 -0700] Get-Notifications client-error-not-found: Subscription #290 does not exist.
D [14/Sep/2020:13:28:44 -0700] Returning IPP client-error-not-found for Get-Notifications (/printers/) from 10.0.45.177
D [14/Sep/2020:13:28:44 -0700] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
D [14/Sep/2020:13:28:45 -0700] [Client 88] POST / HTTP/1.1
D [14/Sep/2020:13:28:45 -0700] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"
D [14/Sep/2020:13:28:45 -0700] [Client 88] No authentication data provided.
D [14/Sep/2020:13:28:45 -0700] [Client 88] 1.1 Get-Notifications 5767`

Any help is appreciated

**Comment by michaelrsweet** [comment]
This is an old bug in the GNOME printer status monitor.

**Comment by paulrattu** [comment]
What's the fix? I've upgraded my server to CentOS 7.9 and I'm still having this problem

**Comment by zdohnal** [comment]
Hi,

please consider the following points:
1) This is a former upstream issue tracker, not CentOS bug tracker - if the issue is closed here doesn't mean it is fixed in CentOS
2) consider filing an issue on [CentOS bug tracker](https://bugzilla.redhat.com) under RHEL component.
