### ISSUE TITLE
gcc-10.2.0 ipptool compile error-message 

### ISSUE THREAD

**Issue by ohquait** [apple/cups#5832]
`/bin/rm -f libcupsimage.a
/usr/bin/ar crvs libcupsimage.a raster-interstub.o raster-stubs.o
a - raster-interstub.o
a - raster-stubs.o
ranlib libcupsimage.a
make[1]: Leaving directory '/repm/src/rpm/BUILD/cups-2.3.3/cups'
Making all in tools...
make[1]: Entering directory '/repm/src/rpm/BUILD/cups-2.3.3/tools'
echo Compiling ippevepcl.c...
Compiling ippevepcl.c...
clang  -fPIC -g -fstack-protector -D_GNU_SOURCE -I.. -D_CUPS_SOURCE -O2  -pipe -Wformat -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fstack-protector-all -fPIC -I/usr/include/libusb-1.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -DDBUS_API_SUBJECT_TO_CHANGE -D_FORTIFY_SOURCE=2 -D_REENTRANT -I/usr/include/p11-kit-1 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -Wall -Wno-format-y2k -Wunused -Wno-unused-result -Wsign-conversion -c -o ippevepcl.o ippevepcl.c
echo Linking ippevepcl...
Linking ippevepcl...
clang -L../cups  -Wl,-z,relro,-z,now  -fPIE -pie -fPIC -g -fstack-protector -D_GNU_SOURCE -o ippevepcl ippevepcl.o -L../cups -lcups
/bin/true -s "-" ippevepcl
echo Compiling ippeveps.c...
Compiling ippeveps.c...
clang  -fPIC -g -fstack-protector -D_GNU_SOURCE -I.. -D_CUPS_SOURCE -O2  -pipe -Wformat -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fstack-protector-all -fPIC -I/usr/include/libusb-1.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -DDBUS_API_SUBJECT_TO_CHANGE -D_FORTIFY_SOURCE=2 -D_REENTRANT -I/usr/include/p11-kit-1 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -Wall -Wno-format-y2k -Wunused -Wno-unused-result -Wsign-conversion -c -o ippeveps.o ippeveps.c
echo Linking ippeveps...
Linking ippeveps...
clang -L../cups  -Wl,-z,relro,-z,now  -fPIE -pie -fPIC -g -fstack-protector -D_GNU_SOURCE -o ippeveps ippeveps.o -L../cups -lcups
/bin/true -s "-" ippeveps
echo Compiling ippeveprinter.c...
Compiling ippeveprinter.c...
clang  -fPIC -g -fstack-protector -D_GNU_SOURCE -I.. -D_CUPS_SOURCE -O2  -pipe -Wformat -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fstack-protector-all -fPIC -I/usr/include/libusb-1.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -DDBUS_API_SUBJECT_TO_CHANGE -D_FORTIFY_SOURCE=2 -D_REENTRANT -I/usr/include/p11-kit-1 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -Wall -Wno-format-y2k -Wunused -Wno-unused-result -Wsign-conversion -c -o ippeveprinter.o ippeveprinter.c
echo Linking ippeveprinter...
Linking ippeveprinter...
clang -L../cups  -Wl,-z,relro,-z,now  -fPIE -pie -fPIC -g -fstack-protector -D_GNU_SOURCE -o ippeveprinter ippeveprinter.o -lavahi-common -lavahi-client -lpam -ldl -L../cups -lcups
/bin/true -s "-" ippeveprinter
echo Compiling ippfind.c...
Compiling ippfind.c...
clang  -fPIC -g -fstack-protector -D_GNU_SOURCE -I.. -D_CUPS_SOURCE -O2  -pipe -Wformat -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fstack-protector-all -fPIC -I/usr/include/libusb-1.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -DDBUS_API_SUBJECT_TO_CHANGE -D_FORTIFY_SOURCE=2 -D_REENTRANT -I/usr/include/p11-kit-1 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -Wall -Wno-format-y2k -Wunused -Wno-unused-result -Wsign-conversion -c -o ippfind.o ippfind.c
echo Linking ippfind...
Linking ippfind...
clang -L../cups  -Wl,-z,relro,-z,now  -fPIE -pie -fPIC -g -fstack-protector -D_GNU_SOURCE -o ippfind ippfind.o -lavahi-common -lavahi-client -L../cups -lcups
/bin/true -s "-" ippfind
echo Compiling ipptool.c...
Compiling ipptool.c...
clang  -fPIC -g -fstack-protector -D_GNU_SOURCE -I.. -D_CUPS_SOURCE -O2  -pipe -Wformat -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fstack-protector-all -fPIC -I/usr/include/libusb-1.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -DDBUS_API_SUBJECT_TO_CHANGE -D_FORTIFY_SOURCE=2 -D_REENTRANT -I/usr/include/p11-kit-1 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_THREAD_SAFE -D_REENTRANT  -Wall -Wno-format-y2k -Wunused -Wno-unused-result -Wsign-conversion -c -o ipptool.o ipptool.c
ipptool.c:2976:7: warning: implicit declaration of function 'ioctl' is invalid in C99 [-Wimplicit-function-declaration]
  if (ioctl(httpGetFd(http), SIOCOUTQ, &buffered))
      ^
ipptool.c:2976:30: error: use of undeclared identifier 'TIOCOUTQ'
  if (ioctl(httpGetFd(http), SIOCOUTQ, &buffered))
                             ^
/usr/include/linux/sockios.h:27:18: note: expanded from macro 'SIOCOUTQ'
#define SIOCOUTQ        TIOCOUTQ        /* output queue size (not sent + not acked) */
                        ^
1 warning and 1 error generated.
make[1]: *** [../Makedefs:271: ipptool.o] Error 1
make[1]: Leaving directory '/repm/src/rpm/BUILD/cups-2.3.3/tools'
make: *** [Makefile:42: all] Error 1
error: Bad exit status from /home/quait/src/tmp/rpm-tmp.6znR1o (%build)

`

**Comment by stalkerg** [comment]
You are using clang (lvvm) not a GCC.

**Comment by ohquait** [comment]
ok, now only gcc and gcc++ are installed on buildsystem

- ipptool.c: In function 'timeout_cb':
- ipptool.c:2976:7: warning: implicit declaration of function 'ioctl' [-Wimplicit-function-declaration]
-  2976 |   if (ioctl(httpGetFd(http), SIOCOUTQ, &buffered))
-       |      ^~~~~
- In file included from /usr/include/bits/socket.h:355,
-                  from /usr/include/sys/socket.h:33,
-                  from ../cups/http.h:34,
-                  from ../cups/ipp.h:18,
-                  from ../cups/cups.h:27,
-                  from ../cups/ipp-private.h:18,
-                  from ../cups/cups-private.h:20,
-                  from ipptool.c:15:
- ipptool.c:2976:30: error: 'TIOCOUTQ' undeclared (first use in this function); did you mean 'SIOCOUTQ'?
-  2976 |   if (ioctl(httpGetFd(http), SIOCOUTQ, &buffered))
-       |                                              ^~~~~~~~
- ipptool.c:2976:30: note: each undeclared identifier is reported only once for each function it appears in
- make[1]: *** [../Makedefs:270: ipptool.o] Error 1
- make[1]: Leaving directory '/repm/src/rpm/BUILD/cups-2.3.3/tools'
- make: *** [Makefile:42: all] Error 1
- error: Bad exit status from /home/quait/src/tmp/rpm-tmp.VWPzor (%build)

**Comment by michaelrsweet** [comment]
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
