### ISSUE TITLE
HP DesignJet 130 requires usb no-reattach on Ubuntu 18.04

### ISSUE THREAD

**Issue by hvfrancesco** [apple/cups#5838]
Struggled workingk with HP DesignJet 130 on a Ubuntu 18.04 server.
Previously was on a Debian server with older cups version and worked perfectly.
After moving to new machine it seemed not responding, had a lot of usblp removed messages in dmesg output and the printer was not printing at all.
lpadmin -p <queue> -o usb-no-reattach-default=true  apparently solved the issue.

This is lsbusb output:
Bus 003 Device 008: ID 03f0:0314 Hewlett-Packard designjet 30/130 series

**Comment by michaelrsweet** [comment]
Fixed in OpenPrinting CUPS

[master da2c49408] Don't reattach DesignJet 130 (Apple #5838)
