### ISSUE TITLE
Media Source Tray not working, how to resolve?

### ISSUE THREAD

**Issue by thefiredragon** [apple/cups#5841]
Dear all,
I tried over days to get cups working well, without an good result.

For my or our understanding there's also no good documentation.
We're using samba with cups.

I tried cups with the stable package from Debian stable repo and also the last release 2.3.3.

My testings are:

Printer IPP -> Cups <- Client IPP (not as an smb share)
I think it would be better when all levels use the same protocol level perhaps here's my mistake.

Kyocera M5526cdw  ipp://20.20.20.113:631/ipp/print 
ECOSYS M5526cdw, driverless, cups-filters 1.28.4 (farbig, 2-seitiges Drucken)

under cups settings I can select the media source tray but this is still ignoring the default setting.
When I connect my MacBook directly via ipp and select an other media source tray it's working perfectly.

For some our customers they use windows clients and we would need to get it working that we can preset over cups the media source tray or via an client. 

Also when I try to print over cups a test page it uses all-time only the first media source tray.

How I could debug this behavior ? 

I noticed when I connect the printer over ipp to cups and my MacBook over ipp under printer settings I can also see the ink status of my printer, well

The same problem we have with  Kyocera ECOSYS P2040dn
--

Is it a good choice to use ipp as default protocol ? I read a lot about it, also the handling between windows clients. 
For some help I would be really happy here at this point,

best Regards,
Dan

**Comment by jschwender** [comment]
The ipp implementation of Windows is something similar to version 1.1 (very old) and incomplete, so it is poorly made, just enough for pretention. Are you using a windows driver?

**Comment by michaelrsweet** [comment]
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
