### ISSUE TITLE
 The printer light flashed and did not print

### ISSUE THREAD

**Issue by liyou54** [apple/cups#5842]
I tried to print a pdf file but the printer only flashed the indicator light and did not print.
My cups version is 1.7.2
I turn on debug mode.

There is a warning: `This document does not conform to the Adobe Document Structuring Conventions and may not print correctly.`

In addition, I tried to use version 1.6.3, and it was able to print successfully

This is my failure log
`I [13/Oct/2020:14:38:41 +0800] [Job 573] Adding start banner page "none".
I [13/Oct/2020:14:38:41 +0800] [Job 573] Queued on "F12_WHITE_M227FDW" by "root".
D [13/Oct/2020:14:38:41 +0800] [Job 573] Auto-typing file...
D [13/Oct/2020:14:38:41 +0800] [Job 573] Request file type is application/pdf.
I [13/Oct/2020:14:38:41 +0800] [Job 573] File of type application/pdf queued by "root".
I [13/Oct/2020:14:38:41 +0800] [Job 573] Adding end banner page "none".
D [13/Oct/2020:14:38:41 +0800] [Job 573] time-at-processing=1602571121
D [13/Oct/2020:14:38:41 +0800] [Job 573] 3 filters for job:
D [13/Oct/2020:14:38:41 +0800] [Job 573] pdftopdf (application/pdf to application/vnd.cups-pdf, cost 66)
D [13/Oct/2020:14:38:41 +0800] [Job 573] pdftops (application/vnd.cups-pdf to application/vnd.cups-postscript, cost 100)
D [13/Oct/2020:14:38:41 +0800] [Job 573] hpps (application/vnd.cups-postscript to printer/F12_WHITE_M227FDW, cost 0)
D [13/Oct/2020:14:38:41 +0800] [Job 573] job-sheets=none,none
D [13/Oct/2020:14:38:41 +0800] [Job 573] argv[0]="F12_WHITE_M227FDW"
D [13/Oct/2020:14:38:41 +0800] [Job 573] argv[1]="573"
D [13/Oct/2020:14:38:41 +0800] [Job 573] argv[2]="root"
D [13/Oct/2020:14:38:41 +0800] [Job 573] argv[3]="增值税电子普通发票.pdf"
D [13/Oct/2020:14:38:41 +0800] [Job 573] argv[4]="1"
D [13/Oct/2020:14:38:41 +0800] [Job 573] argv[5]="finishings=3 number-up=1 job-uuid=urn:uuid:468e2660-66ae-3406-7e1d-836150a1c30b job-originating-host-name=localhost time-at-creation=1602571121 time-at-proc
essing=1602571121"
D [13/Oct/2020:14:38:41 +0800] [Job 573] argv[6]="/var/spool/cups/d00573-001"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[0]="CUPS_CACHEDIR=/var/cache/cups"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[1]="CUPS_DATADIR=/usr/share/cups"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[2]="CUPS_DOCROOT=/usr/share/cups/doc-root"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[3]="CUPS_FONTPATH=/usr/share/cups/fonts"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[4]="CUPS_REQUESTROOT=/var/spool/cups"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[5]="CUPS_SERVERBIN=/usr/lib/cups"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[6]="CUPS_SERVERROOT=/etc/cups"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[7]="CUPS_STATEDIR=/var/run/cups"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[8]="HOME=/var/spool/cups/tmp"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[9]="PATH=/usr/lib/cups/filter:/usr/bin:/usr/sbin:/bin:/usr/bin"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[10]="SERVER_ADMIN=root@ubuntu-InnerPrinter-28046"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[11]="SOFTWARE=CUPS/1.7.2"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[12]="TMPDIR=/var/spool/cups/tmp"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[13]="USER=root"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[14]="CUPS_MAX_MESSAGE=2047"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[15]="CUPS_SERVER=/var/run/cups/cups.sock"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[16]="CUPS_ENCRYPTION=IfRequested"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[17]="IPP_PORT=631"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[18]="CHARSET=utf-8"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[19]="LANG=en_US.UTF-8"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[20]="PPD=/etc/cups/ppd/F12_WHITE_M227FDW.ppd"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[21]="RIP_MAX_CACHE=128m"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[22]="CONTENT_TYPE=application/pdf"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[23]="DEVICE_URI=socket://192.168.8.240"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[24]="PRINTER_INFO=12楼白色打印机"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[25]="PRINTER_LOCATION=12楼"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[26]="PRINTER=F12_WHITE_M227FDW"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[27]="PRINTER_STATE_REASONS=none"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[28]="CUPS_FILETYPE=document"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[29]="FINAL_CONTENT_TYPE=printer/F12_WHITE_M227FDW"
D [13/Oct/2020:14:38:41 +0800] [Job 573] envp[30]="AUTH_I****"
I [13/Oct/2020:14:38:41 +0800] [Job 573] Started filter /usr/lib/cups/filter/pdftopdf (PID 27011)
I [13/Oct/2020:14:38:41 +0800] [Job 573] Started filter /usr/lib/cups/filter/pdftops (PID 27012)
I [13/Oct/2020:14:38:41 +0800] [Job 573] Started filter /usr/lib/cups/filter/hpps (PID 27013)
I [13/Oct/2020:14:38:41 +0800] [Job 573] Started backend /usr/lib/cups/backend/socket (PID 27014)
D [13/Oct/2020:14:38:41 +0800] [Job 573] pdftops - copying to temp print file "/tmp/069845f8b51ac"
D [13/Oct/2020:14:38:41 +0800] [Job 573] HP PS filter starting : F12_WHITE_M227FDW 
D [13/Oct/2020:14:38:41 +0800] [Job 573] hppsfilter: argv[0] = F12_WHITE_M227FDW
D [13/Oct/2020:14:38:41 +0800] [Job 573] hppsfilter: argv[1] = 573
D [13/Oct/2020:14:38:41 +0800] [Job 573] hppsfilter: argv[2] = root
D [13/Oct/2020:14:38:41 +0800] [Job 573] hppsfilter: argv[3] = 增值税电子普通发票.pdf
D [13/Oct/2020:14:38:41 +0800] [Job 573] hppsfilter: argv[4] = 1
D [13/Oct/2020:14:38:41 +0800] [Job 573] hppsfilter: argv[5] = finishings=3 number-up=1 job-uuid=urn:uuid:468e2660-66ae-3406-7e1d-836150a1c30b job-originating-host-name=localhost time-at-creation=1602571121
 time-at-processing=1602571121
D [13/Oct/2020:14:38:41 +0800] [Job 573] HP PS filter func = WriteHeader           : WRITING PJL HEADER INFO
D [13/Oct/2020:14:38:41 +0800] [Job 573] HP PS filter func = GetPPDValues : PPD NAME /etc/cups/ppd/F12_WHITE_M227FDW.ppd
D [13/Oct/2020:14:38:41 +0800] [Job 573] HP PS filter func = WriteJobAccounting    : WRITING JOB ACCOUNTING INFO
D [13/Oct/2020:14:38:41 +0800] [Job 573] HP PS filter func = WriteBornOnDate       : WRITING BORN-ON-DATE
D [13/Oct/2020:14:38:41 +0800] [Job 573] HP PS filter func = WriteECONOMODE        : WRITNING ECONOMODE
D [13/Oct/2020:14:38:41 +0800] [Job 573] HP PS filter func = WriteHPPJLPRINTQUALITY: WRITING PRINT QUALITY INFO
D [13/Oct/2020:14:38:41 +0800] [Job 573] STATE: +connecting-to-device
D [13/Oct/2020:14:38:41 +0800] [Job 573] Looking up "192.168.8.240"...
D [13/Oct/2020:14:38:41 +0800] [Job 573] backendWaitLoop(snmp_fd=5, addr=0x7f301c603448, side_cb=0x7f301b5641f0)
D [13/Oct/2020:14:38:41 +0800] [Job 573] Connecting to 192.168.8.240:9100
I [13/Oct/2020:14:38:41 +0800] [Job 573] Connecting to printer.
D [13/Oct/2020:14:38:41 +0800] [Job 573] Set job-printer-state-message to "Connecting to printer.", current level=INFO
D [13/Oct/2020:14:38:41 +0800] [Job 573] STATE: -connecting-to-device
I [13/Oct/2020:14:38:41 +0800] [Job 573] Connected to printer.
D [13/Oct/2020:14:38:41 +0800] [Job 573] Set job-printer-state-message to "Connected to printer.", current level=INFO
D [13/Oct/2020:14:38:41 +0800] [Job 573] Connected to 192.168.8.240:9100...
D [13/Oct/2020:14:38:41 +0800] [Job 573] backendRunLoop(print_fd=0, device_fd=6, snmp_fd=5, addr=0x7f301c603448, use_bc=1, side_cb=0x7f301b5641f0)
D [13/Oct/2020:14:38:41 +0800] [Job 573] Received 106 bytes of back-channel data
D [13/Oct/2020:14:38:41 +0800] [Job 573] PID 27011 (/usr/lib/cups/filter/pdftopdf) exited with no errors.
D [13/Oct/2020:14:38:41 +0800] [Job 573] Printer make and model: HP LaserJet MFP M227-M231
D [13/Oct/2020:14:38:41 +0800] [Job 573] Running command line for pstops: pstops 573 root 增值税电子普通发票.pdf 1 'finishings=3 job-uuid=urn:uuid:468e2660-66ae-3406-7e1d-836150a1c30b job-originating-host-n
ame=localhost time-at-creation=1602571121 time-at-processing=1602571121'
D [13/Oct/2020:14:38:41 +0800] [Job 573] Using image rendering resolution 600 dpi
D [13/Oct/2020:14:38:41 +0800] [Job 573] Running command line for gs: gs -q -dNOPAUSE -dBATCH -dSAFER -sDEVICE=ps2write -sOUTPUTFILE=%stdout -dLanguageLevel=3 -r600 -dCompressFonts=false -dNoT3CCITT -dNOINT
ERPOLATE -c 'save pop' -f /tmp/069845f8b51ac
D [13/Oct/2020:14:38:41 +0800] [Job 573] Started filter gs (PID 27015)
D [13/Oct/2020:14:38:41 +0800] [Job 573] Started filter pstops (PID 27016)
D [13/Oct/2020:14:38:41 +0800] [Job 573] Page = 595x842; 12,12 to 583,830
D [13/Oct/2020:14:38:41 +0800] [Job 573] slow_collate=0, slow_duplex=0, slow_order=0

D [13/Oct/2020:14:38:41 +0800] [Job 573] This document does not conform to the Adobe Document Structuring Conventions and may not print correctly.

D [13/Oct/2020:14:38:42 +0800] [Job 573] Read 8188 bytes of print data...
D [13/Oct/2020:14:38:42 +0800] [Job 573] Wrote 8188 bytes of print data...
..............
D [13/Oct/2020:14:38:42 +0800] [Job 573] Set job-printer-state-message to "Waiting for printer to finish.", current level=INFO
D [13/Oct/2020:14:38:42 +0800] [Job 573] Received 1 bytes of back-channel data
D [13/Oct/2020:14:38:42 +0800] [Job 573] PID 27014 (/usr/lib/cups/backend/socket) exited with no errors.
D [13/Oct/2020:14:38:42 +0800] [Job 573] time-at-completed=1602571122
I [13/Oct/2020:14:38:42 +0800] [Job 573] Job completed.
D [13/Oct/2020:14:38:43 +0800] [Job 573] Unloading...
`

**Comment by liyou54** [comment]
I have printed other pdf  file,it work

**Comment by michaelrsweet** [comment]
This is either a [cups-filters](https://github.com/openprinting/cups-filters) issue or an HPLIP issue (since this is using the HPLIP PostScript filter).
