### ISSUE TITLE
Possible to customize 'pdl' value in _ipp._tcp. Bonjour txt record to force AirPrint to jpg instead of PDF?

### ISSUE THREAD

**Issue by Waxhaw** [apple/cups#5849]
I've got a serious performance issue.  I'm trying to configure a specialized sublimation photo printer that has been optimized for JPG and is shared via Bonjour as a printer service for AirPrint to pick up.

Here is a subset of the txt record:

```
pdl = application/octet-stream,application/pdf,application/postscript,image/jpeg,image/png,image/pwg-raster
printer-state = 3
printer-type = 0x80100E
priority = 0
product = (DP-DS820)
qtotal = 1
rp = printers/Dai_Nippon_Printing_DP_DS820
TLS = 1.2
txtvers = 1
ty = Dai Nippon Printing DP-DS820, 5.1.2 (build 553) (CUPS)
```

So the issue is AirPrint is 'driverless' and it seems to 'automagically' convert EVERYTHING to a PDF and then transmit it over the network.

Here are the raw image details:

- HEIF/HEIC from iOS 14.2 device has a total file size 2.4MB
- JPG version of this same file at 75% image compression quality is 2.9MB
- AirPrint sends (based on the raw data file in /var/spool/ folder) a PDF data file that is 36.6 MB in size

The raw image file is captured using a 'prefilter' in the PPD printer file to copy it.  Nothing else touches that before or after the prefilter. I'm 99.9% certain that is the payload coming to me from iOS 14.2 over the wire via AirPrint.

It's really confusing to know where to look and what to tweak because this is all behind the curtains for AirPrint.

This printer is only a 300dpi photo printer.

I'm trying to optimize print speed, especially for AirPrint via CUPS and it's proving very difficult.

My hope is that I could 'customize' the pdl var to ONLY show the following:
`pdl = image/jpeg`

This would force newer iOS devices that 'might' export the photo as an HEIC/HEIF image to convert it to 'jpeg' and then transmit it on the wire instead of sending me a large PDF container.

So on older versions of Ubuntu you had to install Avahi and create a 'service' record.  I'm currently on CUPS 2.2.10 and if I go into CUPS and share the printer, it will set it up and share the printer services records so you can print to it from iOS WITHOUT having to install Avahi or create an XML txt record in the Avahi service folder on the print server side.

It appears CUPS now 'automagically' handles Avahi and installs it on the fly with CUPS now and I'm not sure how to tweak any of this now.

Anyone out there have advice on how to pull this off?  I want this printer to ONLY advertise jpg raw image data and force AirPrint to only send that format.  Ideally I could also set a quality value.  If not I'm find with sending it as PNG as well.

If AirPrint always forces PDF for 'driverless printing', I'm sunk.

TIA!

**Comment by jschwender** [comment]
If the txt record is coming from the device, the only way to change it is either changing settings, if possible, or changing the printer's  firmware. If the record comes from an avahi daemon on a linux server, you can configure it just as you like, and try if it helps your printing issue.

**Comment by Waxhaw** [comment]
> If the txt record is coming from the device, the only way to change it is either changing settings, if possible, or changing the printer's firmware. If the record comes from an avahi daemon on a linux server, you can configure it just as you like, and try if it helps your printing issue.

The .Service txt record appears to only work for _ipp traffic and that traffic is NO longer used by the newer versions of iOS.  iOS will only see printers for AirPrint that are broadcasting over HTTPS via _ipps traffic.  I'm not able to find how to change that record or where it is even stored.

To put another way.  The Avahi Daemon on Ubuntu is no longer needed as it's own "apt get install". If you get CUPS and share the printer it shows up for AirPrint but I'm still not sure how.  There isn't a Service record that I'm able to find.

**Comment by jschwender** [comment]
CUPS itself does not come with service discovery functionality. Earlier CUPS had it's own browsing protocol implemented. That used to be a broadcasting protocol. This function was detached and put as a multicast protocol (mDNS+DNS-SD) into into Bonjour (Rendevouz) on MAC OS and to avahi on Linux, BSD....  What you show above could be a DNS-SD resource record from a DNS server. If you have that record manually configured in the DNS, then you would not need avahi on the server to share the printer. Maybe you have a look to your dnsmasq or bind9 config?

**Comment by Waxhaw** [comment]
If what you say is true then how does CUPS 'share' a directly attached USB printer on the network?  It can only do that by publishing a TXT record right?

**Comment by jschwender** [comment]
CUPS has a backend called dnssd. Unfortunaltely it is not well documented, but i think it queries avahi.

**Comment by Waxhaw** [comment]
Thanks for the tip!  Digging into the code in that area now.  The issue is that HEIF/HEIF is not a mime type like JPEG.  So a photo printer share for AirPrint ends up getting a PDF.  PDF doesn't compress the image so we go from a 3MB HEIC to a 36MB PDF.  It's orders of magnitude slower than just printing a JPG photo.  I'm hoping I can tweak what is 'shared' via CUPS to the iPhone and have iOS send me a JPG.  The AirPrint team is super distant and their web site examples are ancient and will not compile or run on anything recent.

**Comment by Waxhaw** [comment]
Just to help document the issue.  If a user does an AirPrint of a JPEG image that is what is sent to the /var/spool/cups folder.  To take a JPG photo you have to go into Settings->Camera->Formats->Most Compatible (check this)
By default photos are saved with the HEIF/HEIC format.

Since this mime type is not in the PDL record a 3MB image gets ballooned into a 36MB PDF and transmitted via AirPrint.
AirPrint SHOULD be sending me a JPG AND/OR give me the option for an HEIC mime type but it doesn't.

Most iPhone users are using the latest Camera setting and AirPrint isn't optimized for it.  :-(

**Comment by Waxhaw** [comment]
I'm going to close this issue and move it to the Open Printing are located here:
https://github.com/OpenPrinting/cups-filters

It also makes me think this is a bug in iOS since they've clearly documented at the link above how it SHOULD work.

>     This is done to support photo printing via AirPrint. The photo
>     apps on Apple's iOS devices send print jobs as JPEG images and do
>     not allow to set any options like "scaling" or the page size. With
>     "scale-to-fit" mode set by default, the iOS photos come out on one
>     page, as expected.
