### ISSUE TITLE
Delay of 10sec to start printing - CUPS v2.2.6

### ISSUE THREAD

**Issue by RPMenon** [apple/cups#5852]
Hello out there, Help required.

  The CUPS version used in source code is 2.2.6, CUPS filter version is 1.20.3
  OS : Linux / Ubuntu 12.04.4
  SNMP is OFF.
  Printer : HP office jet 200 mobile printer
  WIFI direct printing used.
  
  There is a delay of about 10sec for the printing to start (printing single page). Any idea why this might happen ?
  Will upgrading to latest CUPS version 2.3.3 resolve the issue ?
  
   
  I am a beginner in this. Any suggestion would be of great help.

**Comment by jschwender** [comment]
This printer claims to support AirPrint, you may try to use the cups driver ippEverywhere. You may test if 2.3.3 helps or not. On the other hand ubuntu 12 is 6 years after EOL , it is certainly challenging to compile it  and get it running. I would install new.

**Comment by michaelrsweet** [comment]
Please contact the [OpenPrinting CUPS](https://github.com/openprinting/cups) project for assistance.
