### ISSUE TITLE
Print .docx file using Cups

### ISSUE THREAD

**Issue by smudgal-omers** [apple/cups#5853]
Hello, I want to print .docx files using cups and I am using cups-pdf as the printer.

When I try to print .docx files, the output pdf is always empty using cups-pdf.

Is there a way, I can leverage cups's capabilities to print a .docx file?
I see from cups config files that three following application file formats are supported by cups ootb to print:
application/msword (this one prints only .doc files and not .docx)
application/pdf
application/postscript

So, .docx files are not supported by cups but I want to know if there are any options/ways to do it using filters or any other mechanism.

**Comment by jschwender** [comment]
You can configure filters for anything. If you have a filter that can process docx to pdf you can use that in cups. You could try libreoffice, it is able to do that from command line. good luck.

**Comment by smudgal-omers** [comment]
the filter you are mentioning, is it the `officetops` filter? that one seems to need Libreoffice installed and needs manual steps  to be undertaken and completed. My restriction is that I can do it only through code.

**Comment by smudgal-omers** [comment]
closed the issue by mistake.

**Comment by jschwender** [comment]
Yes, you need to install libreoffice to use it. 
i have not tested with docx because i don't use docx at all, but in general it works like this:
`unoconv --stdout filename.doc `
The pdf is outputted to stdout and can be used in a filter.
Alternatively you may print into a file like this:
`libreoffice7.0 --headless --print-to-file  --outdir /tmp filename.docx`
In any case you need to make up that filter yourself, cups provides only the possibility to insert filters.

**Comment by jsmeix** [comment]
@smudgal-omers 
when you want to print .docx files from Linux systems you may have a look at
"Using Your Own Filters to Print with CUPS"
https://en.opensuse.org/SDB:Using_Your_Own_Filters_to_Print_with_CUPS

This article is somewhat old so this or that details could be different now
in particular depending on what Linux distribution you use
but the general basic ideas and methods are still valid.

When you want to print .docx files from Windows client systems
via CUPS on a Linux computer you may have a look at
"Printing from Windows to Linux"
https://en.opensuse.org/SDB:Printing_from_Windows_to_Linux

When you do not want to actually print .docx files (i.e. get output on paper)
but actually you want to convert .docx files into PDF files, then
probably the best way is to load the .docx file into LibreOffice
and from within LibreOffice export it as a PDF file.
Related to that you may have a look at
"Printing to PDF"
https://en.opensuse.org/SDB:Printing_to_PDF

**Comment by debiantriage** [comment]
On Mon 23 Nov 2020 at 14:04:17 -0800, jschwender wrote:

> Yes, you need to install libreoffice to use it.

Coupling the use of LibreOffice with the Tea4CUPS backend gives a
viable technique for printing docx.

https://wiki.debian.org/CUPSTea4CUPS

Cheers,

Brian.

**Comment by smudgal-omers** [comment]
These are all very valuable suggestions @jsmeix @jschwender @debiantriage , however we're also using Sharepoint in our dev environment and will be using its own functionality to download docx as PDF (and print that) and won't probably need to print .docx using Cups.

We do not have the liberty to install LibreOffice (to use the existing filters like OfficeTops or create our own) on the vm we are running Cups and Cups-PDF, thus we'll be printing converted PDFs.

Thanks for the suggestions though!
