### ISSUE TITLE
I do not have enough knowledge to install the cups update-help!!!

### ISSUE THREAD

**Issue by APsWydoK** [apple/cups#5856]
I don't know what I have to put in the command line(s) in the terminal in order to get this to work. My printer is useless, at this point. I could really use some hand-holding to get things working. Help me, please! Thank you.

**Comment by jschwender** [comment]
What OS? Version? What did you do? What printer?

**Comment by APsWydoK** [comment]
I am running Ubuntu 20.04.1 LTS (Studio)
What I did was to update/upgrade to said version of Ubuntu, which then
meant I had to update/upgrade hplip to run my printer (an HP OfficeJet Pro
8610)
The process of running hplip seems to get more complex with each update, &
I think I picked the wrong python level, & then couldn't get that to
correct.
When I asked for help with hplip, it was suggested that I "forget about"
hplip, & work with cups instead. But the specific commands for the terminal
are not included anywhere in the cups documentation & I have forgotten most
of what I learned years ago about terminal commands. Sigh. Once upon a
time, before my husband died suddenly 8 years ago, I aspired to web design,
so I studied some of this stuff in community college & other training
entities, but time & tendinitis of wrists & elbows & arthritis in my neck,
moved me away from heavy computer use time, so I've lost a lot in the
intervening years. I like not being in the clutches of either Microsoft or
Apple, & a former friend (who helped me build the desktop I still use now;
I just bought a new Linux Ubuntu laptop to use @ my "other" location. I'm
in a relatively new relationship which has resulted, along with the effects
of Covid-19 on society, in my migrating back & forth between my own house,
where I live alone, & my partner's house, where he lives with several other
family members) encouraged & abetted me in going the route of Linux. My
life is, in a word, complicated. TMI, probably.
I have other issues with both this desktop machine, (it's dual boot & won't
do the upgrade to Windows 10; the Win7 is hopelessly mangled, apparently; I
almost never use it any more) & the new laptop, (which won't run video @
the moment; I think that'll get resolved with the support from the machine
builders soon) but those are for another day & time.

Thank you for reaching out to help.

**Comment by jschwender** [comment]
ok, i would also recommend to uninstall hplip, it is outdated and no more needed. This model supports AirPrint, which is all you need to get it running with CUPS: You just connect the printer to the local network, and it should appear a few moments later in you CUPS printer choice. No need to install anything but cups. What specific commands for terminal are you missing?
