### ISSUE TITLE
Two ways to define default  printer cause problems when deleting the default printer

### ISSUE THREAD

**Issue by sjvudp** [apple/cups#5858]
First, I'm using an old CUPS version, i.e.: 1.7.5
Some time after having deleted the default printer (it seems) I got some strange behavior:
`lpstat -s` is reporting a `system default destination` (e.g. `bw-laser`, a class), while `lpstat -d` reports `no system default destination`.
`lp` also reports `Error - no default destination available`.
I had a hard time finding out what's going on, and an strace helped me finding out:
The commands were requesting a printer that does not exist any more!
So at least this means a better error message would have been "system default destination XYZ does not exist".
Still one could argue whether such a situation should exist ever.

Eventually I found the source of the problem: `/etc/cups/lpoptions` contained  `Default XYZ` while `classes.conf` contained `<DefaultClass bw-laser>`.
Finally it made me wonder whether it makes any sense to use `lpoptions -d XYZ` as `root`: Why are there two places to define the system default printer? Note: I'm not talking about `~/.cups/lpoptions`, but about `/etc/cups/lpoptions`.

And when deleting a printer: Why not adjust the default printer(s) then?

**Comment by michaelrsweet** [comment]
The server default applies to any client that is pointed at it in the client.conf file. The lpoptions default overrides the server default, and running as root sets the default for all users on the system.

Now, deleting a printer *does* update the server default printer. It doesn't affect the client defaults (which may be set on multiple machines), but in current CUPS releases the client default is ignored if the printer no longer exists (so you'll revert to the server default...)
