### ISSUE TITLE
Cups hangs. 

### ISSUE THREAD

**Issue by rewolff** [apple/cups#5859]
The label printer suddenly stopped working. It is connected through USB to an orange pi zero. (and available on the network through the orange pi)> 

Turns out cupsd is at 100% CPU and in a loop: 
```
read(14, "", 2047)                      = 0
wait4(-1, 0xbe83e360, WNOHANG, NULL)    = -1 ECHILD (No child processes)
epoll_wait(4, [{EPOLLHUP, {u32=39667576, u64=15724733714399053688}}], 4096, 1000) = 1
read(14, "", 2047)                      = 0
wait4(-1, 0xbe83e360, WNOHANG, NULL)    = -1 ECHILD (No child processes)
epoll_wait(4, [{EPOLLHUP, {u32=39667576, u64=15724733714399053688}}], 4096, 1000) = 1
```
From this and confirmed by ps, it looks as if this is the cupsd main process that expects a child to finish or data from said child, but somehow the pipe has been closed (EOF on fd 14) and the child hasn't exited (or has been reaped already). 

You're going to ask what version I'm using. 
`billy:~# cupsd --version
`
doesn't work. dpkg tells me: 2.2.7-1ubuntu2.4

Workaround for me, for now: OK. The deamon had a subprocess and killing that made it work.

**Comment by jschwender** [comment]
What subprocess was that?

**Comment by rewolff** [comment]
It said "cupsd" in the pstree output.

**Comment by michaelrsweet** [comment]
Please contact the [OpenPrinting CUPS](https://github.com/openprinting/cups) project for assistance.
