### ISSUE TITLE
cupsGetDests2 shows deleted printers

### ISSUE THREAD

**Issue by ToddAndMargo** [apple/cups#5862]
Dear Cups Maintainers,

Fedora 33

# rpm -qa cups\*
cups-pk-helper-0.2.6-10.fc33.x86_64
cups-pdf-3.0.1-10.fc33.x86_64
cups-libs-2.3.3-18.fc33.x86_64
cups-client-2.3.3-18.fc33.x86_64
cups-ipptool-2.3.3-18.fc33.x86_64
cups-filesystem-2.3.3-18.fc33.noarch
cups-2.3.3-18.fc33.x86_64
cups-libs-2.3.3-18.fc33.i686
cups-filters-libs-1.28.5-3.fc33.x86_64
cups-filters-1.28.5-3.fc33.x86_64

I clean up a bunch of my unused printers.

Problem: printers with the same long name, except for the end still show in certain programs.

$ lpstat -a
B4350 accepting requests since Thu 29 Oct 2020 01:36:30 PM PDT
Cups-PDF accepting requests since Tue 30 Apr 2019 04:05:39 PM PDT
Virtual_PDF_Printer accepting requests since Tue 29 Sep 2020 03:13:17 AM PDT

Which is the way it is suppose to be. And match http://127.0.0.1:621 and Printer Admin

But programs using reading printers using cupsGetDests2, still get the old deleted printers:

The C text: https://bugs.documentfoundation.org/attachment.cgi?id=167701

The Binary: https://bugs.documentfoundation.org/attachment.cgi?id=167702

#include <iostream>
#include <cups/cups.h>

int main() {
cups_dest_t* dests;
int nCount = cupsGetDests2(CUPS_HTTP_DEFAULT, &dests);

for (int i = 0; i < nCount; i++) {
cups_dest_t dest = dests[i];
std::cout << dest.name << std::endl;
} 
}

$ list-printers
B4350
Cups-PDF
Cups_PDF_rn6             <-- deleted
Oki_B4350_on_dev_lp0_rn6 <-- deleted
Virtual_PDF_Printer
Virtual_PDF_Printer_rn6  <-- deleted

Programs without the problem (a sampling):

Brave Browser, Firefox, Vivaldi, Water Fox, Leafpad, Simple scan, Gimp, Inkscape, Thunderbird, Geany, Shotwell, PDF Studio 2019

Programs with the problem (also a sampling):

Wine, Libre Office, Free Office, Master PDF Editor

Any ideas? Is cupsGetDests2 not the proper way of doing this?

-T

**Comment by jschwender** [comment]
I tried do reproduce that on my ubuntu linux: installed a printer with mentioned naming scheme, deleted it. On Ubuntu 20.10 with CUPS 2.3.3 installed, the above list-printers command does not show the deleted printers. The list result is identical to lpstat -a  or cat /etc/printcap.

**Comment by ToddAndMargo** [comment]
I have seen other people on the fedora mailing list complaining of the same thing.  

Here is my printcap and printers.conf.   The extra deleted printer are nowhere to be found

[printers.conf.txt](https://github.com/apple/cups/files/5646359/printers.conf.txt)

From https://code.woboq.org/gtk/include/cups/cups.h.html I am seeing:

extern int  cupsGetDests2(http_t *http, cups_dest_t **dests)  _CUPS_API_1_1_21;

But I can't read C, so I don't know how cupsGetDests2 is generating its list.

Do you know how cupsGetDests2 is generating its list?

**Comment by ToddAndMargo** [comment]
Follow up:

These are not extras that did not delete when I deleted the originals.  What transpired was the I was experimenting with several way to access a parallel port card and had created several printers using "_rn6" at the end of their names.  "_rn6" is the host name of the computer.

What I "thought" were un-deleted printers was actually the name cups tacks a printer that is shared on the network.  An d it took me several day to realize I was looking at a coincidence.  "cupsGetDests2" in its "ultimate  wisdom" list both the local name and the shared name:

Cups-PDF  <-- local name
Cups_PDF_rn6 <-- shared name
 
Virtual_PDF_Printer  <-- local name
Virtual_PDF_Printer_rn6  <--shared name

Now I will go wipe some eggs off my face.  Thank you for your patience.
