### ISSUE TITLE
CUPS printer-state-reasons not responding

### ISSUE THREAD

**Issue by ShaikhShoeb01** [apple/cups#5864]
Hello ,

I am a college student making project to print pdf files. I'm using PyCUPS for it.
While printing I want to know if there is no paper in the tray  or paper is stuck or marker-supply-empty . For this, I am trying to use 'printer-state-reasons' parameter of getPrinterAttributes().
But the printer-state-reasons is not changing/responding even if the paper emptied or jammed and it is unchanging as ['none'] 
getJobAttributes() is working well for my printer but it's not
Why is it so happening 
Any other suggestion is welcomed
Thanks in advance
I am working on Ink Jet L130 printer
	
Below is the sample snippet of my program:

            printer_reason = print_dict['printer-state-reasons']
			
			if printer_reason == ['none']:        #<--------------------HERE-----------------------
				print("EveryThing Working Fine")
                       elif printer_reason == ['media-needed']:
                               print("Please Insert paper in the tray ")
                       else printer_reason == ['marker-supply-low']:
			      print("Please Fills up the ink in the ink-tank ")

**Comment by michaelrsweet** [comment]
Sorry, we don't support PyCUPS here, perhaps you can contact the author?
