### ISSUE TITLE
Arkscan 2054A label printers

### ISSUE THREAD

**Issue by chris00001** [apple/cups#5867]
I am working on adding/improving support for "Arkscan 2054A" label printers. These printers have the same issues as the Zebra printers below when used via USB. Please add the following to the quirks file to resolve the issue. 

# All Arkscan devices (same issue as Zebra https://bugs.launchpad.net/bugs/1001028) (Issue #5395))
0x2d84 unidir no-reattach

I've added and tested thoroughly the above solution on two different (one USB-only and one USB and ethernet variation) already by editing the /usr/share/cups/usb/org.cups.usb-quirks on a Manjaro system with CUPS 2.3.3op1 as shown above.

The fix for the Zebra printers has already been applied and is the same as below minus the different device ID ranges:

# All Zebra devices (https://bugs.launchpad.net/bugs/1001028) (Issue #5395)
0x0a5f unidir no-reattach

**Comment by michaelrsweet** [comment]
I'll apply this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.

**Comment by michaelrsweet** [comment]
[master c11253c1f] Add USB quirk rule for Arkscan label printers (Apple #5867)
