### ISSUE TITLE
[Feature Request] RESTful API

### ISSUE THREAD

**Issue by yarons** [apple/cups#5869]
Is there any chance to develop a fully working standard RESTful API for CUPS both for managing and printing?

Thanks.

**Comment by freewms** [comment]
Also interesting

**Comment by michaelrsweet** [comment]
Since CUPS supports IPP, which is a well-defined HTTP-based protocol, and there are many IPP client implementations (including Javascript) that can help you do IPP requests, and JSON doesn't provide the necessary value fidelity for IPP, we won't be adding a RESTful interface to CUPS, sorry.

**Comment by yarons** [comment]
OK, I gave up on printing with JSON because it's suboptimal and I agree but what about managing CUPS?

Adding a printer, changing its name, printing a test page, retreiving the jobs and their statuses and all the usual maintenance, I understand that it might not fully replace IPP but I see that as a growing need and a fairly reasonable request, otherwise one would probably need to develop some PHP gateway to translate JSON requests to the internal command line API and get the results back instead of doing it just the way the Web UI does it.

Just an example:
https://stackoverflow.com/questions/28454591/add-new-printers-using-cups-api
https://github.com/nathanstitt/restful-printing
https://github.com/dlazesz/driverless-print-and-scan

And I can guarantee these are not the only customers for this solution, CUPS has become the defacto standard for massive printers deployment and such feature will benefit in large scale deployments.
IPP is great but as you can see, the clients are evolving around these limitations instead of simply using CUPS.

**Comment by michaelrsweet** [comment]
@yarons See the [CUPS Implementation of IPP](https://www.cups.org/doc/spec-ipp.html). **ALL** administration functions that are provided by the command-line tools use IPP operations. IPP is a HTTP-based protocol. Implementations of IPP exist for JavaScript, Python, PHP, Ruby, Go, C/C++, etc. *Why* would you need to use a RESTful interface when you already have a well-defined, well-supported, and secure HTTP interface already?
