### ISSUE TITLE
won't print right

### ISSUE THREAD

**Issue by vimailme** [apple/cups#5870]
I tried fixing orientation but the click and ship stamps is off center then when I tried to fix that it is now printing very small. or it becomes too over sized and keeps labeling printer as 8x11 when I changed it to 4x6.  I am wasting so much label paper. Please help me configure this. I have a Mac. Its very annoying. Damn printer does not even have instructions just some pictures and YouTube is no help. They had one video and it is silent. WTF. Very annoyed right now. Highly. need major help.

**Comment by michaelrsweet** [comment]
What printer are you using?

What version of macOS are you using?

What application are you printing from?

**Comment by michaelrsweet** [comment]
Closing, will reopen if we get more info...
