### ISSUE TITLE
How to I share CUPS printer to windows?

### ISSUE THREAD

**Issue by 0byt3** [apple/cups#5872]
On Debian I am using avahi-daemon to advertise the printer with mDNS. In Windows 10, when I search for the printer, it appears, but the printer fails to install after I click the Add button. Is the a driver issue? Should I be sharing with SAMBA?

**Comment by michaelrsweet** [comment]
Samba is currently the only solution. The next feature release of [OpenPrinting CUPS](https://github.com/openprinting/cups) includes support for Windows 10's IPP class driver.
