### ISSUE TITLE
32bit compile error: sign conversion

### ISSUE THREAD

**Issue by shoober420** [apple/cups#5874]
When compiling cups in 32bit, I receive an error.

Here is the log.
[lib32-libcups-minimal-git-2.3.3-1-x86_64-build.log](https://github.com/apple/cups/files/5740721/lib32-libcups-minimal-git-2.3.3-1-x86_64-build.log)

**Comment by shoober420** [comment]
Here are the build flags I used.

https://gist.github.com/shoober420/4a853bc6739b968d83498deda6e3f7aa

**Comment by michaelrsweet** [comment]
Please verify this with the current OpenPrinting CUPS release, and if it still occurs report it to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
