### ISSUE TITLE
flto compile error

### ISSUE THREAD

**Issue by shoober420** [apple/cups#5875]
Compiling with the flto flag will cause a build error.

Here is the log.
[libcups-nosystemd-minimal-git-1:v2.3.3-1-x86_64-build.log](https://github.com/apple/cups/files/5740745/libcups-nosystemd-minimal-git-1.v2.3.3-1-x86_64-build.log)

**Comment by shoober420** [comment]
Here are the build flags I used.

https://gist.github.com/shoober420/4a853bc6739b968d83498deda6e3f7aa

**Comment by michaelrsweet** [comment]
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
