### ISSUE TITLE
HP Laser MFP 135A driver issue

### ISSUE THREAD

**Issue by hadifarnoud** [apple/cups#5876]
I found no driver for MFP 135A. I tried a few other drivers but it prints gibberish. Is there any specific driver that is close enough to MFP 135A?

also on MacOS, I can select a model in macOS too but there is no HP MFP 135A in that list either.

**Comment by michaelrsweet** [comment]
This is a Windows GDI printer and is not supported on any operating system besides Windows, unfortunately...
