### ISSUE TITLE
Cups HTML template pages should be tuned

### ISSUE THREAD

**Issue by scamhi** [apple/cups#5878]
Two items for cleanup:

1. For pages with a single textfield, the templates should be changed to be: 
`<input type="text" id="fname" name="fname" autofocus>'`
Should also be selecting the first item on a page with multiple controls as well.
1. For items with checkboxes, they should be changed to something like:
`  <label for="other">Other</label>
  <input type="radio" name="gender" id="other" value="other">`
1. More debatable - when adding a location for a printer, use the browser location api to offer to prefill.

Simple to change. These would be minimal changes, doesn't require any fancy web framework, javascript etc. I realize these are old web pages, would not be a big lift to do. I'd be happy to help do this.

**Comment by michaelrsweet** [comment]
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
