### ISSUE TITLE
Issue related with CUPS back channel USB communication in CUPS version 2.2.12/2.3.1

### ISSUE THREAD

**Issue by skapas** [apple/cups#5879]
We are from Lexmark Linux Driver Development Team. We used to use CUPS backend channel APIs while doing Bi-Di (AutoConfiguration) through our filter in USB mode. The APIs we have been using are,

1) cupsBackChannelRead()
2) cupsSideChannelDoRequest()

The problem recently we faced in Ubuntu 20.04 and Fedora 32/33 where CUPS version is 2.3.1, is our Filter is failing while trying Bi-Di through USB. We checked our log and found the reply getting from "cupsBackChannelRead()" API is incorrect than what expected i.e some unnecessary data coming in front of original data which is also incomplete.

We have analyzed more and the findings are given below,

1) The problem doesn't exist in CUPS 2.2.10 (Debian 10.7).
2) The problem exists in CUPS 2.2.12 (Ubuntu 19.10).

Then we checked the CUPS's release notes (https://www.cups.org/doc/relnotes.html) whether any modification done related with CUPS backend USB communication and we found,

1) Some changes related with the same were made in CUPS 2.2.12.
2) One of the change is,

**The libusb-based USB backend now enforces read limits, improving print speed in many cases (Issue #5583).** 

(https://github.com/apple/cups/commit/35e927f83529cd9b4bc37bcd418c50e307fced35)

3) We downloaded the CUPS's source code from GIT and reverted the particular change (mentioned above in point number 2) which was made in CUPS 2.2.12. Then we built the code locally and install it. We found that our problem got resolved.
<img width="766" alt="Screenshot 2021-01-06 at 5 24 35 PM" src="https://user-images.githubusercontent.com/76997103/103766074-3315d880-5044-11eb-9574-25a865e2454a.png">

Please check the issue.

**Comment by michaelrsweet** [comment]
This is being tracked in the [OpenPrinting CUPS](https://github.com/openprinting/cups) project as [issue #72](https://github.com/OpenPrinting/cups/issues/72).
