### ISSUE TITLE
lp follow lpoption settings but system text editor doesn't.

### ISSUE THREAD

**Issue by atal181** [apple/cups#5881]
I have a problem with printing using CUPS on Ubuntu 20.04. When I issue a printout using `lp -d printername filename` then the system prints using default queue settings that were set using the `lpoptions` command. When I print using the dialog box of any text editor, the system prints, but does not use the settings set by `lpoptions`.

I have made raw the default option using `lpoptions -d <printername> -o raw`. I have checked printer options using `lpoptions -d <printername>`, the raw option is there.

**Comment by michaelrsweet** [comment]
It is unlikely that a GUI application that is sending a PDF file will honor the "-o raw" option. There are some text editors that allow you to set a printing command and just send the text file as-is (letting the print system convert it), but those are a vanishing breed.
