### ISSUE TITLE
ZEBRA Printer with CUPS 2.2.7

### ISSUE THREAD

**Issue by birrageb** [apple/cups#5884]
The Zebra printers are controlled via a SUSE Linux and CUPS print server.
Since the changeover of the CUPS version (1.3.9 to 2.2.7) including Suse Linux from 11.3 to 15.2, we have problems with the Zebra printers, e.g. barcode cannot be scanned, (CPCL), printout shifted (ZPL) ...

Does anyone have experience with such a constellation? 

Thanks & BR 

CPCL:
![image](https://user-images.githubusercontent.com/75418422/105351592-0d183880-5bed-11eb-9c9a-a921ac2d8cb0.png)

ZPL:
![image](https://user-images.githubusercontent.com/75418422/105349595-3daaa300-5bea-11eb-88e0-13f38980f848.png)

**Comment by silindza** [comment]
Is there anything that can be done for cutter options.  I only have a mac and want to be able to set the cutter options so it cuts after 2 labels, not after every label, etc.  The functionality in the driver that you have with windows would be great, but I would settle for the cutter options, if anyone knows how to do that.  Thanks!

**Comment by hoene** [comment]
Yes, I can confirm issues with GX420d. The output is rotated by 90° (not matching the paper anymore) and even if I increase the width of the paper to mitigate this issue, the output is not placed correctly.
The documentation of the ZPL is https://www.zebra.com/content/dam/zebra/manuals/printers/common/programming/zpl-zbi2-pm-en.pdf 
Maybe, somewhere width and height are replaced.

**Comment by michaelrsweet** [comment]
Please report this issue to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project. And please provide sample label print files and print commands to help diagnose the issue.

Antialiasing issues cause most of these scan issues - the barcode lines get fattened up at 203dpi, sometimes eliminating the gap between bars. I have a solution going into LPrint soon (which provides a printer application version of the rastertolabel driver in CUPS) that I can probably backport into the OpenPrinting CUPS driver as well.
