### ISSUE TITLE
Purge Jobs says 'Unknown operation purge-jobs' in Printer Class

### ISSUE THREAD

**Issue by 346L3** [apple/cups#5885]
The exact same bug as #4999 exists in the "class.tmpl" of the localizations & english default.

Please replace "purge" with "cancel" as well, thanks!

_Originally posted by @346L3 in https://github.com/apple/cups/issues/4999#issuecomment-767117730_

**Comment by michaelrsweet** [comment]
Please report this issue to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
