### ISSUE TITLE
Airprint works but gives a warning to check printer

### ISSUE THREAD

**Issue by hyperbart** [apple/cups#5888]
I have an Ubuntu 18.04 installation running CUPSd and added a Samsung ML3750ND with the PPL driver from HP website.
Tried adding the printer both via socket://IP and dnssd://Samsung%20ML-375x%20Series%20(SamsungML3750ND)._pdl-datastream._tcp.local/.

Both printer objects show up in the list and when I send a job to either of them (PDF) the PDF gets printed but my iPhone shows a popup when printing via Airprint.

"Printername @ hostname
Check the printer for errors."

Printing is not really superfast, it's okay but with bigger documents or when you are sending multiple jobs it can take some time before the printers starts to print or pick up a new job while directly printing from Windows to the printer (without using CUPS, since the printer is network attached itself) goes blazing fast.

**Comment by hyperbart** [comment]
Any update or more information needed?

**Comment by michaelrsweet** [comment]
The driver is reporting an error that iOS doesn’t recognize. Run:

    lpstat -lp

to see what “alerts” are being reported.
