### ISSUE TITLE
Cups Webinterface looks different / wrong 

### ISSUE THREAD

**Issue by birrageb** [apple/cups#5890]
Hi together, 

does anyone have a clue why out 2.2.7 CUPS looks like you can see in the attached picture? 

![image](https://user-images.githubusercontent.com/75418422/106613619-af7bd880-656a-11eb-95c1-3a5c9497b2ca.png)

THX

**Comment by michaelrsweet** [comment]
This looks like a missing CSS file - please contact your Linux distribution for assistance.
