### ISSUE TITLE
Canon MP540 - Double Sided Printing Not Available

### ISSUE THREAD

**Issue by jstott1070** [apple/cups#5891]
I have the above printer working great with Cups however i cannot seem to access the option for double sided printing when setting the defaults (or via the print dialog (typically windows)) 

The option is listed in the overall printer info: Defaults:	job-sheets=none, none media=iso_a4_210x297mm sides=one-sided
 Hopefully this is a user error?

Thank you

**Comment by michaelrsweet** [comment]
This might be a limitation in the driver you are using - if it doesn’t report duplex support, then CUPS won’t offer it... Given the age of the printer, I’m guessing you are using the Gutenprint driver which does not support duplex printing, unfortunately...
