### ISSUE TITLE
HP LaserJet 1200 Memory Problem

### ISSUE THREAD

**Issue by syswombat** [apple/cups#5892]
Hello
i have installed Cups in a VM an connected the LaserJet 1200 with USB.
And it works!

But sometimes i got a message it tells the Printer is not having enough memory to print.
should not CUPS handle this and give only as much as the printer is able to print?

Have a nice day
vinc

**Comment by michaelrsweet** [comment]
The typical CUPS printer driver sends bitmap data to an HP printer, which requires a minimum amount of memory (1MB for 300 dpi, 4MB for 600dpi) in the printer. There is nothing CUPS can do to detect the amount of memory in an old printer like this.
