### ISSUE TITLE
Brother MFC-L2550DN printer/scanner is bad detected

### ISSUE THREAD

**Issue by bugith** [apple/cups#5893]
Only with implicitclass:// is detected when driver is not installed (not available in DB)
Beside this, this printers seems out-of-date out-of-the-box as of 2021(only lpd driver also it works with ipps URI):
sudo dpkg -i --force-all dcpl2550dnpdrv-4.0.0-1.i386.deb
...
lpadmin -p DCPL2550DN -E -v dnssd://Brother%20DCP-L2550DN%20series._ipps._tcp.local/?uuid=e3248000-80ce-11db-8000-b42200103cff -P /usr/share/ppd/brother/brother-DCPL2550DN-cups-en.ppd
lpadmin: Printer drivers are deprecated and will stop working in a future version of CUPS.

Once driver is installed the printer shows twice and it is really difficult to remove the ghost one. I got rid of it by "changing" the detected printer to select the supplied ppd (/usr/share/ppd/brother/ or /usr/share/cups/model/) then rename it to the name of the manually installed one then delete this one.

On line 5 below the 4 last bytes are the ones of MAC address.
[snmpwalk.log](https://github.com/apple/cups/files/5937323/snmpwalk.log)
[snmp.log](https://github.com/apple/cups/files/5937324/snmp.log)

**Comment by michaelrsweet** [comment]
As this printer supports AirPrint you can just use the IPP Everywhere (‘-m everywhere’ for lpadmin) driver to print.
