### ISSUE TITLE
cups crashes in 50% printed docs

### ISSUE THREAD

**Issue by xxlsuper** [apple/cups#5895]
Hi 
I am getting this exact crash on macOS Big Sur 11.2.1 (20D74). It happens about 50% of the time when printing via Airprint to a Samsung M283DW printer.

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
dyld3 mode
abort() called
cupsd(66396,0x10de88e00) malloc: *** error for object 0x7fb5c1c13224: pointer being freed was not allocated
[cupsd_2021-02-17-212044_slawa-mbp.crash.zip](https://github.com/apple/cups/files/5997828/cupsd_2021-02-17-212044_slawa-mbp.crash.zip)

**Comment by xxlsuper** [comment]
Some infos

Samsung M283x Series (SEC30CDA737C379):

  Status:	Idle
  Print Server:	Local
  Driver Version:	2.0
  Default:	Yes
  System Printer Sharing:	No
  Shared:	No
  URI:	dnssd://Samsung%20M283x%20Series%20(SEC30CDA737C379)._ipp._tcp.local./?uuid=16a65700-007c-1000-bb49-30cda737c379
  PPD:	Samsung M283x Series-AirPrint
  PPD File Version:	2.0
  PostScript Version:	(3010.000) 0
  CUPS Version:	2.3.4 (cups-494.1)
  Scanning support:	No
  Printer Commands:	none 
  AirPrint Version:	1,2
  URF Version:	1,2
  Added:	Monday, 9 March 2020, 21:59:43 Moscow Standard Time
  CUPS filters:
  image/urf:	processed in printer
  Fax support:	No
  PDEs:

**Comment by michaelrsweet** [comment]
Fix is here: <https://github.com/OpenPrinting/cups/pull/43>

Working to get this and other fixes into Apple CUPS.

**Comment by michaelrsweet** [comment]
Tracking in the bug-fix-rollup-1 branch.
