### ISSUE TITLE
Mixed character encoding in lpstat output

### ISSUE THREAD

**Issue by frifl** [apple/cups#5896]
I run CUPS 2.3.1 on Ubuntu 20.04 and I get mixed character encoding in the output from lpstat. The system locale is set to zh_CN.GB18030. The message is UTF-8 and the timestamp is GB18030.

> $  lpstat -a
printer 鑷粠 2021年02月04日 星期四 07时51分54秒 寮�濮嬫帴鍙楄姹�

The timestamp is correct but there are replacement characters in the message part which indicate bad encoding. I checked that the message part was indeed UTF-8 by manually decoding the bytes.

This is my locale setting: 
> $ locale
LANG=zh_CN.GB18030
LANGUAGE=
LC_CTYPE="zh_CN.GB18030"
LC_NUMERIC="zh_CN.GB18030"
LC_TIME="zh_CN.GB18030"
LC_COLLATE="zh_CN.GB18030"
LC_MONETARY="zh_CN.GB18030"
LC_MESSAGES="zh_CN.GB18030"
LC_PAPER="zh_CN.GB18030"
LC_NAME="zh_CN.GB18030"
LC_ADDRESS="zh_CN.GB18030"
LC_TELEPHONE="zh_CN.GB18030"
LC_MEASUREMENT="zh_CN.GB18030"
LC_IDENTIFICATION="zh_CN.GB18030"
LC_ALL=

This is the locales I have on my system:
> $ locale -a
C
C.UTF-8
POSIX
zh_CN.gb18030

**Comment by michaelrsweet** [comment]
This sounds like a failure in the iconv software CUPS uses to transcode to the locale's charset. Please contact the [OpenPrinting CUPS](https://github.com/openprinting/cups) project for assistance.
