### ISSUE TITLE
Citizen CL-S521 thermal printer not printing

### ISSUE THREAD

**Issue by spbe** [apple/cups#5897]
Followed Citizen set up guide for CUPS, however, cannot get it to print. Prints fine from partner's PC using Windows driver. Condition light flashes red when the print job is sent.

**Comment by michaelrsweet** [comment]
Please contact the [OpenPrinting CUPS](https://github.com/openprinting/cups) project for assistance. The Zebra ZPL driver *should* work, but hard to say without knowing more about how you have the printer connected, etc. This isn't a printer I've personally tested...
