### ISSUE TITLE
HP LJ2015 Warning light blinking when printing from CUPS and no printout comes out

### ISSUE THREAD

**Issue by RS-GHub** [apple/cups#5898]
Hi All,
First post here - so apologies if stupid..

I have CUPS installed on Raspberry Pi 4 and set my LAN connected HP LJ2015N printer as default printer.
Any time I print to that printer (either test page from CUPS or on my iPhone) the amber warning light on the printer starts blinking and no printout comes out.

But if I print a printer settings page directly on the printer - printout comes correctly - so printer works.

Pity, because the same set up worked before on my previous installation on different IP address range.
Now I changed the IP relocation on my network, and I removed previous printer and reinstalled the HP printer with the current IP address, it started those problems.

Any ideas?
Thanks in advance!

**Comment by michaelrsweet** [comment]
Please contact the [OpenPrinting CUPS](https://github.com/openprinting/cups) project for assistance. This sounds like either a driver or device URI issue.
