### ISSUE TITLE
lpadmin and foomatic-rip not found after installing CUPS 2.2.1 on AIX 7.1

### ISSUE THREAD

**Issue by yuanqiong-ricoh** [apple/cups#5899]
Since we want to implement IPPS printing on the AIX OS, we want to build a CUPS environment on the AIX OS, using the yum tool, CUPS 2.2.1 was installed, but the following problems occurred:
1. When using the lpadmin command, the following error occurred
===================================
//# lpadmin 
//ksh: lpadmin:  not found. 
//# whereis lpadmin                                                                                                       
//lpadmin:  
//#        
===================================     

2. The following error appears after installing the PPD driver and Print test page:
"File "/opt/freeware/lib/cups/filter/foomatic-rip" not available: No such file or directory"

We checked the installation files, lpadmin and foomatic-rip did not seem to be installed.

### What we want to know:
1.Which CUPS package does lpadmin exist in, and how do we solve this problem?
Below are the package installed
cups.ppc                                                      2.2.1-1                                         @perzl.org
cups-client.ppc                                               2.2.1-1                                         @perzl.org
cups-devel.ppc                                                2.2.1-1                                         @perzl.org
cups-ipptool.ppc                                              2.2.1-1                                         @perzl.org
cups-libs.ppc                                                 2.2.1-1                                         @perzl.org
cups-lpd.ppc                                                  2.2.1-1                                         @perzl.org

2.foomatic-rip seems to exist in the CUPS-filter package. Which is the CUPS-filter package corresponding to CUPS2.2.1 and where can we download it?

**Comment by michaelrsweet** [comment]
Please report this to the [OpenPrinting CUPS](https://github.com/openprinting/cups) project.
