### ISSUE TITLE
problem cups on openwrt mt300nv2

### ISSUE THREAD

**Issue by jejebillo** [apple/cups#5901]
hello, i'm Billotet jeremy.
i have a glinet mt300nv2 with openwrt and luci installed. I did an extroot because 16 mb only. I wanted to install cups, but I can’t access the interface. instead it marks me: dropbear ssh2.0 and code. my hp photosmart c4600 series is detected when i launch backend usb.i think cups is blocked by dropbear. i want use also scanner, how to install his? if you want help me thanks ?

**Comment by michaelrsweet** [comment]
Sorry can't help you.
