### ISSUE TITLE
Clients get wrong parameters (resolution)

### ISSUE THREAD

**Issue by xxxcrow** [apple/cups#5903]
Hi, everyone 👋
I'm trying to get CUPS and Raspberry pi 0 work with HP LaserJet p1005
The driver seems to work fine if i set the resolution `1200*600` (which is set as default)
If i set `600*600` it won't work
But when clients get the printer installed, they set "maximum resolution" to 600... It's strange... And it can't print too...
So, if i remove `600*600` option from PPD.. am.. so.. clients will set "maximum resolution" to a very low number (around 10-20)
What is going on? How to fix this? 😓

**Comment by michaelrsweet** [comment]
It's a little hard to determine where the problem may lay, but CUPS doesn't provide this driver so there isn't much we can do to help you here...

**Comment by xxxcrow** [comment]
Hey 🙁 closed the issue? 
Third party? Why are you so sure?

**Comment by michaelrsweet** [comment]
@xxxcrow You are using a driver from a third party, that driver is responsible for listing the supported resolutions, and one of the supported resolutions doesn’t work. What do you expect CUPS to do in this situation?

**Comment by xxxcrow** [comment]
@michaelrsweet the problem is not in 600*600, i don't want to use 600*600
I want clients to print 1200*600, but when the printer is installed it has only 600*600 option, but not 1200*600

**Comment by michaelrsweet** [comment]
@xxxcrow Again, ALL of that information comes from the driver's PPD file. CUPS just uses what the driver provides.

You say in your original description that you can set 1200x600dpi, but the clients are sending 600dpi (another resolution reported by the driver) and the driver or printer is not happy printing at 600dpi. That tells me the core problem is with the driver and NOT with CUPS.
