### ISSUE TITLE
filter/rastertopwg: fails with Bad Margin without reason

### ISSUE THREAD

**Issue by ComputerDoktor** [apple/cups#5904]
rastertopwg fails for Borderless-A4.pdf with
Bad bottom/left/top margin on page 1.
%%BoundingBox: 0 0 596 842
%%HiResBoundingBox: 0.000000 0.000000 595.313982 841.913974

to reproduce, 
create a printer "print to file"  file:/tmp/printdata.prn with the attached ppd file,
enable debug: cupsctl --debug-logging
"print" the attached pdf file and check error_log for "Bad bottom/left/top margin"
lpr -PBrother_MFC_J4625DW -oprint-quality=5 -omedia=A4.Borderless Borderless-A4.pdf

Brother_MFC_J4625DW.ppd was created by the command
driverless cat ipp://10.0.0.2/ipp > Brother_MFC_J4625DW.ppd

Workaround: round up page height for A4.borderless from 841.889763779528 to 842 in ppd file.
entries *PageSize *PageRegion *ImageableArea *PaperDimension 

versions
cups           	2.3.1-9ubuntu1.1
cups-core-drivers 2.3.1-9ubuntu1.1
cups-filters   1.27.4-1     
Linux 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
[Borderless-A4.pdf](https://github.com/apple/cups/files/6146687/Borderless-A4.pdf)

[Brother_MFC_J4625DW.zip](https://github.com/apple/cups/files/6146696/Brother_MFC_J4625DW.zip)

**Comment by jschwender** [comment]
driverless is a tool from cups-filters, not cups. You may try newer ubuntu version like:
 https://launchpad.net/~jschwender/+archive/ubuntu/cups

**Comment by ComputerDoktor** [comment]
the issue is about a bug in rastertopwg.c which fails with the attached ppd and pdf.
driverless was used to generate the ppd file, no issue with driverless.

**Comment by michaelrsweet** [comment]
OK, the issue is *not* in rastertopwg, the issue is in the program that is generating the PWG raster data (one of the cups-filters pdftoraster producers) and (probably) not filling in the right values in the page header. The rastertopwg filter is saying that the bounding box specified in the raster data is bad so it doesn't know how to pad the CUPS raster data to yield the PWG raster or Apple raster data (which has to be full-bleed).

So please report this to the [cups-filters](https://github.com/openprinting/cups-filter) project - ideally they should just produce the correct format directly rather than adding another (expensive) filter step.

**Comment by ComputerDoktor** [comment]
Sorry, I do not agree. IMO the bug is around line 124 in rastertopwg.c
rastertopwg.c:124
    page_height = (unsigned)(inheader.cupsPageSize[1] * inheader.HWResolution[1] / 72.0);
    page_top    = page_height - page_bottom - inheader.cupsHeight;
    page_bottom = (unsigned)(inheader.cupsImagingBBox[1] * inheader.HWResolution[1] / 72.0);

    page_height = (unsigned)(841.88976 * 300 / 72.0);
    page_bottom = (unsigned)(0 * 300 / 72.0);
    page_top    = page_height - page_bottom - 3508;
right side 3507 - 0 - 3508 yields minus 1
unsigned page_top becomes 4294967295
probably page_height should be rounded and not truncated.
This happens only for pages with very small or zero margins, the majority of pages has considerable margins and are not affected. 
As I wrote, I have found a workaround: manually round page heights in ppd file, replace 841.889763779528 by 842.
I have attached an error log of print to file.
[error_log.txt](https://github.com/apple/cups/files/6156913/error_log.txt)

**Comment by ComputerDoktor** [comment]
Sorry, I am still convinced that the bug is in rastertopwg.
I have attached the files
rastertopwg.sh
Brother_MFC_J4625DW.ppd
in.prn
out.prn

rastertopwg.sh feeds the Cups Raster file in.prn to rastertopwg
and triggers the error
ERROR: Unsupported raster data.
DEBUG: Bad bottom/left/top margin on page 1.

I think the bug is around line 124 in rastertopwg.c
rastertopwg.c:124
page_height = (unsigned)(inheader.cupsPageSize[1] * inheader.HWResolution[1] / 72.0);
page_top = page_height - page_bottom - inheader.cupsHeight;
page_bottom = (unsigned)(inheader.cupsImagingBBox[1] * inheader.HWResolution[1] / 72.0);

page_height = (unsigned)(841.88976 * 300 / 72.0);
page_bottom = (unsigned)(0 * 300 / 72.0);
page_top    = page_height - page_bottom - 3508;
right side 3507 - 0 - 3508 yields minus 1
unsigned page_top becomes 4294967295
probably page_height should be rounded and not truncated.
This happens only for pages with very small or zero margins, the majority of pages has considerable margins and are not affected.
[rastertopwg-testcase.zip](https://github.com/apple/cups/files/6157619/rastertopwg-testcase.zip)

**Comment by ComputerDoktor** [comment]
@michaelrsweet 
please could you try to reproduce my rastertopwg-testcase.zip and possibly reopen the issue?

**Comment by jschwender** [comment]
if i run that the output is:
-------------------------------------
js@jupiter:/tmp/test$ ./rastertopwg.sh
DEBUG: Duplex = 0
DEBUG: HWResolution = [ 300 300 ]
DEBUG: ImagingBoundingBox = [ 0 0 595 842 ]
DEBUG: Margins = [ 0 0 ]
DEBUG: ManualFeed = 0
DEBUG: MediaPosition = 1
DEBUG: NumCopies = 1
DEBUG: Orientation = 0
DEBUG: PageSize = [ 595 842 ]
DEBUG: cupsWidth = 2480
DEBUG: cupsHeight = 3508
DEBUG: cupsMediaType = 0
DEBUG: cupsBitsPerColor = 8
DEBUG: cupsBitsPerPixel = 24
DEBUG: cupsBytesPerLine = 7440
DEBUG: cupsColorOrder = 0
DEBUG: cupsColorSpace = 19
DEBUG: cupsCompression = 0
PAGE: 1 1
DEBUG: In pixels: Width: 2480  Height: 3508  Left: 0  Right:  0  Top: 0  Bottom: 0
RC=0
---------------------
I have installed: cups-filters  1.28.7-1 on ubuntu 20.10, cups 2.3.3op
If i look to in and out file with rasterview, it looks equal.

**Comment by michaelrsweet** [comment]
Will look at again, but understand that a) this filter isn't used on macOS and b) I'm not going to add workarounds for broken filters upstream of rastertopwg.

Also, OpenPrinting CUPS is where any changes will happen.

**Comment by ComputerDoktor** [comment]
@jschwender 
strange. I get the error with
WSL 1
Ubuntu "20.04.2 LTS (Focal Fossa)"
rastertopwg is part of cups? How can I tell if Ubuntu is built with Apple cups or with OpenPrinting CUPS?
dpkg -S rastertopwg
cups: /usr/lib/cups/filter/rastertopwg
dpkg -l cups
ii  cups           2.3.1-9ubuntu1.1 amd64        Common UNIX Printing System(tm) - PPD/driver support, web interface

**Comment by michaelrsweet** [comment]
@ComputerDoktor That version of Ubuntu has Apple's CUPS 2.3.1 source code plus a bunch of patches. OpenPrinting CUPS versions are currently "2.3.3op1" and "2.3.3op2", with the next release in development just "2.4.0".

**Comment by ComputerDoktor** [comment]
Thanks for the clarification. 
Apparently the problem is fixed in OpenPrinting CUPS 2.3.3op according to jschwender.
https://github.com/OpenPrinting/cups/blob/master/filter/rastertopwg.c has modifications dealing with 
"round page_height"  != "truncate page_height"
