### ISSUE TITLE
Epson TM81 could not print text in right side

### ISSUE THREAD

**Issue by TungLe93** [apple/cups#5906]
Hi everyone,

I'm using CUPS as print server and i have 1 Epson TM81 but when printing the receipt some of text/number in the right side were missed (look like oversize the paper size). I've tried to change another paper size but not worked.
Anyone here had faced same problem or can help me to fix it so please leave your comment here.

Thanks everyone!

**Comment by michaelrsweet** [comment]
@TungLe93 It would be useful to know:

1. What version of CUPS you are using
2. What driver you are using for this printer
3. What kind of data/file you are sending to CUPS when printing the receipt

**Comment by TungLe93** [comment]
> @TungLe93 It would be useful to know:
> 
> 1. What version of CUPS you are using
> 2. What driver you are using for this printer
> 3. What kind of data/file you are sending to CUPS when printing the receipt

Hi bro, I would like to reply as below, sorry for late: 

> 1. What version of CUPS you are using
 CUPS 1.7.2

> 2. What driver you are using for this printer
TM/BA Series Printer Driver for Linux Ver.2.0.3.0
Download link: https://download.epson-biz.com/modules/pos/index.php?page=single_soft&cid=5012&pcat=3&pid=3260

> 3. What kind of data/file you are sending to CUPS when printing the receipt
I dont know what you means, the receipt was printed via POS app (our vendor give this app to us)

**Comment by michaelrsweet** [comment]
@TungLe93 For my third question, I wondered whether the POS app was sending printer-ready data or was generating PostScript or PDF for the CUPS filters to convert? If it sends printer-ready data then there is nothing we can do to help you here... :/

As the linked driver does not include source code, I'm afraid there isn't much I can suggest... Have you tried getting help from your POS vendor?
