### ISSUE TITLE
Samsung ML-1640 not print

### ISSUE THREAD

**Issue by Tuxino88** [apple/cups#5909]
with cups 2.3.3op2 the printer not print and give this:
Fedora 33

![photo_2021-03-28_17-57-17](https://user-images.githubusercontent.com/75674245/112758565-633f9880-8fef-11eb-9c8d-d22d694063d2.jpg)

**Comment by michaelrsweet** [comment]
This looks like <https://github.com/OpenPrinting/cups/pull/160>
