### ISSUE TITLE
possiblity to set requesting-user-name

### ISSUE THREAD

**Issue by addap** [apple/cups#5912]
Hi,
I was wondering if it is possible to set the requesting-user-name property on a per-printer basis. We have created a cups shared printer that accepts unauthenticated print jobs and want to send print jobs via ipp from client computers. 
These print jobs are later sorted according the requesting-user-name that is sent along but at the moment we are not able to set it to a custom value <printeruser>. It is always the name of the system user that is logged in on the client computer.

What we have tried
- adding `Option requesting-user-name <printeruser>` to the printer configuration in /etc/printers.conf on the client.
- adding `Option job-originating-user-name <printeruser>` to the printer configuration in /etc/printers.conf on the client.
- adding username and a random password to the device uri on the client like `ipp://<printeruser>:dummy@<ip>:631/printers/<printername>`
Which are recommended when searching for similar issues.

In all cases the ipp messages for a print job have the requesting-user-name attribute to the logged in linux user.
We know it works by issuing `lp -U <printeruser> ...` from the command line and also when we set the CUPS_USER environment variable. But the first one is impractical for our users and the second one seems to apply to all printers.
Is it at all possible to customize this value per printer? From reading the documentation the attribute should be set correctly if we enabled authentication which we would rather not do at this time.

**Comment by michaelrsweet** [comment]
The only way to use a different remote username is to enable authentication. We have no plans of supporting alternate requesting-user-name values.

**Comment by Reylak** [comment]
I'm hitting the same issue here: the Papercut printing system for organizations, uses IPPS URIs and looks for `requesting-user-name` to authenticate, ignoring the username embedded in the URI (although it does use it, and the password, at some point). So from our point of view, the ability to set `requesting-user-name` per printer is essential.

This is not a problem for desktop computers, but for laptops, it is.
