### ISSUE TITLE
in _httpUpdate , after httpAddrClose(http->fd), not reset http->fd . or not need?

### ISSUE THREAD

**Issue by newsky123456** [apple/cups#5915]
in function _httpUpdate :
if (http->status == HTTP_STATUS_SWITCHING_PROTOCOLS && !http->tls)
{
if (_httpTLSStart(http) != 0)
{
httpAddrClose(NULL, http->fd);

*status = http->status = HTTP_STATUS_ERROR;
return (0);
  }

  *status = HTTP_STATUS_CONTINUE;
  return (0);
}
----after httpAddrClose ,does it need to reset http-fd = -1?

**Comment by michaelrsweet** [comment]
Apple CUPS:

[bug-fix-rollup-1 1f3d159e4] Fix one other spot where http->fd isn't reset to -1 (Issue #5915)

OpenPrinting CUPS:

[master 0c92c5feb] Fix one other spot where http->fd isn't reset to -1 (Issue #5915)
