### ISSUE TITLE
gnutls/gnutls.h: No such file or directory while installing latest cups 2.3.3

### ISSUE THREAD

**Issue by deltasata** [apple/cups#5920]
I am trying to install the latest version of cups 2.3.3, I was following https://fossies.org/linux/cups/INSTALL.md

After the `make` command, I got the foll error.
```
In file included from cups-private.h:21:0,
                 from auth.c:17:
http-private.h:70:14: fatal error: gnutls/gnutls.h: No such file or directory
 #    include <gnutls/gnutls.h>
              ^~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [../Makedefs:271: auth.o] Error 1
```
Note that I followed the step

```
sudo apt-get install autoconf build-essential libavahi-client-dev \
     libgnutls28-dev libkrb5-dev libnss-mdns libpam-dev \
     libsystemd-dev libusb-1.0-0-dev zlib1g-dev
```
before going to `make`

Most frustratingly, `/usr/include/gnutls/gnutls.h` is there but still I am getting this error. 
Tried on a different computer with ubuntu 20.04 and got the same error despite having `/usr/include/gnutls/gnutls.h`.

**Comment by michaelrsweet** [comment]
@deltasata I'm not sure what is going on. Have you tried building the current OpenPrinting CUPS release(2.3.3op2) instead? It is possible there is an issue with the configure script, or maybe you are cross-compiling so /usr/include isn't in the list of include directories?
