### ISSUE TITLE
Unknown directive Encryption on line XXX of /etc/cups/cupsd.conf.

### ISSUE THREAD

**Issue by michelsaumon** [apple/cups#5921]
Hello,

Tested with cups 2.3.3 & cups 2.2.6, I have this message when cups is starting.
>E [10/May/2021:17:37:19 +0200] Unknown directive Encryption on line 5 of /etc/cups/cupsd.conf.

Here is my conf :

>LogLevel debug
>PageLogFormat
>\# Force https
>DefaultEncryption Required
>Encryption Required
>Port 631
>ServerAlias *
>Browsing On
>BrowseLocalProtocols none
>DefaultAuthType Basic
>WebInterface Yes
>ErrorPolicy retry-current-job

**Comment by michaelrsweet** [comment]
@michelsaumon OK, so the "Encryption" directive can only appear inside a "Location" section, e.g.:

```
<Location />
Encryption Required
</Location>
```

You can find out more by looking at <https://openprinting.github.io/cups/doc/man-cupsd.conf.html>.
