### ISSUE TITLE
SystemGroup directive missing from cupsd.conf

### ISSUE THREAD

**Issue by Penguin-fach** [apple/cups#5922]
[https://https://wiki.ubuntu.com/Security/Privileges](url) indicates CUPS user permissions assigned by a SystemGroup directive within cupsd.conf. I cannot find any reference to SystemGroup within [https://www.cups.org/doc/man-cupsd.conf.html](url) and SystemGroup is absent from cupsd.conf as deployed within Ubuntu 20.04 LTS. Local users are added to lpadmin but not clear how this is passed (if at all) to CUPS without SystemGroup directive unless CUPS has been changed and Ubuntu documentation is out of date.

I have encountered problems with printing from a networked laptop to a networked desktop PC with shared local USB printer. Sharing is correctly configured and firewalls passing at both ends. Local printing on the desktop PC is working (after removal of conflicting ippusbxd). Printer is recognised by remote laptop and drivers install. Error reported as 'Unable to open print file: permission denied', when trying to print test page.

**Comment by michaelrsweet** [comment]
@Penguin-fach The `SystemGroup` directive moved to the `cups-files.conf` file several years ago for security reasons.
