### ISSUE TITLE
Inability to set printer attribute job-password

### ISSUE THREAD

**Issue by gitneo** [apple/cups#5926]
Hi,
I'm working on a printer service and i'm trying to access a printers' (Canon) SECURE PRINT function by setting these attributes
` attributeMap["job-attributes"] = "job-password:octetString:123#job-password-encryption:keyword:none";`

I get this error at CUPS admin (ver 2.2.12) when i try to print
`"src = job.c, line = 1385, log = none of secured print password and username"`

When i check **/var/spool/cups** i can see all the attributes set except from job-password attribute hence the error.

Please help.

Error at CUPS
![image](https://user-images.githubusercontent.com/4016666/121068642-7081bc00-c7c4-11eb-9c22-4d02a5f068f4.png)

**/var/spool/cups**
![image](https://user-images.githubusercontent.com/4016666/121068519-49c38580-c7c4-11eb-9178-285a4fc351de.png)

**Comment by michaelrsweet** [comment]
@gitneo How are you specifying the job-password value on the CUPS client?

What version of CUPS are you using?

What operating system is the client using?

**Comment by gitneo** [comment]
Hi,
I'm using 

**CUPS 2.2.12.**


**The client operating system**
      NAME="Oracle Linux Server"
      VERSION="7.5"


**job-password specification on client**,
      job-password:octetString:12345



The complete line of code includes the job-password-encryption and requesting-user-name.
```
printAttributes["job-attributes"] = 
      "job-password:octetString:12345#job-password-encryption:keyword:none#requesting-user-name:name:GITNEO";
```

**Comment by michaelrsweet** [comment]
@gitneo I'm not sure how you are submitting jobs, as the code you are including is NOT the CUPS API.

But I can guess from the context that you are passing job-password and job-password-encryption in the job-attributes group, but they MUST be provided in the operation attributes group. They are security attributes and not part of the job ticket...
