### ISSUE TITLE
Lable orientation fault

### ISSUE THREAD

**Issue by fg-ULMA** [apple/cups#5928]
The Label is printed as if the labels where in Portrait format in the Printer but they are in landscape format.
This problem occurs regardless of where is printed except when printing from Chromium, then the label is printed correctly.

The label format is 2.25 to 1.25. The format is natively supported by the printer driver (Zebra epl2). The problem occurs regardless of whether the format is set to 2.25 x 1.25 or 1.25 x 2.25.

Portrait print:
![Portrait print](https://user-images.githubusercontent.com/85786026/121771882-65d37800-cb72-11eb-9ca2-65ed55cdcfb5.jpg)

Landscape print:
![Landscape print](https://user-images.githubusercontent.com/85786026/121771883-6704a500-cb72-11eb-996a-85e6741196df.jpg)

Print from Chromium (expected output):
![Expected output](https://user-images.githubusercontent.com/85786026/121771879-62d88780-cb72-11eb-9884-0a5e56ca8365.jpg)

**Comment by michaelrsweet** [comment]
@fg-ULMA What driver? What operating system?

**Comment by fg-ULMA** [comment]
The driver is the Zebra EPL2 driver. The OS is Ubuntu 20.04.2 LTS.

**Comment by fg-ULMA** [comment]
Because i forgot that too here are the cups spool and log data of an portrait and an landscape print job.
[cups-log-data.zip](https://github.com/apple/cups/files/6643555/cups-log-data.zip)

**Comment by michaelrsweet** [comment]
@fg-ULMA The spooled files show that Cairo is messing up the portrait label. More than likely something in the application's printing code is assuming that all paper sizes are portrait, then generating a landscape PDF... The landscape PDF is portrait (!)

Oh, and the job control files show the print options being for a printer using a Xerox PPD and not the Zebra printer...

**Comment by fg-ULMA** [comment]
@michaelrsweet Ok, just don't understand why firefox is doing this like that because the printer is set up as Zebra EPL2 Printer. And firefox is simply installed and not modified or something else.
Interestingly after i set up firefox to open pdf in system-default application and then print the file from there the job is printed correctly. 

For completeness, here are the log and spool files of an print job from chromium:
[chromium-cups-log.zip](https://github.com/apple/cups/files/6679451/chromium-cups-log.zip)

And here are the log and spool files of an print job from firefox via open pdf on system-default application:
[firefox-sysdefault-app-cups-log.zip](https://github.com/apple/cups/files/6679495/firefox-sysdefault-app-cups-log.zip)
