### ISSUE TITLE
Open browser after printing is done

### ISSUE THREAD

**Issue by hasgardee** [apple/cups#5930]
I know this is not within the scope of this project. I actually want to open a url in the browser after printing is done. I tried system("open URL") and exec functions. Those functions run without error. But the browser is not opening.I tried the same system() from a single .c file and compiled with clang and gcc.it works(./a.out). But it did not work inside my printer module. Is it because of the printer module having limited permissions? Is there any way to do that?

I used this project to create printer module(convert doc to pdf and save): https://github.com/rodyager/RWTS-PDFwriter
OS: Mac BigSur

**Comment by debiantriage** [comment]
Maybe this helps:

https://wiki.debian.org/CUPSTea4CUPS

**Comment by michaelrsweet** [comment]
@hasgardee This isn't something you can do generally from a backend. The IPP backend uses an XPC service (running as the logged-in user) to "trampoline" into the user session to get Kerberos credentials, and I suspect you could do something similar to open a web page, but this isn't something I'd normally recommend doing...
