### ISSUE TITLE
Cups randomly re-print previously printed jobs

### ISSUE THREAD

**Issue by tchartron** [apple/cups#5931]
Hi,

I have a cups server (version 2.2.10-6) installed on a debian NUC.

The cups server has a cups class which has 4 physical label printers (INTERMEC printers)

I use a bash script to request print jobs to the class with the `lp` command : 
```bash
lp -d MyClass -o fit-to-page "$FILENAME"
```

It works great but sometimes an old file is re-printed without it being requested.
The file beeing printed again has usually already been printed 1 or 2 months ago ...

I checked syslogs, `/var/spool/cups` to check jobs file, tried to restart cupsd every weeks, added printed files backup with a `mv --backup=numbered $FILENAME $BACKUP_DIR` command to keep an history of the printed files but nothing shows the old job beeing requested again and still it gets printed.

I'm running out of ideas on this issue and i would really appreciate any help on this if anyone has already experienced this kind of problem.

Thanks a lot.

**Comment by michaelrsweet** [comment]
@tchartron I've not seen this before, but I'd check for either old print filter processes or labels that might be still in memory on those printers.

**Comment by tchartron** [comment]
Hi, @michaelrsweet thanks for your help, i don't understand what you mean by old print filter processes, i checked the filter beeing used for a random label and it says `gziptoany`, how could i look for old processes ?

I don't think printers memory are part of the problem as we were using these same printers before migrating to cups without any problem of that kind ...

**Comment by michaelrsweet** [comment]
@tchartron The "ps" command can be used to list running processes, and you can look for old gziptoany or the corresponding backend to see if they are still running.

If you are just sending raw data to the printers, I agree that stale labels in memory should not be an issue. For labels printed using the rastertolabel driver, it is possible for the label bitmap to stay resident on the printer (but should just be the last printed bitmap, not the Nth to the last bitmap...)

**Comment by tchartron** [comment]
@michaelrsweet ok i did not understand it that way, thanks i'll check for old processes but i'm not very confident about that, thanks for your help i'll post any update on this !

**Comment by michaelrsweet** [comment]
OK, closing for now but let us know if you see this again.
