### ISSUE TITLE
Version problem...

### ISSUE THREAD

**Issue by Neustradamus** [apple/cups#5934]
@michaelrsweet: I see some problems:

The last build is 2.3.3 here:
- https://github.com/apple/cups/releases

And the README.md says: ```README - CUPS v2.3.5 - 2021-04-26```
- https://github.com/apple/cups/blob/master/README.md

And I see:
```
Copyright © 2007-2021 by Apple Inc. Copyright © 1997-2007 by Easy Software Products.
```

-----------

The last build of OpenPrinting is 2.3.3op2:
- https://github.com/OpenPrinting/cups/releases

And the README.md says: ```OpenPrinting CUPS v2.4.0```
- https://github.com/OpenPrinting/cups/blob/master/README.md

And I see:
```
Copyright © 2020-2021 by OpenPrinting
Copyright © 2007-2020 by Apple Inc.
Copyright © 1997-2007 by Easy Software Products.
```

Can you solve it?

**Comment by michaelrsweet** [comment]
@Neustradamus The "master" branch of the two CUPS repositories represents the current "bleeding edge" development of the corresponding projects. Once released, there are tags corresponding to each release, and branches for stable versions once development on the next feature release begins (for example, there will be a v2.4.x branch on the OpenPrinting CUPS repository once 2.4.0 is released, and master will be CUPS 3.0)

**Comment by Neustradamus** [comment]
@michaelrsweet: No, it is not good.

Before an official release build, it is needed to create a commit for the new build.

You can read here:
- https://semver.org/

And:
- Master branch: a.b.c-dev
- Pre-release versions: a.b.c-alpha1 -> a.b.c-beta1 -> a.b.c-rc1
- Final stable build -> a.b.c

**Comment by michaelrsweet** [comment]
We do not follow those guidelines.
