### ISSUE TITLE
CUP

### ISSUE THREAD

**Issue by zjorz** [apple/cups#5935]
running CUPS on raspberry pi. Installed printer.
Printing test page succeeds
Printing from iphone (iOS) the airprint printer is seen and therefore chosen. When actually trying to print I always get the error: 

printer @ server - the printer is offline

have been looking at this for days, tried to search for issues with possible solutions . Nothing worked. Problem still exists.
Please help!

thanks

**Comment by michaelrsweet** [comment]
@zjorz What version of CUPS?

What printer?

What driver?

How have you configured CUPS to be accessible from iOS?

**Comment by zjorz** [comment]
Hello @michaelrsweet 

CUPS version: CUPS 2.2.10
Printer: Xerox WorkCentre 4250
Driver: Xerox WorkCentre 4250 (grayscale, 2-sided printing)

Do not understand the Q "How have you configured CUPS to be accessible from iOS?". Can you please elaborate?

**Comment by michaelrsweet** [comment]
@zjorz CUPS does not support AirPrint and is not compatible with iOS clients without extra configuration.

**Comment by zjorz** [comment]
> @zjorz CUPS does not support AirPrint and is not compatible with iOS clients without extra configuration.

could you please say what that extra configuration is then?

**Comment by michaelrsweet** [comment]
@zjorz I don't know what configuration needs to be done for CUPS 2.2.10, as CUPS itself doesn't have all of the necessary pieces to make this work - you might try contacting the Raspbian or Debian printing folks for help there.

[OpenPrinting CUPS](https://github.com/OpenPrinting/cups) is in the process of developing the 2.4.0 release of CUPS that *does* include all of the necessary pieces to work with iOS clients. *That software has not yet been released* but is the only "supported" path going forward on Linux.
