### ISSUE TITLE
How can I enable SSL/TLS on the CUPS v2.3.3?

### ISSUE THREAD

**Issue by ZJahon** [apple/cups#5936]
My android cannot allowed Clear text traffic.It alert that Clear text traffic is no longer allowed in Android 9.0. Please enable SSL/TLS on the CUPS server/printer.

**Comment by michaelrsweet** [comment]
@ZJahon TLS/SSL support is enabled by default. That said, CUPS is not a Mopria-certified server so I have no idea whether it should work out of the box with Android.
