### ISSUE TITLE
Many printers can’t be bought

### ISSUE THREAD

**Issue by craigtao** [apple/cups#5937]
You can run the lpinfo -m command to list all of the available drivers

Many printers can’t be bought,   how to solve this problem?  

thanks  everyone

**Comment by michaelrsweet** [comment]
@craigtao I don't understand your question.

**Comment by craigtao** [comment]
sorry.
I re-describe my question: 
I run lpinfo -m command to list all of the available drivers.
The printer models corresponding to these valid drivers are no longer available for purchase

Is it because I didn't use cups correctly?

My purpose is: buy a new printer, how to add a printer in cups service


thanks @michaelrsweet

**Comment by craigtao** [comment]
I use raspberry Pi 3B

**Comment by michaelrsweet** [comment]
@craigtao Any printer that lists AirPrint, IPP Everywhere, or Mopria compatibility will work out of the box with CUPS and the IPP Everywhere driver ("everywhere").

**Comment by craigtao** [comment]
Printing failed, prompting that there is no corresponding PPD file

**Comment by michaelrsweet** [comment]
@craigtao We can't provide a lot of help for Raspbian's version of CUPS on the Apple CUPS project. More than likely there is a problem with the version of CUPS bundled with Raspbian, which includes a LOT of code from the OpenPrinting folks (who may be able to help further, particularly @tillkamppeter)

**Comment by craigtao** [comment]
@michaelrsweet  thank you so much.

I tried many more

After installing hplip and hplip-gui on the Raspberry Pi, it can support more printers
