### ISSUE TITLE
Job  stopped  "Filter failed"

### ISSUE THREAD

**Issue by cinghialino** [apple/cups#5941]
Hello, 

I have installed CUPS on a Raspberry pi 3
I made sure that everything was upgraded and updated before posting here.
The same installation of CUPS was working before with a different printer that unfortunately I no longer have.

Since then have bought a new printer and while I can install it and everything seems to work as it should, 
I am experiencing a problem where every job I send to my printer fails with the "Filter failed" error.

I logged onto the terminal and here is the `error_log`:

```
RPi-1:/var/log/cups $ tail error_log
D [07/Aug/2021:16:29:07 -0400] [Job 30] Current allocation mode is local
D [07/Aug/2021:16:29:07 -0400] [Job 30] Last OS error: Broken pipe
D [07/Aug/2021:16:29:07 -0400] [Job 30] GPL Ghostscript 9.26: Unrecoverable error, exit code 1
D [07/Aug/2021:16:29:07 -0400] [Job 30] Rendering completed
D [07/Aug/2021:16:29:07 -0400] [Job 30] PID 13468 (/usr/lib/cups/filter/gstoraster) stopped with status 1.
D [07/Aug/2021:16:29:07 -0400] [Job 30] Hint: Try setting the LogLevel to "debug" to find out more.
D [07/Aug/2021:16:29:07 -0400] [Job 30] End of messages
D [07/Aug/2021:16:29:07 -0400] [Job 30] printer-state=3(idle)
D [07/Aug/2021:16:29:07 -0400] [Job 30] printer-state-message="Rendering completed"
D [07/Aug/2021:16:29:07 -0400] [Job 30] printer-state-reasons=none
```

can anyone help me on this? I am quite inexperienced, please bare with me, I may need an extra help.

Best

**Comment by michaelrsweet** [comment]
This error tells me you are running into a GhostScript issue:

```
D [07/Aug/2021:16:29:07 -0400] [Job 30] GPL Ghostscript 9.26: Unrecoverable error, exit code 1
```

**Comment by wknans** [comment]
hello, 
sory my english bad

i have installed cups on stb hg680
error_log 
root@arm-64:/var/log/cups# tail error_log
D [02/Mar/2023:07:44:45 +0700] [Job 1] printer-state-reasons=hplip.plugin-error
E [02/Mar/2023:07:44:48 +0700] [Client 74] Unable to encrypt connection: A TLS fatal alert has been received.
E [02/Mar/2023:07:51:39 +0700] [Client 76] Unable to encrypt connection: A TLS fatal alert has been received.
E [02/Mar/2023:07:51:39 +0700] [Client 77] Unable to encrypt connection: A TLS fatal alert has been received.
E [02/Mar/2023:07:51:56 +0700] [Client 79] Unable to encrypt connection: A TLS fatal alert has been received.
E [02/Mar/2023:07:52:16 +0700] [Client 80] Unable to encrypt connection: A TLS fatal alert has been received.
E [02/Mar/2023:07:53:32 +0700] [Client 81] Unable to encrypt connection: A TLS fatal alert has been received.
E [02/Mar/2023:07:53:35 +0700] [Client 82] Unable to encrypt connection: A TLS fatal alert has been received.
E [02/Mar/2023:07:53:36 +0700] [Client 84] Unable to encrypt connection: A TLS fatal alert has been received.
E [02/Mar/2023:07:53:47 +0700] [Client 86] Unable to encrypt connection: A TLS fatal alert has been received.
