### ISSUE TITLE
Disable auto add usb printers

### ISSUE THREAD

**Issue by nikolozij** [apple/cups#5943]
How can I disable auto add local usb printers? I need to add a usb printer with a manually entered name.

**Comment by michaelrsweet** [comment]
@nikolozij What operating system?

AFAIK, there is no way to disable auto-add on macOS. I'm not sure about Linux (varies based on the distro...)

**Comment by nikolozij** [comment]
I use Ubuntu 18.04, CUPS 2.2.7

**Comment by michaelrsweet** [comment]
OK, the [cups-filters](https://github.com/OpenPrinting/cups-filters) project is probably the best place to start for this. There is a udev rule that gets installed to auto-add USB printers on most Linux distros, including Ubuntu.

**Comment by zdohnal** [comment]
@nikolozij Uninstalling system-config-printer-udev should do the trick.

**Comment by nikolozij** [comment]
@zdohnal this is a suitable solution, thanks.
