### ISSUE TITLE
2.3.4 Not communicating properly with Web Browser printing

### ISSUE THREAD

**Issue by BradyBriscoe** [apple/cups#5945]
When using a printer (DYMO 450) that is setup VIA 2.3.4 CUPs that was bundled with the latest MACOS Big Sur 11.5.X, the printer drivers and/or settings are not translating to the Web Browser print dialogs properly. 

When in CUPs, the list of Media Sizes appear correct as they should. However, when choosing a Paper Size from the Web Browser's Print Preview, the sizes to choose from are not correctly displayed according to the list of sizes provided by the printer driver. 

Browsers be used: 
Chrome, Opera, FireFox

Here are some screen shots for context. 

CUPs properly displaying:
![Image 8-12-21 at 8 46 AM (1)](https://user-images.githubusercontent.com/17442835/129756720-2c20ced4-bcd2-4cb1-88d9-9670096bfda5.JPG)

Web Browser displaying wrong:
![Image 8-12-21 at 8 43 AM (1)](https://user-images.githubusercontent.com/17442835/129756805-0b348ac7-b769-4dfd-b4e6-8e43671ef1a2.JPG)

We are trying to determine if this is an issue that came about with 2.3.4 CUPs or if the printer manufacture (DYMO) needs to update their printer driver to work with 2.3.4. Of course DYMO says its not a problem with their driver.

**Comment by michaelrsweet** [comment]
This is Google not using the standard print dialog on macOS. Please report this issue to the Chrome folks...
