### ISSUE TITLE
Some characters are not printed correctly

### ISSUE THREAD

**Issue by YuGiOhJCJ** [apple/cups#5959]
Hello,
I am on Slackware 14.2 (64-bit) and I am using:
- cups-2.3.3op2
- cups-filters-1.28.10
- qpdf-10.3.2

I try to print a PDF file `lp myfile.pdf` but the result is a sheet with some characters replaced with a square symbol.
The PDF file characters are shown correctly on `xpdf` and `mupdf` PDF viewers, the problem is just when I print with my printers (tested on two different printers).

Do you know how to fix that please?

Thank you.
Best regards.

**Comment by YuGiOhJCJ** [comment]
I found a workaround.
Instead of using the `lp myfile.pdf` command I am using the `xpdf myfile.pdf` command then I click on File > Print... > Print.
The result is perfect.
However, I would like to use the `lp` command because I prefer command line tools.

How can I get the same result than `xpdf` with the `lp` command please?

**Comment by michaelrsweet** [comment]
@YuGiOhJCJ The PDF filter used on your OS is part of the [cups-filters](https://github.com/OpenPrinting/cups-filters) project. Unfortunately, I am unable to move this issue to that project (different ORG) so I'll have to ask you to re-file it there.

Thanks!
