### ISSUE TITLE
IPP Compliance tests are failing when I run the test suite locally.

### ISSUE THREAD

**Issue by AtariDreams** [apple/cups#5967]
Unable to open listen socket for address - Address already in use. Happens when I run the test suite more than once. The first time, the tests pass, but running it again subsequently without rebooting the Mac causes the IPP 4.2, 4.3, and 4.4 tests to fail due to that error message. It happens on the OpenPrinting cups repo too.

**Comment by michaelrsweet** [comment]
@AtariDreams Is the old test cupsd still running?

**Comment by AtariDreams** [comment]
Yeah I think so

**Comment by michaelrsweet** [comment]
That's why then. The test script shuts the test server down, but if you run the server separately or the test script fails then you might be left with a copy running.
