### ISSUE TITLE
HP Printer is not supported on hplip-3.21.8

### ISSUE THREAD

**Issue by SirrCasper** [apple/cups#5968]
So I have a Problem, I wanna use my old USB HP Printer as a Network Printer with cups. Its a HP Deksjet F2180. So i checked the Driver Image "hplip-3.21.8" and found him. Added on Version 1.7.4. So i startet my little Raspberry Pi Zero w and installed cups and it all works. I  try to ad a neu Printer in the web interface but my Printer was not there. I choosed  HP and searched for Deskjet F2180 but there was no F2180. Why is it supportet in the image but does not shot up in the web interface? Can someone have an explanation?

Can I install a separate Linux Driver for my F2180? 

Checking for my Printer 
https://developers.hp.com/hp-linux-imaging-and-printing/supported_devices/index

**Comment by michaelrsweet** [comment]
@SirrCasper Unfortunately, we are able to provide support for third-party drivers here. Have you tried contacting HP?
