### ISSUE TITLE
airprint client sends get-printer-attributes request for printer-state-reansons every 20 seconds

### ISSUE THREAD

**Issue by Ariesfish** [apple/cups#5969]
I set up an airprint server, and use my macOS high sierra to airprint.
After Print-Job finished, I find that client will send get-printer-attributes request to server for getting printer-state-reansons every 20 seconds.
Is the client mean to do this state check?
User-Agent: CUPS/2.2.5 (Darwin 17.7.0; x86_64) IPP/2.0

But when user-agent is CUPS/2.3.4, it will not do this check. When Print-Job is finished, the communication just finished.

**Comment by michaelrsweet** [comment]
@Ariesfish Without more context I can't say, but generally the backend will continue to monitor the printer until the job is printed. Newer versions of CUPS recognize when they have printed to another server and will allow the local cupsd to continue on to the next job without waiting.
