### ISSUE TITLE
Brother DCP-L2550DW number of copies > 1 doesn't work

### ISSUE THREAD

**Issue by ineuw** [apple/cups#6035]
I am using Linux Mint Cinnamon 20.3 64bit with the printer on a home network. Everything is the latest update. Every other feature of the printer works fine, recto verso, etc. but only a single copy.
 
I spent days researching the issue without any working solution, and I tried everything. There are many identical complaints about cups with various makes and models of printers.

**Comment by cmilitzer** [comment]
I have a MacBook Air M1,2020 OS 12.3.1 Monterey and am having the same issue with my Brother HL-L2350DW Printer.  
Currently the only work around I found was downloading the Brother iPrint & Scan app from the app store.  All print jobs have to be first saved as a PDF then uploaded to this app to print ... not cool.

**Comment by ineuw** [comment]
@cmilitzer. The solution was posted in Linux Mint [(https://forums.linuxmint.com/viewtopic.php?f=51&t=301319&p=2167121#p2167121)]

**Comment by ineuw** [comment]
This is a CUPS issue, not just Apple.
