### ISSUE TITLE
"lpoptions -l" doesn't highlight default page size anymore

### ISSUE THREAD

**Issue by AngusMcGyver** [apple/cups#6067]
Hi,
I recently did an upgrade of Ubuntu 20.04 to 22.04 and with this upgrade cups from 2.3.1 to 2.4.1

Since the upgrade the default page size isn't highlighted by an * anymore via `lpoptions -l`.

cups 2.4.1:
```
# /usr/bin/lpoptions -p HP-LJ-M476dw -l

PageSize/Media Size: Letter Legal Executive FanFoldGermanLegal 4x6 5x8 A4 A5 A6 B5 4x6.Photo Oficio 195x270mm 184x260mm 7.75x10.75 Postcard DoublePostcardRotated Env10 EnvMonarch EnvISOB5 EnvC5 EnvDL Custom.WIDTHxHEIGHT
Duplex/Two-Sided: *None DuplexNoTumble DuplexTumble
InputSlot/Paper Feed: *Auto Tray1 Tray1_Man Tray2 Tray3
HPOption_Duplexer/Duplex Unit: *True False
HPOption_Tray3/Tray 3: *False True
…
```
cups 2.3.1:
```
# /usr/bin/lpoptions -p HP-LJ-M476dw -l

PageSize/Media Size: Letter Legal Executive FanFoldGermanLegal 4x6 5x8 *A4 A5 A6 B5 4x6.Photo Oficio 195x270mm 184x260mm 7.75x10.75 Postcard DoublePostcardRotated Env10 EnvMonarch EnvISOB5 EnvC5 EnvDL Custom.WIDTHxHEIGHT
Duplex/Two-Sided: *None DuplexNoTumble DuplexTumble
InputSlot/Paper Feed: *Auto Tray1 Tray1_Man Tray2 Tray3
HPOption_Duplexer/Duplex Unit: *True False
HPOption_Tray3/Tray 3: *False True
…
```
Notice the difference between `A4` and `*A4` in the first line of each output. The default marking for other options works just fine, only the pagesize is not working correctly.

In the ppd file the default page size seams okay and it also change there, if switched in GUI to another value
```
# cat /etc/cups/ppd/HP-LJ-M476dw.ppd | grep DefaultPageSize
*DefaultPageSize: A4
```

**Comment by debiantriage** [comment]
Hello AngusMcGyver,

You have posted in the wrong place. Ubuntu 22.04 does not use Apple CUPS.
You want https://github.com/OpenPrinting/cups/issues.

**Comment by AngusMcGyver** [comment]
Ahh i'm sorry, wrong browser tab... :facepalm:
