### ISSUE TITLE
how to create a backend that can be CUPS recognize?

### ISSUE THREAD

**Issue by tthnu** [apple/cups#6195]
I've created a new backend which is based on the [cups-pdf](https://www.cups-pdf.de/documentation.shtml) but with fewer code , only keeping the main function and triming the code which is used to generate config file.

After compiling using **_gcc -O9 -s cups-pdf.c -lcups_** and copying cups-mybackend binary to **_/usr/lib/cups/backend/_**, also copying the ppd file to **_/usr/share/ppd/cups-mybackend_**, CUPS cannot recognize this new backend.(**_sudo lpinfo -v_** has nothing about cups-my-backend and it also couldn't be selected in AddPrinter in WEB .)

So how should I do to let CUPS know this new backend?

**Comment by jsmeix** [comment]
When you use Linux,
you may have a look here:
https://en.opensuse.org/SDB:Using_Your_Own_Backends_to_Print_with_CUPS

When you use macOS I don't know.
I think in macOS CUPS runs within some kind of "sandbox"
so user-made CUPS backends may not be allowed by default?
But this is only a blind guess.

Current CUPS upstream is no longer here but under
https://github.com/OpenPrinting
at
https://github.com/OpenPrinting/cups

When you use macOS this place here could be still
the right place for CUPS on macOS - I don't know?

**Comment by tthnu** [comment]
> When you use Linux, you may have a look here: https://en.opensuse.org/SDB:Using_Your_Own_Backends_to_Print_with_CUPS
> 
> When you use macOS I don't know. I think in macOS CUPS runs within some kind of "sandbox" so user-made CUPS backends may not be allowed by default? But this is only a blind guess.
> 
> Current CUPS upstream is no longer here but under https://github.com/OpenPrinting at https://github.com/OpenPrinting/cups
> 
> When you use macOS this place here could be still the right place for CUPS on macOS - I don't know?

Thanks for your reply!

I've read some manuals you provide and source codes of different backend and found that any new backend MUST report its information through stdout with the form "device_scheme, device_uri, device_make_and_model, device_info, device_id, device_location" or could call [cupsBackendReport](https://github.com/apple/cups/blob/a8968fc4257322b1e4e191c4bccedea98d7b053e/cups/backend.c#L86) function instead. CUPS will soon recognize this new backend after reporting operation.
