### ISSUE TITLE
Option to have the pid of cupsd

### ISSUE THREAD

**Issue by michaelrsweet** [apple/cups#805]
Version: 1.1.20
CUPS.org User: sebest.ovibes

it would be nice that cupsd store his pid in a file like /var/run/cupsd.pid.
It's usefull for start/stop scripts of linux distributions or for monitoring software like monit (http://www.tildeslash.com/monit/).
thanx

**Comment by hollaho** [comment]
Just in case someone else also runs into this (IMHO stupid) "policy decision" not to create and support pid files, which are simply expected by other packages / programs to exist.

Use a wrapper script and force creation of a pid file. I used start-stop-daemon in openrc-run environment:

`start() {
        ebegin "Starting ${SVCNAME}"
        start-stop-daemon --start --exec /usr/sbin/cupsd -b -m --pidfile /run/cups/${SVCNAME}.pid -- -C /etc/cups/${SVCNAME}.conf -s /etc/cups/cups-files.conf
        eend $?
}`

Notice the -b -m options, which force the creation of the pid file without cupsd knowing or contributing to it. With this pid file it is now possible to monitor cupsd with monit or other tools.
